- documentation/manual/detailedTopics/production/ProductionConfiguration.md
- framework/src/play/src/main/scala/play/core/server/NettyServer.scala
the http packets are logs when:
- the application is started with -Dhttp.netty.log.wire=true
- the org.jboss.netty.handler.logging.LoggingHandler logger
is set to DEBUG
backport 2cc705719742ede73a1fa1b8ad0b83438ea30c57
> log http wire

- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
Currently OptionReads delegates to format.reads without checking if the value exists and ignores the error returned by the format.
Say I have:
`case class User(name: Option[String])`
Then `{ "name": "Drew" }` is a valid JSON, so is `{ }`, but `{ "name": 12 }` is not. Currently, OptionReads will return JsSuccess(None) when reading `{ "name": 12 }` instead of an error. This PR fixes that.
> OptionReads should validate JSON value if it exists

- framework/src/play/src/main/java/play/http/DefaultHttpErrorHandler.java
- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
This would be useful to us because we'd like to add some additional tagging data that we could process in Sentry:
https://github.com/getsentry/raven-java/tree/master/raven-logback#additional-data-and-information
See also https://github.com/guardian/membership-frontend/pull/31
> Make it easy to override the logging of server errors

- framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/impl/EnumeratorPublisher.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/EnumeratorPublisherSpec.scala
This ensures that the underlying enumerator is cleaned up properly.
> Attach Done iteratee when EnumeratorPublisher is cancelled

- framework/src/iteratees/src/main/scala/play/api/libs/iteratee/CharEncoding.scala
- framework/src/iteratees/src/test/scala/play/api/libs/iteratee/CharEncodingSpec.scala
While building a few `Enumeratees` I ran into an obvious issue: **text-based formats deal in *characters*, not *bytes*.**
Translating between the two is not easy, as there are dozens of reasonably common encodings.
I made a couple `Enumeratee`s to encode and decode between `Array[Byte]` and `String` (I could have used `Array[Char]` instead of `String`, but the latter is more common in APIs).
They use Java's [CharsetEncoder](http://docs.oracle.com/javase/6/docs/api/java/nio/charset/CharsetEncoder.html) and [CharsetDecoder](http://docs.oracle.com/javase/6/docs/api/java/nio/charset/CharsetDecoder.html) to incrementally encode and decode, handling cases where characters are split across chunks.
This allows for broad support, and now my text-based `Enumeratee`s can be used on any encoding Java …
> Add Enumeratees for character encoding and decoding

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/Expect100ContinueSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
> Stop Akka HTTP processing the request body twice

- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
- framework/src/play/src/test/scala/play/api/controllers/AssetsInfoSpec.scala
- framework/src/play/src/test/scala/play/api/controllers/AssetsSpec.scala
Use a regex to recognize the date format and discard any extra trailing information. Then use one of two date formats to do the parsing. See #3569.
This handles the non-standard IE trailing attributes and the non-standard Chrome header reported with Windows 8.1.
Cc @gmethvin, @Cody-SDLGov.
> Parse non-standard If-Modified-Since date format

- framework/project/Dependencies.scala
Dependency update should be fine now: http://search.maven.org/#artifactdetails%7Corg.javassist%7Cjavassist%7C3.19.0-GA%7Cbundle
This **hopefully** fixes #3374
> Updated Javassist to 3.19.0-GA

- framework/project/Dependencies.scala
- framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala
This fixes several issues:
* conf/ and test/resources/ are now on the Eclipse classpath
* test/resources/ no longer breaks Eclipse project when added to Eclipse classpath
* Eclipse output and SBT output no longer collide by default causing strange build errors
> Upgrade to sbteclipse 3.0.0 which has several bug fixes for issues reported by Play users

- framework/src/play-integration-test/src/test/scala/play/it/http/JavaRequestsSpec.scala
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
- framework/src/play/src/test/java/play/mvc/CallTest.java
Actually ends up being less code if we can assume that the map is case insensitive in our `getHeader` implementation.
> Fix case sensitivity in Java headers map

- documentation/manual/detailedTopics/configuration/ws/LooseSSL.md
The actual setting is `ws.acceptAnyCertificate`.
Resolves #3791
> Fix setting name to accept any certificate in the documentation

- framework/src/build-link/src/main/java/play/core/Build.java
- framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
- framework/src/run-support/src/main/java/play/runsupport/classloader/ApplicationClassLoaderProvider.java
- framework/src/run-support/src/main/java/play/runsupport/classloader/DelegatingClassLoader.java
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
- framework/src/sbt-plugin/src/main/scala/PlayRun.scala
@corruptmemory @jroper I refactored out a couple of classloader classes a little while back from Play's run code into build-link. The run-support library didn't exist yet, but seems like it could be a better place for them to go. In fact another one of the classloaders is already there - the AssetsClassLoader. What do you think?
> Move classloaders from build-link to the new run-support library

- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
If you had previously defined a custom value for javascriptUnbind then it gets overwritten when doing a transform. This is because the transform function calls `new QueryStringBindable[B]` which sets the javascriptUnbind method to the default `def javascriptUnbind: String = """function(k,v) {return encodeURIComponent(k)+'='+encodeURIComponent(v)}"""`.
This fixes that by passing through the custom value of javascriptUnbind.
> Fix bug with javascript unbind and transform

- framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala
- framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala
The Etag value used by the `Cached` class include an unquoted date string containing a comma. This is parsed by the browser as a list of headers, so Chrome sends the first token of the string for If-None-Match. For example, chrome requests "If-None-Match:Sun" for the header: "ETag:Sun, 20 Dec 2015 20:11:43 GMT".
> Commas in etag break browser caching

- framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Iteratee.scala
- framework/src/iteratees/src/test/scala/play/api/libs/iteratee/IterateesSpec.scala
Fixes #3855.
The closure inside Iteratee.flatMap could call itself recursively, leading to a StackOverflowError when Cont is flatMapped thousands of times. An unresolved problem is the fact that this closure can still grow so large that it could exhaust memory. This is hard to avoid because there is no easy way in Scala to optimize recursive function composition.
> Use trampoline to avoid Cont.flatMap stack overflows

- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
I don't think "bindings" was meant to be used twice
"Convert the given bindings Play bindings to a Guice module"
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala#L95
> Typo in code comment

- framework/src/play/src/main/scala/play/api/mvc/Action.scala
Fixed "than" in:
This is the main method <strong>than</strong> an ActionFilter has to implement.
to "that":
This is the main method <strong>that</strong> an ActionFilter has to implement.
> Corrected a simple misspelling in the API documentation

- documentation/manual/working/javaGuide/main/http/JavaErrorHandling.md
- documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
The documentation mentions `play.application.errorHandler` but the code uses `play.http.errorHandler`
> [2.4.0-M2] documentation for custom ErrorHandler wrong

- documentation/manual/detailedTopics/production/HTTPServer.md
Modified the example nginx reverse proxy config to add an X-Forwarded-Proto header instead of X-Scheme.
> Document X-Forwarded-Proto header for nginx

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
Akka HTTP doesn't let you construct HTTP entities with a streamed body and a Content-Length of 0. A special constructor needs to be used.
> Use Akka HTTP's HttpEntity.empty when Content-Length is 0

- framework/src/iteratees/src/test/scala/play/api/libs/iteratee/EnumerateesSpec.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Added Results.dechunkWithTrailers method to support this.
> Add chunked encoding trailer support to Akka HTTP backend

- framework/project/Build.scala
Since Play's tests are already configured to run with a concurrency restriction of 1, tagging the scripted task with Test ensures scripted also doesn't execute at the same time.
> Ensure scripted tests don't run in parallel

- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSClient.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSClient.java
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/openid/WsMock.scala
If you look at the Java API:
https://github.com/playframework/playframework/blob/master/framework/src/play-java-ws/src/main/java/play/libs/ws/WSClient.java
and the Scala API:
https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala#L22
then you can see the WSClient doesn't have a defined close() method.  
This means that when users try to create a WSClient instance outside of the plugin lifecycle, they have to do
```
val close(wsClient:WSClient) = wsClient.underlying[AsyncHttpClient].close() 
```
This is inconvenient, and entirely avoidable.
> WSClient should have close() in public API

- framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala
As explained in the related ticket https://github.com/playframework/playframework/issues/3818, sbteclipse should already be taking care of
adding the scala lib to the Eclipse classpath entries, and therefore the Play
Eclipse sbt plug-in should not need to duplicate the work.
Review by @jsuereth
> Don't add the scala lib to the Eclipse classpath of a Play Java proj.  Fix #3818

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
`Option` offers a `toList`. Calling `toSeq` requires an implicit
to be applied (specifically, `Option.option2Iterable`).
(I know this is sort of a ridiculous PR. In fact, feel free to reject it if you feel so :-))
> Avoid the extra implicit conversion for `Option[T] => Seq[T]`

- framework/project/Build.scala
Only compile (or scaladoc compile) one at a time to avoid scala.reflect concurrency issues from scala pickling.
> Restrict compilation of fork run protocol projects

- framework/src/play/src/main/scala/play/api/libs/MimeTypes.scala
The Mimetypes.scala mapping of rtf to text/richtext is probably not the best mapping by extension. While extension is probably not the best indicator, my suspicion would be a much larger number of files with .rtf mean the application/rtf type.
http://en.wikipedia.org/wiki/Rich_Text_Format
> Mimetypes.scala should map rtf to application/rtf instead of text/richtext

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
As described in http://www.w3.org/Protocols/rfc2616/rfc2616-sec4.html#sec4.4,
both 204 and 304 responses must not include a message-body. This requirement
was not enforced in Play, but the built-in instances for both 204 and 304
responses (see `play.api.mvc.Results.NoContent` and
`play.api.mvc.Results.NotModified`) are constructed with an empty body. Hence,
the above mentioned requirement was already respected (though not enforced)
when using these values.
This commit enforces the requirement, returning an empty body for both 204 and
304 responses (whether a message body is provided or not).
Ticket #3899 requested the `Content-Length` header to never be included in a
304 result. The specification for 304 (see
http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.3.5) only states …
> Don't include body and Content-Length in 204 and 304 responses.  Fixes #3899

- documentation/manual/working/scalaGuide/main/json/ScalaJsonInception.md
- framework/project/Build.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala
I would suggest to implement them for:
java.time.LocalDateTime
java.time.LocalDate
Anything else which is relevant by default?
Have them implemented locally and would be willing to provide a pull request.
> Json DefaultReads/Writes should provide Reads/Writes for relevant JDK8 java.time.*

- framework/src/play/src/main/scala/play/api/Logger.scala
This avoids multiple applications configuring the logger simultaneously, which can cause a lot of extra logging from logback and sometimes concurrent modification exceptions.
> Synchronize when configuring the logger globally

- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonValidSpec.scala
I understand that we don't necessary want to parse every possible iso format, but this one is particularly important because it is what browsers produce:
```js
var x = new Date()
x.toISOString()
> "2014-12-29T19:16:09.598Z"
```
Here's the issue: 
```scala
scala> Reads.IsoDateReads.reads(Json.toJson("2014-12-04T10:00:00Z"))
res14: play.api.libs.json.JsResult[java.util.Date] = JsSuccess(Thu Dec 04 03:00:00 MST 2014,)
scala> Reads.IsoDateReads.reads(Json.toJson("2014-12-29T19:16:09.598Z"))
res16: play.api.libs.json.JsResult[java.util.Date] = JsError(List((,List(ValidationError(error.expected.date.isoformat,WrappedArray(yyyy-MM-dd'T'HH:mm:ssz))))))
```
> Reads.IsoDateReads doesn't work with dates including fractions of a second

- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
A simple fix to avoid creating a separate Locale object every time.
> Fix performance problem with toLocale by switching to lazy val

- framework/src/sbt-plugin/src/main/scala/PlayRun.scala
- framework/src/sbt-plugin/src/main/scala/PlaySettings.scala
This was lost in the process of moving from shell script to
activator. This fixes issue #3664.
> Add back activator stop command

- framework/src/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play/src/main/scala/play/api/Routes.scala
I have Play 2.3.6 Java app. In it I have my own error handler for handling bad requests, method looks like:
public Promise<play.mvc.Result> onBadRequest(RequestHeader request, String error {
Logger.debug("400 error: " + error + ", " + request.path() + ", " + request.remoteAddress());
return Promise.<play.mvc.Result> pure(badRequest(views.html.error404.render()));
}
When an error occurs, instead of my own error page I am getting standard error page. It turns out problem is in request.path() method which is supposed to return string. But if the URL is incorrect it throws an exception and breaks my error handling code. 
An example of bad request causing it looks like this: https://www.playframework.com/documentation/2.3.x/Home%
(with % at the end of url).
> RequestHeader.path() is unsafe

- framework/src/play-test/src/main/java/play/test/Helpers.java
- framework/src/play/src/main/java/play/mvc/HandlerRef.java
- framework/src/play/src/main/scala/play/api/mvc/Action.scala
This PR is an alternative to https://github.com/playframework/playframework/pull/3929
> Extend the HandlerRef interface such that we no longer need to cast it to another type when using it

- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/WebSocketHandler.scala
IE11 send pong events every ~20 seconds which the server should ignore.
Previously Play responded with an error which causes IE11 to close the websocket.
https://tools.ietf.org/html/rfc6455#section-5.5.3
>A Pong frame MAY be sent unsolicited.  This serves as a unidirectional
heartbeat.  A response to an unsolicited Pong frame is not expected.
Fixes #2992
> Ignore unsolicited WebSocket Pong frames

- framework/src/play-integration-test/src/test/scala/play/it/http/JavaRequestsSpec.scala
- framework/src/play-java/src/test/scala/play/data/DynamicFormSpec.scala
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/main/scala/play/core/j/JavaGlobalSettingsAdapter.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
- framework/src/play/src/main/scala/play/core/system/RequestIdProvider.scala
- framework/src/play/src/test/java/play/mvc/CallTest.java
This adds a RequestBuilder to make Requests and Contexts easier to create in tests
There are some places in the Play tests where the RequestBuilder could save some code. E.g. it'd probably save 100 lines of code in CallTest since TestRequest and TestCookies could both be deleted. However, I didn't use if there since it would create a circular dependency to have the main Play project use the Play test project.
> Add a RequestBuilder to make it easier to construct a request in Java tests

- framework/src/sbt-plugin/src/main/scala/PlayRun.scala
Fix #3484 by using `resolvedScope` when calling `Project#runTask`.
This can be trivially backported to 2.3.x.
---
There are other places where it seems there may be similar errors, but I am not well acquainted with them.
I was a little surprised at how frequently `Project#runTask` is used.
> Fix #3484: mysubproject/run doesn't work

- framework/src/sbt-plugin/src/main/scala/PlaySettings.scala
- framework/src/sbt-plugin/src/main/scala/play/Project.scala
Otherwise the default main class selection will be used, which relies on discovered main classes from compile. It also means that compile was being triggered before dev mode run, which is different from previous behaviour of only triggering compile on application load.
> Scope mainClass setting to run task in server plugins

- framework/src/sbt-plugin/src/main/scala/PlayRun.scala
Backport of #3970. Use resolvedScope when calling Project.runTask.
> Fix subproject/run (2.3.x)

- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
- framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
Fixes https://github.com/playframework/playframework/issues/4003
Given the following contrived example:
```
import play.api.mvc.QueryStringBindable
import play.api.mvc.QueryStringBindable.bindableSeq
val values = Seq("i", "once", "knew", "a", "man", "from", "nantucket")
val params = Map("q" -> values)
implicit val brokenBinder: QueryStringBindable[String] = {
new QueryStringBindable.Parsing[String](
{ x =>
if (x == "i" || x == "nantucket") x else sys.error(s"failed: ${x}")
},
identity,
(key, ex) => s"failed to parse ${key}: ${ex.getMessage}"
) 
} 
val brokenSeqBinder = implicitly[QueryStringBindable[Seq[String]]]
```
`brokenSeqBinder.bind("q", params)`, will output `Some(Right(Seq("i", "nantucket")))`
I would have expected the result to be an error message detailing what went wrong.
> fix bindable for list and seq so it doesn't swallow errors

- framework/src/play-test/src/main/java/play/test/Helpers.java
Right now you have to do:
Helpers.route(Helpers.fakeRequest(controllers.routes.Application.index()));
It'd be nicer to be able to do:
Helpers.route(controllers.routes.Application.index());
> Add some more test helper routing methods

- framework/project/Dependencies.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaStreamsConversion.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/Build.scala
- framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/project/Build.scala
- framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHttpServerSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala
- framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/SecureFlagSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-server/src/main/scala/play/core/server/ServerStart.scala
- framework/src/play-server/src/test/scala/play/core/server/ServerStartSpec.scala
- framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala
- framework/src/play-test/src/main/java/play/test/TestServer.java
- framework/src/play-test/src/main/scala/play/api/test/TestServer.scala
- framework/src/play/src/main/java/play/libs/Scala.java
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/Build.scala
A few code changes were needed because of Akka API changes.
> Upgrade to Akka HTTP 1.0-M4

- framework/project/Build.scala
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/build.sbt
A couple of small fixes with the new cross build.
With the default scala version now 2.11, scripted tests were still running against 2.10, but 2.10 artefacts may not have been published locally. This may have been why 2.10 was always the default. I've updated to use the play project scala version, rather than the sbt plugin scala version.
The development projects also need to be cross built for fork run.
There's also one awkward point about running the fork run plugin scripted tests against scala 2.11 -- it starts up an sbt server which won't see the scala version system property. For now I've just made the default 2.11 for it to work. A more complete fix would write the scala version to a file as needed, or something like that.
> Scripted tests and new cross build

- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/impl/EnumeratorPublisher.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/EnumeratorPublisherSpec.scala
This partly fixes an Akka HTTP integration test. We now close the stream properly when an error occurs, but unfortunately Akka HTTP strips out the Content-Length on the result so the WS client doesn't realise that the stream closed early. I'm talking to the Akka team now about whether Akka HTTP can support forcing streams to close even if they have a known length or are chunked.
> Handle Enumerator errors in EnumeratorPublisher

- framework/project/Build.scala
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/build.sbt
- templates/build.sbt
The templates build has a project reference on play-ws which doesn't work with a 2.11 default version. The templates build also uses PlayVersion.current, which it gets via the project reference.
Just a quick fix to get other builds working again.
> Revert to 2.10 as default scala version

- framework/src/play-test/src/main/java/play/test/Helpers.java
- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
- framework/src/play/src/main/java/play/mvc/Http.java
RequestBuilder allows specifying a request body already, so it is confusing to have helpers that make you specify a request body a second time
This is also a big improvement because it allows these helper methods to be used with all types of bodies instead of just `byte[]`
> Specify the request body only once in Helpers

- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonValidSpec.scala
The previous implementation would allow floating point values
to be parsed as integers. This commit validates the BigDecimal by
testing that the scale is smaller than 1. This would mean that the
number represented has no decimal points.
> Validate integer value in IntReads. Fixes #4032

- framework/src/play/src/main/scala/play/api/data/validation/Validation.scala
- framework/src/play/src/test/scala/play/api/data/validation/ValidationSpec.scala
To quote @jroper:
> "At the end of the day, if you want to validate an email address, the
> only real way to do it is to send an email to it with a secret token.
> For this reason, false positives are not a big problem, what is a big
> problem is false negatives, ie issues like this very bug."
> return to using HTML5 regex for email verification. Fixes #4022

- framework/project/Build.scala
The branch names had a trailing newline, which was invalid in the source jar manifests.
> Trim snapshot branch name for omnidoc

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Default timeout for a request is 120 seconds as per the defaults
in the code. Docs said default was None for "stream consume behavior."
Changed docs to reflect code, also chose different wording on explaining
`ws.timeout.connection`.
> Fix discrepancy between docs and code for WS timeout. Issue #4059

- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
- framework/src/play/src/test/java/play/mvc/RequestBuilderTest.java
On `Http.Request`, the function `.setUsername` could be deprecated and a `.withUsername` (returning an updated instance of the request) added.
> Immutable username on HTTP request

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
This required a reasonably big refactor of the result streaming code. The streaming logic in ServerResultUtils now gets passed a RequestHeader so it can check the HTTP version and the request Connection header.
This commit fixes the main remaining Akka HTTP integration test.
> Allow connections to be closed in Akka HTTP when a Content-Length is set

- framework/src/sbt-plugin/src/main/scala/PlayCommands.scala
- framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala
- framework/src/sbt-plugin/src/main/scala/play/Project.scala
Fix ugly workaround for sbteclipse not setting EclipseKeys.withBundledScalaContainers correctly by default
> Remove mainLang which wasn't accurately named or typesafe

- documentation/manual/scalaGuide/main/async/ScalaWebSockets.md
'discreet' should be 'discrete', I guess.
> Fix typo in ScalaWebSockets.md

- documentation/manual/detailedTopics/assets/AssetsLess.md
Setting the CSS color property with a font-size variable didn't make sense.
> Create a more useful Bootstrap example

- documentation/manual/detailedTopics/configuration/code/ThreadPools.scala
- documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala
- documentation/manual/working/scalaGuide/main/async/code/ScalaComet.scala
- documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/project/Dependencies.scala
- framework/src/iteratees/src/test/scala/play/api/libs/iteratee/CharEncodingSpec.scala
- framework/src/play-cache/src/test/scala/play/api/cache/SerializableResultSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/DriverRegistrationSpec.scala
- framework/src/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/EnumeratorPublisherSpec.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/FuturePublisherSpec.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/IterateeSubscriberSpec.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/PromiseSubscriberSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/SystemPropertiesSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/debug/DebugConfigurationSpec.scala
- framework/src/play/src/test/scala/play/core/ClosableLazySpec.scala
Since Playframework has a policy of avoid upgrades in minor versions, I want to help with dependency updates before the release of 2.4.0.
This PR updates specs2 without removing the use of any API deprecated in version 3.x of specs2. That way I can keep this PR simple and small and deprecated APIs can be gradually removed in the future.
> Updates specs2 to version 3.1

- framework/project/Dependencies.scala
- framework/src/play-java/src/main/java/play/libs/EventSource.java
- framework/src/play-java/src/main/java/play/libs/Jsonp.java
- framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
- framework/src/play-json/src/test/scala/play/libs/JavaJsonSpec.scala
Jackson [release notes](https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5) states that:
> It is a "minor" release following 2.4, meaning that it adds new functionality but be backwards compatible with earlier 2.x releases.
I just inspect the code to see if there are uses of deprecated APIs and had to do a small change to fix a compile problem.
> Upgrade jackson to version 2.5.1

- framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
Fix issue #4098 by porting code from #2231
> Fix for ticket Wrong RequestHeader is being passed into ErrorHandler's nClientError method

- documentation/manual/detailedTopics/assets/Assets.md
Without it, the asset pipeline won't work, for instance it won't trigger fingerprinting paths to be rendered in templates.
I've spent roughly 20 hours over several attempts trying to figure out why both fingerprinting and using minified versioned wasn't working until I finally found a few references about making sure to write "file: Asset" between the mailing list and stackoverflow. I think this should be explicitly pointed out in the docs for future readers.
> docs: Add a note on declaring file: Asset

- documentation/manual/releases/Migration24.md
I didn't look closely enough when I originally made the change and I put the `FakeRequest`/`RequestBuilder` portion under a dependency injection section that wasn't relevant. This is way makes the migration guide clearer.
> Improve migration guide for testing changes

- documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/CustomApplicationLoader.java
- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
I tried passing in my own Guice `Module` using the `GuiceApplicationBuilder`, but it's really not easy. We should make it easier to do that and then update these docs with an example showing how. I thought I'd at least send in this since it should provide a placeholder for better docs
> Placeholder scaffolding for application loader documentation

- framework/project/Dependencies.scala
I thought about doing small PRs to upgrade each dependencies, but my guess is that it would add too much overhead for you guys. If this PR does to many upgrades, please, let me know.
ps.: I know that this is not a very useful PR, but my guess is that I can help with the mundane work while you guys handle more complicated issues (and while doing these upgrades, I can get more familiar with Play source code).
-------------------
Upgrade dependencies which did not required source changes:
1. SpringFramework to version 4.1.5.RELEASE
2. SnakeYAML to version 1.15
3. Tomcat Servlet API to version 8.0.20
4. Joda-Time to version 2.7
5. SLF4J to version 1.7.10
6. Logback to version 1.1.2
7. Commons Codec to version 1.10
8. Commons IO to version 2.4
9. EhCache to version 1.6.10
10. Hibernate …
> Upgrade dependencies

- framework/project/Build.scala
If I upgrade an existing Play project to Play 2.4, and it was previously imported in IntelliJ with the SDK set to Java 1.6, then I reimport it into IntelliJ using IntelliJ's built in sbt support, IntelliJ will use Java 1.6 to run sbt to import it, which will fail with an error saying there was a binary compatibility, but that error is truncated in IntelliJ's UI, so you can't see that it's an unsupported major version of 52, so even someone that knows what that means and how to solve it can't immediately solve the problem.
A simple solution would be for us to target the Java projects that the sbt plugin depends on such as build link, play exceptions etc at Java 1.6.  We don't need Java 1.8 for them anyway.
> sbt plugins should support Java 1.6

- documentation/manual/releases/Migration24.md
- documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/CompileTimeDependencyInjection.scala
- framework/src/play/src/main/scala/play/api/routing/Router.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala
It should be generated in `router.Router` or something like that.  Otherwise compile time injection is hard, because you can't refer to the root package.
> Don't generate the router in root package

- documentation/manual/releases/Migration24.md
- framework/src/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/Global.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/conf/alternate.conf
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/conf/routes
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/test
* conf directory in dist artifact is now added to the classpath by
default
* Added externalizeResources SBT setting to turn off including the
conf directory as an external (as in, not in the applications jar)
directory and including it in the classpath
* Added --no-exit-sbt flag to Play start and stop commands to help with
scripted tests
* Updated distribution scripted test, which now tests running Play in
prod mode, as well as testing if the conf directory is on the
classpath.
Fixes #3473.
Depends on #4108 being merged first.
> Sorted out conf directory

- framework/project/Build.scala
- framework/runtests
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/utils/JavaScriptRouterGenerator.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
If a user turns on all warnings in the Scala compiler, including `-Xfatal-warnings`, then the output of the routes compiler may not compile (I think it might be fine on master, but definitely not on 2.3.x).  We should add these flags to our routes compilation scripted tests.  Here's a sample set of flags:
```scala
scalacOptions ++= Seq(
"-deprecation", 
"-encoding", "UTF-8",
"-feature", 
"-language:existentials",
"-language:higherKinds",
"-language:implicitConversions",
"-unchecked",
"-Xfatal-warnings", 
"-Xlint",
"-Yno-adapted-args", 
"-Ywarn-dead-code", // N.B. doesn't work well with the ??? hole
"-Ywarn-numeric-widen", 
"-Ywarn-value-discard",
"-Xfuture",
"-Ywarn-unused-import" // 2.11 only
)
```
> Ensure routes compiler outputs code that doesn't emit warnings

- documentation/manual/working/scalaGuide/advanced/routing/ScalaSirdRouter.md
- documentation/manual/working/scalaGuide/advanced/routing/code/ScalaSirdRouter.scala
- framework/src/play/src/main/scala/play/api/routing/Router.scala
- framework/src/play/src/main/scala/play/api/routing/sird/PathBindableExtractor.scala
- framework/src/play/src/main/scala/play/api/routing/sird/PathExtractor.scala
- framework/src/play/src/main/scala/play/api/routing/sird/QueryStringExtractors.scala
- framework/src/play/src/main/scala/play/api/routing/sird/package.scala
- framework/src/play/src/test/scala/play/api/routing/sird/DslSpec.scala
- framework/src/play/src/test/scala/play/api/routing/sird/UrlContextSpec.scala
* Added new query parameter extractor macros for extracting query parameters in the sird DSL. Macros are used to parse and validate at compile time.
* Added ? and & extractors for combining multiple extractors together.
* Modified path bindable extractors to allow extracting optional and sequences of query parameters.
* Made path extractor more typesafe, it no longer extracts object, but uses overloaded unapplySeq methods.
* Small refactor of SimpleRouter, it's now a trait so it can be extended if desired.
> Added support for query parameters in sird

- documentation/manual/scalaGuide/main/sql/ScalaAnorm.md
Need import play.api.Play.current. or playframework will failed:
```
[error] /scala-code/wingo/app/controllers/Admin.scala:15: You do not have an implicit Application in scope. If you want to bring the current running Application into context, just add import play.api.Play.current
[error]     DB.withConnection { implicit c =>
```
> Need import play.api.Play.current

- framework/src/play-datacommons/src/main/scala/play/api/data/validation/ValidationError.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsResult.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonValidSpec.scala
- framework/src/play/src/main/scala/play/api/data/Form.scala
Follow up on the pull request [https://github.com/playframework/Play20/pull/1140].
I missed adding multiple keys in the scala object ValidationErrors.
To limit the impact i didn't change the serialization of the JsError, the Json generated contain only the last key.
For reference the plugin https://github.com/julienrf/play-jsmessages support alternative message keys.
> Allow to define multiple message keys in ValidationError

- framework/src/play/src/main/java/play/mvc/Http.java
Instead of blindly taking the PLAY_LANG value into lang(),
we treat it as the most prioritary language for the user.
This way a user cannot set a language that is undefined for
the application.
> When PLAY_LANG is set; treat it as first accepted lang.

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/mvc/HttpSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
- framework/src/play/src/test/scala/play/core/test/Fakes.scala
Mixing cases in request headers is currently not handled correctly.
```scala
def foo = Action { request =>
Ok(request.headers.getAll("X-Foo").mkString(","))
}
```
```bash
curl -H 'X-Foo: a' -H 'X-Foo: b' http://localhost:9000
a,b
```
```bash
curl -H 'X-foo: a' -H 'X-foo: b' http://localhost:9000
a,b
```
```bash
curl -H 'X-Foo: a' -H 'X-foo: b' http://localhost:9000
b
```
---
This change will choose one of the headers (the last one) as the canonical form for purposes of `Headers.keys`. Both values will be available with `Headers.getAll`, by any capitalization.
This is handled in `PlayDefaultUpstreamHandler`. It could have also been handled in `Headers`. Currently, however, we are already expecting the caller to deduplicate headers:
> The internal data structure here is a sequence of header …
> Handle request headers of different cases

- framework/project/Dependencies.scala
I am facing an issue with Play 2.4.0-M2
To me this seems like Java 8 is not fully supported in Guice 3.0, it may be fixed in 4.0, which is now in Beta5
I think it has something to do with this (using lambda and provides method):
https://github.com/google/guice/issues/757
While this is not directly related to Play it maybe a showstopper for Java 8 and Play 2.4.x users assuming Play would ship with Guice 3.0
Some are saying this will be fixed in Guice 4.0.
Hopefully Guice 4.0 comes out before play 2.4, but even then it there a plan to upgrade to Guice 4.0 before releasing Play 2.4?
[info] play.api.Play$ - Application started (Dev)
[error] application - Error while handling error
com.google.inject.internal.util.$ComputationException: java.lang.ArrayIndexOutOfBoundsException: 9578
at …
> Issue with Play 2.4-M2 (Guice 3.0 is not Java 8 compatible)

- documentation/manual/working/scalaGuide/main/json/code/ScalaJsonCombinatorsSpec.scala
- documentation/manual/working/scalaGuide/main/json/code/ScalaJsonSpec.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsConstraints.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsPath.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsReadable.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/package.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
After the discussion on #3888 it occurred to me that it should be possible to separate `JsValue` from the type used for traversing paths (which requires `JsUndefined`). I created the `JsLookup` specifically for representing the value at a particular JSON path. Many of the other cases where `JsUndefined` might otherwise be used already return `JsResult` and use `JsError` for when a path does not exist.
There are probably other ways of handling the type for doing traversal (implicit conversions from JsValue?) but I wanted to put this out there first as one possible solution.
> JsUndefined should not be a JsValue

- framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
- framework/src/play/src/main/java/play/mvc/Controller.java
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
- framework/src/play/src/main/scala/play/core/j/JavaParsers.scala
- framework/src/play/src/test/scala/play/core/j/JavaParsersSpec.scala
I have discovered an issue with Play 2.4.x and parsing JSON body requests. Sending JSON:
```
{"probability":50}
```
to java controller:
```
@BodyParser.Of(BodyParser.Json.class)
public static Result create() {
JsonNode json = request().body().asJson();
Logger.info("json: " + json);
```
ends with:
```
[info] application - json: {"probability":5E+1}
```
2.3.x works great with that code, 2.4 not.
> [2.4.0-M2] Problem when parsing json number (Scientific notation)

- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala
* Reads.flatMap must not repath the result of the 2nd JsResult
See also [this](https://groups.google.com/d/msg/play-framework/3mVwMtPTOv8/aOTvpnimIwcJ) discussion.
> Fix json-Reads flatMap

- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingConfig.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingConfigSpec.scala
Adds support for 3 more configuration params for AsyncHttpClient
```
// How long (ms) to keep a connection in the pool (default: forever)
ws.ning.maximumConnectionLifeTime
// How long (ms) to keep an idle connection in the pool (default: 1 min)
ws.ning.idleConnectionInPoolTimeout
// How long (ms) to keep an idle WebSocket conn open (default: 15 min)
ws.ning.webSocketIdleTimeout
```
Also updated the docs accordingly.
> WS: add support for 3 more Ning config params

- documentation/manual/detailedTopics/production/ProductionDist.md
On windows system, the merge strategy below won't work because of the defference of path separator.
```
assemblyMergeStrategy in assembly := {
case "play/core/server/ServerWithStop.class" => MergeStrategy.first
case other => (assemblyMergeStrategy in assembly).value(other)
}
```
> Improvement of #3873

- framework/src/play/src/main/java/play/mvc/Call.java
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/java/play/mvc/CallTest.java
Fixes #4034 
The implementation allows you to write e.g.
```scala
routes.Application.index.withFragment("some-id").absoluteURL(request)
```
> Add withFragment(...) to Call

- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play-filters-helpers/src/main/resources/reference.conf
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play/src/main/java/play/Play.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/Play.scala
- framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
Fixes #4068:
* Add setting `play.http.flash.httpOnly` (defaults to `true`)
* Flash cookie uses same `domain` as session cookie now
* Add setting `csrf.cookie.httpOnly` (defaults to `false`)
* Add conf `play.i18n.langCookieSecure` and `play.i18n.langCookieHttpOnly`
* The language cookie uses same `domain` and `path` of as session cookie now
> Cookie enhancements and fixes

- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Rearrange the Flash cookie cleaning logic to make it faster. In the common case where there is no Flash cookie or `Set-Cookie` header we can avoid doing any work at all.
> Optimize Flash cookie cleaning

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
When the `Set-Cookie` header is present we need to perform an expensive operation to split the headers. This change checks for the presence of the `Set-Cookie` header and only splits the headers if Set-Cookie is present.
> Avoid splitting headers unless Set-Cookie is present

- framework/src/play/src/main/scala/play/utils/CaseInsensitiveOrdered.scala
By comparing lengths in many cases we can avoid the need to look at the contents of the headers. This makes header operations a lot faster.
> Make header comparisons faster by comparing lengths

- documentation/manual/detailedTopics/configuration/SettingsLogger.md
- framework/project/Docs.scala
- framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala
- framework/src/play/src/main/resources/logback-play-default.xml
Logback's synchronized appender can be a bottleneck in Play performance. We have reports of dramatic performance improvements when using the [AsyncAppender](http://logback.qos.ch/manual/appenders.html#AsyncAppender), e.g. decrease in large transaction time from 120s down to 20s; apparently all threads were blocking on ch.qos.logback.core.spi.LogbackLock. A downside is that some log messages might be lost if the app crashes, because events are no longer synchronously written to disk. By default debug/trace/info messages will also be discarded if the log queue is full; but this can be disabled by setting *discardingThreshold* to 0.
A good writeup on all the trade offs has been written up by Takipi: http://blog.takipi.com/how-to-instantly-improve-your-java-logging-with-7-logback-tweaks/. …
> Consider using Async appender to improve Logback performance

- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
http://stackoverflow.com/questions/26372528/manipulate-the-response-status-text-in-play-2-2-scala
http://stackoverflow.com/questions/29440983/custom-text-for-http-api-status-code
This is useful when using custom status codes.
---
It would make sense for the parameter order for `ResponseHeader` to be `status`, `reasonPhrase`, `_headers`, since that is the order in which they appear in the response.
But having the order be `status`, `_headers`, `reasonPhrase` is more backwards compatible.
> Add reason phrase to ResponseHeader

- framework/project/Dependencies.scala
Multiple issues related to `AsyncAppender` were fixed/improved. According [release notes](http://logback.qos.ch/news.html):
1. Fixed a bug in AccessEvent which could cause any AsyncAppender based appender to corrupt the request headers, request parameters, or response headers, before logging.
2. Added max runtime parameter to AsyncAppender to allow the appender to flush events, up to a maximum delay, during a stop of the LoggerContext. This can be used to ensure that all queued events are flushed.
Since Play now uses the `AsyncAppender` (see #3862), I think this is relevant.
> Upgrade logback to version 1.1.3

- framework/project/Dependencies.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipSpec.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
- framework/src/play-specs2/src/main/scala/play/api/test/PlaySpecification.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/WSConfigParserSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingConfigSpec.scala
Also, replace deprecated NoTimeConvertions with the proper import to scala.concurrent.duration.
> Upgrade specs2 to version 3.3.1

- framework/src/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala
We spent a lot of this week doing a security audit of our app. One thing we realized is that it'd be very nice to be able to control which security headers are applied to which requests. There are a few pages where we'd like to skip a certain security header for various reasons. There's no good way to do that today. This will make the filter easy to override to add our own logic regarding which headers to apply.
> Allow application of security headers based on request

- framework/src/sbt-plugin/src/main/scala/play/sbt/eclipse/PlayEclipse.scala
It's currently broken. We've added it to sbteclipse instead. I'll upgrade our version of sbteclipse soon which will add it back. This at least fixes things for now
> Remove Eclipse classes_managed support

- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
We make the `remoteAddress` and `secure` fields into a LazyField instead of a standard Scala lazy value. This allows us to copy the field state without evaluating it.
Note: I've made RequestHeader's lazy field state `private[play]`. Should the field state be public so that people can extend `RequestHeader` and `Request`?
> Don't evaluate remoteAddress/secure when copying RequestHeader

- framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
- framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
To reproduce:
* Create a plain new `play-java` project.
* Add the [Global CSRF filter](https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf/Global.java) to `Global.java` like shown in the [docs](https://www.playframework.com/documentation/2.4.x/JavaCsrf#Applying-a-global-CSRF-filter)
* Add `filters` to the `libraryDependencies` in `build.sbt`
* In your `application.conf` set
```java
application.context=/abc
csrf.cookie.name=csrfcookie
```
* Make sure you use Milestone 3 in your `project/plugins.sbt`
```
addSbtPlugin("com.typesafe.play" % "sbt-plugin" % "2.4.0-M3")
```
* Open your browser and **make sure you clean your cookies**
* Run the project and goto http://127.0.0.1:9000/abc.
Result: The `csrfcookie` …
> [2.4.0-M3] Bug: CSRF cookie not set when using application.context

- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Using error handling (catching ConfigException.Missing) to detect missing configuration, replaced by checks with hasPath and getIsNull.
> Fixing #3495

- framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Protocol.scala
- framework/src/fork-run-protocol/src/test/scala/play/forkrun/protocol/SerializersSpec.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/app/Root.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/app/assets/main.less
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/nonplaymodule/src/main/scala/NonPlayModule.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/playmodule/app/PlayModule.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/playmodule/app/assets/module.less
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/build.properties
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/plugins.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/test
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/transitive/app/Transitive.scala
* Now uses proper sbt task dependencies, rather than manually running tasks from state
* Removed some very old hacks required from ancient sbt days
* Fixes #4127, so Play no longer creates missing source directories
* Previously there was a bug, where a non Play project dependency wouldn't be included in the returned analysis of playCompileEverything (though it would get compiled because of dependencies through the compile task).  I'm not sure if that bug actually had any real impact, possiby it meant that non play project compile errors wouldn't have sources loaded properly.  The bug is now fixed.
* Implemented a scripted test that tests that the right directories from the right projects are located (and not created) for monitoring, and that compiling everything compiles everything it …
> Refactored Play cross project aggregation tasks

- framework/src/play-java/src/main/java/play/libs/Time.java
- framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
http://docs.oracle.com/javase/8/docs/api/java/lang/StringBuffer.html
> The StringBuilder class should generally be used in preference to this one, as it supports all of the same operations but it is faster, as it performs no synchronization.
> use StringBuilder instead of StringBuffer

- framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
This seems like it simplifies the implementation quite a bit. All the tests still pass but I'm not completely sure if there is a good reason for the original implementation using `Seq`. If so hopefully someone can enlighten me.
> Implement JsObject using Map instead of Seq

- documentation/manual/releases/Migration24.md
- framework/project/Dependencies.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- templates/play-scala/build.sbt
Fixes #3436.
* Upgraded to netty-http-pipelining 1.1.4 (which is now deployed to maven central)
* Removed Typesafe releases repo resolvers from play settings
I tested this locally with a clean ivy cache, and found an additional issue that specs2 now depends on scalaz-stream as a required dependency, so a note was added to the migration guide and the play scala template has been updated.
Note that this only removes the dependency on the Typesafe releases repo for compile/runtime dependencies.  For build dependencies (sbt plugins etc) this is being tracked in #4223.
> Removed dependency on Typesafe releases repo

- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
@jroper Unfortunately I can not re-open #4225 so I created this new PR.
I removed the commit which reverted your fix for #2042.
The rest is the same.
I believe the close/unbind of the em should still be in `onFailure` and `onRedeem` instead of the finally.
> Correctly close and unbind JPA EntityManager

- documentation/manual/gettingStarted/IDE.md
- documentation/manual/gettingStarted/Installing.md
- documentation/manual/gettingStarted/NewApplication.md
- documentation/manual/gettingStarted/PlayConsole.md
- documentation/manual/gettingStarted/index.toc
Does the following changes to improve the first hour experience of how to use play:
1. Reorder the sections to focus on how to get an app running and how to setup an IDE
2. Explain the difference between full and minimal activator packages
3. Update links to IDE plugins and integrations
This is related to #4179.
> Improve the getting started documentation

- framework/src/run-support/src/main/scala/play/runsupport/FileWatchService.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/changes/some.txt.0
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/changes/some.txt.1
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/public/a/some.txt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/public/b/some.txt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Fixes #4208
If two files had the same name (in different directories), the sbt watcher only watched one of them.  This fixes that.
> Two files with same name are both watched

- framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Enumerator.scala
- framework/src/iteratees/src/test/scala/play/api/libs/iteratee/EnumeratorsSpec.scala
- framework/src/play/src/main/java/play/mvc/Results.java
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/main/scala/play/core/j/JavaResults.scala
- framework/src/play/src/test/java/play/mvc/ResultsTest.java
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
This pull request allows to send a file with the `java.nio.file.Path` API in addition to the old `java.io.File` API. This allows a user to change the underlying filesystem during testing.
This is a WIP pull request, because I would like to discuss some implementation details. The current implementation adds a new method `sendPath` because it isn't possible to overload the method `sendFile` because of its default arguments. An other possibility would be to add an implicit converter which converts a `java.io.File` instance into a `java.nio.file.Path` instance. This converter could be placed into the `play.api.mvc.Results` trait. But this had the disadvantage that `Ok.sendFile` would work but `Results.Ok.sendFile` would not based on the used import.
Any suggestion would be highly …
> Allow to send a file with the Java nio API to allow to change the underlying filesystem

- framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala
[Documentation](https://www.playframework.com/documentation/2.4.x/Evolutions) says that setting `play.modules.evolutions.enabled` to `false` should disable evolutions for all datasources, but it was not happening. Only per datasource config (e.g. `play.modules.evolutions.db.default.enabled = false`) worked.
This patch makes Evolutions Module behave as described in docs.
> Parse and apply 'play.modules.evolutions.enabled' config option.

- documentation/manual/detailedTopics/configuration/ThreadPools.md
- documentation/manual/detailedTopics/configuration/code/ThreadPools.scala
- documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/dynamic/HelloModule.java
- documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaDependencyInjection.md
- documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/RuntimeDependencyInjection.scala
- framework/src/play/src/main/scala/play/api/inject/Module.scala
- framework/src/play/src/test/scala/play/api/inject/ModulesSpec.scala
- framework/src/play/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala
This allows Guice modules to, for example, dynamically create bindings from configuration. You can see an example of this in the updated docs.
> Allow Guice modules to be constructed with Environment and Configuration

- documentation/manual/gettingStarted/Installing.md
With #4204 I've started to simplify the Install instructions.
With #4231, a regression was introduced (to the freshly simplified INSTALL.md document).
Note that I had anyway not yet finished with simplifying the document fully (it's a creative process, and needs some time). I need to apply a few more things, until I can say: "Well, that's a simple installation doc"
So, it would be nice to not interfere here, and to wait until I'm finished (with this one document).
The text
>If you don’ want to download the complete Activator distribution, there is a minimal package with no bundled dependencies. This mini-package has around 1MB and will download all the required dependencies at the first run.
is too much. This information introduces a decision to the newcomer and additionally, this …
> [REGRESS] Simplicity of Install Instructions

- documentation/manual/releases/Highlights24.md
- documentation/manual/releases/Migration24.md
- documentation/manual/working/javaGuide/advanced/embedding/JavaEmbeddingPlay.md
- documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlay.md
- documentation/manual/working/scalaGuide/advanced/iteratees/Enumeratees.md
- documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithDatabases.md
Get rid of spaces in _straight forward_ and apostrophe in _it's_.
> Fix up a few doc typos

- framework/src/play/src/main/resources/play/reference-overrides.conf
This reverts the thread pool configuration change in #4250. That change caused a 25% performance regression.
> Use fewer threads in the ActorSystem

- framework/project/Build.scala
A race condition in the Scala compiler that relates to global state and compiling the same code at the same time with two different instances of the Scala compiler causes intermittent build failures.  The existing work around that we had in place was to take the compile and doc tasks of the fork run protocol projects so they would not be done concurrently with each other.  SBT 0.13.8 split the compile task into multiple smaller tasks, meaning that the task that we now have to tag is compileIncremental.
> Fixed fork run protocol compile flakiness

- framework/src/play/src/main/resources/play/reference-overrides.conf
- framework/src/play/src/main/scala/play/api/libs/concurrent/PlayAkkaDispatcherConfigurator.scala
This improves the throughput of Play under most workloads. There may be a small latency difference, but it shouldn't be significant.
In tests I got a 5% performance improvement.
In rare circumstances it may be possible to starve tasks, indefinitely, e.g. if there are infinite async loops on each thread without any IO, but LIFO scheduling is the default in the JRE ForkJoinPool so it should be pretty safe.
We needed to clone some Akka config code in order to get the new LIFO config setting into the ForkJoinPool constructor. I'll raise an Akka issue to ask for this option to be supported.
> Set the ForkJoinPool to use LIFO scheduling

- framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
We have a case where an app adds vary:accept-encoding to every response, and the gzip filter is adding a duplicate.
> GzipFilter shouldn't add duplicate ACCEPT-ENCODING to VARY header

- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
- framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/api/controllers/AssetsSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Per https://tools.ietf.org/html/rfc7231#section-7.1.1.2
```
An origin server MUST NOT send a Date header field if it does not
have a clock capable of providing a reasonable approximation of the
current instance in Coordinated Universal Time.  An origin server MAY
send a Date header field if the response is in the 1xx
(Informational) or 5xx (Server Error) class of status codes.  An
origin server MUST send a Date header field in all other cases.
```
It's that **An origin server MUST send a Date header field in all other cases** that is the issue -- Play does not currently include a Date header in a generated response by default, only for Assets:
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/controllers/Assets.scala#L395
> Response should include Date header by default

- documentation/manual/detailedTopics/configuration/ThreadPools.md
- documentation/manual/detailedTopics/configuration/ws/CertificateRevocation.md
- documentation/manual/detailedTopics/configuration/ws/WsSSL.md
- documentation/manual/releases/Migration24.md
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/CertificateGenerator.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Debug.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/DefaultHostnameVerifier.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/SystemConfiguration.scala
There were a lot of links pointing to Java 6. I've manually check them all to ensure that the new links are still correct.
> Update docs to use jdk 8

- framework/src/anorm/src/test/scala/anorm/ParameterSpec.scala
A few different time/date/instant objects were expected to be equal when they were all created using current time constructors - if this didn't happen within a ms of each other, they're not equal.
> Improve anorm test stability

- documentation/manual/detailedTopics/configuration/code/ThreadPools.scala
- framework/src/play-java/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
- framework/src/play/src/main/java/play/GlobalSettings.java
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
- framework/src/play/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala
@jroper I thought I would split https://github.com/playframework/playframework/pull/4296 into two PRs to make it easier. I updated this one to deprecate the method as you suggested. I'm not sure that's actually clearer though... I think it's more confusing as a user because you can have lots of warnings in your project and not necessarily pay attention and then spend time tracking down why it's not working. But if it's an error, then you will be forced to update your code. As long as we put it in the migration guide, I think it'd be clearer to actually remove it.
> Remove onLoadConfig from GlobalSettings

- framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/Evolutions.scala
- framework/src/play/src/main/scala/play/api/libs/Files.scala
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
- framework/src/play/src/test/scala/play/libs/FilesSpec.scala
Also, TemporaryFile now has a real moveTo method which uses Java NIO to do the moving, instead of
a copy->delete of the file being moved.
This fixes #3913.
> Replaces deprecated APIs with Java NIO

- framework/project/Build.scala
- framework/src/play/src/main/scala/play/api/Configuration.scala
This should improve our build stability, which is failing with ConcurrentModificationExceptions when we attempt to parse configuration from system properties.
> Use Typesafe config system property config cache

- documentation/manual/working/javaGuide/main/tests/code/tests/guice/JavaGuiceApplicationBuilderTest.java
- documentation/manual/working/scalaGuide/main/tests/code/tests/guice/ScalaGuiceApplicationBuilderSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
- framework/src/play-java/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
- framework/src/play/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala
All of the fields in my tests are injected. I've gotten stuck on migrating to 2.4 when I got to my tests because it seems that Play 2.4 isn't really setup to have injectable tests. In Guice 3 you'd typically use something like [Guiceberry](https://code.google.com/p/guiceberry/) and [in Guice 4 you'd typically use Guice's built-in BoundFieldModule](https://github.com/google/guice/wiki/BoundFields). The typical setup is that you create an injector which injects the tests. The problem is that in Play 2.4 the Injector is hidden within the ApplicationLoader.
This PR helps by making the injector less hidden in the internals. You can see in fact that many of the existing tests had to inject an entire application and then get the injector from it to then inject some other object instead of being …
> Don't create an entire Application just to get an injector

- framework/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
This attempts to fix two build stability problems. One is an OOME from scalac when compiling tests. Hard to know what's causing this, but we know that scalac has problems compiling the same source code twice in the same JVM, these processes are isolated in the Compile scope due to a specific bug with macros, but maybe there are more bugs, so isolating them so the run sequentially in the Test scope may work.
The other is random failures in the dev mode scripted test, and I can't see what the problem is. I'm inserting a sleep at an opportune time, not because I think it should be there, but because I want to know if that makes a difference.
> Attempted build stability improvements

- framework/src/play/src/main/java/play/GlobalSettings.java
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
- framework/src/play/src/main/scala/play/core/j/JavaGlobalSettingsAdapter.scala
Because it is a no-op, users would be very confused if they tried to and it didn't do anything
> Make onLoadConfig final to stop users from overriding it

- framework/project/Build.scala
- framework/project/Tasks.scala
I should have removed this when I changed the way scala template sources are bundled, it's not used anymore.
> Remove unused Tasks object

- framework/build
After discussing with the Scala team, it seems our out of memory errors
may just be expected, given that we are compiling so many projects
together at once.  Increasing the heap to 4G.
> Increase heap for CI

- documentation/manual/detailedTopics/evolutions/Evolutions.md
- framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
Evolutions lock is enabled even Mysql InnoDB not only PostgreSQL and Oracle.
were divided script String according to the jdbc url.
> Enable evolutions lock using Mysql InnoDB.

- documentation/manual/releases/Migration24.md
- framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
- framework/src/play/src/main/scala/play/api/inject/Binding.scala
- framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala
- framework/src/play/src/main/scala/play/api/inject/Injector.scala
- framework/src/play/src/main/scala/play/api/inject/Module.scala
- framework/src/play/src/main/scala/play/api/inject/package.scala
With 2.3.8, this dependency:
"org.webjars" %% "webjars-play" % "2.4.0-M3-1"
And this route:
GET    /thing/create       controllers.ThingController.create
And this static Controller:
````
object ThingController extends Controller {
def create = Action { implicit request =>
Ok(thingViews.edit(newThingForm, None))
}
}
````
Caused this Twirl template to render properly:
````
@(thingForm: Form[model.Thing], maybeThingId: Option[Long])(implicit request: RequestHeader)
@import helper._
// blah blah
inputText(thingForm("sku"))
// blah blah
}
````
However, after changing `plugins.sbt` to use Play 2.4.0-RC1 the above gives the following error for each inputText in the Twirl view:
could not find implicit value for parameter messages: play.api.i18n.Messages
I tried adding the following imports to the …
> 2.4.0-RC1 Docs For Static Routes With Twirl, Also Guice Problem

- documentation/manual/releases/Migration24.md
1. Corrects minor typos
2. Add information about how to enable SbtEbean
3. Add information about how to configure mapped classes
> Improve ebean migration guide

- documentation/manual/releases/Migration24.md
The FileWatchService moved from 
play.sbtplugin.run to play.runsupport
> FileWatchService is in different package in 2.4

- framework/project/Publish.scala
Nightly build is failing because when we're publishing the sbt plugins, we're not publishing a pom files, so things built after them can't resolve them from OSS snapshots. Problem was, we should configure maven style publishing when it is a snapshot, not when it's not (when it's not, it gets published to an ivy repo, but snapshots get published to sonatype OSS snapshot repository).
> Fixing nightly build

- documentation/manual/releases/Migration24.md
The [migration guide](https://www.playframework.com/documentation/2.4.x/Migration24) has a section called "Dependency Injected Components". [`play.libs.Crypto`](https://github.com/playframework/playframework/blob/master/framework/src/play-java/src/main/java/play/libs/Crypto.java) is missing from this section.
Also, the text states:
> While Play 2.4 won’t force you to use the dependency injected versions of components, we do encourage you to start switching to them.
This isn't true for `Crypto` as far as I can tell. It looks like you have to use the dependency injected version because the old version went away. Not sure if that's a big issue, but wanted to mention that I noticed it
> 2.4.x Migration Guide - Crypto missing from "Dependency Injected Components"

- framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Iteratee.scala
Fixed issue with `EofOrElse` where the otherwise would always be executed
> Fixed issue with `EofOrElse`

- documentation/manual/releases/Migration24.md
In this document: https://www.playframework.com/documentation/2.4.0-RC1/Migration24
1)It is not "org.avaje.ebean.Model." but "com.avaje.ebean.Model."
2)You forgot to mention enabling the SbtEbean plugin in project
<code>lazy val myProject = (project in file(".")).enablePlugins(PlayJava, SbtEbean)</code>
> Correct Play2.4 Migration doc about Ebean

- framework/src/play/src/main/java/play/ApplicationLoader.java
Fix for https://github.com/playframework/playframework/issues/4359
> Allow ApplicationLoader.Context to be constructed from Java

- documentation/manual/releases/Migration24.md
WS needs a migration page to go over the changes.  (Someone please stick a "Documentation" label on this.)
Rough overview:
WS upgrades the underlying AsyncHttpClient engine to 1.9.11!
Now supports SNI for HTTPS.
AHC 1.9.x supports DefaultHostnameVerifier and acceptAnyCertificate natively.
The configuration options for Play WS have changed.  AHC 1.9.x also removed a number of configuration options and renamed others (i.e. compressionEnabled is now compressionEnforced).  
WSRequestHolder is now WSRequest.  WSRequestHolder is still available, but has been deprecated.
Options that were already deprecated in 2.3.x have been removed in 2.4.
Signpost OAuth has been mostly replaced by the internal AHC SignatureCalculator (Signpost is still doing the request token retrieval for now).
The internal …
> 2.4.x - WS Migration Guide

- framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonExtensionSpec.scala
Public Service Announcement: Fully qualify references in macros, and
test that you've done this by putting some unusually named identifiers
in scope before calling the macro.
> Better hygiene for the JSON macro

- documentation/manual/working/javaGuide/main/i18n/JavaI18N.md
- documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java
- documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/helloscalatemplate.scala.html
- documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/hellotemplate.scala.html
- documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/messages
- documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/messages.en-US
- documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/messages.fr
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play/src/main/java/play/mvc/Http.java
Currently in the Java API it's impossible to set the current Context's language without also setting a cookie. That means that it's impossible to just change the language for a single request. This change adds new necessary methods to support changing and clearing the language without changing the cookie.
Other changes:
* Added unit tests for changing the language.
* Added documentation tests for Java internationalization.
While writing the documentation tests I discovered that `import play.i18n._` is no longer supported in templates in 2.4 because it conflicts with the default `import play.api.i18n._`. It didn't conflict in 2.3. I'll create an issue to track this regression so we can decide whether to fix it.
> Allow lang to be set without cookie

- documentation/manual/releases/Migration24.md
Also improve table format for anorm type mappings.
> Fix link to Anorm section in migration guide

- framework/project/Dependencies.scala
Akka was just upgraded to 2.3.10 a couple days ago in https://github.com/playframework/playframework/pull/4358
It causes me to get tons of errors as reported in https://github.com/playframework/playframework/issues/4372
Meta comment - we probably want to slow down on the upgrades now that we've already released an RC and only upgrade libraries if there's a compelling reason
> Downgrade Akka to 2.3.9. Getting lots of errors with recently introduced 2.3.10

- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
I'm not sure if there's a reason for the current behavior. We're getting a NullPointerException in https://github.com/playframework/playframework/issues/4323, but there's no details as to where it's occurring, so the message is next to useless. This makes it obvious where the NPE is occurring.
> Don't swallow the stacktrace when an error occurs

- framework/project/Build.scala
- framework/project/Dependencies.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHttpServerSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
Even though Akka HTTP is on a new version I've kept the other Akka libraries on version 2.3.9 due to #4381.
Commits are split into several logical parts so don't need further squashing. More info in the commit messages.
> Upgrade Akka HTTP, fix and turn on integration tests

- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
These sleeps are necessary.  The following is what happens:
* Play detects a changed, stores the last modified timestamp, lets say it's 123 seconds since epoch.
* We then run some assertions, make sure the change was picked up.
* We then modify another file. Less than a second has passed, so its last modified has the timestamp of 123.
* Since it's not less than the last timestamp, that change doesn't get detected.
* Sleeping for a second solves this, ensuring it will tick over to 124 before we modify the file.
> Fix dev-mode test stability

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
Resolves #4402.
This field was unused. Use override when we override other request fields so that this doesn't happen again.
> Remove dead username field

- documentation/manual/releases/Migration24.md
HikariCP uses the JDBC4 Feature Connection.isValid(). 
In some older versions of the JDBC-Drivers, this method threws an exception.
> Mention common problem when migrating to HikariCP

- framework/src/play/src/main/scala/play/api/Configuration.scala
The config path is sufficient and the value may contain sensitive information (e.g. application.secret)
Fix for https://github.com/playframework/playframework/issues/4418
> Don't log values of deprecated config items

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
This leads to some subtle bugs regarding initalisation order. See #4434.
> Don't use vals in Session object.

- framework/src/play/src/main/resources/logback-play-default.xml
…at least with the default logging settings. Not related to #4323, was present already in RC1.
> Java / 2.4.0-RC2 Every UnexpectedException is being logged twice in prod mode.

- documentation/manual/detailedTopics/configuration/ws/LooseSSL.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
* Remove LooseSSL repeated link.
* Change ScalaWS to use the default NingWSClient() apply method in docs (which is secure by default)
* Fix @marcospereira's catch where `play.ws.ning.webSocketIdleTimeout` was not updated.
> Fixes to 2.4.x WS docs

- framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
Fixes #4448. Adds some very basic testing to check that BoneCP doesn't crash when loaded.
We could do a lot more testing on connection pools. The tests I added are very minimal, just enough to test that the crash bug is fixed, but not enough to verify individual connection pool configuration options.
If we care about more testing then I'd suggest merging this PR so that we can cut an RC and then maybe I can add more tests in a follow up PR. It's going to take me a while to work out how to "look into" the connection pool objects in order to check that they're properly configured. It may not even be possible to test if they're configured properly because they're pretty heavily buried in layers of Play and JDBC abstractions.
> Fix crash when BoneCP is used

- documentation/manual/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
Used version 3.6 as it's the most recent one. Removed the mention of 'match results' as this term no longer appears in the docs.
> Updated broken links to spec2 documentation

- documentation/manual/working/javaGuide/main/ws/JavaOAuth.md
- documentation/manual/working/scalaGuide/main/ws/ScalaOAuth.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaOAuthSpec.scala
Broke out the embedded OAuth scala examples so they are in specs files.
Also added some security best practices and a link to OAuth Bible, which goes deeper into OAuth.
> Move OAuth examples to specs

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
Fix #4467. We should be merging cookies by name instead of by path.
> Fix mergeCookieHeader

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
> Revert "Don't use vals in Session object."

- framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala
This should be cherry-picked to 2.4.x before cutting the next release.
> Docs server should be started with a Test Environment. Fix #4483

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Ciphers.scala
Also found the deprecated list was including TLS prefixed cipher suites which did not actually match the list defined in https://docs.oracle.com/javase/8/docs/technotes/guides/security/SunProviders.html#SupportedCipherSuites -- renamed and added note.
> [WS] Add RC4 to deprecated, remove from recommended

- documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md
- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
- framework/src/play/src/main/scala/play/core/j/JavaAction.scala
It is now possible to control if action composition annotations put directly on controller classes should be executed before the ones put on action methods by setting `play.http.actionComposition.controllerAnnotationsFirst = true` in `application.conf` (Right now the methods ones are executed first and also stays the default).
There have been discussions (like [this one](https://groups.google.com/forum/#!topic/play-framework/AY4NuQziYyM)) going on, plus there was [a rejected PR](https://github.com/playframework/playframework/pull/156) long time ago, so hopefully with this fix the issue can finally be settled.
This change is not really disruptive and also completely backwards compatible so hopefully it makes it in 2.4 - I even added documentation :smile:
> Action composition annotation order can be configured

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/AlgorithmChecker.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/CertificateGenerator.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmCheckerSpec.scala
Fixes https://github.com/playframework/playframework/issues/4241
The algorithm to note SHA-1 certificates is based on the expiration date -- a certificate expiring from 6/2016 to 12/2016 gets an info, but expiration after that gets a warning, based on http://googleonlinesecurity.blogspot.com/2014/09/gradually-sunsetting-sha-1.html
> [WS] Add info and warnings to sunset SHA1 signatures

- documentation/manual/releases/Migration24.md
- documentation/manual/working/javaGuide/advanced/http/JavaHttpFilters.md
- documentation/manual/working/javaGuide/advanced/http/JavaHttpRequestHandlers.md
- documentation/manual/working/javaGuide/advanced/http/code/javaguide/RequestHandler.java
- documentation/manual/working/javaGuide/advanced/http/code/javaguide/httpfilters/Filters.java
- documentation/manual/working/javaGuide/advanced/http/index.toc
- documentation/manual/working/javaGuide/advanced/index.toc
- documentation/manual/working/scalaGuide/advanced/http/ScalaHttpRequestHandlers.md
Migration doc for helping users moving away from `GlobalSettings` in the upcoming Play 2.4 release.
Note that some of the links I used are broken (missing page). For instance, we don't have a `JavaHttpRequestHandlers` page in the doc. I've worked under the assumption that we will create the missing pages before 2.4 final is published. Let me know if I'm wrong.
> Migration doc for GlobalSettings

- documentation/manual/detailedTopics/configuration/ThreadPools.md
- documentation/manual/detailedTopics/configuration/code/ThreadPools.scala
- framework/src/play/src/main/resources/play/reference-overrides.conf
https://www.playframework.com/documentation/2.4.x/ThreadPools
```
Since you are never blocking, the default configuration of one thread per processor suits your use case perfectly,
```
but later,
```
This configuration instructs Akka to create 3 threads per available processor
```
So is there one thread per processor, or three?
> [2.4.0] [doc] Inconsistent number of threads in ThreadPools.md

- framework/src/play-integration-test/src/test/scala/play/it/http/ActionCompositionOrderTest.java
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
- framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
- framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala
This adds tests for action composition order configuration, which was added by PR #4461. It also adds tests for HttpConfiguration provider.
> Tests for action composition order and http configuration

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSModule.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
- framework/src/play/src/main/scala/play/core/j/JavaAction.scala
If an action fails due to an exception being thrown, the headers still need to be added so that the cross origin client can process the failed response.
> Ensure CORS headers get added to failed responses

- framework/src/play/src/main/scala/play/api/routing/JavascriptReverseRouter.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/assets/JavaScriptRouterSpec.js
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/utils/JavaScriptRouterGenerator.scala
I rewrote the code for generating the reverse router to make it more readable as well. I'm not sure if it's possible to have invalid JS string characters in controller names but I escaped those too.
> Escape strings in JS reverse router

- framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/conf/routes
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/test
Fixes #4512
* Build an additional sans-externalized jar that doesn't contain the externalized resources when externalized resources is true
* Include this jar in the script classpath, and exclude the normal jar, when externalized resources is true
> Exclude externalized resources from application jar in dist

- framework/src/play/src/main/scala/play/api/mvc/Controller.scala
The scaladoc for Controller.scala doesn't compile.   Tweaked the docs to use the current methods.
> Fix Controller scaladoc

- documentation/manual/detailedTopics/production/cloud/Deploying-CleverCloud.md
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- templates/play-java-intro/conf/application.conf
- templates/play-java/conf/application.conf
- templates/play-scala-intro/conf/application.conf
- templates/play-scala/conf/application.conf
Fix in the code and documentation the configuration keys about evolutions (`play.modules.evolutions` -> `play.evolutions`)
Fixes for #4533
> [2.4] Corrects evolutions configuration keys

- documentation/manual/releases/Migration24.md
The example given for sbt-native-packager did not have spacing and so was not showing up as a code example.  Should backport to 2.4.x
> [doc] Add spacing in Migration24.md

- documentation/manual/releases/Migration24.md
Given I have a static method in a Java interface
```java
public interface Java8Interface {
static String foo() {
return "foo";
}
}
```
Then a Play 2.4.0-RC5 project fails to compile it
```
[error] /home/travis/build/schleichardt/play-2-4-java-8-compile-errors/app/demo/Java8Interface.java:4: `;' expected but `{' found.
[error]     static String foo() {
[error]                         ^
[error] one error found
[error] (root/compile:compileIncremental) Compilation failed
```
* test project to reproduce: https://github.com/schleichardt/play-2-4-java-8-compile-errors
* travis output for a plain sbt project which compiles the interface: https://travis-ci.org/schleichardt/play-2-4-java-8-compile-errors/builds/63322694#L786
* see https://github.com/schleichardt/play-2-4-java-8-compile-errors/blob/ …
> Java 8 static method in interface does not compile in Play 2.4.0-RC5

- documentation/manual/releases/Migration24.md
This is the backport of https://github.com/playframework/playframework/pull/4539 on 2.4.x branch.
> [doc] Add spacing in Migration24.md <backport 2.4.x>

- framework/src/play/src/main/scala/play/api/Routes.scala
In play.api.Routes, the deprecated message for all the deprecated ROUTE objects is the same, e.g.
```
@deprecated("Use play.api.routing.Router.Tags.RouteVerb instead", "2.4.0")
val ROUTE_PATTERN = Router.Tags.RoutePattern
```
Fixed in master, should probably backport to 2.4.x.  It's not mentioned in the documentation as far as I found, so no worries about updating there.
> Fix deprecation messages for ROUTE_* constants

- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
The configuration doc for the max disk buffer setting was set to an invalid value "parsers.disk.maxLength" that would never have any effect.  Looked through some old docs and it shows up here: 
https://www.playframework.com/documentation/2.4.0-M3/ScalaBodyParsers
But it's not showing in 2.3.x so it looks like a new setting that was changed in code but not in docs.
Changed code comment from "parsers.disk.maxLength" to match the HTTPConfiguration value "play.http.parser.maxDiskBuffer"
The test configuration for the property is here:
https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala#L21
> Fix BodyParser diskbuffer scaladoc

- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
#4429 #4545
Added messageSourceName to MessageParser initialization so it's not ignored anymore.
Changed on master.
> Added messageSourceName to MessageParser initialization

- templates/build.sbt
- templates/play-java-intro/conf/logback.xml
- templates/play-java/conf/logback.xml
- templates/play-scala-intro/conf/logback.xml
- templates/play-scala/conf/logback.xml
- templates/project/Build.scala
- templates/project/plugins.sbt
- templates/project/resources/logback.xml
* Made template build no longer depend on the Play build - this was causing big issues and confusion with scala versions etc. Instead it now depends on a static version of play-ws, which is ok.
* Made template build read Play version from version.sbt, but make it overridable for when we publish templates.
* Made template build default to Scala 2.10.5 for snapshots (this means it will work in CI) and 2.11.6 for production versions (which is what we want when we deploy the templates).
* Fixed #4551, logback.xml configuration was missing coloredLevel configuration.
* Provided a logback.xml to template build so that s3 plugin and template publishing doesn't spew massive amounts of debug to console.
> Fix the template build

- documentation/manual/releases/Highlights24.md
There is a mistake in Java Routing DSL link. It is linked to "JavaRoutingDSL" instead of "JavaRoutingDsl".
> Fixing JavaRoutingDsl link

- framework/project/plugins.sbt
This new release contains a fix for parsing JDK8 classfiles.
To be backported to 2.4.x
I just released mima, so it may take a few hours before the jars are available (which is why the build will likely fail now).
> Updated sbt-mima-plugin to version 0.1.7

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/DatabaseConfig.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/Config.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Config.scala
- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
- framework/src/play/src/main/scala/play/api/libs/Crypto.scala
- framework/src/play/src/main/scala/play/api/routing/Router.scala
- framework/src/play/src/main/scala/play/utils/Reflect.scala
- framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
This lets us remove the special getOptionalX methods and just use getX instead. These methods were private to Play so it's OK to remove them without deprecation.
> Implicit ConfigLoader for Option

- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
Currently, when the `Multipart.multipartParser` creates a bad-request result, for instance when there's a missing boundary header, this will be thrown away and replaced with a 413 entity-too-large no matter what the size of the entity actually is.
> Prevent misleading 413 error when multipart parser recieved a bad request.

- framework/src/play-filters-helpers/src/main/resources/reference.conf
- framework/src/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
Fixes #4513.
You can configure the filter with a list of allowed hosts, which can either be exact hostnames like `example.com` or suffix hostnames like `.example.com`, which matches `example.com` as well as `www.example.com` and other subdomains.
> Add AllowedHostsFilter to deny requests with invalid hosts

- documentation/manual/releases/migration24/Migration24.md
This commit intends to make it easy for people using scala builds to find the proper import for play keys and configuration elements.
> Add references to `play.sbt.PlayImport`

- documentation/manual/releases/migration24/Migration24.md
Fixes https://github.com/playframework/playframework/issues/4654, cherry picked to 2.4.x branch.
> Fixes acceptAnyCertificate setting in migration guide

- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
- framework/src/play-java/src/main/java/play/libs/Comet.java
- framework/src/play-java/src/main/java/play/libs/EventSource.java
- framework/src/play-test/src/main/java/play/test/Helpers.java
- framework/src/play/src/main/java/play/libs/F.java
- framework/src/play/src/main/java/play/mvc/Results.java
- framework/src/play/src/main/java/play/mvc/WebSocket.java
- framework/src/play/src/main/scala/play/core/j/FPromiseHelper.scala
- framework/src/play/src/main/scala/play/core/j/JavaResults.scala
- framework/src/play/src/main/scala/play/core/j/JavaWebSocket.scala
- framework/src/play/src/test/java/play/PromiseTest.java
- framework/src/play/src/test/java/play/mvc/WebSocketTest.java
- framework/src/play/src/test/scala/play/api/libs/iteratee/ExecutionTest.scala
- framework/src/play/src/test/scala/play/libs/FSpec.scala
- templates/play-java-intro/test/IntegrationTest.java
- templates/play-java/test/IntegrationTest.java
We are embracing Java8 functional interfaces and hence this commit replaces all
occurrences of Play `F.Callback` with the Java8 counterpart. Types are mapped as
follow:
* `F.Callback0`          -> `java.lang.Runnable`
* `F.Callback<A>`        -> `java.util.function.Consumer<A>`
* `F.Callback2<A,B>`     -> `java.util.function.BiConsumer<A,B>`
* `F.Callback3<A,B,C>`   -> no counterpart in Java8
One important difference between the Play `F.Callback` and the new Java8 types
is that, while the Play Callback types can all throw `Exception`, the new
corresponding Java8 functional interface types can't. This entails that
existing code may need to be changed when moving from the Play `Callable` types
to the Java8 types (for an example of this, see `PromiseTest.java` in this
commit). If interested, …
> Replaced `F.Callback` with Java8 `Runnable`, `Consumer` and `BiConsumer`

- framework/project/Build.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSModule.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
Fixed binary compatibility issues with CORS error handling backport
* Two binary compatibility issues remain and are filtered. See comments on the filters for justifications as to why this is ok.
> Backport of #4524 - Ensure CORS headers get added to failed responses

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
Only apply HttpHeaders.Values.APPLICATION_X_WWW_FORM_URLENCODED work
around when needed.
> Post binary data 'as is' with play-ws client.

- framework/src/play/src/main/java/play/mvc/Call.java
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/main/scala/views/helper/form.scala.html
- framework/src/play/src/test/java/play/mvc/CallTest.java
Starting with Play 2.4 a `Call` now has a `withFragment` method (see #4152).
In a template when writing
```
@routes.Application.index.withFragment("some-id")
```
gives you `/index#some-id`. So that's fine. :+1: 
However when using the form helper with the **exact** same Call  
```
@helper.form(action = routes.Application.index.withFragment("some-id")) { }
```
the fragment is missing:
```html
<form action="/index" method="POST">
```
Description of the changes in this PR:
1) Changed `views/helper/form.scala.html` so it uses `toString` instead of `url`, because `toString` also [returns the fragment](https://github.com/playframework/playframework/blob/5de8000b32bdc6d8abc408c2b677ff606884475d/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L370). This fixed my original problem.
2) …
> Improvements to Call + support for fragments in form actions

- framework/src/play/src/main/java/play/libs/F.java
- framework/src/play/src/main/scala/play/core/j/FPromiseHelper.scala
- framework/src/play/src/test/scala/play/libs/FSpec.scala
As explained in d24c79d85eb9f71499588d2180bfb29e6b73d55f, we are embracing Java8
functional interfaces. This commit replaces `F.Predicate` with
`java.util.function.Predicate`.
The change is source compatible if the lambda's body passed to `F.Predicate`
does not throw a checked exception. Otherwise, users will need to update their
code to catch the exception and provide the necessary logic to deal with it.
By the way, I'm also working on replacing `F.Function` but it's a bit trickier. Hence I thought I'd start pushing this simple commit for today, and hope that by tomorrow I'll sort out the `F.Function` replacement.
> Replaced `F.Predicate` with Java8 `java.util.function.Predicate`

- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Deprecation error message in NettyServer is missing string interpolator
on error message that informs a user that ProdServerStart has replaced
NettyServer as the preferred main class for Play apps.
> Add missing 's' string interpolater to error message in NettyServer

- framework/src/play-streams/src/main/scala/play/api/libs/streams/impl/IterateeSubscriber.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/IterateeSubscriberSpec.scala
This handles a case that was missed: when onSubscribe is called and then the iteratee enters a Done or Error state.
We may wish to backport this to 2.4.
> Always cancel subscription when Iteratee finishes

- framework/project/plugins.sbt
Switching to `webjars-locator-core` per @jamesward suggestion on https://github.com/webjars/webjars-locator-core/pull/3
> Upgrade webjars locator to fix permissions issue with the files inside inside webjars

- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
Fixes the `InvalidUriEncodingException` exception in #3532 
There was already a failing test for this:
```
> test-only *.NettyAssetsSpec
ERROR application -
! @6mf7op276 - Internal server error, for (GET) [/versioned/sub/12345678901234567890123456789012-foo.txt] ->
play.api.UnexpectedException: Unexpected exception[InvalidUriEncodingException: Cannot decode \versioned\sub\foo.txt: illegal character at position 1.]
at play.api.http.HttpErrorHandlerExceptions$.throwableToUsefulException(HttpErrorHandler.scala:250) ~[classes/:na]
at play.api.http.DefaultHttpErrorHandler.onServerError(HttpErrorHandler.scala:180) ~[classes/:na]
at play.core.server.netty.PlayDefaultUpstreamHandler$$anonfun$9$$anonfun$apply$1.applyOrElse(PlayDefaultUpstreamHandler.scala:158) [classes/:na]
at …
```
> Fix versioned assets on Windows

- framework/src/play/src/main/java/play/http/DefaultHttpErrorHandler.java
- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
This PR splits a part of the `DefaultHttpErrorHandler.onClientError` method into the new `onOtherClientError` method, so it can easily be overriden.
Right now when you want to handle a 4xx response (except 400, 403 or 404, which have their own handler methods)  your only choice is to override `onClientError` itself, which IMHO isn't the best idea.
If someone comes up with a better name instead of `onOtherClientError` please tell me :smile: 
I would like to have this in 2.4.1 if it's OK for you guys, thanks!
> Add method to handle various 4xx client errors to DefaultHttpErrorHandler

- framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
I am using `dataSourceClassName` to configure a database connection (instead of the "classic" jdbc-url style) and also bind the datasource via JNDI:
```
db.default.hikaricp.dataSourceClassName=org.postgresql.ds.PGSimpleDataSource
db.default.hikaricp.dataSource.user=myuser
db.default.hikaricp.dataSource.password=mypassword
db.default.hikaricp.dataSource.databaseName=mydb
db.default.hikaricp.dataSource.serverName=localhost
db.default.jndiName=DefaultDS
```
The log now gives me `...datasource [null]...`:
```
[info] p.a.d.HikariCPConnectionPool - datasource [null] bound to JNDI as DefaultDS
```
The problem is [here](https://github.com/playframework/playframework/blob/cf60c65b551cedf99a5cceaee5b15cc9cff8a37b/framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala#L63-L64): I …
> JNDI binding logs "null" as datasource

- documentation/manual/detailedTopics/configuration/filters/CorsFilter.md
The [documentation](https://www.playframework.com/documentation/2.4.x/CorsFilter) and the [config](https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala#L81-L101) code are not matching.
So i assumed the code is right and rename the documentation:
allowOrigins -> allowedOrigns
allowHttpMethods -> allowedHttpMethods
allowHttpHeaders -> allowedHttpHeaders
exposeHeaders -> exposedHeaders
> fix cors config documentation

- documentation/manual/hacking/BuildingFromSource.md
as per http://www.scala-sbt.org/0.13/docs/Cross-Build.html,
the syntax for sbt crossbuilding is `++` not `+++`
> fix small mistake in "Building from source" doc

- documentation/manual/hacking/BuildingFromSource.md
Reverts playframework/playframework#4740, because we're using sbt-doge, not sbt's built in cross building support.
> Revert "fix small mistake in "Building from source" doc"

- documentation/manual/working/javaGuide/advanced/http/code/javaguide/RequestHandler.java
- documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java
- documentation/manual/working/javaGuide/main/async/code/javaguide/async/controllers/Application.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java
- documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/Application.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/Application.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
- framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
- framework/src/play-integration-test/src/test/java/play/routing/RoutingDslTest.java
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/TransactionalAction.java
- framework/src/play-java/src/main/java/play/routing/RoutingDsl.java
- framework/src/play/src/main/java/play/GlobalSettings.java
- framework/src/play/src/main/java/play/http/DefaultHttpRequestHandler.java
- framework/src/play/src/main/java/play/libs/F.java
- framework/src/play/src/main/java/play/mvc/Action.java
- framework/src/play/src/main/java/play/mvc/Security.java
- framework/src/play/src/main/java/play/mvc/WebSocket.java
- framework/src/play/src/main/scala/play/core/j/FPromiseHelper.scala
- framework/src/play/src/test/java/play/PromiseTest.java
- framework/src/play/src/test/java/play/mvc/SecurityTest.java
- framework/src/play/src/test/scala/play/api/libs/iteratee/ExecutionTest.scala
- framework/src/play/src/test/scala/play/api/libs/iteratee/TestChannel.scala
- framework/src/play/src/test/scala/play/libs/FSpec.scala
Replaced `F.Function` with Java8 friends. Fix #4690
As explained in d24c79d85eb9f71499588d2180bfb29e6b73d55f, we are embracing Java8
functional interfaces. This commit makes the following changes:
* `F.Function0` -> `java.util.function.Supplier`
* `F.Function1` -> `java.util.function.Function`
* `F.Function2` -> `java.util.function.BiFunction`
The change is source compatible if the lambda's body passed to either of the
former `F.Function` types does not throw a checked exception. Otherwise, users
will need to update their code to catch the exception and provide the necessary
logic to deal with it.
There is however an important change affecting source compatibility, as several
of the methods in `F.Promise` used to throw (Throwable), while they don't now (
Ref #4691).
There is one …
> Replaced `F.Function` with Java8 friends. Fix #4690

- documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md
The current documentation shows wrong version of scala test plus to use which could create confusion among new comers
> Updated version of Scala Test Plus

- documentation/manual/releases/migration24/Migration24.md
- framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonValidSpec.scala
I think this is a good idea for 2.4.0 since it implements validating `Option` types the "right" way. I'd rather have people migrate from `validate[Option[A]]` to `validateOpt[A]` than to some other more verbose solution.
> Add JsReadable#validateOpt

- framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala
Since Play manages the ehcache instances this is likely to be caused by starting multiple applications at the same time, and not per se related to ehcache or use of the cache API.
Closes #4717.
> Provide a more useful error when a named EhCache already exists.

- templates/play-java-intro/build.sbt
- templates/play-java-intro/project/plugins.sbt
- templates/play-java/project/plugins.sbt
This fixes playframework/play-ebean#45 by correcting some comments in play-java templates. Also, a warning was added to instruct users to remove JPA when activating play-ebean.
> Fixes play-java templates references to play-ebean

- documentation/manual/working/javaGuide/main/ws/JavaOAuth.md
The configuration value should be "play.http.session.secure"
https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala#L128
> Fix invalid session secure cookie setting

- documentation/manual/detailedTopics/production/HTTPServer.md
> If you are running a reverse proxy on a different machine, you can set the trustxforwarded configuration item to true in the application configuration file, like
`trustxforwarded` property is invalid by #2094, and since Play 2.4.x
> Remove trustxforwarded from HTTPServer document

- documentation/manual/working/scalaGuide/main/tests/code-scalatestplus-play/ExampleControllerSpec.scala
- framework/src/build-link/src/main/java/play/core/BuildDocHandler.java
SimpleResult changed for Result as SimpleResult was deprecated in 2.3.
> Update sample controller test for ScalaTest

- documentation/manual/detailedTopics/configuration/ws/CipherSuites.md
- documentation/manual/detailedTopics/configuration/ws/LooseSSL.md
- documentation/manual/detailedTopics/configuration/ws/Protocols.md
- documentation/manual/detailedTopics/configuration/ws/code/HowsMySSLSpec.scala
Some parts of the WS SSL documentation were still referencing the old ws.ssl configuration settings.
> [doc] Fix ws.ssl settings

- framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonExtensionSpec.scala
The JSON macros remove the boilerplate for creating `Reads`/`Writes`/`Format` for case classes.
But given that a case class will always serialise to a `JsObject` then .writes/.format could return
`OWrites`/`OFormat` respectively.
This allows for type-safety in manipulating a statically known `JsObject`, rather than a `JsValue`.
Given that `OWrites` and `OFormat` are subtypes of `Writes`/`Format` this is a backwards-compatible change.
> Make JSON macros return OFormat/OWrites.

- documentation/manual/scalaGuide/main/templates/ScalaCustomTemplateFormat.md
Fixed spelling error (to vs two)
Marked up HTML snippets
Various small grammatical / typo fixes
> Update markup of ScalaCustomTemplateFormat.md 

- framework/project/Dependencies.scala
- framework/project/plugins.sbt
Fix for https://github.com/playframework/playframework/issues/4736
> Upgrade to webjars locator 0.26 to fix bug where some webjars like select2 are not working after we upgraded to 0.25

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala
- framework/src/play-integration-test/src/test/scala/play/it/action/EssentialActionSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
- framework/src/play-server/src/main/scala/play/core/server/ServerProvider.scala
- framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala
- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
- framework/src/play/src/main/scala/play/api/Application.scala
- framework/src/play/src/test/scala/play/api/FakeApplication.scala
- framework/src/play/src/test/scala/play/api/mvc/RawBodyParserSpec.scala
Play was instantiating a new flow materializer for every test. Each one instantiated created a new actor, leading to an actor leak.
The impact on performance is massive.
> Ensure a single flow materializer is used to handle requests

- documentation/style/main.css
This makes the Play built-in documentation server consistent with playframework.com. See https://github.com/playframework/playframework.com/pull/30.
> Make it easier to see hyperlinks in documentation code

- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/build.sbt
default `executableScriptName` is `normalizedName`
https://github.com/sbt/sbt-native-packager/blob/v1.0.3/src/main/scala/com/typesafe/sbt/PackagerPlugin.scala#L100
In most cases, old code is fine if user does not change the default `executableScriptName`.
but can not execute [the "start" command](https://github.com/playframework/playframework/blob/2.4.2/framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala#L190) when user change the `executableScriptName`
> use executableScriptName instead of normalizedName

- documentation/manual/detailedTopics/configuration/ApplicationSecret.md
Updating doc to avoid:
[SystemPlay] $ play-update-secret
[error] Not a valid command: play-update-secret
[error] Not a valid project ID: play-update-secret
[error] Expected ':' (if selecting a configuration)
[error] Not a valid key: play-update-secret (similar: playUpdateSecret, playGenerateSecret)
[error] play-update-secret
> Update key to generate a new secret

- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
- framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
[RFC6266](https://tools.ietf.org/html/rfc6266#section-4.1) allows both quoted and unquoted values.
The .NET HTTP client (specifically `System.Net.Http.MultipartFormDataContent`) formats the header like this:
```
Content-Disposition: form-data; name=document; filename=hello.txt; filename*=utf-8''hello.txt
```
> Add support for unquoted Content-Disposition parameters

- framework/project/Dependencies.scala
1. specs2 to version 3.6.2 ([3.6.2 release notes](http://notes.implicit.ly/post/122717713089/specs2-3-6-2); [3.6.1 release notes](http://notes.implicit.ly/post/120591484789/specs2-3-6-1)) 
2. Scalacheck to version 1.12.4 ([1.12.4 release notes](https://github.com/rickynils/scalacheck/blob/1.12.4/RELEASE); [1.12.3 release notes](https://github.com/rickynils/scalacheck/blob/1.12.3/RELEASE))
> Update test dependencies

- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSCookie.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSCookie.java
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
This is a bug in AHC that results from double encoding the request:
https://github.com/AsyncHttpClient/async-http-client/pull/914
Fix will be to upgrade AHC to the newer version once the fix is in.
> WS adds percent encoding when signing with OAuth

- framework/src/play/src/main/scala/play/api/Logger.scala
- framework/src/run-support/src/main/scala/play/runsupport/DelegatedResourcesClassLoader.scala
- framework/src/run-support/src/main/scala/play/runsupport/NamedURLClassLoader.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
This PR fixes these two memory leaks of #4649:
- `org.slf4j.bridge.SLF4JBridgeHandler`
- `scala.tools.nsc.interactive.PresentationCompilerThread`
I DID NOT fix this leak:
- `javax.xml.bind.DatatypeConverterImpl.datatypeFactory`: This field [is final](http://grepcode.com/file/repository.grepcode.com/java/root/jdk/openjdk/8u40-b25/javax/xml/bind/DatatypeConverterImpl.java#886). You can change a final field via reflection but after reading [this StackOverflow answer](http://stackoverflow.com/a/3301720/3005340)...not worth it.
I did not add any tests because it would fail all the time (at least one leak not fixed).
> fix dev-mode memory leaks (#4649)

- documentation/manual/working/javaGuide/main/sql/JavaDatabase.md
- documentation/manual/working/scalaGuide/main/sql/ScalaDatabase.md
- framework/project/Dependencies.scala
- framework/src/play-jdbc/src/main/resources/reference.conf
- framework/src/play-jdbc/src/main/scala/org/jdbcdslog/LogSqlDataSource.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
- framework/src/play/src/main/resources/logback-play-logSql.xml
Based on this discussion:
https://groups.google.com/forum/#!topic/play-framework-dev/GK3ywRTMexg
----------
What I'm planning to do:
1. Have a boolean configuration (`play.db.logSql`) that controls if statements will be logged or not
2. Use [jdbcdslog-exp](https://github.com/adrianshum/jdbcdslog) to wrap the created datasource when configured to do so
3. Support both HikariCP and BoneCP connection pools.
> Have a way to log SQL statements

- framework/project/Build.scala
- framework/src/play-java/src/main/java/play/libs/Classpath.java
- framework/src/play-java/src/main/scala/play/libs/ReflectionsCache.scala
- framework/src/play-java/src/test/java/play/libs/ClasspathTest.java
- framework/src/play-java/src/test/java/play/libs/testmodel/AC1.java
- framework/src/play-java/src/test/java/play/libs/testmodel/C1.java
Added SubTypesScanner when ReflectionsCache is instantiated since
getTypesAnnotatedWith method requires SubTypesScanner to be configured since Reflections version 0.9.9.
http://reflections.googlecode.com/svn/trunk/reflections/javadoc/apidocs/org/reflections/Reflections.html#getTypesAnnotatedWith(java.lang.Class)
> Added SubTypesScanner when ReflectionsCache is instantiated

- framework/src/play-test/src/test/java/play/test/WithBrowserTest.java
- framework/src/play/src/main/scala/views/defaultpages/badRequest.scala.html
- framework/src/play/src/main/scala/views/defaultpages/devNotFound.scala.html
- framework/src/play/src/main/scala/views/defaultpages/notFound.scala.html
I have changed the tile of the notFound-defaultpage to a simple "Not Found". I guess it is not right to display "Action Not Found" in any such case where a controller action is found in the first place that returns a not found http status due to further conditions. Shouldn't the term "action" be kept internally within the application anyway?
> Corrected Defaultpages View Titles

- framework/src/play/src/main/scala/play/api/libs/MimeTypes.scala
In using `.webm` video files as assets, I noticed that this type wasn't on the list of default types. The [best default](https://www.google.co.uk/search?q=WebM+file+extension&oq=WebM+file+extension&aqs=chrome..69i57j0l5.254j0j4&sourceid=chrome&es_sm=91&ie=UTF-8) for `.webm` seems to be `video/webm`. They use `audio/webm` for the audio-only version however in the link you'll see that `video/webm` is far more common than `audio/webm` and therefore should be the default.
WebM documentation on their website: http://www.webmproject.org/docs/container/
Without this, the default would be `application/octet-stream` which couldn't play WebM videos on the browsers that I tested.  The user would have to explicitly specify the `Content-Type` header.
> Added WebM to list of types

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/FormFieldOrderSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSRequest.java
- framework/src/play-java-ws/src/test/scala/play/libs/ws/ning/NingWSRequestSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
Fixes #4846
As per discussion on issue, I've modified the API to take a `scala.concurrent.duration.Duration` as the parameter rather than `Long`.
I've modified the Ning implementation to set the requestTimeout to -1 if `Duration.Inf` is passed and to validate all non-infinite values to make sure they are non-negative and less than `Int.MaxValue`. Tests and documentation updated.
> Modified WSRequest.withRequestTimeout to take Duration as a parameter

- framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsPath.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsPathSpec.scala
This method alias introduces more better path expression.
```scala
((JsPath \ "key1")(0) \ "key11")(obj)
```
is now also written as
```scala
(JsPath \ "key1" \ 0 \ "key11")(obj)
```
By using this alias, we can remove needless parentheses and path expression becomes clear.
First, I want to use "!!" as haskell. However "!!" cannot be used because it have to start by 'all other special characters' (ref. [6.12.3 Infix Operations](http://www.scala-lang.org/files/archive/spec/2.11/06-expressions.html#infix-operations) ).
I dont have other good ideas anymore, then use same method \ as property access.
It may cause confusing sometimes, but in many case it will be benefit for unified method name.
> Introduce alias of index access on JsPath

- documentation/manual/working/javaGuide/main/sql/JavaDatabase.md
- documentation/manual/working/javaGuide/main/sql/code/JavaApplicationDatabase.java
- documentation/manual/working/javaGuide/main/sql/code/JavaNamedDatabase.java
- documentation/manual/working/scalaGuide/main/sql/ScalaDatabase.md
- documentation/manual/working/scalaGuide/main/sql/code/ScalaControllerInject.scala
- documentation/manual/working/scalaGuide/main/sql/code/ScalaInjectNamed.scala
Currently both links:
https://www.playframework.com/documentation/2.4.x/ScalaDatabase
https://www.playframework.com/documentation/2.4.x/JavaDatabase
containing the old database access API, we should upgrade these Docs that ```DB``` is removed in favor of ```@Inject()(db: Database) or @Inject()(@NamedDatabase("default") db: Database) or @Inject()(dbApi: DBApi)````
As seen here:
http://localhost:9000/@documentation/Migration24
> Documentation for Scala/Java about JDBC Database outdated

- framework/project/Build.scala
- framework/project/Dependencies.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaStreamsConversion.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
*This PR is basically a backport of https://github.com/playframework/playframework/pull/4776, but can be merged independently of it.*
* Moving akka-http from RC2 to RC4.
* Ignored some binary incompatibility reported by MiMa on the
Play-Akka-Http-Server-Experimental project due to the akka-http version bump
(this is OK because the module is experimental, hence we give no binary
compatibility guarantees).
* Had to make `play.it.http.JavaResultsHandlingSpec` and
`play.it.http.ScalaResultsHandlingSpec` running sequentially because they
would fail otherwise (not sure what has changed in akka-http to cause it, but
I assumed it may have been caused by additional asynchronism in the impl).
This is basically a backport of 80a9740c5b325747cb985794dd03accdcf4cef7a
> Bumped akka-http to 1.0-RC4. Re #4774

- framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
The scaladoc implies that the return type is Unit, when it is Future[Unit] -- the example won't compile.
> ApplicationLifecycle.addStopHook has bad example

- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/EnumeratorPublisherSpec.scala
I'd like to backport this to 2.4.x as the test flakiness is causing problems.
> Remove race in EnumeratorPublisherSpec

- framework/project/Build.scala
This will fix the check of compatibility issue introduced in commit 5978b273. `play.test.Helpers.invokeWithContext` was not a static method and now it is.
> Configure mima to filter play.test.Helpers.invokeWithContext

- framework/src/play/src/main/java/play/mvc/Security.java
- framework/src/play/src/test/java/play/mvc/SecurityTest.java
I believe this one simply slid out from 2.4
For reference https://github.com/playframework/playframework/blob/master/framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java receives a class as parameter too (the error); and already is using the injector.
> Allow Authenticator for Security.Authenticated to be injected

- framework/src/play-streams/src/main/scala/play/api/libs/streams/impl/EnumeratorPublisher.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/impl/EnumeratorPublisherSpec.scala
I'm working on #4686, but I've stumbled on this as it was causing a `WSSpec` test to fail after converting the WS API to use Akka streams instead of Iteratees/Enumerators.
review by @richdougherty ;-)
> Propagate failure in `EnumeratorPublisher` impl

- framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
- framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
Transparent HEAD request handling (in [DefaultHttpRequestHandler.handlerForRequest](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala#L125) and [GlobalSettings.onRequestReceived](https://github.com/playframework/playframework/blob/2.4.x/framework/src/play/src/main/scala/play/api/GlobalSettings.scala#L118)) does not tag the request.
This may cause issues for tools that build upon request tags like e.g. [play-statsd](https://github.com/typesafehub/play-plugins/tree/master/statsd) (see [StatsdFilter](https://github.com/typesafehub/play-plugins/blob/master/statsd/src/main/scala/play/modules/statsd/api/StatsdFilter.scala#L47)) or the kamon-play plugin.
Is it intentional, that transparent HEAD requests are not …
> Transparent HEAD request does not contain tags (like e.g. Routes.ROUTE_PATTERN)

- framework/src/play-akka-http-server/src/main/resources/play/reference-overrides.conf
As found out in #4896, with akka-http the request.method is set to GET for a transparent HEAD request.
Steps to reproduce:
- Start with some play-scala app, e.g. using the play-scala template from the templates dir
- Check that there's a route for GET and some path, but no related HEAD route
- Enable akka-http following [the documentation](https://playframework.com/documentation/2.4.x/AkkaHttpServer)
- Print the `request.method` in the route action
- Do a HEAD request for the previously checked route, e.g. `curl -X HEAD http://localhost:9000/`
- In my case (on master branch), using the play-scala template, the `println(s"method: ${request.method}")` results in `method: GET`
- Instead, this should be `method: HEAD`
> Transparent HEAD with akka-http has request method set to GET

- framework/src/play-jdbc/src/main/resources/reference.conf
- framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
Backport of #4901 to 2.4.x. See discussion here about why HikariCP upgrade was avoided:
https://groups.google.com/forum/#!topic/play-framework-dev/nb6HhpT8_-c
> Map HikariCP connectionInitSql property - Backport #4901

- framework/project/Dependencies.scala
- framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java
This commit also seems to fix the tests flakiness that was causing and error
(`Connection reset`) in a few tests.
See https://groups.google.com/forum/#!topic/play-framework-dev/AFLWU-RX4lg for
details.
*Should be backported to 2.4.x*
> Bumped akka-stream and akka-http to 1.0 (fixes tests flakiness)

- documentation/manual/releases/migration24/Migration24.md
Call out that this crucial configuration key has changed. 
Hopefully [[Evolutions configuration|Evolutions#Evolutions-configuration]] ends up linking correctly - please revise if it doesn't.
> "evolutionplugin=disabled" => "play.evolutions.enabled=false"

- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
One thing I didn't manage to do in this commit is reimplementing
`NingWS.executeStream` using Akka Stream. The problem is that I can't find a
convenient solution for attaching a listener to the Ning AsyncHttpClient, so
that the received (response) bytes can be pushed into an Akka Stream `Source`.
For instance, I've tried to use `Source.actorRef` as follow:
val (ref, publisher) = Source.actorRef[NingAsyncHandler].toMat(Sink.publisher)(Keep.both).run() val
source = Source(publisher)
(note: `NingAsyncHandler` is a type extending `akka.actor.Actor`)
The above would return a Reactive Stream `Publisher` (i.e., `publisher`) and an
`ActorRef` that I hoped I could use to feed the bytes to the `publisher` when
the Ning `AsyncHandler.onBodyPartReceived` method is called on the listener. …
> Use Akka Streams for WS streamed response body handling

- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala
The `transform` operations on `OWrites` inherited from `Writes` works with `JsValue` rather than `JsObject`.
Considering...
```scala
val writes = OWrites[Foo] { foo => Json.obj("bar" -> foo.bar) }
```
... the result before transformation is `JsObject` ...
```scala
val result: JsObject = writes(Foo("bar"))
```
..., but if using `.transform`, it works with `JsValue` and result in a `Writes`.
```scala
val transformed = writes.transform { js: JsValue => ??? }
val written: JsValue = transformed.writes(Foo("bar"))
```
After the changes, it can works with `JsObject` and results in a `OWrites`:
```scala
val transformed: OWrites[Foo] = writes.transform { obj: JsObject =>
obj ++ Json.obj("time" -> time)
}
val result: JsObject = transformed.writes(Foo("Lorem"))
```
> Keep JsObject specificity when transforming OWrites

- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
Since `Helpers` implement `HeaderNames`, `Status` and `HttpProtocol`. Handy for testing: 
```
contentType(home) must beSome.which(_ == HTML)
```
> Make scala Helpers implement MimeTypes

- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/StreamedResponse.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSAPI.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSClient.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSResponseHeaders.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSClient.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSRequest.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/util/CollectionUtil.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/StreamedRequest.scala
Introduced a `stream()` method in the Java WS API that closely emulates its
Scala counterpart. The only difference is that instead of returning a `Tuple2`,
it returns a `StreamedResponse`. I felt this is more idiomatic for Java users,
and I'm actually of the idea that we may want to do the same in Scala (but this
might be a matter of personal taste, so I'm raising the point here to see what
you think).
Currently, the Java WS streaming functionality relies on the Scala one, which is
based on iteratees. The plan is to change this and use akka stream, but #4952
needs to be addressed first.
> Added async streaming to the Java WS API. Fix #4973

- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
Documentation on `PathBindable` contains sample code that will not compile as it calls a method that doesn't exist: `intBinder.unbind` with only one argument. This commit simply fixes it to the correct call passing `key` along.
> Update documentation on PathBindable to valid code

- documentation/manual/working/scalaGuide/main/json/ScalaJsonHttp.md
Fix a sentence that uses attributive clause without relative pronoun.
> minor grammatical correction

- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
This has been reported in #4554 and #4561  and fixed in #4743, though the fix has been merged to master and not to 2.4.x. Would it be possible to backport this fix?
Fix for #5024 - Changed log level to debug for actor system initialization.
> Don't log when Akka is started

- framework/project/Dependencies.scala
- framework/src/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
- framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
HikariCP 2.4.x stream will be binary compatible with 2.4.1 as mentioned in
https://groups.google.com/forum/#!topic/play-framework-dev/iqKgOqa3McM.
The changelog for this release can be read here:
https://groups.google.com/forum/#!topic/hikari-cp/FGygaj_yrxg
Also, note that HikariCP 2.4.0 inadvertently broke binary compatibility and
hence was flagged as a bad release.
Finally, the `HikariDataSource.shutdown` method was deprecated, so I've replaced
it with the `close` method.
> Bumped HikariCP version to 2.4.1

- framework/bin/testDocumentation
We don't actually need to do a publish local on Play from test documentation since the documentation project depends directly on Play, so I've removed this.  This should shave a small amount of time off the documentation build.
> Removed publishLocal from testDocumentation script

- documentation/manual/hacking/Documentation.md
We now are able to extract sbt file snippets, so I upgraded the documentation guidelines to reflect this.
> Updated documentation guidelines for sbt settings

- documentation/project/Build.scala
The documentation build tests appears to be being killed by Travis, possibly due to using too much memory. This will hopefully fix that.
> Added memory limits to the documentation build

- documentation/manual/releases/migration24/Migration24.md
- documentation/manual/working/javaGuide/main/sql/JavaJPA.md
- documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
Add notice to the documentation that we need the
PlayKeys.externalizeResources to be false in order to deploy a Play 2.4
App with JPA enabled.
> Add documentation about JPA with Play 2.4 in dist mode

- framework/src/play/src/main/scala/play/api/libs/MimeTypes.scala
Single-line commit.
Add support for detecting MIME for `.woff2` files.
Currently, `.woff2` files returned as `Content-Type: application/octet-stream`.
Short info about WOFF2:
https://gist.github.com/sergejmueller/cf6b4f2133bcb3e2f64a
Current support in browsers:
http://caniuse.com/#feat=woff2
> Add WOFF2 font MIME into MimeTypes.

- documentation/manual/detailedTopics/build/SBTSubProjects.md
- documentation/manual/detailedTopics/build/code/SubProjectsAssetsBuilder.scala
Which cause this compilation error :
```
not enough arguments for constructor AssetsBuilder: (errorHandler: play.api.http.HttpErrorHandler)controllers.AssetsBuilder
```
> Doc multi-projects missing Assets HttpErrorHandler argument

- framework/src/play/src/main/scala/play/core/routing/GeneratedRouter.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/routes-compiler/src/test/resources/generating.routes
- framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala
Fixes #4243 
The change intends to be as minimal and as less intrusive as possible. It removes the coupling between call method and FunctionN, so that controllers with an arbitrary amount of parameters can be used in routes definitions.
Quoting @jroper:
Performance wise, it introduces a new instanceof check for each parameter, since the type information is lost and then regained in the extractor.  I don't think that's anything to worry about, our performance tests should pick up any regressions here anyway.  If it were a problem, we could keep the callN methods for, say, up to 6 parameters, and switch to using a list for anything over that.  But I don't think it's a big deal.
> Changing RoutesCompiler and Router to work with controller definitions with 22+ parameters

- framework/bin/test
- framework/bin/testSbtPlugins
- framework/bin/testTemplates
Turn on quickPublish mode (a command I wrote for Play that turns off generation of API docs and source artifacts) when running the build on Travis. This should shave a minute or two off build times.
> Use quickPublish

- framework/project/Dependencies.scala
This should fix a big part of https://github.com/playframework/playframework/issues/4649
> Upgrade to Akka 2.3.13 to fix permgen leak

- framework/src/play/src/main/scala/views/play20/welcome.scala.html
Just a minor fix to the formatting on the welcome page.
> Format `build.sbt` as code

- documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
- framework/src/play-integration-test/src/test/java/play/it/http/websocket/WebSocketSpecJavaActions.java
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play/src/main/java/play/http/websocket/Message.java
- framework/src/play/src/main/java/play/libs/F.java
- framework/src/play/src/main/java/play/libs/Scala.java
- framework/src/play/src/main/java/play/libs/streams/AkkaStreams.java
- framework/src/play/src/main/java/play/mvc/LegacyWebSocket.java
- framework/src/play/src/main/java/play/mvc/WebSocket.java
- framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala
- framework/src/play/src/main/scala/play/core/j/JavaWebSocket.scala
- framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
- framework/src/play/src/test/java/play/mvc/LegacyWebSocketTest.java
This makes the Java `WebSocket` a simple function that returns a future of either a result, or the flow to handle the WebSocket.
I renamed the existing `WebSocket` class to `LegacyWebSocket`.
> Java WebSocket with Akka streams support

- framework/src/play-server/src/main/scala/play/core/server/common/ForwardedHeaderHandler.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
I have a Play application that serves an internal API accessed from another server in the same network. The caller hits the api through a reverse proxy which also sits in the same network.
So it's like the following situation and I have the `trustedProxies` set to `192.168.1.1/24`.
```
Client    ->    Proxy    ->     API
192.168.1.1    192.168.1.2    192.168.1.3
```
The proxy sets the `X-Forwarded-For` header to `192.168.1.1`. ForwardedHeaderHandler currently drops hosts within the range of `trustedProxies`, so Play handles the request as if there were no Forwarded headers at all, and therefore the `remoteAddr` becomes `192.168.1.2`.
ForwardedHeaderHandler should not drop the first entry of Forwarded header even if it's in the `trustedProxies` range.
> Treat the first Forwarded header as non-proxy

- documentation/manual/detailedTopics/configuration/ws/CipherSuites.md
Fixes https://github.com/playframework/playframework/issues/4877 by fixing documentation from `enabledCiphers` to `enabledCipherSuites`.
> Fix CipherSuites documentation

- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/Build.scala
This was missed in #5091, as pointed out by @cchantep
> Removed last reference to Scala 2.10

- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
The ContravariantFunctor instance for Writes was commented out in 2be3e0815dc5b4e8629bbbc. I have found that this instance could have been useful in a few cases, and it seems like there is currently no problem in enabling it.
> Uncomment ContravariantFunctor instance for Writes

- framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonExtensionSpec.scala
Fixes #2031 
The json macro should always generate using the primary constructor of the case class.
As far as I can tell this was 99% implemented already. There was some logic to detect the correct apply method from several alternatives. We just need to use `asTerm` instead of `asMethod` as the error in #2031 indicates.
> Fix Json.format macro for classes with custom apply method

- framework/project/Dependencies.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
The Proxi API has changed a bit in this async-http-client (AHC) release.
Specifically, `HTTPS` protocol can no longer be specified for a proxy instance.
The reason is that  now you can configure both regular and secured ports on a
single instance, hence the `HTTPS` protocol is not needed anymore.
An additional feature offered by AHC is that it now allows to configure different
ports for HTTP and HTTPS. Exposing this feature in Play would require us to
change the Play `WSProxyServer` and add a new member to configure a secure port.
This should be straightforward to implement, but I'm not sure we need it, so I
haven't done it.
> Bumped async-http-client version to 2.0.0-alpha12

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/MyController.java
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play/src/main/java/play/mvc/StatusHeader.java
* Added `sendEntity` to the Java Results API
* Improvements in Scala WS documentation
* Documentation for streaming request's bodies for Scala/Java
* Java documentation for streaming response bodies
> Documentation for ws streaming request/response body for both Scala and Java

- framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/javascriptReverseRouter.scala.twirl
- framework/src/routes-compiler/src/test/resources/complexNames.routes
- framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesCompilerSpec.scala
- framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/conf/routes
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/assets/JavaScriptRouterSpec.js
fix #4693
Parameter identifiers are being checked against Java identifiers policy,
this adds support for valid backticked Scala identifiers.
> Allow backticks quoted parameters in routes

- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
- framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/forwardsRouter.scala.twirl
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/conf/routes
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/conf/routes
Fixes #5134
The routes generator generates a number of String constants. If these constants contain something that look like an interpolated string, eg, they have "$foo" and foo is an identifier in scope, the Scala compiler will output a warning about a possible missing interpolator.  This change encodes Strings to work around this heuristic, avoiding false positive warnings, both from the generated path String (which uses $ to indicate path parameters), and from comments.
> Routes compiler doesn't generate interpolator warnings

- framework/project/Dependencies.scala
PR #5137 requires this PR to be merged first.
> Bumped typetools' version so that codebase compiles w/ JDK 1.8.0_u60. Fix #5136

- framework/src/play-java/src/main/java/play/inject/DelegateApplicationLifecycle.java
- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play/src/main/java/play/inject/ApplicationLifecycle.java
- framework/src/play/src/main/scala/play/api/Application.scala
- framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
Using an existential type instead of a specific `Unit` or `Void` allows
for better code reuse, and avoids having to map a `Future`/`CompletionStage`
just to make the compiler happy.
We do the same in many places when using an Akka Streams `Source`.
This change was inspired by #5137.
> ApplicationLifecycle stop hook can take an existential type

- documentation/manual/detailedTopics/production/HTTPServer.md
Secure schema information is in header X-Forwarded-Proto not X-Scheme
see https://github.com/playframework/playframework/pull/1823
> Secure schema information is in header X-Forwarded-Proto not X-Scheme

- documentation/manual/releases/Migration25.md
As originally discussed here: https://groups.google.com/forum/#!topic/play-framework-dev/UozJ3ysXESk
> Update 2.5 migration guide re: functional interfaces that don't allow exceptions

- documentation/manual/releases/Migration23.md
Fixed migration documentation. CoffeeScript option is `sourceMap` and not `sourceMaps` as it was on the migration documentation.
> Fixed migration documentation.

- framework/src/play/src/main/java/play/mvc/Security.java
As far as I can tell there's no reason to rethrow exceptions as `RuntimeException`. We can just let all exceptions pass through.
Fixes #5200
> Don't catch and rethrow exceptions in AuthenticatedAction

- framework/src/play-cache/src/main/java/play/cache/CachedAction.java
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
- framework/src/play-integration-test/src/test/java/play/routing/RoutingDslTest.java
- framework/src/play-integration-test/src/test/scala/play/it/bindings/GlobalSettingsSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JAction.scala
- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSAPI.java
- framework/src/play/src/test/java/play/mvc/SecurityTest.java
- framework/src/play/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
All of these instances seemed pretty safe to replace. I didn't change any of the public APIs.
> Replace uses of F.Promise with CompletableFuture

- documentation/manual/gettingStarted/Tutorials.md
The Play Java Intro link goes to a missing page. The correct URL is https://typesafe.com/activator/template/play-java-intro
> Solve dead link in Tutorials.md

- documentation/manual/detailedTopics/database/Developing-with-the-H2-Database.md
Added a caveat section to H2 page mentioning ``DATABASE_TO_UPPER` flag + minor improvement in `Prevent in memory DB reset` section.
Adding this flag to the database url was the only way I found to make H2 in Postgres mode work with Play Evolutions. Mentioning it here is harmless as well and might save some time from other developers.
> Caveat of using H2 Postgres compat mode to 2.3.x

- framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
- Chrome and FireFox are both aggresssively deprecating SHA1 signatures,
making it difficult to use https for local development. This change
creates the default self-signed certs with SHA256-RSA, eliminating
the deprecation errors.
> Generate self-signed certificates with SHA-256

- framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
- Add the signature algorithm to the key rebuild check criteria
- Chrome and FireFox are both aggresssively deprecating SHA1 signatures,
making it difficult to use https for local development. This change
creates the default self-signed certs with SHA256-RSA, eliminating
the deprecation errors.
> Generate self-signed certificates with SHA-256 - 2.4.x

- framework/project/Dependencies.scala
SBT's notTransitive declaration is ignored when generating a pom.xml (see https://github.com/sbt/sbt/issues/2276), which, since we publish maven style, means it has no effect outside of the Play project itself.
Instead, it must be replaced with individual exclusions.  In particular, the findbugs annotations dependency from reflections must be excluded, because it's LGPL, which prevents Play users from distributing a Play application under their own license.
> Remove use of notTransitive

- documentation/manual/working/javaGuide/advanced/routing/JavaRoutingDsl.md
- documentation/manual/working/javaGuide/advanced/routing/RequestBinders.md
- documentation/manual/working/javaGuide/advanced/routing/code/AppLoader.scala
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide.binder.routes
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/BinderApplication.java
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/AgeRange.java
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/User.java
- documentation/manual/working/javaGuide/advanced/routing/code/router/RoutingDslBuilder.java
- documentation/manual/working/javaGuide/advanced/routing/index.toc
- documentation/manual/working/javaGuide/main/http/JavaRouting.md
- documentation/manual/working/scalaGuide/advanced/routing/ScalaRequestBinders.md
- documentation/manual/working/scalaGuide/advanced/routing/ScalaSirdRouter.md
- documentation/manual/working/scalaGuide/advanced/routing/code/SirdAppLoader.scala
- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide.binder.routes
- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/controllers/BinderApplication.scala
- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/AgeRange.scala
- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala
- documentation/manual/working/scalaGuide/advanced/routing/index.toc
- documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
Following discussion with @benmccann  with reference to issue #4586 and #4587, updates documentation basically in 2 areas.
1 - Custom binding
2 - Router config
1 - Custom binding with `PathBindable` and `QueryStringBindable` is described in new pages `RequestBinders` and `ScalaRequestBinders` under `advanced routing`,  providing code examples on how to use binders.
2 - Router config includes a new link to `advanced routing` page in last section of `JavaRouting` and `ScalaRouting`, and a new section at the end of `ScalaSirdRouter` and `JavaRoutingDsl` with possible  alternatives to provide a custom sird/DSL router to the application.
> update documentation for #4585 and #4586

- documentation/manual/detailedTopics/production/cloud/Deploying-Boxfuse.md
- documentation/manual/detailedTopics/production/cloud/DeployingCloud.md
- documentation/manual/detailedTopics/production/cloud/index.toc
Dear Play Team,
this pull request add Boxfuse and AWS to the cloud deployment section of the documentation.
Best regards,
Axel
P.S.: I have signed the Typesafe CLA
> Added Boxfuse and AWS to the cloud deployment documentation

- documentation/manual/detailedTopics/production/cloud/Deploying-Boxfuse.md
- documentation/manual/detailedTopics/production/cloud/DeployingCloud.md
- documentation/manual/detailedTopics/production/cloud/index.toc
Dear Play Team and @marcospereira ,
this pull request adds Boxfuse and AWS to the cloud deployment section of the documentation and is a backport of #5263 .
Best regards,
Axel
P.S.: I have signed the Typesafe CLA
> Backported Boxfuse and AWS Cloud Deployment Docs to 2.4.x

- documentation/manual/detailedTopics/production/Deploying-Boxfuse.md
- documentation/manual/detailedTopics/production/DeployingCloud.md
Dear Play Team and @marcospereira ,
this pull request adds Boxfuse and AWS to the cloud deployment section of the documentation and is a backport of #5263 .
Best regards,
Axel
P.S.: I have signed the Typesafe CLA
> Backported Boxfuse and AWS Cloud Deployment Docs to 2.3.x

- documentation/manual/releases/migration24/Migration24.md
The expression 'gory details' was mistaken for 'glory details'
> Fix eggcorn in 2.4 migration guide

- framework/project/Dependencies.scala
- framework/src/play-netty-server/src/main/resources/reference.conf
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
This is I think the most minimal changes necessary to support integration of [netty native socket](http://netty.io/wiki/native-transports.html).
Starting from `4.0.32` netty supports `TCP_FASTOPEN` for native socket, a feature that which I think will be great to have in playframework.
> Support Netty native socket transport

- framework/project/plugins.sbt
Apparently, the MiMa version was already updated in the 2.4.x branch - see
5cf284ab12ef64fdeae94f11cc977743f094d918
> Updated MiMa version to 0.1.8

- .gitignore
- framework/project/Build.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala
- framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/HttpPipeliningSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala
- framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala
- framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala
- framework/src/play/src/main/scala/play/api/http/websocket/CloseCodes.scala
- framework/src/play/src/main/scala/play/api/http/websocket/Message.scala
Removed all uses of iteratees in tests where Akka streams is appropriate.  Of course, when testing things that use iteratees, it still uses iteratees.
One of the bigger tasks were was converting the WebSocket client to use Akka streams, and I also upgraded it to Netty 4.
> Replaced iteratees with Akka streams in tests

- documentation/manual/scalaGuide/advanced/iteratees/Enumeratees.md
Changed "Enumeratee.mapImput" to "Enumeratee.mapInput"
> Fixed a typo (Enumeratee.mapImput)

- framework/src/play-server/src/main/scala/play/core/server/common/ForwardedHeaderHandler.scala
- framework/src/play-server/src/main/scala/play/core/server/common/NodeIdentifierParser.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
- framework/src/play-server/src/test/scala/play/core/server/common/NodeIdentifierParserSpec.scala
- framework/src/play-server/src/test/scala/play/core/server/common/SubnetSpec.scala
Fixes #5299.
Parsing for `Forward` and `X-Forwarded-*` headers no longer throws exceptions if an invalid header is found. Now a debug log message is thrown instead. This reverses the stricter errors introduced in #5266.
Additional changes were made:
- Don't bother parsing the supplied IP address headers if we don't trust the connection that supplied it.
- Support values in Forward headers surrounded with double quotes. This is needed to support IPv6.
- Support IPv6 values in X-Forwarded-For headers even when they don't have surrounding square brackets. This format is commonly supplied by proxies.
> More fixes to forward header parsing

- documentation/manual/ModuleDirectory.md
Most of these only support Play 2.2 at the latest, so they certainly won't work with master, which is removing plugins support in favor of modules
> Remove plugins from the module directory that have been unmaintained for a long time

- framework/project/Build.scala
- framework/project/Dependencies.scala
Builds the routes compiler library for 2.11 as well as 2.10. Based on @jroper's [suggestion](https://github.com/playframework/playframework/pull/5291#issuecomment-160805748).
See #5290 and #5291.
> Cross-build support for routes compiler

- documentation/manual/detailedTopics/configuration/Configuration.md
- framework/src/fork-run/src/main/scala/play/forkrun/ForkRun.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
- framework/src/run-support/src/test/scala/play/runsupport/FilterArgsSpec.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Adds devSettings into filterArgs so that the port can be changed from build.sbt.
Fixes https://github.com/playframework/playframework/issues/4629
> Allow devSettings to change port

- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
`CSRF.global` is defined as 
```scala
def global = Play.maybeApplication.map(_.injector.instanceOf[CSRFConfig]).getOrElse(CSRFConfig())
```
There is no `apply` method defines on `CSRFConfig` object, so when using compile time dependency injection, calling global will result in `MethodNotFoundError` at runtime.
The associated changes add a new method to `CSRF ` to retrieve a token accepting a `CSRFConfig` as an argument so that `CSRFAction` is usable with runtime dependency injection.
@richdougherty I would like to backport this fix for `2.4.x` and include it in `2.4.5` if you are fine with the changes.
> Use CSRF config rather than the global one which is not available with compile time dependency injection

- framework/src/play/src/main/java/play/GlobalSettings.java
Ongoing work for #5309.  Deprecates the Java version of `play.GlobalSettings` -- missed this in https://github.com/playframework/playframework/pull/5339 -- and removed some Deprecated methods in `play.GlobalSettings`.
> Deprecate play.GlobalSettings

- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- framework/src/play/src/main/scala/play/api/Configuration.scala
Remove a load method from `play.api.Configuration`, as part of on-going work for #5309.
Lower in priority than #5323
> Remove deprecated methods from Configuration

- documentation/manual/scalaGuide/main/templates/ScalaCustomTemplateFormat.md
Play version 2.3.x and 2.4.x use more complicated versions of the Twirl BufferedContent[A] and Format[T] than were documented here. The examples based on Html have been updated to be in line with the latest tagged Twirl API, 1.0.4.
> Make custom template docs reflect new Twirl API

- framework/src/play/src/main/java/play/mvc/Http.java
This fixes a bug where if the request builder gets a relative uri the default localhost host header is overwritten to null.
E.g. ```new RequestBuilder().uri("/foo")``` would have the host header set to null
If this could be backported to 2.4.x I'd appreciate it.
> Don't overwrite existing host header if uri is a relative path

- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/routes-compiler/src/test/scala/play/routes/compiler/templates/TemplatesSpec.scala
This commit fix a bug introduced by PR #5129 as routes parameters have
different name than those being used locally on the generated reverse
routing code.
The error occured because some javsacript code generated by routes
compiler code were not using localnames map when referencing route
parameters, causing js errors as the local variables on js has a
different name than its route parameter counterpart.
> use localname for javascript reverse routes. fix #5340

- framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
I found them missing when navigating the code and while not strictly necessary IMHO adding the return type is a good idea in general for public API.
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)
> Annotate return type of `JsLookupResult.validate` and `JsValue.validate`

- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyHeadersWrapper.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-netty-server/src/test/scala/play/core/server/netty/NettyHeadersWrapperSpec.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
This change improves performance by about 4000 requests/s on a simple benchmark.
*The comments below no longer apply. I'm using a simpler implementation as suggested by @jroper.*
~~This change improves performance by about 5% on a simple benchmark.~~
~~The standard Play `Headers` implementation is slow. `Headers` are stored as a sequence of string pairs. Accessing a single header value involves converting the pairs into a `Map` of headers and sequences of values then converting the sequence to an `Option`.~~
~~We can improve performance on each request by introducing a new `Headers` implementation that wraps the Netty headers data structure and delegates calls directly to Netty where possible. This saves a lot of work in the common case of reading header values because Netty has a fast …
> Add optimized Headers implementation for Netty

- documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/Module.java
- documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/dynamic/Module.java
- documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/eager/Module.java
- documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaDependencyInjection.md
- documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/RuntimeDependencyInjection.scala
- framework/src/play/src/main/scala/play/api/inject/Module.scala
With many things in Play, a conventional, zero config way of providing a component is allowed by creating a particular class in the root package that implements that component.  For example, filters can be provided by putting an implementation of the `HttpFilters` class in a class called `Filters` in the root package.
The same should be done for modules - there should be a conventional location to put a module in the root package that allows the inclusion of that module with zero configuration.
Given that we usually encourage users to implement Guice's `AbstractModule` rather than Plays `Module`, I don't think we need to worry about the naming collision of `Module`, so I think `Module` would be a good name for it, and this is in keeping with the naming conventions for other conventional …
> Provide a conventional way to provide a module

- framework/project/Dependencies.scala
- templates/play-scala-intro/build.sbt
- templates/play-scala/build.sbt
Fix for https://github.com/playframework/playframework/issues/5396
> Use the latest version of specs2 which no longer requires bintray resolver

- framework/src/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala
- framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
- framework/src/play-server/src/test/scala/play/core/server/ssl/FakeKeyStoreSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmCheckerSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/AlgorithmsSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/CompositeX509KeyManagerSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/CompositeX509TrustManagerSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/ConfigSSLContextBuilderSpec.scala
Fixes https://github.com/playframework/playframework/issues/5367
Moves CertificateGenerator into Play-Server, so it can be used in specs in both Play-WS and Play-Server.
> Fix FakeKeystore being regenerated

- framework/src/play-functional/src/main/scala/play/api/libs/functional/Applicative.scala
- framework/src/play-functional/src/main/scala/play/api/libs/functional/Functors.scala
- framework/src/play-functional/src/main/scala/play/api/libs/functional/Monoid.scala
- framework/src/play-functional/src/main/scala/play/api/libs/functional/Products.scala
- framework/src/play-functional/src/main/scala/play/api/libs/functional/syntax/package.scala
Every now and again, I ask for an implicit `FunctionalCanBuild[F]` for some `F` who as an implicit `Applicative[F]` instance and can not get it unless I explicitly import `play.api.libs.functional.syntax.functionalCanBuildApplicative`.
This PR fixes this situation so that no additional import is required. By the way, I also moved some other instances (of `Functor`, `Applicative` and `Monoid`) in thteir companion objects.
> Move implicit instances definitions in companion objects

- framework/src/play/src/main/java/play/libs/F.java
- framework/src/play/src/main/java/play/mvc/WebSocket.java
`Function0` and `Callback2` have been removed but still used in comments. Probably it was overlooked.
> Java doc fixes

- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
Changes the connection handler in the NettyServer from using an Akka Streams approach to using a straight handler.  Modest improvements, but cuts down on context switch.
cc @jroper
> Replace the connection handler in netty core.

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSModule.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/Streams.scala
```FlowMaterializer``` was a trait in early versions of akka-stream that later was renamed to ```Materializer```. In Filters-Helpers code, there are some identifier names derived from ```FlowMaterializer``` name, but some are already named ```materializer```, so naming is inconsistent. 
This naming is quite important when using compile-time DI since in ```BuiltInComponents```  there is a val named ```materializer```, which is not compatible with ```def flowMaterializer``` in ```CORSComponents```.
This is my first PR for Play framework, I hope I didn't break any rules.
> Rename identifiers named "flowMaterializer" to "materializer"

- documentation/manual/detailedTopics/build/code/SubProjectsAssetsBuilder.scala
Hi. I found the problem in the documentation(https://www.playframework.com/documentation/2.4.x/SBTSubProjects#Assets-and-controller-classes-should-be-all-defined-in-the-controllers.admin-package), so fixed the description. Please review my change.
Defining a custom `Assets` by the way described in the doc causes the following errors:
```
--- (Running the application, auto-reloading is enabled) ---
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9401
(Server started, use Ctrl+D to stop and go back to the console...)
[info] Compiling 10 Scala sources and 2 Java sources to /Users/shinnya/tmp/sample/target/scala-2.11/classes...
[error] /Users/shinnya/tmp/sample/conf/routes:9: type Assets is not a member of package controllers.admin
[error] GET     /assets/*file …
```
> Fix the code in the documentation for defining custom `Assets' for sub projects.

- framework/src/play-java-ws/src/main/java/play/libs/ws/WS.java
- framework/src/play-java-ws/src/test/scala/play/libs/oauth/OAuthSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
Deprecates some WS.client methods that assume use of Play.current.
Update some scaladoc in WS that is no longer accurate with the codebase.
> Deprecate WS static methods that use Play.current under the hood.

- documentation/manual/ModuleDirectory.md
Adding info on integration a Typescript compiler in sbt. The one mentioned in the 2.4 docs (https://github.com/mumoshu/play2-typescript) does not work.
I have personally tested the plugin sucessfully with Play 2.4.4 and 2.4.6 but should support 2.5 as well according to the site.
> Update ModuleDirectory.md with info on Typescript integration

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
- framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java
- framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala
The optimisation here is that when there is no body, *and* the accumulator was created using Accumulator.done (ie, the Accumulator isn't interested in the body), rather than feeding an empty source into a cancelled sink to get the result of the accumulator, the result is passed directly.  This avoids needing to materialize an Akka streams flow.
Testing this with prune on vegimite, I've seen the scala-di-simple tests run at 70K req/s, almost twice as fast as the current master speed (which was down at 36K req/s due to a regression introduced in the Akka streams 2 upgrade), 18K req/s faster than the pre Akka streams 2 speeds, and 12K req/s faster than Play 2.4.
> Optimised accumulators

- documentation/manual/working/javaGuide/advanced/http/JavaHttpRequestHandlers.md
- framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionRequestHandler.java
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
- framework/src/play/src/main/scala/play/core/j/JavaAction.scala
- framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala
Finally fixes #1088
To keep backward compatibility I choose to add a config setting - the default stays like it is right now.
But you can now set `play.http.actionComposition.executeRequestHandlerActionFirst=true`.
The fix was quite easy: In `JavaAction.scala` we just need to change the order of how the actions are delegated.
> Action of request handler can now be executed before action composition

- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
fixes https://github.com/playframework/playframework/issues/5474
> [scaladoc] remove misleading "default" for GlobalSettingsHttpErrorHandler

- documentation/manual/detailedTopics/build/SBTSubProjects.md
There's some bits that need more detailed explanations in the SBT subprojects -- like `InjectedRoutesGenerator` not applying to subprojects automatically.
> [doc] Add expanded section for play projects to SBTSubProject.md

- documentation/manual/working/javaGuide/main/application/JavaEssentialAction.md
- documentation/manual/working/javaGuide/main/application/JavaHttpFilters.md
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/EssentialLoggingFilter.java
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/Filters.java
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/LoggingFilter.java
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/RoutedLoggingFilter.java
- documentation/manual/working/javaGuide/main/application/index.toc
- documentation/manual/working/scalaGuide/main/application/ScalaEssentialAction.md
- documentation/manual/working/scalaGuide/main/application/ScalaHttpFilters.md
- framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
- framework/src/play/src/main/java/play/mvc/Action.java
- framework/src/play/src/main/java/play/mvc/EssentialAction.java
- framework/src/play/src/main/java/play/mvc/EssentialFilter.java
- framework/src/play/src/main/java/play/mvc/Filter.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/core/Execution.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Adds the necessary `EssentialAction` and `EssentialFilter` classes required to create filters from Java. Note that `play.mvc.Action` does not extend `EssentialAction`. I think this is okay for now, but I would like to eventually create a functional API for Java so Java users can construct actions similar to how it's done in Scala.
This will also allow us to create a Java API for `play.api.http.HttpRequestHandler` that actually handles requests at a low level.
> Java EssentialFilter/EssentialAction API

- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
- framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- framework/src/play-specs2/src/test/scala/play/api/test/SpecsSpec.scala
- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
- framework/src/play-test/src/test/java/play/test/WithApplicationTest.java
- framework/src/play-ws/src/main/scala/play/api/test/WSTestClient.scala
- framework/src/play/src/main/scala/play/api/GlobalSettings.scala
- framework/src/play/src/main/scala/play/api/Play.scala
- framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
- framework/src/play/src/main/scala/play/api/libs/Crypto.scala
- framework/src/play/src/main/scala/play/api/libs/Files.scala
- framework/src/play/src/main/scala/play/api/libs/JNDI.scala
- framework/src/play/src/main/scala/play/api/libs/MimeTypes.scala
- framework/src/play/src/main/scala/play/api/mvc/Action.scala
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
- framework/src/play/src/main/scala/play/api/mvc/Controller.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/main/scala/play/api/mvc/Security.scala
- framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
Deprecate the static `Play.current` and `Play.maybeApplication` methods.
Note that this is less dramatic than it seems, since there's new `private[play] privateMaybeApplication` method call and most of the internal applications are still using it.  There's also a route compiler which isn't under the play package which I had to account for.
I have not attempted to refactor any of the major offenders, such as Assets or CSRF.  Searching for `privateMaybeApplication` should show where we have internal dependencies.
> Deprecate Play.current and Play.maybeApplication

- documentation/manual/detailedTopics/evolutions/Evolutions.md
- framework/src/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java
- framework/src/play-jdbc-evolutions/src/main/resources/reference.conf
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
- framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala
- framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsSpec.scala
- framework/src/play-jdbc/src/main/resources/reference.conf
Fixes #2286
You can now set `play.evolutions.schema` (or `play.evolutions.db.default.schema`) to define the schema in which the `play_evolutions` and `play_evolutions_lock` tables will be stored in.
> Allow to set schema for play_evolutions(_lock) table

- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/project/Dependencies.scala
- framework/src/play-akka-http-server/src/main/scala/akka/http/play/WebSocketHandler.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-integration-test/src/test/java/play/it/http/websocket/WebSocketSpecJavaActions.java
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala
- framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java
- framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/AkkaStreams.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
- framework/src/play/src/main/java/play/http/HttpEntity.java
- framework/src/play/src/main/java/play/libs/streams/AkkaStreams.java
In addition, this upgrades to the Akka streams and HTTP libraries that are now part of Akka 2.4.2.
I had to disable one Akka HTTP test due to a regression in Akka HTTP, this has been reported in https://github.com/akka/akka/issues/19623.
> Upgrade to Akka 2.4.2-RC1

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/scala/play/core/server/ServerProvider.scala
- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
In most places the stop hook callback return type was already generalized to
`Future[_]`, so this commit is only finishing the work and updating the few
places where `Future[Unit]` was still used.
The change is source compatible. Furthermore, it removes the need of having to
map futures when their inner type isn't `Unit`.
> Generalized stop hook callback return type

- framework/src/play/src/main/scala/views/helper/select.scala.html
- framework/src/play/src/test/scala/views/html/helper/HelpersSpec.scala
Allow a list of disabled items to be passed in using a second special attribute.
Also update the example to show how all features work.
I'm happy to do this another way if there is a sensible alternative.
> #5177: Allow adding of disabled attribute to items in html select tag.

- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
- framework/src/play/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala
Introduced a new method in GuiceApplicationBuilder named shouldDisplayLoggerDeprecationMessage that checks the logger path for any of the deprecated values DEBUG/WARN/INFO/ERROR and in case of a deprecated value it returns true. This is then used instead of the old call that checked if the path contained the logger key.
> #4574: Improve the case of when to display the logger configuration deprecation message

- templates/play-java-intro/conf/logback.xml
- templates/play-java/conf/logback.xml
- templates/play-scala-intro/conf/logback.xml
- templates/play-scala/conf/logback.xml
The documentation points to a logback.xml configuration that uses an ASYNCFILE / ASYNCSTDOUT appender, but the tempates use straight stdout and no file.  This is confusing -- they should all start from the same place, and there's no reason (that I can tell) that you'd want to remove file logging.
https://www.playframework.com/documentation/2.4.x/SettingsLogger#Default-configuration
> Configure templates with default logback.xml template

- framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala
Fixes #4808 - see it's comments.
When we fail to [create an injector](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala#L138) an exception gets thrown which we catch and [look for](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala#L140-L144) a `PlayException` via `getCause`.
The problem here is that a `CreationException` does **not** return a cause when you call `getCause` on it (it's `null`). That's because of how the `CreationException` gets [created](https://github.com/google/guice/blob/4.0/core/src/com/google/inject/internal/Errors.java#L466).
Instead, we are able to access errors via …
> Catch and re-throw PlayException which is enclosed in CreationException

- framework/src/iteratees/src/test/resources/logback-test.xml
- framework/src/play-cache/src/test/resources/logback-test.xml
- framework/src/play-filters-helpers/src/test/resources/logback-test.xml
- framework/src/play-java-jdbc/src/test/resources/logback-test.xml
- framework/src/play-java-jpa/src/test/resources/logback-test.xml
- framework/src/play-java-ws/src/test/resources/logback-test.xml
- framework/src/play-java/src/test/resources/logback-test.xml
- framework/src/play-jdbc-evolutions/src/test/resources/logback-test.xml
- framework/src/play-jdbc/src/test/resources/logback-test.xml
- framework/src/play-json/src/test/resources/logback-test.xml
- framework/src/play-server/src/test/resources/logback-test.xml
- framework/src/play-specs2/src/test/resources/logback-test.xml
- framework/src/play-streams/src/test/resources/logback-test.xml
- framework/src/play-test/src/test/resources/logback-test.xml
- framework/src/play-ws/src/test/resources/logback-test.xml
- framework/src/routes-compiler/src/test/resources/logback-test.xml
- framework/src/run-support/src/test/resources/logback-test.xml
- framework/src/sbt-plugin/src/test/resources/logback-test.xml
Suppress spurious logback warnings
This is needed because multi-module projects are very hard to segment correctly so there is only one logback-test.xml.  In addition, we're also getting `No appenders present in context [default] for logger [play.api.mvc.Cookies]` when the test seems to run before logback has initialized correctly.
If we need to do slf4j testing specifically, worth looking at https://github.com/portingle/slf4jtesting
> Suppress spurious logback warnings

- framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
- framework/src/play/src/main/java/play/mvc/EssentialAction.java
- framework/src/play/src/main/java/play/mvc/EssentialFilter.java
- framework/src/play/src/main/java/play/mvc/Filter.java
- framework/src/play/src/main/scala/play/api/mvc/Action.scala
- framework/src/play/src/main/scala/play/api/mvc/Filters.scala
With the `asJava` method on `EssentialFilter`, now Java users can extend (by composition) existing Scala filters using the Java API.
> Conversions for Java filters

- documentation/manual/releases/Migration25.md
- documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/static.sbt
- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
- framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/app/controllers/Application.scala
- framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/app/controllers/Application.scala
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/controllers/Application.scala
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.1
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.2
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.3
- framework/src/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/changes/Application.scala.1
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/changes/Application.scala.2
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/changes/Application.scala.3
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/test
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/module/ModuleController.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/πø$7ß.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/Application.scala
- templates/play-java-intro/build.sbt
- templates/play-java/build.sbt
- templates/play-scala-intro/build.sbt
- templates/play-scala/build.sbt
Makes routesGenerator := InjectedRoutesGenerator the default.
TODO: The reference to "Replaced static methods with dependency injection" in Migration25.md needs to be updated.
> Change routes compiler to InjectedRoutesGenerator

- documentation/manual/working/commonGuide/configuration/code/ThreadPools.scala
- documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/BodyParserSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WS.java
- framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
- framework/src/play-streams/src/test/java/play/libs/streams/AccumulatorTest.java
- framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
- framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala
- framework/src/play-ws/src/main/scala/play/api/test/WSTestClient.scala
- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
- framework/src/play/src/test/scala/play/api/mvc/RawBodyParserSpec.scala
Fixes deprecated warnings like
```
[warn] /home/wsargent/work/playframework/doc-deprecate-plugin/framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala:245: method shutdown in class ActorSystem is deprecated: Use the terminate() method instead
[warn]     system.shutdown()
```
> Use actorsystem terminate

- framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala
- framework/src/play/src/main/scala/views/helper/Helpers.scala
Fixes following compiler warning:
```
[warn] /home/wsargent/work/playframework/master/framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala:147: trait NotNull in package scala is deprecated: This trait will be removed
[warn]   sealed trait JsValueWrapper extends NotNull
```
See https://issues.scala-lang.org/browse/SI-7247.  
I think removing this is fine, as no-one is going to be referring to `val foo:NotNull` as the base type.
> Remove deprecated NotNull trait

- framework/project/Build.scala
Fixes the following deprecation warning in build:
```
[warn] /home/wsargent/work/playframework/use-previous-artifacts/framework/project/Build.scala:73: value previousArtifact in object MimaKeys is deprecated: Please use previousArtifacts which allows setting more than one previous artifact.
[warn]     previousArtifact := {
[warn]     ^
[warn] /home/wsargent/work/playframework/use-previous-artifacts/framework/project/Build.scala:404: value previousArtifact in object MimaKeys is deprecated: Please use previousArtifacts which allows setting more than one previous artifact.
[warn]       previousArtifact := None
[warn]       ^
[warn] two warnings found
```
> Use previousArtifacts

- documentation/manual/working/commonGuide/configuration/SettingsJDBC.md
- framework/src/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
The JDBC settings page is missing an example of how to override the connection pool settings.  Added a test and some notes.
> Add a test and a note for bonecp settings

- documentation/manual/releases/release25/Migration25.md
- documentation/manual/working/commonGuide/configuration/code/detailedtopics/ThreadPoolsJava.java
- framework/src/play-cache/src/main/java/play/cache/Cache.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
- framework/src/play-java-ws/src/main/java/play/libs/openid/OpenID.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WS.java
- framework/src/play-java/src/main/java/play/libs/Yaml.java
- framework/src/play-test/src/main/java/play/test/Helpers.java
- framework/src/play-test/src/test/java/play/test/WithApplicationTest.java
- framework/src/play/src/main/java/play/Application.java
- framework/src/play/src/main/java/play/Play.java
- framework/src/play/src/main/java/play/i18n/Messages.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/Application.scala
- framework/src/play/src/main/scala/play/api/Play.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
Ongoing work for #5309.  This takes out the deprecated methods in play.api.Play (which mostly delegate to application).
There's a fair bit of code that goes straight to Play.current.injector etc, but removing current is out of scope.
> Remove internal references to deprecated play.api.Play.* methods

- framework/src/play-test/src/test/java/play/test/WithApplicationTest.java
This happens on a clean master:
```
[error] /home/travis/build/playframework/playframework/framework/src/play-test/src/test/java/play/test/WithApplicationTest.java:25: cannot find symbol
[error]   symbol:   method privateMaybeApplication()
[error]   location: class play.api.Play
[error] play.api.Play.privateMaybeApplication
```
> Fix broken test compilation on Play.privateMaybeApplication

- documentation/manual/gettingStarted/Anatomy.md
Text is as follows:
You also have the option of using the default layout used by SBT and Maven. Please note that this layout is experimental and may have issues. In order to use this layout, you must disable the layout plugin and set up explicit monitoring for twirl templates:
```
disablePlugins(PlayLayoutPlugin)
PlayKeys.playMonitoredFiles ++= (sourceDirectories in (Compile, TwirlKeys.compileTemplates)).value
```
Replaces https://github.com/playframework/playframework/pull/5312
> [doc] add note about playMonitoredFiles

- documentation/manual/working/commonGuide/assets/AssetsOverview.md
- documentation/manual/working/commonGuide/assets/code/routes
- documentation/manual/working/commonGuide/build/SBTSubProjects.md
- documentation/manual/working/commonGuide/build/code/routes
- documentation/project/Build.scala
- framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
Pulls in the logic from https://github.com/playframework/playframework/pull/4922 and adds a test to make sure at least the routes file will parse okay, as per 4922 review.
This turns out to be a bit more complex because all the routes file are in commonGuide, so needed to change up the build file to add commonGuide to the build.  This in tern required that the routes files be changed so they weren't under the package mapping scheme (which now caused compilation errors).
Also moves some other routes into code snippets as well, although I did not attempt a full sweep.
> [doc] Add a test for single static file

- documentation/manual/about/PlayUserGroups.md
- documentation/manual/releases/release24/migration24/Migration24.md
- documentation/manual/working/commonGuide/configuration/ws/LooseSSL.md
- documentation/manual/working/commonGuide/filters/SecurityHeaders.md
- documentation/manual/working/commonGuide/production/HTTPServer.md
- documentation/manual/working/javaGuide/main/sql/JavaDatabase.md
- documentation/manual/working/javaGuide/main/ws/JavaOAuth.md
- documentation/manual/working/scalaGuide/main/json/ScalaJsonHttp.md
- documentation/manual/working/scalaGuide/main/sql/ScalaDatabase.md
- documentation/manual/working/scalaGuide/main/xml/ScalaXmlRequests.md
TODO: 
Correct the 404 status code response for Typesafe snapshots repository URL in 
https://github.com/playframework/playframework/blob/master/documentation/manual/hacking/Repositories.md
> Fix some links to external sites in documentation

- framework/src/play/src/main/scala/play/api/routing/Router.scala
- framework/src/play/src/test/scala/play/api/routing/SimpleRouterSpec.scala
Hi,
My problem was, I had to define a router with SIRD like 
```
val myRouter = Router.from {
case GET(p"/") => // an action
case GET(p"/$id") => // another action with the path extracted id
}
```
and use it in the `routes` file like
```
->          /myPrefix           foo.Bar.myRouter
```
Therefore, I was expecting the application to handle `GET /myPrefix` requests which were not.
Instead `GET /myPrefix/` was handled.
The problem is from the `withPrefix` implementation of the `SimpleRouter`.
I hope it helps.
By the way, I added a test that covers the use case above.
> Enable prefixed SimpleRouter to handle / request with prefix only

- documentation/manual/working/commonGuide/filters/GzipEncoding.md
- documentation/manual/working/commonGuide/filters/code/GzipEncoding.scala
- documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/gzipencoding/CustomFilters.java
- framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
In general, I think our built in filters can accept `Config` classes that that use the builder pattern. 
/cc @mkurz
> Improve GzipFilter configuration from Java

- framework/src/play/src/main/java/play/Play.java
- framework/src/play/src/main/java/play/i18n/Lang.java
- framework/src/play/src/main/java/play/i18n/Messages.java
- framework/src/play/src/main/java/play/i18n/MessagesApi.java
- framework/src/play/src/main/java/play/mvc/Http.java
Fixes https://github.com/playframework/playframework/issues/5596
Move to instance `play.i18n.Messages` methods.
Deprecate `play.Play`, since every single method in it is deprecated.  Also some clean up.
> Deprecate static i18n Java API

- framework/src/play/src/main/java/play/libs/Akka.java
- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
This method is not referenced anywhere in the code, and the documentation correctly uses dependency injection: https://github.com/playframework/playframework/blob/master/documentation/manual/working/javaGuide/main/akka/JavaAkka.md
I did add a note in scaladoc to say that the Scala version of Akka.system takes an implicit application.
> Deprecate static play.libs.Akka.system method.

- documentation/manual/ModuleDirectory.md
Play Shiro isn't a supported module, and the author would prefer it not to show up.
Also re-arranged the modules so the versions that support Play 2.4.x show up first.
> [doc] Remove play-shiro, rearrange authentication

- framework/src/play/src/main/scala/play/core/j/JavaWebSocket.scala
One less warning.  Since JavaWebSocket.scala is itself a deprecation wrapper, I wasn't sure about deprecating it myself.
@dotta can you review to see if we can refactor this to take implicit application or the like?
> Move reference to play.api.Play.current to privateMaybeApplication

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/java/play/data/Formats.java
- framework/src/play-java/src/test/java/play/data/Money.java
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
Fixes #2065 
Now the `locale` param is set correctly for both the `parse` and `print` method.
> Set correct Locale in Databinder

- documentation/manual/working/javaGuide/main/tests/JavaTest.md
Mockito is not included in build by default, but the documentation was saying that.
> Mockito is not included in build by default

- documentation/manual/working/commonGuide/production/HTTPServer.md
There is not an example to add trusted proxies in Configure trusted proxies section.
This example will be useful for beginner.
`::FF` doesn't mean `localhost` of IPv6. I checked code of `ForwardedHeaderHandler.scala`, `defaultTrustedProxies` doesn't include `::FF`.
```
private def defaultTrustedProxies = List("::1", "127.0.0.1")
```
So, I also fixed Default description.
> Update documentation for Configure trusted proxies

- framework/project/Dependencies.scala
There were several important fixes since the currently used 1.7.13.
Read the release notes http://www.slf4j.org/news.html for details.
> Bumped slf4j version to 1.7.16

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
When the `cookieHeader` is empty: `Cookies.decodeSetCookieHeader("")` the variable `cookie` is set to null.
The message `Couldn't decode the Cookie header containing: ` occurs in production logs many, many times for each user trying to connect with application without cookies in session.
See #5591 for more details.
PR solves #5591
> Potential NPE in Cookies#decodeSetCookieHeader.

- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala
I already created an issue about this problem a few months back (https://github.com/playframework/playframework/pull/4872).
Also, I started a discussion on the user list which I tried to move to the dev list (https://groups.google.com/forum/#!topic/play-framework-dev/91PQ6Zal7f0) for some directions but there was no reply.
Currently, the Reads are still broken because the timezone offset is not taken into account when parsing an Instant. And writing is broken (IMO) because the output is ambiguous since it lacks timezone information.
When a user chooses an Instant to represent a point in time, he does that on purpose because of the inherent properties of an Instant (unambiguous representation of a point in time without timezone or offset information). Trying to guess the zone offset or …
> Fix java.time.Instant JSON Reads / Writes

- framework/src/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala
- framework/src/play/src/test/scala/play/core/parsers/FormUrlEncodedParserSpec.scala
* Allow semicolon separators in addition to ampersands
* Parse empty/non-existant names and values
---
W3C [recommends](http://www.w3.org/TR/1999/REC-html401-19991224/appendix/notes.html#h-B.2.2) accepting semicolons separators.
> We recommend that HTTP server implementors, and in particular, CGI implementors support the use of ";" in place of "&"
Old stuff, but most parsers still follow the recommendation.
Also, most parsers accept empty names and values, and non-existent values. For example, the example request in [RFC 5849 3.4.1.3.1](http://tools.ietf.org/html/rfc5849#section-3.4.1.3.1) (OAuth 1.0) has the body
```
c2&a3=2+q
```
and requires parsing the `c2` parameter in order for OAuth to work.
---
Most parsers allow these two usages, for example …
> More standard application/x-www-form-urlencoded parsing

- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSCookie.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSCookie.java
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
Should fix https://github.com/playframework/playframework/issues/5626
Note that AHC 1.9.33 has binary incompatible changes with 1.9.21, because the expires field is no longer used in an AHC cookie.
> Update 2.4.x to AHC 1.9.33

- documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
"db.default.driver" is missing from Procfile.
If Procfile dose not have "db.default.driver", an error occurs.
I found the same problem in 2.4.3/2.4.4/2.4.x/2.5.0-M2/2.5.x of the document
> "db.default.driver" is missing from Procfile

- framework/src/play-logback/src/main/scala/play/api/Logger$ColoredLevel.scala
This should allow for a smoother migration path, as it tells the user how to solve the problem, rather than simply having logback emit a ClassNotFoundException.
The result of this change is that when the deprecated class is used, along with all the logback debug output, you see this:
```
13:21:22,079 |-ERROR in play.api.Logger$ColoredLevel@57ac5964 - You are using the deprecated play.api.Logger$ColoredLevel in file:/home/jroper/tmp/play-scala/target/scala-2.11/classes/logback.xml, please use play.api.libs.logback.ColoredLevel instead. See https://www.playframework.com/documentation/2.5.x/Migration25#Change-to-Logback-configuration for more information.
```
It has to be logged at error, as warnings don't trigger logback to dump its status messages - the user would never see the warning.
> Created deprecated Logger$ColoredLevel

- documentation/manual/working/javaGuide/code/MockJavaAction.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/bindings/GlobalSettingsSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JAction.scala
- framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
- framework/src/play/src/main/java/play/http/GlobalSettingsHttpRequestHandler.java
- framework/src/play/src/main/java/play/http/HttpRequestHandler.java
- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
- framework/src/play/src/main/scala/play/core/j/JavaAction.scala
- framework/src/play/src/main/scala/play/core/j/JavaHttpRequestHandlerAdapter.scala
- framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
Use `DefaultHttpRequestHandler` in both Java and Scala.
I also did some refactoring of the Java `HttpRequestHandler`-related code.
Fixes #5357, closes #5369.
> Change default HttpRequestHandlers

- framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSRequest.java
- framework/src/play-java-ws/src/test/scala/play/libs/ws/ning/NingWSRequestSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
Fixes #5221 in 2.4.x, by only parsing WS request body if signature calculator is present.
> Play WS only parses form body when used with OAuth - 2.4.x

- documentation/build
- documentation/manual/releases/release25/Highlights25.md
- documentation/manual/releases/release25/index.toc
- documentation/manual/releases/release25/migration25/JavaMigration25.md
- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/releases/release25/migration25/StreamsMigration25.md
- documentation/manual/releases/release25/migration25/index.toc
- framework/src/play/src/main/scala/play/api/mvc/Action.scala
- framework/src/play/src/main/scala/play/api/mvc/Filters.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
I split out the streams and Java migration docs into separate files because they're each quite big on their own. The streams migration docs are still being worked on by me, but I'm pushing them now so that other people can work on the other parts of the docs.
> Started Play 2.5 streams migration docs

- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
This fixes the following warnings in the logs when Netty binds the server channel:
```
Ignoring unknown Netty channel option: child.SO_KEEPALIVE
Valid values can be found at http://netty.io/4.0/api/io/netty/channel/ChannelOption.html
```
> Correctly exclude child options

- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaCsrf.java
- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf.scala.html
- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/form.scala.html
- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
- documentation/manual/working/scalaGuide/main/forms/code/ScalaCsrf.scala
- documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/csrf.scala.html
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play-filters-helpers/src/main/scala/views/html/helper/CSRF.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/ScalaCSRFActionSpec.scala
- framework/src/play/src/main/scala/play/api/libs/Crypto.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
The form helpers and `CSRF.getToken` now take an `implicit RequestHeader` and will pull the token name and value off of tags on the request. No global state is required to do this, since the token is placed on the request by the `CSRFFilter`.
Unfortunately because of the limitations of tags this solution ended up being a little bit ugly. Ideally we should have a way to attach arbitrary data onto the request, e.g. a `CSRFContext` that has the token name, value, and possibly other functionality (re-signing tokens), but I thought it might be out of the scope of this PR.
> CSRF filter API changes

- framework/src/play/src/main/resources/messages.default
Seems it was forgotten. It's defined [here](https://github.com/playframework/playframework/blob/2.5.0-M2/framework/src/play-java/src/main/java/play/data/validation/Constraints.java#L401).
> Message key for constraint.pattern

- documentation/manual/working/commonGuide/production/HTTPServer.md
- framework/src/play-server/src/main/scala/play/core/server/common/ForwardedHeaderHandler.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
- framework/src/play/src/main/resources/reference.conf
In addition, I improved the docs to be more detailed and clearer, including information about getting forwarded headers working on platforms that require trusting all proxies.
> Moved forwarded header configuration to reference.conf

- framework/src/play-cache/src/main/java/play/cache/Cache.java
- framework/src/play-cache/src/main/java/play/cache/CachedAction.java
Deprecate the static `play.cache.Cache` methods as they are static and rely on `Play.current()`.
Also added a test to make sure that the `Cached` annotation is called, but interesting note -- how do you call a Java controller in Play directly?
> Deprecate static cached methods

- documentation/manual/gettingStarted/Tutorials.md
Better tutorials page, fixes https://github.com/playframework/playframework/issues/5496
I seperated the templates into "Typesafe maintained" and "Third Party" and focused more on actual blog posts giving in depth discussions of various parts of Play (where they are still current, within reason).
Some of these will inevitably be out of date, but it gives a better process to integrate blog posts into the documentation.
**NOTE** I do not expect this to be the final draft, feel free to chip in with additions / modifications.
> Better tutorials

- documentation/manual/working/commonGuide/configuration/ThreadPools.md
- documentation/manual/working/commonGuide/configuration/code/ThreadPools.scala
Fixes https://github.com/playframework/playframework/issues/5400.
Added a debug section, changed sychronous section to use thread-pool-executor, fixed-pool-size (see https://github.com/akka/akka/pull/19211 and https://github.com/akka/akka/issues/19201) and added throughput=1 for greater fairness.
Note that the documentation in previous versions appears be incorrect -- it's not `akka.fork-join-executor`, but `akka.actor.default-dispatcher.fork-join-executor`, for example -- see https://github.com/akka/akka/blob/master/akka-actor/src/main/resources/reference.conf#L337 for reference.
> [doc] Update thread pool documentation

- framework/src/play-java-ws/src/main/java/play/libs/openid/DefaultOpenIdClient.java
- framework/src/play-java-ws/src/main/java/play/libs/openid/OpenID.java
- framework/src/play-java-ws/src/main/java/play/libs/openid/OpenIdClient.java
Switch to `CompletionStage` and deprecate static methods in favor of `OpenIdClient`.
> Update OpenID for 2.5

- framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala
There is no `play.api.libs.Streams.actorFlow` method, so moving this.
> Fix references to ActorFlow.actorRef

- templates/play-java-intro/conf/application.conf
- templates/play-scala-intro/conf/application.conf
The "play-scala-intro" and "play-java-intro" templates still have old style, flat with no documentation templates.
All the settings are the same as previously, so the only difference in this PR is structure and comments.
> Update intro templates with default application.conf

- documentation/manual/releases/release24/migration24/Migration24.md
- documentation/manual/releases/release25/Highlights25.md
- documentation/manual/releases/release25/migration25/JavaMigration25.md
- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/releases/release25/migration25/StreamsMigration25.md
- Made some clarifications about the deprecated static APIs
- Fixed incorrect links
- Improved wording and fixed several minor typographical/spelling/grammar errors
- Changed to tables instead of lists
> Even more 2.5 migration guide improvements

- documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/main/http/JavaRouting.md
- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
- documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
Clarified that the default routes generator is `InjectedRoutesGenerator`. Also added some clarifications about using DI and links to the Guice wiki.
I also made the DI doc a bit more opinionated toward constructor injection. In Scala it seems like the obvious choice, but I guess some people justify field injection in their Java apps for reasons of brevity.
> Dependency injection documentation clarifications

- documentation/manual/releases/release25/migration25/StreamsMigration25.md
Maybe need a newline before the start of these two code blocks? The HTML rendering on the project website isn't doing code highlighting correctly and showing the lowercase word "java" for the first and "scala" for the second in the visible content, too.
> Possible fix for rendering issue on web site

- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
We'd like to be able to customize the behavior when a localization key is missing.
> Make noMatch overridable

- templates/play-scala/test/ApplicationSpec.scala
Fixed deprecation warnings in ApplicationSpec.scala in templates/play-scala template project.
> Deprecation Warning Fix for play-scala Template's Tests

- framework/src/play/src/main/java/play/http/HttpRequestHandlerActionCreator.java
Guice is automatically proxying interfaces to break circular dependencies, but other DI frameworks won't do this.
> Break circular dependency in HttpRequestHandlerActionCreator

- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
Fixes #4614 
[As recommended](https://github.com/playframework/playframework/issues/4614#issuecomment-121089467) by @richdougherty, instead of using a cache, just use the field that is already on Application.
This should probably be backported to 2.4.x, let me know if there's anything I need to do to make that happen.
> Fixes #4614 Make Akka.system point to app.actorSystem

- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
Simple backport of  #5691 which fixes #4614 in case it comes in handy.
> #5691 2.4.x backport:  Make Akka.system use the system field on app

- documentation/manual/working/commonGuide/build/SBTDependencies.md
Fixes #2441
Point users to the right page at sbt docs when they have problems with dependency management.
Most of the SBTDependencies page is just copy and paste from sbt docs. I've just give the page some update and add a section about conflict management.
See issue #2441.
> Improve and update SBT Dependencies docs

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
Fixes #5687
Change the CORS filter to treat HTTP and HTTPS requests as different origins. Previously, we would let the request pass through without adding CORS headers if the host and port matched. Now we check the `request.secure` attribute so requests to `https://example.com` are treated differently from `http://example.com`.
Another possible approach might be to check all requests with an origin, but since some browsers send the `Origin` header with same-origin requests, it would mean we'd have to whitelist the origin of the server as well, so it could break things for existing users.
> Make CORS filter treat http and https as different origins

- documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/CircularDependencies.java
- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
- documentation/manual/working/scalaGuide/main/dependencyinjection/code/RuntimeDependencyInjection.scala
Documents how to handle circular dependencies in a Play app.
#5695 turns off Guice's automatic proxying to resolve circular dependencies, and there have been a few questions in the past about handling circular dependencies, especially when dealing with dependencies on Application.
https://groups.google.com/forum/#!topic/play-framework-dev/RqSoXt0FJT0
#5695
> Documentation on managing circular dependencies

- documentation/manual/releases/release25/migration25/Migration25.md
- framework/src/play-java/src/main/java/play/inject/guice/GuiceBuilder.java
- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
- framework/src/play/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala
- framework/src/play/src/test/scala/play/api/inject/guice/GuiceInjectorBuilderSpec.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala
Guice offers several configuration options on the binder that advanced users might want to enable for testing purposes or for their entire application:
- `disableCircularProxies`: Disable proxying interfaces to break circular dependencies. By default, if Guice finds a circular dependency, it can break it by creating a proxy interface.
- `requireExplicitBindings`: Only inject classes that are explicitly bound in a module.
- `requireExactBindingAnnotations`: Disables the error-prone feature in Guice where it can substitute a binding for @Named Foo when injecting @Named("foo") Foo.
- `requireAtInjectOnConstructors`: Only inject classes that have a constructor explicitly annotated with @Inject
This also enables `disableCircularProxies` by default and fixes the classes that have circular …
> Allow configuring binder options on Guice injector

- documentation/manual/detailedTopics/production/ProductionConfiguration.md
update the 2.4.x jvm options documentation
related to: #5579
> Remove -mem from 2.4.x production configuration documentation as it doesn't work

- framework/src/play/src/main/java/play/http/DefaultHttpRequestHandler.java
We actually want it to wrap a `JavaCompatibleHttpRequestHandler`.
See https://groups.google.com/d/msg/play-framework/WLKidonv58U/g7t_a3HLFQAJ
> Fix StackOverflowError in play.http.DefaultHttpRequestHandler

- framework/src/play/src/main/java/play/mvc/BodyParser.java
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
- framework/src/play/src/test/scala/play/api/mvc/MaxLengthBodyParserSpec.scala
Fixes #5704.
Rather than signalling max length exceeded by terminating the stream with a failure, this new parser materialises the status of the max length check so that it can be worked with explicitly.  This means that if multiple max length flows are applied to the same stream, they don't impact one another.
> Rewrote maxLength body parser

- framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
Fixes #5711
The current implementation calls `map` on the `Map` but it would be sufficient to call `mapValues`. If called on an ordered map like a `ListMap`, the `map` method will produce an unordered map, but `mapValues` does not have this problem.
> Prevent mapWrites from losing ordering on ordered maps

- documentation/manual/working/javaGuide/main/forms/JavaForms.md
- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormHelpers.scala
- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
- framework/src/play-integration-test/src/test/scala/play/it/libs/JavaFormSpec.scala
- framework/src/play-java/src/main/java/play/data/DynamicForm.java
- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/main/java/play/data/FormFactory.java
- framework/src/play-java/src/main/java/play/data/FormFactoryModule.java
- framework/src/play-java/src/main/resources/reference.conf
- framework/src/play-java/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/scala/play/data/DynamicFormSpec.scala
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
- framework/src/play-java/src/test/scala/play/data/PartialValidationSpec.scala
- templates/play-java-intro/app/controllers/Application.java
Fixes #5678
Introduces a `FormBuilder` which can be injected to create a `Form` with all the dependency it needs.
I completely got rid of any static `Form.form` reference in the codebase.
@gmethvin Is that the solution that you have in mind?
If this PR makes it in it makes it **much** more easier to fix/implement #5666/#5670 and #5619 and #5620.
> play.data.Form uses DI now via FormFactory

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/resources/messages
- framework/src/play/src/main/scala/play/api/data/Form.scala
- framework/src/play/src/main/scala/views/helper/Helpers.scala
- framework/src/play/src/test/resources/messages
- framework/src/play/src/test/scala/play/api/data/FormSpec.scala
- framework/src/play/src/test/scala/views/html/helper/HelpersSpec.scala
Original this was part of #5619.
I don't know if I have enough time fix #5619 until the Play 2.5 release so it would be nice to at least get this PR in.
With this PR people (like us) will be able to implement their **own** DataBinders and Constraints which make use of message keys as arguments so...
-  .. *databinders* like `@MyCurrencyBinder(pattern = "myFormats.currency")` where `myFormats.currency` is defined in the `messages.XX` files like e.g. `#,###.##`, etc. will display `#,###.##` correctly when displaying the field's format in the HTML (instead of displaying `myFormats.currency`).
- ...*constraints* like `@MyPattern(value="myConstraints.zipPattern", message="error.zip")` where `myConstraints.zipPattern` is defined in the `messages.XX` files like e.g. `[1-9][0-9]{3}`, etc. (the …
> Look up arguments of constraint/format/error messages in message file

- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/scala/play/core/server/ServerListenException.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
- framework/src/run-support/src/main/scala/play/runsupport/ServerStartException.scala
Fixes #5568
Now when I try `sbt run` when the port is already bound, it looks like this:
```
--- (Running the application, auto-reloading is enabled) ---
[error] p.c.s.NettyServer - Failed to listen for HTTP on /0.0.0.0:9000!
[error] (compile:run) play.runsupport.ServerStartException
[error] Total time: 1 s, completed Feb 23, 2016 5:55:02 AM
```
I extended `FeedbackProvidedException` to suppress the stack trace in SBT.
> Fail to start the server if we can't bind to a port

- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play/src/main/scala/play/api/http/StandardValues.scala
Related ML discussion: https://groups.google.com/forum/#!topic/play-framework/oiMC43aZP8c
The charset parameter is meaningless for the [application/json](https://www.iana.org/assignments/media-types/application/json) media type, and apparently some servers error if you send it.
The same is also true for [application/x-www-form-urlencoded](https://www.iana.org/assignments/media-types/application/x-www-form-urlencoded).
> Don't send charset if we don't need to

- documentation/manual/working/commonGuide/build/SBTSubProjects.md
- documentation/manual/working/commonGuide/build/code/SubProjectsAssetsBuilder.scala
- documentation/manual/working/commonGuide/build/code/common.build.routes
Fixes https://github.com/playframework/playframework/issues/5718
Changes instances of `Application` to `HomeController` and uses `class HomeController` instead of `object HomeController` to make the code more DI aware.
The new Play templates use `HomeController` as a name instead of `controllers.Application` to avoid confusion with `play.api.Application`.  Since 2.5.x uses InjectedRoutesGenerator by default, use of `object Application` should be a deprecated usage and there are multiple bugs based on outdated docs.
* https://stackoverflow.com/questions/33985108/play-framework-2-4-x-module-route-specific-name-fails-with-assets-is-not-a
* https://github.com/playframework/playframework/issues/4812
> Update controller to be class based assuming DI

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
- framework/src/play/src/test/scala/play/core/test/Fakes.scala
Exposes the SSLSession for requests over SSL. This allows access to the X509 Certificate that a client may present.
Rather than exposing the certificate directly I thought it would be more useful to expose the SSLSession since it provides access to the full certificate chain as well as both the (java|javax).security.cert.X509Certificate APIs. The certificates won't be available unless wantClientAuth or needClientAuth is enabled through config.
I've tested this locally using a self signed client certificate and setting noCaVerification to true. I'm not sure of the best way to write automated tests for this - suggestions for testing strategies are welcome.
I didn't find a way to implement this for the Akka server. The SSLEngine seems to only be available in TLSActor and not through the Akka …
> Expose client X509Certificates for a request

- documentation/manual/releases/release25/migration25/CryptoMigration25.md
- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/releases/release25/migration25/index.toc
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
- framework/src/play-java/src/main/java/play/libs/Crypto.java
- framework/src/play-java/src/main/java/play/libs/crypto/CSRFTokenSigner.java
- framework/src/play-java/src/main/java/play/libs/crypto/CookieSigner.java
- framework/src/play/src/main/scala/play/api/Application.scala
- framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala
- framework/src/play/src/main/scala/play/api/libs/Crypto.scala
- framework/src/play/src/main/scala/play/api/libs/crypto/Crypto.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/libs/crypto/AESCTRCrypterSpec.scala
- framework/src/play/src/test/scala/play/api/libs/crypto/CSRFTokenSignerSpec.scala
- framework/src/play/src/test/scala/play/api/libs/crypto/CookieSignerSpec.scala
- framework/src/play/src/test/scala/play/api/libs/crypto/CryptoConfigParserSpec.scala
A more ambitious Crypto module.
Breaks out Crypto into a trait and adds Guice bindings.
Deprecates AES methods (see #4407)
Adds more tests of signing, generating random methods.
Does a random.nextBytes() with 55 bytes, because why not.
> Add crypto module for 2.5.x

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequestExecutor.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequestFilter.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-java-ws/src/test/scala/play/libs/ws/WSSpec.scala
- framework/src/play-java-ws/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
This is a first pass at https://github.com/playframework/playframework/issues/2932
The idea is that requests that seem to go wrong can have a request logger attached to them which has access to the WSRequest.  From there, it should be pretty easy to write a Curl logger.
```
val logger = new WSRequestLogger {
def log(request: WSRequest): Unit = {
Console.println(s"request = $request")
}
}
WS.url("http://playframework.com").withRequestLogger(logger).get()
```
> [WS] Add filter pipeline to WS

- framework/src/play-java/src/main/java/play/data/format/Formats.java
- framework/src/play-java/src/main/java/play/data/format/Formatters.java
- framework/src/play-java/src/test/java/play/data/Birthday.java
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/resources/messages
- framework/src/play-java/src/test/resources/messages.en-US
- framework/src/play-java/src/test/resources/messages.fr
That's how `AnnotationDateFormatter` works right now:
```java
@DateTime(pattern = "dd/MM/YYYY")
private java.util.Date birthDate;
```
The `pattern` for a field is "hardcoded".
Depending on the locale of the request we want to use different patterns. E.g. "dd.MM.YYYY" for german, "dd-MM-YYYY" for english, etc.
Problem: That's not possible right now.
With this PR the pattern string will now also be looked up in the message files so you could define e.g.: `customFormats.date=dd.MM.YYYY` in `messages.de`, `customFormats.date=dd-MM-YYYY` in `messages.en`, etc. and the just use the key:
```java
@DateTime(pattern = "customFormats.date")
```
Actually I am wondering why this was not working before.
> Look up pattern for AnnotationDateFormatter in messages

- documentation/manual/releases/release25/migration25/StreamsMigration25.md
- documentation/manual/working/javaGuide/main/async/JavaComet.md
- documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaComet.java
- documentation/manual/working/javaGuide/main/async/index.toc
- documentation/manual/working/scalaGuide/main/async/ScalaComet.md
- documentation/manual/working/scalaGuide/main/async/code/ScalaComet.scala
- documentation/manual/working/scalaGuide/main/async/index.toc
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
- framework/src/play-java/src/main/java/play/libs/Comet.java
- framework/src/play-java/src/main/java/play/libs/EventSource.java
- framework/src/play-java/src/test/java/play/libs/CometTest.java
- framework/src/play/src/main/scala/play/api/libs/Comet.scala
- framework/src/play/src/main/scala/play/api/libs/EventSource.scala
- framework/src/play/src/test/scala/play/api/libs/CometSpec.scala
Fixes https://github.com/playframework/playframework/issues/5602
Add `Comet.flow()` method for both Scala and Java APIs.  Add documentation and migration guide.
Comet needs updating to use Akka Streams.
EventSource Streams API https://github.com/playframework/playframework/pull/5300
> Update Comet API to use Akka Streams

- framework/src/play-java/src/main/java/play/data/format/Formats.java
- framework/src/play-java/src/main/java/play/data/format/Formatters.java
- framework/src/play-java/src/test/java/play/data/Birthday.java
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/resources/messages.en-US
- framework/src/play-java/src/test/resources/messages.fr
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
- framework/src/play-java/src/test/scala/play/data/Task.scala
- framework/src/play/src/main/resources/messages.default
Right now the default pattern for binding *any* `java.util.Date` from a Form is  `'yyyy-MM-dd'`. Unfortunately this pattern is hardcoded :cry: 
We are writing an app for german users and the default pattern for entering dates in german is `'dd.MM.yyyy'`. That's why I want to be able to change the default pattern of the Date binding.
With this PR you can simply change the pattern by putting
```
formats.dateFormat=dd.MM.yyyy
```
in your `messages` files.
This makes date binding much more flexible.
This PR is fully backwards compatible because `yyyy-MM-dd` stays the default pattern.
> Read pattern for DateFormatter from messages

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
Trying to fix #5666 that's what I have come up with.
Feedback welcome.
> Bugfix: Correctly look up error.invalid.* messages

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
> Make CORS filter treat http and https as different origins (2.4.x)

- framework/src/play-java/src/main/java/play/data/format/Formats.java
- framework/src/play-java/src/test/resources/messages.en-US
- framework/src/play-java/src/test/resources/messages.fr
- framework/src/play/src/main/resources/messages.default
Not to be confused with `format.date`  (without the `s`).
If you think it is to similiar just close this PR.
> Key formats.date is shorter and more clear

- documentation/manual/working/javaGuide/main/sql/JavaJPA.md
- documentation/manual/working/javaGuide/main/sql/code/JavaApplicationDatabase.java
- documentation/manual/working/javaGuide/main/sql/code/JavaNamedDatabase.java
- documentation/manual/working/javaGuide/main/sql/code/controllers/JPAController.java
- documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
- documentation/project/Build.scala
- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAEntityManagerContext.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/TransactionalAction.java
- framework/src/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
- framework/src/play/src/main/java/play/mvc/Http.java
Fixes #4890
Improves the JPAApi to be more consistent and also to have better ways to handle EntityManager lifecycle.
See this comment: https://github.com/playframework/playframework/issues/4890#issuecomment-127368670
Please see discussion and suggestions made at #4890.
This changes both JPAApi and JPA helper to work more consistently.
1. Both JPAApi.em(String) and JPA.em(String) should always return a new EntityManager for the given name. This was already working this way and only tests were added to avoid regressions
2. Now both JPA and JPAApi  have an em() method which returns the EntityManager from Http.Context or ThreadLocal if available. A new class was created to "hold" the current EntityManager instead of duplicate/split this logic between JPAApi and JPA.
3. JPAApi now overloads …
> JPAApi improvements

- documentation/manual/releases/release25/migration25/Migration25.md
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-java-ws/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Fixes #5221 in master, by only parsing WS request body if signature calculator is present.
> Play WS only parses form body when used with OAuth - master

- framework/src/play/src/main/java/play/mvc/Http.java
`play.mvc.HTTP` is missing few HTTP statuses comparing to `play.api.http.StandardValues`
> Add missing HTTP statuses in play.mvc.Http

- templates/play-scala-intro/test/ApplicationSpec.scala
In line with commit a2e4c7ff6b125638b8d9d511e27a7c338c6e9c69 this change also fixes the deprecation warnings in the play-scala-intro template:
```
test/ApplicationSpec.scala:23:
method route in trait RouteInvokers is
deprecated: Use the version that takes an application
```
> Fix deprecation warnings in play-scala-intro

- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Fixes #5777.
The NettyServer adds `Content-Length` if it's not present, which is why it was happening in dev mode.
> Always send Content-Length with files

- framework/project/Dependencies.scala
- templates/play-java-intro/test/IntegrationTest.java
- templates/play-scala-intro/test/IntegrationSpec.scala
Fixes #5050
Allows us to enable javascript again in the integration tests (Originally I disabled javascript in #5613).
> Explicitly depend on htmlunit 2.20 to support jQuery 2.20

- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/resources/messages.fr
Just one more test for #5670 which checks if the message key `error.invalid.<fieldName>` gets looked up if defined.
> Added specific test scenario for error.invalid.<fieldName>

- framework/src/play/src/main/scala/play/utils/Resources.scala
- framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
Allow I18n usage of play apps on weblogic.
Loading of I18n messages checks if items on the classpath are directories and breaks the application on unknown protocol e.g. "zip", which exists on weblogic installations.
Original commit introducing the breakage - https://github.com/playframework/playframework/commit/686a9b4535815d24381cea9acd901461fd28a4fa
Fix for 2.3 branch - https://github.com/playframework/playframework/commit/422ca97c54a7ab84cb965df1474f2cd0d11e5fc6 (PR #5728)
Fix for 2.4 branch - (PR #5763)
> allow i18n usage on weblogic

- framework/src/play-akka-http-server/src/main/resources/play/reference-overrides.conf
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHttpServerSpec.scala
Fixes #5780
Enables the `Raw-Request-URI` header in akka-http and uses that for `request.uri`.
> Get raw request URI in AkkaHttpServer

- documentation/manual/releases/release25/migration25/Migration25.md
Adds migration notes to LoggerConfigurator for compile time injection migration.
Compile time injection is slightly different.
https://groups.google.com/d/msg/play-framework/aFEkSOaAEbk/UqjDiCFSGQAJ
> [doc] Add compile time LoggerConfigurator instructions

- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaCompileTimeDependencyInjection.md
Updates the compile time dependency injection page to have a configuring logging section.
Previous text was unclear.
https://groups.google.com/d/msg/play-framework/aFEkSOaAEbk/nQB6SeVNGQAJ
> [doc] Add configuring logging to ScalaCompileTimeDependencyInjection

- documentation/manual/releases/release25/Highlights25.md
- documentation/manual/releases/release25/migration25/CryptoMigration25.md
- documentation/manual/releases/release25/migration25/JavaMigration25.md
- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/releases/release25/migration25/StreamsMigration25.md
Fixes some small problems with migration guide for Play 2.5.0. This should be backward ported to branch 2.5.x.
> Small corrections to migration guide 2.5

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
- framework/src/play-java-jdbc/src/main/java/play/db/DB.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
- framework/src/play/src/main/scala/play/utils/UriEncoding.scala
Feel free to use this if you like. Found a way to escape the warnings when using $var in comments.
> Fixed some Javadoc warnings ref issue #4995

- documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
- documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
- documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala
- documentation/manual/working/scalaGuide/main/tests/code/specs2/FunctionalExampleControllerSpec.scala
- documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala
- documentation/manual/working/scalaGuide/main/tests/code/specs2/WithDbDataSpec.scala
Small corrections and also updates to testing with specs2. This is related with other corrections made at #5799 (backported at #5807) and also playframework/scalatestplus-play#43. While these changes are pretty independent from each other, they are all related to fix some issues with docs for Play 2.5.0.
> Corrections and updates to Specs2 docs

- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
Before the PR: the `CSRFTokenSigner` provided by `BuiltInComponents` was not automatically used by `CSRFComponents`: one had to explicitly alias it (`val tokenSigner = csrfTokenSigner`).
> Rename CSRFComponents.csrfTokenSigner to be consistent with BuiltInComponents

- documentation/manual/working/commonGuide/configuration/ws/DebuggingSSL.md
Verbose logging section used a (very) obsolete example to show debug configuration.
Fix section to use logback style.
> Add updated verbose debugging section

- framework/src/play/src/main/scala/play/api/Application.scala
Another approach would have been to have a dedicated `instanceCache[CookieSigner]` and to use it [here](https://github.com/playframework/playframework/blob/207c1018891b9d8d16ad831ed1303450e5ba627c/framework/src/play/src/main/scala/play/api/mvc/Http.scala#L716) instead of using `Crypto`, because `CookieSigner` is already injectable by `BuiltInComponents`.
> Fix runtime injector provided by BuiltInComponents so that Crypto is injectable

- framework/src/play/src/main/scala/play/api/Application.scala
This a backport of #5856 to the 2.5.x branch.
> Fix Crypto injection

- framework/bin/checkCodeStyle
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/debug/DebugConfigurationSpec.scala
The `./build` script was removed in #5648 but we still refer to it in a couple places.
> Remove references to build script

- documentation/manual/working/javaGuide/main/i18n/JavaI18N.md
- documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
- framework/src/play-integration-test/src/test/scala/play/it/i18n/LangSpec.scala
- framework/src/play-java/src/main/java/play/data/format/Formats.java
- framework/src/play/src/main/java/play/i18n/Lang.java
- framework/src/play/src/main/java/play/i18n/Messages.java
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
Our current regex only accepts two and three-character "country" parts, which means language tags containing script tags such as `zh-Hans` (Simplified Chinese) are not considered valid.
I realized `java.util.Locale` in JDK8 has pretty much everything we need for this. So now a `Lang` is backed by a `Locale` and simply delegates to `Locale` for all of its functionality.
> Allow all language tags supported by java.util.Locale

- documentation/manual/working/scalaGuide/main/http/ScalaSessionFlash.md
The session's maxAge is now different.
Fixes the session maxAge, adds a warning note telling you not to rely on it for security.
Minimal doc impact.
Needs backport to 2.5.x
> [doc] Update session.maxAge

- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- framework/project/Dependencies.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
Upgrade to the last RC of async-http-client.
Here is what have changed between RC9 and RC12:
https://github.com/AsyncHttpClient/async-http-client/compare/async-http-client-project-2.0.0-RC9...async-http-client-project-2.0.0-RC12
> Upgrade async-http-client to version 2.0.0-RC12

- documentation/manual/releases/release25/migration25/StreamsMigration25.md
- framework/src/play/src/main/java/play/mvc/StatusHeader.java
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
Fixes #5866
This removes calls to `FileIO.fromFile` to create a `Source` and, instead uses `StreamConverters.fromInputStream`. As discussed at #5866, by using `FileIO.fromFile` the following exception was being logged even if for successful responses:
```
[warn] i.n.u.c.SingleThreadEventExecutor - A task raised an exception.
java.util.NoSuchElementException: http-handler-body-subscriber
at io.netty.channel.DefaultChannelPipeline.getContextOrDie(DefaultChannelPipeline.java:971)
at io.netty.channel.DefaultChannelPipeline.remove(DefaultChannelPipeline.java:298)
at com.typesafe.netty.http.HttpStreamsHandler.completeBody(HttpStreamsHandler.java:291)
at com.typesafe.netty.http.HttpStreamsHandler.access$100(HttpStreamsHandler.java:16)
at …
```
> Fixes #5866: Use StreamConverters in favor of FileIO

- documentation/manual/working/javaGuide/main/i18n/JavaI18N.md
- documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
- framework/src/play-integration-test/src/test/scala/play/it/i18n/LangSpec.scala
- framework/src/play-java/src/main/java/play/data/format/Formats.java
- framework/src/play/src/main/java/play/i18n/Lang.java
- framework/src/play/src/main/java/play/i18n/Messages.java
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
Backports #5805 to the 2.5.x branch.
@gmethvin See the second commit, I think we only need to add this constructor so it matches to "old" 2.5.x api.
> [Backport] Allow all language tags supported by java.util.Locale

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/java/play/mvc/MultipartFormatter.java
- framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
Hello here is a PR for #902, actually it misses the following things:
Actually before providing a Documentation I wanted to grab some feedback if that is clever enough.
Also I'm not sure where to put tests for that behavior since there aren't many tests for WS yet.
**Edit:** 
Actually what I thought is if I should provide custom interfaces for Part, however then I thought that actually implementing them on top would actually double the work here, however It could be good to add them later, so that we could send JsValue and XML without additional work. However for the moment I found that satisfying, since there aren't many frameworks that actually parse anything else than StringParts and FileParts, actually even Play only knows how to handle Content-Disposition=form-data. 
**Edit2:** I …
> (WIP) Fixes #902 added a way to sent multipart/form-data requests via play-ws

- documentation/manual/working/commonGuide/production/Deploying.md
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/test
Fixes #5320.
Rename `testProd` command to `runProd`. The testProd still exists but shows a deprecation warning.
> Fix #5320: rename testProd command to runProd

- framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java
- framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
- framework/src/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala
- Generally, allows to flatten Java `Accumulator` from `CompletionStage` (as from `Future` with the Scala equivalent).
- More specifically, will allow to restore the possibility to flatten `Future[BodyParser]` (as previously using `BodyParsers.parse.empty.flatMapM(_ => futureBodyParser)`).
> Flatten operation on Java Accumulator

- documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala
- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play-java/src/test/resources/messages.en-US
- framework/src/play/src/main/java/play/i18n/MessagesApi.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Fixes #5875 
`ctx().messages()` [says](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play/src/main/java/play/mvc/Http.java#L187) it `returns the messages for the current lang` but that isn't true. It just uses the request, but doesn't care about the `lang` variable, which could be altered be `changeLang()` or `setTransientLang()`.
A more detailed explanation can be found here: https://github.com/playframework/playframework/issues/5875#issuecomment-196322682
> ctx().messages() takes current lang into account now

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
Add an explicit type annotation to the public `play.api.mvc.Request.apply` method.
DISCLAIMER: I did not yet have a chance to take a deeper look why the inferencer is led astray here, but I think everybody agrees that you don't want to leak that type to API users ;)
Inferred type without ascription:
```scala
def apply[A](rh: RequestHeader, a: A): Request[A] with Object {val clientCertificateChain: Option[Seq[X509Certificate]]; def id: Long; def method: String; def version: String; def path: String; val secure: Boolean; val remoteAddress: String; def queryString: Map[String, Seq[String]]; def uri: String; def tags: Map[String, String]; val body: A; def headers: Headers} = ???
```
changed it to
```scala
def apply[A](rh: RequestHeader, a: A): Request[A] = ???
```
> Add type ascription to play.api.mvc.Request.apply

- framework/project/Build.scala
- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
This PR follows the change done in #5876 
Take into account the language set by `changeLang()` or `setTransientLang()` when called before binding a form by using `ctx.messages()` instead of `msgApi.preferred(ctx.request())`. (I also could have changed it to `msgApi.preferred(ctx.request(), ctx.lang())` but it would exactly the same effect, because that's what `ctx.messages()` actually calls)
Actually I grep'd for all occurences of `preferred(...)` and this was the only occurence were it should be changed.
Some tests now need a running app, that's why I added `in new WithApplication()`. I also added two test scenarios for my changes.
> Use ctx.messages() instead of msgApi.preferred(req) when binding form

- framework/project/Build.scala
- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
> [Backport ]Use ctx.messages() instead of msgApi.preferred(req) when binding form

- framework/src/play-logback/src/main/resources/logback-play-logSql.xml
Actually inside the logback-play-logSql.xml there was a bug so that the documentation here:
- https://www.playframework.com/documentation/2.5.x/JavaDatabase#Log-Statement-Text-/-Slow-Query-Logging
- https://www.playframework.com/documentation/2.5.x/ScalaDatabase#How-to-configure-SQL-log-statement
wouldn't output anything, since the ConnectionLogger, StatementLogger, ResultSetLogger aren't sitting in ``logger.org.*`` they are sitting in ``org.jdbcslog.*``
> Fixes jdbcdslog logback.xml

- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/test/java/play/mvc/RequestBuilderTest.java
Fixes #2289
Adds a bodyMultipart function to the RequestBuilder
Actually inside the bodyMultipart there needs to happen a blocking call, since Helpers.route doesn't accept any CompletionStage / CompletableFuture value.
> Fixes #2289 adds a bodyMultipart function to the request builder

- framework/project/Build.scala
- framework/src/play/src/main/java/play/i18n/Lang.java
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Rationale for the exclusions:
- `Multipart.partParser` was broken and is unlikely to be used externally at this point.
- There is only one major implementation of WS, so it should be okay to add those methods for multipart.
- The `BuiltInComponents` and `CSRFComponents` traits were changed to make compile-time DI work properly and expose all the necessary components. Those traits are not intended to be used by external libraries, so all the code using it should be recompiled.
Several other issues have been fixed.
/cc @jroper 
We still need to decide what to do about the changes in #5888.
> [2.5.x] Fix several binary compatibility issues

- framework/src/play-netty-utils/src/main/java/play/core/netty/utils/CookieUtil.java
- framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
Fixes #4460 
This PR changes the CookieUtil class to reflect the Netty 4.0 CookieUtil with fixes by @slandelle for RFC 6265 cookie compliance.
Minimal changes necessary.
Yes, see #4460 comments for details.
> Update cookie encoder to cover exclaimation points

- framework/src/play-netty-utils/src/main/java/play/core/netty/utils/CookieUtil.java
- framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
Backport of https://github.com/playframework/playframework/pull/5907 for https://github.com/playframework/playframework/issues/4460 for 2.5.x branch.
> [2.5.x] Update cookie encoder to cover valid chars like !

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Fixes https://github.com/playframework/playframework/issues/5824
Removes NONE from the list of WS AuthScheme.
This needs backporting to 2.5.x branch.
> [doc] Remove NONE as AuthScheme

- .travis.yml
- documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala
- framework/bin/codeChecks
- framework/src/play/src/main/java/play/i18n/MessagesApi.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Removes the extra methods added to `MessagesApi` and uses an alternative strategy to achieve the same result.
Also enables MiMa on the 2.5.x branch (closes #5900).
> [2.5.x] Fix binary compatibility issues in MessagesApi

- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/FormBodyParserSpec.scala
- framework/src/play/src/main/java/play/mvc/BodyParser.java
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
Fixes #5919.
Requires backport to 2.5.x.
> Fix default charset in FormUrlEncoded

- documentation/manual/working/scalaGuide/main/http/ScalaBodyParsers.md
Java version doesn't have this issue.
"this can by passing a body parser" => "this can **be done** by passing a body parser"
> [docs] Minor ScalaBodyParsers wording fix

- framework/src/play/src/main/scala/play/api/libs/Crypto.scala
Fixes #5425
Requires backport to 2.5.x/2.4.x
> Explicitly throw error when no application is in scope for Crypto

- documentation/manual/working/commonGuide/production/ProductionConfiguration.md
The title is "Additional Configuration" but it is "Production Configuration" in the TOC and URL.  Changing to "Production Configuration".
> [doc] Rename title to match the TOC

- framework/src/play-integration-test/src/test/java/play/it/http/websocket/WebSocketSpecJavaActions.java
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
Fixes #5924.
Sets the context before calling the action method, so using `Http.Context.current()` within the action works properly.
Requires backport to 2.5.x
> Make sure Context is set for Java WebSocket

- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/Play.scala
- framework/src/play/src/main/scala/play/core/Execution.scala
This should allow us to selectively disable global state in tests. Obviously it's disabled by default because it breaks a ton of tests, but it's a good way of seeing where the issues are.
/cc @jroper
> Add setting to disable global application

- framework/project/Build.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala
- framework/src/play-server/src/main/resources/reference.conf
This adds support for idle connection timeout to the Netty server. Separate timeouts can be defined for http and https connections.
@jroper said that it would be alright to push this to the 2.4.x branch and it could be forward ported to 2.5.x and master
I was unable to get this working with the Akka server. While poking around the code it looks like there is an API for supporting idle timeout but it doesn't seem to be used currently (akka-http-core-experimental-1.0). I left TODOs where changes need to be made for Akka.
> Add idle timeout support for Netty

- framework/src/play/src/main/scala/play/api/libs/Files.scala
- framework/src/play/src/test/scala/play/api/libs/FilesSpec.scala
Fixes #5936 
I think there could still be a race condition here (if the directory is deleted after we call Files.exists but before we create the temp file), but at least if it happens we don't need to restart the app to get things working again.
> Recreate temp directory if it is deleted

- documentation/manual/gettingStarted/Installing.md
- documentation/manual/hacking/Translations.md
- documentation/manual/releases/release21/Highlights21.md
- documentation/manual/releases/release21/Migration21.md
- documentation/manual/releases/release24/migration24/Migration24.md
- documentation/manual/working/commonGuide/filters/SecurityHeaders.md
- documentation/manual/working/commonGuide/production/HTTPServer.md
- documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
- documentation/manual/working/javaGuide/advanced/routing/JavaRoutingDsl.md
- documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
This is just a documentation fix, so I think I can keep unchecked some checklists above.
There is no issue, because this is just a documentation fix.
Remove unnecessary duplications.
While I'm translating the docs into Japanese, I found these duplications.
There're not any relevant issues / PRs / mailing lists discussions.
> Remove duplicate typo words in documentation

- documentation/manual/releases/release25/Highlights25.md
- documentation/manual/releases/release25/migration25/Migration25.md
Migration guide for 2.5.x does not includes information about how to upgrade Play plugin.
See this message at the mailing list:
https://groups.google.com/forum/#!msg/play-framework/aFEkSOaAEbk/CtubkgIxHAAJ
This PR must be backported to 2.5.x. branch.
> Explains how to upgrade Play at the migration guide

- documentation/manual/releases/release25/Highlights25.md
- documentation/manual/releases/release25/migration25/Migration25.md
Backport of https://github.com/playframework/playframework/pull/5938 to 2.5.x
> [2.5.x] Explains how to upgrade Play at the migration guide

- documentation/manual/working/scalaGuide/advanced/extending/ScalaPlayModules.md
Note: The Java counterpart (documentation/manual/working/javaGuide/advanced/extending/JavaPlayModules.md) was not affected, so there is no need to fix the documentation for Java.
> [doc] Fix link to ScalaTestingWithGuice page

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Actually the Documentation of multipart/form data had a bug
that it pointed to the underyling parts of async-http-client
which play doesn't use.
I also added some file upload examples
I found the error cause of #5988 
Actually this needs a backport.
> Documentation fix for multipart/form data in ws

- documentation/manual/working/javaGuide/main/http/JavaActionCreator.md
This PR fixes a typo. 
`HttpRequestHandler`  is a interface in Java API, not a trait.
> typo: trait in place of interface

- documentation/manual/releases/release25/migration25/JavaMigration25.md
* [Yes ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [Yes ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [Yes ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [Yes] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [No new files added] Have you added copyright headers to new files?
* [Related to Java only] Have you checked that both Scala and Java APIs are updated?
* [ Related to Java only ] Have you updated the documentation for both Scala and Java sections?
* [Documentation related ] Have you added tests for any changed functionality?
Fixes …
> Java 2.5 migration guide (Thread Local attributes)

- framework/src/play/src/main/scala/play/utils/Resources.scala
- framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
Allow I18n usage of play 2.4 apps on weblogic.
Loading of I18n messages checks if items on the classpath are directories and breaks the application on unknown protocol e.g. "zip", which exists on weblogic installations.
Original commit introducing the breakage - https://github.com/playframework/playframework/commit/686a9b4535815d24381cea9acd901461fd28a4fa
Fix for 2.3 branch - https://github.com/playframework/playframework/commit/422ca97c54a7ab84cb965df1474f2cd0d11e5fc6 (PR #5728)
> allow i18n usage on weblogic (play 2.4)

- framework/src/play-akka-http-server/src/main/resources/reference.conf
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/resources/reference.conf
- framework/src/play-test/src/main/java/play/test/Helpers.java
- framework/src/play-test/src/main/java/play/test/TestServer.java
- framework/src/play-test/src/main/scala/play/api/test/TestServer.scala
* Modified test API to remove hacks in idle timeout specs
* Set a default idle timeout of 75 seconds (this matches nginx keep alive timeout)
* Changed config to read Duration and use null as infinite
* Refactored NettyServer to use PlayConfig
> Improved idle timeouts

- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
Typo ScalaDependencyInjection.md:
```
Declaring runtime DI depndencies
```
"depndencies" -> "dependencies"
> Fix typo in ScalaDependencyInjection.md

- documentation/manual/releases/release25/migration25/Migration25.md
- framework/src/play/src/main/java/play/mvc/StatusHeader.java
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/java/play/mvc/ResultsTest.java
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Fixes #5872.
This made Java Results API more consistent while sending files/paths and resources. It was also checked against Scala API to ensure consistent between the two APIs (at least in relation to sending files, paths and resources).
See #5872.
> Resolve small inconsistencies at Results API

- templates/play-common/conf/application.conf
- templates/play-java-intro/conf/application.conf
- templates/play-scala-intro/conf/application.conf
`play.http.filters` isn't a sequence/list. [See](https://github.com/playframework/playframework/blob/2.5.1/framework/src/play/src/main/resources/reference.conf#L60) `reference.conf`.
When using `+=` you get following exception:
```
play.api.Configuration$$anon$1: Configuration error[reference.conf @ jar:file:.../jars/play_2.11.jar!/reference.conf: 60: Cannot concatenate object or list with a non-object-or-list, ConfigNull(null) and SimpleConfigList(["filter.Filters"]) are not compatible]
at play.api.Configuration$.configError(Configuration.scala:154)
at play.api.Configuration$.load(Configuration.scala:101)
at play.api.Configuration$.load(Configuration.scala:109)
at play.api.ApplicationLoader$.createContext(ApplicationLoader.scala:91)
at …
```
> Fix bug in application.conf template

- documentation/manual/working/javaGuide/main/http/JavaBodyParsers.md
- documentation/manual/working/scalaGuide/main/http/ScalaBodyParsers.md
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaRequestsSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/DefaultBodyParserSpec.scala
- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play/src/main/java/play/mvc/BodyParser.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fixes #5503.
If a `Content-Length` or `Transfer-Encoding` header is present on the request, then it must have a body. In this case, we should always try to parse a body, regardless of the HTTP method.
This also fixes the Akka HTTP model conversion to make sure those headers show up.
(also closes #5756)
> Make default body parser parse if and only if a body is present

- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
Adds a way to set a manual Content-Length Header for Streaming Bodies, this could be useful if you want to send multipart/form data bodies to Clients that can't make use of Transfer-Encoding: chunked (i.e. WSGI)
Actually with this it's possible to manually provide the Content-Length however in the Future we could maybe create a way to determine it, but I doubt that this would break Mima.
i.e. I had tests that checked the headers but actually only on Netty or Akka (don't know which) the Content-Length/Transfer-Encoding will be in the Request Headers. 
https://groups.google.com/forum/#!topic/play-framework/mcA7jmnCiAw
Needs Backport
> Made it possible to specify a Content-Length Header for a StreamedBody

- framework/src/play/src/main/scala/views/defaultpages/devError.scala.html
- framework/src/play/src/main/scala/views/helper/requireJs.scala.html
Partially reverts 65610c1890d9ee07caa8b10bba590c429f17da05
The `requireJs.scala.html` template stopped working for us since 2.5.0 and I think the changes @jroper made to `requireJs.scala.html` and `devError.scala.html` may have been accidental.
Please have a look.
> Fix data-attibutes in devError and requireJs partials

- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- framework/project/Dependencies.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
Upgrade Async-Http-Client to version 2.0.0.
https://github.com/AsyncHttpClient/async-http-client/tree/async-http-client-project-2.0.0
> [master]: Upgrade async-http-client to version 2.0.0

- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- framework/project/Dependencies.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
Backports upgrade Async-Http-Client to version 2.0.0.
1. #6036
2. https://github.com/AsyncHttpClient/async-http-client/tree/async-http-client-project-2.0.0
> [2.5.x]: Upgrade async-http-client to version 2.0.0

- framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala
Remove usage of deprecated procedure syntax in `LogbackLoggerConfigurator.shutdown`
> Remove procedure syntax in LogbackLoggerConfigurator.shutdown

- framework/src/play-integration-test/src/test/scala/play/it/views/DevErrorPageSpec.scala
- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
- templates/play-common/conf/application.conf
Fixes https://github.com/playframework/playframework/issues/3892
The `play.editor` setting was not being applied -- this change ensures that error pages can read the value in for the DefaultHttpErrorHandler singleton object.
> Add check for play.editor setting

- framework/src/play/src/test/java/play/mvc/RangeResultsTest.java
This will fix the 2.5.x branch since it removes the duplicated test that wasn't updated.
> shouldReturnRangeResultForStream was duplicated

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Fixes #6057 
The headers map is now created using the case insensitive ordering, and I checked to see that methods that extract headers use the case-insensitive comparison.
We might want to consider refactoring how this is done in the future. Having `AhcWSRequest` accept a generic `Map` type does not give the guarantees we want. We should probably fix it when we fix #5811.
This should be backported to 2.5.x.
> Make sure headers are handled case-insensitively in AhcWSRequest

- framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
Assets controller was adding a `Content-Disposition` header when serving files. This is not necessary and also changes the way this was working before. This must be backported.
See discussion at gitter channel: https://gitter.im/playframework/playframework?at=5715069c2c9711166432efb1
> Do not add Content-Disposition header when serving assets

- documentation/manual/gettingStarted/NewApplication.md
- documentation/manual/hacking/Repositories.md
dl.bintray.com is considered the implementation detail for where those artefacts
are served from. repo.typesafe.com is the canonical URL.
> Use repo.typesafe.com rather than dl.bintray.com

- framework/src/play/src/main/java/play/ApplicationLoader.java
- framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
The documentation [says](https://www.playframework.com/documentation/2.5.x/ScalaCompileTimeDependencyInjection#Application-entry-point) that the configuration key for setting a custom application loader is `play.application.loader`, but in ScalaDoc it was `application.loader`.
> Fix configuration key name in ScalaDoc for ApplicationLoader trait

- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaCompileTimeDependencyInjection.md
Fixes #6062, adds reference to macwire and Adam Warski's DI in Scala guide, and removed the "Current application" section which didn't seem that useful
> Update compile-time DI docs

- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
This is actually a follow-up fix to #1403.
By throwing the exception up front, it makes it easier to determine where the null header is inserted, and also makes it possible for filters to detect this type of error.
> Handle null response headers

- framework/src/play/src/main/scala/play/api/mvc/Http.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
Fixes #6066
This uses a regex since we are only trying to extract the host and port, and we don't really care if the rest of the URI is valid. I think this is a better solution than throwing an exception unexpectedly, especially since in many cases the host is just the value of the `Host` header and has nothing to do with the request URI.
> Get host properly even if full URI is invalid

- documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
csrf bypassHeaders configuration example has incorrect config key "play.filters.csrf.headers.bypassHeaders" when it is "play.filters.csrf.header.bypassHeaders" in the code.
> typo in csrf documentation

- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/view.scala.html
- documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/user.scala.html
Only displaying `error.message` is wrong. Right now the documentation doesn't take the validation error arguments into account.
We for example create (global) `ValidationError`s (the java ones) like this:
```java
new ValidationError("", "msgkey", Arrays.asList("msgarg1", "msgarg2"));
```
> Doc fix: Correctly look up validation errors in messages

- framework/src/play/src/main/java/play/mvc/StatusHeader.java
- framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/main/scala/play/utils/UriEncoding.scala
- framework/src/play/src/test/java/play/mvc/RangeResultsTest.java
- framework/src/play/src/test/java/play/mvc/ResultsTest.java
- framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Fixes #5253
Support non-ISO8859-1 filename n Content-Disposition header (see [RFC 6266](https://tools.ietf.org/html/rfc6266)).
See #5253
> Support non-ISO8859-1 filename in Content-Disposition header

- documentation/manual/working/commonGuide/configuration/SettingsLogger.md
- documentation/manual/working/commonGuide/configuration/code/Log4j2LoggerConfigurator.scala
- documentation/manual/working/commonGuide/configuration/code/ThreadPools.scala
- framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala
- framework/src/play/src/main/scala/play/api/LoggerConfigurator.scala
- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
- framework/src/play/src/test/scala/play/api/LoggerConfiguratorSpec.scala
Fixes https://github.com/playframework/playframework/issues/2833
This PR exposes configuration properties from application.conf to Logback.    So given a "play.http.context" property in application.conf, you can expose it with `${play.http.context}`:
```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
<encoder>
<pattern>%coloredLevel context = ${play.http.context} - %logger - %message%n%xException</pattern>
</encoder>
</appender>
```
This is a deliberately unclever implementation that passes everything through properties, so that there's no logic in Play-Logback itself if necessary and it's all done in GuiceApplicationLoader.  This means that anyone who wants to pass in custom properties to the logger or modify the logic can do it through ApplicationLoader rather than …
> Expose play config properties to logback

- documentation/manual/releases/release25/migration25/Migration25.md
- framework/src/play/src/main/java/play/mvc/StatusHeader.java
- framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/main/scala/play/utils/UriEncoding.scala
- framework/src/play/src/test/java/play/mvc/RangeResultsTest.java
- framework/src/play/src/test/java/play/mvc/ResultsTest.java
- framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
> [2.5.x] Support non-ISO8859-1 filename in Content-Disposition header

- framework/src/play/src/main/java/play/mvc/RangeResults.java
- framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala
- framework/src/play/src/main/scala/play/core/j/JavaRangeResult.scala
- framework/src/play/src/test/java/play/mvc/RangeResultsTest.java
- framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
Support optional entity-length for range requests, as documented by [RFC 7233](http://tools.ietf.org/html/rfc7233#section-4.2). This PR can be safety backported to 2.5.x after being merged.
See #5961.
----------------
@schmitch and @mkurz you may be interested in reviewing this. ;-)
> Optional entity length for range requests

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
- framework/src/play-java/src/test/scala/play/data/DynamicFormSpec.scala
- framework/src/play/src/main/scala/play/api/data/Form.scala
Just a small fix.
We have a test where we create a `DynamicForm` or `Field` without any injected components (no `MessagesApi`, `Validator`, etc.)
When we want to access a field on this dummy `DynamicForm` we get a `NullPointerException` because no validator is set.
E.g. this line throws the NPE:
```
new DynamicForm(null, null, null).field("somefield");
```
Please backport before the `2.5.3` release, thanks!
> Don't throw NPE when variables in a Form or a Field are null

- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
If the path of the URI is null, it can cause NPEs in the router and in user code. This normally doesn't happen in an HTTP request, but it seems it can happen if you send a URI which does not have a path component defined, for example:
```
GET mailto:foo@example.com HTTP/1.1
```
It seems appropriate to send a 400 error in this case. I've done that here by throwing an exception.
This was discussed on the mailing list as well: https://groups.google.com/forum/#!topic/play-framework/-bsLA-UTyis.
> Trigger 400 error if path is null

- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/Streamed.scala
Fixes scaladoc for deprecated methods.
Before:
```
Deprecated   (Since version Use WS.stream() instead.) 2.5.0
```
After:
```
Deprecated   (Since version 2.5.0) Use WS.stream() instead.
```
Note, according to `git grep -l '@deprecated\s*(\s*"\d'` these were the only occurrences.
> Fix @deprecated annotations

- documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala
* [N/A] Have you added copyright headers to new files?
* [N/A] Have you checked that both Scala and Java APIs are updated?
* [N/A] Have you added tests for any changed functionality?
Fixes #6105
Fixes call to deprecated API in documentation 
Following the documentation caused me to use deprecated API which caused build warnings
> remove redunant call to deprecated API in TestingWebServices docs

- documentation/manual/working/javaGuide/main/application/code/javaguide/application/def/ErrorHandler.java
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/root/ErrorHandler.java
- documentation/manual/working/scalaGuide/main/http/code/ScalaErrorHandling.scala
Play's own `DefaultHttpErrorHandler` [is a singleton](https://github.com/playframework/playframework/blob/fc86a2e3993ca6cdc80d80ef937712d31d6e6c06/framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala#L70-L71) as well.
> ErrorHandlers should be singletons in docs

- documentation/manual/working/commonGuide/filters/code/AllowedHostsFilter.scala
- documentation/manual/working/commonGuide/filters/code/CorsFilter.scala
- documentation/manual/working/commonGuide/filters/code/GzipEncoding.scala
- documentation/manual/working/commonGuide/filters/code/SecurityHeaders.scala
- documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/cors/Filters.java
- documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/headers/Filters.java
- documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/hosts/Filters.java
- documentation/manual/working/javaGuide/main/application/JavaHttpFilters.md
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/Filters.java
- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf/Filters.java
- documentation/manual/working/scalaGuide/main/application/ScalaHttpFilters.md
- documentation/manual/working/scalaGuide/main/application/code/ScalaHttpFilters.scala
- documentation/manual/working/scalaGuide/main/forms/code/ScalaCsrf.scala
- framework/src/play/src/main/java/play/http/DefaultHttpFilters.java
- framework/src/play/src/main/scala/play/api/http/HttpFilters.scala
- templates/play-java/app/Filters.java
Fixes #6115.
This creates a `DefaultHttpFilters` class that extends `HttpFilters` in both Java and Scala. This makes the Java API in particular much easier to use for simple cases:
```java
public class Filters extends DefaultHttpFilters {
@Inject public Filters(GzipFilter gzip, LoggingFilter logging) {
super(gzip, logging);
}
}
```
Another advantage is that this doesn't require the `.asJava()` conversion on the filters.
One limitation is that since we're using `super`, you can't do much logic in the constructor since `super` has to be the first call, but I think most of that logic should be done by either binding a different `HttpFilters` implementation (for example based on application mode) or by binding different implementations of those filters.
> Provide helper for creating HttpFilters

- documentation/manual/working/commonGuide/configuration/code/detailedtopics/httpec/MyController.java
- documentation/manual/working/commonGuide/filters/code/GzipEncoding.scala
- documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/gzipencoding/CustomFilters.java
- documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/gzipencoding/Filters.java
- documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredActor.java
- documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ParentActor.java
- documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/inject/Application.java
- documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/inject/Application.java
- documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/CircularDependencies.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java
- documentation/manual/working/javaGuide/main/sql/code/JavaApplicationDatabase.java
- documentation/manual/working/javaGuide/main/sql/code/JavaJdbcConnection.java
- documentation/manual/working/javaGuide/main/sql/code/JavaNamedDatabase.java
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClient.java
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClientTest.java
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/InjectionTest.java
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWebServiceClients.java
As discussed in #5837, constructor injection is easier to understand for newbies to DI, and is the right way to use DI in a real application, so I've converted all the documentation examples to use constructor injection instead of field injection.
> Prefer constructor injection in documentation

- documentation/manual/releases/release25/migration25/JavaMigration25.md
In the context of the other listed methods I think this makes it more clear.
> Docs: Supplier returns type; it does not take an argument

- framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala
Makes it possible to load the logger configuration through the `logger.url` system property.
This should be supported according to documentation at https://www.playframework.com/documentation/2.5.x/ProductionConfiguration
> Use logger.url system property for logger configuration

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/main/java/play/data/FormFactory.java
[`validator.validate(...)`](https://github.com/playframework/playframework/blob/2.5.3/framework/src/play-java/src/main/java/play/data/Form.java#L353) actually takes an array/varargs as second argument. We should reflect this in the Play Form api as well.
Right now it is not possible to use more than one validation group, which is a pain. We actually ran into this limitation today - we have a complex form in which we want to use three validation groups to distinct different form submission scenarios.
I overloaded the form constructors to accept a groups array in addition to the single group object.
I also removed the deprecated static methods for creating a form in favor of DI.
> Group(s) in form should be an array/varargs

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/main/java/play/data/FormFactory.java
Backport of #6124, except that I can't remove the static form methods because of backwards compatibility - so I simply changed the second argument to take varargs.
> [Backport] Group(s) in form should take an array/varargs

- documentation/manual/working/javaGuide/main/json/JavaJsonActions.md
Fixes #5953
Replaces documentation link to Jackson. The old link: http://jackson.codehaus.org/ which is no longer valid. The new link: https://github.com/FasterXML/jackson#documentation
There is only one link to codehaus website.
> [doc] Replace invalid link to Jackson documentation (#5953)

- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Corrects the code example shown in the documentation for using a wsclient without injecting the configuration through play.
The code on the documentation page would not compile without this change.
> Move environment definition into code example

- framework/src/play-jdbc-evolutions/src/main/resources/reference.conf
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- framework/src/play-jdbc/src/main/resources/reference.conf
I have been operating the service in a micro- service architecture.
In a particular service instance,
sometimes evolution script is not up-to-date.
so, I wish to skip the evolution scripts if downs only.
> add evolutions parameter `skipApplyDownsOnly`

- documentation/manual/gettingStarted/Tutorials.md
Make the distinction between core / 3rd party maintained templates clearer
The documentation didn't say clearly that the templates under "playframework" are maintained and current, while the 3rd party templates are by whatever version they were released at.
Added https://github.com/playframework/playframework/pull/6118 under the 3rd party section as it is not a core Play template.
Some minor tweaks to whitespace and headers.
> More changes to Tutorials.md

- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
Fixes deprecation warnings 
`   Method route in trait RouteInvokers is deprecated: Use the version that takes an application` 
in spec/test code:
-   `SecurityHeadersFilterSpec`, 
-  `GzipFilterSpec`,
-  `CORSSpec`,
-  `AllowedHostsFilterSpec`
> Clean deprecation warnings in spec code

- framework/src/play/src/main/scala/play/api/http/MediaRange.scala
Fixes #6139 (see also #2406)
If the parser is at the end of the input, there are no more tokens left to parse, which means the parse was successful.
> Negate predicate for logging media range parsing errors

- framework/src/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
- framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/ConnectionPool.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
Fixes #6149 
To enable SQL logging with jdbcdslog the data source needs to be wrapped in a org.jdbcdslog.LogSqlDataSource. This was previously done at the database API level (in Databases.scala) before data sources were registered with JNDI. This causes database operations that use JPA to not be logged as their data source is not wrapped in a org.jdbcdslog.LogSqlDataSource. Now each supported connection pool wraps its own data sources when they are created and unwraps them before they are closed.
The data sources are already registered with JNDI in the implementation classes for both supported connection pools, so I modified both to also automatically wrap the data source in a org.jdbcdslog.LogSqlDataSource if logSql is set to true. I have also moved the code that unwraps a data source …
> jdbcdslog is now enabled at the connection pool / data source level

- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
Properly forward the persistence unit name instead of the `default` one. Fixes wrong persistence unit name that use the `default` instead of the provided one.
Very simple quick fix. We are using 2 persistence unit (none of them are named `default`) and that's why we saw the error.
Well very simple fix :)
Nop
> Properly forward the persistence unit name in Java DefaultJPAApi

- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaRequestsSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultException.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
Fixes #6099.
When the backend server (Netty, Akka HTTP) discovers an error in a result (e.g. invalid headers) the server needs to abort processing the result and send an error result to the user. Previously, this error
handling was done with custom error handling code for the server.
This pull request changes the server behavior to use the application's `HttpErrorHandler` to generate the error result instead of the server generating a custom error response. Using the existing error handler makes the error handling more standardized. It also means that the application will be notified when an error occurs during result generation, which will make it easier to track errors that occur in Play applications (see #6098, #6099).
This pull request changes the signature of `HttpErrorHandler`'s …
> Better Result error handling

- documentation/manual/working/scalaGuide/main/upload/ScalaFileUpload.md
- documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
Fixes https://github.com/playframework/playframework/issues/6182
This code sample adds a snippet to ScalaFileUpload.md and uses code from https://github.com/wsargent/play-fileupload-scala to show how to use a custom FilePartHandler with Akka Streams.
The page previously referenced an Iteratee and a PartHandler, and did not have an example.
> [doc] Add an example showing a custom FilePartHandler

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/java/play/data/LoginCheck.java
- framework/src/play-java/src/test/java/play/data/PasswordCheck.java
- framework/src/play-java/src/test/java/play/data/SomeUser.java
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
Now that we finally can use as many validation groups in forms as we want (#6124), there is one thing I would consider a bug.
Right now, when you retrieve a field from a form (via `myForm.field("fieldname")`), we *always* return the field with **all** of its constraints, no matter if we told the form to use a specific validation group or not.
This is wrong.
If you create a form and tell it to use (a) specific validation group(s) than only the constraints should be added (to a field) which match any of the validation groups the form actually currently uses.
For example if you display all fields of a form in a view, and all fields contain the `@Required` constraint, but some of this constraints use a specific validation group like `@Required(groups = MyGroup.class)` and you create the form …
> Only add/display constraint(s) which match the used validation group(s)

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala
This adds basic authentication to WSRequest Logging
I wanted to check for feedback on this change before implementing curl request conversion for more WsRequests. 
None
The request logger doesn't log auth for curl requests, this change
adds the --user flag to the curl request when auth is basic.
> Add basic auth params to AHCRequestLogger

- framework/project/Dependencies.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
Fixes #6190 for `2.5.x` branch
> Fix displaying runtime exception coming from Twirl template while running in development mode - PR for branch 2.5.x

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Config.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/SSLConfigParserSpec.scala
actually there should be a warning so that you don't enable acceptAnyCertificate in production
As discussed here: https://github.com/playframework/playframework/pull/6170
> added a warning inside the play ws ssl config parser

- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/Application.java
Small update on example to use JavaScriptReverseRouter
https://www.playframework.com/documentation/2.5.x/api/java/play/routing/JavaScriptReverseRouter.html
play.Routes and Routes.javascriptRouter has been deprecated
> Updated example to 2.5.x (play.routing.JavaScriptReverseRouter)

- documentation/manual/releases/release25/migration25/Migration25.md
Add key documentation for Build.scala users wanting to configure the routesGenerator. 
No code changes, just docs.
> Build.scala import for routesGenerator configuration

- framework/project/Dependencies.scala
A potential memory leak issue.
slf4j project highly recommends bumping version [here](http://www.slf4j.org/news.html):
Releases 1.7.19 and 1.7.20 suffer from a memory leak. Please use version 1.7.21 or later instead.
See the purpose section.
http://jira.qos.ch/browse/SLF4J-364
> Bump slf4j minor version to fix a memory leak issue (SLF4J-364)

- framework/src/play/src/main/java/play/http/DefaultHttpFilters.java
Fixes #6237
This PR addresses a ClassCastException in DefaultHttpFilters.java
This seemed like an intuitive approach given the StreamAPI toArray() interface.
https://github.com/playframework/playframework/issues/6237
> This fixes a ClassCastException introduced in DefaultHttpFilters.java

- documentation/manual/gettingStarted/Tutorials.md
I need to use my personal name as attribution for this tutorial, I should not have used the name of the organisation who I produced the work for.
> change author name of 3rd party tutorial to be personal not corporate

- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
Revise the doc for `DefaultInstantReads`.
It will throw exception if user follows the comment.
`JsString("2011-12-03T10:15:30")` cannot be read `as[Instant]`, because there is no time zone info in the `TemporalAccessor` parsed by `DateTimeFormatter.ISO_DATE_TIME`.
> update doc for play-json DefaultInstantReads

- framework/src/play-guice/src/main/java/play/inject/guice/GuiceApplicationLoader.java
Javadoc isn't finding ApplicationLoader.Context. Changing so it works in the nightly build.
> Fix javadoc generation

- framework/project/Build.scala
This pull request is just a suggestion on migration manager usage.
Currently, the `master` branch checks bin-compatibility with only 2.5.0. But the current setting may miss bin-incompatibility in some cases. For instance, it cannot detect unexpected deletion of new methods introduced 2.5.{1,2,3,4}.
> Suggestion: validating bin compatibility with all the patch versions in 2.5 series

- framework/src/play/src/main/scala/play/api/data/Forms.scala
- framework/src/play/src/main/scala/play/api/data/format/Format.scala
- framework/src/play/src/test/scala/play/api/data/FormSpec.scala
- framework/src/play/src/test/scala/play/api/data/format/FormatSpec.scala
Fixes No java.time.LocalDate form mappings available
Form mappings do not support java.time.LocalDate. This PR adds this functionality for form mapping
Currently, to use java.time.LocalDate in domain objects mapped to form definitions, one has to take in the LocalDate in as a joda LocalDate and convert to java.time LocalDate. By introducing a localdate mapping for form data, one can use the new java.time.LocalDate directly.
> Add java.time.LocalDate support to Forms Mapping

- framework/project/Build.scala
Allows a more free-form version pattern as long as it starts with x.y.z
> Fix version pattern

- framework/src/play-ws/src/main/resources/reference.conf
Fixes "Configuratino" to "Configuration" on play-ws/reference.conf
Fix typo in conf file comment.
While reading code for study, I found this typo.
There're not any relevant issues / PRs / mailing lists discussions.
> Fix typo in play-ws/reference.conf comment

- framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
- framework/src/play-netty-server/src/main/java/play/core/server/netty/PlayHttpContentDecompressor.java
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Fixes #6152 
This implements what jroper suggested https://github.com/typesafehub/netty-reactive-streams/pull/19#issuecomment-226998199
Akka Test is pending until fixed (it can't decode deflate/gzip yet)
> Fixes #6152 by customizing the HttpContentDecompressor

- framework/src/play/src/main/scala/play/api/Application.scala
This PR deprecates methods of `Application` that are already available in `Environment`.
> Deprecate some methods of Application that are mirrored in Environment

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
I know this probably will avoid someone not understand why their application does not behave as expected because of a silly `T` character instead of `t`.
See [AhcConfigSpec](https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcConfigSpec.scala) and [reference.conf](https://github.com/playframework/playframework/blob/master/framework/src/play-ws/src/main/resources/reference.conf)
I think it should be backported to `master`.
> Fix typo in documentation for WS

- framework/src/play/src/main/java/play/mvc/Results.java
- framework/src/play/src/main/java/play/mvc/StatusHeader.java
- framework/src/play/src/test/scala/play/mvc/ResultSpec.scala
Fixes #6282
Now in order to send a JSON response in Java, you have to specify an encoding that is valid for `application/json`. This has been made more clear by using JsonEncoding instead of String to represent the encoding, and deprecated the String-based methods.
We can backport this to 2.5 but without the deprecations.
> Validate charset when we send JSON results

- templates/play-java-intro/app/controllers/PersonController.java
* [x ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [ x] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ x] Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* [ x] Have you added copyright headers to new files?
* [ x] Have you checked that both Scala and Java APIs are updated?
* [ x] Have you updated the documentation for both Scala and Java sections?
* [ x] Have you added tests for any changed functionality?
No issues
This PR is just to remove a useless casting in the play-java-intro template.
Casting is …
> Remove casting in query

- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala
Fixes #5838 
Fix the pattern match so that `Terminated` messages are processed correctly.
> Websocket actor termination fix

- framework/src/play-netty-utils/src/main/java/play/core/netty/utils/CookieUtil.java
- framework/src/play-netty-utils/src/main/java/play/core/netty/utils/DefaultCookie.java
- framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
no issues
This commit applies [1] to the Play's cookie encoder/decoder implementation, for better RFC6265 following
This commit applies [1] to the Play's cookie encoder/decoder implementation.
Netty was update cookie encoder/decoder at 2015/4/14 [2] and 2016/5/19 [1].
And Play was update cookie encoder/decoder at 2015/5/11. So, [1] is not applied to Play yet.
[1] is `Drop broken DefaultCookie name validation`.
Detail is discussed in issue [4] `DefaultCookie's own name validation doesn't conform to RFC6265 #4999`.
I think, current Play's DefaultCookie has the same issue.
> it doesn't conform to RFC6265, eg seperators such as @ are allowed
> it's redundant with the checks performed in CookieEncoder/Decoder in STRICT mode (those are RFC6265 compliant)
And, RFC6265 accepts, cookie-name which …
> Apply Netty's cookie encoder/decoder updates.

- .travis.yml
- framework/bin/rehearseMicrobenchmarks
- framework/project/Build.scala
- framework/project/plugins.sbt
- framework/src/play-microbenchmark/src/main/scala/play/api/mvc/Cookies_01_ReadCookieFromHeader.scala
- framework/src/play-microbenchmark/src/main/scala/play/api/mvc/MvcHelpers.scala
- framework/src/play-microbenchmark/src/main/scala/play/api/mvc/RequestHeader_01_ReadHeaderValue.scala
- framework/src/play-microbenchmark/src/main/scala/play/core/server/netty/NettyHelpers.scala
- framework/src/play-microbenchmark/src/main/scala/play/core/server/netty/NettyModelConversion_01_ConvertMinimalRequest.scala
- framework/src/play-microbenchmark/src/main/scala/play/core/server/netty/NettyModelConversion_02_ConvertNormalRequest.scala
The microbenchmarks have been added in a new Play subproject called Play-Microbenchmark. The microbenchmarks are executed using JMH via the sbt-jmh plugin. They can be run with the `jmh:run` command. I've added a few simple benchmarks to show how they are implemented.
Cc @gmethvin, @wsargent, @ktoso.
> Add some microbenchmarks

- framework/src/play/src/main/scala/play/api/http/StandardValues.scala
The `Link` header is used for many things including server push in HTTP/2 so it would be convenient to have it provided here.
> Add `Link` header to StandardValues

- framework/src/play-server/src/main/resources/reference.conf
Right now you can set `play.editor` in `application.conf`.
The problem is on compilation errors this setting will not (better: can't) be read and therefore in such a case no link is available.
A workaround, which works now already, is to set
```
javaOptions += "-Dplay.editor=http://localhost:63342/api/file/?file=%s&line=%s"
```
in `build.sbt`.
This also displays a link even when compilation errors occur - because this java system property gets also read and set even when the `application.conf` doesn't/can't get loaded/read (which happens when compilation errors occur).
But IMHO putting this settings in `build.sbt` isn't really nice.
Also a problem is different developers use different IDE's which need different links.
Therefore I added the feature to read `play_editor` from the …
> Read play.editor from environment variables as fallback

- framework/src/play-streams/src/main/scala/play/api/libs/streams/AkkaStreams.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/GzipFlow.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/Probes.scala
- framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
- framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
PushPullStage based implementations are deprecated and must be migrated to GraphStage.
Related to PR https://github.com/playframework/playframework/pull/6022
> Migrate PushPullStage based implementations to GraphStage

- framework/src/play-java/src/main/java/play/data/Form.java
- framework/src/play-java/src/test/scala/play/data/FormSpec.scala
Fixes https://groups.google.com/d/topic/play-framework/95d3ZsWGm4M/discussion
We also bumped into this limitation - the fix is quite easy :smile: 
Details:
Right now it's impossible to get the form value when the form has errors - because in such a case the value never gets set!
I expect [`myform.value()`](https://github.com/playframework/playframework/blob/2.5.4/framework/src/play-java/src/main/java/play/data/Form.java#L494-L496) to return the backed value even if the form has errors - it returns an `Optional` anyway.
The very similiar [`myform.get()`](https://github.com/playframework/playframework/blob/2.5.4/framework/src/play-java/src/main/java/play/data/Form.java#L631-L636) will still throw an exception when the form has errors - that's ok.
> Set Form value even when form has errors

- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSResponse.java
Fixes #6316
Adds the correct content encoding to WSResponse asXml()
> Fixed #6316 encoding will be applied to asXml

- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaCompileTimeDependencyInjection.md
- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
Fixes the absence of `CSRFCheck` and `CSRFAddToken` in the `CSRFComponents` trait.
It also enhances the documentation by mentioning the `CSRFComponents` in the compile time dependency injection page, and the csrf page.
I didn't add a unit test as I'm unsure about how to test the presence of a field nor did I find any similar example but please let me know if I missed anything.
If this is accepted on master I'll cherry pick it on the 2.5.x branch as I believe it will be useful.
This will help users trying to use CSRF per endpoint when they use compile time dependency injection as these two components are currently missing.
https://github.com/playframework/playframework/pull/6323
> Add csrfCheck and csrfAddToken to the CSRFComponents

- framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala
- framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
Currently the regular expression in https://github.com/playframework/playframework/blob/2.5.4/framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala#L268-L271 will not match expected range header values.
E.g.
```scala
val WithoutEntityLengthRangeSetPattern = """^bytes=([0-9]+-[0-9]+,?)+""".r
val header = "bytes=1-2"
header match {
case WithoutEntityLengthRangeSetPattern() => ...
case _ => ...
}
```
Will incorrectly fall through to `case _ => ...` even though `header.matches(WithoutEntityLengthRangeSetPattern.regex)` is `true`
We need to add a parameter or `_` to the case statement as I have in this PR to allow it to successfully match.
```scala
header match {
case WithoutEntityLengthRangeSetPattern(_) => ...
case _ => ...
}
```
Will match correctly.
> Fix range result pattern match bug

- documentation/project/Build.scala
- framework/project/Build.scala
- framework/project/Dependencies.scala
- templates/play-java-intro/build.sbt
- templates/play-java/build.sbt
- templates/play-scala-intro/build.sbt
Actually I don't think its a good idea to directly ship a database driver. So I think this one should be exludeded.
https://groups.google.com/forum/#!topic/play-framework/FEMIT-40tks
> removes h2 from play-jdbc as a compile dependency

- framework/src/play-server/src/main/scala/play/core/server/ssl/ServerSSLEngine.scala
- framework/src/play/src/main/scala/play/server/api/SSLEngineProvider.scala
Fixes #6341 
Scaladoc has incorrect `play.http.sslengineprovider` config reference. Fixed that to correct reference `play.server.https.engineProvider`
> Fixed incorrect config reference in scala doc [#6341]

- framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala
- framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java
- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala
Makes the Method withMultipartBody public and renames it to withBody.
Actually that can't work on Java since there is a `WSRequest setBody(Source<ByteString,?> body);` and due to type erasure we can't have a `setBody(Source<? extends..)` any ideas to do that aswell?
had a Conversation with @akkie that it's better to make it public
> renamed withMultipartBody to withBody and made it public

- framework/project/Dependencies.scala
- framework/src/play/src/main/java/play/libs/XML.java
- framework/src/play/src/main/scala/play/api/Play.scala
Removes xerxces since it's already included in the JDK.
https://groups.google.com/forum/#!topic/play-framework/FEMIT-40tks
> removes xerces

- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ApplicationTest.java
Documentation fix
The docs are explaining how to use a FakeRequest [here](https://www.playframework.com/documentation/2.5.x/JavaTest#Unit-testing-controllers), but the example omits that. Here is the original:
> You can also retrieve an action reference from the reverse router and invoke it. This also allows you to use FakeRequest which is a mock for request data:
> ```
@Test
public void testCallIndex() {
Result result = route(
controllers.routes.HomeController.index(),
);
assertEquals(OK, result.status());
}
```
> Add an example of the FakeRequest being explained

- documentation/manual/working/commonGuide/database/Developing-with-the-H2-Database.md
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
Actually this takes the first approach it adds a note on the H2 Documentation and also gives a nice error message when calling `h2-browser`.
Another possible resolution would be removing all, which is feasable, too I guess since H2 shouldn't be encouraged to be used in Production anyways. And h2-browser is also just a wrapper around the H2-Browser.
> Fixes #6352: added a note to the h2 doc

- framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala
- framework/src/play/src/main/scala/play/api/controllers/ExternalAssets.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Fixes #6351
Makes onClose of Results#sendFile working
Actually if somebody has an idea to make the Unittest better, tell me
Actually if we backport it we could actually put `play.api.libs.concurrent.Execution.defaultContext` as a paramter directly instead of having a `implicit ec: ExecutionContext`
> Fixes #6351 made the parameter onClose of sendFile working again

- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
- framework/src/play/src/test/scala/play/mvc/ResultSpec.scala
Finally Fixes #6360
Actually in https://github.com/playframework/playframework/pull/6363 we fixed the Fragment URL, but somehow one method slipped through, this fixes it so that #6360 could be closed. 
Also needs backport. This also moves the tests on the correct place.
> append fragment in Results.Redirect(call, status)

- framework/src/play/src/main/java/play/mvc/Results.java
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/test/scala/play/mvc/ResultSpec.scala
Fixes #6360 
Actually this includes the fix in https://github.com/playframework/playframework/pull/6366
@gmethvin maybe we could actually make a 2.4.x release after that?
**Edit** Build only fails on Travis-CI. Unrelated to my change.
> [Backport 2.4.x]  Append fragment (use Call.path instead of Call.url) when redirecting (#6363)

- framework/src/play-java/src/main/java/play/libs/Resources.java
- framework/src/play-java/src/test/java/play/libs/ResourcesTest.java
Fixes #5547
Introduces function for async try-with-resource
> Add async try-with-resources for java api

- documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md
- documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
- framework/src/play/src/main/java/play/mvc/BodyParser.java
This PR adds a custom FilePartHandler to the Java Multipart BodyParser API.
This brings the Java API up to parity with the Scala API, which allows for custom FilePartHandler:
https://www.playframework.com/documentation/2.5.x/ScalaFileUpload#Writing-your-own-body-parser
https://github.com/playframework/playframework/blob/2.5.4/framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala#L655
> Add a delegating file part handler for Java

- documentation/manual/gettingStarted/IDE.md
Supercedes https://github.com/playframework/playframework/pull/6267 (which was created as playframework/fix-5270, and not wsargent/fix-5270)
Fixes #5270
Updates documentation to reflect fix made in #6009
> [doc] fix play.editor configuration documentation

- documentation/manual/working/commonGuide/production/ProductionConfiguration.md
Fixes #xxxx
Had an issue that seemed silly, so I updated the docs with it explicitly. Basically you can't name your Env variables the same as the variables
> [doc]Added advice for production env variables

- framework/project/Docs.scala
- framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala
- framework/src/play-java/src/main/java/play/libs/Classpath.java
- framework/src/play-jdbc/src/main/scala/play/api/db/DB.scala
- framework/src/play-logback/src/main/scala/play/api/Logger$ColoredLevel.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/SynchronousMappedStreams.scala
- framework/src/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala
- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
Fixes #https://github.com/playframework/playframework/issues/4995
All the javadoc warnings are fixed, and -Xdoclint:none is removed from the javadoc.
> Fix all javadoc warnings, remove -Xdoclint:none

- framework/src/play-json/src/main/scala/play/api/libs/json/jackson/JacksonJson.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
This places limits on the minimum and maximum values that can are written out using `BigDecimal#toPlainString` in play-json. There are really two issues when dealing with large BigDecimal values that this attempts to fix:
1. Normally you do not want to print out every digit of a large `BigDecimal` value if most of the digits are leading or trailing zeroes. I understand the desire to avoid scientific notation for shorter numbers (so we still support that), but JSON is a data format, so we should strive for compactness in general.
2. In an extreme case, trying to use `toPlainString` on a very large number, we will get an `OutOfMemoryError`:
```
scala> BigDecimal("1e100000000").bigDecimal.toPlainString
java.lang.OutOfMemoryError: Java heap space
at …
```
> Avoid OutOfMemoryError when writing JSON BigDecimals

- framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala
- framework/src/play/src/main/scala/play/api/http/HttpFilters.scala
- framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
Fixes #6384.
It should be possible to use Play's built-in components with Guice's `requireAtInjectOnConstructors` option.
(needs backport to 2.5.x)
> Add @Inject annotation to a few constructors

- documentation/manual/working/commonGuide/configuration/SettingsLogger.md
- framework/src/play-logback/src/main/resources/logback-play-default.xml
- framework/src/play-logback/src/main/resources/logback-play-dev.xml
Fixes #6361 
Because the default log file appenders can not be easily removed via user config, they are removed from the default configs.  If the user needs file logging they can add it in their own `logback.xml` config.
> remove file log appenders from default configs - fixes #6361

- documentation/manual/working/scalaGuide/advanced/routing/ScalaSirdRouter.md
- documentation/manual/working/scalaGuide/advanced/routing/code/ApiRouter.scala
- documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
Fixes https://github.com/playframework/playframework/issues/4586
Describes SIRD routing in context of a conf/routes file and by extending SimpleRouter.
> [doc] Add SIRD routing documentation

- templates/play-scala/build.sbt
Tests using scalatest so there is no need for the scalaz repository
> removed scalaz repository in play-scala template

- framework/project/Dependencies.scala
after playing with scala 2.12.0-m5 i found out that play has a really unnecessary dependency.
I'm not sure but I guess we could drop that one even for 2.5.x I guess that wouldn't even make a mima incompatibility. and I guess for 99% of the people it would not break anything.
Tests would run on 2.5.x, just fine.
> removed scala-stm

- framework/project/Dependencies.scala
Actually I'm not sure about this one, I searched the history and only found that:
https://github.com/playframework/playframework/commit/0981b80ed1ab019f966740572e52f39c516352c0
Which just changes javax.servlet to tomcat-servlet-api. But I guess it's not needed at least not in the runtime (maybe it's used in the tests but I couldn't track it, if it makes problems we could at least readd it)
> removed the tomcat-servlet-api

- documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
- documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
- framework/src/play-ws/src/main/scala/play/api/test/WSTestClient.scala
Removes the static WS methods in documentation.  This is related to https://github.com/playframework/playframework/pull/6402 but can be backported to 2.5.x easily.
There is a change in the method signature of WsTestClient, where if you're passing in a custom client you have to pass it in as a function parameter now.  I think that this should be okay as it's very unlikely to be used, and can be done as (_, _) => client inline so it's a very light code change overall.  (This was prompted by the problem that the WsTestClient doesn't reliably close off the actorsystem and the client after running, other approaches welcome.)
> Fix documentation using static WS methods

- framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
This fix makes sure that Play never sends Content-Length header field for a 204 response.
As described in [RFC7230 section-3.3.2](https://tools.ietf.org/html/rfc7230#section-3.3.2), sending a Content-Length header field is not allowed in any response with a status code of 1xx (Informational) or 204 (No Content). This requirement was not forced in Play, which means a user can intentionally set a Content-Length header. To follow the RFC section, we need to make sure that we don't send the header field.
~~With regard to a Content-Length header field in a 304 response, a server May send it as mentioned in RFC7230 section-3.3.2. Thus it'd be better for us to allow users to set the field if they like.~~
With regard to a Content-Length header field in a 304 response, we don't allow users to do …
> Disallow users to send a message-body and Content-Length header field for 1xx, 204 and 304 responses

- framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
Backport of https://github.com/playframework/playframework/pull/6261
Please have a look at https://github.com/playframework/playframework/pull/6261
> [Backport 2.5.x] Disallow users to send a message-body and Content-Length header field for 1xx, 204 and 304 responses (#6261)

- framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
actually play tried to parse connection reset or broken pipe, however under
different locales than en_* it will actually give a "localized message (broken pipe)" this can't be parsed by specs2. However SocketException already is known for the broken pipe so we can just omit the message parsing
> tests won't run under linux if locale is different than en_*

- framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala
- framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala
```scala
import play.api.libs.json.Json
case class Foo[T](value: T)
object Foo {
val writes = Json.writes[Foo[Int]]
}
```
yields the compilation error
```
error: No apply function found matching unapply parameters
val writes = Json.writes[Foo[Int]]
^
```
```Json.reads``` has the same problem.
> JSON macros don't work for generic classes

- documentation/manual/releases/release25/migration25/Migration25.md
Adds line breaks in source examples on the [Play 2.5 Migration Guide](https://www.playframework.com/documentation/2.5.x/Migration25) to reduce horizontal scrolling.
When updating my project from 2.4 to 2.5 and switching to dependency injection the other day, I was initially faced with a wall of red due simply to the fact I hadn't scrolled the controller example far enough to the right to spot that there was still an `extends Controller` at the end. I did figure it out quite quickly but it seemed like something easy to remedy.
(CLA signed)
> [doc] Add line breaks in examples to reduce horizontal scrolling

- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
- framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
- framework/src/play-server/src/main/scala/play/core/server/Server.scala
- framework/src/play/src/main/java/play/ApplicationLoader.java
- framework/src/play/src/main/scala/play/api/Application.scala
- framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
- framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
- framework/src/play/src/test/scala/play/api/inject/DefaultApplicationLifecycleSpec.scala
Fixes #6433
It actually ensure's that Shutdown Hooks will be only called **once** and that they will **always** be called in dev mode. This ensure's that nothing can go stale.
Actually without breaking backwards compatibility I didn't see any other way of having a good way to do it.
So this isn't back portable since it will break mima and definitly add some problems when people **didn't** used BuiltInComponentsWithContext.
Another problem still happens or at least I don't if it will, it still never garbage collects the ReloadableClassLoader which I can't actually fix without a profiler like Yourkit (VisualVM is too dumb), I guess something still holds a reference to something but since nothing is running there it isn't a big deal.
> shutdown hooks will now be called correctly in dev mode

- framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Currently there's no tests to check if the returned body of 1xx, 204 and 304 responses is empty, which is required by RFC7230. To make sure that no entity is sent to a client, we can add unit tests of `ServerResultUtils#validateResult`[1] that takes responsibility for cancelling a body if necessary.
PR(#6261)[2] was merged to meet the requirement of RFC7230. `BasicHttpClient` is used for the integration tests to check if an empty body is returned for 1xx, 204 and 304 responses. These integration tests, however, don't guarantee that those responses return an empty body as our `BasicHttpClient` just returns an empty body instead of sending an actual body.[3]
PR(#6261)[2]
PR Comment[4]
[1] https://github.com/playframework/playframework/blob/2.5.4/framework/src/play-server/src/main/scala/play/ …
> Add tests of ServerResultUtils#validateResult to make sure an empty body is sent for 1xx, 204 and 304 responses

- documentation/manual/releases/release25/migration25/JavaMigration25.md
- documentation/manual/working/javaGuide/main/async/JavaAsync.md
Fixes https://github.com/playframework/playframework/issues/6451.
There is actually a note about `HttpExecutionContext`, but it's under ThreadPools(!):
https://www.playframework.com/documentation/2.5.x/ThreadPools#Java-thread-locals
So added it to the migration notes and JavaAsync.md.
> Add note about HTTP execution context

- framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Backport https://github.com/playframework/playframework/pull/6436
> [Backport 2.5.x] Add tests of ServerResultUtils#validateResult to make sure an empty body is sent for 1xx, 204 and 304 responses (#6436)

- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-java-ws/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Fixes the hardcoding of OAuth SignatureCalculator reported in https://groups.google.com/d/topic/play-framework/onkvUUMrg8w/discussion
Leverages the AHC 2.0 API so an AHC SignatureCalculator is passed through if the type matches.  This is only applicable in Java -- the Scala API works fine.
Added tests for both Java and Scala just to double check.
> Ensure that custom signature calculator works in Java

- framework/src/play-json/src/main/scala/play/api/libs/json/JsResult.scala
- framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
This is only about code style:
* in `Reads.scala`, all methods have a return type but one
* in `JsResults.scala`, instead of using `[A, B]` and `[A, X]` as generic names, only use `[A, B]`
> Minor: Add missing return type and uniformize the naming of generic type

- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
This prevents the default body parser assuming the body is empty and ignoring it.
Fixes #6440.
> Set content length in test helper when invoking action with an explicit body.

- documentation/manual/gettingStarted/NewApplication.md
- documentation/manual/releases/release26/migration26/Migration26.md
- documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaCompileTimeDependencyInjection.md
- framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/build.sbt
- framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt
- framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/build.sbt
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/build.sbt
- templates/play-java-intro/build.sbt
- templates/play-java/build.sbt
- templates/play-scala-intro/build.sbt
- templates/play-scala/build.sbt
After discussing with Will, I think it makes more sense to name the key `PlayKeys.guice` instead of  `PlayKeys.guiceSupport`. I also added an explanation about it to the migration guide.
> Change guiceSupport to guice and add to migration guide

- framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
- framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala
Fixes #6466
Fixes the stop hooks, again.
Actually due to the wrong override it would've registered the `DefaultApplicationLifecycle` to `ApplicationLifecycle`, however that would happen anyway (https://github.com/playframework/playframework/blob/master/framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala#L45) as you can see we would now have a new `DefaultApplicationLifecycle` bind to self and one bind to `ApplicationLifecycle` and this is pretty pretty bad. The override should've targeted `DefaultApplicationLifecycle`.
This is even worse than before since stop hooks would've only be called in dev mode.
> stop hooks won't be called when Play.stop(app) was called

- framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
- framework/src/play/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala
> [Backport 2.5.x] stop hooks won't be called when Play.stop(app) was called (#6469)

- framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-java-ws/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
- framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
- framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Fixes #6467
Set usePreemptiveAuth option to false when used with Digest auth
See comment https://github.com/AsyncHttpClient/async-http-client/issues/792#issuecomment-69026231
https://github.com/playframework/playframework/issues/6467
> Fix PR for WS requests returning 401 with Digest auth (#6467)

- documentation/manual/working/commonGuide/production/cloud/Deploying-CleverCloud.md
If play.json is used instead of sbt.json the application is detected as a Play 1.x app.
> Fix config file name in Clever Cloud deployment docs
