framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
There are three changes in this PR. See commit messages for more details.
=> Fix more Akka HTTP integration tests

documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FunctionalTest.java, framework/src/play-specs2/src/test/scala/play/api/test/FakesSpec.scala, framework/src/play-test/src/main/scala/play/api/test/Fakes.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, templates/play-scala/test/ApplicationSpec.scala
See [this message](https://groups.google.com/d/msg/play-framework-dev/9IZOhzQ8e9Y/rgR5_L0c79IJ) for details about the problem to solve.
=> Don’t use global to route requests in test helpers

documentation/manual/detailedTopics/production/ProductionHeroku.md
Includes the sbt-heroku plugin. Also added some update links for further reading.
=> Updated Heroku documentation 

framework/project/plugins.sbt
@muuki88 does this seem like a good idea to you?
=> Upgrade SBT native packager to 0.8.0

framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHttpServerSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingWSSpec.scala
Give a couple of tests more time and skip one entire test. Hopefully this will help stablise CI.
=> Fix CI failures

framework/project/Dependencies.scala
Backport of https://github.com/playframework/playframework/pull/3802
=> Updated Javassist to 3.19.0-GA

documentation/manual/detailedTopics/configuration/SecurityHeaders.md
Switched xssProtection with contentTypeOptions.
=> [doc] Fix the security filters list so the keys match

framework/project/Build.scala, framework/project/Dependencies.scala, framework/runtests, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Protocol.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Serializers.scala, framework/src/fork-run/src/main/scala/play/forkrun/ForkRun.scala, framework/src/fork-run/src/main/scala/play/forkrun/Logger.scala, framework/src/fork-run/src/main/scala/play/forkrun/SbtClient.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkProcess.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/Global.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/assets/main.less, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/controllers/Application.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/build.sbt, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.2, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.3, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/application.conf.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/main.less.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/some.css.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/conf/routes, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/Build.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/build.properties, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/plugins.sbt, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/public/css/some.css, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/test, framework/src/sbt-plugin/src/main/scala/play/PlayReload.scala
Add forked development-mode run for using with sbt server.
=> Add forked dev-mode run (2.3.x)

framework/project/Build.scala, framework/project/Dependencies.scala, framework/runtests, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Protocol.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Serializers.scala, framework/src/fork-run/src/main/scala/play/forkrun/ForkRun.scala, framework/src/fork-run/src/main/scala/play/forkrun/Logger.scala, framework/src/fork-run/src/main/scala/play/forkrun/SbtClient.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkProcess.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/Global.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/assets/main.less, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/controllers/Application.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/build.sbt, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.2, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/Application.scala.3, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/application.conf.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/main.less.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/changes/some.css.1, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/conf/routes, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/Build.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/build.properties, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/plugins.sbt, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/public/css/some.css, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/test, framework/src/sbt-plugin/src/main/scala/PlayReload.scala
Forward port of #3829.
Add forked development-mode run for using with sbt server.
=> Add forked dev-mode run

documentation/manual/detailedTopics/production/cloud/ProductionHeroku.md
Updated Heroku documentation to include sbt-heroku plugin. Also added some updated links for further reading.
These changes are already in the 2.3.x branch, but probably need to be in master.
=> Updated Heroku documentation in master

documentation/manual/detailedTopics/production/ProductionHeroku.md
Should I also merge this new documentation into the master branch?
=> Fixed a typo and formatting issue in the Heroku documentation.

documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
Input link was missing a trailing $
=> Fix the bad link to form input

documentation/manual/releases/Migration24.md
`your Scala actions to to be classes` -> `your Scala actions not to be classes`
=> Small typo

documentation/manual/ModuleDirectory.md
=> Moved PlayDok module

framework/project/Dependencies.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Protocol.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Serializers.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala
* Converted to pickling serlialization
=> Port to sbt-rc 1.0-M1

framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala, framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala
Hi
What do you guys think, Is this fix Ok? Im a bit unsure about matching on the Nothing, but it seems to work.
=> fix #3858: CacheApi always returns None when type not provided.

framework/src/play/src/main/scala/play/api/Application.scala
This method is very useful for people who are migrating from static singleton values to DI values, but who can't do it all in one go. It allows users to keep most of the performance of static values but it is compatible with DI.
=> Make Application.instanceCache method public

framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Enumerator.scala
A structural type was leaking on `onDoneEnumerating` due to lack of explicit type.
Which I added, with as well some `private` annotation to be defensive with regards to such issues.
=> Prevent leaking of structural types in `Enumerator`.

documentation/manual/detailedTopics/production/ProductionDist.md
Fixes #3873.
Updated the docs to instruct users to use sbt-assembly 0.12.0, exclude
commons-logging, and fix the merge conflict with ServerWithStop.
=> Update docs for sbt-assembly with 2.3.x

framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
The `handleFilePart` helper and `FileInfo` case class from the multipart parser should not be private, as they are very useful for using the multipart parsing API.  They should be made public, and scaladoc.  Documentation should also be added to the Scala file upload docs on how to use them.
=> Multipart.handleFilePart should not be private

documentation/manual/detailedTopics/configuration/ThreadPools.md, documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
Added some details about Akka thread pools and a little fix.
=> Thread pools documentation improvement 

framework/src/play-json/src/test/scala/play/api/libs/json/JsObjectSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsResultSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
=> Add test for Functor[JsResult]

documentation/manual/detailedTopics/configuration/ThreadPools.md
First one was not really clear...
=> ThreadPools Documentation : better nb-threads formula

framework/project/Build.scala, framework/project/Dependencies.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Protocol.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Serializers.scala, framework/src/fork-run/src/main/scala/play/forkrun/SbtClient.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkProcess.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/controllers/Application.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/Build.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/test
=> Update to sbt-remote-control 1.0-M4

documentation/manual/javaGuide/main/upload/JavaFileUpload.md
Solves compilation error: "play.PlayExceptions$CompilationException: Compilation error[not found: value form]"
=> Use @helper.form instead of @form

framework/project/Dependencies.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Serializers.scala, framework/src/fork-run-protocol/src/test/scala/play/forkrun/protocol/SerializersSpec.scala
=> Updated to latest sbt-rc (0.3.1) and sbt-core-next (0.1.1)

framework/src/fork-run/src/main/scala/play/forkrun/ForkRun.scala, framework/src/fork-run/src/main/scala/play/forkrun/SbtClient.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkProcess.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala
* Should shutdown resources more cleanly
* Shuts down if there is an unrecoverable connection error
=> A bit more orderly shutdown of the forked process

framework/project/Build.scala, framework/project/Dependencies.scala, framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Serializers.scala, framework/src/fork-run-protocol/src/test/scala/play/forkrun/protocol/SerializersSpec.scala, framework/src/fork-run/src/main/scala/play/forkrun/ForkRun.scala, framework/src/fork-run/src/main/scala/play/forkrun/SbtClient.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkProcess.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/app/controllers/Application.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/Build.scala, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/test
Forward port changes from 2.3.x branch:
- update to latest dependencies
- update serialization to picklers
- improve fork run shutdown
- make fork run scripted test more robust
Based on 2.3.x commits: 5641ace, 0bd99a4, 268c929, 33ebfcc, a969fda, 88fd6d2, 41c9c31, 4908645, 1f9aed9
=> Update fork run to latest sbt server

documentation/manual/working/scalaGuide/advanced/http/code/FiltersRouting.scala, documentation/manual/working/scalaGuide/advanced/http/code/ScalaHttpFilters.scala
This is a small cleanup of the sample code for the filters.  It just
removes some unneeded parentheses and fixes indentation.  It makes the
code look a little better and the document a little easier to follow.
=> Small cleanup of sample code for Scala filters.

framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
Since #3764 the JsonSpec test has been failing in the New Zealand timezone. This fixes the test by handling daylight savings properly.
=> Fix JsonSpec for New Zealand timezone

framework/src/play/src/main/java/play/mvc/Security.java, framework/src/play/src/test/java/play/mvc/SecurityTest.java
Related to issue [#3603](https://github.com/playframework/playframework/issues/3603) and is a rebased version of pull request [#3721](https://github.com/playframework/playframework/pull/3721).
=> AuthenticatedAction to support async

framework/src/fork-run-protocol/src/main/scala/play/forkrun/protocol/Protocol.scala, framework/src/fork-run-protocol/src/test/scala/play/forkrun/protocol/SerializersSpec.scala, framework/src/fork-run/src/main/scala/play/forkrun/ForkRun.scala, framework/src/play-server/src/main/scala/play/core/server/ServerStart.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/run-support/src/test/scala/play/runsupport/FilterArgsSpec.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-plugin/src/main/scala/PlayImport.scala, framework/src/sbt-plugin/src/main/scala/PlayRun.scala, framework/src/sbt-plugin/src/main/scala/PlaySettings.scala
=> Support http.address property in dev mode run

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play/src/main/scala/play/core/system/ApplicationProvider.scala
=> Avoid full reload of application on dev mode run exit

documentation/manual/hacking/ThirdPartyTools.md
This is a micro contribution that fixes the image link in the documentation.
=> Fixed image reference.

templates/play-java/tutorial/index.html, templates/play-scala/tutorial/index.html
=> Update tutorials to state Run instead of Start

framework/project/Dependencies.scala, framework/src/play-json/src/main/java/play/libs/Json.java, framework/src/play-json/src/test/scala/play/libs/JavaJsonSpec.scala, framework/src/play-json/src/test/scala/play/libs/JavaPOJO.java
Already added the jar in another commit, but forgot to register the module
=> Add support for Java 8 datatypes in JSON serialization/deserialization

documentation/manual/javaGuide/main/i18n/JavaI18N.md
Hi, I added documentation for Controller.changeLang() method.
=> Adding changeLang documentation. Fixes #1625

documentation/manual/gettingStarted/IDE.md
* import statement not needed as plugins keys get wildcard import
=> Fixed documentation of EclipsePlugin

framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala
It's much cleaner to use the built-in Eclipse method. addSourceDirectory doesn't check to see if the directory is present which resulted in users complaining about duplicate directories over at sbteclipse. And this is also more correct because it handles Twirl files that live in your test directory.
However, there is one weird thing about the solution I'm proposing here. The previous code was only adding:
<classpathentry kind="src" path="target/scala-2.10/twirl/main"/>
This new code is adding:
<classpathentry kind="src" path="target/scala-2.10/twirl/main"/>
<classpathentry kind="src" path="target/scala-2.10/twirl/test"/>
I'm not sure why there's a `target/scala-2.10/twirl/test` directory being created since there's no content in it. It'd be nice if whatever was creating this directory …
=> Better way of adding managed sources to Eclipse classpath

framework/src/sbt-plugin/src/main/scala/PlayEclipse.scala
As playframework 2.3.x already uses Twirl, the generated source code should be added to eclipse source classpath. 
The fix is already merge in master as #3661 and this is just a backport for the current 2.3.x branch.
=> Backport #3661: Add twirl sources to eclipse classpath.

framework/project/Dependencies.scala
[HikariCP Changelog](https://github.com/brettwooldridge/HikariCP/blob/2.3.x/CHANGES) show what have changed between version 2.3.3 and 2.3.5. This is a very simple minor update.
=> Upgrade HikariCP version to 2.3.5

documentation/manual/about/PlayUserGroups.md
I added links for my group. :)
=> add links for  Korea Play! User group

framework/src/play-integration-test/src/test/resources/application.conf, framework/src/play-integration-test/src/test/resources/logback.xml, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/main/scala/play/utils/Resources.scala
This is instead of 200 or 500 (depending on where the directory was found).
Fixes #3459.
=> Assets controller returns 404 for directories

documentation/manual/detailedTopics/configuration/ws/LooseSSL.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, framework/src/play-ws/src/main/resources/reference.conf, framework/src/play-ws/src/main/scala/play/api/libs/ws/Config.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingConfig.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Config.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/WSConfigParserSpec.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/SSLConfigParserSpec.scala
Move acceptAnyCertificate under the "loose" options where it belongs.
=> Move acceptAnyCertificate

framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonValidSpec.scala
=> Fix Reads validation for all integer types

documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md
Thanks to @megazord for catching my error
=> Fix copy/paste error in docs

documentation/manual/detailedTopics/build/AggregatingReverseRouters.md, documentation/manual/detailedTopics/build/Build.md, documentation/manual/detailedTopics/build/code/aggregate.sbt, documentation/manual/detailedTopics/build/code/build.sbt, documentation/manual/detailedTopics/build/index.toc, documentation/project/Build.scala, framework/runtests, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala, framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesCompilerSpec.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/a/app/controllers/a/A.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/a/conf/a.routes, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/b/app/controllers/b/B.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/b/conf/b.routes, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/c/app/controllers/c/C.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/c/conf/c.routes, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/conf/routes, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/nonplay/src/main/scala/nonplay.NonPlay.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/test, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/test, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/test, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/test, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/build.sbt
Fixes #1390.
* Implemented reverse router aggregation
* Replaced routesFiles task with sources in routes task
* Added scripted test for testing router aggregation
* Added support for compiling/including .sbt code snippets in the documentation
=> Reverse router aggregation

documentation/manual/javaGuide/main/i18n/JavaI18N.md
Hi, I added documentation for changeLang method.
=> Adding changeLang documentation.

documentation/manual/javaGuide/main/i18n/JavaI18N.md
Hi, I added documentation for changeLang method.
=> Adding changeLang documentation. 2.3.x

framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Reference: https://github.com/typesafehub/config/issues/288
Issue:
- Throwable implements Serializable, but the instantiated `PayException.ExceptionSource` held a reference to a non-serializable `ConfigOrigin`, making it non-serialisable
- Non-serialisable exceptions break ScalaTest ...
Changes:
- Add a regression test
- Implement the fix
=> Fix non-serialisability of Play's configuration exceptions

framework/project/Dependencies.scala
https://github.com/FasterXML/jackson-core/releases/tag/jackson-core-2.5.2
=> Upgrade jackson

framework/project/Dependencies.scala
=> update AHC to 1.9.16

documentation/manual/detailedTopics/production/ProductionDist.md, framework/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
I will release `RC2` today and this is the upgraded documentation.
=> Updating documentation for RC2

documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/javaGuide/advanced/dependencyinjection/code/injected.sbt, documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide.advanced.di.routes, documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/controllers/Application.java, documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/playlib/HelloModule.java, documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaCompileTimeDependencyInjection.md, documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaDependencyInjection.md, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/RuntimeDependencyInjection.scala, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/injected.sbt, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/scalaguide.advanced.dependencyinjection.injected.routes, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/scalaguide.advanced.dependencyinjection.routes, documentation/project/Build.scala
[saw someone asking about this on the mailing list](https://groups.google.com/forum/?fromgroups=#!topic/play-framework/z2qY5mJdg3U) and they were confused when we pointed them to the scala docs since they are writing in java
http://www.playframework.com/documentation/2.2.x/ScalaDependencyInjection
=> dependency injection docs need to describe interaction with routes generator

framework/src/play/src/main/scala/play/api/mvc/Http.scala
Make some of the cookie decoding operations a bit faster.
=> Optimize common cookie decoding operation

framework/project/Dependencies.scala
=> update AHC to 1.9.17

documentation/manual/ModuleDirectory.md
Fixed Minor formatting and grammatical errors.
=> Minor fixes in ModuleDirectory.md

framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Enumerator.scala
=> Enumerator Fix

framework/src/play/src/main/java/play/mvc/Http.java
=> Added JavaDoc for http request in Java.

framework/src/play/src/main/scala/play/core/utils/CaseInsensitiveOrdered.scala
See #4161 
Also move to the proper directory.
=> Make CaseInsensitiveOrdered private[play]

framework/project/Dependencies.scala
Keeping dependencies updated to new upcoming RC.
=> Upgrade AHC to version 1.9.18

framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala
Opening this so we can continue discussion from #3865.
Currently my proposed solution is to just use `mutable.LinkedHashMap` and make sure `value` always returns an immutable map.
=> Fix performance issues creating JsObject

documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md, framework/project/Dependencies.scala
Also, correct documentation to avoid broken links.
=> Upgrade specs2 to version 3.4

documentation/manual/gettingStarted/NewApplication.md, documentation/manual/hacking/Translations.md, documentation/manual/releases/Migration24.md, documentation/project/build.properties, framework/project/Build.scala, framework/project/Dependencies.scala, framework/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/project/build.properties, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/project/build.properties, templates/build.sbt, templates/project/build.properties
* Upgraded to Play enhancer 1.1.0
* Organised migration guide so that all build changes are grouped together and appear first in the guide.
=> Upgraded to sbt 0.13.8

documentation/manual/javaGuide/main/http/JavaActionsComposition.md, documentation/manual/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java
Nearly scratched my head off when read the old version, I think my modification made it easier to understand, any suggestions?
=> Refine action composition java guide

documentation/manual/working/javaGuide/main/tests/JavaFunctionalTest.md, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/BrowserFunctionalTest.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FakeApplicationTest.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FunctionalTest.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ServerFunctionalTest.java, documentation/manual/working/javaGuide/main/tests/code/tests/guice/JavaGuiceApplicationBuilderTest.java, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md
=> Better documentation for functional tests in Java

framework/src/play/src/main/java/play/mvc/Results.java, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
I will add the case HTTP status return 402. 
Please check it.
=> Add 402 status result.

framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Added clean commands so that incremental compilation is reset between each group of tests.
=> Made dev mode tests more stable

documentation/manual/gettingStarted/Installing.md, documentation/manual/gettingStarted/Tutorials.md, documentation/manual/hacking/BuildingFromSource.md, documentation/manual/hacking/index.toc
1. Correct link to Activator download
2. Better organization and description of tutorials list
3. Change order of pages for Hacking section
4. Small format corrections
This corrects some of the commends mades at PR #4231.
=> Minor documentation corrections

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala, framework/src/play/src/main/scala/play/api/http/Writeable.scala, framework/src/play/src/main/scala/play/api/libs/Jsonp.scala, framework/src/play/src/main/scala/play/api/mvc/Render.scala, framework/src/play/src/main/scala/play/core/j/JavaResults.scala
=> More trampolining

framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
Just small enhancements.
The exception was thrown in `withTransaction` already but not in `withTransactionAsync` yet.
=> Use lambda + throw exception when EntityManager is missing

documentation/manual/detailedTopics/production/Production.md, documentation/manual/gettingStarted/Anatomy.md, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayLayoutPlugin.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
Fixes #4242
Also moved configuration of the dist folder to the PlayLayoutPlugin, so that if disabled, it will revert to the standard `src/universal`.
=> Documented the dist folder

documentation/manual/ModuleDirectory.md
Added information about Thymeleaf integration module
=> Add Thymeleaf integration module

framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
=> Add head/headOption & tail/tailOption on JsArray

documentation/manual/working/javaGuide/main/akka/JavaAkka.md, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredActorProtocol.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredChildActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredChildActorProtocol.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ParentActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ParentActorProtocol.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/factorymodules/MyModule.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/inject/Application.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/modules/MyModule.java, documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md, documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala, framework/project/Dependencies.scala, framework/src/play/src/main/java/play/inject/DelegateInjector.java, framework/src/play/src/main/java/play/inject/Injector.java, framework/src/play/src/main/java/play/libs/Akka.java, framework/src/play/src/main/java/play/libs/akka/AkkaGuiceSupport.java, framework/src/play/src/main/java/play/libs/akka/BinderAccessor.java, framework/src/play/src/main/java/play/libs/akka/InjectedActorSupport.java, framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
* Provided convenience methods for instantiating actors and binding ActorRefs for those actors
* Provided convenience methods for working with Guice assisted inject factory methods to DI actors that depend on state that isn't from the container as well
* Documented all of the above
* Bound an ExecutionContext in DI
=> Actor DI support

documentation/manual/detailedTopics/evolutions/Evolutions.md, documentation/manual/releases/Migration24.md, framework/src/play-jdbc/src/main/resources/reference.conf, framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala, framework/src/play-jdbc/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala, framework/src/play/src/main/scala/play/api/Configuration.scala
* Removed modules from configuration keys
* Used new PlayConfig APIs
=> Updated evolutions config

framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
Adds the last method for arrays to `JsLookup`
=> Add last to JsLookup

templates/play-scala-intro/app/views/main.scala.html
Hi Play Team,
I've noticed that there is missing ">" sign on play-scala-intro activator html file.
=> fixed html closing tag

framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala, framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Also removes a duplication of databases url patterns and do some small code refactoring.
This fixes #3918.
=> Mysql support for migrations bigger than 64Kbs

framework/project/Dependencies.scala, framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
=> Upgrade HikariCP to version 2.3.7

framework/project/Dependencies.scala, framework/src/iteratees/src/test/scala/play/api/libs/iteratee/IterateeSpecification.scala, framework/src/iteratees/src/test/scala/play/api/libs/iteratee/IterateesSpec.scala, framework/src/iteratees/src/test/scala/play/api/libs/iteratee/RunQueueSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/BodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/mvc/HttpSpec.scala, framework/src/play-java-jdbc/src/test/scala/play/db/DBSpec.scala, framework/src/play-java/src/test/scala/play/data/FormSpec.scala, framework/src/play-jdbc/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala, framework/src/play-jdbc/src/test/scala/play/api/db/DriverRegistrationSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsResultSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingConfigSpec.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/debug/DebugConfigurationSpec.scala
Also have done some small code clean up.
=> Upgrade specs2 to version 3.5

documentation/manual/releases/Migration24.md
=> minor documentation fix for anorm sample queries

documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithScalaTest.md, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
=> Remove docs reference to getControllerInstance

framework/project/Build.scala
This will ensure that omnidoc compiles and includes the scaladocs for the Play twirl templates in the aggregated scaladocs for the project.
=> Ensure Twirl scala sources are included in the source jar

framework/project/Build.scala, framework/project/Publish.scala, framework/project/Release.scala, framework/project/plugins.sbt
* sbt plugin releases get published to bintray
* sbt plugin snapshots get published to sonatype snapshots
* Added sonatype plugin, and incorporated promote phase into release process
=> Publish sbt plugin to bintray

documentation/manual/detailedTopics/configuration/filters/GzipEncoding.md, documentation/manual/detailedTopics/configuration/filters/SecurityHeaders.md, documentation/manual/working/javaGuide/main/forms/JavaCsrf.md, documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
The [CSRF docs](https://www.playframework.com/documentation/2.4.x/JavaCsrf) say "Now add them to your Filters class". What is my Filters class? What configuration do I need to update to point to my filters class?
=> CSRF docs need to explain Filters setup

documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/eager/HelloModule.java, documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaDependencyInjection.md, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/RuntimeDependencyInjection.scala
This is the first part of my docs changes. The next part, which is still in progress, will give docs for the `GuiceApplicationLoader`.
=> Docs on DI lifecycle and bindings

framework/project/Dependencies.scala
=> Upgrade to Guice 4.0

documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md
The suggestion came from @jroper, and a comment in #4261 proves its useful
for users.
=> Added a note in the doc about correct usage of Spring DI with Play

documentation/manual/working/javaGuide/main/global/JavaGlobal.md
=> Corrects docs about how to use Java Global

documentation/manual/javaGuide/main/tests/JavaTest.md
=> Update mockito repository URL

documentation/manual/working/javaGuide/advanced/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/CustomApplicationLoader.java, documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaDependencyInjection.md, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/RuntimeDependencyInjection.scala, framework/src/play-java/src/main/java/play/inject/guice/GuiceApplicationLoader.java, framework/src/play-java/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java, framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/java/play/Configuration.java, framework/src/play/src/main/java/play/Environment.java, framework/src/play/src/main/java/play/libs/Scala.java, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala, framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala, framework/src/play/src/test/java/play/ConfigurationTest.java, templates/buildTemplate
This will mostly be useful because it makes it easier to override the GuiceApplicationLoader.
=> Support Java ApplicationLoaders; add GuiceApplicationLoader docs

framework/project/Dependencies.scala
1. Typetools to version 0.4.1
2. Webjars:jquery to version 2.1.4
3. Ehcache to version 2.6.11
4. Akka to version 2.3.10
=> Upgrade dependencies

documentation/manual/releases/Migration24.md
=> Add Java 8 to migration guide

framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala, framework/src/play/src/main/scala/play/api/GlobalSettings.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
=> Add Date header in NettyResultStreamer

framework/src/play-server/src/main/scala/play/core/server/ServerConfig.scala, framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
=> Fail if application.conf can't be found

framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala, framework/src/play/src/main/scala/play/api/Configuration.scala
=> Settings should be able to be of any type instead of just String

framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fix for https://github.com/playframework/playframework/issues/4323
Partially reverts https://github.com/playframework/playframework/commit/3c8c54109ab290bd7a0009f47fa1150ccb310986, which tried to refactor out some common functionality, but did so incorrectly
=> Fix JavaHelpers.invokeWithContextOpt

framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
=> Also send Date header with 500 when headers are invalid

framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Execution.scala
Optimize trampoline queue used for scheduling so we can avoid constructing an ArrayDeque in most cases.
I couldn't help indulging myself in this little bit of optimization work. :)
=> Trampoline micro-optimization

framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Execution.scala
I noticed a couple of mistakes in the comments.
=> Fix errors in trampoline comments

documentation/project/plugins.sbt, framework/project/Build.scala, framework/project/Dependencies.scala, framework/project/Release.scala, framework/project/plugins.sbt, framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/project/plugins.sbt, templates/build.sbt, templates/play-java-intro/project/plugins.sbt, templates/play-java/project/plugins.sbt, templates/play-scala-intro/project/plugins.sbt, templates/play-scala/project/plugins.sbt, templates/project/plugins.sbt
=> Removed reliance on Typesafe repo

documentation/manual/experimental/AkkaHttpServer.md, documentation/manual/experimental/ReactiveStreamsIntegration.md
=> Update docs for experimental modules

framework/project/Dependencies.scala
https://github.com/netty/netty/releases/tag/netty-3.10.2.Final
=> Upgraded netty

framework/project/Dependencies.scala
https://github.com/AsyncHttpClient/async-http-client/releases/tag/async-http-client-1.9.21
=> Upgrade async-http-client

framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala, framework/src/play/src/main/scala/play/api/mvc/Http.scala, framework/test/integrationtest/test/FunctionalSpec.scala
* Also update build to publish to bintray/maven central
=> Upgrade to Netty 3.9.8

framework/project/Dependencies.scala
This may not pass quite yet as I'm not sure the artifact is synced to central. If we re-run jenkins in an hour or so it should pass.
=> Upgrade Typesafe Config to 1.3.0 final

documentation/manual/working/scalaGuide/main/json/ScalaJsonInception.md
https://www.playframework.com/documentation/2.4.x/ScalaJsonInception
=> fix ScalaJsonInception.md. escape underscore

framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Ciphers.scala
Forward port of https://github.com/playframework/playframework/pull/4246
=> Deprecate rc4 in master

framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/mvc/Http.scala
=> Don’t store unstable paths in vals

documentation/manual/releases/Migration24.md
Add more information to the 2.4 migration docs, especially some extra information about how the format has changed.
See #4407.
cc @benmccann @tikurahul.
=> Expanded crypto migration docs

framework/src/play-integration-test/src/test/scala/play/it/bindings/GlobalSettingsSpec.scala, framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
See #4311.
Note: This doesn't fix #4311 because I couldn't reproduce the problem. I'm pushing it because I thought looking at the code would help with the discussion of that issue. It's fine to merge this PR, or we can wait until I learn how to reproduce #4311.
=> Add tests for GlobalSettings filters

documentation/manual/releases/Migration24.md
Accounts for recent change made by playframework/play-ebean#35
review by @jroper
=> Updated ebean migration doc

documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/hellotemplate.scala.html, framework/project/plugins.sbt
Fixes #4366, problems with ambiguous wildcard imports.
See https://github.com/playframework/twirl/pull/76.
=> Update Twirl to fix template import regression

documentation/manual/releases/Migration24.md
describe whats changed with the sbt-native-packager / debian package creation. 
tracked in bug report #4329
=> describe changes req. to create debian packages

framework/src/play-integration-test/src/test/scala/play/it/bindings/GlobalSettingsSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JAction.scala, framework/src/play/src/main/java/play/http/GlobalSettingsHttpRequestHandler.java
=> Ensure Java Global.onRequest gets invoked

framework/project/Dependencies.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala, framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesCompilerSpec.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/test, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/test
File names now have more meaning.  Also updated scripted tests to check for existence of new files.
=> Renamed generated routes files

framework/src/play-json/src/main/scala/play/api/libs/json/JsConstraints.scala
modified email regex pattern for 「.tokyo」domain.
thank you.
=> modified email reggae pattern for ".tokyo" domain

framework/src/play-json/src/main/scala/play/api/libs/json/package.scala
=> Update UserFormat example in json package doc

documentation/manual/working/javaGuide/advanced/dependencyinjection/code/javaguide/advanced/di/guice/CustomApplicationLoader.java, documentation/manual/working/javaGuide/main/tests/JavaFunctionalTest.md, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/InjectionTest.java, framework/src/play-java/src/main/java/play/inject/guice/GuiceApplicationLoader.java, framework/src/play-java/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java
Fix for https://github.com/playframework/playframework/issues/4466
=> Document how to inject a test

framework/project/Dependencies.scala
This introduces the ability to auto detect node.js.
=> Upgrade sbt-js-engine

documentation/manual/releases/Migration24.md
A few people have asked about this.
=> Add OptionReads changes to migration guide

documentation/manual/releases/Migration24.md
The addition is motivated by feedback received in the play-framework ML.
**To backport**
=> Reworded play-sbt package change in migration doc

documentation/manual/releases/Migration24.md, documentation/project/Build.scala
The addition is motivated by feedback received in the play-framework ML.
**To backport**
=> Mentioned play-slick in migration doc

documentation/manual/releases/Migration24.md
Fixes https://github.com/playframework/playframework/issues/4477
=> Add migration docs for requesthandler

framework/src/play/src/main/scala/play/api/mvc/Binders.scala, framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala
For context see: https://github.com/playframework/playframework/issues/4523
=> Fixes missing Char binding for PathBindable and QueryStringBindable

framework/project/Build.scala
No matter how hard we try, we can never get rid of these repos....  urgh...
=> Reinstate typesafe repos

framework/src/play/src/main/scala/play/api/Routes.scala
Backport of https://github.com/playframework/playframework/pull/4546
=> Fix deprecation messages for ROUTE_* constants

framework/src/play/src/main/scala/play/api/mvc/Http.scala, framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
=> Get effective host from absolute request URIs

documentation/manual/working/javaGuide/main/ws/JavaWS.md
=> Add WSRequest to JavaWS.md

framework/project/Dependencies.scala
Changelog: http://www.joda.org/joda-time/upgradeto280.html
=> Joda-Time upgrade

documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/InjectionTest.java
Just added missing application start in `@Before` method.
=> Missing application start.

framework/src/play/src/main/java/play/i18n/Langs.java, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
=> Fix i18n.langs comment

framework/src/play/src/main/java/play/i18n/Langs.java, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
=> [Backport] Fix i18n.langs comment

documentation/manual/hacking/ThirdPartyTools.md
=> Correct docs links

framework/project/Dependencies.scala
https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5.4
Should I backport?
=> Jackson upgrade

documentation/manual/releases/migration24/Migration24.md
Fixes https://github.com/playframework/playframework/issues/4654
=> Fixes acceptAnyCertificate in master

framework/src/play-json/src/main/scala/play/api/libs/json/JsValue.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsObjectSpec.scala
=> Fix regression in JsObject#deepMerge

framework/src/play-integration-test/src/test/resources/logback.xml, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/main/scala/play/utils/Resources.scala
Ensures Assets controller returns 404 for directories.
=> Backport of #3459 to Play 2.3.x

framework/project/Build.scala, framework/version.sbt
See https://docs.google.com/document/d/1OejviUX5TDlRVeKg1JD9L4qh2Tn21giItmyxRXCydN0/edit
=> Change master version to 2.5.0-SNAPSHOT

framework/src/play/src/main/java/play/mvc/Call.java, framework/src/play/src/main/scala/play/api/mvc/Http.scala, framework/src/play/src/main/scala/views/helper/form.scala.html, framework/src/play/src/test/java/play/mvc/CallTest.java
=> [Backport] Improvements to Call + support for fragments in form actions

framework/src/play/src/main/scala/play/api/controllers/Default.scala, framework/src/play/src/main/scala/play/api/controllers/ExternalAssets.scala
=> Make Default and ExternalAssets controllers injectable

framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java, framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/core/j/JavaAction.scala
=> Propogate changes to context through action composition

framework/src/play/src/main/scala/play/api/data/Forms.scala, framework/src/play/src/main/scala/play/api/data/format/Format.scala, framework/src/play/src/test/scala/play/api/data/FormSpec.scala, framework/src/play/src/test/scala/play/api/data/format/FormatSpec.scala
complements prior [accepted pull request](https://github.com/playframework/playframework/commit/e6cec6bc003fb3612f4337cf943da96a3f533c5a) that added Char binding to routes.
=> add Char binding to forms

framework/src/play/src/main/java/play/http/DefaultHttpErrorHandler.java, framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
=> [Backport] Add method to handle various 4xx client errors to DefaultHttpErrorHandler

framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
=> 413 responses now call HttpErrorHandler.onClientError

documentation/manual/gettingStarted/IDE.md
Updated info on how to run IntelliJ projects for IntelliJ 14.1.3 and Scala plugin 1.5.2
=> Update IDE.md - how to run IntelliJ projects

framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala
See https://github.com/playframework/playframework/issues/4719
=> Fixes #4719 - Content-type incorrectly parsed by play.api.test.ResultExtractors

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/AnyContentBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/DefaultBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/EmptyBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/FormBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/IgnoreBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/JsonBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/TextBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/XmlBodyParserSpec.scala, framework/src/play-java-ws/src/test/scala/play/libs/oauth/OAuthSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/RequestBodyHandler.scala, framework/src/play-specs2/src/test/scala/play/api/test/FakesSpec.scala, framework/src/play-test/src/main/scala/play/api/test/Fakes.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play-ws/src/test/scala/play/api/libs/oauth/OAuthRequestVerifier.scala, framework/src/play-ws/src/test/scala/play/api/libs/oauth/OAuthSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/mvc/Action.scala, framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala, framework/src/play/src/main/scala/play/api/mvc/Filters.scala, framework/src/play/src/main/scala/play/core/actions/HeadAction.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala, framework/src/play/src/test/scala/play/api/mvc/ContentTypesSpec.scala, framework/src/play/src/test/scala/play/core/test/Fakes.scala
Play should use ByteString for its request body handling.
=> Switch to ByteString for request body handling

documentation/project/Build.scala, framework/runtests, templates/build.sbt
I couldn't get `./build` to run locally, but hopefully it's just the flaky network I'm on. Jenkins can tell me if the upgrade works. :)
=> Upgrade to Scala 2.11.7

framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
=> Leave other set cookies alone when cleaning up flash

framework/project/Dependencies.scala
Changes: https://github.com/jboss-javassist/javassist/compare/rel_3_19_0_ga...rel_3_20_0_ga
JIRA: https://issues.jboss.org/browse/JASSIST/fixforversion/12326488/?selectedTab=com.atlassian.jira.jira-projects-plugin:version-summary-panel
=> Upgrade javassist

framework/project/Dependencies.scala
=> Upgrade joda time

framework/project/Dependencies.scala
=> [Backport] Upgrade joda time

documentation/manual/detailedTopics/production/cloud/ProductionHeroku.md
Current Postgres driver for 9.4.1
Non-deprecated evolutions setting
=> Update Heroku documentation

documentation/manual/releases/migration24/Migration24.md
Describe needed changes to get assets in subprojects to route correctly. See https://github.com/playframework/playframework/issues/4576
=> Add SubProject Assets section

framework/project/Dependencies.scala
Changes: https://github.com/netty/netty/compare/netty-3.10.3.Final...netty-3.10.4.Final
Also contains a fix from @jroper
=> Upgrade netty

framework/src/play/src/main/scala/play/api/libs/Files.scala
=> Clean up temp files on app shutdown

framework/src/play/src/main/scala/play/api/libs/Files.scala
=> [Backport] Clean up temp files on app shutdown

framework/src/play-streams/src/main/scala/play/api/libs/streams/impl/PromiseSubscriber.scala
State does not take type parameter
=> fix incorrect scaladoc

documentation/manual/detailedTopics/production/cloud/ProductionHeroku.md
General maintenance and updates.
=> Update Heroku deployment documentation for 2.4

framework/src/play-json/src/main/scala/play/api/libs/json/JsLookup.scala
=> Change JsLookupResult#getOrElse to call by name

framework/src/play-test/src/main/java/play/test/Helpers.java
=> Make `invokeWithContext` static in Helpers.java

framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala
comment is incorrect since https://github.com/playframework/playframework/commit/2f6e57b4b
=> fix ProdServerStart.createPidFile scaladoc

documentation/manual/working/javaGuide/main/i18n/JavaI18N.md, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java
See also #4886 and  #4888.
In the previous PR, I caused the horrible trouble.
I'm VERY sorry I have given many people such a lot of trouble.
=> Fix the usage of Messages.get().

framework/project/Dependencies.scala, framework/src/play-jdbc/src/main/resources/reference.conf, framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala, framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
Fix #4893 and also upgrade HikariCP to version 2.3.9
=> Map HikariCP connectionInitSql property

documentation/manual/working/scalaGuide/main/forms/code/scalaguide.forms.scalaforms.routes, documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/contact/form.scala.html, documentation/manual/working/scalaGuide/main/json/ScalaJsonTransformers.md
new template compiled with https://github.com/playframework/playframework/blob/2.4.x/documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
and tested by browser at https://github.com/moilioncircle/playframework-2.4.x-scala/blob/master/app/controllers/c4/S1ScalaForms.scala
=> fill  the original tempty template

documentation/manual/gettingStarted/PlayConsole.md, documentation/manual/gettingStarted/code/PlayConsole.scala
Following the recipe in https://github.com/playframework/playframework/issues/4593
=> Updating guide to starting an application in the console

framework/project/Dependencies.scala
https://github.com/netty/netty/releases/tag/netty-3.9.9.Final
Fix for #4432
=> Upgrade netty, fixes #4432

framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala
This fixes the issues reported by @mslinn in issue #4584.
=> Fix documentation issues in json Writers API

framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala, framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala
Surprisingly (at least to me), the `DefaultInstantReads` is not able to parse strings containing an all-zero seconds field:
```scala
> import play.api.libs.json._
> Reads.DefaultInstantReads.reads(JsString("2015-05-01T13:00:00+02:00"))
res3: play.api.libs.json.JsResult[java.time.Instant] = 
JsError(List((,
List(ValidationError(List(error.expected.date.isoformat),WrappedArray((ParseCaseSensitive(false)(Value(Year,4,10,EXCEEDS_PAD)'-'Value(MonthOfYear,2)'-'Value(DayOfMonth,2))'T'(Value(HourOfDay,2)':'Value(MinuteOfHour,2)[':'Value(SecondOfMinute,2)[Fraction(NanoOfSecond,0,9,DecimalPoint)]]))[Offset(+HH:MM:ss,'Z')['['ParseCaseSensitive(true)ZoneRegionId()']']]))))))
```
The reason is that LocalDateTime.toString returns the shortest format that outputs the full value of the time where the …
=> Issues with Play JSON java.time.Instant default Reads and Writes

framework/project/Dependencies.scala, framework/src/play-json/src/test/scala/play/libs/JavaJsonSpec.scala, framework/src/play-json/src/test/scala/play/libs/JavaPOJO.java
See the accumulated release notes below:
1. https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.5.5
2. https://github.com/FasterXML/jackson/wiki/Jackson-Release-2.6
Specifically, this could be important to us: 
1. https://github.com/FasterXML/jackson-databind/pull/852
=> Upgrade jackson to version 2.6.0

framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala, framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala
=> Backport #4872: JSON Reads for java.time.Instant

framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala
=> Disabled pending tests in `HeadActionSpec`.

documentation/manual/releases/Highlights25.md, documentation/manual/releases/Migration25.md, documentation/manual/releases/index.toc
As suggested by @richdougherty here: 
https://github.com/playframework/playframework/pull/4713#issuecomment-121767094
=> Add sql log statements feature to feature hightlights

framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala
See https://github.com/playframework/playframework/pull/4925
=> Remove dependency from core to Guice

framework/src/play/src/main/java/play/mvc/StatusHeader.java, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/test/java/play/mvc/ResultsTest.java, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
=> Always send Content-Disposition with filename in sendFile

framework/project/Dependencies.scala
=> Bumped akka-stream and akka-http to 1.0

documentation/manual/detailedTopics/production/Production.md, documentation/manual/detailedTopics/production/ProductionConfiguration.md, documentation/manual/detailedTopics/production/code/assembly.sbt
I accidentally deleted this pull request. So here is it again.
It took me some time figure out how to make my Play application work well in my environment, since not everything has been documented. So I added the parts I was missing.
=> Update deployment documentation

framework/bin/checkCodeStyle, framework/bin/compile211, framework/bin/test, framework/bin/testDocumentation, framework/bin/testSbtPlugins, framework/bin/testTemplates
This should remove most of the noise in the logs.
=> Adjust CI logging to warn

.travis.yml, framework/bin/codeChecks, framework/bin/compile211, framework/bin/test, framework/bin/testDocumentation, framework/bin/testSbtPlugins, framework/bin/testTemplates
Also adjusted logging so that only warnings are output
=> Enabled mima for 2.4.x travis builds

documentation/manual/hacking/Documentation.md
Hi all.
I think that It is wrong word.
If I am wrong. Please Let me know about what this words mean.
=> fix typs consoloditated to consolidated

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
=> Switched CSRFFilter to use Akka Streams

documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/Streams.scala, framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Fixes #4728 and #4729
Also updated remaining body parsers that were using iteratees to use Akka streams.
=> Rewrote multipart/form-data parser using Akka streams

framework/src/play-json/src/main/scala/play/api/libs/json/Reads.scala
[uuidReads](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.libs.json.Reads$@uuidReads:play.api.libs.json.Reads[java.util.UUID]) is not a subclass of [Reads](https://www.playframework.com/documentation/2.4.x/api/scala/index.html#play.api.libs.json.Reads), which is why it is not listed as a subclass at the top of the `Reads` ScalaDoc. However, even though it is implemented as a method, it probably deserves some mention, especially regarding usage since its usage differs from most of the other `Reads`.
=> uuidReads is buried

documentation/manual/detailedTopics/build/SBTSubProjects.md, documentation/manual/detailedTopics/build/code/detailedtopics.build.subprojects.assets.routes
add some note to explain how it works; externalize routes file code sample
=> Fix documentation of multi-projects assets path in routes

framework/src/play-java-jdbc/src/main/java/play/db/DB.java, framework/src/play-jdbc/src/main/scala/play/api/db/DB.scala
=> Deprecates the DB singletons

documentation/manual/working/javaGuide/code/MockJavaAction.scala, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaComet.java, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaCsrf.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, documentation/manual/working/javaGuide/main/http/JavaBodyParsers.md, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActions.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaContentNegotiation.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java, documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java, framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala, framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java, framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/inject/Binding.scala, framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
=> Documented Java body parsing

framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
Fixed warnings for file framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
This pull request is small step in resolving issue #4995
=> Fixed JavaDoc warnings

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
Replacing "that are likely destructives" with "that are likely destructive" in the comments that users see.
=> Just a small typo

documentation/manual/detailedTopics/build/SBTCookbook.md, documentation/manual/detailedTopics/build/code/cookbook.sbt, documentation/manual/detailedTopics/build/code/runhook.sbt, documentation/manual/hacking/BuildingFromSource.md
* Updated building from source which still had wording relevant to when Play 2.0-beta was released.
* Clarified some of the wording in Play run hooks documentation to make it clear that they are only run in dev mode.
* Fixed and extracted all sbt code snippets from SBTCookbook docs.
=> Some small doc changes

framework/src/play-integration-test/src/test/java/play/it/JavaServerIntegrationTest.java, framework/src/play-server/src/main/java/play/server/Server.java, framework/src/play-server/src/main/scala/play/core/server/Server.scala
=> Enables SSL port configuration for embedded java servers.

documentation/manual/detailedTopics/configuration/filters/CorsFilter.md
=> Update CORS filter document

framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala, framework/src/play-json/src/main/java/play/libs/Json.java
=> Use newDefaultMapper in ObjectMapperModule

documentation/manual/releases/migration24/Migration24.md
Add migration documentation for optional JsValues
=> Migration documentation fixes

documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClientTest.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWebServiceClients.java, framework/project/Dependencies.scala, framework/src/play-java-ws/src/main/java/play/libs/ws/WS.java, framework/src/play-java-ws/src/main/java/play/libs/ws/WSClient.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSClient.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSRequest.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ning/NingWSResponse.java, framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingWS.scala
Trying to keep master up to date with the latest AHC alpha release
so that we can catch early possible glitches, and it will be easier
to update to 2.0.0 final.
=> Bumped async-http-client version to 2.0.0-alpha14

framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Tests in the `ResultsSpec` class were run sequentially because each of the test was creating a temporary file with the *same* name. I've updated the tests so that a fresh name is used for each file created, and hence there is no longer a need to run the tests sequentially.
=> Refactoring ResultsSpec class so that tests can be run in parallel

documentation/manual/releases/Migration25.md
Migration doc for Play functional types and Option.
=> Migration doc for Play function types and Option

documentation/manual/working/scalaGuide/advanced/dependencyinjection/ScalaCompileTimeDependencyInjection.md, documentation/manual/working/scalaGuide/advanced/dependencyinjection/code/CompileTimeDependencyInjection.scala
same as https://github.com/playframework/playframework/pull/4532, but against master
=> configure logback with custom application loader

framework/src/play-java-jdbc/src/test/java/play/db/NamedDatabaseTest.java
This removes 5 / 52 usages of Play.current
=> Remove usage of Play.current in NamedDatabaseTest

documentation/manual/releases/migration24/Migration24.md
Added some things to json section. Closes #5196
=> Some minor clarifications in 2.4 migration guide

framework/src/play-java/src/main/java/play/inject/guice/GuiceApplicationBuilder.java
=> Support creating Java GuiceApplicationBuilder from scala builder

framework/src/play-json/src/main/scala/play/api/libs/json/JsConstraints.scala, framework/src/play-json/src/main/scala/play/api/libs/json/JsPath.scala, framework/src/play/src/main/scala/play/api/Configuration.scala
Fixing all the unclosed tags warnings on Scaladoc.
=> Fixing unclosed tags warnings on Scaladoc for #4996

documentation/manual/detailedTopics/configuration/ws/DefaultContext.md
Removes duplicate link pointing to Debugging SSL section
=> Removes duplicate links

framework/project/Dependencies.scala
Announcement: https://groups.google.com/forum/#!topic/hikari-cp/G78VkPvFw6I
=> Bumped HikariCP version to 2.4.2

framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala
Closed the previous pull request created by me for this because of some conflict and created new one.
=> Scala doc warnings fix

framework/src/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/README, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/conf/application.conf, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/test, framework/src/sbt-plugin/src/test/scala/play/sbt/ApplicationSecretGeneratorSpec.scala
Adding support for playUpdateSecret to work with nested key format.
=> updateSecret update nested keys fix #5131

framework/project/Build.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/test/scala/play/libs/FilesSpec.scala
Fixes #5230.
This is a backport of #4925 and #4943.
=> Backport TemporaryFileCreator fixes to 2.4.x

templates/play-scala/test/ApplicationSpec.scala
Improve code formatting in ApplicationSpec
=> Code formatting in ApplicationSpec

framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java, framework/src/play-java-jpa/src/test/java/play/db/jpa/JPATest.java
A different approach to solve the problem of nested JPA transactions than https://github.com/playframework/playframework/pull/3388.
This implementation should be safe and backwards compatible with the current behavior of withTransaction:
- it creates a new EntityManager and a new EntityTransaction for the nested block
- it completes or rollbacks the inner transaction when the inner block exits depending on exit condition
- it completes or rollbacks the outer transaction when the outer block exits depending on exit condition
The only difference is that now, if you call JPA.em() after a nested withTransaction block, you will get the correct EntityManager associated with the current block's transaction.
Internally, a stack is used to keep track of the EntityManager being used in the current …
=> Added nested JPA transactions support.

framework/project/Build.scala, framework/project/plugins.sbt, framework/src/play/src/main/java/play/mvc/Security.java
https://github.com/playframework/playframework/commit/c40ff08dbc53 is binary incompatible change
ref https://github.com/playframework/playframework/pull/4913
=> update sbt-mima-plugin 0.1.8. fix binary incompatible issue.

templates/play-java-intro/project/plugins.sbt, templates/play-java/project/plugins.sbt
Fixes #5283
Already fixed in master.
=> Rename SbtEbean to PlayEbean

framework/src/play/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
NOTE: Not tested, should be fine.
=> Fix not showing real cause of chunked responses exceptions

documentation/manual/detailedTopics/configuration/SettingsNetty.md, documentation/manual/detailedTopics/configuration/index.toc, documentation/manual/releases/Highlights25.md, framework/project/Dependencies.scala
* Update to netty `4.0.33` - [Changelog](http://netty.io/news/2015/11/04/4-0-33-Final.html)
* Add documentation about configuring netty 
* Add [native socket transport feature](https://github.com/playframework/playframework/pull/5273) in `2.5` highlights
=> Update to netty 4.0.33

framework/project/Dependencies.scala
Update netty-reactive-streams to 1.0.1 which includes netty 4.0.33.final and fixes #5331
=> Update netty-reactive-streams to 1.0.1

framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
Add a retry operation to the basic httpclient to stop the build failing.
=> Add retry operation.

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
Backport of https://github.com/playframework/playframework/pull/5347
=> Use CSRF config rather than the global one which is not available with compile time dependency injection

documentation/manual/gettingStarted/IDE.md
Update the [documentation section](https://playframework.com/documentation/2.4.x/IDE#ENSIME) about `ENSIME` with the newest version (`0.2.3`) of the plugin and correct the mentioned sbt command from `ensime generate` to `gen-ensime`.
-- 24pullrequests
[![](http://24pullrequests.com/assets/logo-8a77737f86fec8def19a1c9a605c9841dbd44e59f243ed3bf64bbdf3214d6fa1.png)](http://24pullrequests.com/)
=> Update ENSIME section in "Setting up your preferred IDE"

framework/src/play/src/main/scala/play/api/controllers/Assets.scala
This commit succesfully merged to 2.4.x anno:
https://github.com/playframework/playframework/commit/9cd744f7171de2682e93a533a18c672f43a898e1
I can't test it on local, I had problems in local publish, and its not a really well documented area in this version, but we want to use it in the next release.
=> Fix versioned assets on Windows

framework/project/Build.scala
=> Cross-build support for routes compiler

framework/project/Dependencies.scala, framework/src/play/src/main/resources/play/reference-overrides.conf
Addresses #5378, #3795, https://github.com/playframework/playframework/issues/5120
=> Upgrade to Akka 2.4.1

framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala
These changes improve performance by about 3000 requests/s on our test box.
* Inline some higher-order code in Server and NettyModelConversion
* Avoid concatenating an empty map in NettyModelConversion
=> Minor changes to improve performance

documentation/manual/releases/Highlights25.md
Fixes https://github.com/playframework/playframework/issues/5370
=> Add flexible logging section to Highlights25.md

documentation/manual/releases/Migration25.md
Fixes https://github.com/playframework/playframework/issues/5371
=> Add section on Plugin API to Migration25.md

documentation/manual/ModuleDirectory.md
I categorized into:
* API hosting
* Assets
* Auth
* Datastore
* Deployment
* Localization
* Performance
* Templates and view
* Utilities
* Cloud services
=> Organize the modules listing page so that it's easier to consume

framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala
=> Stop supporting deprecated logging methods

documentation/manual/detailedTopics/configuration/ws/code/HowsMySSLSpec.scala
HowsMySSL switch to Let's encrypt, and the JDK doesn't have the root CA for it in its trusted CAs.
This should fix CI.
=> Fixed HowsMySSLSpec

documentation/manual/detailedTopics/configuration/SettingsLogger.md
Fixes https://github.com/playframework/playframework/issues/5411
=> Remove obsolete akka logging info

framework/src/play-exceptions/src/main/java/play/api/PlayException.java
See https://groups.google.com/forum/?fromgroups#!topic/play-framework/QxKlrDOdvQE
Thanks to @gslowikowski for reporting this.
=> Show correct line in console error message

framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-java-ws/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
=> Fix repeated content type headers in WS on POST

documentation/manual/detailedTopics/build/SBTSubProjects.md
Keys.devSettings is from old documentation, it should be PlayKeys.devSettings
=> Keys.devSettings to PlayKeys.devSettings

framework/src/play-java/src/main/java/play/inject/guice/GuiceApplicationBuilder.java, framework/src/play-test/src/main/java/play/test/FakeApplication.java, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play-test/src/main/scala/play/api/test/Fakes.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/GlobalSettings.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala, framework/src/play/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
Fixes https://github.com/playframework/playframework/issues/5494
=> Deprecate references to GlobalSettings

framework/src/play/src/main/scala/play/api/Play.scala
=> Fix up @deprecated links

framework/src/play/src/main/scala/play/api/mvc/Http.scala, framework/src/play/src/main/scala/play/core/j/JavaAction.scala
Fixes https://github.com/playframework/playframework/issues/5358.
Pull everything together so the `Cookies` utility class is using `CookiesConfiguration` etc.
Does not change program behavior or modify existing APIs, but should make it clearer for 2.6.
=> Minimize use of HttpConfiguration.current 

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
"Try again" instead of "Mark it resolved" button for transactional evolutions.
Fixes #4885
=> Transactional evolutions: "Try again" button

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
=> Evolution now work when play.http.context is set

framework/src/play-logback/src/main/resources/logback-play-default.xml, framework/src/play-logback/src/main/resources/logback-play-dev.xml, framework/src/play-logback/src/main/resources/logback-play-logSql.xml, templates/play-java-intro/conf/logback.xml, templates/play-java/conf/logback.xml, templates/play-scala-intro/conf/logback.xml, templates/play-scala/conf/logback.xml
Fixes https://github.com/playframework/playframework/issues/5535
Updates the application.home so you can run tests from intellij.
=> Update application.home default

documentation/manual/releases/release25/Highlights25.md, documentation/manual/releases/release25/Migration25.md
I edited the existing highlights and migration docs and added some new text.
There's a lot of content we need to write so I put placeholder `TODO` entries in the docs for us to fill in later.
This PR should be merged even though it's incomplete so that people can start working on the TODO entries.
=> Release docs for 2.5

documentation/manual/gettingStarted/NewApplication.md, documentation/manual/hacking/Translations.md, documentation/manual/releases/release25/Migration25.md
Still some places in the documentation that refer to 0.13.8.  
Also see https://github.com/playframework/interplay/issues/10
=> [doc] Change docs to make clear we use 0.13.9

documentation/manual/ModuleDirectory.md, documentation/manual/working/javaGuide/advanced/extending/JavaPlayModules.md, documentation/manual/working/javaGuide/advanced/extending/JavaPlugins.md, documentation/manual/working/javaGuide/advanced/extending/code/javaguide/advanced/extending/JavaExtendingPlay.java, documentation/manual/working/javaGuide/advanced/extending/code/javaguide/advanced/extending/MyApi.java, documentation/manual/working/javaGuide/advanced/extending/code/javaguide/advanced/extending/MyModule.java, documentation/manual/working/javaGuide/advanced/extending/index.toc, documentation/manual/working/scalaGuide/advanced/extending/ScalaPlayModules.md, documentation/manual/working/scalaGuide/advanced/extending/ScalaPlugins.md, documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala, documentation/manual/working/scalaGuide/advanced/extending/index.toc
Fixes https://github.com/playframework/playframework/issues/4625
Describes using the Module functionality -- may want to expand on this.
=> [doc] Remove Plugins documentation, add modules doc

framework/project/Dependencies.scala
=> Upgrade to AHC 2.0.0-RC8

documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
Was already in JavaRouting.md.
=> Add PATCH to list of HTTP verbs in ScalaRouting.md

documentation/manual/gettingStarted/PlayConsole.md
Reverts playframework/playframework#5428 -- this applies to 2.4.x but the changes it refers to are on master.
=> Revert "Update PlayConsole.md"

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
Adds a builder for `CORSConfig` and a constructor for `CORSFilter` that accepts Java types.
=> Java API for constructing CORSFilter

documentation/manual/gettingStarted/IDE.md
- update old links
- new workflow in IDEA when creating a new project
- mention activator templates
=> Update IDE docs about IntelliJ IDEA

framework/project/Docs.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-java/src/main/java/play/libs/EventSource.java, framework/src/play-java/src/main/java/play/libs/LegacyEventSource.java, framework/src/play-java/src/test/java/play/libs/LegacyEventSourceTest.java, framework/src/play/src/main/scala/play/api/libs/EventSource.scala, framework/src/play/src/test/scala/play/api/libs/EventSourceSpec.scala
Changes the interface of EventSource to accept Source[Event, _].
Fixes #5160
=> Use Akka Streams for EventSource

documentation/manual/releases/release25/Migration25.md, documentation/manual/working/javaGuide/main/forms/JavaCsrf.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaCsrf.java, documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md, documentation/manual/working/scalaGuide/main/forms/code/ScalaCsrf.scala, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
Includes the changes in #5527, plus some improvements to configuration, plus an option to trust CORS requests.
=> Hardened CSRF filter

framework/src/play/src/main/scala/play/core/j/JavaWebSocket.scala
=> Reformat JavaWebSocket

framework/src/play-json/src/main/java/play/libs/Json.java
Fixes #5540 by updating the comment.
=> Change comment to not include reference to GlobalSettings

templates/play-common/conf/application.conf
Fixes https://github.com/playframework/playframework/issues/5533
Added lots of documentation and links to the documentation website.
=> Updates the application.conf

framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Promise.scala, framework/src/play/src/main/scala/play/api/mvc/WebSocket.scala
Reduce use of `implicit app:Application` god object.
=> Deprecate and minimize use of Akka.system

framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala, framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc/src/main/scala/play/api/db/DB.scala, framework/src/play-ws/src/main/scala/play/api/libs/openid/OpenIdClient.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
=> Deprecate methods with implicit Application

documentation/manual/gettingStarted/code/PlayConsole.scala, documentation/manual/working/commonGuide/configuration/code/ThreadPools.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala, framework/src/play/src/main/scala/play/api/Application.scala
Remove Play.current from places in documentation tests and from ImplicitNotFounds
=> Remove Play.current doc references

documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/javaGuide/main/dependencyinjection/code/static.sbt
Fixes https://github.com/playframework/playframework/pull/5363#issuecomment-179634751
Change the Java DI page to match the Scala DI page.
=> Add router documentation to Java DI doc

documentation/manual/releases/release25/migration25/JavaMigration25.md, documentation/manual/releases/release25/migration25/Migration25.md, documentation/manual/releases/release25/migration25/StreamsMigration25.md, framework/src/play-streams/src/main/scala/play/api/libs/streams/Streams.scala
Also added missing processor <-> enumeratee converters.
=> Continued work on the Migration docs

documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/cors/Filters.java, documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/gzipencoding/CustomFilters.java, documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/gzipencoding/Filters.java, documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/headers/Filters.java, documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/hosts/Filters.java, documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/Filters.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf/Filters.java, framework/src/play/src/main/java/play/http/HttpFilters.java, framework/src/play/src/main/scala/play/api/http/HttpFilters.scala, templates/play-java/app/Filters.java
=> Use Java filters in play.http.HttpFilters

framework/src/play-java/src/main/java/play/libs/EventSource.java
This fixes the omnidoc nightly build.
=> Fixed javadocs generation

templates/play-scala/build.sbt, templates/play-scala/test/ApplicationSpec.scala, templates/play-scala/test/IntegrationSpec.scala
Changed to use ScalaTest as default.
=> ScalaTest + Play

documentation/manual/releases/release25/migration25/StreamsMigration25.md
Some docs explaining how to migrate SSE code from Play 2.4 to Play 2.5.
=> Server-Sent Event migration docs

framework/project/Build.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-java/src/main/java/play/libs/Crypto.java
So Java users can manually construct a CSRF filter.
=> CSRF config Java API

documentation/manual/releases/release25/Highlights25.md, documentation/manual/releases/release25/migration25/JavaMigration25.md, documentation/manual/releases/release25/migration25/StreamsMigration25.md, documentation/manual/working/commonGuide/configuration/ThreadPools.md, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java, documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala, framework/project/Dependencies.scala, framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala
* Upgrade to Akka 2.4.2
* Finish Highlights and remove todos
* Remove todos from migration guide
* Deprecated Json API iteratees dependency
=> RC release preparation

framework/project/plugins.sbt
This fixes scripted eviction warnings.
=> Upgrade to interplay 1.1.1

framework/src/play-java/src/main/java/play/data/Form.java
I wanted to get rid of the `play.i18n.Messages.get(...)` which is deprecated.
=> Remove Global state from errorsAsJson

documentation/manual/ModuleDirectory.md, documentation/manual/gettingStarted/IDE.md, documentation/manual/gettingStarted/Tutorials.md, documentation/manual/releases/release25/migration25/StreamsMigration25.md, documentation/manual/working/commonGuide/configuration/ws/CertificateGeneration.md, documentation/manual/working/commonGuide/configuration/ws/CertificateValidation.md, documentation/manual/working/commonGuide/configuration/ws/CipherSuites.md, documentation/manual/working/commonGuide/configuration/ws/LooseSSL.md, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala
1. Validates/corrects most of the external links
2. Small correction to validateExternalLinks task
=> Docs: validate/correct external links

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Adds an issue and pull request templates, from https://github.com/blog/2111-issue-and-pull-request-templates
=> Add issue template and pull request template

framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
=> Deprecate static JPA methods

documentation/manual/working/scalaGuide/main/http/ScalaActions.md, documentation/manual/working/scalaGuide/main/http/code/ScalaActions.scala
Fixes #4508 
Clarify the difference between class and objects when declaring controllers.
See discussion at #4508
=> Docs about the difference between class and objects to declare controllers

templates/README.md
=> [ doc]  Fix minor typo  in documentation

documentation/manual/gettingStarted/NewApplication.md, documentation/manual/hacking/Translations.md, documentation/manual/releases/release25/migration25/Migration25.md, documentation/project/build.properties, framework/project/Dependencies.scala, framework/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/project/build.properties, framework/src/sbt-fork-run-plugin/src/sbt-test/fork-run/dev-mode/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/project/build.properties, templates/build.sbt, templates/project/build.properties
In addition to upgrading to 0.13.11, I upgraded to a new sbt-web release (1.3.0) which adds compatibility with sbt's new inter project dependency tracking features.
=> Upgraded to sbt 0.13.11

documentation/manual/gettingStarted/NewApplication.md, documentation/manual/hacking/Repositories.md
=> Update repository URL for snapshots

documentation/manual/releases/release25/migration25/StreamsMigration25.md, documentation/manual/working/javaGuide/main/async/JavaStream.md, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java
=> Update JavaStream to use Akka streams

documentation/manual/working/javaGuide/main/forms/JavaForms.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/FormattersModule.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/FormattersProvider.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, framework/src/play-java/src/main/java/play/data/DynamicForm.java, framework/src/play-java/src/main/java/play/data/Form.java, framework/src/play-java/src/main/java/play/data/FormFactory.java, framework/src/play-java/src/main/java/play/data/format/Formatters.java, framework/src/play-java/src/main/java/play/data/format/FormattersModule.java, framework/src/play-java/src/main/resources/reference.conf, framework/src/play-java/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java, framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play-java/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java/src/test/scala/play/data/FormSpec.scala, framework/src/play-java/src/test/scala/play/data/PartialValidationSpec.scala
I also already inject `MessagesApi` into `Formatters` because it's needed for other PR's I will push soon.
Also addresses jroper's [comment](https://github.com/playframework/playframework/pull/5619#discussion_r53101188).
=> Formatters use DI now

documentation/manual/gettingStarted/Tutorials.md
* Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* Have you signed the [Typesafe CLA](https://www.typesafe.com/contribute/cla)?
* Have you [squashed your commits](https://www.playframework.com/documentation/2.4.x/WorkingWithGit#Squashing-commits)?
* Have you added copyright headers to new files?
* Have you checked that both Scala and Java APIs are updated?
* Have you updated the documentation?
* Have you added tests?
Fixes #xxxx
=> add play conditional form mapping tutorial

documentation/README.md
Fixes https://github.com/playframework/playframework/issues/5706
Updates the documentation README.
The build instructions were out of date.
=> [doc] Update documentation readme

framework/src/play-java/src/main/java/play/data/FormFactory.java, framework/src/play-java/src/main/java/play/data/FormFactoryModule.java, framework/src/play-java/src/main/java/play/data/format/FormattersModule.java, framework/src/play-java/src/main/java/play/libs/crypto/CookieSigner.java, framework/src/play-java/src/test/java/play/data/Birthday.java, framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcCurlRequestLogger.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcCurlRequestLoggerSpec.scala, framework/src/play/src/main/scala/play/api/libs/crypto/Crypto.scala, framework/src/play/src/test/scala/play/api/libs/CometSpec.scala, framework/src/play/src/test/scala/play/api/libs/crypto/AESCTRCrypterSpec.scala, framework/src/play/src/test/scala/play/api/libs/crypto/CSRFTokenSignerSpec.scala, framework/src/play/src/test/scala/play/api/libs/crypto/CookieSignerSpec.scala
This will probably occur for a while when merging pull requests which have been written before the name change to Lightbend.
=> Typesafe ->  Lightbend

framework/src/play/src/main/scala/play/utils/Resources.scala, framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
Allow deployment of play apps on weblogic.
On the application start loading of messages and the check added to ignore directories breaks the startup by throwing an exception on unknown protocol ("zip"), rendering the application unusable.
Original commit introducing the breakage - https://github.com/playframework/playframework/commit/686a9b4535815d24381cea9acd901461fd28a4fa
=> fix deployment on weblogic

.github/PULL_REQUEST_TEMPLATE.md
Adds checkboxes
Now you can check things off if you have PRs in progress.
See https://github.com/blog/1375-task-lists-in-gfm-issues-pulls-comments for more details.
=> Added checkboxes to PULL_REQUEST_TEMPLATE.md

documentation/manual/gettingStarted/IDE.md, documentation/manual/releases/release25/Highlights25.md, documentation/manual/releases/release25/migration25/CryptoMigration25.md, documentation/manual/releases/release25/migration25/Migration25.md
Some general doc improvements.
=> [doc] Update highlights and cryptographic migrations 2.5

documentation/manual/releases/release25/migration25/Migration25.md
See also #5738 and https://groups.google.com/d/msg/play-framework/pu1GR69Xyp8/iChj9mzoFwAJ
=> Update migration guide to mention charset changes

documentation/manual/gettingStarted/Anatomy.md
=> [doc] Update layout of Play application

documentation/manual/working/scalaGuide/main/ScalaHome.md
=> Docs: Should be Scala instead of Java

framework/src/play-java/src/main/java/play/data/Form.java
`Optional.of` is wrong here, it throws an exception. We don't want that, we check with `isPresent()` a few lines later instead.
=> Use Optional.ofNullable

framework/src/play-logback/src/main/resources/logback-play-default.xml, framework/src/play-logback/src/main/resources/logback-play-dev.xml
=> Remove ebean specific logging configuration

documentation/manual/detailedTopics/configuration/ws/LooseSSL.md
Fixes #xxxx
which works for completely disabling verification
ws.acceptAnyCertificate=true
=> corrected the property

documentation/manual/working/scalaGuide/main/ws/ScalaWS.md, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Fixes the documentation for the Scala request filter.
Cleans up the Curl example
The example is unclear because both withBody and the put(body) are defined.
=> [doc] Fix the Scala request filter example

documentation/manual/releases/release25/Highlights25.md, documentation/manual/releases/release25/migration25/CryptoMigration25.md, documentation/manual/releases/release25/migration25/JavaMigration25.md, documentation/manual/releases/release25/migration25/Migration25.md, documentation/manual/releases/release25/migration25/StreamsMigration25.md
Backport of https://github.com/playframework/playframework/pull/5799
=> [2.5.x] Small corrections to migration guide 2.5 

framework/src/play/src/main/scala/play/api/mvc/Controller.scala
Fixes #5831.
Requires backport to 2.5.x.
=> Fix Controller scaladoc to use class

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsModule.scala
=> Make EvolutionsComponents.dynamicEvolutions concrete

documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
Added a "motivation" section explaining the benefits of DI.
=> Clarifications to DI documentation

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsModule.scala
=> Backport #5839 fix on 2.5.x

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
=> Adds column names to insert into statement in EvolutionsApi evolve method

.github/PULL_REQUEST_TEMPLATE.md
=> [doc] Update CLA link at PULL_REQUEST_TEMPLATE.md

framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
=> Ensure data parts don't take 5 seconds to parse

.github/PULL_REQUEST_TEMPLATE.md
Adds a link for general PR etiquette
First time contributors sometimes don't know all the ins and outs of Github PRs.  This link provides some background context.
=> [doc] Add extra line to PR template

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, documentation/manual/working/scalaGuide/main/ws/ScalaWS.md, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/libs/WSSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/play-java-ws/src/main/java/play/libs/ws/WSRequest.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-ws/src/main/scala/play/api/libs/ws/WS.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/java/play/mvc/MultipartFormatter.java, framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
Backports #5698 to the 2.5.x branch
=> [Backport] Fixes #902 added multipart/form-data requests to play-ws

documentation/manual/ModuleDirectory.md
=> [doc] Update URL to play-slick

documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala, framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play-java/src/test/resources/messages.en-US, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
=> [Backport] ctx().messages() takes current lang into account now

framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala
This introduces a new `FlattenedAccumulator` with more efficient implementations of the `run` methods. This also rewrites the logic to use more standard Akka streams approaches.
@jroper said the bugs mentioned in the comment may no longer exist or may be due to his lack of experience with Akka streams at the time.
=> Better implementation for Accumulator.flatten

templates/play-scala/app/Module.scala, templates/play-scala/app/controllers/AsyncController.scala, templates/play-scala/app/services/ApplicationTimer.scala
Fixes few typos I have found in `scala-play` template after starting a new project. Also I'm adding parentheses to `asEagerSingleton` which was reported by IntelliJ as warning.
Fixing typos, so it will be more pleasant experience when staring a new project.
I have seen those typos and IntelliJ warning as a first thing after starting new project,
no references
=> fixed typos in play-scala application template

framework/src/play-logback/src/main/resources/logback-play-logSql.xml
=> Fixes jdbcdslog logback.xml

framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/test/java/play/mvc/RequestBuilderTest.java
=> [Backport] Fixes #2289 adds a bodyMultipart function to the request builder

documentation/manual/working/commonGuide/configuration/ws/WsSSL.md
Fixes https://github.com/playframework/playframework/issues/3643
There's a problem where people try to use SSL Config but don't have the unlimited policy files installed.  Add a note in the docs.
Many.
=> [doc] Add link to JCE policy files

documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
=> [Forwardport] Fix binary compatibility issues in MessagesApi

framework/src/play-logback/src/main/resources/logback-play-default.xml, framework/src/play-logback/src/main/resources/logback-play-dev.xml
* [] Have you added copyright headers to new files?
* [] Have you checked that both Scala and Java APIs are updated?
* [] Have you updated the documentation for both Scala and Java sections?
* [] Have you added tests for any changed functionality?
Fixes #5842
Fixes default application logging level 
@marcospereira confirmed it was a bug and asked for a PR
Default logging levels for application
- DEBUG in DEV mode
- INFO in other modes
=> Fixed default logging level for application. Fixes #5842

templates/play-java/app/Filters.java, templates/play-java/app/controllers/AsyncController.java, templates/play-java/app/controllers/HomeController.java, templates/play-java/app/filters/ExampleFilter.java, templates/play-java/app/services/ApplicationTimer.java
Fixes typos and javadoc in the `play-java` template. Also removed one unused import
Fixing typos, so it will be more pleasant experience when staring a new project with this template
After fixing `play-scala` template I decided to take a look at this template as well.
I did similar for for `play-scala` template in https://github.com/playframework/playframework/pull/5904
=> fixed typos in play-java application template

framework/project/Dependencies.scala
=> [Backport] Update netty-reactive-streams

framework/src/play-java/src/test/java/play/data/validation/TestConstraints.java, framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play-java/src/test/resources/messages, framework/src/play-java/src/test/resources/messages.fr, framework/src/play-java/src/test/scala/play/data/Task.scala
Nothing spectacular - just added a test for #5753 which I still had on my TODO list.
I just want to ensure no one breaks DI support for validators in the future :wink:
=> Add tests for constraints which contain injected components

documentation/manual/working/javaGuide/main/sql/JavaDatabase.md, documentation/manual/working/javaGuide/main/sql/code/JavaJdbcConnection.java
=> Fix documentation for Jdbc connection from Database

documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md, documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
I haven't done the Java documentation yet since I am not that familiar with the API.
=> Update Scala WebSocket documentation for 2.5

documentation/manual/releases/release25/migration25/StreamsMigration25.md
=> Forwardport PR 5950

documentation/manual/working/commonGuide/assets/AssetsSass.md, templates/build.sbt
Update to the latest version of sbt-sassify.
There is an issue with sbt-sassify version 1.4.2 where the encoding of unicode characters is messed up on window. This is solved in version 1.4.4
For more details see [this issue](https://github.com/irundaia/sbt-sassify/issues/13).
=> Update to the latest version of sbt-sassify

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala, framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/resources/reference.conf
Port of https://github.com/playframework/playframework/pull/5948 to 2.5.x
Working with Akka HTTP now
https://github.com/playframework/playframework/pull/5948
=> Add idleTimeout support to 2.5.x

framework/project/Build.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala
Backport of #5897. Fixes #5972.
=> [2.5.x] Better implementation for Accumulator.flatten

documentation/manual/gettingStarted/Installing.md
Fixes #xxxx
bin folder is missing in Windows configuration section.
=> Update Installing.md - bin folder is missing in Windows configuration section

documentation/manual/gettingStarted/Installing.md
=> Forwardport #5983 - Update Installing.md

framework/project/Build.scala, framework/src/play-java/src/main/java/play/libs/Classpath.java, framework/src/play-java/src/main/scala/play/libs/ReflectionsCache.scala, framework/src/play-java/src/test/java/play/libs/ClasspathTest.java, framework/src/play-java/src/test/java/play/libs/testmodel/AC1.java, framework/src/play-java/src/test/java/play/libs/testmodel/C1.java
This PR backports PR #4831 to 2.4.x.
=> Added SubTypesScanner to Reflections factory in Classpath

framework/project/Dependencies.scala
Fixes #5988
Needs backport to 2.5.x
=> Changed async-http-client to RC19

documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
Forward port of https://github.com/playframework/playframework/pull/5999 which was 2.5.x only
=> [master] Fix typo in ScalaDependencyInjection.md

documentation/manual/gettingStarted/Tutorials.md
Adds http://www.schibsted.pl/2016/04/dependency-injection-play-framework-scala/ to tutorials page.
=> Add Dependency Injection blog post

framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala
Generally, if we have an exception configuring the logger, it should prevent the application from starting, since lack of logging can hide serious problems.
=> Don't catch exceptions in LogbackLoggerConfigurator

framework/src/play-logback/src/main/scala/play.api.libs.logback/LogbackLoggerConfigurator.scala
Backports https://github.com/playframework/playframework/pull/6025
=> [2.5.x] Don't catch exceptions in LogbackLoggerConfigurator

framework/src/play-akka-http-server/src/main/scala/akka/http/play/WebSocketHandler.scala
According to the [Akka migration guide 2.0.x to 2.4.x](http://doc.akka.io/docs/akka/snapshot/scala/stream/migration-guide-2.0-2.4-scala.html#PushStage__PushPullStage_and_DetachedStage_have_been_deprecated_in_favor_of_GraphStage) 
"The PushStage PushPullStage and DetachedStage classes have been deprecated and should be replaced by GraphStage"
Replace the implementation of the methods based on PushStage with GraphStage in WebSocketHandler.scala
=> Replace PushStage based methods with GraphStage in WebSocketHandler

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
=> Fix header parsing in Akka server

framework/src/play/src/main/scala/views/play20/welcome.scala.html
Fixes #6035 
Updates mysql connection information in `welcome.scala.html`
=> #6035 - update mysql config in welcome.scala.html

documentation/manual/working/commonGuide/build/BuildOverview.md
=> Update play imports for sbt in Documentation

framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/test/java/play/mvc/RangeResultsTest.java, framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
https://groups.google.com/d/msg/play-framework/gYURNzkSt6k/qfHY-xMJJgAJ
=> Fixes the warning: "Content-Type set both in header"

documentation/manual/Home.md, documentation/manual/experimental/AkkaHttpServer.md, documentation/manual/releases/release22/Migration22.md, documentation/manual/releases/release24/ReactiveStreamsIntegration.md, documentation/manual/releases/release25/Highlights25.md, documentation/manual/releases/release25/migration25/StreamsMigration25.md, documentation/manual/working/commonGuide/configuration/ThreadPools.md, documentation/manual/working/javaGuide/main/async/JavaComet.md, documentation/manual/working/javaGuide/main/async/JavaStream.md, documentation/manual/working/javaGuide/main/http/JavaBodyParsers.md, documentation/manual/working/scalaGuide/main/async/ScalaComet.md, documentation/manual/working/scalaGuide/main/http/ScalaBodyParsers.md, framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala, framework/src/play/src/main/java/play/mvc/StatusHeader.java, framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala, framework/src/play/src/test/java/play/mvc/RangeResultsTest.java
=> [2.5.x] Upgrade Akka to version 2.4.4

framework/src/play-java-jpa/src/test/java/play/db/jpa/TestEntity.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSResponse.java, framework/src/play-java/src/main/java/play/data/Form.java, framework/src/play-java/src/main/java/play/libs/XPath.java, framework/src/play-jdbc-evolutions/src/main/java/play/db/evolutions/EvolutionsReader.java, framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java, framework/src/play/src/main/java/play/Configuration.java, framework/src/play/src/main/java/play/i18n/Lang.java, framework/src/play/src/main/java/play/mvc/EssentialAction.java, framework/src/play/src/main/java/play/mvc/Filter.java, framework/src/play/src/test/java/play/ConfigurationTest.java
Just some refactoring to use Java 8 stream APIS and have more concise code.
=> Refactoring to use Java 8 Streams API

framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
=> Add websocket tests

framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Config.scala
Fixes #6020
Needs backport to 2.5.x.
=> Make SSLConfigParser accept Configuration

templates/play-java/app/services/ApplicationTimer.java, templates/play-scala/app/services/ApplicationTimer.scala
Correct a spelling mistake in play-java/scala template. Is: "wil", should be: "will".
=> Corrected spelling in templates

framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
Fixes #6076
Allows request filters to add (immutably) to the outbound request. E.g. appending headers to a request
=> allow request filters to modify outbound request

framework/project/Dependencies.scala
1. https://github.com/AsyncHttpClient/async-http-client/issues?q=milestone%3A2.0.1
2. https://github.com/AsyncHttpClient/async-http-client/issues?q=milestone%3A2.0.2
3. https://github.com/AsyncHttpClient/async-http-client/compare/b60e5a0...6d4ab5a38042481c8c39ce8ffd78f99fda2f567d
=> Upgrade async-http-client to version 2.0.2

documentation/manual/gettingStarted/Tutorials.md
N/A
Add new tutorial for RethinkDB & Play
N/A
N/A
=> Added Play 2.4.x, Scala and RethinkDB Tutorial

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/scala/play/api/mvc/Http.scala, framework/src/play/src/main/scala/play/core/j/JavaResults.scala
=> Add withCookies to Java Result API

documentation/manual/gettingStarted/Installing.md, documentation/manual/working/javaGuide/main/http/JavaRouting.md
- Fixes "though" to "through" on GettingStarted/Installing.md
- Fixes "assume" to match plural on working/javaGuide/main/http/JavaRouting.md
=> docs: fix typos

documentation/manual/gettingStarted/Tutorials.md
* [ *] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [* ] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [* ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* Existing Play with Slick template is outdated so added new Template with latest version.
=> Play with Slick Template update

framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala
=> Update Documentation in Json.scala

framework/src/play-exceptions/src/main/java/play/api/PlayException.java
=> Trim \r in PlayException interestingLines

documentation/manual/working/commonGuide/configuration/SettingsLogger.md
=> Add note about LoggerConfigurator with custom ApplicationLoader

documentation/manual/ModuleDirectory.md
Just add a new module (Play I18n HOCON) to module directory.
=> Add Play I18n HOCON module to module directory

documentation/manual/working/javaGuide/main/cache/JavaCache.md, documentation/manual/working/scalaGuide/main/cache/ScalaCache.md, framework/src/play-cache/src/main/resources/reference.conf, framework/src/play-cache/src/main/scala/play/api/cache/Cache.scala, framework/src/play-cache/src/test/scala/play/api/cache/CacheApiSpec.scala
Fixes #5443 
This can be backported to 2.5.x and 2.4.x.
=> Add option to prevent Play from creating bound caches

documentation/manual/working/javaGuide/main/ws/JavaWS.md
Fixes https://github.com/playframework/playframework/issues/6132
=> Update the API for JDK 1.8 and add links

documentation/manual/gettingStarted/Tutorials.md
Updates the tutorials page to point to playframework github pages primarily, add more explicit "downloading a template" sections, and adds new sections on using cryptography, compile time injection, and ORM.
Many of the play projects point either off site, or point to outdated examples.  The goal here is to make all of the tutorials current and to keep a running list in the "release guide" so that they can be updated with new major releases.
=> Update tutorials section

documentation/manual/working/javaGuide/advanced/routing/JavaRoutingDsl.md, documentation/manual/working/javaGuide/advanced/routing/code/GuiceAppLoader.java, documentation/manual/working/javaGuide/advanced/routing/code/GuiceRouterProvider.java, documentation/manual/working/scalaGuide/advanced/routing/ScalaSirdRouter.md, documentation/manual/working/scalaGuide/advanced/routing/code/ScalaSimpleRouter.scala
Fixes #6133
Adds more documentation about routing
=> Fixed #6133 added some docs for routes provider

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Fixes #6161
The execution of prepared statements is now wrapped in a try-finally and closed at the end.
=> Close prepared statements in EvolutionsApi

framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcConfig.scala
Fixes #4796
Actually it makes acceptAnyCertificate working
In Play 2.4 upwards Play added a JsseSslContext and relied on Netty 4 / Asynchttpclient 2 while everything worked, the certificate handling changed and made it impossible to run under "really" loose SSL setups.
At the moment there aren't tests for this, but it will be actually hard to implement.
There is one way but since I would need to work around some things I didn't. Actually setting up a play instance with -Dhttps.port=9443 and point a ws.url to itself it will actually fail with a SSL Error so there would be a way to test, however the WS Test client doesn't rely on a typesafe config (https://github.com/playframework/playframework/blob/9a06b9a0a6ea7d1299e61ea3c1f37a08b714297e/framework/src/play-ws/src/main/scala/play/api/test/W …
=> Fixes #4796 makes acceptAnyCertificate work

documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
We still use static actions in upload docs:
https://www.playframework.com/documentation/2.5.x/JavaFileUpload
=> Documentation fix: Action should not be static anymore

documentation/manual/releases/release24/migration24/PluginsToModules.md, documentation/manual/working/javaGuide/advanced/extending/JavaPlayModules.md, documentation/manual/working/scalaGuide/advanced/extending/ScalaPlayModules.md
Adds documentation around Modules
=> added some more documentation around Modules

framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
The issue seems to be already fixed.
I added two tests to prove that.
=> Tests for #4906

documentation/manual/releases/release24/migration24/PluginsToModules.md, documentation/manual/working/javaGuide/advanced/extending/JavaPlayModules.md, documentation/manual/working/scalaGuide/advanced/extending/ScalaPlayModules.md
=> [Backport 2.5.x] added some more documentation around Modules (#6185)

framework/project/Dependencies.scala
Fixes https://groups.google.com/forum/#!topic/play-framework/9utj-Xtv8SU
=> update netty-reactive-streams to 1.0.6

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
=> Properly set underlying request in AddCSRFToken

framework/project/Dependencies.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
Fixes #6190 
Replaces #6191 (that one was not up to date).
=> Fix for #6190

framework/project/Build.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultException.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
This is a backport of #6153 from master.
Once this has been merged into 2.5.x, I'll backport it again to 2.4.x.
=> Better Result error handling

documentation/manual/hacking/Repositories.md
Fixes #xxxx
Changes the docs to recommend the built in typesafe Repo resolver
It's recommended at http://www.scala-sbt.org/0.13/docs/Resolvers.html#Predefined
http://www.scala-sbt.org/0.13/docs/Resolvers.html#Predefined
=> Use the built in typesafe Repo resolver

documentation/manual/hacking/BuildingFromSource.md
Change version from 2.5.0-SNAPSHOT to 2.6.0-SNAPSHOT in BuildingFromSource.md.
=> Update version number in BuildingFromSource.md

documentation/manual/working/commonGuide/database/Evolutions.md
=> Clarify how to use evolutions with compile-time DI

documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Forward port of #6148 into master via cherry-pick of 4488248009c075e37fd619610e465c1152e27c0c
=> [master] Move environment definition into code example (#6148)

framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala
With the Accumulator API sometimes your Controllers will yield a `Accumulator[ByteString, Result]` instead of a `Future[Result]`. Mostly when you handle `EssentialAction`s or have some `multipart/form-data` stuff.
To make it easier to test those I added some Methods to `Helpers.scala`
Actually it's the only way of adding them.
Should be backportable since it won't change existing methods.
=> added test helper for accumulator

framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java, framework/src/play/src/main/java/play/mvc/Http.java
=> Fix double-encoding of RequestBuilder params

documentation/manual/gettingStarted/Tutorials.md
Fixes https://github.com/playframework/playframework/issues/6188 by backporting Tutorials.md to 2.5.4
=> [doc] Backport tutorials

framework/project/Dependencies.scala
Fixes #6235 for 2.5.x series.
https://github.com/playframework/playframework/pull/6235
=> Backport for 2.5.x #6235: Bump slf4j minor version to fix a memory leak issue (SLF4J-364)

framework/project/Dependencies.scala
Fixes #6235 for 2.4.x series.
https://github.com/playframework/playframework/pull/6235
=> Backport for 2.4.x #6235: Bump slf4j minor version to fix a memory leak issue (SLF4J-364)

framework/project/Build.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayDefaultUpstreamHandler.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultException.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
This is a backport of #6153 from master. The 2.5.x backport is #6210.
Fairly extensive changes were required to backport to 2.4.x.
=> Better Result error handling (2.4.x)

framework/src/play/src/main/scala/play/api/routing/JavascriptReverseRouter.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/assets/JavaScriptRouterSpec.js, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/utils/JavaScriptRouterGenerator.scala
=> [2.4.x] Escape strings in JS reverse router

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
=> Backport ws doc typo

framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/test/scala/play/mvc/ResultSpec.scala
=> Fix parsing in play.mvc.Result#charset()

framework/src/play/src/main/java/play/mvc/Results.java, framework/src/play/src/main/java/play/mvc/StatusHeader.java, framework/src/play/src/test/scala/play/mvc/ResultSpec.scala
=> [2.5.x] Validate charset when we send JSON results

framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/tests/ServerSpec.scala, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/tests/ServerSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/ScalaCSRFActionSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/FormFieldOrderSpec.scala, framework/src/play-ws/src/test/scala/play/api/libs/oauth/OAuthSpec.scala
Fixes #5806 
Use dependency injection instead of global state for WS
=> [fix] remove usage of WS, use injection instead

framework/src/play-netty-utils/src/main/java/play/core/netty/utils/CookieUtil.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/DefaultCookie.java, framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
This PR backports #6289.
please see #6289
=> Backport for 2.5.x #6289: Apply Netty's cookie encoder/decoder updates.

documentation/manual/working/commonGuide/assets/AssetsOverview.md, framework/src/play/src/main/scala/play/api/controllers/Assets.scala
Fixes #5173, https://groups.google.com/d/topic/play-framework/wAW-HbVPx6I/discussion and https://github.com/playframework/playframework/pull/2973#issuecomment-207121085
=> Don't try to use minified asset in DEV mode

documentation/manual/working/javaGuide/main/json/JavaJsonActions.md, documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonCustomObjectMapper.java, documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonCustomObjectMapperModule.java
Fixes #6318
made the documentation about customizing a object mapper better
=> Fixed #6318 made the documentation about customizing a object mapper better

documentation/manual/working/commonGuide/assets/AssetsLess.md
Fixes #xxxx
This line confused me,  so I think it is more clear now.
=> Clear up the 'other' files in AssetsLess.md

documentation/manual/releases/release25/migration25/Migration25.md
=> fix doc error

framework/src/play-server/src/main/scala/play/core/server/ssl/ServerSSLEngine.scala, framework/src/play/src/main/scala/play/server/api/SSLEngineProvider.scala
Backport of https://github.com/playframework/playframework/pull/6343
=> Fixed incorrect config reference in scala doc [#6341] (#6343)

documentation/manual/working/commonGuide/assets/AssetsOverview.md, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/controllers/Assets.scala
Fixes #6292
Moved assets configuration under play namespage.
Also, added configuration key in reference.conf.
=> Change asset config

documentation/manual/working/javaGuide/main/http/JavaActionCreator.md, documentation/manual/working/javaGuide/main/http/code/javaguide/http/SimpleHttpRequestHandler.java
Fixes #6270
This needs backport to 2.5.x.
=> Fix HttpRequestHandler docs to add JavaHandlerComponents

framework/project/Dependencies.scala
=> Updated dependencies

framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
=> Remove unused imports.

documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md, documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java, framework/src/play/src/main/java/play/mvc/BodyParser.java
Fixes https://github.com/playframework/playframework/issues/5044 
Cherry pick of #6369 to 2.5.x
=> [2.5.x] Add a delegating file part handler for Java (#6369)

framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
=> [2.5.x] fix #6131 (#6284)

framework/src/play-ws/src/main/scala/play/api/libs/openid/OpenIdClient.scala
Remove deprecated OpenIDClient methods
=> Remove deprecated OpenIDClient methods

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Fixes #6420
Result after testing: 
oracle
psql
=> applied_at in evolutions filled as timestamp (#6420)

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
https://github.com/playframework/playframework/pull/6421 was applied to 2.5.x, so cherrypicked with
```
git checkout master
git cherry-pick 1c39cbc498d1adb55d2618a0a9b520bb82169096
```
=> Forward to master -- applied_at in evolutions filled as timestamp (#6420) (#6421)

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSWithCSRFSpec.scala
Remove deprecated CSRF methods
=> Remove deprecated CSRF methods

documentation/manual/releases/release25/migration25/Migration25.md
Backports #6439 to 2.5.x branch.
=> Add line breaks in examples to reduce horizontal scrolling (#6439)

framework/src/play-logback/src/main/scala/play/api/Logger$ColoredLevel.scala
Reverts playframework/playframework#6443
=> Revert "Removes Logger$ColoredLevel"

framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala, framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala, framework/src/play/src/main/scala/play/api/data/Form.scala, framework/src/play/src/main/scala/play/api/mvc/Binders.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala, framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala, framework/src/play/src/main/scala/views/helper/Helpers.scala, framework/src/play/src/main/scala/views/helper/select.scala.html
Fixes some compiler warnings to do with existential types and type erasure.
=> Fix type erasure compiler warnings

documentation/manual/releases/release26/migration26/Migration26.md, framework/src/play/src/main/java/play/libs/Akka.java, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
Removes deprecated `Akka.system` methods.
=> Remove deprecated Akka static methods

framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala
Setting logging options in application.conf makes no difference
=>  Fixed logging documentation in AhcWSClient

templates/play-java/app/filters/ExampleFilter.java, templates/play-scala/app/filters/ExampleFilter.scala
In parent package there is only "Filters" class.
=> Fixes minor typo in default templates

framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala, framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Reverts playframework/playframework#6460
=> Revert "Update deprecated Akka calls"

documentation/manual/working/scalaGuide/main/json/ScalaJsonAutomated.md, documentation/manual/working/scalaGuide/main/json/code/ScalaJsonAutomatedSpec.scala, framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala, framework/src/play-json/src/main/scala/play/api/libs/json/Json.scala, framework/src/play-json/src/main/scala/play/api/libs/json/JsonConfiguration.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonExtensionSpec.scala
Fixes #2333
I liked the idea from @cchantep what he did in anorm.
P.S.: It's the first time i played with Macros.
Also this could be backportable I guess.
Edit: I would merge this as is, so that it maybe could go into 2.5.x but I would change that as soon as I take other issues from #4684. Can't see the big picture yet.
=> Fixes #2333 made it possible to implement custom naming conventions

framework/project/Dependencies.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/HttpRequestDecoder.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
this actually imports the deflate/gzip coding directive from `akka-http`.
=> adds gzip support to the akka backend

framework/src/play/src/main/resources/play/reference-overrides.conf
Fixes https://github.com/playframework/playframework/issues/6510
=> kills the jvm if there is an error

documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala
Minor issue with the Scala Akka documentation.
Using the example in the documentation causes an error as the ask pattern requires the Timeout type to be included for the implicit timeout value. See the below stackoverflow issue for more details. 
To address an error when using the code as an example.
[This stack overflow issue](http://stackoverflow.com/questions/35854812/play-2-5-with-akka-could-not-find-implicit-value-for-parameter-timeout-akka-u) show the exact error I got and the solution to the problem.  
This is my first pull request for play framework, if I missed anything please let me know!
=> Minor addition: adding the timeout type

documentation/manual/working/javaGuide/main/akka/JavaAkka.md, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/HelloActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ask/Application.java
=> Fix Akka example

framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala, framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala
Fixes #6504
Edit: Fix is just 3 Lines https://github.com/playframework/playframework/pull/6534/files#diff-745ef9331ba1901efedd1607f6675eeaR183
Basically we can also omit complet/cancel for netty (not for akka) if necessary.
=> fixes websockets on netty

documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
Fixes #6535
Added cookie reference in the documentation.
=> Improved scala documentation for i18n

documentation/manual/working/commonGuide/database/Developing-with-the-H2-Database.md, templates/play-scala-intro/conf/application.conf
Fixes #6537
P.S.: Looks like ApplicationLifecycle now works really really great.
=> adds a note about h2 while developing

framework/project/Dependencies.scala
=> [2.5.x] Upgrade Netty and netty-reactive-streams

framework/project/Dependencies.scala
This may fix #6491.
/cc @schmitch
=> Upgrade Netty and netty-reactive-streams

documentation/manual/working/scalaGuide/main/http/code/ScalaRouting.scala
Actually this resolves the documentation test fails against 2.5.x
=> makes the documentation tests work again

documentation/manual/gettingStarted/Tutorials.md
Adds the REST API guide into the tutorials page.
=> [doc] Add REST API link into tutorials.

framework/project/Build.scala, framework/project/Docs.scala, framework/project/plugins.sbt, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/build.sbt, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt, templates/project/Build.scala
https://github.com/sbt/sbt/pull/2716
/cc @eed3si9n
=> avoid deprecated methods since sbt 0.13.13

documentation/manual/working/commonGuide/production/Deploying.md
=> Backport PR #6571 to 2.5.x

framework/src/play/src/main/scala/play/api/data/validation/Validation.scala
Add possibility to customize error message for built-in constraints in more flexible way.
=> Custom error messages for built-in validation constraints

framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
Is there  a reason for this behavior?
```
scala> case class Emtpy()
defined class Emtpy
scala> Json.reads[Emtpy]
<console>:16: error: Apply of object Emtpy has no parameters. Are you using an empty case class?
Json.reads[Emtpy]
^
```
In a project I'm working on, this situation is fairly typical. It would be nice if this case produced a `Reads` that matched an empty `JsObject`.
=> Json.reads fails for case classes with no parameters

framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala
Fix master by reformatting with sbt scalariformFormat test:scalariformFormat
=> Reformat to sbt-scalariform 1.6.0

framework/project/Build.scala, framework/project/Docs.scala, framework/project/plugins.sbt, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/build.sbt, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala, framework/src/sbt-fork-run-plugin/src/main/scala/play/sbt/forkrun/PlayForkRun.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt, templates/project/Build.scala
This reverts commit 0193d25d0f7ed15ac55f054e925ee80248e626c6.
=> Revert "avoid deprecated methods since sbt 0.13.13 (#6569)"

documentation/manual/experimental/AkkaHttpServer.md, documentation/manual/experimental/code/ScalaAkkaEmbeddingPlay.scala, documentation/project/Build.scala
Actually my Commit for Akka-Http missed some Tests and Documentation, this adds it: https://github.com/playframework/playframework/commit/a10f4a77a54fafc9e23afb4ec9072f53e9fa8b5d
=> adds documentation around AkkaHttpServer embedded and adds some tests

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-guice/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java, framework/src/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java, framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java, framework/src/play-integration-test/src/test/java/play/it/http/websocket/WebSocketSpecJavaActions.java, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala, framework/src/play-java-jdbc/src/main/java/play/db/ConnectionPool.java, framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAConfig.java, framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-java/src/main/java/play/data/validation/Constraints.java, framework/src/play-java/src/main/java/play/libs/EventSource.java, framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java, framework/src/play-jdbc-evolutions/src/test/java/play/db/evolutions/EvolutionsTest.java, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/libs/Akka.java, framework/src/play/src/main/java/play/mvc/BodyParsers.java, framework/src/play/src/main/java/play/mvc/StatusHeader.java, framework/src/play/src/main/scala/play/api/Play.scala, framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/main/scala/play/api/mvc/Security.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala, framework/src/play/src/test/java/play/mvc/CallTest.java, framework/src/play/src/test/java/play/mvc/RangeResultsTest.java, framework/src/play/src/test/java/play/mvc/SecurityTest.java
Pick off some low-hanging fruit with IntelliJ IDEA.
=> Remove unused imports

framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
Following https://github.com/playframework/playframework/pull/6255#issuecomment-226993937
=> Add javax.inject.Inject to default Twirl constructor

documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
Fixes https://github.com/playframework/playframework/issues/3672
=> [doc] Add a paragraph emphasizing that an implicit request must exist in CSRF

framework/project/plugins.sbt
Let's upgrade sbt-jmh to the latest version (with the latest JMH version 1.14.1) if there's no problems :)
From sbt-jmh version `0.2.10`, we can use Flight Recorder / Java Mission Control[1], which would be nice.
[1] https://github.com/ktoso/sbt-jmh#using-oracle-flight-recorder
=> Upgrade sbt-jmh to 0.2.16

framework/project/Build.scala, framework/project/Dependencies.scala, framework/project/Docs.scala
Backport https://github.com/playframework/playframework/pull/6584 to 2.5.x
=> Backport documentation mappings

framework/src/play-java/src/main/java/play/data/format/Formatters.java, framework/src/play-java/src/test/java/play/data/format/FormattersTest.java
=> Fix Java Formatters (#6419)

framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
Throwables being thrown during initialization of DefaultHttpErrorHandler
may suppress prior thrown ones.
This happens when you e.g. have a broken configuration the can't be initialized (by expecting a (non-optional) environment variable).
DefaultHttpErrorHandlerProvider now provides the DefaultHttpErrorHandler
as lazy val to prevent this behavior.
=> Do not suppress throwables on DefaultHttpErrorHandler initialization

framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala
Fixes #xxxx
For code performance and compactness.
#6634
=> Code updation of HttpConfiguration for compactness and performance

framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
=> Clarify guice error message

documentation/manual/working/commonGuide/build/code/SubProjectsAssetsBuilder.scala, documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/test/scala/play/api/controllers/AssetsDateParsingSpec.scala, framework/src/play/src/test/scala/play/api/controllers/AssetsSpec.scala
Moves around a bunch of the assets stuff so everything is injected.
=> Remove global state from Assets

framework/src/play/src/test/java/play/i18n/MessagesTest.java
Fixes https://github.com/playframework/playframework/issues/6110#issuecomment-256843739
=> fixes MessagesTest so that the community build won't throw any error

documentation/manual/working/scalaGuide/main/json/ScalaJson.md, documentation/manual/working/scalaGuide/main/json/ScalaJsonAutomated.md, documentation/manual/working/scalaGuide/main/json/ScalaJsonHttp.md, documentation/manual/working/scalaGuide/main/json/code/ScalaJsonAutomatedSpec.scala, documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala
Mostly...
Fixes #xxxx
Adds a summary of the capabilities of the Scala JSON package so users know it's able to convert to and from case classes automatically. Also provided an example of doing that.
The first page of the JSON docs is pretty intimidating for new users. Now it highlights some of the features of the package so users don't get bogged down in the details if they just want to serialise to/from case classes.
#6663
=> Summarize the JSON package and provide relevant links.

framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala, framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala
Improve handling of If-None-Match header:
- correctly parse a list of etags
- correctly parse weak etags
- use etag weak comparison as specified by rfc7232
=> If-None-Match caching header improvements.

documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
#6605 [Doc] Adding 'StreamedBody' example to `forward-body`
=> [Doc] Adding 'StreamedBody' example to `forward-body`

documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
=> fix unchecked assignment problem in sample code

documentation/manual/working/javaGuide/main/async/JavaAsync.md, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java, documentation/manual/working/scalaGuide/main/async/ScalaAsync.md, documentation/manual/working/scalaGuide/main/async/code/ScalaAsync.scala, framework/src/play/src/main/java/play/libs/concurrent/Timeout.java, framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala, framework/src/play/src/test/java/play/libs/concurrent/TimeoutTest.java, framework/src/play/src/test/scala/play/api/libs/concurrent/TimeoutSpec.scala
=> [Backport 2.5.x] Add Timeout trait to play.api.libs.concurrent (#6459)

framework/src/play/src/main/scala/play/api/mvc/Controller.scala
@wsargent You added a few things to `ControllerComponents` so I wanted to make them also available through `AbstractController`. I also changed names to make them less likely to conflict with existing methods in the controller.
=> Add methods to AbstractController

framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala, framework/src/play-json/src/test/scala/play/api/libs/json/MacroSpec.scala
`Json.reads[Foo]` with all optional parameters will not actually validate that the input is an object. Instead for non-object inputs it will assume all the optional parameters are not provided.
Test case:
``` scala
import play.api.libs.json._
case class Thingy(id: Option[Long], name: Option[String], description: Option[String])
implicit val readsThingy = Json.reads[Thingy]
val emptyFromObject = Json.fromJson(Json.obj())
val emptyFromString = Json.fromJson(JsString("foo"))
val emptyFromBoolean = Json.fromJson(JsBoolean(false))
```
results in:
``` scala
emptyFromObject: play.api.libs.json.JsResult[Thingy] = JsSuccess(Thingy(None,None,None),)
emptyFromString: play.api.libs.json.JsResult[Thingy] = JsSuccess(Thingy(None,None,None),)
emptyFromBoolean: play.api.libs.json.JsResult[Thingy] = …
```
=> Json.reads[Foo] does not validate that the input is an object

documentation/manual/working/commonGuide/production/Deploying.md
=> Change deprecated 'application.secret' from docs

documentation/manual/releases/release26/migration26/Migration26.md, framework/src/play/src/main/scala/views/helper/requireJs.scala.html, framework/src/play/src/main/scala/views/play20/welcome.scala.html
Removes some references to `Play.maybeApplication` in the helper twirl pages.
=> Remove some static play references in helper pages

framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/ScalaCSRFActionSpec.scala
Removes Play.privateMaybeApplication from the CSRF specs.  
Refactors the tests a little bit to make using an implicit application easier by using withActionServer when components are used in routing, adds an inject method, and takes crypto out of the equation.
=> [UFR] Remove privateMaybeApplication from CSRF tests

documentation/manual/gettingStarted/Tutorials.md
Simplifies the play tutorials page to point to example projects.
=> [doc] Update tutorials page in 2.5.x

documentation/manual/gettingStarted/Tutorials.md
Updates the tutorial page in master branch
=> [doc] Update tutorials page in master

framework/src/play/src/main/java/play/libs/concurrent/HttpExecution.java, framework/src/play/src/main/java/play/libs/crypto/CSRFTokenSigner.java
Fixes the remaining javadoc issues in master.
=> Fix the remaining javadoc issues

framework/src/play/src/main/java/play/libs/concurrent/Timeout.java, framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala
Add more detailed example to Timeout.java, add `@Inject()` to Timeout.scala to provide better examples.
=> [UFR] Add @Inject() to Timeout example

documentation/manual/working/javaGuide/main/akka/JavaAkka.md
=> Rename 'method' to 'field' in java akka docs (#6751)

framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala
Fixes #6773 
Note to myself: don't code at night.
=> changes the slice bytes transformer to graph stage #6773

framework/project/Build.scala, framework/src/play-java/src/main/java/play/data/Form.java, framework/src/play-java/src/test/scala/play/data/FormSpec.scala
Fixes #6272
This is a backport of the change in the 2.5.x branch to fix the issue as above
This was suggested as part of issue #6592 
#6592
=> 2.4.x Backport to fix issue #6272

framework/build.sbt, framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/build.sbt, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/module/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/build.sbt
Upgrades master to Scala 2.12.1
=> Upgrade Scala 2.12.1

framework/src/play/src/main/scala/play/api/LoggerConfigurator.scala
=> Use correct classloader when loading logger configurator class

framework/src/play/src/main/scala/play/api/LoggerConfigurator.scala
=> 2.5.x Use correct classloader when loading logger configurator class (#6779)

framework/src/play/src/main/java/play/mvc/Http.java
In case of a body multipart failure, it'd be nice to have the source exception.
=> Add source exception to multipart failure

framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/ServerConfig.scala
!(isDefined) and isEmpty are equivalent.
Make it simple.
=> Refactoring play-server - !(isDefined) to isEmpty

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/StandaloneWithConfig.java
shows how to use a standalone ws client with the configuration from a HOCON file
CLA signed
=> Added sample code to java documentation for custom WS with config

framework/src/play-java-forms/src/main/java/play/data/format/Formatters.java, framework/src/play-java-forms/src/test/scala/play/data/format/FormattersTest.java
See [my comments](https://github.com/playframework/playframework/pull/6526/files#r91960286)
=> Remove unnecessary parameter

documentation/manual/working/commonGuide/configuration/ConfigFile.md, documentation/manual/working/scalaGuide/main/config/ScalaConfig.md, documentation/manual/working/scalaGuide/main/config/code/ScalaConfig.scala, documentation/manual/working/scalaGuide/main/config/index.toc, documentation/manual/working/scalaGuide/main/index.toc
=> Add documentation for Scala Configuration and ConfigLoader

documentation/manual/working/javaGuide/main/http/JavaRouting.md, documentation/manual/working/scalaGuide/main/http/ScalaRouting.md, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
=> Deprecate StaticRoutesGenerator

framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
=> Handle null ConfigOrigins in Configuration.configError

documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java, documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md, documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java, documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
Documents how to test file uploads in Java.
=> Add docs about how to test file uploads

framework/src/play/src/main/java/play/mvc/StatusHeader.java, framework/src/play/src/test/scala/play/mvc/StatusHeaderSpec.scala
=> use Json.mapper().getFactory() instead of creating a new JsonFactory

documentation/manual/about/PlayUserGroups.md
@domdorn founded a user group in Austria.
I put it beneath Berlin and Cologne because Vienna is german speaking as well :wink:
=> Add Play User Group Austria

framework/project/Build.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ClientCookieDecoder.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/mvc/Http.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Backporting #6890 to 2.5.x branch.
=> [2.5.x]: Fix cookie max-age computation

framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
Backports #6851 to Play 2.5.x.
=> [2.5.x]: Preserve headers, cookies, flash and session when gzipping

framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
=> [2.5.x] parses the path and the query string from our uri (#6801) (#6803)

documentation/manual/ModuleDirectory.md, documentation/manual/about/PlayUserGroups.md, documentation/manual/gettingStarted/IDE.md, documentation/manual/gettingStarted/Tutorials.md, documentation/manual/releases/release25/migration25/StreamsMigration25.md, documentation/manual/working/commonGuide/assets/AssetsOverview.md, documentation/manual/working/commonGuide/configuration/SettingsLogger.md, documentation/manual/working/commonGuide/filters/SecurityHeaders.md, documentation/manual/working/commonGuide/production/ConfiguringHttps.md, documentation/manual/working/javaGuide/main/ws/JavaOAuth.md, documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/ws/ScalaOAuth.md, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ClientCookieDecoder.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ClientCookieEncoder.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ServerCookieDecoder.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ServerCookieEncoder.java, framework/src/play/src/main/java/play/mvc/RangeResults.java
Fixes #6797 and #6870.
```bash
cd documentation
sbt validateExternalLinks
```
=> Docs: validate and update external links

documentation/manual/ModuleDirectory.md
Hi,
the play-guard module already has several users, so I thought it might be worth to be included in the module directory. 
Thanks
Simon
=> added play-guard (Scala) to module directory

.travis.yml
Try out https://www.sourceclear.com/
=> Add sourceclear scanning

framework/src/play/src/main/scala/play/api/Configuration.scala
=> [2.5.x]: Remove unnecessary println call

framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/test/scala/play/api/libs/TemporaryFileReaperSpec.scala
Fixes https://github.com/playframework/playframework/issues/6893
=> Prevent reaper from being scheduled in tests

framework/src/play/src/main/scala/play/api/Configuration.scala
Fixes #6907 at the master branch.
See #6908 for 2.5.x branch.
=> Remove unnecessary println call

documentation/manual/releases/release26/migration26/CacheMigration26.md, documentation/manual/releases/release26/migration26/MessagesMigration26.md, documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/releases/release26/migration26/index.toc
1. How to update play and sbt
2. Changes to cache apis
3. Better order of migration steps
=> Add more details to migration guide

.travis.yml
Trying this to see if it improves build stability, since we get an independent VM with their sudo-enabled infrastructure.
=> Switch to Travis sudo-enabled infrastructure

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/Environment.scala
Original PR was https://github.com/playframework/playframework/pull/5405
=> remove notice about not supported logging methods

documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormHelpers.scala, framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
Removes global state from PlayMagicForJava.
=> Fix template magic for java

framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play/src/main/scala/play/api/controllers/Assets.scala
=> [2.5.x] Add immutable header to aggressiveCacheControl

documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormHelpers.scala, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClient.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala, framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/CustomExecutionContext.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala, framework/src/play/src/main/scala/play/api/libs/crypto/CSRFTokenSigner.scala, framework/src/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala, framework/src/play/src/main/scala/play/api/mvc/Handler.scala, framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala, framework/src/play/src/test/scala/play/core/test/Fakes.scala
See https://gist.github.com/wsargent/d72985c3ce8dfca718b3c23a579620a7
=> Fixes bad scala/javadoc

documentation/manual/ModuleDirectory.md
=> [master] Add Scalate as a library for Play support (#6944)

framework/src/play/src/main/scala/play/api/Play.scala
Add `synchronized` block to `Play.stop` and `Play.start` to make sure the current app is accessed correctly across threads.
=> Make Play.start and Play.stop synchronized

documentation/manual/releases/release26/migration26/Migration26.md
Fixes #6980.
https://github.com/playframework/play-iteratees/blob/master/README.md
=> Migration details about play-iteratees being a standalone project

framework/src/play/src/main/scala/play/api/controllers/Assets.scala
This also makes the API consistent with other APIs that define a default of `Mode.Test`. The default Assets controller is likely to be used in testing environments so this makes sense.
=> Use test mode by default in StaticAssetsMetadata

framework/src/play-cache/src/main/java/play/cache/AsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/CacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultAsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultSyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/SyncCacheApi.java, framework/src/play-cache/src/main/scala/play/api/cache/AsyncCacheApi.scala, framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala, framework/src/play-cache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala, framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala, framework/src/play-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
Fixes #4757 
We have added clearAll function in cacheApi to remove all cached item at once. 
#5912 
#4757
=> Added clear all function to cacheApi to remove all cached items.

framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/main/scala/play/api/mvc/Action.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
Fixes https://github.com/playframework/playframework/issues/6995
=> Add stub controller components

framework/src/play-cache/src/main/java/play/cache/AsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/CacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultAsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultSyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/SyncCacheApi.java, framework/src/play-cache/src/main/scala/play/api/cache/AsyncCacheApi.scala, framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala, framework/src/play-cache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala, framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala, framework/src/play-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
Reverts playframework/playframework#6985
=> Revert "Added clear all function to cacheApi to remove all cached items."

documentation/manual/releases/release26/Highlights26.md
Add twirl injectable templates to the 2.6 highlights
Also see https://github.com/playframework/twirl/pull/135
=> Add injectable templates to highlights

documentation/manual/releases/release25/migration25/Migration25.md
=> [2.5.x] Add note to Migration25 about Lucidchart blog (#7008)

.gitignore
VS Code is becoming more popular and I'm trialling it now. This tiny commit tells Git to ignore the files VS Code adds to the root directory of the repository.
=> Ignore files created by Visual Studio code editor

framework/src/play/src/main/scala/play/api/http/StandardValues.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala
=> Fix logging on redirects and add status utility methods

documentation/manual/working/javaGuide/main/forms/JavaFormHelpers.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/helpers.scala.html, documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/repeat.scala.html, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play/src/main/scala/views/helper/Helpers.scala
Because I needed it just now and people did ask for it in the past as well...
https://groups.google.com/d/topic/play-framework/FIHBAS6qNms/discussion
https://groups.google.com/d/topic/play-framework/knA9AzU7i3Q/discussion
...I thought it would be nice to have it built-in.
=> Add @helper.repeatWithIndex(...) template helper

documentation/manual/working/javaGuide/main/forms/JavaFormHelpers.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/helpers.scala.html, documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/repeat.scala.html, framework/src/play-java/src/test/scala/play/data/FormSpec.scala, framework/src/play/src/main/scala/views/helper/Helpers.scala
=> [2.5.x] Add @helper.repeatWithIndex(...) helper

framework/src/play-ws/src/test/scala/play/api/libs/ws/ning/NingConfigSpec.scala
Build for branch 2.4.x is failing. This fix the test that is causing the failure.
=> [2.4.x]: Fix build test

documentation/manual/working/commonGuide/build/SBTSubProjects.md, documentation/manual/working/javaGuide/main/sql/JavaDatabase.md, documentation/manual/working/scalaGuide/main/sql/ScalaDatabase.md
Upgrade mysql connector java to 5.1.41
=> Update mysql connector java to  5.1.41

framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClient.scala, framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java/src/main/java/play/routing/RoutingDslComponents.scala, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala, framework/src/play/src/main/scala/play/api/mvc/Action.scala, framework/src/play/src/main/scala/play/api/mvc/Handler.scala
Some minor cleanup in `publishLocal` warnings.
=> Clean up some warnings in doc

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
Fixes #4878.
As suggested by @gmethvin (https://github.com/playframework/playframework/issues/4878#issuecomment-125174212), `HEAD` request against ws endpoints will now respond with a Bad Request (`400`).
=> [2.5.x]: WebSocket endpoints returning 400 for HEAD requests

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala, framework/src/play/src/main/scala/play/api/GlobalSettings.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
Related to #4878.
Backport of #7057 to branch 2.4.x.
=> [2.4.x]: WebSocket endpoints returning 400 for HEAD requests

documentation/manual/releases/release25/migration25/Migration25.md
=> Typo fixed from CRSF.getToken to CSRF.getToken

documentation/manual/working/commonGuide/filters/SecurityHeaders.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
Adds referrer-policy to the list of security headers.
See https://scotthelme.co.uk/a-new-security-header-referrer-policy/ for more information.
=> Adds referrer policy security header

framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
This should allow people to use the helpers to run tests in parallel automatically, as long as they disable global state.
Not sure how much configurability is needed here. This retains the existing functionality for those using global state so it shouldn't break existing apps.
=> Only use PlayRunners.mutex for apps with global app enabled

documentation/manual/working/commonGuide/build/code/SubProjectsAssetsBuilder.scala, documentation/manual/working/commonGuide/configuration/code/ThreadPools.scala, documentation/manual/working/commonGuide/filters/code/GzipEncoding.scala, documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/controllers/Application.scala, documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala, documentation/manual/working/scalaGuide/advanced/routing/code/ScalaSirdRouter.scala, documentation/manual/working/scalaGuide/advanced/routing/code/SirdAppLoader.scala, documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/controllers/BinderApplication.scala, documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/controllers/Users.scala, documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala, documentation/manual/working/scalaGuide/main/forms/code/ScalaCsrf.scala, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, documentation/manual/working/scalaGuide/main/tests/code/tests/guice/ScalaGuiceApplicationBuilderSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala, documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala, documentation/manual/working/scalaGuide/main/upload/code/scalaguide.upload.fileupload.routes, documentation/manual/working/scalaGuide/main/upload/code/scalaguide/templates/views/uploadForm.scala.html, documentation/manual/working/scalaGuide/main/xml/code/ScalaXmlRequests.scala, framework/src/play-test/src/main/java/play/test/Helpers.java
Remove some more deprecated APIs calls from the documentation and sample code.
=> Remove some more deprecated api usage from docs

documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java, documentation/manual/working/scalaGuide/main/http/ScalaActionsComposition.md, documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala, framework/src/play-cache/src/main/java/play/cache/Cached.java, framework/src/play/src/main/java/play/mvc/Security.java
Fixes #5815.
Most of the documentation was already updated with examples using Dependency Injection. This just add some small points to make it more clear and complete.
=> Make clear that action composition can use Dependency Injection

documentation/manual/working/commonGuide/configuration/ApplicationSecret.md
The command as written right now doesn't actually run for me. I found that changing it to single quotes fixed the issue
=> Change double quotes to single quotes to fix command

documentation/manual/releases/release26/migration26/JavaConfigMigration26.md, documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/releases/release26/migration26/index.toc
Improve the migration guide with information about Java Configuration API changes.
See discussion here:
https://groups.google.com/forum/#!msg/play-framework/PInYQIyQ32M/Ev7CDs4hBwAJ
=> Docs about the changes in Java Configuration API

framework/src/play-java/src/main/java/play/libs/Classpath.java, framework/src/play-java/src/main/java/play/libs/Time.java, framework/src/play-java/src/main/java/play/libs/XPath.java, framework/src/play-java/src/main/java/play/routing/RoutingDsl.java, framework/src/play-java/src/test/java/play/libs/TimeTest.java
Don't think this actually changed functionality.
This is not related to any issue.
I dive into the source code every now and then to look up how things are done and I recently found a small thing where I thought "that's not the ideal way to use a for loop". Seeing as how reading the source code had been helpful for me, I thought I'd do some static analysis, find some stuff to clean up and then submit said cleanup. Kinda like the boy scout rule, which is mentioned in the 'contributing' page.
This PR limits itself to the `play-java` sub-project.
No references
So yeah. general cleanup. It makes the code a bit cleaner. I fully understand if you're all like "we don't actually need this right now".
Things that changed:
* \* imports changed to fully qualified imports.
* Seemingly pointless …
=> Static analysis of play-java subproject.

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
This is a first stab at the lowest-hanging fruits for improving akka-http backend performance in play (we have a few more ideas).
Two things in here:
* don't generate a `Content-Length: 0` header for GET requests => `BodyParser.default` will now correctly detect that a GET request has no body and return a `DoneAccumulator` => this will prevent any expensive stream logic to run for any GET requests => throughput more than doubles for this very common case
* optimize `DoneAccumulator` to prevent scheduling combinator callbacks if the given Future has already been successfully completed, on top of the other change this improves throughput for me by another 5-10% and also simplifies profiling a lot as regular stacktraces become much simpler than before
=> First akka-http backend performance improvement

.gitignore, .travis.yml, framework/build.sbt, framework/project/Dependencies.scala, framework/src/run-support/src/main/scala/play/runsupport/AssetsClassLoader.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/run-support/src/main/scala/play/runsupport/ServerStartException.scala
This is the first step towards supporting Maven + Play along with https://github.com/playframework/playframework/pull/7093
=> Remove SBT dependency from reloader

documentation/manual/releases/Releases.md
Added an explanation of the Play versioning scheme and API compatibility guarantees.
=> Update Play releases page to explain versioning and API compatibility

framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
This refactors `Form.bind` method into a set of smaller and more digestible methods.
Follow up of the work done by @mkurz in #7038. See discussion there about this refactoring.
=> Refactoring forms

documentation/manual/releases/release26/Highlights26.md
Expand on the Highlights26.md document.
=> Add more info to highlights

framework/project/Dependencies.scala
=> update dependencies related to webdriver

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play/src/main/java/play/mvc/Http.java
```
[warn] /home/travis/build/playframework/playframework/framework/src/play/src/main/java/play/mvc/Http.java:1987: warning: no @param for name
[warn]         public Cookie(String name, String value, Integer maxAge, String path,
[warn]                ^
[warn] /home/travis/build/playframework/playframework/framework/src/play/src/main/java/play/mvc/Http.java:1987: warning: no @param for value
[warn]         public Cookie(String name, String value, Integer maxAge, String path,
[warn]                ^
[warn] /home/travis/build/playframework/playframework/framework/src/play/src/main/java/play/mvc/Http.java:1987: warning: no @param for maxAge
[warn]         public Cookie(String name, String value, Integer maxAge, String path,
[warn]                ^
[warn] …
```
=> Fix javadoc warnings

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
Turns out my impl from yesterday was fine, just that something else on my other WIP branch was causing a failure.
This unblocks us from upgrading to Akka 2.5 and the new materialzer with it 👍
=> Rewrite CSRF BodyParser, unlock upgrading to Akka 2.5

framework/src/play-integration-test/src/test/scala/play/it/action/EssentialActionSpec.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala
On top of the `hasBody` change this removes unncessary scheduling of
future combinator code. It should bring an additional 5-10% increase of
throughput in the request-without-body case.
=> Optimize DoneAccumulator to bypass dispatcher in the happy strict case

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
It looks like Logback has some internal state that causes NPE on the build server. 
Still not sure what is causing this, but we can at least flag it as a known problem.
=> Add exception to track down Logback error

framework/src/play-test/src/main/java/play/test/Helpers.java
=> Add Helpers.httpContext method for creating new Http.Context

documentation/manual/working/javaGuide/code/MockJavaAction.scala, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/CSRFErrorHandler.java, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala, framework/src/play-jdbc-api/src/main/java/play/db/Database.java, framework/src/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play/src/main/java/play/Application.java, framework/src/play/src/main/java/play/DefaultApplication.java, framework/src/play/src/main/java/play/http/DefaultHttpRequestHandler.java, framework/src/play/src/main/java/play/http/HandlerForRequest.java, framework/src/play/src/main/java/play/inject/DelegateInjector.java, framework/src/play/src/main/java/play/inject/Injector.java, framework/src/play/src/main/java/play/mvc/BodyParser.java, framework/src/play/src/main/java/play/mvc/BodyParsers.java, framework/src/play/src/main/java/play/mvc/Filter.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala, framework/src/play/src/main/scala/play/api/inject/Injector.scala, framework/src/play/src/main/scala/play/api/mvc/Action.scala, framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/main/scala/play/core/j/JavaHttpRequestHandlerAdapter.scala, framework/src/play/src/main/scala/play/core/j/JavaRouterAdapter.scala
Fixes #5722
This adds some missing conversions between Java and Scala types. This issue is also one of the steps to have Java components.
=> More consistent asJava and asScala methods

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, framework/build.sbt, framework/project/Dependencies.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-akka-http-server/src/test/resources/application.conf, framework/src/play-akka-http-server/src/test/scala/play/AkkaTestServer.scala, framework/src/play-netty-server/src/test/resources/application.conf, framework/src/play-netty-server/src/test/scala/play/NettyTestServer.scala
Depends on https://github.com/playframework/playframework/pull/7153
Then rebase and apply.
Putting it into the validation queue though right away
=> Update Akka to 2.5.0-RC2

.travis.yml, srcclr.yml
Adding beta sourceclear support to master.
=> Add sourceclear

framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
=> Keep form.data() backward compatible but introduce rawData()

framework/src/play-guice/src/main/java/play/inject/guice/GuiceApplicationLoader.java, framework/src/play-integration-test/src/test/java/play/routing/CompileTimeInjectionRoutingDslTest.java, framework/src/play-java-jdbc/src/main/java/play/db/ConnectionPool.java, framework/src/play-java-jdbc/src/main/java/play/db/DefaultConnectionPool.java, framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/java/play/Environment.java, framework/src/play/src/main/java/play/http/HttpErrorHandler.java, framework/src/play/src/main/java/play/i18n/Langs.java, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/i18n/MessagesImpl.java, framework/src/play/src/main/java/play/inject/ApplicationLifecycle.java, framework/src/play/src/main/java/play/inject/DelegateApplicationLifecycle.java, framework/src/play/src/main/java/play/libs/Files.java, framework/src/play/src/main/java/play/libs/crypto/CookieSigner.java, framework/src/play/src/main/java/play/libs/crypto/HMACSHA1CookieSigner.java, framework/src/play/src/main/java/play/mvc/FileMimeTypes.java, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala, framework/src/play/src/main/scala/play/api/Environment.scala, framework/src/play/src/main/scala/play/api/http/FileMimeTypes.scala, framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/i18n/Langs.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala, framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/main/scala/play/api/libs/crypto/CookieSigner.scala, framework/src/play/src/main/scala/play/core/ApplicationProvider.scala
Follow up for #7163 and #5722.
=> Add missing asJava/asScala conversion

framework/src/play/src/main/scala/play/api/controllers/Assets.scala
It seems to make more sense for `AssetsMetadata` to contain and provide an `AssetsFinder` rather than extending it. This way we avoid type conflicts when using Macwire and it's harder to accidentally use one instead of the other.
=> Use composition instead of inheritance for AssetsFinder/AssetsMetadata

framework/project/Dependencies.scala
Fixes Issue #7169
See details/discussion on the issue's page
=> Upgrade logback dependency to fix 5 secs delays in unittests

framework/project/Dependencies.scala
We upgraded to 1.2.3 in the 2.5.x branch. Should make master match
=> Upgrade logback to 1.2.3

documentation/manual/releases/release26/Highlights26.md, documentation/manual/releases/release26/migration26/Migration26.md, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java, framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaHttpHandlerSpec.scala, framework/src/play-java/src/test/java/play/mvc/AttributesTest.java, framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/java/play/mvc/Security.java, framework/src/play/src/main/scala/play/api/mvc/Request.scala, framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/main/scala/play/core/routing/GeneratedRouter.scala, framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala, framework/src/play/src/test/scala/play/api/mvc/RequestSpec.scala, framework/src/play/src/test/scala/play/core/test/Fakes.scala
This PR resolved #7016.
@richdougherty please take a look. 
I will be happy if you can suggest what can be improved since I've just started to learn Scala. (btw, thanks for the handy `newbie` label)
=> allows to attach single attribute to the request

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
If you run several integration tests in parallel, then logback configuration will
die in interesting ways as the configuration is not thread-safe.
Adds synchronized block on LogbackLoggerConfigurator.
=> Fix NPE in LogbackLoggerConfigurator

framework/project/Dependencies.scala
so we can have the latest on 2.5.14
=> [2.5.x] Upgrade akka and akka-http

documentation/manual/hacking/Translations.md, documentation/manual/releases/release26/migration26/Migration26.md, documentation/project/build.properties, framework/project/Dependencies.scala, framework/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/project/build.properties
See:
1. http://developer.lightbend.com/blog/2017-04-10-sbt-01315-JDK9-support-and-offline-installation/
2. http://www.scala-sbt.org/0.13/docs/sbt-0.13-Tech-Previews.html#sbt+0.13.15
=> Update to sbt 0.13.15

framework/project/plugins.sbt, framework/project/project/buildinfo.sbt
The version of sbt-buildinfo in this project is outdated, so it should be upgrade to latest version.
This bumped the version of sbt-buildinfo to `0.6.1`.
- [official migration guide of sbt-buildinfo](https://github.com/sbt/sbt-buildinfo/blob/master/Migration.md)
=> Upgrade sbt-buildinfo to latest version

framework/src/play-integration-test/src/test/java/play/routing/RoutingDslTest.java, framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
This has been backported from #7214, and I've raised a PR rather than backporting directly because the backport wasn't trivial.
=> Include changes to Http.Context in Result from RoutingDsl

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
This will be one of the APIs that will support Http2 in the future.
=> Change Akka Http backend to use Http().bindAndHandleAsync

documentation/manual/working/commonGuide/production/Deploying.md
Fixes #7217
Backports #7227 to branch 2.5.x.
=> [2.5.x]: Backport #7227

documentation/manual/ModuleDirectory.md
This PR adds informations about a new plugin I wrote "play-webpack", see https://github.com/BowlingX/play-webpack.
=> added play-webpack plugin informations

framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/test
=> [2.5.x] Make it possible to disable the reverse router

documentation/manual/working/javaGuide/main/sql/JavaDatabase.md
Fixes outdated documentation.
From https://groups.google.com/d/msg/play-framework/HlpHPEyPbrU/q_BJYQNtAgAJ
=> [doc] Replace DB.getConnection with db.getConnection

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala, framework/src/iteratees/src/main/scala/play/api/libs/iteratee/Enumerator.scala, framework/src/iteratees/src/test/scala/play/api/libs/iteratee/EnumeratorsSpec.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala, framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/KeyStore.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/SSLContextBuilder.scala, framework/src/play-ws/src/test/scala/play/api/libs/ws/ssl/ConfigSSLContextBuilderSpec.scala, framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala, framework/src/play/src/main/scala/play/utils/PlayIO.scala, framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala, framework/src/play/src/test/scala/play/libs/XMLSpec.scala, framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
Backports #7244 to branch 2.5.x.
=> [2.5.x]: Backport "Remove FileInputStream/FileOutputStream"

documentation/manual/releases/release26/migration26/Migration26.md, framework/project/Dependencies.scala
Bumps fluentlenium from 3.1.1 to 3.2.0
=> Update fluentlenium to 3.2.0

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
Resolves #7256, I have verified on the reporters reproducer however would be good to add a test covering this too I guess
=> =pfh #7256 fix illegal double push in CSRF handler rewrite

documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
Fixes a wrong URL in the documentation 
* I have  signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)
=> [doc] Corrected URL to match the example

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWSSpec.scala, documentation/manual/working/scalaGuide/main/ws/ScalaWS.md, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Add example of timeout to Play WS and Scala WS pages.
=> [doc] Update WS timeout with examples

framework/project/Dependencies.scala
Updates sbt-web (and plugins) dependencies, since we already made some releases already. This is related to issue #7045.
=> Update sbt-web dependencies

framework/project/Dependencies.scala
Akka HTTP 10.0.6 released: http://akka.io/news/2017/05/03/akka-http-10.0.6-released.html
=> Upgrade to Akka HTTP 10.0.6

documentation/manual/working/commonGuide/configuration/ThreadPools.md
Typo  "You should se your changes.." =>  "You should see your changes.."
Fixes #xxxx
=> Typo  "You should se your changes.." =>  "You should see your changes.."

documentation/manual/releases/release26/migration26/MessagesMigration26.md, framework/src/play/src/main/scala/play/api/i18n/Langs.scala
Fixes https://github.com/playframework/playframework/issues/7317
=> Remove implicit from defaultLang

documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md
There was an error in line 85 so I changed "It" to "In"
Fixes #xxxx
=> Line 85, changed "It" to "In"

framework/build.sbt, framework/src/play-filters-helpers/src/main/scala/play/api/test/CSRFTokenHelper.scala
Takes out a dependency and reference to FakeRequest for type enrichment.
=> Remove Filters dependency on Play-Test

documentation/manual/working/scalaGuide/main/application/ScalaHttpFilters.md, documentation/manual/working/scalaGuide/main/application/code/AccumulatorFlowFilter.scala
Adds an example of using Accumulator with `through` to show usage of Flow.
=> [doc] Add accumulator flow example

documentation/manual/releases/release23/Highlights23.md, documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/commonGuide/configuration/ThreadPools.md, documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/javaGuide/main/sql/JavaJPA.md, documentation/manual/working/scalaGuide/advanced/iteratees/Enumeratees.md, documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md, documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
Forward port changes made at #7321 and #7305 to master branch. Also correct some other typos.
=> Correct some typos

framework/project/plugins.sbt
Replace deprecated java Docker container with openjdk
https://github.com/sbt/sbt-native-packager/releases
=> Upgrade sbt-native-packager version.

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
I noticed we had no tests for clearing the session in the Java API.
=> Add test for session clear

framework/src/play-java-jdbc/src/test/java/play/db/DatabaseTest.java, framework/src/play-jdbc/src/main/resources/jndi.properties, framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala, framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala, framework/src/play/src/main/scala/play/api/libs/JNDI.scala
=> Fix JNDI initial context initialization

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/commonGuide/assets/AssetsOverview.md
=> Add AssetsComponents to migration guide

documentation/manual/gettingStarted/PlayConsole.md, documentation/manual/working/commonGuide/production/ProductionConfiguration.md, documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
=> Fix docs to correct state Akka HTTP as the default server

documentation/manual/working/javaGuide/main/tests/JavaTestingWithDatabases.md, documentation/manual/working/javaGuide/main/tests/code/javaguide.tests.databases.sbt, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithDatabases.md, documentation/manual/working/scalaGuide/main/tests/code/database/databases.sbt
Fixes #7309 
To improve documentation about testing with databases
=> Added dependency to documentation about testing with database

framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java
=> [2.5.x] Make sure context.withRequest maintains original session and flash

documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/views/html/formTemplate.scala, documentation/manual/working/scalaGuide/main/tests/code/views/html/formTemplateWithCSRF.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
Fixes https://github.com/playframework/playframework/issues/7333
=> Add form helper stubs

framework/project/Build.scala, framework/project/Dependencies.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/AkkaStreams.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/GzipFlow.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/Probes.scala, framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/main/scala/play/core/formatters/Multipart.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
This backports several PRs (#6157, #6774, #7153, #7257) to the 2.5.x branch, to enable compatibility with Akka 2.5.
=> [2.5.x] Unlock Akka 2.5 upgrade

documentation/manual/ModuleDirectory.md, documentation/manual/working/commonGuide/index.toc, documentation/manual/working/commonGuide/schedule/ScheduledTasks.md, documentation/manual/working/commonGuide/schedule/code/javaguide/scheduling/CodeBlockOnceTask.java, documentation/manual/working/commonGuide/schedule/code/javaguide/scheduling/CodeBlockTask.java, documentation/manual/working/commonGuide/schedule/code/javaguide/scheduling/MyActorTask.java, documentation/manual/working/commonGuide/schedule/code/javaguide/scheduling/MyBuiltInComponentsFromContext.java, documentation/manual/working/commonGuide/schedule/code/javaguide/scheduling/TasksCustomExecutionContext.java, documentation/manual/working/commonGuide/schedule/code/javaguide/scheduling/TasksModule.java, documentation/manual/working/commonGuide/schedule/code/scalaguide/scheduling/CodeBlockTask.scala, documentation/manual/working/commonGuide/schedule/code/scalaguide/scheduling/MyActorTask.scala, documentation/manual/working/commonGuide/schedule/code/scalaguide/scheduling/MyBuiltInComponentsFromContext.scala, documentation/manual/working/commonGuide/schedule/code/scalaguide/scheduling/TasksCustomExecutionContext.scala, documentation/manual/working/commonGuide/schedule/code/scalaguide/scheduling/TasksModule.scala, documentation/manual/working/commonGuide/schedule/index.toc, documentation/manual/working/javaGuide/main/akka/JavaAkka.md, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java, documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md, documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala
Fixes #7322.
Add documentation about how to schedule recurring tasks out-of-the-box. Also add a new module section to list task schedulers.
=> Add docs about how to schedule tasks

framework/src/play/src/main/java/play/libs/concurrent/Timeout.java, framework/src/play/src/main/scala/play/api/libs/concurrent/CustomExecutionContext.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Futures.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala
Fixes https://github.com/playframework/playframework/issues/7240
Also fixes some outdated documentation in Futures.
=> Add Timeout and make it deprecated

documentation/manual/working/javaGuide/main/cache/JavaCache.md, documentation/manual/working/javaGuide/main/cache/code/cache.sbt, documentation/manual/working/scalaGuide/main/cache/ScalaCache.md, documentation/manual/working/scalaGuide/main/cache/code/cache.sbt, framework/build.sbt, framework/src/play-jcache/src/main/java/play/libs/jcache/JCacheComponents.java, framework/src/play-jcache/src/main/resources/reference.conf, framework/src/play-jcache/src/main/scala/play/api/libs/jcache/JCacheComponents.scala, framework/src/play-jcache/src/main/scala/play/api/libs/jcache/JCacheModule.scala, framework/src/play-jcache/src/test/scala/play/api/libs/jcache/JCacheSpec.scala
Adds bindings for `CacheManager`
=> JCache module implementation

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/commonGuide/server/AkkaHttpServer.md
Updates the highlights and the AkkaHttpServer docs about HTTP/2.
=> Add HTTP/2 to highlights

documentation/manual/working/scalaGuide/advanced/iteratees/Enumeratees.md, documentation/manual/working/scalaGuide/advanced/iteratees/Enumerators.md, documentation/manual/working/scalaGuide/advanced/iteratees/Iteratees.md
=> Add note about play iteratees as a standalone project

framework/project/Dependencies.scala, framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
Update play-ws to release candidate 1.
=> Update play-ws to RC1

framework/src/play/src/main/scala/play/core/j/JavaAction.scala
This just got added I'm guessing by mistake. Feel free to close if it was added purposefully
=> Remove semicolon at end of comment

framework/src/play/src/main/java/play/LoggerConfigurator.java
Some javadoc lint errors in the build.
=> Fix loggerconfigurator javadoc

framework/src/play/src/main/java/play/libs/concurrent/DefaultFutures.java, framework/src/play/src/main/java/play/libs/concurrent/Futures.java, framework/src/play/src/main/java/play/libs/concurrent/Timeout.java, framework/src/play/src/main/scala/play/api/libs/concurrent/Futures.scala, framework/src/play/src/test/java/play/libs/concurrent/FuturesTest.java, framework/src/play/src/test/scala/play/api/libs/concurrent/FuturesSpec.scala
For @richdougherty per https://github.com/playframework/playframework/pull/7381#pullrequestreview-39891391
=> Add futures.delay()

documentation/manual/working/commonGuide/filters/CorsFilter.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
Fixes #5193 
Backports #6580 to branch 2.5.x.
=> [2.5.x]: Add a CORS config param to allow pass-through of forbidden origins (backports #6580)

framework/build.sbt, framework/project/Dependencies.scala
Update Akka HTTP to version 10.0.7 and remove snapshot resolvers.
=> Update akka-http to 10.0.7

documentation/manual/working/commonGuide/database/Evolutions.md, documentation/manual/working/commonGuide/database/code/CompileTimeDIEvolutions.scala
What does this PR do? Makes the documentation around running evolutions with compile time DI a little clearer. Describes what imports and dependencies are necessary to make it work.
=> improve documentation for running evolutions using compile-time DI

framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
executionContent -> executionContext
=> executionContent -> executionContext

documentation/manual/releases/release26/Highlights26.md, documentation/manual/releases/release26/migration26/Migration26.md
=> Improve highlights and migration guide for play-json

documentation/manual/working/commonGuide/configuration/SettingsLogger.md
Applies changes from #7420 on `master`.
=> [master] Fixed appender references (#7420)

documentation/manual/working/javaGuide/main/i18n/JavaI18N.md, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/MyService.java, documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md, documentation/manual/working/scalaGuide/main/i18n/code/ScalaI18N.scala, documentation/manual/working/scalaGuide/main/i18n/code/scalaguide/i18n/ScalaI18nService.scala
For both Java and Scala versions.
=> [docs]: Extract code samples for I18n documentation

documentation/manual/working/javaGuide/main/async/JavaStream.md, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, documentation/manual/working/scalaGuide/main/async/ScalaStream.md, documentation/manual/working/scalaGuide/main/async/code/ScalaAsync.scala, documentation/manual/working/scalaGuide/main/async/code/ScalaComet.scala, documentation/manual/working/scalaGuide/main/async/code/scalaguide/async/scalastream/ScalaStream.scala
For both Java and Scala. Also, tries to keep both the docs in sync. Java docs were lacking some sections that are present in Scala's.
=> [docs]: Update async actions docs

documentation/manual/releases/release26/migration26/MessagesMigration26.md
The migration document was written before MessagesAbstractController was added.  Revised so that it is included.
=> Update messages migration with MessagesAbstractController

documentation/manual/releases/release26/migration26/JavaConfigMigration26.md
This corrects a small error in the code and rewords for clarity.
=> Make some clarifications to Java config migration guide

documentation/manual/working/javaGuide/main/i18n/JavaI18N.md, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java, documentation/manual/working/javaGuide/main/tests/JavaTest.md, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/MessagesTest.java, documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md, documentation/manual/working/scalaGuide/main/i18n/code/ScalaI18N.scala, documentation/manual/working/scalaGuide/main/i18n/code/scalaguide/i18n/ScalaI18nService.scala, documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleMessagesSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play/src/main/scala/play/api/i18n/Langs.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Fixes https://github.com/playframework/playframework/issues/7306
The documentation was missing references to MessagesRequest and the stubs.
Also found a couple of implicit conversion that were missing and some awkwardness in the Java construction.
=> Fill out the i18n documentation with tests

framework/project/Dependencies.scala, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSModule.scala
=> Upgrade to play-ws 1.0.0

framework/src/play-integration-test/src/test/scala/play/it/auth/SecuritySpec.scala, framework/src/play/src/main/scala/play/api/mvc/Security.scala
Fixes https://github.com/playframework/playframework/issues/7398 by updating the Javadoc and adding more tests.
=> Update AuthenticatedBuilder javadoc

documentation/manual/gettingStarted/Installing.md, documentation/manual/working/commonGuide/build/SBTDependencies.md, documentation/manual/working/commonGuide/build/code/dependencies.sbt
This is a small follow up after #6623.
=> [docs]: Small improvements of sbt docs

framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-java-ws/src/test/scala/play/libs/ws/ahc/AhcWSRequestSpec.scala
Fixes https://github.com/playframework/playframework/issues/7444
=> [2.5.x] Fix url encoded query parameter in WSRequest

documentation/manual/releases/release26/migration26/Migration26.md
Explain in detail what each filter does and what to do about it.
=> Add notes to migration about filters

documentation/manual/working/javaGuide/main/cache/JavaCache.md, documentation/manual/working/scalaGuide/main/cache/ScalaCache.md, framework/src/play-cache/src/main/java/play/cache/AsyncCacheApi.java, framework/src/play-cache/src/main/scala/play/api/cache/AsyncCacheApi.scala, framework/src/play-ehcache/src/test/scala/play/api/cache/ehcache/EhCacheApiSpec.scala
Clarifies what the `removeAll` method is for and how to use it.
=> Update CacheApi docs and fix test

documentation/manual/working/commonGuide/filters/AllowedHostsFilter.md, documentation/manual/working/commonGuide/filters/Filters.md, documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
Fill out the Java CSRF documentation and add HttpExecutionContext as a thing, rather than calling Controller.request()
=> Add more links and docs to java csrf

framework/src/play-joda-forms/src/main/scala/play/api/data/JodaForms.scala, framework/src/play-joda-forms/src/main/scala/play/api/data/format/JodaFormats.scala
=> move play-joda-forms files to correct location

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
Add more CSRF documentation, fill out migration classes with links and fix some broken links
=> Add more links and docs

documentation/manual/releases/release26/migration26/Migration26.md
Fixes #7481
Fix Akka migration link in Play Framework 2.6 migration guide
=> Fix Akka migration link

documentation/manual/releases/release26/Highlights26.md
Swapping two code blocks and labeling them for consistency
The other code blocks show the Java example before the Scala example and explicitly label them as such. This example was in a different order and did not label the language.
It's a minor thing and something that isn't all that hard to figure out for the average reader though.
=> Make code examples consistent

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java
=> Fix max-age when converting from Java to Scala cookie

documentation/manual/releases/release26/Highlights26.md, documentation/manual/releases/release26/migration26/JavaConfigMigration26.md, documentation/manual/releases/release26/migration26/MessagesMigration26.md, documentation/manual/releases/release26/migration26/Migration26.md
Fixing typos and various styling issues in the migration docs
Tried to fix everything I noticed while reading through the migration docs.
=> 2.6 Migration docs fixups

documentation/manual/releases/release26/Highlights26.md
=> Fix example

documentation/manual/releases/release26/migration26/Migration26.md
Looks like these links were broken and must be fixed
=> Fix broken markdown in Migration26.md

documentation/manual/releases/release26/Highlights26.md, documentation/manual/releases/release26/migration26/JavaConfigMigration26.md, documentation/manual/releases/release26/migration26/MessagesMigration26.md, documentation/manual/releases/release26/migration26/Migration26.md
=> 2.6 Migration docs fixups (backports #7486)

documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
=> [2.6.x]: Improvements to RedirectHttpsFilter

documentation/manual/releases/release26/migration26/Migration26.md
* Update `Migration26.md`: add GET HTTP method in the routes.
=> Update Migration26.md: add HTTP method in routes.

documentation/manual/releases/release26/Highlights26.md
Good to have in our highlights.
=> Add Scala 2.12 support to 2.6 hightlights

framework/project/Dependencies.scala
=> Update to sbt-javaagent 0.1.3

framework/bin/checkBinaryCompatibility, framework/bin/travis, framework/project/BuildSettings.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
So we can explicitly see/control differences from 2.6.x.
=> Add MiMa check for master

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/javaGuide/main/logging/JavaLogging.md, documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaMarkerController.java, documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaTracerController.java, documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
* Fill out the java logging section to match scala logging
* Fix the implicit request in RequestMarkerContext
=> [doc] Expand on logging documentation

framework/project/Dependencies.scala
Fixes https://github.com/playframework/playframework/issues/7422
=> Add SLF4J simple to SBT-Plugin

documentation/manual/releases/release26/migration26/Migration26.md
Backport on `master` of https://github.com/playframework/playframework/pull/7531
=> Correct import for Joda time json Reads and Writes

framework/project/Dependencies.scala
Backport #7528
```
cd 2.6.x
git checkout -b backport-7528
hub am -3 https://github.com/playframework/playframework/pull/7528
git push origin backport-7528
hub pull-request -b 2.6.x
```
=> [2.6.x] Add SLF4J simple to SBT-Plugin

framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
Backports https://github.com/playframework/playframework/pull/7530 to 2.6.x branch
=> [2.6.x] Add better error message to invalid JWT cookie

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/javaGuide/main/logging/JavaLogging.md, documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaMarkerController.java, documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaTracerController.java, documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
Backport of https://github.com/playframework/playframework/pull/7510
* Expand on logging documentation
* more specific link
* Fix snippet links
* Add links
=> [2.6.x] [doc] Expand on logging documentation

.travis.yml, framework/bin/whitesource, framework/build.sbt, framework/project/plugins.sbt
Add integration with Whitesource.com.
See also playframework/interplay#25 and [sbt-whitesource](https://github.com/typesafehub/sbt-whitesource).
=> [2.6.0]: Add whitesource support

.travis.yml, framework/bin/whitesource, framework/build.sbt, framework/project/plugins.sbt
Add integration with Whitesource.com **in master branch**.
See playframework/interplay#25 and [sbt-whitesource](https://github.com/typesafehub/sbt-whitesource).
Also, see PR for other branches:
1. #7524 for 2.6.x
2. #7527 for 2.5.x
=> [master]: Add whitesource support

framework/project/Dependencies.scala
See http://akka.io/blog/news/2017/06/26/akka-http-10.0.9-released.
=> Update akka-http to version 10.0.9

documentation/manual/releases/release26/migration26/JPAMigration26.md, framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
Backport https://github.com/playframework/playframework/pull/7540
=> [2.6.x] Deprecate static JPA class

framework/src/play-integration-test/src/test/scala/play/it/http/parsing/ByteStringBodyParserSpec.scala, framework/src/play/src/main/java/play/mvc/BodyParser.java, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/test/scala/play/api/mvc/RawBodyParserSpec.scala
=> [2.6.x]: Added ByteString body parser (#7551)

framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala, framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
=> Use ApplicationLifecycle instead of DefaultApplicationLifecycle

framework/build.sbt
This check is needed for a change introduced by PR #7563. Not sure why the check didn't fail then!
=> Add MIMA exclusion

documentation/manual/releases/release26/migration26/Migration26.md
=> Minor typo in 2.6 Migration page where->were

documentation/manual/releases/release26/migration26/WSMigration26.md, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
=> [doc]: Explain the difference between using play-ws standalone and in a Play project

framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceInjectorBuilderSpec.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/inject/Injector.scala, framework/src/play/src/test/scala/play/api/BuiltInComponentsSpec.scala
=> [2.6.x]: Make sure injector uses application ClassLoader (#7552)

framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-test/src/main/java/play/test/WithApplication.java, framework/src/play-ws/src/main/java/play/libs/ws/WSRequest.java, framework/src/play/src/main/java/play/http/HttpFilters.java, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/java/play/mvc/Results.java, framework/src/play/src/main/java/play/routing/Router.java, framework/src/play/src/main/java/play/server/ApplicationProvider.java
Fixes a number of small deprecation issues I've noticed while removing deprecated code (see #7611).
=> Small deprecation fixes

documentation/manual/working/javaGuide/main/async/JavaWebSockets.md, documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md
Updated WebSocket page for both java and scala
To provide clear documentation to the readers.
For getting a good documentation
=> updated WebSocket Documentation page

documentation/manual/releases/release26/migration26/MessagesMigration26.md, documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, framework/src/play/src/main/scala/play/api/data/Form.scala, framework/src/play/src/main/scala/play/api/data/Forms.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
=> Better explain how default form value works

documentation/manual/releases/release26/migration26/Migration26.md
Backport of https://github.com/playframework/playframework/pull/7602
=> Backport: Explain that updating sbt is required

framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-test/src/main/java/play/test/WithApplication.java, framework/src/play-ws/src/main/java/play/libs/ws/WSRequest.java, framework/src/play/src/main/java/play/http/HttpFilters.java, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/java/play/mvc/Results.java, framework/src/play/src/main/java/play/routing/Router.java, framework/src/play/src/main/java/play/server/ApplicationProvider.java
=> [master]: Small deprecation fixes (#7612)

documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala
=> alias defaultActionBuilder to Action in ws test samples
