playframework/playframework

framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Idle timeout support introduced for 2.4 would cause thread exhaustion because a HashedWheelTimer was being created per request. Instead we should be using a single one. This isn't an issue in 2.5+ because Netty's IdleStateHandler no longer requires a Timer.
=> [2.4] Fix thread leak caused by idle-timeout support

documentation/manual/releases/release26/migration26/Migration26.md
Not related to any issue
Fix documentation in the Migration Guide from 2.5 to 2.6
The `Yaml` class is calling instance fields in static methods.
Since they are calling an instance field they should not be static anymore.
=> Make Yaml methods non static

.travis.yml, framework/bin/travis
Adjusts the build constraints to run Travis CI serially.  We are running into OutOfMemoryErrors and timeouts, and it probably results from running everything in parallel on the same container.
=> Change Travis CI script to run CI test in serial

framework/bin/travis
travis script won't fail on error in a task
however the websocketspec is failing all the time so the script should abort after a failure.
=> fixes the travis script

framework/project/Dependencies.scala
So that the scalaz-stream bintray resolver is not needed
=> upgrade specs2 to 3.6.6

framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala, framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Fixes some deprecated warnings coming from Akka by upgrading to new API.
Replaces FileIO.fromFile with FileIO.fromPath.
Replaces PushStage with GraphStage.
=> Update deprecated Akka calls

framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
Moves the WebSocket ping specs out to a different area and mark them as pendingAsFixed.  
Also added comments to add in debugging this.  I suspect Netty is handling the close itself.
=> Make WebSocket ping specs pendingUntilFixed

framework/bin/travis
Adds back:
```
framework/bin/$TASK "set concurrentRestrictions in Global += Tags.limitAll(1)" 
```
I'm seeing concurrent modification errors in logback, and I think it's from tasks running in parallel.
```
04:01:38,763 |-ERROR in ch.qos.logback.core.joran.spi.Interpreter@4:16 - RuntimeException in Action for tag [configuration] java.util.ConcurrentModificationException
at java.util.ConcurrentModificationException
at 	at java.util.HashMap$HashIterator.nextNode(HashMap.java:1437)
at 	at java.util.HashMap$EntryIterator.next(HashMap.java:1471)
at 	at java.util.HashMap$EntryIterator.next(HashMap.java:1469)
at 	at java.util.HashMap.putMapEntries(HashMap.java:511)
at 	at java.util.HashMap.<init>(HashMap.java:489)
at 	at ch.qos.logback.core.ContextBase.getCopyOfPropertyMap(ContextBase.java:80)
at …
```
=> Add back the sbt concurrent limitations to build

framework/src/play-java-ws/src/main/java/play/test/WSTestClient.java, framework/src/play-ws/src/main/scala/play/api/test/WSTestClient.scala
Fixes the Travis CI build.
This should stop the OOM seen after a few hundred ws-test-client instances:
https://travis-ci.org/playframework/playframework/builds/156315711#L2617
[INFO] [08/30/2016 19:36:16.989] [ws-test-client-163-scheduler-1] [akka.actor.ActorSystemImpl(ws-test-client-163)] starting new LARS thread
=> Ensure actorSystem stops before starting new test

framework/src/play-ws/src/main/scala/play/api/test/WSTestClient.scala
Use a singleton client with an underlying actorsystem, but
makes the actorsystem kill itself if there are no references
and it's been idle for 5 seconds.
=> Make WsTestClient.withClient close on idle

documentation/manual/working/scalaGuide/main/json/ScalaJsonCombinators.md, framework/src/play-json/src/main/scala/play/api/libs/json/JsConstraints.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonValidSpec.scala
Allows to use any type with an ordering for the Json-Combinators `min` and `max`.
For me this allows to use SI units like meter in https://github.com/KarolS/units like Int and Double. Other possible use-cases would be ordered enum types like log levels. (e.g. `(__ \ 'level).read[LogLevel](min(warning))`)
Implementing Numeric is something between awkward (the signature of multiplication makes no sense for meters) and impossible (translation from and to Int for LogLevels?). Luckily we need much less to implement `min` and `max`: [`Ordering`](http://www.scala-lang.org/api/2.11.8/#scala.math.Ordering).
=> Json Reads Validation min and max with ordering

framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala, framework/src/play-netty-server/src/test/scala/play/core/server/netty/NettyModelConversionSpec.scala
This will actually fix the error that will come up with netty 4.0.40.Final.
We don't need to Backport the Netty Decoder since `java.net.URI` is already correct.
Only fails: https://travis-ci.org/playframework/playframework/jobs/157826296#L3011
NettyWebSocketSpec.
=> [2.5.x] fixes the uri encoding/decoding with netty 4.0.40.Final

framework/src/play/src/main/scala/play/api/controllers/Assets.scala
If using external tools to generate the digest of an asset (e.g. md5sum main.css > main.css.md5), it may happen that the tool adds non printable characters (like \n) after the digest.
This results in URLs generated like:
/assets/styles/dc5672cb5071cd31a6fb6d670807161c
-main.css
instead of 
/assets/styles/dc5672cb5071cd31a6fb6d670807161c-main.css
Proposed solution: Trim the digest read from the digest file.
=> Trim digest of asset after reading it. fixes #6538

framework/src/play-json/src/main/scala/play/api/libs/json/jackson/JacksonJson.scala, framework/src/play-json/src/test/scala/play/api/libs/json/JsonSpec.scala
Possible fix for #6530 
Fixes serialization of BigDecimals to json in some particular case which was failing
=> Fixes serialization of big decimals to json (#6530)

documentation/manual/working/javaGuide/main/http/JavaRouting.md, documentation/manual/working/javaGuide/main/http/code/javaguide.http.routing.defaultcontroller.routes, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaRouting.scala, documentation/manual/working/scalaGuide/main/http/ScalaRouting.md, documentation/manual/working/scalaGuide/main/http/code/ScalaRouting.scala, documentation/manual/working/scalaGuide/main/http/code/scalaguide.http.routing.defaultcontroller.routes, framework/src/play/src/main/scala/play/api/controllers/Default.scala
I found the `Default` controller useful and thought it'd be good to mention it in the routing documentation. This PR does that, along with some other minor documentation fixes.
=> Document Default controller in routing docs

framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/play/src/main/scala/play/api/mvc/ContentTypes.scala
This PR fixes a typo in `MultipartFormData` where `mdf` should most likely be abbreviated as `mfd`
=> Fix MultipartFormData typo mdf -> mfd

framework/src/play-netty-server/src/main/java/play/core/server/netty/QueryStringDecoder.java, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala, framework/src/play-netty-server/src/test/java/play/core/server/netty/QueryStringDecoderTest.java
Fixes #6551
Fixes #6549
@gmethvin @wsargent This is a Backport of QueryStringDecoder which I proposed here:
https://github.com/netty/netty/pull/5820
This needs a backport against 2.5.x
After this we can also merge: https://github.com/playframework/playframework/pull/6543
I will delay scala-uri WIP for master since I got some questions after working with it the last couple of days.
=> fixes some problems with query strings

documentation/manual/working/scalaGuide/main/json/code/ScalaJsonAutomatedSpec.scala, framework/src/play-functional/src/main/scala/play/api/libs/functional/Functors.scala, framework/src/play-functional/src/main/scala/play/api/libs/functional/Products.scala, framework/src/play-functional/src/main/scala/play/api/libs/functional/syntax/package.scala, framework/src/play-json/src/main/scala/play/api/libs/json/Format.scala, framework/src/play-json/src/main/scala/play/api/libs/json/JsMacroImpl.scala, framework/src/play-json/src/main/scala/play/api/libs/json/JsonConfiguration.scala, framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala, framework/src/play-json/src/test/scala/play/api/libs/json/MacroSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/ReadsSpec.scala, framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala
I've come up with a partial solution to making the JSON macro more robust when handling recursive types. Rather than making a pull request, I wanted to discuss my findings here first, because I don't know how well they will be received.
Suppose we have: 
```
case class Foo(id: Long, value: Either[String, Foo])
```
and some:
```
implicit def eitherReads[A : Reads, B : Reads]: Reads[Either[A, B]] = ???
```
The following macro call will fail from a type-mismatch error:
```
implicit val reads = Json.reads[Foo]
```
After some digging, I found that if the macro determines that the structure is recursive (and not using a nullable call), it will eventually land [here](https://github.com/playframework/playframework/blob/f7e17a7880972b2e6a955e71a7035ae0f7903681/framework/src/play-json/src/main/scala …
=> Limited support for recursive types within Json macro (reads/writes/format)

documentation/manual/working/javaGuide/main/async/JavaAsync.md, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java, documentation/manual/working/scalaGuide/main/async/ScalaAsync.md, documentation/manual/working/scalaGuide/main/async/code/ScalaAsync.scala, framework/src/play/src/main/java/play/libs/concurrent/Futures.java, framework/src/play/src/main/java/play/libs/concurrent/Timeout.java, framework/src/play/src/main/scala/play/api/libs/concurrent/Timeout.scala, framework/src/play/src/test/java/play/libs/concurrent/TimeoutTest.java, framework/src/play/src/test/scala/play/api/libs/concurrent/TimeoutSpec.scala
Fixes https://github.com/playframework/playframework/issues/6400
This PR adds a Timeout trait which replaces the deprecated Promise.timeout method, and provides an implicit class so we can use `future.withTimeout(100 millis)` in a Play app where we know that actorSystem is in context.
We have [Futures.timeout](https://playframework.com/documentation/latest/api/java/play/libs/concurrent/Futures.html#timeout-long-java.util.concurrent.TimeUnit-) in the Java API already, so we don't need to add anything on the Java API side.
Timeout operations are applicable all through Play HTTP requests in the form of `Future[Result]` and `Future[WSResponse]` -- while there are underlying timeouts, it's not well known how to do non-blocking timeouts, and there are multiple instances of applications using …
=> Add Timeout trait to play.api.libs.concurrent

documentation/manual/working/commonGuide/production/Deploying.md
Fixes https://github.com/playframework/playframework/issues/4695
This PR changes the Play doc to reflect sbt-native-packager doc.
Needs backport to 2.5.x docs.
=> [doc] Add note about Play PID in Debian deployment

documentation/manual/experimental/AkkaHttpServer.md, framework/src/play-akka-http-server/src/main/resources/play/reference-overrides.conf, framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala
currently the raw-request-uri-header was never set, even after changing the configuration
since we construct the initial-settings manually, so it always raised "Can't get raw request URI. Please set...'
Unfortunatly the user can't set it by himself
=> polished the akka-http backend

documentation/manual/hacking/Documentation.md, documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala, documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/code/controllers/Application.scala, documentation/manual/working/scalaGuide/main/tests/code/controllers/HomeController.scala, documentation/manual/working/scalaGuide/main/tests/code/specs2/FunctionalExampleControllerSpec.scala, documentation/manual/working/scalaGuide/main/ws/code/ScalaOAuthSpec.scala
Scrubs some more "object Application" references in the documentation.
=> [doc] Remove object controller references

documentation/manual/working/javaGuide/main/ws/JavaWS.md
As in ScalaWS.md, the `## Configuring WS with SSL` should be a level 3 header under `Configuring WS`
See https://www.playframework.com/documentation/2.5.x/ScalaWS#Configuring-WS and https://www.playframework.com/documentation/2.5.x/JavaWS#Configuring-AsyncClientConfig for reference.
=> [doc] Fix incorrect level header in JavaWS

documentation/manual/working/javaGuide/main/ws/JavaWS.md
As in ScalaWS.md, the `## Configuring WS with SSL` should be a level 3 header under `Configuring WS`
=> Fix incorrect level header (#6585)

framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala, framework/src/play-cache/src/test/scala/play/api/cache/CacheApiSpec.scala
We should be calling `cacheApi.getOrElseUpdate` in our default implementation of `SyncCacheApi`.
=> Correct cacheApi call in SyncCacheApi

documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/csrf.scala.html, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/hellotemplate.scala.html, framework/project/Dependencies.scala, framework/project/plugins.sbt, framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala, framework/src/play-docs/src/main/scala/play/docs/DocumentationHandler.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-integration-test/src/test/scala/play/it/auth/SecuritySpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/SecureFlagSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala, framework/src/play-server/src/main/java/play/server/Server.java, framework/src/play-specs2/src/test/scala/play/api/test/FakesSpec.scala, framework/src/play/src/main/java/play/mvc/Filter.java, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/main/scala/play/api/mvc/Filters.scala, framework/src/play/src/main/scala/play/core/j/AbstractFilter.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/main/scala/play/core/j/JavaRouterAdapter.scala
actually these adds a wrapper class JFilter which actually works around the different trait encoding
that will be introduced by scala 2.12
and it removes some calls to Int.unbox() in java which aren't necessary since we can just cast these to Integer (which Int.unbox) will do anyway, calling the intValue() isn't needed since this won't be so much overhead here and the jvm can unbox it anyway
it also adds the newest version of twirl and play-doc
Guess it's fine to merge as is
=> upgrades play-doc, twirl and fixes some hiccups while trying to get scala 2.12 to work

framework/project/Dependencies.scala, framework/project/plugins.sbt
Upgrades specs2 and twirl versions to 3.8.5 and Twirl 1.2.0, to be better suited for Scala 2.12, for https://github.com/playframework/playframework/issues/6110
See https://github.com/etorreborre/specs2/issues/504 and
=> Upgrade spec2 and twirl for 2.12

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Evolutions doesn't work with query parameter.
> http://localhost:9000/search?q=aaa
When url already has query parameters on Evolution, Play can't catch a redirect parameter as a query parameter in apply button.
> http://localhost:9000/search?q=aaa/@evolutions/apply/default?redirect=http%3A%2F%2Flocalhost%3A8484%2Fsearch%3Fq%3Daaa
Because `?` character is duplicated in redirect url.
My PR removes the search query from url in apply button for Evolution.
> http://localhost:9000/search/@evolutions/apply/default?redirect=http%3A%2F%2Flocalhost%3A8484%2Fsearch%3Fq%3Daaa
=> fix failed evolutions with query parameter

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/Standalone.java, documentation/manual/working/scalaGuide/main/ws/ScalaWS.md, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSStandalone.scala
Adds a description of using Play WS from a main method in the simple case, with no bells or whistles.
=> [doc] Add example of using WS from main

framework/src/play/src/main/scala/play/api/Play.scala
Removes deprecated example from scaladoc.
=> Remove Play.current from scaladoc header

framework/project/Build.scala, framework/project/Dependencies.scala, framework/project/Docs.scala
Connects Play apidoc with Akka, Java and Scaladocs.  
This means that https://www.playframework.com/documentation/2.5.x/api/scala/index.html#play.api.package will have links to the scala-lang site, java.lang.String, Akka, and so forth.
This is naturally difficult to test, but here's how you run through this:
```
cd framework
sbt apiDocs
cd ../documentation
sbt run
```
The external javadoc links were broken because of a missing ":", meaning the apiMappings were not applied previously in 2.5.x.  This PR contains the following fix:
```
val options = Seq(
// Note, this is used by the doc-source-url feature to determine the relative path of a given source file.
// If it's not a prefix of a the absolute path of the source file, the absolute path of that file will be put
// into the FILE_SOURCE …
```
=> Connect docs to external apidoc where possible

framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
actually on netty 4.1 some headers will be sent lowercased,
however our current basic http test client wasn't inlined with the current rfc
and handled headers in a case sensitive fashion.
This actually will enable netty-reactive-streams 2.0.0-SNAPSHOT, async-http-client 2.1.0-alpha1 and netty 4.1.5 to run the play test suite.
=> changes the basic http client to use a case insensitive tree map

documentation/manual/working/scalaGuide/main/async/ScalaStream.md
Fixes #xxxx
Updated Streaming HTTP responses documentation with  new API  to create a Result object directly and choose an HttpEntity to represent its body.
=> Updated Streaming HTTP responses documentation

framework/src/play-cache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSModule.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceInjectorBuilderSpec.scala, framework/src/play-java-ws/src/main/java/play/libs/ws/ahc/AhcWSModule.java, framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsModule.scala, framework/src/play-jdbc/src/main/scala/play/api/db/BoneCPModule.scala, framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala, framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala, framework/src/play-ws/src/main/scala/play/api/libs/openid/OpenIdClient.scala, framework/src/play-ws/src/main/scala/play/api/libs/ws/ahc/AhcWS.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala, framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/inject/Module.scala
This creates a `SimpleModule` class that makes it slightly easier to define Play DI modules. It allows the syntax:
```scala
class FooModule extends SimpleModule(
bind[Foo].to[FooImpl],
bind[Bar].to[BarImpl]
)
```
or passing a function:
```scala
class BazModule extends SimpleModule((env, conf) => Seq(
bind[Environment] to env,
bind[Configuration] to conf
))
```
This is mainly intended to clean up our internal code but it could also be useful to external module developers.
=> Create SimpleModule helper for creating Play modules

.travis.yml
Adds Travis build notification into #play-buzz.
See https://blog.travis-ci.com/2014-03-13-slack-notifications/ for more details.
=> Add slack notification for travis CI builds

documentation/manual/about/Philosophy.md, documentation/manual/gettingStarted/IDE.md, documentation/manual/gettingStarted/Installing.md, documentation/manual/gettingStarted/NewApplication.md, documentation/manual/gettingStarted/PlayConsole.md, documentation/manual/gettingStarted/Tutorials.md, documentation/manual/hacking/BuildingFromSource.md, documentation/manual/hacking/Translations.md, documentation/manual/working/commonGuide/assets/AssetsOverview.md, documentation/manual/working/commonGuide/build/BuildOverview.md, documentation/manual/working/commonGuide/build/SBTCookbook.md, documentation/manual/working/commonGuide/production/Deploying.md, documentation/manual/working/commonGuide/production/cloud/Deploying-Boxfuse.md, documentation/manual/working/javaGuide/main/tests/JavaTest.md
- Mention SBT as the build tool except for the few areas we talk about features exclusive to Activator.
- Clarify that Activator is just a wrapper for SBT
- Refer to the sample template downloads being added to the Play website: https://github.com/playframework/playframework.com/pull/97
=> De-emphasize activator in docs and refer to sample templates

documentation/manual/working/javaGuide/code/MockJavaAction.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play/src/main/scala/play/api/mvc/Action.scala, framework/src/play/src/main/scala/play/core/j/JavaAction.scala
This makes the `executionContext` method of `Action` abstract. Previously we defaulted to Play's default execution context obtained using global state.
This shouldn't have much effect on our users, since Actions are generally created using `ActionBuilder`.
=> Make Action#executionContext abstract

documentation/manual/working/scalaGuide/main/http/code/ScalaResults.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/main/scala/play/api/mvc/Flash.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/api/mvc/Session.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala, framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
This moves the actual encoding of cookies to the server implementation. The list of cookies as well as separate session and flash data structures are stored directly on the request. These are encoded when the request is sent.
This has two main advantages:
1. Not having to encode and decode the cookies every time we change a small thing saves us unnecessary work and makes the implementation simpler
2. Doing the encoding on the server instead of on the result itself makes it easier to remove the global state from results.
@richdougherty Do you think it makes sense to use attributes on the result rather than extra fields here for session and flash?
=> Move encoding of cookies from Result to server implementation

documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/select.scala.html
This PR adds an example and clarifies how the `options` helper actually converts the list/pairs given to it into values/displays for a `select` helper. 
Previously, it wasn't clear to people who weren't comfortable looking at the source code of the helpers that the first value of the pair would become the value of an input and the second would become the text displayed to the user.
Signed the CLA via the github application.
=> Update ScalaForms documentation with options example

documentation/manual/gettingStarted/Installing.md
This PR simply fixes 2 lines in documentation/manual/gettingStarted/Installing.md,
where the path to activator was wrong.
=> Fix path to activator in document

framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
Removes an unneeded JavaContextComponents from the `JavaCompatibleHttpRequestHandler` constructor.
`JavaContextComponents` is pulled from `JavaHandlerComponents`, so this constructor doesn't need to exist.
=> Remove an extraneous JavaContextComponents parameter

documentation/manual/working/commonGuide/production/Deploying.md
Fixes a broken link from the deployment docs to the sbt-native-packager docs regarding default mappings for the java server archetype.
=> Fix reference to default mappings in sbt-native-packager docs

documentation/manual/working/commonGuide/production/Deploying.md
Backport of https://github.com/playframework/playframework/pull/6664
=> [Backport 2.5.x] Fix reference to default mappings in sbt-native-packager docs (#6664)

documentation/manual/working/commonGuide/configuration/SettingsLogger.md, documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala, framework/src/play/src/main/java/play/Logger.java, framework/src/play/src/main/scala/play/api/Logger.scala, framework/src/play/src/test/scala/play/api/LoggerSpec.scala
This PR adds the SLF4J Marker API to play.Logger and play.api.Logger interfaces. 
In the Java API, it is a straight port of the SLF4J Logger API.
In the Scala API, markers are added through a MarkerContext trait, which is added as an implicit parameter to the logger methods, i.e. 
```scala
import play.api._
logger.info("some info message")(MarkerContext(someMarker))
```
This opens the door for implicit markers to be passed for logging in several statements, which makes adding context to logging much easier.  In particular, see what you can do with the [Logstash Logback Encoder](https://github.com/logstash/logstash-logback-encoder#event-specific-custom-fields):
```scala
implicit def requestToMarkerContext[A](request: Request[A]): MarkerContext = {
import …
```
=> Add Marker support to Logger API

framework/src/play-test/src/main/java/play/test/WithApplication.java, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play-test/src/main/scala/play/api/test/package.scala, framework/src/play-test/src/test/java/play/test/WithApplicationTest.java, framework/src/play-test/src/test/scala/play/api/test/InjectingSpec.scala
Adds a `Providing` trait to make access to components in functional testing a bit easier.
Using `app.injector.instanceOf[Foo]` all the time is not all that fun, and this provides a more direct experience to the end user, who really shouldn't have to care about the injector per se.
=> Add Injecting trait to WithApplication

framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
This makes sure the Netty server always uses Akka's ExecutionContext to execute actions (like we did in 2.4.x), rather than using the Netty thread.
/cc @jroper
=> Use the Akka ExecutionContext to execute actions

framework/src/play/src/main/scala/play/api/mvc/Action.scala
No reason this would deadlock so it can execute on the same thread.
=> Use trampoline EC in Action#asJava

documentation/manual/working/javaGuide/main/http/JavaRouting.md, documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
The source code above the text I've changed refers to `controllers.routes.Application` and `controllers.Application`, and not `controllers.admin.routes.Application` and `controllers.admin.Application`.
I therefore removed the `.admin` - which is otherwise inconsistent with the preceding code.
Introducing a different namespace placement of the Application in this paragraph could confuse the reader.
One can see the rendering of the code and document here, for review:
https://playframework.com/documentation/2.5.6/ScalaRouting#reverse-routing
https://playframework.com/documentation/2.5.6/JavaRouting#reverse-routing
=> Remove incorrect occurrence of ".admin." in HTTP Routing docs

documentation/manual/working/javaGuide/main/akka/JavaAkka.md, documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
Fixes #xxxx
It adds a tiny bit to the akka documentation clarifying how the child actor gets its name, because in the existing example the `key` parameter is used both as a parameter to the factory as well as the actor's name.
- this confused me a lot when I saw that the key is passed twice.
=> documentation: clarify how the child actor get its name

framework/src/play-server/src/main/scala/play/core/server/common/NodeIdentifierParser.scala, framework/src/play-server/src/main/scala/play/core/server/common/Subnet.scala, framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala, framework/src/play-server/src/test/scala/play/core/server/common/NodeIdentifierParserSpec.scala, framework/src/play-server/src/test/scala/play/core/server/common/SubnetSpec.scala
Fixes #6629.
I also changed to use Guava's IP address parser instead of the standard Java parser. The Java parser will make DNS lookups for non-IP addresses. I don't think we need DNS lookups so the Guava parser is probably better.
Cc @swoopster-sb.
=> Parse IPv4-mapped IPv6 addresses in forward headers

documentation/manual/working/commonGuide/filters/CorsFilter.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSConfig.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSCommonSpec.scala
Fixes #5193 
This patch adds support to conditionally handle requests from non-whitelisted origins as non-CORS requests, ie let them to pass through. The default behavior is not changed, unallowed origins are forbidden. Please note that serving forbidden origins as non-CORS requests doesn't lower the security, given that browsers check the access control headers and block the response anyway.
Not all requests with an `Origin` header are CORS requests generated by browsers. Other clients can set the `Origin` header, don't send preflight calls, and don't expect to receive CORS access control headers in the answer. A common client of such type is a Cordova application, that always sends the `Origin: file://` header.
=> Add a CORS config param to allow pass-through of forbidden origins.

documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java, framework/src/play/src/main/java/play/mvc/Http.java
Fixes #6626
Also remove several deprecated methods for Java cookies (these have been deprecated since 2.5.0 and are easily rewritten).
=> Change CookieBuilder#withMaxAge to accept Duration

framework/src/play-integration-test/src/test/scala/play/it/i18n/MessagesSpec.scala, framework/src/play/src/main/scala/play/api/i18n/I18nModule.scala, framework/src/play/src/main/scala/play/utils/Reflect.scala
I noticed I couldn't find the bindings for the Java versions of these anywhere. I think we inadvertently removed them.
=> Add bindings for Java i18n classes

.travis.yml
The master build seems to be failing and we don't need to use a custom java installer now that Travis CI has upgraded past the u31 bug...
https://travis-ci.org/playframework/playframework/builds/174834911
```
Using worker: worker-linux-docker-d5c5f82d.prod.travis-ci.org:travis-linux-3
Build system information
Build language: scala
Build group: stable
Build dist: precise
Build id: 174834911
Job id: 174834912
travis-build version: 628c8d2e6
Build image provisioning date and time
Thu Feb  5 15:09:33 UTC 2015
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise
Linux Version
3.13.0-29-generic
Cookbooks Version
a68419e https://github.com/travis-ci/travis-cookbooks/tree/a68419e
GCC version
gcc (Ubuntu/Linaro 4.6.3-1ubuntu5) 4.6.3 …
```
=> Remove custom Java installer for travis build

framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java
```
[error] /Users/cchantep/Projects/playframework/framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java:72: no suitable method found for collect(java.util.stream.Collector<java.lang.Object,capture#1 of ?,java.util.List<java.lang.Object>>)
[error]     method java.util.stream.Stream.<R>collect(java.util.function.Supplier<R>,java.util.function.BiConsumer<R,? super capture#2 of ?>,java.util.function.BiConsumer<R,R>) is not applicable
[error]       (cannot infer type-variable(s) R
[error]         (actual and formal argument lists differ in length))
[error]     method java.util.stream.Stream.<R,A>collect(java.util.stream.Collector<? super capture#2 of ?,A,R>) is not applicable
[error]       (cannot infer type-variable(s) R,A,capture#3 of ?,T
[error] …
```
=> OS X/Java build error

framework/bin/travis
Travis CI could use some speeding up, and microbenchmarks only work when we know what hardware we're running on.
=> Removes microbenchmark from travis build

documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
Fixes #6707
Fixes a documentation error that made people use the noop `setContentType` of `play.mvc.Http.Response`
Cleaning up an issue that had no real priority but gave backlog.
https://github.com/playframework/playframework/issues/6707
=> Fix documentation error (usage of noop setContentType)

framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
Actually in `IdleTimeoutSpec.scala` we have had a regex that also checked the SocketException message, however this message might change depending on the system you test. In master we already removed them.
P.S.: Doc validation still fails but we might Backport https://github.com/playframework/playframework/commit/ce8c083bba163faac9a2dd7a782bd87b57e0baa7 so that it will be fixed or remove the "bad doc" references.
=> [2.5.x] fixes the NettyIdleClientTimeoutSpec

framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala
Fixes ScalaResultsSpec to use the non-deprecated config settings.
=> Remove deprecated config settings from tests

framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/README, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/app/controllers/Application.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/conf/application.conf, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/conf/routes, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/test
Fixes #6688
Fixes #6688 adds a includeDocumentation variable to remove the java/scala-doc from the distribution
Actually to really stop it from generating the documentation would mean to actually set `packageDoc` to new `File(".")`, see https://github.com/playframework/playframework/pull/6723/files#diff-69b29e5ccdf04d73ef169d932b4e2dbcR20.
Another way would be creating a `AutoPlugin` to remove the `mappings` but even that can't remove the `packageDoc` call.
/cc @muuki88
=> Fixes #6688 adds a includeDocumentation variable

framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
##Fix
Multipart form data parts have optional quotes. This was already fixed for "filename" param, but not for regular parameters.
##References
I've also commented on this issue:
playframework#6275
=> Fix Multipart form data parts with optional quotes

framework/src/play-java/src/main/java/play/libs/Classpath.java
Deprecates `play.lib.Classpath`.  It's not used anywhere in the codebase, but is public, so this marks it for removal.  Will probably make this package private.
=> [UFR] Deprecate play.libs.Classpath

framework/src/play/src/main/java/play/libs/concurrent/HttpExecution.java
Deprecates `HttpExecution.defaultContext`, as it uses Execution.internalContext under the hood, has no usage internally, and can be easily replaced.
=> [UFR] Deprecate HttpExecution.defaultContext

documentation/manual/releases/release26/migration26/MessagesMigration26.md, documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala, documentation/manual/working/scalaGuide/main/forms/code/ScalaFieldConstructor.scala, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, documentation/manual/working/scalaGuide/main/i18n/code/ScalaI18N.scala, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala, framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala, framework/src/play/src/main/scala/play/api/i18n/I18nModule.scala, framework/src/play/src/main/scala/play/api/i18n/Langs.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/test/scala/play/api/data/FormSpec.scala, framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala, framework/src/play/src/test/scala/play/core/test/package.scala, framework/src/play/src/test/scala/views/html/helper/HelpersSpec.scala
This PR breaks out the construction of a `DefaultMessagesApi` from configuration using a `javax.inject.Provider`.  It removes a hardcoded reference to HttpConfiguration and allows for other instances of `DefaultMessagesApi` to be passed back with just a Map backing and default arguments instead of the entire environment / configuration etc.
This also makes it much easier to supply a MessagesApi object to FakeRequest, etc.
Docs added: unit testing a form by passing a `DefaultMessagesApi` in.
=> [UFR] Define MessageApi configuration in a provider.

documentation/manual/gettingStarted/Installing.md
Fixes #6754
currently the link used https:// however sbt uses github pages which results in a broken certificate.
=> changes sbt download page to use http:// #6754

framework/build.sbt, framework/project/BuildSettings.scala, framework/project/plugins.sbt
the newest version supports Scala 2.12 properly and is capable of
detecting a variety of compatibility issues older versions missed
=> upgrade to latest MiMa (0.1.12)

framework/project/Dependencies.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
Hi there,
this brings Play onto 2.4.14 - it's fully binary compatible otherwise - just extending the materializer is "gray zone" so this needed to change.
=> Update to Akka 2.4.14, materializer is not public API and changed a bit

framework/project/Build.scala, framework/project/Dependencies.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
Backport of https://github.com/playframework/playframework/pull/6767
I'm unsure about `akka-http`  but since we still have the experimental marker on it I guess it's fine to use 10.0.0?
=> [2.5.x Backport] Update to Akka 2.4.14, materializer is not public API and changed a bit (#6767)

framework/src/play-java-ws/src/main/java/play/libs/openid/DefaultOpenIdClient.java, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala, framework/src/play/src/main/scala/play/core/Execution.scala
The `Execution.internalContext` methods are static, so they all depend on Play.privateMaybeApplication.  They can be replaced with generic thread pool references that don't go through the same pathway.
=> [UFR] Remove `Execution.internalContext` references

framework/project/BuildSettings.scala
Actually we need to set `no-java-comments` for 2.12 unfortunatly that does not get applied for play-java since it overrides the scala version. I also made it future proof since 2.12.1 would not include the fix for it.
=> publishLocal fails due to -no-java-comments not getting applied, since we override the scala version

framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
Expose the PlayRequestHandler class, and make it simple to override this
in a NettyServer subclass.  This will make it possible to use
lightweight wrappers around the request handler's `handle()` method.
=> Simplify wrapping of PlayRequestHandler.

framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
See title.
The previous return type was overly ambitious for no real gain.
All tests in `Play-Netty-Server` still pass.
=> Better return type on method, to avoid cast when overriding handleRead()

documentation/manual/ModuleDirectory.md
Backport of https://github.com/playframework/playframework/pull/6665
=> [Backport 2.5.x]  Added the mohiva/swagger-codegen-play-scala module and updated the URLs for Silhouette.

framework/build.sbt, framework/project/Dependencies.scala, framework/src/play-openid/src/test/scala/play/api/libs/openid/package.scala
Removes the 3.5.x Netty dependency on QueryStringDecoder from Play-OpenId project by moving to the Netty 4.x version.
=> Remove Netty dependency from play-openid

framework/src/play-java/src/main/java/play/data/Form.java, framework/src/play-java/src/test/scala/play/data/FormSpec.scala
Fixes #6272 and #6592
This is a backport of the fix for #6272 (Set form value even when form has errors) into the 2.3.x branch. I have also backported to 2.4.x as well in PR #6595 
As recommended in #6592
#6592 and #6595
=> Backport of Issue #6272 to 2.3.x

framework/src/play-json/src/main/scala/play/api/libs/json/Writes.scala, framework/src/play-json/src/test/scala/play/api/libs/json/WritesSpec.scala
Play 2.5.x
Scala
- Any 
- Darwin leto.local 15.6.0 Darwin Kernel Version 15.6.0: Thu Sep  1 15:01:16 PDT 2016; root:xnu-3248.60.11~2/RELEASE_X86_64 x86_64
- Any
- java version "1.8.0_25" 
Allow to enrich/rewrite an existing JSON writer, with a function given the initial input and the intermediary JSON output.
```scala
val transformed: OWrites[Foo] = OWrites.transform(writes) { (foo, obj) =>
obj ++ Json.obj("hash" -> foo.hashCode)
}
val foo = Foo("Lorem")
val written: JsObject = transformed.writes(foo)
```
=> New transformations for JSON writers

documentation/manual/hacking/Repositories.md
well sonatype is a maven style repo so the ivy style would be wrong, was probably wrong since the transition from typesafe to sonatype repo.
=> corrected the sonatype repository

documentation/manual/hacking/Repositories.md
well the note is also invalid (follow up on https://github.com/playframework/playframework/commit/edf0e24bfc4f8eb2c67446b69c9459a1587bf232)
=> removed the note about the sonatype repository

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala, framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHttpServerSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
Well this is a controversial one, however netty allows **every** content-type (even `Content-Type: wsargent/gmethvin`), not just arbitary ones.
This PR allows actually Setting non RFC like Content-Types.
Well in Future Play Versions we should probably Parse everything **and** disallow such things, however as seen in the AssetsSpec some people actually need non compliance (a big one is probably adding a charset to json, which is invalid by the specification, but is actually used in many many frameworks/applications)
Also the parsing should've been done a level higher, so I guess even if we have typed headers we would need to convert them and I guess this is the most straightforwarded way since it tricks `akka-http`.
=> akka-http header should not be parsed to be on par with netty

documentation/manual/working/scalaGuide/main/json/ScalaJsonCombinators.md
Removes a typo:
`Reads[Option[T]]readNullable` -> `Reads[Option[T]]`
=> Typo in ScalaJsonCombinators.md

framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
I think this should have been done in #6559 but was overlooked.
I tried to run a very simple play java project with current `master` but I got this error when compiling the twirl templates:
```
[info] Compiling 6 Scala sources and 3 Java sources to play-java-seed/target/scala-2.12/classes...
[error] play-java-seed/app/views/index.scala.html:1: object data is not a member of package play
[error] @()
[error] ^
[error] play-java-seed/app/views/main.scala.html:1: object data is not a member of package play
[error] @*
[error] ^
[error] two errors found
[error] (compile:compileIncremental) Compilation failed
```
Changing the plugin settings fixed the problem - it should have been like this in first place already I think.
=> Fix PlayJava after extracting Java forms

framework/project/plugins.sbt
This change makes Play depend on Interplay 1.3.1, which uses the Scala 2.12.1 compiler explicitly.
This fixes the javadoc stackoverflow bug and ensures downstream Play projects don't run into odd issues.
Notably, the sbt-twirl download error in https://github.com/playframework/playframework/issues/6782 was being caused by a misapplied scalaVersion looking for a 2.12 version of sbt-twirl, when all SBT projects should be on 2.10.
=> Upgrade to interplay 1.3.1

framework/src/play-java-forms/src/main/java/play/data/validation/ValidatorProvider.java
Right now we create a `ValidatorFactory` **each time** we need a validator - which is quite often (for every constraint annotation for each request).
But we just need a single `ValidatorFactory` per app which delivers us the desired validator(s).
Also using `usingContext` isn't ideal here. What we do right now we create a `ValidationFactory` via `buildDefaultValidatorFactory` (which actually is just a shortcut for `.byDefaultProvider().configure().buildValidatorFactory()`) and then re-configure this just created factory via `usingContext()`. With my change we now immediately create the factory we want. 
This change will save some CPU cycles and heap space :laughing:
=> Create ValidatorFactory just once

documentation/manual/working/javaGuide/advanced/routing/code/GuiceAppLoader.java, framework/src/play-cache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaRequestsSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala, framework/src/play-openid/src/main/java/play/libs/openid/DefaultOpenIdClient.java, framework/src/play-openid/src/main/scala/play/api/libs/openid/OpenIdClient.scala, framework/src/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala, framework/src/play/src/main/java/play/i18n/Langs.java, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala, framework/src/run-support/src/main/scala/play/runsupport/FileWatchService.scala
JavaConversions was deprecated in Scala 2.12. This PR replaces it with JavaConverters.
=> Use JavaConverters instead of deprecated JavaConversions

framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/i18n/Messages.scala, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/main/scala/play/api/mvc/Flash.scala, framework/src/play/src/main/scala/play/api/mvc/Session.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala
This is a working in progress PR. There is still work to be done regarding the `CookieSigner`.
Fixes #6694 and invalidates #6753.
Remove the global state access made at Cookies, Flash, Sessions and related classes.
#6753  PR was made agains branch 2.3.x, so maybe we can backport part of this PR to branch 2.5. Basically, these two new configurations:
1. play.http.session.path: defaults to play.http.context
2. play.http.flash.path: defaults to play.http.context
=> [WIP]: Remove global state for Cookies, Sessions and Flash

framework/src/play/src/main/java/play/mvc/EssentialAction.java
This eliminates the global state in `EssentialAction` by running the `Result::asScala` in the same thread.
=> Use trampoline ExecutionContext in Java EssentialAction

documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredChildActor.java, documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/CustomApplicationLoader.java, documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/dynamic/Module.java, documentation/manual/working/javaGuide/main/tests/code/tests/guice/JavaGuiceApplicationBuilderTest.java, framework/src/play-guice/src/main/java/play/inject/guice/GuiceBuilder.java, framework/src/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java, framework/src/play-guice/src/test/java/play/inject/guice/GuiceInjectorBuilderTest.java, framework/src/play-guice/src/test/scala/play/api/inject/ModulesSpec.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala, framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/scala/play/api/inject/Module.scala
Removes `play.Configuration` in favor of using the `Config` class, from Typesafe Config lib.
=> Reduce usage of deprecated play.Configuration class

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
`Evolutions.applyFor` can also be done directly by the `EvolutionsApi`.
=> Deprecate global state in evolutions

framework/project/plugins.sbt, framework/src/play-openid/src/main/java/play/libs/openid/DefaultOpenIdClient.java, framework/src/play/src/main/java/play/i18n/Langs.java, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fixes #6782.
1. Uses JavaConverters' methods compatible with both Scala 2.11 and 2.12.
2. Update interplay to ensure that proper `crossScalaVersions` is used in sbt plugins
See playframework/interplay#22 and playframework/interplay#23.
=> Fix cross build compilation and publishing

framework/project/Dependencies.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
Fixes #6190 for `2.4.x` branch
=> Fix displaying runtime exception coming from Twirl template while running in development mode - PR for branch 2.4.x

documentation/manual/gettingStarted/PlayConsole.md, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
* [n/a] Have you added copyright headers to new files? No new files
* [n/a] Have you added tests for any changed functionality? AFAIK, sbt scripted test plugin doesn't allow to have test the reading key stroke from the console, i guess that's the reason why there is no existing tests for this part of the plugin.
Fixes #2671
This PR allows the use if the key Enter to stop the play run command.
Using Ctrl-D for stopping the run command is risky since Ctrl-D is also used for terminating SBT. I regularly terminate SBT when I only mean to stop the run command.
We should allow Enter to be used to stop the run command. SBT already uses Enter to terminate other interactive commands, such as ~compile, ~test, etc. To make the transition easy for users we can still support …
=> Use Enter key to stop play run command (#2671)

framework/src/play-docs/src/main/scala/play/docs/DocumentationHandler.scala
Fixes a small problem at the documentation server. The `/api` were not being delivery inline because the `fileMimeTypes` was matching against the filename instead of file extension.
=> Delivery /api inline at documentation server

documentation/manual/ModuleDirectory.md
This PR updates the documentation. It adds reference to [play-redis](https://github.com/KarelCemus/play-redis) module implementing a redis based cache. It implements common `CacheAPI` and some additional redis commands including the support of collections. The API is implemented in both blocking and asynchronous manner.
=> Reference to play-redis module in Module directory in the documentation

documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, framework/src/play/src/main/scala/play/api/data/format/Format.scala, framework/src/play/src/test/scala/play/api/data/format/FormatSpec.scala
For users developing their own `Formatter`s wanting to re-use the logic in the `parsing` method, please make this method non-private.
Fixes #xxxx
=> Make Formats.parsing method non-private

documentation/build.sbt, documentation/manual/experimental/AkkaHttpServer.md, documentation/manual/experimental/code/ScalaAkkaEmbeddingPlay.scala, framework/build.sbt, framework/project/Dependencies.scala, framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/HttpRequestDecoder.scala, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/test, framework/src/play-akka-http-server/src/test/scala/play/core/server/AkkaHttpServerSpec.scala, framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHttpServerSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala
actually this marks akka-http backend as non experimental
and changes the gzip decoder from akka-http to akka-stream so that we can
only depend on the akka-http-core model
AkkaHttpServer and ModelConversions were moved to play.core.server to be on par with the netty backend.
=> Moves/Renames akka-http related files to be on par with netty and changes gzip decoder

framework/project/Dependencies.scala, framework/src/play-java-forms/src/main/java/play/data/validation/ValidatorProvider.java, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
Hibernate validator *itself* will by default interpolate the error messages you define in a constraint (e.g. `@Required(message="I will be interpolated")`). See the [docs](https://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html_single/#validator-gettingstarted-uel):
> Hibernate Validator requires an implementation of the Unified Expression Language (JSR 341) for evaluating dynamic expressions **in constraint violation messages**
So you *could* [use expressions like](https://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html_single/#_examples) `${validatedValue}` and `${formatter.format('%1$.2f', validatedValue)}` or [reference the attribute values of the constraint](https://docs.jboss.org/hibernate/validator/5.2/reference/en-US/html_single/#section-interpolation-with-m …
=> Un-interpolated error messages allows removal of javax.el

framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAEntityManagerContext.java, framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAModule.java
I came across this while testing out the Spring application loader. It's actually not a problem in master because we don't use DI for the JPAEntityManagerContext.
=> [2.5.x] Add explicit binding for JPAEntityManagerContext

documentation/manual/gettingStarted/IDE.md
So it matches the `sbt-eclipse` default `managedClassDirectories` setting:
https://github.com/typesafehub/sbteclipse/blob/v5.1.0/src/main/scala/com/typesafe/sbteclipse/core/EclipsePlugin.scala#L48
@benmccann [agrees with me on this change](https://github.com/typesafehub/sbteclipse/pull/327#issuecomment-268654889)
=> (compile in Test) should also be a default in sbt-eclipse preTasks

framework/src/play-cache/src/main/java/play/cache/AsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultSyncCacheApi.java, framework/src/play-cache/src/test/scala/play/api/cache/CacheApiSpec.scala, framework/src/play-cache/src/test/scala/play/api/cache/CachedSpec.scala, framework/src/play-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
The main change here is to solve a small bug at `DefaultSyncCacheApi.getOrElseUpdate` which was ignoring the `expiration` parameter.
Tests were added to the Java version of Cache APIs and other small improvements were made.
After merging, #4972 could be closed.
=> Honors the expiration time in DefaultSyncCacheApi

documentation/manual/working/javaGuide/main/forms/JavaForms.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/view.scala.html, documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/user.scala.html, framework/src/play-java-forms/src/main/java/play/data/validation/ValidationError.java, framework/src/play/src/main/scala/play/api/data/Form.scala
Adds format method to `FormError`.
If you're using a form error in Twirl, then the way to do it is:
```
@Messages(error.messages, error.args)
```
https://www.playframework.com/documentation/2.5.x/ScalaForms#Displaying-errors-in-a-view-template
Since you have to pass in an implicit Messages anyway (again, from the docs above):
```
@(userForm: Form[UserData])(implicit messages: Messages)
```
and the Messages singleton object takes that same implicit messages, there's a whole bunch of typing that could just as well be:
```
@error.format
```
So... that's what this PR does.
=> Add format methods to FormError

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/mvc/Result.java
This actually fixes a bug introduced on the master branch. We need to append the provided list of cookies to the existing list.
=> Allow multiple withCookies calls in Java API

framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ClientCookieDecoder.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Fixes #6888 by reading the raw max-age value from the cookie and setting that directly instead of using `Math.max(maxAge, 0)`. It's valid to have negative `Max-Age` values, and this is needed to properly set `Expires` since `maxAge` is used to set both.
Needs backport to 2.5.x.
=> Fix cookie max-age computation

framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/java/play/data/validation/TestConstraints.java, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play-java-forms/src/test/scala/play/data/Task.scala
Just a simple addition to #5565 so that the `withRequestLocale` lambda also spans across the `validator.validate(...)` method - just to make sure spring's `LocaleContextHolder.getLocale()` is set inside the validate logic if needed by spring (or by user code). Actually I thought I did this in the original PR already...
=> Make (spring) locale of current request available in validate()

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/scalaGuide/main/cache/code/ScalaCache.scala, framework/src/play/src/main/scala/play/api/mvc/Security.scala
I don't believe this helper is used that often, since typically we recommend a third-party library for handling authentication/authorization, so I've just deprecated the code that reads from configuration.
=> Remove global state from play.api.mvc.Security

documentation/manual/working/javaGuide/main/cache/JavaCache.md, documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/qualified/Application.java, framework/src/play-cache/src/main/java/play/cache/CacheApi.java
Users should now use play.cache.SyncCacheApi or play.cache.AsynCacheApi.
https://github.com/playframework/playframework/pull/6865#pullrequestreview-17119846
=> Deprecate play.cache.CacheApi

framework/project/Dependencies.scala
Hi, 
After upgrading to 2.5.11 I was getting runtime exceptions when using a class from ` "org.apache.httpcomponents" % "httpclient"`. 
`httpclient` has a dependency on `httpcore`, but `httpcore` is excluded by 
`ExclusionRule(organization = "org.apache.httpcomponents")`
I could fix this by adding it to my app dependencies, but maybe it's better to have this dependency in the framework.
[Here is a forum user who also had this problem.](https://groups.google.com/d/msg/play-framework/E2fnsC0sbSg/B9Rd2kPCAAAJ)
thanks
Simon
=> added httpcore dependency

framework/project/Dependencies.scala
Upgrades netty-reactive-streams to 2.0.0-M1 and upgrades Netty to 4.1.7.Final, upgrades akka-http to 10.0.2
=> Upgrade to Netty 4.1.7

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSWithCSRFSpec.scala
It stills keep some global state to keep some compatibility.
The remaining global state usage was marked as deprecated and should be removed later.
=> Removes global state from CSRF components

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/BrowserFunctionalTest.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FunctionalTest.java, documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala, framework/project/Dependencies.scala, framework/src/play-test/src/main/java/play/test/TestBrowser.java, framework/src/play-test/src/main/scala/play/api/test/Selenium.scala
Bumps fluentlenium version to 3.1.1 and adjusts classes accordingly. This seems fit since scalatestplus-play already uses Selenium 3 while the current fluentlenium version 0.10.9 still uses Selenium 2
=> Update Fluentlenium to latest version

framework/project/plugins.sbt
Could not tag a docker image as the latest using `docker:publish`/`docker:publishLocal` due to old `sbt-native-packager` version.
Updates `sbt-native-packager` to the latest stable version. 
I tried to use `dockerUpdateLatest in Docker := true`, but it was broken in the `sbt-native-packager` used in Play 2.5.12
https://github.com/sbt/sbt-native-packager/releases/tag/v1.1.5
https://github.com/sbt/sbt-native-packager/releases/tag/v1.1.3
sbt/sbt-native-packager#845
sbt/sbt-native-packager#818
sbt/sbt-native-packager#838
I want this in the next 2.5.x release too, is that possible? How would I go about doing that (open a PR against the `2.5.x` branch?)?
=> Upgrade sbt-native-packager to latest stable version

.travis.yml
Removes sourceclear from the build because it errors and doesn't work with sbt in any case :-/
=> Remove sourceclear from Travis

framework/project/plugins.sbt
Could not tag a docker image as the latest using `docker:publish`/`docker:publishLocal` due to old `sbt-native-packager` version. This a backport of #6924 on master.
Updates `sbt-native-packager` to the latest stable version. 
I tried to use `dockerUpdateLatest in Docker := true`, but it was broken in the `sbt-native-packager` used in Play 2.5.12
#6924
https://github.com/sbt/sbt-native-packager/releases/tag/v1.1.5
https://github.com/sbt/sbt-native-packager/releases/tag/v1.1.3
sbt/sbt-native-packager#845
sbt/sbt-native-packager#818
sbt/sbt-native-packager#838
=> Upgrade sbt-native-packager to latest stable version (2.5.x)

framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
Extend the websocket timeout to 10 seconds, re-enable the ping tests now we have Netty upgraded.
=> Extend timeout and enable ping in websockets

documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Moves the note about unreliable networks in WS documentation down to patterns and adds `CustomExecutionContext` as a class.
The note is situated too high, where it can be skipped over as an introduction, rather than as a general pattern.
This needs an example and also needs a Java section that is equivalent.
=> [doc] Move the unreliable network section

framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/controllers/Assets.scala
Per [Mozilla](https://hacks.mozilla.org/2017/01/using-immutable-caching-to-speed-up-the-web/) and [Patrick McManus](https://bitsup.blogspot.com/2016/05/cache-control-immutable.html) we can add the "immutable" property to versioned, fingerprinted assets in Prod mode to make sure that Firefox and Chrome speed up reloads of assets.
[Chromium Issue](https://bugs.chromium.org/p/chromium/issues/detail?id=611416)
[Mozilla Issue](https://bugzilla.mozilla.org/show_bug.cgi?id=1267474)
=> Add immutable header to aggressiveCacheControl

framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
The websocket integration test is flaky, and will sometimes fail.  
Add some code to retry only websocket specs up to 5 times, with 100 msec delay.
=> Retry the websocket spec

documentation/manual/working/commonGuide/configuration/code/detailedtopics/ThreadPoolsJava.java, documentation/manual/working/javaGuide/code/MockJavaAction.scala, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaComet.java, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaCsrf.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActions.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaContentNegotiation.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaRouting.scala, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java, documentation/manual/working/javaGuide/main/i18n/code/javaguide/i18n/JavaI18N.java, documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java, documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWSSpec.scala, documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala, documentation/project/plugins.sbt, framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play-test/src/main/java/play/test/WithApplication.java
Refactoring docs code to avoid some usages of deprecated APIs. Also add some missing tests.
We have deprecated a lot of APIs but they are still being used by some documentation code. I don't want to remove them all at once to avoid big pull requests (which are harder to review). Some of the changes are just mechanical and some could add new methods to production code (like https://github.com/playframework/playframework/pull/6916/commits/5f36597c5abe761e9159da854a7ba298fca320b3 at this PR).
=> [doc]: remove some deprecated API usages

documentation/manual/ModuleDirectory.md
Adds Scalate as a library module to the module directory.  This gives HAML and Velocity type support as an alternative to Twirl.
=> Add Scalate as a library for Play support

documentation/manual/gettingStarted/PlayConsole.md
Remove wrong app directory from console docs
This was wrongly introduced at #6946.
Must be merged before #6948 and cherry picked there.
=> Remove wrong app directory from console docs

framework/project/Dependencies.scala
This includes new features like the `include required("foo")` syntax. Should be compatible with 1.3.0.
=> [2.5.x] Update Typesafe Config to 1.3.1

documentation/manual/releases/release26/migration26/Migration26.md, framework/project/Dependencies.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/scala/play/api/http/Writeable.scala
Instead of writing our `JsValue`s to a string and then to bytes when writing them out, let's just write directly to a byte array.
One small API change here is that the implicit `Writeable` for `JsValue` always uses UTF-8. I decided to make the implicit `Writeable` not take a `Codec` and always write to UTF-8 and make another non-implicit one that allows setting a codec. The reasoning is that almost always you want to write as UTF-8, and since JSON is always Unicode, you would produce an invalid response if you happened to have the wrong codec in scope.
=> Update Writeable to write JsValue to bytes with play-json 2.6.0-M2

documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, framework/project/Dependencies.scala, framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSClient.java, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClient.scala, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClientProvider.scala
* Updates Play-WS dependency to M3 (which does not contain unshaded deps)
* Add option to create WSClient with HTTP caching (disabled by default)
=> Update to Play-WS m3, add caching option

framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/AnyContentBodyParserSpec.scala, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/Play.scala, framework/src/play/src/test/scala/play/api/PlayCoreTestApplication.scala, framework/src/play/src/test/scala/play/api/PlayGlobalAppSpec.scala
- Add `globalApplicationEnabled` lazy val to Application to make it easier to determine or set if the global app is enabled.
- Change `Play.start` to only call `Play.stop` on the current app if we need to replace the existing global application instance.
- Add `GuiceApplicationBuilder#globalApp(Boolean)` to make it easy to enable or disable global state in a test.
- Change a test as a proof of concept.
=> Improve global application configuration and handling

documentation/manual/working/javaGuide/code/MockJavaAction.scala
Removes `play.api.libs.concurrent.Execution` usage from documentation code.
See #6916 for more background context.
=> [doc]: Remove play.api.libs.concurrent.Execution from documentation code

framework/src/play/src/main/java/play/mvc/ResponseHeader.java, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/core/j/JavaResults.scala, framework/src/play/src/test/scala/play/mvc/ResponseHeaderSpec.scala, framework/src/play/src/test/scala/play/mvc/ResultSpec.scala
Fixes #2178.
Add a Java API for response headers
See #2178 and related issues.
=> Add a Java API for response headers

documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/AgeRange.java
The documentation code was using 
return Optional.of(null); instead of Optional.empty();
of(null) would throw a NullPointerException
=> Fix documentation code NPE

framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/test/scala/play/api/mvc/MaxLengthBodyParserSpec.scala
Changes the naming of `PlayBodyParsersImpl` to `DefaultPlayBodyParsers`. Also removes the call by name parameters and creates a special case for `BodyParsers.parse`
=> Refactor PlayBodyParsers

framework/project/Dependencies.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
Updates Netty and remove deprecated API calls.
http://netty.io/news/2017/01/30/4-0-44-Final-4-1-8-Final.html
=> Update netty to version 4.1.8.final

framework/project/Dependencies.scala, framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSModule.java, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClient.scala
Updates Play to use Play-WS 1.0.0-M4 and updates the Java provider to use the injected ObjectMapper.
=> Update to play-ws M4

documentation/manual/working/commonGuide/configuration/SettingsLogger.md
References logback documentation about `<file>` tag when using log rolling.
See #6364 for discussion and more information. /cc @ToBeHH.
=> Add note and link about file tag for log configuration

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/javaGuide/main/ws/JavaOpenID.md, documentation/manual/working/javaGuide/main/ws/code/javaopenid.sbt, documentation/manual/working/scalaGuide/main/ws/ScalaOpenID.md
Additionally, fix case of `openId` import in the OpenID documentation, and add a Java sbt import snippet.
=> Add note about modularized OpenID support to 2.6 migration guide.

framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/http/HttpPipeliningSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
There are some tests that fail repeatedly on CI server even when they work locally.
=> Add a skip on slow CI server flag on specs

framework/src/play-akka-http-server/src/main/resources/reference.conf
The reference.conf refers to `request-timeout` but the code refers to `requestTimeout`
The idleTimeout settings are left undefined and not in AkkaHttp.
See https://groups.google.com/d/msg/play-framework/imf51EsYU08/tDk0sEfPCgAJ for user experience
Documentation at https://github.com/playframework/playframework/blob/master/documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md could also use some love
@ktoso and @jrudolph are looking at akka-http already, so not going to go into cleaning up the `.getOptional` calls...
=> Ensure akka-http has valid reference.conf

documentation/manual/gettingStarted/Tutorials.md
This post describes many "gotachas" associated with upgrading from play 2.3 to play 2.5 and some of the things that were learned while upgrading.
I've been working with @wsargent to get this blog post published. He initially suggested that it might be good to link to it on this page.
~~_I haven't signed the CLA yet, I'm working on that now._~~
=> Add link to upgrading blog post

documentation/manual/releases/release25/migration25/Migration25.md
Adds a link https://www.lucidchart.com/techblog/2017/02/22/upgrading-play-framework-2-3-play-2-5/ to Migration25.
This gives more context for people going through the upgrade and makes it more visible than it would be on the tutorials page.
**Needs backport to 2.5.x branch**
=> Add Lucidchart Migration Blog Guide to Migration25

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/main/scala/views/html/helper/CSRF.scala
This just migrates from using tags to attributes for storing the CSRF token info on the request.
All the existing tests still pass. I still have to look at what's happening with #6977.
=> Migrate CSRF to request attributes

framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
Adds controller components to BuiltInComponentsFromContext
Makes it easier to use in compile time DI.
This is important because any compile time DI that uses AbstractController depends on it:
```
class MyComponents(context: ApplicationLoader.Context) 
extends BuiltInComponentsFromContext(context)
with AhcWSComponents
with _root_.controllers.AssetsComponents {
lazy val parsers: PlayBodyParsers = playBodyParsers
lazy val actionBuilder: ActionBuilder[Request, AnyContent] = defaultActionBuilder
lazy val homeController = new _root_.controllers.HomeController(controllerComponents)
lazy val router: Router = new _root_.router.Routes(httpErrorHandler, homeController, assets)
}
```
=> Add builtin controller components

framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
This adds type ascription to `path` and `withMultipartFormDateBody` method  in `play.api.test.FakeRequest` and `play.api.test.RequestTarget`. 
And remove useless method.
=> Add type ascription in play.api.test.Fakes.scala, and remove useless method

framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java, framework/src/play-integration-test/src/test/java/play/routing/CompileTimeInjectionRoutingDslTest.java, framework/src/play-integration-test/src/test/java/play/routing/DependencyInjectedRoutingDslTest.java, framework/src/play-integration-test/src/test/java/play/routing/GlobalStateRoutingDslTest.java, framework/src/play-test/src/main/java/play/test/Helpers.java
Deprecated test helpers methods that were using global state.
=> Deprecate methods using global state in test Helpers

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
Fixes #6977 
This fixes the `SignedTokenProvider` so it correctly compares signed tokens. It also fixes the CSRF tests so they correctly catch this type of error.
=> Correctly compare signed tokens

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java, framework/src/play-java-forms/src/main/scala/play/core/PlayFormsMagicForJava.scala, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
Right now we use a `Map<String,List<ValidationError>>` to store validation errors inside a `play.data.Form` instance.
But this absolutely doesn't make any sense at all and makes the code just very confusing. A `Map` entry's key will always be the same as the keys of the `ValidationError`s the `Map` entry stores anyway. It seemed the only "sense" to store the `ValidationError`s in a map was to access it "more easy" via `.get("somekey")` - but since we are using Java >= 8 we can simple use stream methods (`filter`, `findFirst` , etc.) to access the desired error(s).
Also it turns out the use of a `Map` here is a leftover from one of Play 2 first commits ever - where a `ValidationError` [didn't have a `key` field yet](https://github.com/playframework/playframework/commit/8d644fe0f629bb5213f0d …
=> Use List instead of Map to manage java-form errors

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/http/StandardValues.scala
This fixes an incorrect mime type for XHTML, and adds constants for the XHTML mime type (`application/xhtml+xml`).
=> Fix XHTML mime type

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java
Backport of #7026
(I decided not to add some of the constants in traits for binary compatibility reasons.)
=> [2.5.x] Fix XHTML mime type

framework/project/Dependencies.scala
The upgrade to Apache HttpClient 4.5.x has created an incompability with FluentLenium:
1. FluentLenium depends on selenium-htmlunit-driver
2. selenium-htmlunit-driver depends on Apache HttpClient
And the version required by selenium-htmlunit-driver is not compatible with the new version. This updates FluentLenium to a version that has compabible dependencies.
http://mvnrepository.com/artifact/org.fluentlenium/fluentlenium-core/0.10.9 and http://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-htmlunit-driver/2.48.2
=> [2.4.x]: Fix dependency conflicts

framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java, framework/src/play-java-forms/src/test/java/play/data/ListForm.java, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
Just had this case: When validating a form I want to make sure that all integers [inside a list submitted by the user](https://www.playframework.com/documentation/2.5.x/JavaFormHelpers#Handling-repeated-values) are positiv. This can be done with Hibernate validator via:
```java
import play.data.validation.Constraints.Min;
@Valid
private List<@Min(0) Integer> values;
```
Unfortunataly all our constraints defined in [`play.data.validation.Constraints`](https://github.com/playframework/playframework/blob/2.6.0-M1/framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java) are only allowed  on fields currently. **So right now this doesn't work in Play.**
However Hibernate validator allows you to put constraints on type arguments (`TYPE_USE`) like needed in the case …
=> Add additional @Targets to constraints

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/ModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyResultStreamer.scala
Fixes the issue of "204/304 response didn't trigger onDoneEnumerating for the body", which @bbarkley has reported.
When the response status is 204 or 304, the response doesn't send out with a body. The case of StreamWithNoBody in both Netty server and Akka HTTP server didn't consume the response's empty Enumerator body, thus the onDoneEnumerating hook couldn't be triggered.
Added tests, which fail without the fix.
Create this pull request on behalf of @bbarkley.
=> [2.4.x] 204/304 response should also trigger onDoneEnumerating for the body

framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala, framework/src/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala, framework/src/play/src/test/scala/play/core/parsers/FormUrlEncodedParserSpec.scala
=> Return empty map when parsing uris with empty query strings

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
WIP NEEDS BENCHMARKING
Fixes https://github.com/playframework/playframework/issues/6958
This PR removes the SLF4J-JUL bridge and configuration from LogbackLoggerConfigurator
JUL is not used internally, and if there are any performance considerations, they'll come out in the build.  
Should run through microbenchmarks and prune before merging this.
=> Add LevelChangePropagator

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/releases/release26/migration26/WSMigration26.md
1. Add Netty 4.1 upgrade information
2. Correct some format details
3. Reword a phrase of Akka migration.
=> Improvements and small corrections to migration guide

framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/action/HeadActionSpec.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala
Fixes #4878.
As suggested by @gmethvin (https://github.com/playframework/playframework/issues/4878#issuecomment-125174212), `HEAD` request against ws endpoints will now respond with a Bad Request (`400`).
See #7057 and #7059.
=> WebSocket endpoints returning 400 for HEAD requests

framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala, framework/src/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala, framework/src/play/src/test/scala/play/core/parsers/FormUrlEncodedParserSpec.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
Returns an empty Map when parsing URIs with empty query string.
Fixes #7028.
=> [2.5.x]: Fix empty query string parse

documentation/manual/releases/release25/migration25/Migration25.md
Forward porting from 2.5 branch. See https://github.com/playframework/playframework/commit/c490f506f2a9c136ed15070b54cc1f919ac01b69
=> Typo: CRSF -> CSRF

framework/src/play-java/src/main/java/play/inject/BuiltInModule.java
Seems weird that play.Environment does not have a binding but play.api.Environment does.
=> Make play.Environment injectable

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/commonGuide/filters/Filters.md
Enabled filters was in migration guide, but not mentioned in highlights.
=> Add enabled filters to highlights

documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
This PR provides a reasonable default for Strict-Transport-Security, but only enables it in production.mode.  
This means that applications only have to enable the filter, and don't have to also explicitly configure HSTS.
=> Better HSTS behavior in RedirectHttpsFilter

LICENSE, README.md
Checkout https://github.com/blog/2335-open-source-license-descriptions-and-metadata
I tought it's nice to make use of this GitHub feature.
Also IMHO the sentence in the README is just redundant (and not part of what the APPENDIX in the license says).
Feel free to close this PR if you don't want this.
=> Added LICENSE file to make use of GitHub goodness

documentation/manual/releases/release26/migration26/Migration26.md, framework/project/Dependencies.scala, framework/src/play-jdbc/src/main/resources/reference.conf, framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala, framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
Updates HikariCP to its new version.
See HikariCP changelog for 2.6.0 and 2.6.1 to better understand what changed for this update:
https://github.com/brettwooldridge/HikariCP/blob/dev/CHANGES
=> Update HikariCP to version 2.6.1

framework/src/play-akka-http-server/src/main/scala/akka/http/play/WebSocketHandler.scala, framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/AkkaStreams.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/Probes.scala, framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
This follows a suggestion made by @ktoso and give Akka Streams Inlet/Outlet because it is better for debugging purposes.
=> Change inlet/outlet stream names to improve debug

framework/src/play/src/main/scala/play/api/mvc/Controller.scala
actually request methods were not available in AbstractController
which is a little bit inconvienient since somebody would need
to write them by itself
TODO:
Not sure if a better place might be `RequestExtractors` besides it's not a Extractor in "Scala" sense, but I think it can be called a RequestExtractor also.
=> adds a mixin trait for request methods

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ClientCookieDecoder.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/Cookie.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/CookieHeaderNames.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/DefaultCookie.java, framework/src/play-netty-utils/src/main/java/play/core/netty/utils/ServerCookieEncoder.java, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/main/scala/play/api/mvc/Flash.scala, framework/src/play/src/main/scala/play/api/mvc/Session.scala, framework/src/play/src/main/scala/play/core/j/JavaResults.scala, framework/src/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala, framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
Fixes #7086 
This adds the [`SameSite`](https://tools.ietf.org/html/draft-west-first-party-cookies-07) attribute to the cookie models, and sets it to `Lax` by default for the session and flash cookies.
=> Add cookie SameSite attribute and use for session and flash

documentation/manual/working/javaGuide/main/forms/JavaForms.md
The statement doesn't match the [code](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play-java/src/main/java/play/data/Form.java#L451-L457).
See https://github.com/playframework/playframework/pull/7038#discussion_r107654150
I will tackle this in #7038 for the `master` branch.
=> Fix statement about empty List when using validate()

documentation/manual/working/commonGuide/build/SBTDependencies.md
Fixes a small wording issue in the documentation about managing library dependencies.
=> Small fix to wording in SBTDependencies.md

framework/project/Dependencies.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
This makes it so that:
* Reloader no longer depends on Twirl and is more generic
* We don't try to parse a source file as Twirl unless the extension matches
* It's easier to support other generated sources in the future
=> More generic handling of generated sources

documentation/manual/releases/release26/migration26/Migration26.md, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/data/Form.scala, framework/src/play/src/test/scala/play/api/data/FormSpec.scala
=> POST, PUT, PATCH should ignore querystring params when building form

framework/src/build-link/src/main/java/play/core/BuildLink.java, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
I'd like to refactor more of the Reloader into reusable components if possible. There's a bit of code that's shared between here and Lagom and it'd be nice to have it be an easily callable library.
I couldn't find anything that was using this. Lagom doesn't support it, so it brings the two reloaders a little closer. It also simplifies the code by not needing to support unused functionality. Let me know if there's some external project that depends on it somehow. I did some searches and couldn't find any.
=> Remove unused runSbtTask

framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
`SourceModificationWatch` internally is quite a bit more complicated than what we really are using it for. It calls `sleep` internally, tracks a quiet waiting period, etc. and really all we want to know is have any files been updated.
Once I simplified this implementation it became much clearer to walk through the test and see why it was failing. The issue is that the sleep statements need to be in between compiling and modifying the file.
I'm wondering if a better solution though wouldn't be to setup a second watcher for the classpath using the file watch service. Do we really want the expected behavior of the user modifying `application.conf` within 1s of a compilation to be that the modification is ignored?
=> Simplify timestamp checking and fix dev-mode tests

framework/src/play/src/main/java/play/Logger.java
Some log statements  (especially trace- and debug-level) use parameters that are costly to compute. However, such logging levels are disabled in production. "Lazy" logging allows to log such big messages without explicitly checking if the requested log level is enabled. Still not supported by slf4j logging facade, although log4j 2 and JUL realization provide such methods.
=> Override some log statements in Logger.java to provide lazy logging

framework/project/Dependencies.scala, framework/src/play-filters-helpers/src/test/resources/application-logger.xml
Centralizes logback dependencies inside specs and junit builds.
Removes an obsolete application-logger.xml file.
=> Small refactoring for logback in tests

framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Reasons why:
* Removing makes it easier to share code with Lagom and other projects
* Doesn't work if you have a compile error in project
* Docs are not searchable, so are hard to navigate compared to web
* It's undocumented, so few know it exists
* Required if we want to move to Paradox
The main benefit to the feature is that it makes the docs available offline, but we should be able to add a downloadable link to the docs artifact to fulfill this purpose
=> Remove docs from dev mode

documentation/manual/releases/release26/Highlights26.md
With regards to https://github.com/playframework/playframework/issues/7154 there isn't an explicit warning that default filters may impact sites that are upgrading.
I'll make the logs more explicit as well, so a security failure results in a log with SECURITY marker.
=> Add a note about default filters potentially blocking 

.travis.yml, framework/bin/sourceclear, framework/bin/travis
Previous PR https://github.com/playframework/playframework/pull/7175 didn't take because the build.sbt wasn't at the root.
Calling the script manually should resolve the issue.
=> Add explicit call to sourceclear

framework/src/play-server/src/main/java/play/server/Server.java
Going over some more code, I noticed an opportunity for EnumMap to be used.
EnumMap documentation: https://docs.oracle.com/javase/8/docs/api/java/util/EnumMap.html
EnumMap is basically a Map specifically implemented for when the Map's key is an Enum. It's faster and has a smaller memory footprint than a HashMap. Extremely compact and performant.
I made this little bit of code with some HashMap vs EnumMap loops, for people who want to test it: https://ideone.com/y5mT3d
I scanned the entirety of the playframework github project for use of Maps, this instance is the only one in the entire project that has an Enum for a key, far as I call tell.
EDIT: XmlBodyParser unit test failed for Scala version 2.11.8, something else for 2.12.1. Not sure how it's related.
=> Using EnumMap for mapping enums.

framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala
I've noticed that we don't have compile time dependency injection support for `ObjectMapper` (and `Json`) initialization.
=> Add missing module for ObjectMapper

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala
Fixes #7174. Basically, this makes sure if we add new cookies, any existing cookies with the same name are removed from the list.
=> Make Result#withCookies override existing cookies with the same name

framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
Replaces #6964 because most of the work was done in my previous pull requests regarding Java Forms already anyway.
=> Deprecate form.reject() and form.discardErrors()

framework/src/play/src/main/scala/play/api/http/HttpFilters.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/test/scala/play/api/http/EnabledFiltersSpec.scala
It should be clear to people what filters are enabled on server startup in development, and this is not obvious from the logs.  
This PR ensures that filters are printed out to the log on the first URL request, using a webcommand hook.
This is one of a series of "filter visibility" PRs, see https://github.com/playframework/playframework/issues/7148 as well
=> List enabled filters on startup

framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java, framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
Fixes #7213.
Uses `JavaHelpers.createResult` to incorporate the changes to `Http.Context.current()` into the final `Result`.
=> Include changes to Http.Context in Result from RoutingDsl

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
Fixes #7194.
Fix Akka Server version to correctly deliver empty files.
See issue #7194. Tests were added by @ScalaWilliam in #7195 and cherry-picked here.
=> Fix akka server empty response body

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/commonGuide/configuration/SettingsLogger.md, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala, framework/src/play/src/main/scala/play/api/Logger.scala, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
This PR adds a security marker context, and adds warning log messages tagged with an SLF4J marker when a request fails a security filter.
This serves several purposes:
1. Make people aware why a particular request is failing and why they're getting a 400 code
2. Allow security failures to be marked out distinct from normal Play logging
3. Allow developers to disable security messages with a turbo filter.
May need to add some documentation to show how to turn off the warnings -- essentially in logback.xml you add:
```xml
<turboFilter class="ch.qos.logback.classic.turbo.MarkerFilter">
<Marker>SECURITY</Marker>
<OnMatch>DENY</OnMatch>
</turboFilter>
```
or triggering an email if you're in production (see https://roman-ivanov.blogspot.com/2015/03/neutral-filters-and-evaluator-ordering.html …
=> Add security marker context, tag filter failures

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
For simple requests all the Futures are already completed so avoiding any
overhead of using ExecutionContext brings a ~ 4% improvement.
=> Use FastFuture in Akka Http backend result processing

framework/src/play/src/main/scala/play/api/http/HttpFilters.scala
Under some conditions (seen in examples) the EnabledFilters can print repeatedly, and it should be a @Singleton in any case.
=> Make EnabledFilters a singleton

framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
RequestHeaderSpec will cover this change because it runs concurrently.
Fixes #7229
=> Reuse AbsoluteUri for parsing host in RequestHeader #7229

framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
Fixes https://github.com/playframework/playframework/issues/6041 and https://github.com/playframework/playframework/issues/7037
=> Only call entityManagerContext.pop if the EntityManager is set

framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/test
Fixes #7185. Makes sure RoutesPrefix is generated regardless of whether reverse routes are enabled, since it is used in the generated forwards router.
One of the scripted tests was failing for me locally but it wasn't clear why. Maybe someone more familiar with those tests can help.
=> Make it possible to disable the reverse router

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala, framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala, framework/src/play/src/test/scala/play/libs/XMLSpec.scala, framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
Replaces instances of "new FileInputStream" and "new FileOutputStream" with Files.newInputStream and Files.newOutputStream, respectively.
See https://www.cloudbees.com/blog/fileinputstream-fileoutputstream-considered-harmful for the extended version -- the basic idea is that it reduces GC pauses.
=> Remove FileInputStream/FileOutputStream

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-streams/src/main/java/play/libs/streams/Accumulator.java, framework/src/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala, framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
Background:
Akka HTTP buffers request bodies as "strict" entities in certain
situations. These bodies are available immediately, and don't need
stream materialization to handle them.
Play's action design requires that all request bodies be handled as
streams, since an action is defined to be a Sink that materializes to a
future of the response, so the only way to pass a body into a Play
action is to feed a Source of the body into that Sink. Even if that body
is a 100 byte body that has already been buffered by Akka HTTP as a
strict entity, and even if actions handling is to simply fold all the
byte strings received together, Play's design still requires that this
in memory body be wrapped in a Source.single, and then fed into a
Sink.fold(_ ++ _). No matter how much Akka streams improves …
=> [WIP] Akka HTTP performance improvement for strict requests

framework/project/Tasks.scala
Otherwise, it gets regenerated and reformatted with every compilation.
=> Fix generated PlayVersion.scala formatting

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
- Connection header handling is done in akka-http
- No need to parse headers into akka-http header model
=> Improve result header handling for Akka Http backend

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, documentation/manual/working/scalaGuide/main/http/ScalaActions.md, documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala, framework/src/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala, framework/src/play-integration-test/src/test/scala/play/it/action/ContentNegotiationSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/i18n/MessagesSpec.scala, framework/src/play-test/src/test/scala/play/api/test/HelpersSpec.scala, framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/main/scala/play/api/controllers/Default.scala, framework/src/play/src/main/scala/play/api/controllers/ExternalAssets.scala, framework/src/play/src/main/scala/play/api/http/FileMimeTypes.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/main/scala/play/api/mvc/Action.scala, framework/src/play/src/main/scala/play/api/mvc/Binders.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/main/scala/play/api/mvc/Controller.scala, framework/src/play/src/main/scala/play/api/mvc/package.scala, framework/src/play/src/test/scala/play/api/libs/CometSpec.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/app/controllers/Application.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/app/controllers/Application.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/a/app/controllers/a/A.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/b/app/controllers/b/B.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/c/app/controllers/c/C.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/Application.scala
This provides a new controller `InjectedController` that uses method injection. It also refactors the controller hierarchy to remove duplication, makes `BaseController` the actual base controller trait with abstract `ControllerComponents`, and adds additional information to the migration guide.
=> Add InjectedController and refactor controller hierarchy

framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/main/scala/play/api/http/AcceptEncoding.scala, framework/src/play/src/test/scala/play/api/http/AcceptEncodingSpec.scala
This implements parsing for the Accept-Encoding header. The idea is we can use to determine encoding preference for assets as discussed in #7198.
=> Accept-Encoding parsing

documentation/manual/gettingStarted/IDE.md, documentation/manual/working/commonGuide/configuration/ConfigFile.md, documentation/manual/working/commonGuide/database/Developing-with-the-H2-Database.md
Replaces with references to sbt and sbt shell.
Fixes #7268.
=> Remove references to `play` command

documentation/build.sbt, documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
This documentation change adds more examples of MarkerContext usage to Highlights and logging.
This was previously https://github.com/playframework/playframework/pull/7269 but that PR was misfiled as a playframework branch instead of a wsargent branch.
=> More explicit MarkerContext examples

documentation/manual/releases/release26/Highlights26.md
The example in Highlights was using an action, but was not a controller.  Fixed to extend AbstractController.
=> Fix example timeout

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java, framework/src/play-filters-helpers/src/main/scala/play/api/test/CSRFTokenHelper.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
This PR makes the `TokenInfo` class lazy, so we don't have to even generate the token if the page never chooses to render it. This is a performance optimization in the simple case of rendering a page that doesn't need a CSRF token.
This also performs some other refactoring of our CSRF utilities. There's still a lot of things that could be improved, but the main goal here was to move complexity to the `CSRFActionHelper` that's shared among all the CSRF utilities.
/cc @richdougherty
=> Only add CSRF token if it has been rendered

framework/src/build-link/src/main/java/play/core/Build.java, framework/src/build-link/src/main/java/play/core/server/ReloadableServer.java, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala, framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play-server/src/test/scala/play/core/server/ProdServerStartSpec.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
This change will allow us to delete Lagom's `build-link` project when Lagom is upgraded to Play 2.6
=> Align the BuildLink interface with Lagom

framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
As far as I can tell these settings have never been used and just add extra complication. These are not present in the Lagom reloader, which is a little cleaner
I also reordered to parameters to `startDevMode` to match the ordering in Lagom, which I think was nicer, as it makes it easier for me to follow the logic across the two
After this is merged, I have just one or maybe two changes left to the reload functionality and we will then be able to use the same reloader for Play and Lagom. After the cleanup is done it may make sense to have this be a separate project with its own lifecycle
=> Remove unused classloader settings

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, framework/src/play/src/main/scala/play/api/mvc/MessagesRequest.scala
Renames MessagesAction to MessagesActionBuilder.
Should be inline with the other action builders.
=> Rename MessagesAction to MessagesActionBuilder

documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/components/CompileTimeDependencyInjection.java, documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala, framework/src/play/src/main/java/play/LoggerConfigurator.java, framework/src/play/src/main/scala/play/api/LoggerConfigurator.scala, framework/src/play/src/test/scala/play/api/LoggerConfiguratorSpec.scala
This is useful mainly for test purpose and is also supported (and documented) by Play 2.5.x.
=> LoggerConfigurator should work with empty app config

framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala
Fixes a problem happening in https://github.com/playframework/play-java-dagger2-example/pull/10.
Remove global state access from `Results.bakeCookie`.
=> Remove access to global state while baking result cookies

framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Copies in changes from https://github.com/lagom/lagom/pull/137
Lagom should be able to use this Reloader instead of having its own after this change
This should help for adding Maven support to Play as well because it will be easier to copy what Lagom is doing by aligning the codebases a bit more
I'd appreciate a new milestone release after this is merged if that's not too hard. Lagom is already working on upgrading to Play 2.6 and that would make it slightly easier for me to test out some of these changes with Lagom
=> Enable sharing Reloader with Lagom

framework/src/play-jdbc/src/main/resources/reference.conf, framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
If `hikariConfig.setInitializationFailFast` is called from code, it spits out a runtime warning which is awkward, considering it's in `reference.conf` and therefore always called.
This PR makes the `hikaricp.initializationFailFast` property optional and removes it from configuration, so that there is no warning from HikariCP by default.
=> Make initializationFailFast optional

documentation/manual/releases/release26/Highlights26.md
https://www.playframework.com/documentation/2.6.x/ScalaI18N does not specify the use of custom MessagesApi objects
We need to specify how i18n can be tested, and add the changes to Highlights26.md and JavaI18n / ScalaI18n pages.
Also see https://github.com/playframework/playframework/blob/master/framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala
=> [WIP] Add documentation for testing MessagesApi

documentation/manual/releases/release26/Highlights26.md, documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
This makes sure the new Configuration API is mentioned in the highlights and migration guide. I included a small amount of detail and refer to the Scala configuration docs for more information.
=> Add Scala configuration changes to highlights and migration guide

documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClientTest.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWebServiceClients.java, framework/src/play-integration-test/src/test/java/play/BuiltInComponentsFromContextTest.java, framework/src/play-integration-test/src/test/scala/play/it/routing/ServerSpec.scala, framework/src/play-java/src/main/java/play/routing/RoutingDsl.java, framework/src/play-java/src/main/java/play/routing/RoutingDslComponents.java, framework/src/play-server/src/main/java/play/server/Server.java, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/java/play/BuiltInComponents.java, framework/src/play/src/main/java/play/components/BodyParserComponents.java
Instead of using Scala `BuiltInComponents` in `Server.forRouter`, now uses the Java version.
See #7170.
=> Use Java version of BuiltInComponents in Server.forRouter

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
Previously, we were using the implicit conversion to convert an `Int` status code to a `Status`, but that doesn't work for all possible values.
Fixes #7299
=> Support non-standard response codes on Akka HTTP

framework/src/play/src/main/java/play/libs/Files.java, framework/src/play/src/main/scala/play/api/libs/Files.scala, framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
Try to move files atomically if supported and, if not, fallback to regular moving. It was added as a new API to avoid breaking existent uses of `moveTo` which does not use atomic moves.
This was adapted from Kafka: https://github.com/apache/kafka/blob/d345d53/clients/src/main/java/org/apache/kafka/common/utils/Utils.java#L608-L626
=> API to atomically move the files or fallback if not supported

documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Adds documentation example to WS on timeout for futures.
Futures functionality needs example.
=> [doc] Update WS timeout with examples

framework/src/play/src/main/java/play/i18n/Lang.java, framework/src/play/src/main/scala/play/api/i18n/Langs.scala
There were some 2.5.x deprecated Lang methods still hanging around.
This PR removes them.  Note that the 2.5.x deprecated Play.current() accessors are still around.
=> Remove deprecated lang methods

framework/src/play-test/src/test/java/play/test/HelpersTest.java, framework/src/play-test/src/test/java/play/test/WithApplicationOverrideTest.java, framework/src/play-test/src/test/java/play/test/WithApplicationTest.java
We have these tests for Scala helpers, but not for Java. This was the result of another PR and was sitting in my machine for awhile.
=> Add tests for Java test Helpers

framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java
The `play.mvc.Http.Context#withRequest` method should maintain the original `Session`, `Flash`, and `Response` references, so all changes can be read by `JavaAction`. Otherwise, modifications made inside the action will not be propagated up the chain.
This looks like it has actually been a bug for a while, but we only recently noticed it because we started using this method in `AuthenticatedAction`.
Fixes #7328.
=> Make sure context.withRequest maintains original session and flash

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/javaGuide/main/async/JavaWebSockets.md, documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/resources/reference.conf
Fixes #7335.
Configurable websocket buffer limit. Also add a reference value, which was hardcoded for both Akka and Netty servers.
This should be backported to 2.5.x.
=> Configurable websocket frame max length

documentation/manual/working/commonGuide/production/ConfiguringHttps.md, documentation/manual/working/commonGuide/production/HTTPServer.md, documentation/manual/working/commonGuide/production/code/javaguide/CustomSSLEngineProvider.java, documentation/manual/working/commonGuide/production/code/scalaguide/CustomSSLEngineProvider.scala
This will both keeps better consistency with other sections of our documentation but also avoid an annoying warning that I’ve noticed while writing #7346. Here is an example of this warning in our build:
https://travis-ci.org/playframework/playframework/jobs/232592636#L3259
=> Rename package from java to javaguide

framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/mvc/Controller.scala, framework/src/play/src/main/scala/play/api/mvc/MessagesRequest.scala
This PR adds a BaseControllerHelpers trait that wires everything in ControllerHelpers to ControllerComponents.
Then, it redefines BaseController as BaseControllerHelpers with the Action trait.
Finally, it adds a MessagesAbstractController that extends BaseControllerHelpers, and a MessagesControllerComponents.  
This means that if you want to use MessagesRequest as the base type with an abstract controller, you can do it without interfering with BaseController inheritance or rewiring ControllerHelpers from the ground up.
=> Add MessagesAbstractController

framework/project/Dependencies.scala
This change supports the latest versions of `node` and `npm`
=> Upgrade sbt-js-engine to 1.2.0

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md, documentation/manual/working/scalaGuide/main/tests/ScalaTestingYourApplication.md, documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleHelpersSpec.scala
Adds the stub helpers so that AbstractController is documented.
Also add a couple of missing pages from the testing overview page and add it to the highlights.
Note that this doesn't cover scalatestplus-play as the documentation is in nother repository, and it doesn't cover changes in the Java test helpers (if any)...
=> Add stub helpers into documentation

documentation/manual/working/scalaGuide/main/forms/ScalaForms.md, documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala, documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/implicitMessages.scala.html, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Add messages implicit not found and more forms documentation.
This gives an error message like the following:
```
[play-scala-seed] $ compile
[info] Compiling 10 Scala sources and 1 Java source to
/home/wsargent/work/play-scala-seed/target/scala-2.12/classes...
[error]
/home/wsargent/work/play-scala-seed/app/views/user/form.scala.html:9: An
implicit MessagesProvider instance was not found.  Please see
https://www.playframework.com/documentation/latest/ScalaForms#passing-messages-to-form-helpers
[error]   @helper.inputText(userForm("name"))
[error]                    ^
[error]
/home/wsargent/work/play-scala-seed/app/views/user/form.scala.html:10: An
implicit MessagesProvider instance was not found.  Please see
https://www.playframework.com/documentation/latest/ScalaForms#passing-messages-to …
```
=> Better MessagesProvider implicitNotFound

framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/main/scala/play/api/mvc/Flash.scala, framework/src/play/src/main/scala/play/api/mvc/Session.scala
Remove some deprecated singleton access in the Helpers.
Interestingly enough, even if I call `new Session()` the singleton object deprecation warning still is triggered by the compiler.
Think this is bug.
=> Refactor some singleton access

documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md, documentation/manual/working/commonGuide/server/AkkaHttpServer.md, framework/build.sbt, framework/project/Dependencies.scala, framework/src/play-akka-http-server/src/main/resources/play/reference-overrides.conf, framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http2-support/src/main/resources/reference.conf, framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala
To enable HTTP/2, you can enable the `PlayAkkaHttp2Support` module on your project. This will add the `play-akka-http2-support` module and add the Java agent for ALPN support.
See also playframework/play-scala-tls-example#30
To work in dev mode, the user has to manually add a Java agent for ALPN support. I hope to improve the user experience for this in the future.
=> Add HTTP/2 support module and documentation

framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play/src/main/java/play/mvc/Http.java
The RequestBuilder has a remote connection of 127.0.0.1 but does not pass the AllowedHostsFilter as it does not have a Host header.  This PR adds the Host header directly to the RequestBuilder constructor.
Note that `Helpers.fakeRequest()` does contain the appropriate host header, but in testing it's just as valid to call `new Http.RequestBuilder()` as it is to call `Headers.fakeRequest()`.
=> Initialize Http.RequestBuilder with localhost

documentation/manual/releases/release26/migration26/MessagesMigration26.md
* Adds details about i18nsupport migration needing an implicit request.
* Adds details of using `MessagesRequest` in migration.
=> [doc] Add more explicit migration notes.

documentation/manual/releases/release26/migration26/Migration26.md, framework/build.sbt, framework/project/Dependencies.scala, framework/src/play-forms-joda/src/main/scala/play/api/data/JodaForms.scala, framework/src/play-forms-joda/src/main/scala/play/api/data/format/JodaFormats.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
I'm going to remove https://github.com/playframework/play-joda. Since this is just a legacy support module that is unlikely to change, I don't think it makes sense to have a separate project. It's much easier if we have simple submodules (play-joda-forms, play-json-joda) that are associated with each project.
=> Add joda forms module

framework/src/play/src/main/java/play/libs/concurrent/DefaultFutures.java, framework/src/play/src/main/scala/play/api/libs/concurrent/Futures.scala
Futures were being evaluated immediately, instead of calling at the later point.
=> Use call by name on Futures

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaAsync.java, framework/src/play/src/main/java/play/libs/concurrent/DefaultFutures.java, framework/src/play/src/main/java/play/libs/concurrent/Futures.java, framework/src/play/src/test/java/play/libs/concurrent/FuturesTest.java
The `Future.delayed` method took a `CompletionStage<T>` instead of a `Callable<CompetionStage<A>>`, which meant that an active completion stage was being passed in, instead of only being executed at the time on the delay.  This was pre-existing functionality, as the previous call took a `Supplier` which had the same effect, but `Supplier` is semantically more of an idempotent operation while `Callable` indicates processing.
Also added tests, fixed documentation. and cleaned up javadoc with examples.
Java version of https://github.com/playframework/playframework/pull/7380
=> Make Futures.delayed take Callable<CompletionStage<T>>

documentation/manual/releases/release26/Highlights26.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala, framework/src/play/src/main/java/play/routing/HandlerDef.java, framework/src/play/src/main/scala/play/api/routing/HandlerDef.scala, framework/src/play/src/main/scala/play/api/routing/Router.scala, framework/src/play/src/main/scala/play/core/j/JavaAction.scala, framework/src/play/src/test/scala/play/core/routing/GeneratedRouterSpec.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesModels.scala, framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl, framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/forwardsRouter.scala.twirl, framework/src/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala
This adds a syntax to "tag" routes to modify the behavior of that route. The tags are simply strings, but it's theoretically possible to extract the tags from the `HandlerDef` and implement more complex behavior (e.g. `key=value`).
Route modifiers are introduced using a line beginning with a `+` symbol before the route definition:
```
+ NOCSRF
POST /api/foo/bar ApiController.foobar
```
(leading/trailing spaces are optional)
Fixes #5882, by defining a new `NOCSRF` modifier that can be applied to the route (this can be configured in the CSRF config).
I decided not to use comments as suggested in #5882, since I suspect others are already using comments and did not want to interfere with custom implementations already out there. Traditionally comments should not change the behavior of your …
=> Add route modifier tags and NOCSRF

framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala, framework/src/play/src/main/java/play/Application.java, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
I cleaned up the injector instance used in `BuiltInComponents`, removing an override in `BuiltInComponentsFromContext` (which seems unnecessary) and some components I could not find usages of in our APIs. I also added Scaladoc/Javadoc to clarify how the injector is set up.
=> Simplify compile-time DI Injector and add comments

documentation/manual/working/javaGuide/main/forms/JavaCsrf.md, documentation/manual/working/javaGuide/main/http/JavaRouting.md, documentation/manual/working/javaGuide/main/http/code/javaguide.http.routing.routes, documentation/manual/working/javaGuide/main/http/code/javaguide/http/routing/controllers/Api.java, documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md, documentation/manual/working/scalaGuide/main/http/ScalaRouting.md, documentation/manual/working/scalaGuide/main/http/code/ScalaRouting.scala, documentation/manual/working/scalaGuide/main/http/code/scalaguide.http.routing.routes, framework/src/play-filters-helpers/src/main/resources/reference.conf
Adds documentation for route modifiers in general (though nocsrf is the only one we support now) and the nocsrf modifier in both the routing documentation and the CSRF documentation.
Fixes #7383.
=> Add docs for nocsrf and route modifiers

documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
The example code for [Combining body parsers](https://www.playframework.com/documentation/2.5.x/ScalaBodyParsers#Combining-body-parsers) does not compile when copied into another Controller, because it uses a `file` method that is not part of the example. 
Since the method is a one-liner and not used elsewhere I inlined it in the example.
=> [doc] make combined-body-parser example compile

framework/src/play-akka-http-server/src/main/resources/play/reference-overrides.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
It's better to set these programmatically than use reference-overrides.
=> Remove unnecessary reference overrides for Akka HTTP server

framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala, framework/src/play-ehcache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala, framework/src/play-ehcache/src/test/scala/play/api/cache/ehcache/EhCacheApiSpec.scala
Make sure we bind to the named cache for all cache types, and also bind the default implementation to the default named cache.
Fixes #7401
=> Fix CacheApi bindings

framework/src/play-integration-test/src/test/scala/play/it/action/FormActionSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/scala/play/api/data/Form.scala, framework/src/play/src/main/scala/play/api/http/Writeable.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/test/resources/multipart-form-data-file.txt, framework/src/play/src/test/scala/play/api/data/FormSpec.scala, framework/src/play/src/test/scala/play/api/http/WriteableSpec.scala
Fixes #7356.
Correctly handles form `bindFromRequest` when using a max lengthed body parsers. Proper test was not possible without adding a `Writeable` to handle `MultipartFormData` so this PR also adds this.
The `Writeable` is based on both jroper/playframework@1cb3fdb and https://goo.gl/DTgGkj.
=> Correctly bind form from request when using multipart form with max length

framework/src/play-filters-helpers/src/main/java/play/filters/components/CORSComponents.java, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSModule.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play/src/main/scala/play/api/mvc/Action.scala
All the other built-in filters are already implemented as `EssentialFilter`s, which is more performant. This PR refactors the `CORSFilter` to be an `EssentialFilter` too.
=> Refactor CORSFilter to be an EssentialFilter

framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSComponents.java, framework/src/play-filters-helpers/src/main/java/play/filters/components/CSRFComponents.java
This is a small problem I've noticed in playframework/play-java-dagger2-example#21. Basically, this method declaration is causing a conflict with the default implementation present in `AkkaComponents`.
=> Remove unnecessary method declaration

documentation/manual/releases/release26/Highlights26.md
A user doesn't have to set `TwirlKeys.constructorAnnotations` by him/herself. It's done by Play already:
https://github.com/playframework/playframework/blob/2.6.0-RC1/framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala#L57
With the note users will end up annotating the generated scala class twice (checked it myself):
`class SomeView @javax.inject.Inject()@javax.inject.Inject() ...`
=> Remove unnecessary "@Inject" twirl setting from 2.6 highlights

framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/java/play/data/LegacyUser.java, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
This was a mistake introduced by me.
`clazz.isInstance(obj)` actually checks if `obj` is an instance of `clazz` (and not the other way around).
So in our code correct would be: `Validatable.class.isInstance(result.getTarget())`.
However to avoid any confusion I just use the `instanceof` operator now which is much more clearer what we want to express.
I found out about this problem because I got the warnings displayed from line 487 altough I switched everything to the new validate approach.
=> [Bug] Fix instanceof

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/commonGuide/filters/GzipEncoding.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
(I think) the gzip filter is the only play-provided  filter left which can't be configured solely via `application.conf`.
Would be great if this makes it in before 2.6 final.
=> gzip filter can be configured via black-/whitelist in application.conf

documentation/manual/working/commonGuide/filters/SecurityHeaders.md
Removed duplicated `can`.
Correct a typo in `SecurityHeaders.md`.
Found a typo while reading `SecurityHeaders.md`.
There are no relevant issues / PRs / mailing lists discussions.
=> Correct a typo in SecurityHeaders.md

framework/project/BuildSettings.scala, framework/src/build-link/src/main/java/play/TemplateImports.java, framework/src/play-java/src/main/scala-2.11/play/core/j/JavaImplicitConversions.scala, framework/src/play-java/src/main/scala-2.12/play/core/j/JavaImplicitConversions.scala, framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
Fixes #7406
Since this is just for the templates, I think it's probably justified to use `ToScalaImplicits` and `ToJavaImplicits` from scala 2.12.
I decided to create a trait that's mixed into `PlayMagicForJava` since there are other implicit conversions there, but I could move to a separate object if people think it's a good idea.
=> Don't use JavaConversions in scala 2.12 template imports

documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fixes #7432
The Java to Scala cookies conversion was not considering the `SameSite` attribute.
=> Consider SameSite when converting cookies from Java to Scala

documentation/manual/working/commonGuide/production/Deploying.md
This updates the docs to reference the correct version of sbt-native-packager.
See #7424.
=> Update docs to the used version of sbt-native-packager

framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
Fixes https://github.com/playframework/playframework/issues/7435
SimpleModule was incorrectly declared with braces instead of using a Seq in the constructor parameters, and so the bindings never took effect.  This didn't show up in the tests, because the binding was done directly instead of through the module.
Changed the tests, and made the filter and provider be @Singleton for housekeeping.
=> Fix module in RedirectHttpsFilter

framework/src/play/src/main/java/play/routing/JavaScriptReverseRouter.java
Very simple enhancement: We want to be able to pass the `host` explicitly to `JavaScriptReverseRouter.create` - right now the host is solely determined from the current Http.Context. There can be use cases where you may want to use a different host other than the one from the request or if you want to pre-render and cache stuff where an Http.Context isn't available.
=> Overload JavaScriptReverseRouter.create to pass host explicitly

documentation/manual/working/javaGuide/main/http/JavaSessionFlash.md
This is just a minor update to the docs.
I found it weird to display "an error" after a successful save.
=> Docs: change "an error" to "a message"

documentation/manual/working/commonGuide/configuration/SettingsLogger.md
- changed the location of the `application.log` and `access.log` to the standard `logs/` location of a Play application
- fixed reference to incorrect ACCESS_FILE_APPENDER
Fixes #xxxx
=> Fixed appender references

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala
Fixes #7359.
In this case, we leave it up to the user to decide what to do. If Akka HTTP can't parse the query string, we leave the params map empty and still provide the raw query string in case the user wishes to parse it manually.
=> Don't send 500 error if query string fails to parse

framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/SessionCookieSpec.scala, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fixes #7440 
Cookies for session and flash respecting the sameSite configuration.
This adds tests and also a small refactoring to use `asScala` idiom instead of having a helper method to convert Java cookies to Scala cookies.
See #7432 and #7433.
=> Session and Flash cookies respecting the sameSite configuration

documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala, framework/src/play-integration-test/src/test/scala/play/it/views/DevErrorPageSpec.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/java/play/components/BodyParserComponents.java, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/test/scala/play/api/mvc/MaxLengthBodyParserSpec.scala, framework/src/play/src/test/scala/play/api/mvc/RawBodyParserSpec.scala, framework/src/play/src/test/scala/play/mvc/RawBodyParserSpec.scala
The goal here is to provide sensible defaults for using Play components in a unit testing context. This is done by defaulting constructor parameters and apply methods to empty or singleton versions when possible.
I know this mainly affects the Scala API. This is much more difficult to do with the Java API due to lack of default values.
There are more components we could do this for but I wanted to get an idea of whether this makes sense before I do more.
=> Provide better defaults for manually instantiating components

framework/src/play-server/src/main/scala/play/core/server/ssl/ServerSSLEngine.scala, framework/src/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala, framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/java/play/server/ApplicationProvider.java, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
While this API is internal and wouldn’t be used by users creating application, it could be useful to people integrating with Play.
It will helps us to move from this code:
```java
public class Foo {
public static void main(String[] args) {
play.Environment env = play.Environment.simple();
play.ApplicationLoader.Context context = play.ApplicationLoader.create(env);
play.api.ApplicationLoader loader = play.api.ApplicationLoader$.MODULE$.apply(context.underlying());
play.api.Application application = loader.load(context.underlying());
play.core.ApplicationProvider applicationProvider = play.core.ApplicationProvider$.MODULE$.apply(application);
scala.Option<play.api.mvc.Result> resultOption = applicationProvider.handleWebCommand(someKindOfRequestTranslation());
if (resultOption.isDefined()) { …
```
=> Improve Java app loader/provider

documentation/manual/working/commonGuide/filters/code/GzipEncoding.scala, documentation/manual/working/commonGuide/filters/code/detailedtopics/configuration/gzipencoding/CustomFilters.java, documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/Filters.java, documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/add/MyAppComponents.java, documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/remove/MyAppComponents.java, documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/Filters.java, framework/src/play-filters-helpers/src/main/java/play/filters/components/HttpFiltersComponents.java, framework/src/play-filters-helpers/src/main/java/play/filters/components/NoHttpFiltersComponents.java, framework/src/play-integration-test/src/test/java/play/BuiltInComponentsFromContextTest.java, framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/java/play/components/HttpComponents.java, framework/src/play/src/main/java/play/http/DefaultHttpFilters.java, framework/src/play/src/main/java/play/http/HttpFilters.java, framework/src/play/src/main/scala/play/api/http/HttpFilters.scala
In Java, lists are easier to manipulate (append, filter, etc) than arrays.
=> Use java.util.List instead of an array for Java list of filters

documentation/manual/hacking/Documentation.md, documentation/manual/releases/release26/migration26/MessagesMigration26.md, documentation/manual/working/scalaGuide/advanced/routing/code/ApiRouter.scala, documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala, documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala, documentation/manual/working/scalaGuide/main/cache/code/ScalaCache.scala, documentation/manual/working/scalaGuide/main/config/code/ScalaConfig.scala, documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaActions.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaContentNegotiation.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaResults.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaRouting.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaSessionFlash.scala, documentation/manual/working/scalaGuide/main/i18n/code/ScalaI18N.scala, documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/controllers/HomeController.scala, documentation/manual/working/scalaGuide/main/tests/code/tests/guice/controllers/Application.scala, documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala, framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-specs2/src/main/scala/play/api/test/PlaySpecification.scala, framework/src/play/src/main/scala/play/api/i18n/I18nSupport.scala, framework/src/play/src/main/scala/play/api/mvc/Controller.scala
Removes the deprecated controller references from specs and from example documentation
Fixes https://github.com/playframework/playframework/issues/7390
=> [doc] Remove controller references

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/AkkaRequestTimeoutSpec.scala
Akka HTTP server backend was not considering configuration `play.server.akka.requestTimeout`. We don't have a requestTimeout setting for Netty server backend. This is why the specs here are Akka only.
=> Correct requestTimeout configuration in Akka Server

documentation/manual/releases/release26/migration26/Migration26.md
=> [docs]: Document Akka HTTP timeouts in the migration guide

documentation/manual/releases/release26/migration26/Migration26.md
Fills out Migration26 with more links and fixes some typos.
=> Add links to migration document

documentation/manual/releases/release26/migration26/Migration26.md, documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md, documentation/manual/working/commonGuide/configuration/SettingsNetty.md, framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
Fixes #7172.
Now `play.server.akka.http.idleTimeout` is derived from `play.server.http.idleTimeout` so that we these existing options will be respected by Akka HTTP server backend. The docs were also improved to clarify these with Akka HTTP specific settings (in the namespace
`akka.http.server`).
See also #7067.
=> Consistent configuration for idleTimeout in Akka HTTP server backend

documentation/manual/releases/release26/migration26/Migration26.md
referred to the 2.5 migration guide in case users still depended on removed
Forms functionality.
=> #7052 added note on migrating deprecated Forms code

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play/src/main/java/play/http/DefaultHttpRequestHandler.java, framework/src/play/src/main/java/play/mvc/EssentialAction.java, framework/src/play/src/main/java/play/mvc/Filter.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/java/play/mvc/RangeResults.java, framework/src/play/src/main/java/play/routing/Router.java, framework/src/play/src/main/scala/play/api/mvc/Headers.scala, framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala, framework/src/play/src/main/scala/play/core/j/JavaHttpRequestHandlerAdapter.scala, framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala, framework/src/play/src/test/java/play/mvc/RangeResultsTest.java, framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala, framework/src/play/src/test/scala/play/mvc/RequestHeaderSpec.scala, gravatar.py
Fixes any leftovers of #2240.
This is both consistent with the Scala play.api.mvc.Headers (part of it since this Java version is not as complete as the Scala one) and also with the headers APIs in play-ws.
This Headers API can evolve later, but I kept it small now to avoid bigger changes (since we are very close to release 2.6.0).
See discussion in #2240 and playframework/play-ws#101.
=> Consistent API to get headers from play.mvc.Http.RequestHeader

documentation/manual/releases/release26/Highlights26.md
Amazingly enough, we don't mention global state in the highlights!
Also, it looks like `play.allowGlobalApplication` is also not mentioned in docs, so putting it front and center here.
=> Add allowGlobalApplication to highlights

framework/bin/checkBinaryCompatibility, framework/bin/travis
This enables MiMa so future changes to 2.6.x will be checked for binary compatibility.
=> Add MiMa check to travis

framework/project/plugins.sbt
This includes the fix for the regression in parsing `if` statements without braces: playframework/twirl#140
=> Update twirl version to 1.3.3

framework/project/plugins.sbt
2.6.x is protected so I can't push it directly
```
remote: error: GH006: Protected branch update failed for refs/heads/2.6.x.
remote: error: At least one approved review is required by reviewers with write access.
To github.com:playframework/playframework.git
! [remote rejected]     2.6.x -> 2.6.x (protected branch hook declined)
error: failed to push some refs to 'git@github.com:playframework/playframework.git'
```
=> [Backport 2.6.x] Update twirl version to 1.3.3

documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala
Fixes #7492
- Add `play.filters.https.redirectEnabled` setting for deciding whether to enable the filter, in which case both the redirect and HSTS header are disabled. The default value of `redirectEnabled` is `null`, which only enables the filter in Prod by default.
- If the redirect filter is disabled, this also means the HSTS header is disabled by default in dev mode, as it was before.
- Emit a log message when the filter is disabled.
- Update the documentation to explain these changes, as well as the issue with HSTS in dev mode.
=> Improvements to RedirectHttpsFilter

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Fixes https://github.com/playframework/playframework/issues/7497
The documentation in ScalaWS / JavaWS was not explicit enough about adding failure handing around WS client calls.
=> [doc] Clean up the warnings in WS calls

documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md, documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/dynamic/Module.java
1. There were a handful of instances where the class name `Configuration` was used.  These have been changed to `Config`.
2. In the sample code there was no import statement for `Config` so the reader couldn't easily copy this code.
3. The variable names have been changed to `config` for consistency.
=> [doc] replace instances of play.Configuration with Config

framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/SessionCookieSpec.scala, framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
Fixes #7513
I decided for backwards compatibility any string other than "strict" or "lax" will still map to no SameSite attribute, but I added a warning to encourage the use of `null` explicitly.
=> Make sameSite=null work with session and flash

documentation/manual/releases/release26/migration26/Migration26.md
When migrating existing play apps to `2.6.x.` that are using Joda time and following the migration guide I noticed that the suggested import does not seems to work as expected.
The associated changes add the correct import.
=> Correct import for Joda time json Reads and Writes

framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
When a user switches from one application to another application (i.e. from play-scala-secure-session-example to play-java-dagger2-example) and has JWT cookies active, the JWT cookie in the browser will not be wiped, and will not validate correctly.
This PR replaces the out of the box error message (which is not helpful) with one that details what this means exactly and how to fix it.
=> Add better error message to invalid JWT cookie.

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
Fixes #7495.
This partially reverts some of the code added in #6784, which sets all result MediaTypes to Akka HTTP's Binary type. Since Akka HTTP is very protective of its Binary type we can't use it for multipart content types. So now we try to parse first - which should handle multipart  types - then we fall back to the Binary type as a default.
Cc @jrudolph, @schmitch.
=> Support multipart Content-Type in results

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
This removes the lazy rendering for the CSRF token, because it made too many assumptions about how the token is retrieved. This optimization does not work properly if the token is rendered after the headers are sent, or if the token is needed by client-side JavaScript.
=> Remove lazy rendering of CSRF token

documentation/manual/releases/release26/migration26/JPAMigration26.md, framework/src/play-java-jpa/src/main/java/play/db/jpa/JPA.java
This PR deprecates the `play.db.jpa.JPA` class and points people to the JPAApi.
This should have been in 2.6.0, but there are no code changes involved, only the annotation and docs.
=> Deprecate static JPA class

.travis.yml, framework/bin/whitesource, framework/project/Build.scala, framework/project/PlayWhitesourcePlugin.scala, framework/project/plugins.sbt
Add integration with Whitesource.com. This is not using the support provided by interplay since it would require an update from interplay 1.1.1 to 1.3.6, which changes a lot of things.
See [sbt-whitesource](https://github.com/typesafehub/sbt-whitesource).
=> [2.5.x]: Add whitesource support

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
=> Support multipart Content-Type in results (backport)

framework/src/play-logback/src/main/resources/logback-play-default.xml, framework/src/play-logback/src/main/resources/logback-play-dev.xml, framework/src/play-logback/src/main/resources/logback-play-logSql.xml
Hibernate gives off a spurious warning on start up when Java Forms are being used:
```
HV000184: ParameterMessageInterpolator has been chosen, EL interpolation will not be supported
```
Until https://hibernate.atlassian.net/browse/HV-1323 is fixed, we must suppress the error manually.
=> Suppress Hibernate EL warning

framework/src/play-integration-test/src/test/scala/play/it/http/parsing/ByteStringBodyParserSpec.scala, framework/src/play/src/main/java/play/mvc/BodyParser.java, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/test/scala/play/api/mvc/RawBodyParserSpec.scala
Sometimes you just want to handle the body as a simple buffered ByteString, failing if the body is larger than the configured memory buffer limit, similar to the plain text body parser. The raw body parser doesn't fail when the buffer is exceeded, it buffers to disk, and so is more cumbersome to deal with. This adds a simple ByteString body parser.
Also added the strict Accumulator fast path to the raw body parser, so that when the body is an Akka http strict body, the zero materialization fast path will be taken. Also, the Java buffering body parser wasn't taking advantage of the strict fast path either, so I added that.  
Note that the Java body parsers already has a ByteString body parser, so there was no need to add that.
This change is only binary compatible in Scala 2.12 (it adds a …
=> Added ByteString body parser

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
Follow up for #7498. 
Notice that we can add some missing tests for Java result handling. Also, this moves an XML test from JavaWS to Java result handling specs.
@richdougherty, notice that while looking at another issue.
=> Add new tests to Java result handling

framework/src/play-jdbc/src/main/resources/reference.conf
The exact same configurations can be found in the `play-jdbc-evolutions` project anyway:
https://github.com/playframework/playframework/blob/master/framework/src/play-jdbc-evolutions/src/main/resources/reference.conf
For me it looks like @dotta just forgot to remove it after copying the config into it's own `reference.conf` in the (then newly created) `play-jdbc-evolutions` project in #4380.
=> Remove (duplicate) evolutions configuration from play-jdbc

framework/build.sbt, framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/AkkaResponseHeaderHandlingSpec.scala
currently previous play versions allowed illegal response headers.
however akka-http enforces them, so we check if a response header
is renderable in responses and if not, we convert them to a RawHeader
Fixes #7549
=> only warn the user if a response header is invalid #7549

framework/build.sbt
This backports #7574 to 2.6.x.
=> Add MIMA exclusion (backport to 2.6.x)

framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala, framework/src/play-java/src/main/scala/play/core/ObjectMapperModule.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
=> [2.6.x]: Use ApplicationLifecycle instead of DefaultApplicationLifecycle (#7563)

documentation/manual/working/javaGuide/main/forms/JavaCsrf.md, documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md, framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
A more intelligent implementation of lazy CSRF token rendering. Now we only avoid adding the token to the session/cookie if the following is true:
- The cookie is `HTTPOnly`, meaning we know it's impossible for the browser-side JavaScript to read the token from the cookie and use it client side.
- The body is strict, meaning we know it's impossible the body is still streaming from somewhere and `CSRF.getToken` will be called later.
- `CSRF.getToken` has not been called on that request.
=> Add lazy rendering for CSRF token with HTTPOnly and strict body

documentation/manual/working/scalaGuide/main/tests/index.toc
Update index.toc to include link to `Testing with compile-time Dependency Injection` in the scalatestplus-play repo.
This documentation covers the new test classes to support those who aren't using Guice.
See: https://github.com/playframework/scalatestplus-play/pull/85
=> Update index.toc to include link to `Testing with compile-time Dependency Injection`

framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceInjectorBuilderSpec.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/inject/Injector.scala, framework/src/play/src/test/scala/play/api/BuiltInComponentsSpec.scala
Fixes #7535.
We need to set the thread context ClassLoader before we inject a class, because that class may itself use reflection when it initializes.
This fixes an issue where in dev mode initialization of the @Transactional annotation in dev mode fails to find the application's model classes. This is because in dev mode there are multiple ClassLoaders so we need to be careful about always using the correct ClassLoader when we load classes reflectively or call an API, such as JPA, which uses reflection internally.
=> Make sure injector uses application ClassLoader

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Fixes #7567.
Preserves the order of repeated parameters in query string. While there is no saying in RFC3986 about how to handle repeated params, this is less surprising than having a reverse order.
=> Preserve the order of repeated params in query string

framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
Currently this fixes a bug that all request bodies must be 8 megabyte big or they will fail since akka-http has a default max body size of 8m. currently I tought it's a good idea to actually import all settings so that users can/might fiddle with them.
**This PR should be backported, since else we do not support bodies with > 8m on akka-http**
=> overrides the akka-http max-content-length

framework/src/play/src/main/scala/play/api/data/Forms.scala, framework/src/play/src/main/scala/play/api/data/format/Format.scala, framework/src/play/src/test/scala/play/api/data/FormSpec.scala, framework/src/play/src/test/scala/play/api/data/format/FormatSpec.scala
Fixes #7522.
This is using the `LocalDate` format to bind/unbind `java.sql.Date` since the conversion between these two types is straightforward and supported.
=> Avoid exception when using sqlDate

framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
=> [2.6.x]: overrides the akka-http max-content-length (#7548)

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
=> [2.6.x]: Preserve the order of repeated params in query string (#7573)

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/server/ServerReloadingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala
Fixes #7533.
This fixes a bug that can occur in dev mode where the server and application can end up with different keys for signing and verifying cookies.
At the moment, if the application fails to start in dev mode, e.g. due to an evolutions failure or compile error, the server will load invalid default keys. The server's keys will persist even when the application is properly loaded again. This means that the server and application can end up with different keys. Since the server manages key signing, while the application manages key verification, it becomes possible in dev mode for the server to sign cookies that can't later be verified by the application.
This fix ensures that the key configuration is reloaded when the application starts again or changes, which means that the keys …
=> Reload server HTTP configuration when app changes

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/mvc/StatusHeader.java, framework/src/play/src/main/scala/play/api/mvc/RangeResult.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala, framework/src/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala, framework/src/play/src/test/java/play/mvc/RangeResultsTest.java, framework/src/play/src/test/java/play/mvc/ResultsTest.java, framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala, framework/src/play/src/test/scala/play/api/mvc/ResultsSpec.scala, framework/src/play/src/test/scala/play/core/utils/HttpHeaderParameterEncodingSpec.scala
Fixes #7501.
1. Improve handling of extended characters in filenames, following the definition in RFC 5987.
The previous rendering had a couple of problems. First, it rendered UTF-8 characters into the regular `filename` parameter. Second, its %-escaping of extended characters in the `filename*` parameter used the URI path-segement encoding, which doesn't escape all necessary characters.
In addition, the new handling only renders an extended `filename*` parameter when there are special characters that need escaping.
See:
- https://github.com/playframework/playframework/pull/6042
2. Use a RawHeader with Akka HTTP to avoid the backend parsing and re-rendering the header. There's currently a bug with this that needs to be fixed before we can use a typed header.
See:
- …
=> Fix Content-Disposition filename handling

CODE_OF_CONDUCT.md
Github now has tools to better show CoC, just as it has to licenses.
See https://help.github.com/articles/adding-a-code-of-conduct-to-your-project/
This is copy of https://playframework.com/contributing
=> Add our code of conduct to integrate with Github tools

framework/src/play/src/main/scala/play/api/data/Forms.scala, framework/src/play/src/main/scala/play/api/data/format/Format.scala
Deprecates methods producing a `java.sql.Date` that take a `java.util.TimeZone` and provides extra methods for binary compatibility.
Fixes #7590
=> Deprecate sqlDateFormat with time zone

framework/project/BuildSettings.scala
This fixes a deprecation warning we get when building Play.
=> Fix sbt deprecation warnings in BuildSettings

documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala
The example shown on the play website leads to deprecation warnings: `object Action in package mvc is deprecated (since 2.6.0): Inject an ActionBuilder (e.g. DefaultActionBuilder) or extend BaseController/AbstractController/InjectedController`
This change updates the example to use the action builder in the "new style".
=> Updated ws test example to avoid deprecated syntax

documentation/manual/releases/release26/migration26/Migration26.md
Explains that sbt update to 0.13.15 is required.
See conversation here: https://groups.google.com/d/msgid/play-framework/CAA%3D11Hxr3YdddOguNdngkBgoA-SkchSFQYk9kzo8XycsuNXLPA%40mail.gmail.com?utm_medium=email&utm_source=footer
=> [doc]: Explain that updating sbt is required

framework/src/play/src/main/scala/play/api/libs/Files.scala
Fixes #7584. Uses an `AtomicReference` and retries if the value was changed while trying to update it.
=> Fix race condition creating play temp folder

documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ConfiguredChildActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/HelloActor.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java, documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/ParentActor.java, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java, documentation/manual/working/javaGuide/main/async/code/javaguide/async/MyWebSocketActor.java, framework/src/play-akka-http-server/src/test/scala/play/AkkaTestServer.scala, framework/src/play-guice/src/main/java/play/libs/akka/AkkaGuiceSupport.java, framework/src/play/src/main/java/play/libs/akka/InjectedActorSupport.java
This fixes the small Javadoc error contained in PR #7547 so that it can be merged.
=> Update Actor usage in docs to use AbstractActor, the main Java API since 2.5

framework/src/play/src/main/scala/play/api/mvc/Binders.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/controllers/Application.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/models/UserId.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/conf/routes, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/Application.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/models/UserId.scala, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/conf/routes, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
This fixes the inconsistency in which a `PathBindable` for a custom type does not have its result encoded properly as a path segment, even though `String` path segments are encoded properly. This also adds some Javadoc to the `Parsing` helpers with the necessary warnings.
I also removed the `implicit codec: Codec` parameter from `PathBindable.Parsing` because it was unused, and added an extra constructor for binary compatibility. This will also be source compatible unless the codec was passed explicitly, but that would not have made sense anyway since the extra parameter has no effect.
Fixes #7610
=> Encode path parameter returned from custom PathBindables

framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
Fixes https://github.com/playframework/playframework/issues/7614 
Switch from a synchronized block to a StampedLock.  This means that multiple threads can read the application state and it's only when a reload is happening (and there's a write lock) that other threads attempting a read will be blocked.
Tried this on https://github.com/joymufeng/play-scala-starter-example on a Dell XPS 15 9650 and running 
```
wrk -t4 -c400 -d30s http://localhost:9000/
```
with a warmed up JVM:
```
Running 30s test @ http://localhost:9000/
4 threads and 400 connections
Thread Stats   Avg      Stdev     Max   +/- Stdev
Latency    15.50ms   47.74ms   1.43s    99.08%
Req/Sec     9.03k     1.54k   11.81k    83.61%
1074813 requests in 30.04s, 396.68MB read
Requests/sec:  35782.61
Transfer/sec:     13.21MB
```
=> Use read/write lock to minimize blocking in applicationprovider.get

documentation/manual/working/javaGuide/main/async/JavaComet.md, documentation/manual/working/scalaGuide/main/async/ScalaComet.md
Added hint on how to successfully run the sample code snippets in the comet documentation. There was missing context on miscellaneous configuration that is needed to run the snippets. This is especially useful to someone new following through and trying out the snippets in the documentation.
=> Added hint on how to successfully run snippets in comet docs

framework/src/play-cache/src/main/java/play/cache/CachedAction.java, framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaCachedActionSpec.scala
Fixes #7615.
Instead of using get-and-set the cache, using getOrElseUpdate.
This way the execution won't happen in a ForkJoinPool thread pool, but instead it will fallback all the way down until Scala AsyncCacheApi implementation which uses the application ExecutionContext. Because of that, ContextClassLoaderInjector won't fail to change the ClassLoader for the executing thread.
=> Better use of AsyncCacheApi in CachedAction

documentation/manual/working/scalaGuide/main/async/code/ScalaAsync.scala
Two clarifications for the documentation:
* Spell out more explicitly that you typically get the `Futures` instance via injection.
* Make clear where `TimeoutException` comes from, since it doesn't show up when searching the ScalaDocs.
Fixes #xxxx
=> Proposed fix for #7630

documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala
Fixed example code in documentation.
In this article, because it is assumed all codes are written in the controller class that extends `AbstructController`, `PlayBodyParsers` should be used instead of `BodyParsers.parse`
Play 2.6 Migration Guide.
=> Documentation: use PlayBodyParsers instead BodyParsers.parse

framework/project/BuildSettings.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala, framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala, framework/src/play-microbenchmark/src/main/scala/play/core/server/netty/NettyHelpers.scala, framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala, framework/src/play/src/main/scala/play/api/mvc/request/RequestFactory.scala
Obtain the CookieBakers from application.requestFactory for ServerResultUtils.
Fixes #7659.
=> Fixes #7659:  The session module doesn't work after LegacyCookiesModule is enabled.

documentation/manual/working/javaGuide/main/cache/JavaCache.md, documentation/manual/working/scalaGuide/main/cache/ScalaCache.md, framework/src/play-ehcache/src/main/resources/reference.conf, framework/src/play-ehcache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala, framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
Calling `Future.successful` just returns an already finished `Future` but doesn't process it's body asynchronous. So we are actually blocking. Only `removeAll` did it the non-blocking way right now.
Or do I understand something wrong here?
=> Change how we call Futures in EhCacheApi

framework/src/play/src/main/scala/play/api/libs/Files.scala
Fixes #7667
As noted already, this is not easy to unit test without adding further abstractions. Ideas and feedback how to properly test it is welcome.
=> Fixes resource leakage in DefaultTemporaryFileReaper

framework/src/play/src/main/scala/play/api/libs/Files.scala
Fixes #7569
This changes the log level from info to debug to help avoid confusion
@richdougherty suggested changing the logging level to debug or updating the error message. I checked if `playTempFolder` is empty and if true say no temp folder has been created otherwise display the old message. 
Issue #7569
=> set Files$DefaultTemporaryFileReaper log level to debug

framework/project/Dependencies.scala
Version 1.0.2 has no API changes. See https://github.com/playframework/play-ws/pull/174 for more information.
=> Update play-ws to version 1.0.2

documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java, documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayAkkaHttp.md, documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayNetty.md, documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala, documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala, framework/build.sbt, framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/scala/play/api/Application.scala
Adds new methods to create Akka and Netty servers using components, and then avoiding deprecated methods. We have the same for Java `Server` API.
This can be backported to 2.6.x since it is just adding new APIs.
See [this message from @schmitch in our gitter channel](https://gitter.im/playframework/contributors?at=594fe4438dae425031515775).
=> Create Akka and Netty servers from built in components

documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java, documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayAkkaHttp.md, documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayNetty.md, documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala, documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala, framework/build.sbt, framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/scala/play/api/Application.scala
This is a backport of #7520 with [an additional change](https://github.com/playframework/playframework/pull/7520#discussion_r129967680) to preserve binary compatibility.
=> Create Akka and Netty servers from built in components (backport)

framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala
Running time on my machine was 2.5 minutes, which for both Akka HTTP and Netty tests added 5 minutes to the test suite running time. This reduces the time down to 5-20 seconds. The trickle delay should still work well enough to test the body handling code properly.
=> Make RequestBodyHandlingSpec faster

framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
Removes line breaks from JWT message.
Before, the error message was as follows:
```
[info] p.a.m.DefaultJWTCookieDataCodec - The JWT signature in the cookie does not match the locally computed signature with the server.
This usually indicates the browser has a leftover cookie from another Play application,
so clearing cookies may resolve this error message.
```
which is difficult to read and unnecessary.
=> Remove linebreaks from cookie message

framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java, framework/src/play-java/src/main/java/play/routing/RoutingDsl.java, framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala, framework/src/play/src/main/java/play/mvc/Http.java
Fixes #7682.
Preserve the request body when using `RoutingDsl`. See #7682 for discussion.
=> Preserve request body when using RoutingDsl

framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
This change makes sure we can decode an empty cookie. We just decode to an empty map.
=> Decode empty cookies without an exception

documentation/manual/working/javaGuide/main/sql/JavaJPA.md, framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAConfig.java, framework/src/play-java-jpa/src/main/resources/reference.conf, framework/src/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
- Fix issue of `jpa` key not existing as reported here: https://groups.google.com/forum/#!topic/play-framework/LSqKKEyv8BQ
- Deprecate root `jpa` key in favor of `play.jpa`
- Add JPA config keys to `reference.conf` with a short description of how they are used
=> Improve JPA configuration

documentation/manual/releases/release26/migration26/Migration26.md
Fix play-json-joda dependency in Play 2.6 Migration guide.
=> Fix play-json-joda dependency in Migration26.md

framework/src/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/Build.scala
Those checks are no longer needed 'cause Play now requires Java >= 8
Tries to fix #7697. I guess this will do it, but I'm still running the build.
=> Remove code to handle old Java versions

documentation/manual/working/javaGuide/main/sql/JavaJPA.md, framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAConfig.java, framework/src/play-java-jpa/src/main/resources/reference.conf, framework/src/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
Backport of #7691. Supports both `play.jpa` and `jpa` configuration but will warn if both are used.
=> [2.6.x]: Improve JPA configuration

framework/project/plugins.sbt
Updates twirl to 1.3.4, which does not pull in the scalajs sbt plugin. This will provide a fix for lagom/lagom#852 once Lagom is upgraded.
=> Update twirl to 1.3.4

documentation/manual/working/javaGuide/main/sql/JavaJPA.md, framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAConfig.java, framework/src/play-java-jpa/src/main/resources/reference.conf, framework/src/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
This restores the previous default JPA location back
from "play.jpa" to "jpa", but makes the location
configurable. This means that users won't have to
change their JPA configuration when they update
Play versions.
The configuration location is at "play.jpa.config",
which is similar to "play.db.config". This config
location is advanced usage and I've followed the
lead of "play.db.config" and not documented this
anywhere except in reference.conf.
For reference, the previous behavior was introduced
very recently in PRs #7681 and #7698.
=> Configure JPA at "jpa"; make this configurable

documentation/manual/working/javaGuide/main/sql/JavaJPA.md, framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAConfig.java, framework/src/play-java-jpa/src/main/resources/reference.conf, framework/src/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
This is a backport of #7711 to the 2.6.x branch.
This restores the previous default JPA location back
from "play.jpa" to "jpa", but makes the location
configurable. This means that users won't have to
change their JPA configuration when they update
Play versions.
The configuration location is at "play.jpa.config",
which is similar to "play.db.config". This config
location is advanced usage and I've followed the
lead of "play.db.config" and not documented this
anywhere except in reference.conf.
For reference, the previous behavior was introduced
very recently in PRs #7681 and #7698.
=> [2.6.x]: Configure JPA at "jpa"; make this configurable (backport)

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
In case the CSRF check fails, CSRFAction logs a helpful message. Unfortunately, this message doesn't contain the URI of the request, so it's hard to track down precisely which specific action has an issue. 
This PR adds the request.uri to the relevant log messages.
=> CSRFAction should log the URI when check fails

framework/build.sbt
`play-microbenchmark` isn't meant to be published since it's not a publicly supported module and is only used internally by Play Framework for testing. It also need not be included in the whitesource check for this reason.
=> Don't aggregate play-microbenchmark

documentation/manual/releases/release26/Highlights26.md, documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md, documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
It looks like the link to the chaining implicits documentation has been changed from http://docs.scala-lang.org/tutorials/FAQ/chaining-implicits to http://docs.scala-lang.org/tutorials/FAQ/chaining-implicits.html
=> Fix links to chaining implicits documentation

framework/project/Dependencies.scala
We already get jnotify from play-file-watch so I don't think we need it here. It's confusing since it's a different version from the play-file-watch one.
=> Remove jnotify from direct dependencies

framework/src/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl, framework/src/routes-compiler/src/main/twirl/play/routes/compiler/static/forwardsRouter.scala.twirl
Fixes #7519 
The routes compiler generates code with an unused argument `params` for controllers that do not take any parameters. This leads to the following warning when compiling using Scala 2.6.x when the option `-Ywarn-unused` is set:
`pattern var params in method applyOrElse is never used; 'params@_' suppresses this warning`
This PR suppresses the warning by changing the argument `params` to `params@_`
See the discussion in #7519 for more details
=> Suppress unused arguments warning in generated routes code

framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play/src/test/resources/messages
Fixes #7756
If the [`messages` list](https://github.com/playframework/playframework/blob/2.6.3/framework/src/play-java-forms/src/main/java/play/data/validation/ValidationError.java#L17) inside a Java `ValidationError` contains multiple items, by default the [last item of that list](https://github.com/playframework/playframework/blob/2.6.3/framework/src/play-java-forms/src/main/java/play/data/validation/ValidationError.java#L71) will be shown when calling `error.message()` - so more general errors are stored in the "top" of the list and more "specific" errors at the end (that's how the error messages [get stored](https://github.com/playframework/playframework/blob/2.6.3/framework/src/play-java-forms/src/main/java/play/data/Form.java#L447-L457) when there are any binding failures).
The …
=> Java Form.errorsAsJson should use last item of messages array

framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
EDIT: I sqaushed everything into 1 commit.
While doing a migration, I noticed that the `request.execute(String method)` call was ignoring the actual method.
Sure, there's a `setMethod(String method)` call that does it, but providing a method that accepts a method String and then doesn't use it at all is just plain incorrect.
So this is a quick fix for that. I don't know if this fix is prefered or if it's encouraged people use only `setMethod(String method)` and thus the `execute(String method)` call should be removed?
I checked the Scala file, that seems to have been correct already:
https://github.com/playframework/playframework/blob/3c6ca710a192725ec59d965ad9635c62dd1adecf/framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSRequest.scala#L255-L257
Fixes #7745
Fix a bug in …
=> Method being passed along to an execute method is being ignored

framework/src/play/src/main/scala/play/api/i18n/Messages.scala, framework/src/play/src/test/scala/play/api/i18n/MessagesSpec.scala
When using [custom data binders](https://www.playframework.com/documentation/2.6.x/JavaForms#Register-a-custom-DataBinder)
> When the binding fails an array of errors keys is created, the first one defined in the messages file will be used. This array will generally contain:
> `["error.invalid.<fieldName>", "error.invalid.<type>", "error.invalid"]`
The  the [libphonenumber](https://github.com/googlei18n/libphonenumber) library e.g. provides a `Phonenumber.PhoneNumber` type which is a [nested class](https://static.javadoc.io/com.googlecode.libphonenumber/libphonenumber/8.8.0/index.html?com/google/i18n/phonenumbers/Phonenumber.PhoneNumber.html).
To provide an custom error message when binding the `PhoneNumber` type fails we would have to add following message key the the message file:
``` …
```
=> Allow dollar sign in message key (for inner classes)

framework/project/Dependencies.scala
async-http-client 2.0.35 addresses a security vulnerability in async-http-client.
=> async-http-client 2.0.24 -> 2.0.35

framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala
Fixes #7596.
This update fixes several HTTP/2 related issues. As well as parsing query strings there is now handling for Cookie headers that have been split during [HTTP/2 encoding](https://tools.ietf.org/html/rfc7540#section-8.1.2.5).
=> Update to Akka HTTP 10.0.10

documentation/manual/hacking/Translations.md, documentation/project/build.properties, framework/project/Dependencies.scala, framework/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/project/build.properties, framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/nested-secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/project/build.properties, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/secret/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/project/build.properties, framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/project/build.properties
Backporting https://github.com/playframework/playframework/pull/7794 is the first step of supporting SBT 1.0. We'll need to build with SBT 0.13.16 in order to cross-build the Play plugins to work with SBT 1.0
=> [2.6.x backport] Upgrade to SBT 0.13.16

framework/build.sbt, framework/project/BuildSettings.scala, framework/project/Dependencies.scala, framework/project/Tasks.scala, framework/project/plugins.sbt, framework/src/play-ahc-ws/src/main/scala/play/api/test/WSTestClient.scala, framework/src/play-integration-test/src/test/scala/play/it/ServerIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ApplicationFactory.scala, framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecificationSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ServerEndpoints.scala, framework/src/play-integration-test/src/test/scala/play/it/test/WSEndpointSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/WSEndpointSupport.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/ServerSSLEngine.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play-test/src/main/scala/play/api/test/TestServer.scala, framework/src/play/src/main/scala/play/api/Configuration.scala
Backports two commits from _master_ to _2.6.x_. These PRs add tests for HTTP/2 query string decoding and then update Akka HTTP to fix it.
You might want to not squash these commits to preserve their lovely commit messages. :)
=> HTTP/2 integration tests; update to Akka HTTP 10.0.10 (backport)

framework/project/Dependencies.scala, framework/project/plugins.sbt
`sbt-web` got an issue fixed: https://github.com/sbt/sbt-web/pull/161
I think it would be a good idea to also go over [the dependencies in the 2.6.x branch](https://github.com/playframework/playframework/blob/2.6.x/framework/project/Dependencies.scala) and upgrade them where possible before the 2.6.4 release.
=> Upgrade some dependencies

documentation/manual/releases/release26/migration26/WSMigration26.md
This addresses [play-ws#191](https://github.com/playframework/play-ws/issues/191).
It's worth mentioning because the nearest match for `withHeaders` doesn't have the same behaviour.
Fixes [play-ws#191](https://github.com/playframework/play-ws/issues/191)
See [play-ws#191](https://github.com/playframework/play-ws/issues/191)
See [play-ws#191](https://github.com/playframework/play-ws/issues/191)
See [play-ws#191](https://github.com/playframework/play-ws/issues/191)
=> mention renamings on `WSRequest` in 2.6 migration

documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
This makes the first example in [JavaFileUpload.md](https://www.playframework.com/documentation/2.6.x/JavaFileUpload) consistent with the second one (the test) regarding the usage of MultipartFormData.
I've also been trying to follow these docs to learn Play. At some point somewhere, I've come to start using this for my controller boilerplate:
package controllers;
import play.mvc.*;
import views.html.*;
public class MyController extends Controller {
public Result myAction() {
return ok("change me");
}
}
(I think this comes from `play-java-starter-example`, but I'm not really sure)
By using Http explicitly (in `Http.MultipartFormData<File> body`), I am able to continue using this boilerplate combined with a simple text editor. I don't need to resort to some fancy IDE or anything.
=> Consistency update for JavaFileUpload.md

framework/src/play-exceptions/src/main/java/play/api/PlayException.java, framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play/src/main/java/play/mvc/Result.java
This PR isn't related to any issue, it's just something I wanted to do, don't let reviewing this take time away from your actual work. It's just refactoring regexes into statically compiled versions.
Which means the JVM will not have to compile them again every time they're used. It compiles them once and then uses the object this created.
Also, I saw this one case of a few lines of code just being inside brackets for no apparent reason, so I removed that.
All other changes was Intellij cleaning up whitespace and imports, I can revert that if so desired.
Also a backport can be provided to 2.6.x if wanted.
=> Use statically compiled regexes where possible.

framework/project/Dependencies.scala, framework/project/plugins.sbt
It should be safe to upgrade these dependencies in the 2.6.x branch.
There are also newer versions of `specs2` (3.9.5 and 4.0.0-RC4), `jackson` (2.9.1) and `guava` (23) available, however I am not sure if they are backwards compatible (and necessary) so I just kept them like they are now (except for `jackson` a minor version bump).
If I should change something in this PR let me know.
=> [2.6.x] Update dependencies

documentation/manual/working/javaGuide/main/sql/code/JavaJdbcConnection.java
Probably a copy&paste issue from [another](https://github.com/playframework/playframework/blob/2.6.3/documentation/manual/working/javaGuide/main/sql/code/JavaNamedDatabase.java#L13) example [above](https://www.playframework.com/documentation/2.6.x/JavaDatabase#Accessing-the-JDBC-datasource) this one.
=> Remove wrong comment in docs

framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ApplicationFactory.scala, framework/src/play/src/main/scala/play/api/Application.scala
If these methods are public, they make it difficult to use Macwire with Play, as reported here: https://stackoverflow.com/questions/46092028/macwire-found-multiple-values-of-type
Given that the purpose (as I understand it) is to allow idiomatic usage within `BuiltInComponents`, I think it makes sense to make the methods `protected` here, which would make them no longer a candidate for injection (see https://github.com/adamw/macwire/issues/77).
This still preserves binary compatibility, but would break source compatibility for anyone calling `Action` instead of `defaultActionBuilder` from outside the components class.
=> Switch Action and parse in BuiltInComponents to protected

framework/src/play/src/main/scala/play/api/mvc/Controller.scala
I noticed that the global `Action` was being used here. Probably the result of the various refactorings that went on in this file. `ActionBuilder.ignoringBody` is a special internal helper that simply ignores the body and uses the trampoline execution context.
=> Use ActionBuilder.ignoringBody instead of Action for TODO

framework/src/play-filters-helpers/src/main/resources/reference.conf
Fixes #7823
Appends values to `play.filters.enabled` instead of assigning an array. Necessary so other libraries can also append values to this config within their `reference.conf` without getting overwritten.
It's just the same like we handle `play.modules.enabled`:
https://github.com/playframework/playframework/blob/3c6ca710a192725ec59d965ad9635c62dd1adecf/framework/src/play/src/main/resources/reference.conf#L813-L819
=> Appends filters to play.filters.enabled in reference.conf

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-server/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Fixes #7752
"null" and "infinite" as possible values when configuring server `idleTimeout`.
=> Support null and infinite when configuring timeouts

framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
Fixes some of #6302
This PR changes the reverse routes generator so that `ReverseRouteContext` is only introduced for routes that for `Asset`s. Currently, a `ReverseRouteContext` is introduced for any route with fixed parameters, which causes Scala to issue warnings when the project is compiled with `-Ywarn-unused`
The only of `ReverseRouteContext` I could find was to implicitly convert it into a `PathBindable[Asset]`, so this PR modifies it to fit that use case.
Related issue: #6302
=> Prevent compiler for issuing an unused warning for ReverseRouteContext

framework/src/play/src/main/scala/play/api/libs/concurrent/Futures.scala
https://github.com/playframework/playframework/blob/56456b8e76729a82374e441931f2ad674256aba3/framework/src/play/src/main/scala/play/api/libs/concurrent/Futures.scala#L188
The `withDelay` method above, that enriches a `Future`, as defined now, it accepts an additional `Future` as a parameter instead of using the `Future` that is being enriched.
Such a method doesn't make much sense, I think it should be deprecated and removed in the future.
In this PR I add a new `withDelay` method (not to break backwards compatibility) that accepts only the desired duration as an explicit parameter. So, someone can do the following:
```scala
someFuture.withDelay(2 seconds)
```
=> Add more reasonable FutureOps.withDelay

framework/src/play-cache/src/main/java/play/cache/SyncCacheApiAdapter.java, framework/src/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
=> Make timeout use seconds instead of milliseconds in Java SyncCacheApi

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSFilterSpec.scala, framework/src/play/src/main/scala/play/api/mvc/Render.scala, framework/src/play/src/main/scala/play/api/mvc/Results.scala
Extracts the logic used in GzipFilter to merge the header and uses it in CORSFilter also.
Fixes #7850
=> Merge Vary header properly in CORSFilter

framework/project/BuildSettings.scala
This version was not released properly so should not be used.
=> Exclude 2.6.4 from MiMa checks

framework/project/Dependencies.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/plugins.sbt
We don't need to backport this necessarily; just checking to see if tests pass.
=> Update play-file-watch to 1.1.2

framework/src/play-integration-test/src/test/scala/play/it/http/AkkaRequestTimeoutSpec.scala
Fixes #7669  
##Purpose
Here the purpose is to avoid exception caused because of the less difference in server timeout (300 ms) and the sleep value (400 ms). The problem is solved by increasing the thread sleep time from 400ms to 1400ms.
=> Fix-issue-7669-AkkaRequestTimeoutSpec is flaky

framework/src/play-java/src/main/java/play/libs/Resources.java
I'm pretty sure this is a bug since our tests periodically fail. We need to use the `CompletionStage` returned by `whenComplete` if we want the resulting future to be completed after the `close()`.
=> Use whenComplete properly for asyncTryWithResources

framework/src/play-ehcache/src/test/scala/play/api/cache/ehcache/EhCacheApiSpec.scala
Before we were using the `AsyncCacheApi`, so calling `remove` doesn't block until the remove completes.
=> Remove race condition from EhCacheApiSpec

framework/src/play-akka-http-server/src/test/resources/application.conf, framework/src/play-netty-server/src/test/resources/application.conf, framework/src/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala
Fixes #6412
This alters the log-output from generateSecretTask, as playGenerateSecret should always display the secret even in the case of suppressed logging.
=> Fix-issue-6412-playGenerateSecret to always output

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSCommonSpec.scala
This is a follow up to #7851.
The current behaviour of the CORSFilter is only to serve the Vary:Origin header when CORS headers are served. This means a non-CORS request will not be served the Vary header. So a cache might store a response for a same-origin request and serve it to a user expecting CORS headers, thus breaking CORS.
=> Always add Vary header in CORSHeader

framework/project/Dependencies.scala
Actually I just wanted to upgrade HikariCP so it gets backported in the `2.6.x` branch but then updated some other dependencies as well :smile: 
Please backport, thanks!
=> Update dependencies (minor versions only)

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala, framework/src/play/src/main/scala/play/api/mvc/Headers.scala
This fixes the behavior of `request.headers.remove` and `request.headers.replace` when dealing with headers of a different case. Previously, `remove` and `replace` would not remove or replace a header if the case differed, while `get` and `getAll` would work regardless of case.
=> Fix Akka HTTP headers handling

framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala, framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
As you can see in the snippet below, the [current implementation of `Cached`](https://github.com/playframework/playframework/blob/a9525c22d8bd271425c8781f07e193824f7f1612/framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala#L211) does not wait for `cache.set` to complete before returning the result of the `Action`. 
```scala
cache.set(etagKey, etag, duration)
cache.set(resultKey, new SerializableResult(resultWithHeaders), duration)
resultWithHeaders
```
As I described [in the mailing list](https://groups.google.com/forum/#!topic/play-framework/9XzMWKTKUfg) this can lead to undesired behavior.
> So let's say we have the following endpoints:
>
> - Endpoint A: Its response is cached
> - Endpoint B: When called it invalidates the cached response of endpoint A
>
> And I also …
=> Wait for cache.set in Cached

framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala, framework/src/play/src/test/scala/play/api/mvc/HttpHeaderSpec.scala
Fixes #7892
Makes the tests under HttpSpec common to both AkkaRequestHeader and NettyRequestHeader specifications.
=> Fixes issue-7892 with consolidated test

framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
This fixes a potential bug introduced in https://github.com/playframework/playframework/pull/7868, if an outgoing ContentType can't be parsed as a MediaType.
I rushed this PR here to minimize potential impact, I can add some more test later to prevent any regressions.
@richdougherty @jeffmay
=> Fixes a possible match error in the gzip filter.

documentation/manual/working/javaGuide/main/ws/JavaWS.md
The documentation refers to `asJson` / `asXml`, but the example uses `r.getBody(json())` / `r.getBody(xml())`
* https://www.playframework.com/documentation/2.6.x/JavaWS#Processing-a-response-as-JSON
* https://www.playframework.com/documentation/2.6.x/JavaWS#Processing-a-response-as-XML
=> [doc] Fix inconsistent JavaWS using asJson/asXml

framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/HttpRequestDecoder.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestBodyHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala
Fixes #7911.
The code now filters out the Content-Encoding header instead of all the other headers when decoding the request content.
=> Keep headers when Content-Encoding set

documentation/manual/releases/release26/migration26/WSMigration26.md
Latest versions could be found in central maven repository: [com.typesafe.play/play-ahc-ws-standalone_2.12](https://mvnrepository.com/artifact/com.typesafe.play/play-ahc-ws-standalone_2.12)
=> Update library dependencies to the latest version

documentation/manual/releases/release26/migration26/Migration26.md
Updates documentation/manual/releases/release26/migration26/Migration26.md file with additional mentions of Play 2.6.5 supports sbt 0.13.16 and 1.0.x
=> Mention SBT 0.13.16 / 1.0.x in Play 2.6 Migration Guide #7922

framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ApplicationFactory.scala, framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecificationSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ServerEndpoints.scala, framework/src/play-integration-test/src/test/scala/play/it/test/WSEndpointSpec.scala
Another test changed to use HTTP/2. Includes some minor refactoring to the endpoint testing code.
=> Update FlashCookieSpec to test HTTP/2

framework/project/Dependencies.scala
This fixes a bug that would crash the watcher if a file is created and deleted before the watcher gets a chance to process the creation event.
=> Update play-file-watch to 1.1.3

documentation/manual/working/commonGuide/configuration/WsCache.md, framework/src/play-ahc-ws/src/main/resources/reference.conf, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSModule.scala, framework/src/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/OptionalAhcHttpCacheProviderSpec.scala
Fixes #7863
We currently configure the value of  play.ws.cache.cacheManagerURI using file URI scheme. If configured with a absolute file path, it's ok.  However, if configured with a relative file path, the real file path 
depends on the current working directory.  For example:
```
play.ws {
cache.enabled = true
cache.cacheManagerURI="file:./conf/ehcache-play-ws-cache.xml"
}
```
While running in dev mode,  it's ok, because the real file path is:
```
PROJECT_ROOT/./conf/ehcache-play-ws-cache.xml
```
But in prod mode,  the real file path depends on where you start the project. For example, we start it under the PROJECT_ROOT/bin directory, the real file path will be:
```
PROJECT_ROOT/bin/./conf/ehcache-play-ws-cache.xml
```
So FileNotFoundException will be thrown.
This PR resolves this …
=> Fixes #7863: Support both cacheManagerResource and cacheManagerURI properties of AhcHttpCacheConfiguration, use cacheManagerURI first.

documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
This docs improvement aims to save time of developers that are using Heroku to host their apps on and have possible troubles with migrating to Java 9 according to the fact that Heroku uses OpenJdk 8 by default.
=> Improve Heroku deploying docs (deploying project that depends on Java 9)

framework/project/Dependencies.scala
This version uses a version of directory-watcher that also has debug logging and logging of exceptions, which should make it easier to track down bugs in the future.
=> Update to play-file-watch 1.1.5

documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/commonGuide/database/Evolutions.md, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/commentsyntax/1.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/commentsyntax/2.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/commentsyntax/3.sql, framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsReaderSpec.scala
* Enables support for SQL92-style comments in Play Evolutions scripts in addition to the older MySQL style
* Replaces the older MySQL-style comments in play-jdbc-evolutions with SQL92-style comments (for generated Evolutions, etc.)
* Includes a new test for recognizing files in both MySQL and SQL92 comment syntax.
* Updates documentation to feature the new default style
MySQL-style comments can cause syntax errors in linting tools and IDEs when using another database's SQL dialect. By conforming to SQL92-style comment syntax everywhere, there will be less confusion and enable more flexibility in evolutions.
[Mailing list thread](https://groups.google.com/forum/#!topic/play-framework-dev/knKA5aGbFq8)
=> Play-JDBC-Evolutions - SQL92-style comment syntax support

framework/src/play/src/main/java/play/mvc/Action.java, framework/src/play/src/main/scala/play/core/j/JavaAction.scala
Follow up on #7964
As opposite to `delegate` it would be a valuable information to also have the `precursor` of an action in the Java action composition chain. (That makes the composition chain kind of like a double linked list).
That - with #7964 (for some cases) - would allow us to travel forth and backwards in the composition chain and look up things like "are there any (more) actions defined on an action/controller via an annotation are coming/have been processed already?" or "I am to last/first action method of a specific type?" and much much more.
=> Provide an action the information about its precursor

documentation/manual/working/commonGuide/configuration/WsSSL.md
Fixes #7962 
Fixes the bug  in documentation that is caused by migration from typesafehub to lightbend.
=> Fix documentation issue for WS SSL

documentation/manual/releases/release26/migration26/JavaConfigMigration26.md
Fixes #7971 
Fixes Java Config Migration docs not available
Similar to Issue #7962
=> Fixes Java Config Migration docs not available

framework/src/play-java/src/main/java/play/libs/Jsonp.java
`text/javascript` is deprecated in favor of `application/javascript`
=> Use constant to refer to javascript mime type

documentation/manual/working/commonGuide/production/Deploying.md, framework/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
This includes improved support for building Docker images in [version 1.3.0](https://github.com/sbt/sbt-native-packager/releases/tag/v1.3.0).
Specifically, it uses a new Docker feature to copy files and `chown` them in a single layer. Previously it did this in two separate `Dockerfile` steps, effectively doubling the size of Docker images it built.
Would like if this can be backported to Play 2.6.x.
=> Update sbt native packager to 1.3.1

framework/src/play/src/main/scala/play/api/mvc/Filters.scala
I noticed this when tracing through some filter construction logic, and figured I might as well submit a patch. The match here is superfluous because `h` is, by definition, always of the type `EssentialAction`.
I also added the explicit return type, because IntelliJ nagged me to.
If this sort of thing is too small to open PRs over, feel free to just close it. 😃
=> Removes a superflous match that contains unreachable code.

documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
The solution is documented here: https://www.playframework.com/documentation/2.5.x/ScalaWS#Streaming-data
--> The JavaDoc doesn't have this TODO
TODO in ScalaBodyParsers documentation, https://www.playframework.com/documentation/2.5.x/ScalaBodyParsers#Directing-the-body-elsewhere
=> Fix TODO in BodyParser documentation -- Wrap source body within StreamedBody

framework/src/play/src/test/scala/play/api/libs/concurrent/FuturesSpec.scala
I've seen at least one test failure where the value was `300L` exactly. We are delaying the future by 300ms then checking the difference from the start, so in some cases it could be 300 exactly depending on how things are scheduled.
=> Fix timeout check in FuturesSpec

framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Before we were using `valueLoader.load(conf, key)` for each key in the map, but `ConfigLoader` accepts a path, not a key. So if you have a key like "foo.bar" in your map, it will assume that's actually a path with two components. By escaping and quoting we can make sure our key is actually treated as a key.
=> Fix Map ConfigLoader for keys containing dots or special characters

framework/project/BuildSettings.scala, framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala, framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala, framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/action/FormActionSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ApplicationFactory.scala, framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala, framework/src/play/src/main/java/play/ApplicationLoader.java, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/ApplicationLoader.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala, framework/src/play/src/main/scala/play/core/ApplicationProvider.scala, framework/src/play/src/test/scala/play/api/BuiltInComponentsSpec.scala, framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala, framework/src/play/src/test/scala/play/core/test/package.scala
WebCommands let the application add code that (a) runs before any other code in the application and (b) hook into the dev mode build to do things like restart the application.
As far as I know WebCommands is only used by Play's Evolutions code.
This change simplifies the WebCommands implementation by injecting the BuildLink into the application so that the DefaultHttpRequestHandler can manage WebCommand execution without needing to interact with as much code in DevServerStart.
BuildLink and SourceMapper are provided in a new DevContext object that encapsulates the interface between a Play application and the dev mode container. In the future we can simplify the DevContext interface further, e.g. remove the dependency on BuildLink and just supply the minimum that we need to support …
=> Move WebCommands (e.g. evolutions) inside application code

documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
=> Fix example to only use last part of filename

documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md, framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionActionCreator.java, framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java, framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play/src/main/java/play/mvc/Action.java, framework/src/play/src/main/scala/play/core/j/JavaAction.scala
When using action composition in Play Java there is no way to find out if the current executed action annotation was defined on a controller class or on an action method.
For some use cases that would be a very valuable information. E.g. in https://github.com/schaloner/deadbolt-2-java/pull/50 we are working towards a solution where deadbolt-contraints defined on an action method can fallback to the constraints defined at controller level (if desired by the developer). Unfortunately such things are impossible right now since we don't have any clue where an action was defined.
With this pull request we now get a field `origin` which provides us an enum value with the origin:
```java
public class SomeAnnotationAction extends Action<SomeAnnotation> {
@Override
public CompletionStage<Result> …
```
=> Provide an action the information about its origin

framework/project/Dependencies.scala
A new lib would be fetched - the "Spring Commons Logging Bridge": `spring-jcl`. However I think we don't need that one. See: 
https://github.com/spring-projects/spring-framework/tree/v5.0.1.RELEASE/spring-jcl
https://github.com/spring-projects/spring-framework/blob/v5.0.1.RELEASE/spring-jcl/spring-jcl.gradle
https://github.com/spring-projects/spring-framework/blob/v5.0.1.RELEASE/spring-jcl/src/main/java/org/apache/commons/logging/package-info.java#L2-L23
=> Upgrade Spring dependency

framework/src/play/src/main/java/play/mvc/Action.java, framework/src/play/src/main/scala/play/core/j/JavaAction.scala
Backports #7965
We do need this in the next 2.6.x release since it *is* useful for us right *now*.
=> [2.6.x] Provide an action the information about its precursor (#7965)

framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayFilters.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayLayoutPlugin.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayLogback.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/README, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/src/main/resources/application.conf, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/src/main/resources/routes, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/src/main/scala/controllers/HomeController.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/test, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/README, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/src/main/resources/application.conf, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/src/main/scala/controllers/HomeController.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/src/main/scala/router/Routes.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/test
Fixes #7991.
Splits the current `Play` plugin into a `PlayService` and `PlayWeb` plugin.
`PlayService` uses the standard maven layout and doesn't automatically add template support, sbt-web, or routes file support. Support for routes can be easily added using the `RoutesCompiler` sbt plugin. The old Play layout can be added by adding `PlayLayoutPlugin`.
Eventually the `PlayService` plugin could also be the base plugin for Lagom services.
=> Create minimal sbt plugin for Play services

documentation/manual/working/commonGuide/server/NettyServer.md, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
The Netty `HTTP_SERVER` request tag was never set.
Also the docs were buggy (the tags are a `<String, String>` map).
BTW: I know tags are deprecated, I will provide another pr for this.
=> Actually set the netty request tag

documentation/manual/working/javaGuide/main/http/JavaBodyParsers.md
Switching to 'K' instead of 'kb'. Using 'kb' causes the app to crash.
=> Fixing example value for maxMemoryBuffer on 2.6.x documentation

framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
Follow up on #8011, since this value is used by the deprecated `Play` plugin and should match the original value of `defaultSettings`.
=> Fix defaultSettings to refer to both webSettings and serviceSettings

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
IIUC, `AkkaHttpServer` doesn't need to stop the actorSystem it runs on. It is provided externally so I would expect the invoking code to manage the termination.
* In `ProdServerStart` the actorSystem used is the one from the `Application`. When `AkkaHttpServer` stops the application the actor system is terminated. In this case, the removed line is a noop.
* In `DevServerStart` the `ServerContext` has a custom `stopHook` that stops the actorSystem custom-created for the server. In this case, the removed line actually terminates the actor system and the custom `stopHook` becomes a noop.
=> Removes unnecessary actorsystem.terminate

documentation/manual/working/commonGuide/server/NettyServer.md, documentation/manual/working/commonGuide/server/code/SomeJavaController.java, documentation/manual/working/commonGuide/server/code/SomeScalaController.scala, framework/src/play/src/main/java/play/libs/typedmap/TypedKey.java, framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java, framework/src/play/src/main/scala/play/api/libs/typedmap/TypedKey.scala, framework/src/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
Don't use tags in the documentation, it's deprecated. Use request attributes instead.
=> asScala/asJava for TypedMap and TypedKey + docs update

framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayLogback.scala
This makes it easier to build minimal projects without using the Play plugin.
I also added the `playCore` import for the `play` library. This is useful when building libraries based on Play where you don't want to use the Play plugin.
=> Add imports to PlayImport

documentation/manual/working/commonGuide/server/NettyServer.md, documentation/manual/working/commonGuide/server/code/SomeJavaController.java, documentation/manual/working/commonGuide/server/code/SomeScalaController.scala, framework/src/play/src/main/java/play/libs/typedmap/TypedKey.java, framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java, framework/src/play/src/main/scala/play/api/libs/typedmap/TypedKey.scala, framework/src/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
Backports #8036 but without deprecations.
=> [2.6.x] asScala/asJava for TypedMap and TypedKey + docs update

framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-integration-test/src/test/scala/play/it/routing/ServerSpec.scala
Fix TODO task for Akka HTTP Server: Get `clientCertificateChain` information when it is available.
See https://github.com/akka/akka-http/issues/1104.
=> Get clientCertificateChain information for Akka HTTP server

framework/build.sbt, framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala, framework/src/play/src/test/scala/play/api/mvc/InMemoryTemporaryFileCreator.scala, framework/src/play/src/test/scala/play/api/mvc/MultipartBodyParserSpec.scala
Fixes #7936 
The PR check IOResult provided by FileIO.toPath when a temporary file is created.
If file creation fails, the error is reported to error handler.
=> Fixes #7936 Check failure when writing an uploaded file

framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
In the deprecation message for `start`, there's a recommendation to run `testProd` which is deprecated too.
The deprecation message for `testProd` recommends using `runProd`.
This change updates the deprecation message of `start` to avoid the double indirection and instruct users to go straight to `runProd`.
=> Removes double indirection

framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fixes #7866
Improve the error message when when a Java controller method returns a null `Result`.
=> Improve error message when result is null

documentation/manual/working/scalaGuide/main/http/code/ScalaErrorHandling.scala
The ScalaErrorHandling.scala file contains a useless semicolon while importing a package.
Update the documentation to remove the useless semicolon.
=> Remove useless semicolon from ScalaErrorHandling.scala

framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
`.get[Option[String]]("some.key")` and `.getOptional[String]("some.key")` should have the same behaviour, however that isn't the case. Right now when calling `.getOptional[String]("some.key")` and `some.key = null` we get an exception where I would expect to get `None` instead:
```
[info] Caused by: com.typesafe.config.ConfigException$Null: reference.conf @ /reference.conf: 41: Configuration key 'some.key' is set to null but expected STRING
[info] 	at com.typesafe.config.impl.SimpleConfig.throwIfNull(SimpleConfig.java:142)
[info] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:188)
[info] 	at com.typesafe.config.impl.SimpleConfig.find(SimpleConfig.java:193)
[info] 	at com.typesafe.config.impl.SimpleConfig.getString(SimpleConfig.java:250)
[info] 	at …
```
=> Fix play.api.Configuration.getOptional

framework/project/Dependencies.scala
This change upgrades Akka HTTP to [recently release](https://doc.akka.io/docs/akka-http/current/scala/http/release-notes.html) 10.0.11 which is necessary to complete https://github.com/lagom/lagom/pull/1054.
#fixes #7995
=> Bumps AkkaHttp version

documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/FiltersTest.java, documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java, framework/src/play-integration-test/src/test/java/play/BuiltInComponentsFromContextTest.java, framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play-java/src/main/java/play/routing/RoutingDsl.java, framework/src/play-java/src/main/java/play/routing/RoutingDslComponents.java, framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala, framework/src/play-java/src/main/scala/play/routing/RoutingDslModule.scala
Fixes #7682
Scala's BodyParser resulting bodies are not handled by Java RequestBody API. By using a Java BodyParser, we can ensure that RoutingDsl actions are executed like regular Java Actions internally.
=> [2.6.x]: Use a Java BodyParser in RoutingDsl

framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-microbenchmark/src/test/scala/play/core/server/netty/NettyHelpers.scala, framework/src/play-netty-server/src/main/resources/reference.conf, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
For akka-http we [already have](https://github.com/playframework/playframework/blob/2.6.7/framework/src/play-akka-http-server/src/main/resources/reference.conf#L37-L41) this setting:
```
play.server.akka.server-header = ...
```
which is implemented [here](https://github.com/playframework/playframework/blob/2.6.7/framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala#L98).
This pull request now adds the same feature for the Netty backend:
```
play.server.netty.server-header = ...
```
Please backport this to 2.6 because I need this to get the TechEmpower benchmarks working with the netty backend. All the Play benchmarks (which all use akka-http now) just set the `server-header` config, which allowed me to get rid of filters and action compositions which …
=> Easy way to set server-header when using Netty

framework/src/play-java/src/main/java/play/routing/RoutingDsl.java
Add missing deprecated annotations to RoutingDsl.
See PR #8077.
=> [2.6.x]: Add missing deprecated annotations to RoutingDsl

framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
* N/A
* N/A
* I didn't not change any functionality, I'll be happy to improve the exception management tests if you think it's worth it.
Fixes #8023
Check that the transaction is active before to roll it back and add logging if any exception is encountered during the rollback.
I started to look at #8023 and followed the advises. I looked at the JPA documentation in order to choose a better exception type to catch
[JPA EntityTransaction documentation](https://docs.oracle.com/javaee/6/api/javax/persistence/EntityTransaction.html#rollback())
=> Fix #8023 - Don't ignore exceptions thrown during JPA rollback

documentation/manual/working/javaGuide/main/akka/JavaAkka.md, documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md, framework/src/play/src/main/resources/play/reference-overrides.conf, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/test/resources/application-infinite-timeout.conf, framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
Since Akka 2.5 there's a JVM shutdown hook enabled by default. That competes with Play's shutdown hook when stopping the process.
This PR also replaces `ActorSystemProvider`'s stopHook to use Akka's CS instead of an explicit `actorSystem.terminate()`. The code only runs last phases of CS (not clustering shutdown) as it is not Play's responsibility to setup a hypothetical Akka cluster. Users of Akka cluster within Play already have to handle shutdown themselves.
=> Disable Akka-CS's JVM shutdown hook [2.6.x]

framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala, framework/src/play-microbenchmark/src/test/scala/play/core/server/netty/NettyHelpers.scala, framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
This field was unused. On top of that, it was reloading the HttpConfiguration more often than required. This could result in warnings about the use of deprecated config parameters such as `play.crypto.secret` on every connection.
=> Remove httpConfiguration from ServerResultUtils

framework/project/BuildSettings.scala
`2.6.8` had a build failure when releasing so not all artifacts are available on bintray/maven central. 
Mima validation must ignore `2.6.8`
=> Ignores 2.6.8 when validating mima compat

framework/src/play/src/main/scala/play/api/mvc/Binders.scala, framework/src/play/src/main/scala/play/api/mvc/macros/BinderMacros.scala, framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala
currently it is very repetitive to generate PathBindable's for every AnyVal
so I created a small (understandable) macro that will implicitly
generate the AnyVal PathBindable's whenever needed
I will try to make it possible for QueryBindable's, too. (after the pr is merged)
(this PR can probably be backported)
=> makes it possible to have implicit PathBindable's for AnyVal

framework/project/BuildSettings.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/utils/InlineCache.scala
Objects that are referenced only by a weak reference will be eagerly
collected on the next GC run. Using a soft reference ensures that the
referent is only collected when there is memory pressure.
This should improve the utilization of the cache and reduce the need to
repopulate it.
See discussion in https://stackoverflow.com/a/299702/29470 for example.
I'm not sure whether this is actually a good idea, but I wanted to propose it for discussion. 😄 
ATTN: @richdougherty
=> Make InlineCache use a soft (not weak) reference

framework/project/BuildSettings.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/utils/InlineCache.scala
This is a backport of #8086 to the 2.6.x branch. cc @TimMoore
=> [2.6.x]: Make InlineCache use a soft (not weak) reference

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/http/HttpFiltersSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlaySource.scala
Fixes #8089
This refactors the request handling code in the `AkkaHttpServer` and `NettyServer` slightly, so that the action is always executed in a future using the Play default execution context, then that future is flatMapped with a function that runs the body accumulator, and the resulting future is recovered using the error handler.
I added a test that tests with both the `Filter` and `EssentialFilter` case.
=> Send errors from filters to the application HttpErrorHandler

framework/src/play/src/main/resources/play/reference-overrides.conf, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
Akka `2.5.8` introduced the `Reason` argument on the `CoordinatedShutdown` API so CS users can distinguish the actual trigger of the shutdown process.
Akka `2.5.8` also introduced the `jvm-shutdown-hooks` setting to make sure there's a single responsible for registering JVM shutdown hooks. This setting should be disabled on Play's `2.6.x` branch.
=> Use Akka's Reason when shutting down and disable Akka JVM hooks globally

framework/src/play/src/main/resources/play/reference-overrides.conf, framework/src/play/src/main/resources/reference.conf
This undoes some of the changes from #8053 that we now believe to be detrimental.
See discussion at https://github.com/playframework/playframework/pull/8053#discussion_r153903732
=> [2.6.x] Stop overriding run-coordinated-shutdown-when-down

framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala, framework/src/play-microbenchmark/src/test/scala/play/core/server/netty/NettyHelpers.scala, framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
Backport of #8085 to the 2.6.x branch.
=> [2.6.x] Remove httpConfiguration from ServerResultUtils

documentation/manual/working/commonGuide/production/code/assembly.sbt
The documented configuration for sbt-assembly is incomplete. This adds the necessary merge strategy to make it work with sbt.
https://github.com/sbt/sbt-assembly#merge-strategy
=> [docs]: Document merge strategy for sbt-assembly-plugin

documentation/manual/releases/release27/Highlights27.md, documentation/manual/releases/release27/index.toc, documentation/manual/working/javaGuide/main/forms/JavaForms.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/customconstraint/ValidateWithDB.java, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/customconstraint/ValidateWithDBValidator.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java, framework/src/play-java-forms/src/test/java/play/data/GreenValidator.java, framework/src/play-java-forms/src/test/java/play/data/RepeatableConstraintsForm.java, framework/src/play-java-forms/src/test/java/play/data/validation/TestConstraints.java, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play/src/main/java/play/libs/AnnotationUtils.java
In `master` branch we upgraded to Hibernate Validator 6 which [made all it's constraint annotations `@Repeatable`](https://github.com/hibernate/hibernate-validator/pull/493). This PR does the same for the constraint annotations play-java offers.
This allows a user to e.g. apply multiple `@ValidateWith`, etc. on the same element or use groups to choose when a certain constraint annotation should be used, even when an other group needs the same constraint annotation on the same element. Very nice actually, makes the form validation much more flexible...
```
@Validate(groups={GroupA.class})
@Validate(groups={GroupB.class})
public class MyForm {
@ValidateWith(MyValidator.class)
@ValidateWith(MyOtherValidator.class)
@Pattern(value="[a-k]", message="Should be a - k")
@Pattern(value="[c-v]", …
```
=> Make constraint annotations @Repeatable

framework/src/play-docs/src/main/scala/play/docs/DocServerStart.scala
Uses regular routes and actions instead of WebCommands to server documentation pages.
See #7986.
=> Fix documentation server run

framework/project/Dependencies.scala
Fixes **a regression which could cause a core-dump when using one of the native transports (!)**
http://netty.io/news/2017/12/18/4-1-19-Final.html
=> Upgrade netty 

framework/project/BuildSettings.scala, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala, framework/src/play-streams/src/main/scala/play/api/libs/streams/GzipFlow.scala
Allow user to specify the compression level to use for the underlying Deflater instance, and switch the default compression level from Deflater.BEST_COMPRESSION to Deflater.DEFAULT_COMPRESSION.
Mailing list discussion: https://groups.google.com/d/topic/play-framework/xjgcXPsRvyo/discussion
In a not very scientific microbenchmark where I compress a 600kb webpage 100x for each compression level I got the following (on the second run so things have had a chance to JIT): 
[info] application - Level 1: 619,883 -> 111,773, 18.03130590772775%, nanos: 531,628,867, 11177300
[info] application - Level 2: 619,883 -> 87,209, 14.068622627173193%, nanos: 549,247,847, 8720900
[info] application - Level 3: 619,883 -> 94,679, 15.27368874448888%, nanos: 731,691,153, 9467900
[info] application - Level 4: …
=> Add GzipConfig.compressionLevel

documentation/manual/working/javaGuide/main/http/JavaActions.md
The link to `play.mvc.Results` class methods is correct, but its name in the text is `play.mvc.Result`, which is not correct. This can be misleading since there's a different class named `play.mvc.Result` with its own methods.
=> fix Results class name in the doc

documentation/README.md
Hi,
The link `(https://github.com/playframework/play-doc]` redirect to `https://github.com/playframework/play-doc%5D` 
which is not reachable.
Fixes #xxxx
=> Correct play-doc link

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSCommonSpec.scala
Fixes #8108.
Fixes the serveForbiddenOrigins flag to allow both invalid and forbidden Origins to be served as non-CORS requests.
Previously the test in CORSCommonSpec used the Origin `http://www.example.com` in the "forbidden" test case (line 75). This Origin is the same as the Host set on the default FakeRequest. This meant that the test case would pass, as it would be recognized as a same-origin request.
The Origin on the forbidden test case has been changed to one that is neither in the whitelist, nor the Host on the default FakeRequest. Added an additional case within filterRequest in AbstractCORSPolicy to match a non-empty, valid Origin with the serveForbiddenOrigins flag set.
No new files so no copyright headers …
=> This fixes AbstractCORSPolicy's inability to serve valid but forbidden origins

framework/project/BuildSettings.scala, framework/src/play/src/main/java/play/routing/Router.java, framework/src/play/src/main/scala/play/api/routing/Router.scala, framework/src/play/src/test/scala/play/api/routing/RouterSpec.scala
Hey guys,
This is a small PR to make Router objects composable by adding an `append` method. Effectively this adds a `Monoid` instance for the `Router` type (I didn't want to make that explicit since the framework doesn't currently depend on any library that provides a `Monoid` typeclass, like `play-functional`, but that's essentially what it is). 
This is useful because then you can have traits that extend BuiltInComponents and add their own routes to whatever is already there using the stackable trait pattern. Example:
```
trait FooComponents extends BuiltInComponents {
lazy val fooRouter = Router.from {
// router definition here, e. g. using SIRD
}
abstract override def router: Router = fooRouter.append(super.router)
}
```
This really helps to create more modular applications, because …
=> make Routers composable

framework/src/play/src/main/scala/play/api/Configuration.scala
In Lagom, clients require an `application.conf` [lest an exception be thrown](https://github.com/lagom/lagom/issues/412).
To mitigate this, passing `allowMissingApplicationConf` to `Configuration#load` would be perfect. Unfortunately, it is only part of the private API. 
This PR adds `Configuration#load` (with `allowMissingApplicationConf`) to the public API.
=> add `play.api.Configuration#load` to the public API

framework/src/play-akka-http-server/src/main/resources/reference.conf, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play/src/main/resources/reference.conf
Fixes #8096.
The request timeout should be `Duration.Inf` when `play.server.akka.requestTimeout` is null.
=> Fix akka-http server configuration for request timeout

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala, framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/001.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/0010.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/002.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/005.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/01.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/010.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/0100.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/02.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/05.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/4.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/6.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/7.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/8.sql, framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/9.sql, framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsReaderSpec.scala, framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/LogbackCapturingAppender.scala
Fixes #7976
The order of precedence which file is chosen is `1.sql` if it exists, otherwise `01.sql` if it exists, otherwise `001.sql` and so on - until `000000000001.sql`.
Can be backported because it's backwards compatible.
=> Support evolutions scripts prefixed with zeros (01.sql, 001.sql, etc.)

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play/src/main/scala/play/core/ApplicationProvider.scala
As far as I can tell, `ApplicationProvider#get` is not meant to be called multiple times for the same request. It looks like that was the case previously, but in 2.6.x we've added some caching based on the `Try[Application]` instance and are calling the `ApplicationProvider` to get the current instance each time. The current dev mode reload logic forces a reload next time (`forceReloadNextTime = true`) when compilation fails, so if `get` is called more than once for a single request, that causes multiple compilations per request.
My solution here proposes to get the `Try[Application]` once and pass that instance around for the handling of the request.
Fixes #7753
=> Avoid multiple calls to ApplicationProvider#get for a single request

framework/src/play/src/main/scala/play/api/data/Form.scala, framework/src/play/src/test/scala/play/api/data/FormSpec.scala
Fixed https://github.com/playframework/playframework/issues/8081
The FormError.format method should call messages.apply(message, args: _*)
instead of messages.apply(message, args) in order to properly format the values of the arguments.
=> Fixed bug where error messages with parameters are not correctly formatted

documentation/manual/working/commonGuide/configuration/ConfigFile.md, documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md, documentation/manual/working/commonGuide/configuration/code/build.sbt, framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/app/Module.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Fixes #7990 #7617.
Not all `devSettings` are being respected because we use a distinct `ActorSystem` to run the application in DEV mode and this actor system was not considering `devSettings`. So now, it first gets specific configuration under `play.akka.dev-mode` (which could be used to solve conflicts between DEV's ActorSystem and app's ActorSystem) and then falls back to `devSettings` + application configuration.
This PR also adds documentation to explain better `play.akka.dev-mode`.
=> Preserve all devSettings including Akka's

documentation/manual/working/commonGuide/filters/CorsFilter.md
Updates the option list to include the version for serveForbiddenOrigins, which is only part of the last few versions of 2.5.x
For anyone running an existing project in an earlier version of play 2.5, this is rather confusing.
=> Clarify the CorsFilter documentation

framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Scripted test for dev-mode is broken when running in Travis (I could not reproduce it locally, maybe due to different OS). I suspect this is somehow related to the differences between file watcher services for Mac OS and Linux (used by Travis).
#8173 is where the test was introduced. #8179 is a backport that needs a fix too.
=> Fix scripted test for dev mode

framework/project/PlayWhitesourcePlugin.scala
Remove extra `-` at `whitesourceAggregateProjectName`.
#8186.
=> [2.5.x]: Fix whitesource name: remove additional dash

framework/build.sbt, framework/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Updates interplay to version 1.3.14. This version changes the naming scheme for Whitesource projects.
https://github.com/playframework/interplay/pull/44
=> Update interplay to version 1.3.14

.gitattributes, framework/build.sbt, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala, framework/src/play/src/main/scala/play/api/controllers/Assets.scala, framework/src/play/src/test/scala/play/api/http/WriteableSpec.scala, framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala, framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
With these changes the Play core project tests pass on Windows. There are still plenty of tests failing, but this is a start!
The Assets changes are designed for maximum compatibility. The `resourceNameAt` method tries to guard against users accessing resources outside a particular prefix on the classpath. Before this
change it used `File.getCanonicalPath` to avoid `..` paths from escaping the prefixed part of the classpath. The `File.getCanonicalPath` method unfortunately behaves differently on Windows from Linux or macOS. I have written a closely compatible method (all the tests pass). In the future we might want to re-examine
how we do this test - there may be a more elegant and safer check that we can do. For now, I'm trying to change as little as possible.
=> Windows compatibility fixes

framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
NettyModelConversion should return an empty map instead of an Internal Server Error if the query string can not be parsed.
Fixes #8128 
We should avoid returning Internal Server Error when query string can not be parsed. Returning an empty parameter map should provide a better user experience for the end user. Additionally, AkkaHttpServer vs NettyHttpServer behaving similarly is desirable in terms of consistency.
=> Fix #8128 - Invalid query string in NettyHttpServer

framework/src/play/src/main/java/play/Environment.java
Makes life a bit easier. Scala's `Environment` has it but the Java version is missing it :cry:
=> Add getExistingFile(...) to Java Environment

documentation/manual/working/commonGuide/database/Evolutions.md
One simple technique to normalize the thought of women being developers is to use he for some examples and she for others. When reading this part of the documentation, I stumbled upon the example where both developers are assumed to be male.
An alternative, that is not assuming any gender at all (going beyond binary gender identification), would be to use completely gender neutral language.
=> Don't assume developers are male

documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
Example called "block-request" uses Forbidden in onlyHttps method. Results traits should be imported so that you can use http results like Forbidden.
Fixed import statement of an example in docs
Results traits should be important in said example.
=> Changed import of "block-request" example in docs

framework/project/Dependencies.scala
Fixes APLN issue found in https://github.com/playframework/playframework/issues/8234#issuecomment-367217731
The TL;DR is that if you have Java b161 and you run the integration tests, you get:
```
[jetty-alpn-agent] Replacing: sun/security/ssl/Alerts
Exception in thread "specs2.fixed.env397465184-3" java.lang.NoClassDefFoundError: sun/security/ssl/SupportedEllipticCurvesExtension
```
The latest ALPN is 2.0.7 and has support for b161, and adding it fixes the problem.
https://github.com/jetty-project/jetty-alpn-agent/releases/tag/jetty-alpn-agent-2.0.7
=> Upgrades ALPN agent to 2.0.7

framework/src/play-docs-sbt-plugin/src/main/twirl/com/typesafe/play/docs/sbtplugin/translationReport.scala.html, framework/src/play/src/main/scala/views/defaultpages/badRequest.scala.html, framework/src/play/src/main/scala/views/defaultpages/devError.scala.html, framework/src/play/src/main/scala/views/defaultpages/devNotFound.scala.html, framework/src/play/src/main/scala/views/defaultpages/error.scala.html, framework/src/play/src/main/scala/views/defaultpages/notFound.scala.html, framework/src/play/src/main/scala/views/defaultpages/unauthorized.scala.html, framework/src/play/src/main/scala/views/helper/checkbox.scala.html, framework/src/play/src/main/scala/views/helper/defaultFieldConstructor.scala.html, framework/src/play/src/main/scala/views/helper/form.scala.html, framework/src/play/src/main/scala/views/helper/input.scala.html, framework/src/play/src/main/scala/views/helper/inputCheckboxGroup.scala.html, framework/src/play/src/main/scala/views/helper/inputDate.scala.html, framework/src/play/src/main/scala/views/helper/inputFile.scala.html, framework/src/play/src/main/scala/views/helper/inputPassword.scala.html, framework/src/play/src/main/scala/views/helper/inputRadioGroup.scala.html, framework/src/play/src/main/scala/views/helper/inputText.scala.html, framework/src/play/src/main/scala/views/helper/javascriptRouter.scala.html, framework/src/play/src/main/scala/views/helper/requireJs.scala.html, framework/src/play/src/main/scala/views/helper/select.scala.html, framework/src/play/src/main/scala/views/helper/textarea.scala.html, framework/src/play/src/main/scala/views/play20/manual.scala.html, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/views/index.scala.html, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/views/main.scala.html
In the twirl repo some people were annoyed that Play/twirl adds many unnecessary newlines when using form helpers, etc.
Together with https://github.com/playframework/twirl/pull/169 this will be a bit better now.
=> Remove newlines in twirl templates

framework/build.sbt, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHeadersWrapperTest.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala
Fixes #8228
When switching backends small changes between Netty and Akka HTTP slipped. Akka HTTP models the lack of a Content-Type header with something like `Some(ContentType("none/none"))`. This PR captures that case and propagates the equivalent of `None` instead.
=> Prevent none/none to leak into Play (master)

documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md, framework/project/BuildSettings.scala, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
currently the RedirectHttpsFilter is really handy if one actually
directly wants to use a L4/L7 cloud load balancer, however
most of these need Health Checks and aren't happy if one just
redirects to HTTPS, so there is a header to look for and if it
is present it will redirect to HTTPS if it isn't present it
will just serve the content.
=> add a way to read X-Forwarded-Proto in RedirectHttpsFilter

documentation/manual/gettingStarted/NewApplication.md, documentation/manual/gettingStarted/Tutorials.md
Fixes playframework/play-scala-starter-example#68.
The giter8 sbt plugin for scaffold does not have a final release for sbt 1.0 which is used in our seeds and starter projects.
=> Remove references to g8Scaffold

framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
The setAutoCommit call can potentially throw an exception, causing DB connections to leak. This commit wraps the call in a try/catch block, closing the connection if necessary.
Fixes #8196.
=> Move setAutoCommit call into try block

framework/project/Dependencies.scala
Update play-ws to version 1.1.6. This version is virtually identical to 1.1.4, but we had some fixes in the release process.
=> Update play-ws to version 1.1.6

framework/project/Dependencies.scala
Just bumps the play-json version to the latest stable version.
=> Update play-json to 2.6.9

framework/project/Dependencies.scala
http://www.reactive-streams.org/announce-1.0.2
No changes to the interfaces, this is just to keep up to date.
I noticed that in Lagom we are having to override this dependency to get the version to match.
https://github.com/lagom/lagom/blob/ce9960f3880eab1e290acc2d35a6ba7e94974792/project/Dependencies.scala#L614
=> Update Reactive Streams to 1.0.2

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Fixes #8095, by loading the logback configuration files in the order specified by https://logback.qos.ch/manual/configuration.html#auto_configuration.
Also fixes #7767, since this switches to using the `ContextInitializer` for loading the files, which supports groovy-based configuration as well.
=> Load standard logback files in LogbackLoggerConfigurator

framework/project/BuildSettings.scala, framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
`invokeWithContextOpt` isn't used and also not need anymore.
Also it's javadocs says
> This is intended for use by methods in the JavaGlobalSettingsAdapter...
[JavaGlobalSettingsAdapter](https://github.com/playframework/playframework/blob/2.5.x/framework/src/play/src/main/scala/play/core/j/JavaGlobalSettingsAdapter.scala) was removed #5955 and therefore only exists up to the `2.5.x` branch which means since the 2.6 release that method is useless.
=> Remove method which isn't needed anymore

documentation/manual/working/commonGuide/build/code/dependencies.sbt, documentation/manual/working/javaGuide/main/sql/code/jpa.sbt, framework/project/Dependencies.scala
`hibernate-entitymanager` was moved to `hibernate-core` with the 5.2 release:
https://github.com/hibernate/hibernate-orm/wiki/Migration-Guide---5.2#hibernate-entitymanager-merged-into-hibernate-core
https://mvnrepository.com/artifact/org.hibernate/hibernate-entitymanager
=> Upgrade + rename Hibernate ORM

framework/src/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala
in a previous version I changed that from `completionStage()` to
complete and cancel, because `completionStage()` will fail under netty.
however since appOut and appIn is already closed at that point it
needs to be a `cancel(remoteIn)` as the comment suggested.
=> currently this should cancel the remoteIn

framework/src/play-filters-helpers/src/main/scala/play/filters/cors/CORSActionBuilder.scala
In our code we are using the CORSActionBuilder.  We updated to play 2.6 and discovered that our async actions that use this builder were executing twice!
Upon investigation, it turned out that there is some code that evaluates the block twice, discarding the first result.  However because Future has a side effect when created, the code is executed. a second time.
It looks like the duplication was just the author considered two approaches and never settled on a specific one but left both in.
This PR removes the second of the approaches, this meaning the block will be called exactly once.
Original change here:
https://github.com/playframework/playframework/pull/7409/files#diff-fa325da5d47d46c39e3044b9fcf62397R33
Our code that uses the cors builder: …
=> remove duplicate execution of action async block

framework/project/Dependencies.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala, framework/src/play-integration-test/src/test/scala/play/it/LogTester.scala, framework/src/play-integration-test/src/test/scala/play/it/http/AkkaResponseHeaderHandlingSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/RequestHeadersSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/libs/ScalaWSSpec.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala, framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala, framework/src/play/src/main/scala/play/core/utils/AsciiSet.scala, framework/src/play/src/main/scala/play/utils/UriEncoding.scala, framework/src/play/src/test/scala/play/libs/json/JavaJsonSpec.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
Fixes #7733, #7735, #7719, #7997, #8205.
Maybe fixed, but not verified: #7737, #8149.
Most request and response headers are now unparsed by Akka HTTP and stored as RawHeaders. That Akka HTTP won't log warnings, won't reject headers and won't reformat headers.
Several headers are still parsed in order for Akka HTTP to function properly: Content-Type, Content-Encoding, WebSocket related headers, etc. These headers are in a whitelist in the Akka HTTP source.
I was originally going to merge #8296 and then backport it, but we're waiting on a version of Akka HTTP to be ready for the *master* branch, so instead we can merge this to *2.6.x* and then forward port it later.
=> Change Akka HTTP backend to use raw headers

framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play/src/main/java/play/i18n/Messages.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/i18n/Messages.scala
Fixes #8288
Currently in Play 2.6.x we tried to have a change that adds the current context language from Java to the MessagesApi in Scala, however due to bin incompatible changes it got reverted here: https://github.com/playframework/playframework/commit/c7855328e14f7f99d68f8d5ce072e1bbe5f26cc6
This addresses it by using a TypedKey, which has the benefit of not breaking any api contract and also not introducing any kind of binary incompability.
It also saves duplicated code.
=> used typed keys to pass the current context lang to scala (#8288)

framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/server/ServerReloadingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/resources/reference.conf, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerDebugInfo.scala, framework/src/play/src/main/scala/play/core/ApplicationProvider.scala
Fixes #7812.
The caching of the `ReloadCache` uses reference equality so we need to be more careful when passing around the Try[Application] returned by `ApplicationProvider.get`. We need to make sure we keep the same reference.
=> [2.6.x]: Stop Netty server reloading configuration on each request

documentation/build.sbt, documentation/manual/working/commonGuide/configuration/ConfigFile.md, documentation/manual/working/commonGuide/configuration/code/javaguide/configuration/MyController.java, documentation/manual/working/javaGuide/main/config/JavaConfig.md, documentation/manual/working/javaGuide/main/config/code/javaguide/config/MyController.java, documentation/manual/working/javaGuide/main/config/index.toc, documentation/manual/working/javaGuide/main/index.toc, documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
We already have `ScalaConfig` page. This adds the equivalent Java version.
=> Add documentation about Java Config

documentation/manual/releases/release27/migration27/Migration27.md, framework/project/Dependencies.scala
Play framework still uses an old version of guava (23.0), however, there were 6 minor versions (23.1-23.6) and now the actual one is 24.0.
=> update guava to 24.0-jre

framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/core/cookie/encoding/ClientCookieDecoder.java, framework/src/play/src/main/java/play/core/cookie/encoding/ServerCookieEncoder.java, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/test/scala/play/api/mvc/CookiesSpec.scala
Fixes #8332. Use 0 as the max-age for discarded cookies for maximum compatibility. Since non-positive Max-Age values always mean "expire now", set the expiration date of such cookies to 1 Jan 1970.
=> Use Max-Age=0 to expire a cookie

framework/project/BuildSettings.scala
It makes possible for projects that have Play artifacts as dependencies to just enable `autoAPIMappings` and have their scaladocs cross-linked to Play scaladocs.
1. https://www.scala-sbt.org/1.x/docs/Howto-Scaladoc.html
2. https://github.com/lagom/lagom/pull/1283
=> Configure apiURL to enable cross-linking

framework/project/BuildSettings.scala
We don't need/have a `VersionPattern` since we can assume that snapshots will use `2.6.x` version.
=> [2.6.x]: Correct apiURL setting

documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, framework/project/BuildSettings.scala, framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/main/scala/play/core/PlayFormsMagicForJava.scala, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
From Play 2.5 to 2.6 we needed to change the return types of a couple Java form methods thats why we added new methods and deprecated the old ones to have a smooth migration path.
This pr renames give the methods their old names again (which are much better and more consistent with the other methods within their classes)
=> Rename Java form methods back to original names

documentation/build.sbt, framework/project/BuildSettings.scala
We cannot have `apiURL` scoped since later sbt reads the setting without a scope. So the change introduced in #8317 had no effect on the generated pom file. We then need to "unscope" apiURL and run `publishLocal` for play-docs before running `test` for documentation.
#8317.
=> Documentation test task depending on publishLocal for play-docs

documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
This PR fixes typo for `play.ws.ning.maxConnectionLifetime`
Fixing documentation mistake.
https://github.com/playframework/playframework/blob/7abb4d5721f8313e59b8188c9efc89ead6fcb08e/framework/src/play-ws/src/main/scala/play/api/libs/ws/ning/NingConfig.scala#L79
=> Fix typo for `play.ws.ning.maxConnectionLifetime`

framework/src/run-support/src/main/java/play/runsupport/classloader/ApplicationClassLoaderProvider.java, framework/src/run-support/src/main/java/play/runsupport/classloader/DelegatingClassLoader.java, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
Fixes #8350
under JDK 9+ DelegatingClassLoader raised an Illegal reflective access
error.
By changing ApplicationClassLoaderProvider to use an URLClassLoader
the whole reflective access can be removed.
Currently nobody uses `ApplicationClassLoaderProvider` with a different `ClassLoader` than an `URLClassLoader`. I even checked Lagom and they basically have the same classes than Play which also implement and URLClassLoader. Gradle does not use anything from `play.runsupport`.
After that PR on sbt 1.1.2 and master Branch we would still see (and of course we still need to add jaxb):
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 …
```
=> Removes Illegal reflective access of DelegatingClassLoader

framework/project/Dependencies.scala
Pulls in the new version of jackson-databind - 2.8.11.1 - which fixes 
https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2018-7489
see the change in
https://github.com/FasterXML/jackson-databind/issues/1931
This PR uses a fixed version of jackson-databind.  It is only a 0.0.0.1 version update so there shouldn't be any issues.
=> use less vulnerable version of jackson-databind

documentation/manual/releases/release27/migration27/Migration27.md, framework/project/BuildSettings.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-integration-test/src/test/scala/play/it/server/ServerReloadingSpec.scala, framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala, framework/src/play-server/src/main/resources/reference.conf, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play-server/src/main/scala/play/core/server/common/ReloadCache.scala, framework/src/play-server/src/main/scala/play/core/server/common/ServerDebugInfo.scala, framework/src/play/src/main/scala/play/core/ApplicationProvider.scala
Fixes #7812.
The caching of the `ReloadCache` uses reference equality so we need to be more careful when passing around the Try[Application] returned by `ApplicationProvider.get`. We need to make sure we keep the same reference.
Also did some refactoring of code while I was making these changes.
=> [master]: Stop Netty server reloading configuration on each request

framework/src/play/src/main/scala/play/api/Configuration.scala, framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Fixes #8370
To use a more human-readable representation of durations.
- I also made the `ConfigLoader`s for `Duration` use the loaders for `FiniteDuration` underneath to avoid repetition - hence the reordering of vals. If the reason for not using them in the first place had something to do with overhead (or there's any other reason to keep it as it was), I can revert that piece of the change.
=> Make ConfigLoader for durations use Duration.fromNanos

framework/src/play-akka-http-server/src/main/scala/play/api/mvc/akkahttp/AkkaHttpHandler.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpHandler.scala, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/app/controllers/AkkaHttpRouter.scala, framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/conf/routes, framework/src/play-akka-http-server/src/test/scala/play/AkkaTestServer.scala
Exposing the akka-http types. This would be useful in providing the server side of an [akka-grpc](https://github.com/akka/akka-grpc) service in a Play application next to 'normal' Play routes.
This is pretty minimal but it'd be nice already, so we can experiment with this approach and flesh it out more later.
=> Introduce an akka-http specific Handler

framework/src/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
Prevent O(headers.length * 2) overhead of bitset construction in ServerResultUtils
This PR should improve performance of ServerResultUtils by avoiding per-response construction of AsciiBitSet instances.
I noticed a lot of time being spent creating AsciiBitSet instances in flame graphs. See below:
=> Store AsciiSet fields in ServerResultUtils

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
I changed this in #8275 without realizing this was only used in initializing the dev mode server before an application is available, and is intentionally more minimal for that reason. This change should be minimal risk, since it reverts to the previous behavior in 2.6.12.
This also fixes another issue, which is that the global logging mode (used for `logger.forMode`) should be set in `configure`.
=> Fix LogbackLoggerConfigurator#init

framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
`/:` is deprecated since Scala 2.13
https://github.com/scala/scala/blob/312ddb5d1e3436d7e07acad978cb116e9d023164/src/library/scala/collection/IterableOnce.scala#L465
=> use foldLeft instead of /:

documentation/manual/working/commonGuide/configuration/ConfigFile.md, documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md, documentation/manual/working/commonGuide/configuration/code/CustomAkkaHttpServer.scala, documentation/manual/working/commonGuide/configuration/code/application.conf, documentation/manual/working/commonGuide/configuration/code/build.sbt, documentation/manual/working/commonGuide/server/AkkaHttpServer.md, documentation/manual/working/commonGuide/server/NettyServer.md, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-filters-helpers/src/main/java/play/filters/components/CSPComponents.java, framework/src/play-filters-helpers/src/main/java/play/filters/components/CSPReportComponents.java, framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java, framework/src/play-filters-helpers/src/main/java/play/filters/csp/CSP.java, framework/src/play-filters-helpers/src/main/java/play/filters/csp/CSPAction.java, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPActionBuilder.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPConfig.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPFilter.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPModule.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPProcessor.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala, framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPResultProcessor.scala, framework/src/play-integration-test/src/test/scala/play/it/http/AkkaHttpCustomServerProviderSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecification.scala, framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala, framework/src/play-integration-test/src/test/scala/play/it/test/ServerEndpointRecipe.scala, framework/src/play/src/main/scala/views/html/helper/CSPNonce.scala
Fixes #8368.
Refactor the `AkkaHttpServer` class so that more of its internal behavior is accessible to advanced users. Users can now extend this class and override behavior through protected methods. The custom class can be hooked into Play through the existing `play.server.provider` setting.
By allowing users to change the Akka HTTP server behavior, particularly the server settings, we reduce the pressure on Play to provide a perfect and universal configuration out of the box. We can now provide a configuration that is right for most users and allow advanced users to reconfigure their settings as needed.
For example, it is now possible to modify the Akka HTTP server's configuration to extend the list of HTTP methods that is supported. This example is shown in an integration test.
=> Allow users to directly configure Akka HTTP settings

framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala, framework/src/play/src/main/scala/play/api/http/HttpRequestHandler.scala, framework/src/play/src/main/scala/play/api/inject/Binding.scala, framework/src/play/src/main/scala/play/api/inject/BuiltinModule.scala, framework/src/play/src/main/scala/play/api/libs/Files.scala
This fixes a number of issues with bindings that don't manifest when using Guice, but do when using CDI. The issues fixed are:
* `ExecutionContext` and `Executor` were both bound to interfaces, which is illegal. Guice seems to be ok with this if there are bindings for the interfaces they are bound to, but other DI implementations aren't. I've replaced their bindings with alias bindings (because that's really what we want here), and I've also added validation to ensure this dosen't happen again.
* There were duplicate bindings for `JavaContextComponents`. This wasn't noticed because they came from the `HttpErrorHandler` and `HttpRequestHander` dynamic bindings methods. But the JavaContextComponents binding isn't dynamic, so I pulled it out of there and in to `BuiltinModule`. For some …
=> Fixed a number of binding issues

documentation/manual/working/javaGuide/main/forms/JavaForms.md
Fixes #7937
This PR changes `JavaForms` documentation so it does not reference `Model` anymore.
Changes made according to suggestions from #7937.
=> Remove references to `Model`

framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala, framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala, framework/src/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
Fixes #8402.
We now pass the Injector value to the initialization code so that it can use Guice to load a value instead of always using the default constructor.
Increases visibility of PooledDatabase.pool field so that we can unit test its value more easily. May fail the MiMA tests because I wasn't able to run these locally.
=> Use Guice to initialize database connection pools

framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Fixes #8361 by only applying `logback-test.xml` in test mode, where it is most likely intended. For master I plan to add to the migration guide something about `logback-test.xml` and how to use it properly.
=> [2.6.x] Only apply logback-test.xml in Test mode

framework/src/build-link/src/main/java/play/TemplateImports.java
I noticed a couple minor code issues while working on the Gradle integration
=> TemplateImports cleanup

framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
`HttpErrorHandlerSpec` on the 2.6.x branch is [failing at the moment](https://github.com/playframework/playframework/pull/8414#issuecomment-389706494) due to a [pushed backport](https://github.com/playframework/playframework/pull/8398#issuecomment-388272038). This fixes the test.
=> Add binding to fix 2.6.x build failure

framework/src/run-support/src/main/java/play/runsupport/classloader/ApplicationClassLoaderProvider.java, framework/src/run-support/src/main/java/play/runsupport/classloader/DelegatingClassLoader.java, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
under JDK 9+ DelegatingClassLoader raised an Illegal reflective access
error.
By changing ApplicationClassLoaderProvider to use an URLClassLoader
the whole reflective access can be removed.
**WARNING:** this breaks bin compatibility (maybe), but only for dev-mode, so if that's a no-go we can reject it. Because it raises the type of ClassLoader to URLClassLoader
=> [Backport 2.6.x] Removes Illegal reflective access of DelegatingClassLoader (#8355)

framework/project/Dependencies.scala
This brings in cachecontrol 1.1.3 which in turn removes an unneeded dependency on slf4j-nop.
Cc @TimMoore.
=> Update play-ws to 1.1.9

framework/src/play/src/main/scala/play/api/mvc/Action.scala
Fixes #8224.
Small change without tests which should be OK. Writing a unit test for this is a bit tricky because it may need a custom Accumulator to test properly. However I think it's OK to make this change so long as no existing unit tests fail.
=> Call ExecutionContext.prepare in Action.apply

framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/Build.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/src/main/resources/application.conf, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/src/main/scala/controllers/HomeController.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/src/main/scala/router/Routes.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
currently the generated keystore was always placed inside conf/
however that was/is bad in two ways:
1. it means that the generated.keystore is inside the distribution files
2. it also means that the generated.keystore needs the conf/ folder
(which does not exists when using the maven layout)
this places it into the root folder and also adds a test to it,
to confirm that the correct folder is used.
Fixes #3677
we can close the issue than, because the ebean project has it's own [issue](https://github.com/playframework/play-ebean/issues/1).
=> places the generated keystore into the root folder

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java, framework/project/Dependencies.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala, framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/http/parsing/XmlBodyParserSpec.scala, framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala, framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala
actually this only removes commons-io inside the routes generator and
inside our specs, there is just no need to use it, because we do not
really use it that much.
no need for any migration guide since play does only use it in the
sbt plugin
It's more a hygenic change in the first place, no need for commons-io if we have guava
=> removes commons-io

documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWSSpec.scala, documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayAkkaHttp.md, documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayNetty.md, documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala, documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaNettyEmbeddingPlay.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaErrorHandling.scala, documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleEssentialActionSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala, framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala, framework/src/play-integration-test/src/test/java/play/routing/DependencyInjectedRoutingDslTest.java, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/play-test/src/main/scala/play/api/test/Helpers.scala, framework/src/play/src/main/resources/reference.conf
This sets `play.allowGlobalApplication = false` by default and updates the tests accordingly.
I also realized there are several places in our documentation where we use global state where we shouldn't be. Perhaps also it would be smart to remove the `Action` companion object to prevent conflicts with the one in `BaseController` and confusion about which `Action` you are using.
Fixes #8050
=> Set play.allowGlobalApplication=false by default

framework/project/Dependencies.scala, framework/project/plugins.sbt
currently this adds the jaxb-api jar (122kb) so that play will work without any flag under jdk 9+.
An alternative would be to either fork jjwt and fix the outstanding issue or use a different JWT implementation.
We could also wait for a fix directly in jjwt however I guess it's fine to add jaxb-api.jar for known since it is only 122kb and than we could run play under jdk 9+ without any flags/problems.
After we merge that Play will still print:
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (guice.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of …
```
=> added jaxb-api so that jdk 9+ classpath works without configuration

framework/project/Dependencies.scala, framework/project/plugins.sbt
as suggested by @marcospereira.
Guess this won't break any user code. it only adds a dependency, which should not make any binary compatibility problems.
=> [Backport 2.6.x] added jaxb-api so that jdk 9+ classpath works without configuration

documentation/manual/working/commonGuide/build/SBTDebugging.md
This page https://www.playframework.com/documentation/2.6.x/SBTDebugging appears to have some out of date / incorrect information on it. For example it says
The reports can be found in the target/resolution-cache/reports directory
but they are actually located in target/scala-2.12/resolution-cache/reports/
=> Update made to the reports path

documentation/manual/releases/release27/migration27/Migration27.md, framework/project/BuildSettings.scala, framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/tools/HttpBin.scala, framework/src/play-java/src/main/java/play/libs/Comet.java, framework/src/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala, framework/src/play/src/main/java/play/i18n/MessagesApi.java, framework/src/play/src/main/java/play/libs/reflect/ClassUtils.java, framework/src/play/src/main/java/play/libs/reflect/ConstructorUtils.java, framework/src/play/src/main/java/play/libs/reflect/MemberUtils.java, framework/src/play/src/main/java/play/libs/reflect/MethodUtils.java, framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/inject/Module.scala, framework/src/play/src/main/scala/play/api/libs/Codecs.scala, framework/src/play/src/main/scala/play/api/libs/Comet.scala, framework/src/play/src/main/scala/play/api/libs/crypto/CSRFTokenSigner.scala, framework/src/play/src/main/scala/play/api/routing/JavascriptReverseRouter.scala, framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
currently play added a lot of "helper" libraries in the past,
however with recent JVM upgrades and more and more stuff inside
the JVM itself these got more and more unnecessary.
Actually this imports some Classes from apache commons lang3,
however only a really small subset of the library is imported.
The subset itself barly changed over the recent years and Play
mostly used just the reflect stuff of commons lang3
Edit:
actually I'm not against these libraries, I'm actually like them, however I think Play should use as few helper libraries as possible. It's easier for users to upgrade them without any breakage and it also reduces the Play footprint.
If people are ok with the PR I will still need to write docs.
=> remove apache commons libs

documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala, documentation/manual/working/scalaGuide/main/cache/code/ScalaCache.scala, documentation/manual/working/scalaGuide/main/cache/code/ScalaEhCache.scala, framework/project/BuildSettings.scala, framework/src/play/src/main/scala/play/api/Play.scala, framework/src/play/src/main/scala/play/api/http/HttpConfiguration.scala, framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala, framework/src/play/src/main/scala/play/api/libs/Crypto.scala, framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala, framework/src/play/src/main/scala/play/api/mvc/Security.scala, framework/src/play/src/main/scala/play/core/Execution.scala, framework/src/play/src/test/scala/play/api/PlayGlobalAppSpec.scala
The current app was still being initialized even with the global state disabled. This removes that and adds some more warnings to instruct users to move away from `Play.current` and similars.
See discussion in our Gitter channel: https://gitter.im/playframework/contributors?at=5b106c1d52e35117cdf94838
This can be considered a follow up of #8183.
=> Remove set current app when allow global false

framework/src/play/src/main/scala/views/defaultpages/devError.scala.html, framework/src/play/src/main/scala/views/defaultpages/devNotFound.scala.html
Fixes #7753
Rolls back #8213, the removal of shortcut icon which when removed, chrome tries to hit server for default /favicon.ico causing the server to recompile everything again.
#8213 was intended to solve #7105 but went to far when removing the favicon from development templates
#7753, #8213, #7105
=> rollback 8213 causing chrome favicon.ico request to recompile

documentation/manual/releases/release27/Highlights27.md, documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java, documentation/manual/working/javaGuide/main/ws/JavaWS.md, documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java, framework/project/BuildSettings.scala, framework/project/Dependencies.scala, framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java, framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSResponse.java, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSRequest.scala, framework/src/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSResponse.scala, framework/src/play-ws/src/main/java/play/libs/ws/WSRequest.java, framework/src/play-ws/src/main/scala/play/api/libs/ws/WSRequest.scala
Update the version of standalone ws to 2.0.0-M2.
This version has some breaking changes that were documented in our migration guide. Most of them just involve changing return types to use Optional or Duration.
=> Update play-ws to version 2.0.0-M2

framework/build.sbt, framework/project/BuildSettings.scala
Correct the value for `crossScalaVersions` at the root project. It should not use the default Scala 2.13 version defined by interplay 2.0.3.
See #8473.
=> Fix crossScalaVersions value for root project

framework/build.sbt, framework/project/BuildSettings.scala, framework/version.sbt
A missing configuration for RoutesCompilerProject which does not inherit `crossScalaVersions` from `playRuntimeSettings`.
See #8481 and #8473.
=> Fix routes compiler cross scala versions

framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala
it *seems* this version is better at picking the right alpn-boot resource based on JDK version (http://www.eclipse.org/jetty/documentation/current/alpn-chapter.html#alpn-versions)
=> Update jetty-alpn-agent version

framework/project/Dependencies.scala
https://akka.io/blog/news/2018/06/08/akka-2.5.13-released
There is a config change in the release, but I don't think it effects us:
```
akka.typed -> akka.actor.typed
akka.testkit.typed -> akka.actor.testkit.typed
```
=> akka 2.5.13

framework/project/BuildSettings.scala, framework/src/play/src/main/scala/play/api/Configuration.scala
Removes the deprecated Play-internal `PlayConfig` class. Shouldn't require any migration guide changes since it's `private[play]` and is only usable within Play modules.
=> Remove PlayConfig

documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java, documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java, framework/project/BuildSettings.scala, framework/src/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play-java/src/test/java/play/mvc/HttpTest.java, framework/src/play-test/src/main/java/play/test/Helpers.java, framework/src/play-test/src/main/java/play/test/TestServer.java, framework/src/play-test/src/main/java/play/test/WithApplication.java, framework/src/play/src/main/java/play/Application.java, framework/src/play/src/main/java/play/DefaultApplication.java
1. Deprecated getWrappedApplication in favor of asScala which idiomatic to Play APIs
2. Add environment method to access application's environment.
Notice that while reviewing https://github.com/lagom/lagom/pull/1397.
=> Small improvements in Application Java API

documentation/manual/ModuleDirectory.md
Add new library, PlayFOP, to "Play modules" page.
* Announced PlayFOP in Play forum on 13/14 June 2018: ["Now available (with live demo): PlayFOP, a library for creating PDFs, images, and other types of output in Play applications"](https://discuss.lightbend.com/t/now-available-with-live-demo-playfop-a-library-for-creating-pdfs-images-and-other-types-of-output-in-play-applications/1293).
* Discussed PlayFOP and this pull request with @gmethvin via e-mail.
=> Add PlayFOP to "Play modules" page

documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java, documentation/manual/working/javaGuide/main/cache/code/javaguide/ehcache/JavaEhCache.java, framework/project/BuildSettings.scala, framework/src/play-cache/src/main/java/play/cache/AsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultAsyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/DefaultSyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/SyncCacheApi.java, framework/src/play-cache/src/main/java/play/cache/SyncCacheApiAdapter.java, framework/src/play-caffeine-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala, framework/src/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
I will finish this PR after #7611 has been merged which removes deprecated `play.cache.CacheApi`.
The PR changes the return type of the Java...
* ... `SyncCacheApi` `<T> T get(String key)` to `<T> Optional<T> get(String key)`
* ... `AsyncCacheApi` `<T> CompletionStage<T> get(String key)` to `<T> CompletionStage<Optional<T>> get(String key)`
The Scala api also returns `Option`, see [here](https://github.com/playframework/playframework/blob/2.6.6/framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala#L46) and [here](https://github.com/playframework/playframework/blob/2.6.6/framework/src/play-cache/src/main/scala/play/api/cache/AsyncCacheApi.scala#L51).
=> Java cache api should return Optional (like the scala api)

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
This fixes comments which mistakenly say not `Akka HTTP` but `Netty`.
Fix incorrect comments.
=> Fix wrong comments

documentation/manual/releases/release27/migration27/Migration27.md, framework/project/BuildSettings.scala, framework/src/play-jdbc/src/main/resources/reference.conf, framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala, framework/src/play-jdbc/src/main/scala/play/api/db/DefaultDBApi.scala, framework/src/play-jdbc/src/test/scala/play/api/db/DBApiSpec.scala, framework/src/play-jdbc/src/test/scala/play/api/db/DriverRegistrationSpec.scala, framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
Currently, when there is a database misconfiguration or when the database is not available, we fail to start the application. This PR changes it to avoid trying to connect to the database eagerly and delaying it to when an actual database connection is needed.
See https://github.com/lagom/lagom/pull/1409 and also discussion at https://github.com/playframework/playframework/issues/6706. See also [this discussion at our gitter channel](https://gitter.im/playframework/contributors?at=5b3370086ceffe4eba373b79).
=> Start the application when database is not available

framework/src/play-integration-test/src/test/scala/play/it/http/HttpErrorHandlingSpec.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala
The current error handling code in `Server.getHandlerFor` does not properly handle exceptions that happen during the creation of the `EssentialAction`. In this case it uses the `DefaultHttpErrorHandler` rather than the one from the application.
This fix changes the code so we only use `DefaultHttpErrorHandler` if we fail to get an application. Once we get an application, we use `application.errorHandler`.
This should fix #8496.
=> Use configured HttpErrorHandler for exceptions before action is created

documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java, framework/project/BuildSettings.scala
Fixes #8449.
Make it possible to build Play on Windows without changing any project configurations. This was tested on a Windows 10 VM.
=> Fix issues when building on Windows

framework/src/play-integration-test/src/test/scala/play/it/mvc/FiltersSpec.scala, framework/src/play/src/main/java/play/mvc/EssentialFilter.java, framework/src/play/src/main/scala/play/api/mvc/Filters.scala
Fixes #8509
Adding `asScala` API for `EssentialFilter`, so that Java `EssentialFilter` generated by Scala `EssentialFilter.asJava` can be converted back to the original object.
=> [2.6.x] Added asScala API to EssentialFilter

documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
Removed a repeated phrase in documentation
No open issues as far as I can see
Fix a typo in the documentation.
N/A
N/A
=> Fix a typo in ScalaConfig.md

framework/src/play-java-jdbc/src/test/java/play/db/DatabaseTest.java, framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala, framework/src/play-jdbc/src/test/resources/application.conf, framework/src/play-jdbc/src/test/resources/logback-test.xml, framework/src/play-jdbc/src/test/scala/play/api/db/DBApiSpec.scala, framework/src/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
In #8497 we did not handle other modes besides test. In Prod and Dev modes, there is a log entry that requires the database URL and, to get the database URL, Play was trying to get datasource metadata,
which requires a connection.
Then the log entry forced the database connection pool to initialize and fail. The new implementation gets the configured URL instead.
https://github.com/playframework/playframework/pull/8502#discussion_r202928829
=> Handle database not available in Prod/Dev/Test modes

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
This refactors part of the coordinated shutdown code introduced in #8406, providing a shared implementation for asynchronous and synchronous shutdown using the configured `play.akka.run-cs-from-phase ` property.
This reduces duplication within the Play framework code, and I'd also like to use this from Lagom.
=> Refactor invocation of Akka coordinated shutdown

documentation/manual/releases/release27/migration27/Migration27.md, framework/src/play/src/main/resources/reference.conf, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
The default now is to run all the phases. Users can create an instance of CoordinatedShutdown and run from a specific phase if they want/need to.
=> Remove `play.akka.run-cs-from-phase` configuration

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/test/scala/play/api/inject/DefaultApplicationLifecycleSpec.scala, framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
Two main changes here:
1. Users should interact directly with Akka's CoordinatedShutdown API instead of relying on Play helpers. This way evolutions on Akka API will be available faster and more consistently.
1. Renaming from `CoordinatedShutdownProvider` to `CoordinatedShutdownSupport`.
This may later have some impact on Lagom since it depending on these APIs (at least this is the direction in  https://github.com/lagom/lagom/pull/1453. What we can do is to access Play's `CoordinatedShutdownSupport` just like it was done in [`TrampolineContextAccessor.scala`](https://github.com/lagom/lagom/blob/349d7f94d592ed63a63d5959425a480e061774e7/service/core/api/src/main/scala/TrampolineContextAccessor.scala#L7).
=> Refactoring CoordinatedShutdownProvider object

framework/src/play/src/main/scala/play/api/routing/Router.scala, framework/src/play/src/test/scala/play/core/routing/RouterSpec.scala
This introduces a `/:` alias for `withPrefix` in the `Router`. In other words this code:
```scala
val router = "/api" /: apiRouter
```
can be used instead of 
```scala
val router = apiRouter.withPrefix("/api")
```
It will also work nicely with the `orElse` method introduced in #8012:
```scala
val router = ("/api" /: apiRouter) orElse ("/frontend" /: frontendRouter)
```
or even
```scala
val router = Seq(
"/api/v1" /: v1Router,
"/api/v2" /: v2Router,
"/app" /: appRouter
) reduce (_ orElse _)
```
=> Nicer syntax for router.withPrefix

framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/test/resources/application.conf, framework/src/play/src/test/resources/logback-test.xml, framework/src/play/src/test/scala/play/api/ApplicationSpec.scala, framework/src/play/src/test/scala/play/core/test/package.scala
`play.api.application.asJava` was not considering the environment. Notice that while working on some coordinated shutdown refactorings.
=> Fix asJava play.api.Application conversion

framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala, framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
This pull request contains an implementation for the problem described in issue #8527 (Content-Disposition of multipart/form-data too strict for some implementations).
Play did not recognise webhook callbacks from scanners because the manufacturer uses `Content-Disposition: file` instead of `form-data` (probably, they are in accordance with older standards, see investigation in issue #8527).
We have added respective tests and changed the implementation accordingly (solution 1 proposed in the issue).
Furthermore, we have tested the resulting Play snapshot with the scanner software that previously did not interoperate with Play (see issue #8527).
We signed the Lightbend CLA.
=> Implementation for issue #8527 (Content-Disposition of multipart/form-data too strict for some implementations)

documentation/manual/working/commonGuide/build/code/runhook.sbt
This is just a minimal update to the documentation: adding Play Run Hooks did no longer work [as described in the documentation](https://www.playframework.com/documentation/2.6.x/SBTCookbook).
Probably, this has something to do with the SBT version (pre/post 1).
In recent SBT, `Process` in the examples is interpreted as the abstract Java class `java.lang.Process`:
```
[error] M:\dev\play-cookbook-process\project\Grunt.scala:10:9: Java class java.lang.Process is not a value
[error]         Process("grunt dist", base).run
[error]         ^
[error] one error found
```
The additional `import scala.sys.process.Process` fixes this problem.
[See this repository for a minimal example to reproduce problem and solution.](https://github.com/aimpulse/play-cookbook-process/commits/master)
=> Improved SBT Cookbook in documentation by adding imports for scala.sys.process.Process

framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
Fixes #8548.
If configured to use a cookie, the CSRF filter will only check the cookie. If configured to use the Play session, it will only check the session.
=> Make CSRF filter consider either the cookie or the session, but not both

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
One problem that I have occasionally is that, when an error occurs during Evolution, it's difficult to figure out which statement causes the error.
I'd see an error like: `invalid character at position 61` without any pointer to which statement causes the error. This PR alleviates the problem.
This partly solves #8468. There's also a short discussion here: https://discuss.lightbend.com/t/should-we-add-more-logging-to-plays-evolutions/1460
=> More logs during Play's evolution

framework/bin/test-sbt-plugins-1_0, framework/project/Tasks.scala
We can use `quickPublish` to speed up scripted tests for sbt 1 too.
=> Quick publish when running scripted tests for sbt 1

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
The creating of SSLEngineProvider and later of SSLContext can be delayed as much as possible so that we won't need to call ApplicationProvider.get until it is necessary.
This fixes a problem in the integration of Play and Gradle when using HTTP in DEV mode.
There is also a fix in progress on Gradle side: https://github.com/gradle/gradle/pull/6345.
=> Lazily create SSLEngineProvider

documentation/manual/releases/release27/migration27/Migration27.md, framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala, framework/src/play/src/main/java/play/mvc/Controller.java, framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/java/play/mvc/Result.java, framework/src/play/src/main/java/play/mvc/StatusHeader.java
The main purpose here is to deprecate `Http.Response` which is a confusing API since we have `Result`. ~~There is also a deprecation warning for `Http.Context.args` but I'm not sure this should be part of this PR since we still don't have a substitute to it (the ideal solution is to add request attributes, but this would require to change action composition to call using a request instead of a context)~~.
Edit: This now focuses exclusively on deprecating `Http.Response`.
This is a less ambitious PR than #8312 by @mkurz.
=> Deprecate Http.Response

documentation/manual/working/commonGuide/build/SBTSubProjects.md
Really per-project build.sbt is not recommended, but it was easier to fix the false statement than to change all the examples.
Also, I think subproject shouldn't be hyphenated but I used the spelling of the rest of the file.
=> SBTSubProjects.md: fix contradiction about per-project build.sbt

framework/project/Dependencies.scala, framework/src/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/run/PlayRunCompat.scala, framework/src/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayRunCompat.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Fixes #8458.
This uses the new attribute key `ContinuousEventMonitor` added in sbt 1.1.5. The old one (`ContinuousState`) was deprecated and is not set anymore.
This may be a little tricky to backport: `ContinuousEventMonitor` was introduced in sbt 1.1.5. If we use it in Play 2.6.x, it will break support for 1.1.4 (and prior versions) meaning that users should use at least sbt 1.1.5. So, for all projects using sbt 1.1.4 and earlier, and update to 2.6.18 will break things which is not ideal.
Of course, for Play 2.7, we can put 1.1.5+ as a requirement.
=> Fix sbt auto trigger when using sbt 1.1.5+

framework/src/play/src/main/scala/play/api/data/validation/Validation.scala, framework/src/play/src/test/scala/play/api/data/validation/ValidationSpec.scala
Fixes an issue with ValidationError and varargs when converting to a JsonValidationError.   Replaces an earlier pull request that was getting messy due to CLA/GitHub email address confusion.
Fixes #8560
=> fromJsonValidationError did not expand varargs, fixes #8560

documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/commonGuide/production/ConfiguringHttps.md, framework/project/BuildSettings.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala, framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala, framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
Lagom has a copy of our local certificate generation, but with some adjustments. See https://github.com/lagom/lagom/pull/1443.
Refs https://github.com/lagom/lagom/issues/1507
This brings most of the changes made there so that both frameworks can use the same code.
=> Adopt lagom keystore generation changes in Play

framework/project/Dependencies.scala
Update Akka to version 2.5.15
https://akka.io/blog/news/2018/08/24/akka-2.5.15-released
=> Update Akka to version 2.5.15

documentation/manual/releases/release27/migration27/Migration27.md, framework/project/Dependencies.scala
Update Guava to the latest version.
https://github.com/google/guava/releases/tag/v26.0
=> Update guava to version 26.0-jre

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala, framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala, framework/src/play/src/main/scala/play/api/Application.scala, framework/src/play/src/main/scala/play/api/internal/libs/concurrent/CoordinatedShutdownSupport.scala, framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala, framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
The API needs to be public so that we can better use it in Lagom. But it is not supposed to be used in users code.
=> Make CoordinatedShutdoownSupport public but internal

documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
The Programmatic Bindings section used the same content as present in the Scala version of the doc and used the term trait. Proposing change to interface for more compatibility with the Java terminology.
Fixes #xxxx
=> Changed from trait to interface in Programmatic Bindings

framework/project/Dependencies.scala, framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala, framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala, framework/src/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala
Please, do not squash commits here to keep contributors credits.
This backports #8437 and #8589 so that we can have an updated version of Akka in Play 2.6.x.
Akka 2.5.12 introduced a fix that causes source compatibility issues (see https://github.com/akka/akka/pull/24575). This should not affect most of the users though. Also, Akka [2.5.13 brings some API changes](https://akka.io/blog/news/2018/06/08/akka-2.5.13-released) for Akka Typed and if you are using it in your Play application, there are some changes you need to make. These changes are okay according to Akka [binary policy rules](https://doc.akka.io/docs/akka/2.5/common/binary-compatibility-rules.html) since Akka Typed is still market as a ["may change" module](https://doc.akka.io/docs/akka/2.5/common/may-change.html). Internally, …
=> Update akka 2.5.16

framework/src/play-docs/src/main/scala/play/docs/DocumentationHandler.scala
While digging into source, found what looks like a typo in the `ico` MIME Type.
Note also that `ico` is there twice (line 32)...
=> DocumentationHandler small typo

documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/commonGuide/build/SBTCookbook.md, documentation/manual/working/commonGuide/build/code/runhook.sbt, framework/project/BuildSettings.scala, framework/src/build-link/src/main/java/play/core/server/ReloadableServer.java, framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala, framework/src/play-server/src/main/scala/play/core/server/Server.scala, framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala, framework/src/run-support/src/main/scala/play/runsupport/RunHook.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayRunHook.scala
This PR removes `mainAddress` from `ReloadableServer`. This address was only used in two places:
1. The documentation plugin printed the server address on the console
2. The `RunHook` passed it to `afterStarted`. I could not find a single usage anywhere on github or the internet of the address being used in a run hook. The run hooks are not heavily used in the first place. The most common usage is for js build tool integrations (e.g. [react webpack support](https://github.com/nouhoum/play-react-webpack/blob/master/project/Webpack.scala), [vue webpack support](https://github.com/gbogard/play-vue-webpack/blob/master/project/WebpackServer.scala), [grunt support](https://www.playframework.com/documentation/2.6.x/SBTCookbook)). None of these integrations or any others rely on the server …
=> Simplify ReloadableServer interface

framework/bin/test-scala-211
See:
* https://travis-ci.org/playframework/playframework/jobs/427334869
* https://repo.akka.io/snapshots/com/typesafe/akka/akka-stream_2.11/
* https://repo.akka.io/snapshots/com/typesafe/akka/akka-stream_2.12/
There are no recent snapshot builds of akka-stream for 2.11.
=> Disable test-scala-211 on nightly

.travis.yml, framework/project/Dependencies.scala
Update Akka HTTP to the latest version.
https://akka.io/blog/news/2018/09/06/akka-http-10.1.5-10.0.14-security-fix-released
This version of Akka HTTP fixes a [vulnerability](https://doc.akka.io/docs/akka-http/current/security/2018-09-05-denial-of-service-via-decodeRequest.html?_ga=2.123987082.1025615845.1536248761-1450633930.1536073782) but we find Play is not affected at all since the content length validation is done by BodyParsers.
=> Update Akka HTTP to 10.1.5

documentation/manual/releases/release27/migration27/Migration27.md
Fixes #8603.
Explains that Hibernate Validator update can cause some compatibility issues with other Hibernate dependencies.
https://github.com/playframework/playframework/issues/8603#issuecomment-421495463
=> Add note about Hibernate Validator compatibility

framework/project/BuildSettings.scala, framework/src/play-guice/src/test/java/play/inject/guice/GuiceInjectorBuilderTest.java, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala, framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceInjectorBuilderSpec.scala, framework/src/play/src/main/java/play/inject/Binding.java, framework/src/play/src/main/java/play/inject/BindingKey.java, framework/src/play/src/main/java/play/inject/BindingKeyTarget.java, framework/src/play/src/main/java/play/inject/BindingTarget.java, framework/src/play/src/main/java/play/inject/ConstructionTarget.java, framework/src/play/src/main/java/play/inject/Module.java, framework/src/play/src/main/java/play/inject/ProviderConstructionTarget.java, framework/src/play/src/main/java/play/inject/ProviderTarget.java, framework/src/play/src/main/java/play/inject/QualifierAnnotation.java, framework/src/play/src/main/java/play/inject/QualifierClass.java, framework/src/play/src/main/java/play/inject/QualifierInstance.java, framework/src/play/src/main/scala/play/api/inject/Binding.scala
…gnostic
Backport #8559 to `2.6.x` branch.
=> [2.6.x]: Added Java APIs for general dependency-injection to be DI framework agnostic

documentation/build.sbt, documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaComet.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaBodyParsers.java, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaErrorHandling.scala, documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java, documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/MockitoTest.java, documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java, documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java, documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala, documentation/manual/working/scalaGuide/advanced/routing/code/ScalaSimpleRouter.scala, documentation/manual/working/scalaGuide/advanced/routing/code/ScalaSirdRouter.scala, documentation/manual/working/scalaGuide/main/application/code/ScalaHttpRequestHandlers.scala, documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala, documentation/manual/working/scalaGuide/main/dependencyinjection/code/RuntimeDependencyInjection.scala, documentation/manual/working/scalaGuide/main/http/code/ScalaRouting.scala, documentation/manual/working/scalaGuide/main/json/code/ScalaJsonHttpSpec.scala, documentation/manual/working/scalaGuide/main/tests/code/specs2/ScalaFunctionalTestSpec.scala, documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
Removes deprecated APIs usage from our docs.
It also uses (almost) the same compiler configuration used by Lagom so that we can better know when docs are using deprecated APIs.
=> Remove deprecated APIs usage from docs

documentation/manual/hacking/BuildingFromSource.md
In the Play framework documentation, command is wrong to Cross-Building a Project with specific version. Corrected and submitted PR to community.
N/A.
In Play Framework document SBT command is wrong to build application with different Scala version. 
N/A. It is a document correction PR.
=> Corrected SBT Cross-Building command

framework/src/play/src/main/scala/play/api/libs/Files.scala
Should fix problem with TempFile objects not being released in memory (including proper deletion of underlining file). 
Remove tempFile from closure (to avoid strong reference to tempFile object preventing GC from triggering finalizeReferent of phantom reference).
As a result finalizeReferent method with deletePath is proper called when GC collects TempFile after usage.
This issue was found as a result of memory leak investigation (all TempFile objects created are held in memory while play application is alive).
N/A
=> Fix PhantomReference approach for TempFileCreator.

documentation/manual/working/commonGuide/filters/AllowedHostsFilter.md, framework/project/BuildSettings.scala, framework/src/play-filters-helpers/src/main/resources/reference.conf, framework/src/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala, framework/src/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
In some cases requests cannot always be validated against a fixed list of Allowed Hosts. Specifically, autoscaling groups using AWS application load balancers require http host checks, and will always use the dynamically assigned IP address of the instance as the host. This PR allows the allowed hosts filter to be applied to or filtered out of specific routes (such as health check urls) if desired. 
This PR adds a the ability to whitelist or blacklist route modifiers from the AllowedHostsFilter. The basic premise mirrors that of the CSRFilter.
=> Implement allowed hosts filter route modifiers

documentation/manual/working/javaGuide/main/sql/JavaJPA.md
Backports #8617 + fixed two links which are going to be fixed in #8616 for the master branch already.
=> [2.6.x] Fix incomplete sentence in JPA doc

documentation/manual/working/commonGuide/build/SBTCookbook.md, documentation/manual/working/javaGuide/main/sql/JavaJPA.md, documentation/manual/working/javaGuide/main/sql/code/jpa.sbt, framework/src/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/PlaySettingsCompat.scala, framework/src/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/PlaySettingsCompat.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/test
Introduces `PlayKeys.externalizeResourcesExcludes` which allows us/you to exclude selected resources from being externalized even though when `PlayKeys.externalizeResources := true` (which is the default).
This is especially useful for JPA because the `META-INF/persistence.xml` file has to be in the *same* jar file where its persistence-unit(s) entities live, otherwise these entities won't be availabe for the persistence-unit(s) - even when that jar containing the entities is on the classpath. (You could, however, add the jar via `<jar-file>xxx.jar</jar-file>` to  a persistence-unit, according to the [JPA specification](http://download.oracle.com/otn-pub/jcp/persistence-2_1-fr-eval-spec/JavaPersistence.pdf) - but that doesn't work well with play because that would fail with a …
=> Introduce externalizeResourcesExcludes

framework/bin/scriptLib, framework/bin/test-scala-211
Cron builds for 2.6.x is broken since it is not skipping Scala 2.11 script.
This also limits the Akka snapshot versions to 2.5.
=> [2.6.x] Akka 2.5 only for snapshot builds

framework/src/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala, framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/app/assets/main.less, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/build.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/project/plugins.sbt, framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/test
Currently this adds a way to disable `-assets.jar` by setting `playAssetsJar := false`.
At the moment I do not use anything from `sbt-web` Thus I either get a [Empty Assets Jar](https://github.com/playframework/playframework/issues/7570) or I actually get my assets packaged into the application jar and the assets jar.
Basically this allows to disable the assets.jar completly and disable the `packageBin in Assets` task.
This allows better packaging assets that come from other sources, like a npm project, etc.
This somewhat fixes #7570 (not automatically tough).
=> make it possible to disable the assets jar

documentation/manual/working/javaGuide/main/tests/JavaTestingWithDatabases.md
The JavaTesting page does not have any hyperlinks to the above 2 pages, so if we would like the ScalaTest and specs2 libraries to be used by Java Developers, it may be useful to have links to them.
Yes
Yes
Yes
NA
NA
NA
Yes this is update in the Java section of the doc
NA
Fixes missing links in the Java sections of the doc.
The JavaTesting page does not have any hyperlinks to the above 2 pages, so if we would like the ScalaTest and specs2 libraries to be used by Java Developers, it may be useful to have links to them.
While referring to this documentation page, I could not find where the 2 framework pages referenced are, until I went to the scala section of the doc where the links were maintained. This can save some effort on the part of java developers who may want to explore these …
=> Missing hyperlinks to ScalaTest and specs2 pages

documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
PR updates outdated fragment of heroku deployment documentations. After the java 11 LTS was released, there are not many reasons for using java 9/10(which are end-of-premier-support now) in both new and existing projects, especially since migration to java 11 is trivial. However, if someone needs to use java 9 or 10 for some reasons, the link to heroku documentation can help.
=> Update heroku deploying docs (declaring java version)

documentation/manual/hacking/BuildingFromSource.md
Play is still using sbt-doge to cross run publish tasks. So we need `+++` instead of `++`. So this reverts #8613.
=> Revert "Corrected SBT Cross-Building command (#8613)"

framework/build.sbt, framework/project/Dependencies.scala
https://akka.io/blog/news/2018/09/27/akka-2.5.17-released
=> Update to Akka 2.5.17

framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
`AkkaHttpServer` didn't honour some HTTPS-related settings:
````
play {
server {
https {
wantClientAuth = false
needClientAuth = false
}
}
}
```
=> Honor play settings on AkkaHttpServer for client auth in SSL

documentation/manual/releases/release27/Highlights27.md, documentation/manual/releases/release27/migration27/Migration27.md, framework/project/Dependencies.scala
Check the [diff from 4.2.0.](https://github.com/google/guice/compare/4.2...4.2.1)
Most notable Guice upgraded [ASM](https://asm.ow2.io/) and [cglib](https://github.com/cglib/cglib) which should bring better JDK11 support.
BTW: The Guice team is planning to release an even newer version as soon as ASM 7 final released (currently in beta). That should  happen "in the next weeks". ASM 7 should bring even better JDK11 support.
=> Guice 4.2.1 with better JDK 11 support

documentation/manual/releases/release27/Highlights27.md, documentation/manual/releases/release27/migration27/Migration27.md, documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java, framework/project/BuildSettings.scala, framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java, framework/src/play-java-forms/src/main/java/play/data/Form.java, framework/src/play-java-forms/src/main/java/play/data/FormFactory.java, framework/src/play-java-forms/src/main/java/play/data/FormFactoryComponents.java, framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java, framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java, framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala, framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala
Just a small enhancement to #8316:
The payload now also provides the config via `payload.getConfig()`.
I didn't include that in the original pull request since this is not a must-have, however every now and then I stumbled over a use-case where I had to access the config during validation. It's just a comfortable addition and since we already have a migration path for the constructors that change, I thought we could just include this feature straight away.
=> Also pass config via validation payload

framework/src/play/src/main/scala/views/helper/Helpers.scala, framework/src/play/src/test/resources/messages, framework/src/play/src/test/scala/views/html/helper/HelpersSpec.scala
Actually I thought that was happening already - like it's done for the `getOrElse` part as well, however it looks like I forgot that when I added the `translateMsgArg` method and other i18n stuff to the helpers.
(Actually I don't use the Play built-in helpers myself, most of the time [play-bootstrap](https://github.com/adrianhurt/play-bootstrap) - which *does* look up these attributes in the messages - therefore I did not recognize earlier).
We can backport as well.
=> Lookup form helpers' _label and _name attributes in messages

framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
Fixes #6656 
This change fixes play_evolutions_lock CRUD queries which are broken for Oracle Database.
following discussing in issue #6656 in order to keep backward compatibility, we are expected to keep column name as lock, which is reserved keyword.
=> escaped oracle reserved word using doublequote

framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java, framework/src/play/src/main/java/play/mvc/Security.java
Whenever we create a new `Context` and pass it on to the next action we always also have to make sure that this new context is also set as the current one in the Context thread local.
Actually that is how it's done already in another action helper:
https://github.com/playframework/playframework/blob/471708da65723353d3045e360ae663b4553a4a63/framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java#L87-L88
=> Make sure a new ctx gets set in the Context.current ThreadLocal

framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java, framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala, framework/src/play/src/main/java/play/mvc/Http.java
Fixes #8661
At first I just fixed the issue like I suggested in #8661
See the first commit.
However I think the much safer fix is to just remove the `play.api.mvc.RequestHeader header` field. We can simply replace it with `request.asScala()`.
Also what backs my suggestion for that safer fix is that in [`AbstractCSPAction.java`](https://github.com/playframework/playframework/blob/471708da65723353d3045e360ae663b4553a4a63/framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java#L37-L45) and [`AddCSRFTokenAction.java`](https://github.com/playframework/playframework/blob/471708da65723353d3045e360ae663b4553a4a63/framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java#L76-L84) we already have to make sure that `header` and …
=> Make sure request and header stay in sync in Http.Context

framework/src/play/src/main/java/play/mvc/Http.java, framework/src/play/src/main/scala/play/api/mvc/Cookie.scala, framework/src/play/src/test/java/play/mvc/CookieBuilderTest.java
Usually we set `httpOnly` to true in most places.
And usually `path` is "/".
=> Sync Scala and Java cookie default values

framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java, framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
Has the same effect but simpler.
Actually I am wondering why we even have `WrappedContext` (probably was here before we added the `withRequest` method).
=> Simply use ctx.withRequest instead of a new WrappedContext
