playframework/playframework

- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormHelpers.scala
The tests sometimes failed due to a missing `Http.Context`. They would often pass, but this was only because previous tests forgot to clean up their own `Http.Context` values.
> Fix flaky tests in JavaFormHelpers

- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/models/UserId.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/conf/routes
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/models/UserId.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/conf/routes
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
> [2.6.x] Encode path parameter returned from custom PathBindables (#7621)

- framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
Backports #7627 to 2.6.x branch.
> Backport #7627 to 2.6.x branch

- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/app/models/UserId.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/conf/routes
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/tests/RouterSpec.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/controllers/Application.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/app/models/UserId.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/conf/routes
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/tests/RouterSpec.scala
> [2.5.x] Encode path parameter returned from custom PathBindables (#7621)

- documentation/manual/working/javaGuide/main/async/JavaComet.md
- documentation/manual/working/scalaGuide/main/async/ScalaComet.md
This is a backport of #7632 by @ivanoronee to the 2.6.x branch.
> Added hint on how to successfully run snippets in comet docs

- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
- What does this PR do?
_Fixes simple typo in documentation_
> Fix simple typo

- framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
After the call to `BuildLink`'s `reload` method there was a race to get to the read/write lock around the `DevServerStart` reload logic. This fixes the race by surrounding both the call to the reload method and the `DevServerStart` reload logic in a single `synchronized` block. This is potentially less efficient than use a read/write lock, but it doesn't have a race condition.
I've added a TODO comment suggesting that we change this code into something asynchronous, so that we can avoid using any blocking locks at all. This is something we can do later for our next release. Right now, a simpler change that can be backported safely is more appropriate.
I have tested this locally in a browser and with `wrk` to ensure that the original deadlock reported in #7614 and #7622, and fixed by …
> Fix race condition when reloading in dev mode

- documentation/manual/releases/release26/Highlights26.md
The word "the" was written twice.
Fixes #xxxx
> Fixed typo

- documentation/manual/releases/release26/Highlights26.md
Removed mention of Global state changes in 2.6.0 changed it to 2.6.
Fixes #xxxx
> Removed mention of 2.6.0

- documentation/manual/working/javaGuide/main/async/JavaWebSockets.md
- documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md
- framework/src/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaHttpServer.scala
- framework/src/play-server/src/main/resources/reference.conf
Backports #7337 to 2.5.x branch.
> [2.5.x]: Configurable websocket frame max length

- framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
When the GzipFilter zips a streamed entity, it will try and buffer it if it's under a configured threshold - it does this so that it can return entities with a content length. When this threshold is exceeded, it reverts to not sending a content length, and instead sending the entity as a chunked entity. However, it doesn't check if it's allowed to do this, if the HTTP version is 1.0 (eg, when behind nginx in its default configuration), it's not allowed to send a chunked entity, and this will end up failing further down in the Play server implementation.
This changes so that when HTTP 1.0 is in use, the gzip filter will fallback to close delimited entities (ie, streamed entities with no content length), rather than chunked entities.
> Ensure GzipFilter doesn't revert to chunked illegally

- documentation/manual/working/javaGuide/main/tests/JavaFunctionalTest.md
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FakeApplicationTest.java
- documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
- documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
- documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala
1. Remove `play.test.Helpers` import in `FakeApplicationTest.java`
2. Fix borders of template code in `ExampleControllerSpec.scala` (see https://www.playframework.com/documentation/2.6.x/ScalaTestingWithSpecs2#unit-testing-controllers )
3. Additional links in `ScalaTestingWithSpecs2.md`
4. Additional links in `ScalaFunctionalTestingWithSpecs2.md`
> Fixes in Play testing documentation

- documentation/manual/working/javaGuide/main/tests/JavaFunctionalTest.md
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FakeApplicationTest.java
- documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
- documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
- documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala
This is a backport of @PromanSEW's PR to the _2.6.x_ branch.
> Fixes in Play testing documentation (backport)

- documentation/manual/working/javaGuide/main/cache/JavaCache.md
- documentation/manual/working/scalaGuide/main/cache/ScalaCache.md
- framework/src/play-ehcache/src/main/resources/reference.conf
- framework/src/play-ehcache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala
- framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
> [2.6.x] Change how we call Futures in EhCacheApi (#7649)

- framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala
- framework/src/play-server/src/test/scala/play/core/server/ProdServerStartSpec.scala
Fixes #7646.
1. This allows the PID file to be set to the `nul` special file in Windows. (Thanks @dwickern for verifying this.)
2. This fixes a race condition when starting the server. Using CREATE_NEW ensures the PID file is created atomically by only one server.
> Use CREATE_NEW for PID file creation

- documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
Simple documentation wording fix.
> The full API documentation is not for sale

- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/working/commonGuide/build/BuildOverview.md
- documentation/manual/working/javaGuide/main/forms/JavaForms.md
Fixes #7654 
Adds additional descriptions to several parts of the documentation highlighting the existence of the `PlayMinimalJava` plugin.
> Add documentation for PlayMinimalJava

- documentation/manual/working/commonGuide/configuration/ThreadPools.md
This is a backport of #7689 by @sarathraj-coder.
> Update link in ThreadPools docs (backport)

- framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java
- framework/src/play-java/src/main/java/play/routing/RoutingDsl.java
- framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
> [2.6.x]: Preserve request body when using RoutingDsl

- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
> doesn't seem like EmptyBody is documented?

- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
Sorry, missed two spots in the body checking code.
See [pull request 7716](https://github.com/playframework/playframework/pull/7716)
> CSRFAction should log the URI when check fails 2

- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
The full name of CSRF filter should be play.filters.csrf.CSRFFilter.
> Correct CSRF filter name from CsrfFilter to CSRFFilter.

- framework/src/play/src/main/scala/play/api/libs/Files.scala
- framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
> Avoid to create multiple temporary folders

- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/working/commonGuide/build/BuildOverview.md
- documentation/manual/working/javaGuide/main/forms/JavaForms.md
This is a backport of @gmethvin's PR #7678 to the 2.6.x branch. PR #7678 was marked as _needs-backport_.
> Docs for minimal java 2.6 (backport)

- framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
> Fix CachedSpec: Wait until cache operation has been finished

- framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
Backport of #7734 
/cc @richdougherty
> [2.6.x] Fix CachedSpec: Wait until cache operation has been finished

- documentation/manual/working/commonGuide/configuration/SettingsLogger.md
- documentation/manual/working/commonGuide/production/ProductionConfiguration.md
* [n/a] Have you added copyright headers to new files?
* [n/a] Have you checked that both Scala and Java APIs are updated?
* [n/a] Have you updated the documentation for both Scala and Java sections?
* [n/a] Have you added tests for any changed functionality?
Fixes #7708
> Mention Logback's -Dlogback.debug=true option in documentation (#7708)

- framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
- framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
Fixes #7746
Backport of pull request 7746
Added a test for a DELETE call.
HTTP methods need to be uppercase, as per standards.
Backport pull request, following this guide: https://groups.google.com/forum/#!topic/play-framework-dev/SKuFnTF-hLI
> 2.6.x backport for PR 7746

- documentation/manual/ModuleDirectory.md
Add Push Notifications module information to the documentation
https://github.com/splendidbits/play-pushservices
> Add push-services (Push Notification library) module to module documentation

- documentation/manual/ModuleDirectory.md
Forward ports #7748 to master branch.
> Add push-servies module (#7748)

- framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala
- framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
This change simply adds methods to the `Cached` helper class to use `Duration` as argument.
It seems a bit odd that one has to specify an Integer for the duration of the `Cached` helper when the underlying `CacheBuilder` operates with `Duration`.
Specifically, we want to configure the duration from the config:
```
cache.max = 5 minutes
```
```scala
val duration = config.get[Duration]("cache.max")
cached(_ => "key", duration.toSeconds.toInt) // yikes
```
> Add overloads with `Duration` to `Cached` helper class

- framework/src/play/src/main/scala/play/api/libs/Files.scala
- framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
This address comments made at #7713.
> Small improvements for temporary files creator spec

- framework/src/play-cache/src/main/scala/play/api/cache/Cached.scala
- framework/src/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
> [2.6.x]: Add overloads with `Duration` to `Cached` helper class (#7686)

- framework/project/Dependencies.scala
> [2.6.x]: Update play-ws-standalone to 1.0.7 (#7772)

- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Fixes #7791
This makes sure that `Statement`s and `PreparedStatement`s opened in the `EvolutionsApi` are properly closed.
The `execute` method is the one which was causing errors for me.
The `executeQuery` method couldn't actually cause any issue in the current code, because it was only ever called once before closing the connection, but I fixed it too just in case it's used differently some day.
See also #6164, which already fixed a similar issue.
> Properly close JDBC statements in evolutions API

- documentation/manual/releases/release27/migration27/Migration27.md
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/EssentialLoggingFilter.java
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/LoggingFilter.java
- documentation/manual/working/javaGuide/main/application/code/javaguide/application/httpfilters/RoutedLoggingFilter.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionsComposition.java
- documentation/manual/working/javaGuide/main/logging/JavaLogging.md
- documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/Application.java
- documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaLogging.java
- documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaMarkerController.java
- framework/src/play-logback/src/main/resources/logback-play-default.xml
- framework/src/play-logback/src/main/resources/logback-play-dev.xml
- framework/src/play-logback/src/main/resources/logback-play-logSql.xml
- framework/src/play/src/main/java/play/Logger.java
Addresses https://github.com/playframework/playframework/issues/1669 for Play 2.7
> Deprecate play.Logger

- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
- framework/src/play/src/test/scala/play/api/controllers/AssetsDateParsingSpec.scala
> Make parseModifiedDate return None for invalid dates

- framework/src/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala
> Increase timeout for allowed host filter spec

- framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
> [2.6.x] Support null and infinite when configuring timeouts

- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
> Add note about compile time dependency injection to WS config page

- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
Update akka, akka-http and async-http-client on 2.5.x.
> [2.5.x] Update several dependencies

- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FakeApplicationTest.java
> Fixed issue-6935-Functional test doc recommends using deprecated method

- framework/src/play-guice/src/main/java/play/libs/akka/AkkaGuiceSupport.java
> Deleted example code. It gived the play docs link.

- framework/src/play-ahc-ws/src/main/scala/play/api/test/WSTestClient.scala
Fixes the race condition in `WSTestClient` that's causing our builds to fail recently.
The main problem was that we were using an `AtomicReference` but were not checking the return value of `compareAndSet`. We also were mutating shared state before we knew whether we would actually use that client.
This fix is to set the client first using `compareAndSet`, then if the set succeeds schedule the idle check to run. If `compareAndSet` fails, we clean up the resources without having mutated any shared state.
> Fix race condition in WSTestClient

- documentation/manual/working/javaGuide/main/tests/JavaTest.md
> explain how to get mockito

- framework/src/play/src/main/java/play/http/DefaultHttpErrorHandler.java
> Fix-issue-7417-DefaultHttpErrorHandler should expose throwableToUsefulException method as protected scope

- framework/project/Dependencies.scala
Adds some fixes to the configuration mechanism
> Update play-json to 2.6.6

- documentation/manual/working/commonGuide/assets/AssetsOverview.md
grammar correction
Fixes #xxxx
> grammar correction

- documentation/manual/gettingStarted/Installing.md
- documentation/manual/gettingStarted/NewApplication.md
- documentation/manual/gettingStarted/Tutorials.md
Fixes/references #7702, #7768
Minor additions to documentation under "Getting Started".
> Adding to getting-started docs

- framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala
- framework/src/play-server/src/test/scala/play/core/server/ProdServerStartSpec.scala
For example, if the server does not have the secret key configured in production, it will stop but not clean up the pidfile afterwards.
Fixes #5510
> Delete the pidfile if server fails to start

- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSSpec.scala
- framework/src/play-java/src/main/java/play/libs/Resources.java
- framework/src/play/src/main/scala/play/api/mvc/Render.scala
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
This backports #7886 and #7851 to the 2.5.x branch
> [2.5.x] Always add Vary header in CORSFilter (backport #7886, #7851)

- framework/project/Dependencies.scala
See https://github.com/playframework/play-ws/milestone/2?closed=1 for a list of issues fixed in play-ws 1.1.2.
> Update play-ws to version 1.1.2

- documentation/manual/working/javaGuide/main/application/JavaErrorHandling.md
- documentation/manual/working/javaGuide/main/http/JavaActionCreator.md
- documentation/manual/working/scalaGuide/main/application/ScalaHttpRequestHandlers.md
- documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
I found a few parts of the documentation where we mention the way to do something is to create a class in the root package. Of course this will not work for compile-time DI users, since the whole point of compile-time DI is that everything is known at compile-time, so we don't have an opportunity to dynamically load classes. Feel free to point out any other areas that need clarification and I'll update them.
> Add some clarifications for compile-time DI users

- framework/src/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
This fixes a minor bug I noticed in my personal play server (running v2.6.5). 
Upon starting up my application, I receive these two log messages:
```
[debug] p.a.h.MediaRange - Unable to parse media range header '': end of input
[debug] p.a.h.MediaRange - Unable to parse media range header '': end of input
```
It took me a little while to trace down the root cause of this, and found out that, while I'm not using the Gzip filter, it still constructs the `GzipFilterConfig` object when my app starts up (since I'm importing and using other filters).
This causes it to look for the configuration values `play.filters.gzip.contentType.whiteList` and `blackList`, which returns an empty `Seq[String]`, because there are no elements defined (presumably in the reference config). It then makes a string …
> Avoids attemping to parse empty gzip MediaRange configuration.

- framework/src/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/run/PlayRunCompat.scala
- framework/src/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayRunCompat.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
Fixes #7898.
Filter out non-existing files and directories from the list of watched files.
> Avoid trying to watch non-existing files and directories

- framework/project/Dependencies.scala
> [2.6.x] Update dependencies (minor versions only)

- documentation/manual/working/javaGuide/main/ws/JavaWS.md
Backport of https://github.com/playframework/playframework/pull/7931
> [2.6.x] Fix inconsistent docs using asJson/asXml

- documentation/manual/working/commonGuide/assets/AssetsSass.md
sbt-sassify 1.4.9 is not available in the sbt-plugin-releases repo
> updated sbt-sassify to 1.4.11

- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
* [ x] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [ x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x ] Have you signed the [Lightbend CLA](https://www.lightbend.com/contribute/cla)?
* [ x] Have you referenced any issues you're fixing using [commit message keywords](https://help.github.com/articles/closing-issues-using-keywords/)?
* [x ] Have you added copyright headers to new files?
* [x ] Have you checked that both Scala and Java APIs are updated?
* [x ] Have you updated the documentation for both Scala and Java sections?
* [ x] Have you added tests for any changed functionality?
Fixes #xxxx
Are …
> added apostrophes

- documentation/manual/gettingStarted/IDE.md
More comprehensible
Beginners cannot understand in which files the commands has to be inserted.
Clear understanding of setting up  ide in eclipse with the certain changes that has to be made in the plugin and build files.
> [2.6.x]: Make it clear where to add sbt-eclipse settings

- documentation/manual/gettingStarted/IDE.md
To make documentation more comprehensible
It provides the  newbie and starters about actual file in which plugin has to be added.
> [2.6.x]: Make it clear where to add the sbt-eclipse plugin dependency

- framework/src/play-integration-test/src/test/scala/play/it/http/FormFieldOrderSpec.scala
This was previously part of #7941 but I was having trouble getting that PR to pass on Travis so I've cherry-picked it into a new PR.
> Update FormFieldOrderSpec to test HTTP/2

- documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
Fixes some typos in ScalaCsrf.md and JavaCsrf.md.
> Fixes some typos in ScalaCsrf.md and JavaCsrf.md.

- documentation/manual/working/scalaGuide/main/json/ScalaJsonHttp.md
> Remove charset=utf-8 from JSON HTTP examples

- documentation/manual/working/commonGuide/configuration/ws/LooseSSL.md
removed startsll because they are not trusted anymore (see: https://arstechnica.com/information-technology/2017/07/google-drops-the-boom-on-wosign-startcom-certs-for-good/). 
Also cacert is on the way out (see: https://www.golem.de/news/zertifizierungsstelle-ungewisse-zukunft-fuer-cacert-1403-105359.html)
Fixes #xxxx
> Update free certification authorities

- documentation/manual/working/commonGuide/production/Deploying.md
- framework/project/plugins.sbt
Follow up from #7975.
Version 1.3.2 includes a few bug fixes.
> Update sbt-native-packager to 1.3.2

- documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md
- framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
- framework/src/play/src/main/java/play/mvc/Action.java
- framework/src/play/src/main/scala/play/core/j/JavaAction.scala
> [2.6.x] Provide an action the information about its origin

- documentation/manual/working/commonGuide/assets/AssetsOverview.md
- framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
Make it possible to configure `Cache-Control` directives using partial paths. See the added documentation for details about how it should work.
> Make it possible to configure assets `Cache-Control` using partial paths

- documentation/build.sbt
- documentation/manual/gettingStarted/Anatomy.md
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- framework/bin/test-scala-211
- framework/project/BuildSettings.scala
- framework/project/Dependencies.scala
http://scala-lang.org/news/security-update-nov17.html
> security upgrade

- framework/build.sbt
- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
- framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
- framework/src/play/src/test/scala/play/api/mvc/InMemoryTemporaryFileCreator.scala
- framework/src/play/src/test/scala/play/api/mvc/MultipartBodyParserSpec.scala
> [2.6.x]: Fixes #7936 Check failure when writing an uploaded file

- framework/project/Dependencies.scala
https://akka.io/blog/news/2017/11/17/akka-2.5.7-released
https://github.com/brettwooldridge/HikariCP/blob/HikariCP-2.7.4/CHANGES
> Upgrade Akka and HikariCP

- documentation/manual/working/scalaGuide/main/http/ScalaActions.md
- documentation/manual/working/scalaGuide/main/http/code/ScalaActions.scala
> Include examples of implicit request in Action documentation

- documentation/manual/releases/release26/Highlights26.md
- framework/src/sbt-plugin/src/main/scala/play/sbt/Play.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/README
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/project/plugins.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/src/main/resources/application.conf
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/src/main/resources/routes
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/src/main/scala/controllers/HomeController.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/test
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/README
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/project/plugins.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/src/main/resources/application.conf
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/src/main/scala/controllers/HomeController.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/src/main/scala/router/Routes.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/test
This backports #8011 but keeps the Play plugin the same.
> [2.6.x] Create sbt plugin for Play services

- documentation/manual/releases/release26/Highlights26.md
Forward-port of changes from #8035
> Forward-port PlayService info in 2.6 highlights

- documentation/manual/working/scalaGuide/main/http/ScalaActionsComposition.md
Minor documentation fix in `ScalaActionsComposition.md`
> ScalaActionsComposition.md doc fix

- documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/FiltersTest.java
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java
- framework/src/play-integration-test/src/test/java/play/BuiltInComponentsFromContextTest.java
- framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java
- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
- framework/src/play-java/src/main/java/play/routing/RoutingDsl.java
- framework/src/play-java/src/main/java/play/routing/RoutingDslComponents.java
- framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
- framework/src/play-java/src/main/scala/play/routing/RoutingDslModule.scala
> [master]: Use a Java BodyParser in RoutingDsl

- framework/project/BuildSettings.scala
- framework/src/play-akka-http-server/src/main/resources/reference.conf
- framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
- framework/src/play-microbenchmark/src/test/scala/play/core/server/netty/NettyHelpers.scala
- framework/src/play-netty-server/src/main/resources/reference.conf
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
> [2.6.x] Easy way to set server-header when using Netty (#8028)

- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
> Fixed-issue-5957-Mention scala-guice helpers in docs

- framework/build.sbt
- framework/project/BuildSettings.scala
Compilation and test should now add copyright header automatically.
> Enables Header creation on all projects

- documentation/manual/working/javaGuide/main/akka/JavaAkka.md
- documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
- framework/src/play/src/main/resources/play/reference-overrides.conf
- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
- framework/src/play/src/test/resources/application-infinite-timeout.conf
- framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
> Disable Akka-CS's JVM shutdown hook

- framework/src/play/src/main/resources/play/reference-overrides.conf
- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
- framework/src/play/src/test/scala/play/api/libs/concurrent/ActorSystemProviderSpec.scala
> Use Akka's Reason when shutting down and disable Akka JVM hooks globally

- documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
- framework/src/play/src/main/scala/play/api/mvc/macros/BinderMacros.scala
- framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala
added a way to do the thing I commited for `PathBindable`'s to `QueryStringBindable`'s.
> makes it possible to have implicit QueryStringBindable's for AnyVal

- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
This can be used by Lagom to remove the need to copy and paste all of the ActorSystemProvider.start code in LagomApplicationLoader.scala.
See https://git.io/vbM3g
Intend to use this in https://github.com/lagom/lagom/pull/1109 to prevent the two implementations from falling out of sync.
> [2.6.x] Add a way to pass additional ActorSystem setup

- framework/src/play/src/main/scala/play/api/libs/concurrent/Akka.scala
This is a forward port of #8110.
> This can be used by Lagom to remove the need to copy and paste all of the ActorSystemProvider.start code in LagomApplicationLoader.scala.
> Add a way to pass additional ActorSystem setup

- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
> Log assets configuration at debug instead of warn

- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/001.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/0010.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/002.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/005.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/01.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/010.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/0100.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/02.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/05.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/4.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/6.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/7.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/8.sql
- framework/src/play-jdbc-evolutions/src/test/resources/evolutions/test/9.sql
- framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsReaderSpec.scala
- framework/src/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/LogbackCapturingAppender.scala
> [2.6.x] Support evolutions scripts prefixed with zeros

- framework/project/Dependencies.scala
> Upgrade HikariCP

- framework/project/Dependencies.scala
> Upgrade akka

- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Fixes a problem when reading evolutions generated dynamically
We need to use `env.getExistingFile` and fallback to `env.resource` because there are dynamic evolutions generated at runtime for development env, for example when using play-ebean. These dynamic evolutions are not present at the classpath and so we need to try to read the file first and then fallback to resources on the classpath.
/cc @mkurz 
https://github.com/playframework/play-ebean/pull/144
> Fix environment evolutions reader

- framework/project/Dependencies.scala
Because of brettwooldridge/HikariCP#1064
Needs backport
> Upgrade HikariCP once more

- documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
Forward port #5001 to master branch.
> [master]: Add missing import block in documentation about Forms

- documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
Forward port #5001 to **2.6.x** branch.
> [2.6.x]: Add missing import block in documentation about Forms

- documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
Forward port #5001 to **2.5.x** branch.
> [2.5.x]: Add missing import block in documentation about Forms

- framework/src/play-ws/src/main/scala/play/api/libs/ws/ssl/Config.scala
> [2.5.x]: Make SSLConfigParser accept Configuration

- framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/AkkaRequestTimeoutSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
- framework/src/play-java-forms/src/main/java/play/data/Form.java
- framework/src/play-java-forms/src/main/java/play/data/validation/MappedConstraintValidatorFactory.java
- framework/src/play-test/src/main/scala/play/api/test/Selenium.scala
- framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/main/scala/play/api/LoggerConfigurator.scala
- framework/src/play/src/main/scala/play/api/inject/Injector.scala
- framework/src/play/src/main/scala/play/api/mvc/Binders.scala
- framework/src/play/src/main/scala/play/utils/Reflect.scala
Fixes small deprecations and warnings when building Play using Java 9.
#7879
> Java 9 compatibility improvements

- framework/project/BuildSettings.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
- framework/src/play-server/src/main/scala/play/core/server/Server.scala
- framework/src/play/src/main/scala/play/core/ApplicationProvider.scala
> [2.6.x]: Avoid multiple calls to ApplicationProvider#get for a single request

- framework/project/PlayWhitesourcePlugin.scala
Related to https://github.com/playframework/interplay/pull/44.
> [2.5.x]: Update Whitesource project naming policy

- documentation/manual/working/commonGuide/configuration/ConfigFile.md
- documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md
- documentation/manual/working/commonGuide/configuration/code/build.sbt
- framework/src/play-server/src/main/scala/play/core/server/DevServerStart.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/app/Module.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
> [2.6.x]: Preserve all devSettings including Akka's (#8173)

- framework/build.sbt
- framework/project/plugins.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
> [2.6.x]: Update interplay to version 1.3.14 (#8191)

- .gitattributes
- framework/build.sbt
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ForwardedHeaderHandlerSpec.scala
- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
- framework/src/play/src/test/scala/play/api/http/WriteableSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/BindersSpec.scala
- framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
> Windows compatibility fixes (backport)

- framework/bin/scriptLib
- framework/project/plugins.sbt
Update interplay to version 1.3.15.
#8191 and https://github.com/playframework/interplay/pull/46.
> Update interplay to version 1.3.15

- framework/bin/scriptLib
- framework/project/plugins.sbt
> [2.6.x]: Update interplay to version 1.3.15

- documentation/build.sbt
- documentation/manual/gettingStarted/Anatomy.md
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- framework/bin/test-scala-211
- framework/project/BuildSettings.scala
- framework/project/Dependencies.scala
> [2.6.x]: security upgrade (#8018)

- framework/project/Dependencies.scala
- framework/project/plugins.sbt
> Upgrade netty and sbt-native-packager

- documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
Adds documentation for [a common problem when deploying to Heroku](https://stackoverflow.com/questions/48078645/i-deployed-play-framework-app-to-heroku-but-it-doesnt-work/48080897)
> Added troubleshooting section for Heroku deployment

- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play/src/main/scala/play/api/mvc/MessagesRequest.scala
- framework/src/play/src/main/scala/play/api/mvc/Security.scala
- framework/src/play/src/test/scala/play/core/test/Fakes.scala
Fixes https://github.com/playframework/playframework/issues/8240
> Make request types covariant

- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Fixes a `java.nio.file.FileSystemNotFoundException` when running a Play app that has evolutions in prod mode (e.g. `sbt stage`) with Play compiled from the current `master` branch, having #8153 applied.
See [my comment here](https://github.com/playframework/playframework/pull/8153/files#r161624801).
/cc @marcospereira
> Once more fix environment evolutions reader

- framework/project/Dependencies.scala
Update Akka to version 2.5.10.
> Update Akka to version 2.5.10

- framework/project/plugins.sbt
> Upgrade twirl

- framework/project/Dependencies.scala
Updates play-ws to version 1.1.4.
> Update play-ws to version 1.1.5

- CONTRIBUTING.md
text.replace("2017", "2018") ;)
> Contribution Guidelines: Update Copyright year to 2018

- framework/project/Dependencies.scala
I guess this should be ok to backport.
> [Backport 2.6.x] Update Reactive Streams to 1.0.2 (#8272)

- documentation/manual/hacking/Documentation.md
Based on my previous PR to introduce the usage of unisex names in the documentation examples, I have been encouraged (https://github.com/playframework/playframework/pull/8217#event-1476477834) to add a short guideline for the use of gender-neutral language and names.
I'm interested to hear what you think.
> Add guideline for use of gender-neutral language

- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaActionCreator.java
- framework/src/play/src/main/java/play/libs/Json.java
- framework/src/play/src/main/scala/views/helper/Helpers.scala
Fixes #8283.
Remove duplicated copyright headers.
> Remove duplicated copyright headers

- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release27/migration27/Migration27.md
- documentation/manual/working/scalaGuide/main/akka/code/ScalaAkka.scala
- documentation/manual/working/scalaGuide/main/dependencyinjection/code/RuntimeDependencyInjection.scala
- framework/project/BuildSettings.scala
- framework/project/Dependencies.scala
- framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala
- framework/src/play-guice/src/test/scala/play/api/inject/ModulesSpec.scala
- framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala
- framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceInjectorBuilderSpec.scala
- framework/src/play-specs2/src/test/scala/play/api/test/SpecsSpec.scala
- framework/src/play-test/src/main/java/play/test/TestBrowser.java
- framework/src/play-test/src/main/scala/play/api/test/Selenium.scala
Release notes:
https://github.com/google/guice/wiki/Guice42
Adds Java 9 support:
https://github.com/google/guice/issues/1085#event-1497746031
I think we want to backport this?
> Upgrade Guice

- documentation/manual/releases/release27/migration27/Migration27.md
- framework/src/play-java-forms/src/main/java/play/data/Form.java
> Remove callLegacyValidateMethod

- documentation/manual/ModuleDirectory.md
Object storage DSL
Fixes #xxxx
> Benji module

- documentation/README.md
Per https://twitter.com/kelleyrobinson/status/975386818278543360
> Add contribution and download links to doc README

- framework/src/play-java/src/test/java/play/mvc/HttpTest.java
- framework/src/play/src/main/java/play/i18n/Messages.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
> [2.6.x] used typed keys to pass the current context lang to scala (#8288)

- documentation/manual/working/scalaGuide/main/tests/code/specs2/WithDbDataSpec.scala
- framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
- framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/BasicHttpClient.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/SecureFlagSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala
- framework/src/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- framework/src/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- framework/src/play-server/src/main/scala/play/core/server/ProdServerStart.scala
- framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/ExecutionSpec.scala
- framework/src/play-test/src/main/scala/play/api/test/Selenium.scala
- framework/src/play-test/src/main/scala/play/api/test/TestServer.scala
- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
- framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
- framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
- framework/src/play/src/main/scala/play/core/j/HttpExecutionContext.scala
- framework/src/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
- framework/src/play/src/test/scala/play/utils/ResourcesSpec.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
procedure syntax is deprecated
https://github.com/scala/bug/issues/7605
> avoid procedure syntax

- framework/project/Docs.scala
related to https://github.com/playframework/playframework/pull/8317
related to https://github.com/lightbend/platform-reconciliation/issues/33
related to https://github.com/lagom/lagom/pull/1283
> Adds cross-linking to Akka and Java SE javadocs

- .github/ISSUE_TEMPLATE.md
Pointing the github text to new place
> Update issue template to point to discuss.lightbend.com

- framework/project/Dependencies.scala
Updates play-ws to version 1.1.7.
> Update play-ws to version 1.1.7

- framework/project/Dependencies.scala
https://github.com/brettwooldridge/HikariCP/releases/tag/HikariCP-2.7.9
> Upgrade HikariCP in 2.6.x branch

- documentation/manual/working/commonGuide/production/Deploying.md
- framework/project/plugins.sbt
https://github.com/sbt/sbt-native-packager/releases/tag/v1.3.4
> Upgrade sbt-native-packager

- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release27/migration27/Migration27.md
- framework/project/Dependencies.scala
- framework/src/play-jdbc/src/main/resources/reference.conf
- framework/src/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
https://github.com/brettwooldridge/HikariCP/blob/HikariCP-3.0.0/CHANGES
> New major release of HikariCP

- documentation/manual/releases/release24/migration24/Migration24.md
- framework/project/BuildSettings.scala
- framework/src/play-cache/src/main/scala/play/api/cache/SyncCacheApi.scala
- framework/src/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheApi.scala
- framework/src/play-ehcache/src/main/scala/play/api/cache/ehcache/EhCacheApi.scala
Fixes #7805
Remove deprecated `CacheApi` usages in `EhCacheApi`.
> Remove deprecated CacheApi usages (#7805)

- framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
> Only apply logback-test.xml in Test mode

- framework/project/Dependencies.scala
http://netty.io/news/2018/05/14/4-1-25-Final.html
> Netty upgrade

- documentation/README.md
- documentation/build.sbt
- documentation/manual/ModuleDirectory.md
- documentation/manual/gettingStarted/PlayConsole.md
- framework/project/BuildSettings.scala
- framework/project/Dependencies.scala
- framework/src/build-link/src/main/java/play/TemplateImports.java
- framework/src/play-jdbc/src/main/scala/play/api/db/DBModule.scala
- framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/ConnectionPoolConfigSpec.scala
- framework/src/run-support/src/main/scala/play/runsupport/Reloader.scala
Contains several backports from master to 2.6.x - see list of commits. *This PR should be rebased, but not squashed.*
> Misc backports to 2.6.x

- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
> Correct implementation of ConfigLoader[Seq[Long]] to load all longs

- documentation/manual/releases/release26/Highlights26.md
- framework/bin/test-sbt-plugins-1_0
- framework/bin/test-scala-212
- framework/project/BuildSettings.scala
- framework/project/Dependencies.scala
- framework/src/play-akka-http-server/src/sbt-test/akka-http/play-akka-http-plugin/build.sbt
- framework/src/play-akka-http-server/src/sbt-test/akka-http/system-property/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service-with-routes-file/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/basic-service/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/module/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/aggregate-reverse-routes/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/incremental-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/routes-compilation/build.sbt
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/source-mapping/build.sbt
> Use Scala 2.12.6 in tests and docs

- framework/src/play/src/main/scala/play/api/mvc/Action.scala
> Call ExecutionContext.prepare in Action.apply

- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
- framework/src/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
- framework/src/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala
> corrected methods for akka 2.5.12

- documentation/manual/releases/release27/migration27/Migration27.md
- framework/project/Dependencies.scala
latest Google Guava (version 25.1)
latest Google Guava (version 25.1)
latest Google Guava (version 25.1)
n/a
> Google Guava 24.1 -> 25.1

- framework/project/Dependencies.scala
latest Jackson library (2.9.6)
latest Jackson library (2.9.6)
latest Jackson library (2.9.6)
n/a
> Jackson 2.9.6

- framework/src/play-java-jdbc/src/main/java/play/db/Databases.java
- framework/src/play-java/src/main/java/play/libs/Time.java
- framework/src/play/src/main/java/play/core/Paths.java
- framework/src/play/src/main/java/play/core/cookie/encoding/ClientCookieDecoder.java
- framework/src/play/src/main/java/play/core/cookie/encoding/DefaultCookie.java
- framework/src/play/src/main/java/play/mvc/Result.java
Small set of changes, found by static code analysis. Done in my spare time, don't spend too much time on this if you have actual work to do :)
As already stated: These are some small changes, found by means of static code analysis. They all fall under category "performance". While nothing world shocking, I do feel it's worth it.
> A small set of changes, brought to light by static code analysis.

- framework/src/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
- framework/src/play/src/test/scala/play/api/inject/DefaultApplicationLifecycleSpec.scala
Related to https://github.com/playframework/playframework/pull/8497#discussion_r199424160
> Handle exceptions thrown from stop hooks

- documentation/manual/working/commonGuide/build/BuildOverview.md
- documentation/manual/working/commonGuide/build/SBTDebugging.md
- documentation/manual/working/javaGuide/main/http/JavaActions.md
Forward ports #8074, #8119 and #8463.
Please, don't squash when merging to keep contributions history. :-)
Fixes #8358.
> [master]: Forward ports documentation improvements

- framework/src/play-integration-test/src/test/scala/play/it/http/HttpErrorHandlingSpec.scala
- framework/src/play-server/src/main/scala/play/core/server/Server.scala
> [2.6.x] Use configured HttpErrorHandler for exceptions before action is created

- framework/src/play/src/main/java/play/mvc/BodyParser.java
I ran into this while testing out PMD's duplicate code finder. Turns out there's a utility class that has a method which does exactly what the code in the override does. So I changed it to that.
Apart from this, there's actually only 8 other results generated by the tool across the entire framework code and it's all very particular bits that can't be unified away.
> MINOR: Duplicate code identified and factored out.

- framework/src/play-jdbc/src/main/scala/play/api/db/DefaultDBApi.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/DBApiSpec.scala
Brings some of the changes we made at #8502 to master branch.
#8502 and #8497.
> DBApi improvements after supporting app initialization when database is unavailable

- framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
- framework/src/play/src/test/scala/play/api/controllers/AssetsSpec.scala
Fixes a compatibility issue in assets controller when an application is running on Windows.
> Fix Windows compatibility issue in assets controller

- framework/src/play-integration-test/src/test/scala/play/it/http/assets/AssetsSpec.scala
- framework/src/play/src/main/scala/play/api/controllers/Assets.scala
- framework/src/play/src/test/scala/play/api/controllers/AssetsSpec.scala
> [master]: Fix Windows compatibility issue in assets controller

- framework/src/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
- framework/src/play-jdbc/src/main/scala/play/api/db/Databases.scala
- framework/src/play-jdbc/src/test/resources/application.conf
- framework/src/play-jdbc/src/test/resources/logback-test.xml
- framework/src/play-jdbc/src/test/scala/play/api/db/DBApiSpec.scala
- framework/src/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
> [2.6.x]: Handle database not available in Prod/Dev/Test modes

- documentation/manual/Home.md
- documentation/manual/LatestRelease.md
- documentation/manual/releases/index.toc
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release27/migration27/Migration27.md
- documentation/manual/releases/release27/migration27/index.toc
- documentation/manual/working/commonGuide/filters/GzipEncoding.md
Add Play 2.7 to listed releases and as the latest release. Add some new sections to our migration guide.
> Improve 2.7 migration guide

- framework/src/play/src/main/scala/play/api/ApplicationLoader.scala
Possibly a competitor for most trifling change of the year, but I noticed this was missing when exploring the source
> Add type annotation to BICFC fields

- documentation/manual/working/commonGuide/build/code/enhancer.sbt
Bump play-enhancer plugin version to 1.2.2 in document.
Fixes (not really a **fix**) #8438 
Bump play-enhancer plugin version to 1.2.2 in document.
#8438
> Bump play-enhancer plugin version in document.

- framework/project/Dependencies.scala
- framework/project/plugins.sbt
- framework/src/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/run/PlayRunCompat.scala
- framework/src/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayRunCompat.scala
- framework/src/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
> [2.6.x]: Fix sbt auto trigger when using sbt 1.1.5+ (#8558)

- framework/src/play/src/main/scala/play/api/mvc/Controller.scala
The logger in `InjectedController` trait is unused, so remove it.
> Remove unneeded logger

- framework/src/play-java-forms/src/main/java/play/data/Form.java
- framework/src/play-java-forms/src/test/java/play/data/BlueValidator.java
- framework/src/play-java-forms/src/test/java/play/data/DarkBlueValidator.java
- framework/src/play-java-forms/src/test/java/play/data/MyBlueUser.java
- framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
> @ValidateWith now uses args from getErrorMessageKey()

- framework/project/Dependencies.scala
Keep Play updated with the latest milestone of Play-WS.
> Update Play-WS to version 2.0.0-M3

- framework/project/Dependencies.scala
Minor dependencies updates before releasing.
> Minor dependencies updates

- framework/project/Dependencies.scala
https://akka.io/blog/news/2018/08/29/akka-2.5.16-security-fix-released
> Akka 2.5.16 Security Patch

- documentation/manual/working/javaGuide/main/akka/JavaAkka.md
- documentation/manual/working/javaGuide/main/akka/code/javaguide.akkaupdate.sbt
- documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
- documentation/manual/working/scalaGuide/main/akka/code/scalaguide.akkaupdate.sbt
Documents how to manually update Akka if necessary.
A follow up to #8590.
> Document how to upgrade Akka manually

- documentation/manual/working/javaGuide/main/tests/JavaTest.md
> Remove the mention of Scala in java testing docs

- documentation/manual/releases/release27/migration27/Migration27.md
Fixes #8611.
Add example and a longer explanation about `allowGlobalApplication` default change.
> Add longer explanation about allowGlobalApplication change

- documentation/manual/working/javaGuide/main/sql/JavaJPA.md
> Fix incomplete sentence in JPA doc

- documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayAkkaHttp.md
- documentation/manual/working/scalaGuide/advanced/embedding/ScalaEmbeddingPlayNetty.md
- documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala
- documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaNettyEmbeddingPlay.scala
- documentation/manual/working/scalaGuide/advanced/embedding/code/embedded.sbt
Follow up to #8619 since configuring logging was relevant to debug the problem, but it is not explained on the docs about embedding Play.
> Explain how to configure logging when embedding Play servers

- documentation/build.sbt
- framework/src/play-test/src/main/java/play/test/TestServer.java
A small follow up after #8320 merge.
> Fail docs validation when using deprecated APIs

- framework/bin/scriptLib
> Use Akka 2.5 snapshots only for cron builds

- documentation/manual/working/javaGuide/main/application/JavaErrorHandling.md
- documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
- framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
Take @gmethvin review remarks of this PR https://github.com/playframework/playframework/pull/8299 into account.
> Doc for `JsonHttpErrorHandler`

- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/app/controllers/HomeController.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/app/router/Routes.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/build.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/conf/application.conf
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/Build.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/project/plugins.sbt
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
This is a port of generated-keystore scripted test that was added in `master`.
> added generated keystore test

- framework/project/BuildSettings.scala
- framework/src/play/src/main/scala/play/api/i18n/Langs.scala
- framework/src/play/src/main/scala/play/api/i18n/Messages.scala
> More asJava methods

- framework/project/BuildSettings.scala
- framework/project/Dependencies.scala
- framework/src/play-integration-test/src/test/scala/play/it/test/ServerEndpoint.scala
- framework/src/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala
- framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
> Upgrade to ssl-config 0.3.4

- framework/project/BuildSettings.scala
- framework/src/play-test/src/main/scala/play/api/test/Fakes.scala
- framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
- framework/src/play/src/test/scala/play/core/test/Fakes.scala
- project/build.properties
https://github.com/playframework/playframework/issues/8651
> remove: deprecated copy method on RequestHeader

- documentation/manual/gettingStarted/Requirements.md
I think PR checklist is not needed :)
> Fixed repeated word "install"

- framework/src/play-exceptions/src/main/java/play/api/UsefulException.java
Driven by the need to have more information for various runtime exceptions, e.g. `@79emlk42a: No valid constructors at ...` without any reference for a problem class that is passed as a description to this exception.
Fixes #xxxx
> Output exception description for better diagnostics.

- CONTRIBUTING.md
Fixes two broken links by replacing them with a link in gitbooks.io.
> Fixed two broken links

- framework/project/Dependencies.scala
- framework/src/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
- framework/src/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
Update ssl-config to version 0.3.5
* https://github.com/lightbend/ssl-config/pull/125
* https://github.com/lagom/lagom/pull/1610
> Update ssl-config to version 0.3.5

- framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
At the time of merging #8546 and #8663 both were green, however turns out #8663 broke #8546.
> Fix Travis

- documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
- documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
- framework/src/play/src/main/java/play/mvc/Controller.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/java/play/mvc/Result.java
- framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
- framework/src/play/src/main/scala/play/api/mvc/Session.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
> Deprecate Http.Context.session method

- framework/src/play-specs2/src/main/scala/play/api/test/Specs.scala
- framework/src/play-test/src/main/scala/play/api/test/RunningServer.scala
- framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
- framework/src/play-test/src/main/scala/play/api/test/TestServerFactory.scala
* Introduces `play.api.test.TestServerFactory`
* Introduces play.api.test.ForServer in `play-specs2`
> More testkit changes from Akka gRPC experiments

- framework/bin/test-docs
- framework/src/play-server/src/main/scala/play/core/server/SelfSigned.scala
- framework/src/play-server/src/main/scala/play/core/server/ServerEndpoint.scala
- framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
- framework/src/play-test/src/main/scala/play/api/test/TestServerFactory.scala
> Extract SelfSigned into a separate file

- framework/src/play/src/main/scala/play/api/Configuration.scala
- framework/src/play/src/test/scala/play/api/ConfigurationSpec.scala
Allow to parse URL and URI directly from `play.api.Configuration`:
```
val config = Configuration.load()
val serverUrl = config.get[URL]("server.url")
val credentialsFileUri = config.get[URI]("credentials.uri")
```
> Add URL & URI `ConfigLoader`s

- framework/src/play-test/src/main/scala/play/api/test/Helpers.scala
> add stubMessagesControllerComponents helper

- framework/src/play-cache/src/main/java/play/cache/CachedAction.java
- framework/src/play-filters-helpers/src/main/java/play/filters/csp/AbstractCSPAction.java
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
- framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionActionCreator.java
- framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/TransactionalAction.java
- framework/src/play/src/main/java/play/http/DefaultActionCreator.java
- framework/src/play/src/main/java/play/mvc/Security.java
- framework/src/play/src/test/java/play/mvc/SecurityTest.java
Travis will fail for that one right now.
Will turn green after merging #8692 and #8639.
However - can be reviewed already.
> Change occurrences of call(ctx) to call(req)

- framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
I do not see the need to save the same data in `Form` and `DynamicForm`:
https://github.com/playframework/playframework/blob/c19a9bd27ade8e965b351abb00de38edad4e43e3/framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java#L31
https://github.com/playframework/playframework/blob/c19a9bd27ade8e965b351abb00de38edad4e43e3/framework/src/play-java-forms/src/main/java/play/data/Form.java#L95
`rawData` was introduced in `DynamicForm` [looong time ago](https://github.com/playframework/playframework/pull/486) to fix a bug. Given that James Roper did add tests back then and these tests don't fail now, I think it's ok to remove the redundant data. It's just confusing.
> Remove redundant data from DynamicForm

- framework/src/play-exceptions/src/main/java/play/api/UsefulException.java
Driven by the need to have more information for various runtime exceptions, e.g. `@79emlk42a: No valid constructors at ...` without any reference for a problem class that is passed as a description to this exception.
Fixes #xxxx
> [2.6.x]: Output exception description for better diagnostics.

- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/ServerFunctionalTest.java
- framework/src/play-test/src/main/java/play/test/Helpers.java
- framework/src/play-test/src/main/java/play/test/TestServer.java
- framework/src/play-test/src/test/java/play/test/TestServerTest.java
> [2.6.x]: java versions of runningHttpPort/runningHttpsPort methods added to TestServer

- documentation/manual/working/commonGuide/filters/CorsFilter.md
- framework/src/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/cors/CORSCommonSpec.scala
* [] Have you checked that both Scala and Java APIs are updated?
Fixes #8600 
Allows null as CORS origin value.
> Allows null origin in CORS.

- framework/project/Dependencies.scala
latest version of Netty
latest version of Netty
latest version of Netty
n/a
> Netty 4.1.30.Final

- framework/src/play/src/main/java/play/mvc/Security.java
> Fix copy/paste javadoc typo

- framework/project/BuildSettings.scala
- framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
- framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
- framework/src/play/src/main/scala/play/api/mvc/Request.scala
- framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
- framework/src/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
To remove a request attribute of course :wink: 
(Why not? Also would be nice to have for an upcoming pull request of mine)
> Add request.rmAttr(key)

- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
> Deprecate constructors in DefaultJPAApi which use ThreadLocal

- documentation/manual/releases/release27/migration27/Migration27.md
See https://github.com/playframework/playframework/pull/8745#discussion_r229565890
> Upgrades migration27 to fix guava version

- documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/AssetsBuilder.java
Fixes #8231 , almost fixed by @jn-se in #8238 , thought I would finish it.
> Fix AssetsBuilder.java

- framework/project/Dependencies.scala
Update play-file-watch (which brings the new version fo directory-watcher) and also sbt-web.
> Update play-file-watch and sbt-web

- .travis.yml
- framework/bin/test-docs
- framework/bin/validate-docs
- framework/project/plugins.sbt
- framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
- framework/src/play/src/main/scala/play/core/parsers/Multipart.scala
Split the build into multiple stages.
https://docs.travis-ci.com/user/build-stages/
> Build stages

- documentation/build.sbt
- framework/bin/scriptLib
- framework/bin/test-docs
- framework/bin/test-sbt-plugins-0_13
- framework/bin/test-sbt-plugins-1_0
- framework/bin/validate-docs
- framework/bin/validate-microbenchmarks
- framework/project/BuildSettings.scala
- framework/src/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
- framework/src/play-integration-test/src/test/resources/logback.xml
- framework/src/play-integration-test/src/test/scala/play/it/api/SecretConfigurationParserSpec.scala
Have a build output that shows test execution results.
We have something similar for Lagom: https://github.com/lagom/lagom/pull/1399
> Better build output

- documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
- framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
- framework/src/play/src/main/java/play/mvc/Http.java
Proofreading the `Http.Context` migration guide and some other minor changes to the APIs.
> Minor improvements to http context

- documentation/manual/working/javaGuide/main/tests/JavaTest.md
- documentation/manual/working/javaGuide/main/tests/JavaTestingWithDatabases.md
- documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
Forward port:
- #8635 
- #8602 
- #8521
> Forward port multiple documentation changes

- framework/src/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
Forward port #8642.
Fixes #8660.
> [master]: Honor play settings on AkkaHttpServer for client auth in SSL

- documentation/manual/releases/release27/migration27/Migration27.md
> Document how to use a custom reason with coordinated shutdown

- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
Fixes #8730 
Simple fix to part of link in docs
> fixed broken link (issue #8730)

- framework/src/play/src/main/scala/play/core/hidden/ObjectMappings.scala
https://github.com/playframework/playframework/issues/8748
FIx ObjectMappings generate script.
https://github.com/scala/scala/blob/2.10.x/src/manual/scala/man1/scala.scala#L227
https://github.com/scala/scala/blob/2.11.x/src/manual/scala/man1/scala.scala#L223
> argv to args

- documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
- framework/project/BuildSettings.scala
- framework/src/play-java-forms/src/main/java/play/data/Form.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAComponents.java
- framework/src/play-java-jpa/src/main/java/play/db/jpa/JPAEntityManagerContext.java
- framework/src/play-java-jpa/src/main/resources/reference.conf
- framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
- framework/src/play/src/main/java/play/mvc/Action.java
- framework/src/play/src/main/java/play/mvc/Http.java
- framework/src/play/src/main/resources/reference.conf
- framework/src/play/src/main/scala/play/core/j/HttpExecutionContext.scala
- framework/src/play/src/main/scala/play/core/j/JavaAction.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
- framework/src/play/src/main/scala/play/core/routing/HandlerInvoker.scala
@marcospereira What do you think?
> Disable Http.Context and JPA thread local via system property

- documentation/manual/working/commonGuide/configuration/code/detailedtopics/httpec/MyController.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
- documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
- documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
- documentation/manual/working/scalaGuide/main/http/code/ScalaSessionFlash.scala
- documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala
- documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
- framework/project/BuildSettings.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsSpec.scala
- framework/src/play-integration-test/src/test/scala/play/it/server/ServerReloadingSpec.scala
- framework/src/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
- framework/src/play/src/main/java/play/mvc/Result.java
- framework/src/play/src/main/scala/play/api/mvc/Results.scala
- framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
Fixes https://github.com/playframework/playframework/issues/8779
> refactor method name(from flashing to flash)

- framework/src/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Attempt to fix #8212
/cc @wsargent Does this look correct to you?
> LoggerContext.reset should not remove just added listeners

- framework/src/routes-compiler/src/main/scala/play/routes/compiler/RoutesModels.scala
- framework/src/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
- framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/tests/RouterSpec.scala
> Need to filter params for java request

- documentation/manual/releases/release27/migration27/Migration27.md
- framework/project/BuildSettings.scala
- framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
- framework/src/play-filters-helpers/src/main/resources/reference.conf
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
- framework/src/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- framework/src/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
Default is ~~not to set the SameSite attribute.~~ to set the same SameSite attribute like the session has.
> SameSite attribute for CSRF cookie

- framework/project/Dependencies.scala
- framework/project/plugins.sbt
- framework/src/play-test/src/main/java/play/test/TestBrowser.java
The main purpose is to update:
- twirl to version 1.4.0-RC4
- play-ws to version 2.0.0-RC2
- play-json 2.7.0-RC2
Other libraries updated too.
> Update dependencies before Release Candidate 4

- documentation/project/build.properties
- framework/project/build.properties
latest version of SBT
latest version of SBT
latest version of SBT
latest version of SBT
> sbt 0.13.18

- documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/JavaAkka.java
- framework/project/Dependencies.scala
https://akka.io/blog/news/2018/12/07/akka-2.5.19-released
Fixes #8856
> Akka 2.5.19

- project/build.properties
Looks like committed by accident in #8832
> Remove unnecessary file

- documentation/project/build.properties
- framework/project/build.properties
- project/build.properties
#8870 for the 2.7.x branch.
Also cherry-picks the pr which upgrades sbt in master...
> [2.7.x] Remove unnecessary file

- documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
- https://github.com/playframework/playframework/issues/8233
> Issue 8233 | Tried to clarify wording regarding custom errorHandler cfg

- documentation/manual/working/commonGuide/configuration/ConfigFile.md
> Reference application.conf as file in ConfigFile

- documentation/manual/working/commonGuide/build/code/dependencies.sbt
- documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
- framework/project/Dependencies.scala
http://in.relation.to/2018/12/12/hibernate-orm-540-final-out/
> Hibernate 5.4.0

- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/Application.java
> Correct order of params in doc example

- .travis.yml
Build Play using AdoptOpenJDK 8 & 11 (11 still allowed to fail).
> Build using AdoptOpenJDK 8 & 11

- framework/src/play/src/main/scala/play/api/mvc/Results.scala
Minor documentation fix to clarify the function signature.
> Update sendPath method documentation

- .mergify.yml
We don't allow merge commits in this repo.
See https://doc.mergify.io/actions.html#merge
> Mergify should squash

- framework/project/Dependencies.scala
play-json 2.7.0
play-json 2.7.0
play-json 2.7.0
play-json 2.7.0
> play-json 2.7.0

- documentation/manual/tutorial/ImplementingHelloWorld.md
- documentation/manual/working/commonGuide/configuration/ConfigFile.md
Forward port of
* #8888
* #8847
to the master branch. They only made it in 2.6.x.
> [master] Forward port documentation fixes

- documentation/manual/releases/release25/migration25/Migration25.md
- documentation/manual/tutorial/ImplementingHelloWorld.md
- documentation/manual/working/commonGuide/configuration/ConfigFile.md
Same like #8975 but for 2.7.x branch.
> [2.7.x] Forward port documentation fixes

- framework/project/Dependencies.scala
- framework/project/plugins.sbt
> Upgrade twirl and play-ws-standalone to final releases

- framework/bin/publish-local
See https://github.com/playframework/playframework/pull/8986#issuecomment-458511532
> publishLocal for all Scala versions (in daily cron build)

- framework/build.sbt
- framework/project/BuildSettings.scala
- framework/src/play/src/main/java-scala-2.13+/play/libs/CrossScala.java
- framework/src/play/src/main/java-scala-2.13-/play/libs/CrossScala.java
- framework/src/play/src/main/java/play/libs/Scala.java
- framework/src/play/src/main/java/play/libs/typedmap/TypedMap.java
- framework/src/play/src/main/scala/play/api/data/Form.scala
> Forwardports from getting Play 2.7 working on Scala 2.13

- framework/build.sbt
- framework/project/BuildSettings.scala
> MiMa should check against 2.7.0 tag in 2.7.x branch

- framework/project/BuildSettings.scala
See https://github.com/playframework/playframework/pull/9003#issuecomment-459186717
> MiMa should check against 2.7.0 tag in master branch

- framework/build.sbt
We should now check binary compatibility for play-caffeine-cache module.
> Check binary compatibility for play-caffeine-cache

- documentation/manual/about/PlayUserGroups.md
Delete playframework-ja from the list of user groups because their domain has been lost.
> Delete playframework-ja from the list of user groups

- documentation/manual/releases/release27/migration27/Migration27.md
n/a
tweak SBT version in the Migration Guide
n/a
n/a
> sbt version 1.2.8 in [Migration27.md]

- documentation/manual/releases/release27/migration27/Migration27.md
- framework/project/Dependencies.scala
latest version of Guava library
latest version of Guava library
n/a
n/a
> guava 27.0.1

- core/play-integration-test/src/it/scala/play/it/libs/JavaWSSpec.scala
- core/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
- project/Dependencies.scala
- project/plugins.sbt
https://akka.io/blog/news/2019/02/13/akka-2.5.21-released
https://github.com/sbt/sbt-native-packager/blob/master/CHANGELOG.md
https://github.com/sbt/sbt-native-packager/compare/v1.3.14...v1.3.18
> Update Akka and sbtNativePackager

- documentation/manual/working/javaGuide/main/ws/code/javaws.sbt
Java requires javaWs not ws.
Fixes #xxxx
> Java requires javaWs not ws

- documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Changed variable name so that the example makes sense.
Fixes #xxxx
> Changed variable name

- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
Added ArrayList to list of imports to example as it is required.
Fixes #xxxx
> Added ArrayList to imports

- build.sbt
- project/BuildSettings.scala
> Build cleanup

- build.sbt
- project/BuildSettings.scala
(cherry picked from commit fa9a183b38f32f6a4fc5ab9967d9794b0caf684f)
Backport of #9060
> [2.7.x] Build cleanup

- documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Added comment syntax to a comment so that it looks nicer in the manual. Without the syntax coloring.
Fixes #xxxx
> Added comment syntax to a comment

- documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
Added closing bracket that was missing after User.
Fixes #xxxx
> Form was missing a closing bracket after User

- core/play/src/main/java/play/mvc/Results.java
- core/play/src/main/java/play/mvc/StatusHeader.java
- scripts/validate-code
- web/play-java-forms/src/test/java/play/data/LoginUser.java
We already check Scala code formatting in our build. This adds the same for Java code.
> Add javafmt to travis build

- project/Dependencies.scala
https://netty.io/news/2019/03/08/4-1-34-Final.html
> Netty 4.1.34

- core/play/src/main/scala/play/api/mvc/Binders.scala
> Avoid bindableOption inferring an over-specific type

- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
Added package controllers to the template so that it works when someone copies and paste it.
Fixes #xxxx
> Added package controllers to the template

- core/play-logback/src/main/resources/logback-play-default.xml
Improves [docs](https://www.playframework.com/documentation/2.7.x/SettingsLogger) to consider the [linked blog post](https://blog.overops.com/how-to-instantly-improve-your-java-logging-with-7-logback-tweaks/).
> Tune the AsyncAppender following the overops blogpost on the link

- project/Dependencies.scala
Updates Play to use Akka-Http 10.1.8
> akka-http 10.1.8

- .mergify.yml
* backport rule should only run after merge
* remove backport labels
* adds WIP rule
> Mergify fixes

- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
As suggested by @ignasi35 in https://github.com/playframework/playframework/pull/8875#discussion_r243262520
> Synchronize evolutions code

- .travis.yml
The first one was wrongly generated using my fork instead of playframework/playframework.
> Update Slack secret configuration

- documentation/project/plugins.sbt
- project/plugins.sbt
To make it consistent with what is happening in #9140.
> Update sbt-header to version 5.2.0

- project/plugins.sbt
https://github.com/sbt/sbt-native-packager/blob/master/CHANGELOG.md#v1320-2019-03-29
> New sbt-native-packager release

- documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md
The example was missing helper, we could have either called helper.form or import helper. I decided to import helper since most of the other examples have this format.
Fixes #xxxx
> The example was missing helper

- .github/settings.yml
* Enable strict mode on PR status checks
* Only protect the master + maintenance branches
> Tweak branch protection settings

- build.sbt
- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/project/build.properties
- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/Docs.scala
- project/Release.scala
- project/Tasks.scala
- project/build.properties
- project/plugins.sbt
- scripts/test-docs
- scripts/test-sbt-plugins-0_13
- scripts/test-sbt-plugins-1_0
- scripts/test-scala-211
- scripts/test-scala-212
- scripts/validate-code
(cherry picked from commit 891ca6fbc253bb9866c0e7c59990f9674324912c)
(cherry picked from commit 2729a9c4927573339b43f5b230947eb8d31cea67)
Backport of #9001
> [2.6.x] Use sbt 1 to build Play itself (#9001)

- .github/settings.yml
Following the investigations in
https://github.com/probot/settings/issues/87 and the documentation in
https://github.com/probot/settings#usage to the latter.
> Fix pendantic settings probot's config

- project/Dependencies.scala
https://netty.io/news/2019/04/17/4-1-35-Final.html
> Netty 4.1.35

- project/Release.scala
Follow up to #9194.
See https://github.com/sbt/website/pull/757.
> Follow sbt 1 recommendation when integrating with sbt-release

- project/BuildSettings.scala
- project/Release.scala
Forward porting #9189, #9194 and #9200.
> [master]: forward port fixes to release process

- project/BuildSettings.scala
- project/Release.scala
Backports #9189, #9194 and #9200.
> [2.6.x]: backport fixes to release process

- core/play/src/main/scala/play/api/mvc/Cookie.scala
> Adds deprecation annotation to Cookiers companion object

- project/Docs.scala
> [2.7.x]: Fix relative paths to markdown files

- project/Docs.scala
> [master]: Fix relative paths to markdown files

- build.sbt
- core/play-streams/src/main/java/play/libs/streams/Accumulator.java
- core/play/src/main/java/play/core/j/MappedJavaHandlerComponents.java
- core/play/src/main/java/play/i18n/MessagesApi.java
- core/play/src/main/java/play/libs/Scala.java
- core/play/src/main/java/play/mvc/BodyParser.java
- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/java/play/mvc/MultipartFormatter.java
- core/play/src/main/scala/play/api/data/Form.scala
- core/play/src/main/scala/play/api/inject/BuiltinModule.scala
- core/play/src/main/scala/play/api/mvc/Request.scala
- core/play/src/main/scala/play/api/routing/sird/PathExtractor.scala
- core/play/src/main/scala/play/core/j/JavaParsers.scala
- core/play/src/test/java/play/mvc/RangeResultsTest.java
- core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
Slowly starting to select, cleanup and push all my local warning fixes and cleanups.  This is part 1 of ??.
> Fix or suppress some compilation warnings

- core/play/src/test/java/play/mvc/RangeResultsTest.java
> No need for Http.Context in RangeResultsTest anymore

- core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
- core/play/src/test/java/play/mvc/ResultsTest.java
- web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
- web/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
- web/play-java-forms/src/test/scala/play/data/FormSpec.scala
(not all done yet, will provide more pull requests)
> Remove Http.{Context, Response} from tests

- core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/core/j/JavaHelpers.scala
- documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaTracerController.java
- documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
- project/BuildSettings.scala
* [n/a] Have you added copyright headers to new files?
Fixes #xxxx
> Deprecate getQueryString, add queryString (fixes #9225)

- core/play-java/src/test/java/play/mvc/HttpTest.java
- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/core/j/JavaHelpers.scala
- project/BuildSettings.scala
See #9279: Same same but different
> Return Optional<Cookie> when retrieving cookie from JRequest

- core/play-java/src/test/java/play/mvc/HttpTest.java
- web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPActionSpec.scala
- web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
Another step towards Http.Context removal.
> Remove Http.Context from tests

- core/play/src/main/java/play/i18n/Lang.java
- web/play-java-forms/src/test/scala/play/data/FormSpec.scala
These methods depend on `Http.Context`...
> Don't use deprecated methods in play.data.FormSpec

- documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
- project/BuildSettings.scala
- web/play-java-forms/src/main/java/play/data/Form.java
- web/play-java-forms/src/main/java/play/data/validation/Constraints.java
It depends on `Http.Context`...
> Remove deprecated ValidationPayload.getArgs()

- core/play/src/main/java/play/routing/JavaScriptReverseRouter.java
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/controllers/Application.java
- project/BuildSettings.scala
> Make JavaScriptReverseRouter Http.Context free

- project/AkkaSnapshotRepositories.scala
Fixes playframework/play-meta#76.
> [2.7] Fix the akka-http snapshots repo

- core/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
- core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
- core/play-java/src/main/java/play/routing/RoutingDsl.java
- core/play-java/src/main/java/play/routing/RoutingDslComponents.java
- core/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
- core/play-java/src/main/scala/play/routing/RoutingDslModule.scala
- core/play/src/main/java/play/BuiltInComponents.java
- core/play/src/main/java/play/BuiltInComponentsFromContext.java
- core/play/src/main/java/play/components/HttpErrorHandlerComponents.java
- core/play/src/main/java/play/core/j/MappedJavaHandlerComponents.java
- core/play/src/main/scala/play/api/Application.scala
- core/play/src/main/scala/play/core/j/JavaAction.scala
- core/play/src/main/scala/play/core/j/JavaHelpers.scala
- core/play/src/main/scala/play/core/j/JavaHttpErrorHandlerAdapter.scala
- documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/FiltersTest.java
- documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/SimpleHttpRequestHandler.java
- project/BuildSettings.scala
- testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
- testkit/play-test/src/main/java/play/test/Helpers.java
- web/play-filters-helpers/src/main/java/play/filters/components/CSRFComponents.java
- web/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala
- web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFFilter.scala
- web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
- web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
> Deprecate JavaContextComponents

- core/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
- core/play/src/main/scala/play/core/j/JavaAction.scala
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/working/javaGuide/main/http/JavaContentNegotiation.md
This is a follow up to #9320.  See the conversation there.
> Fix some small details after removing Http.Context

- .mergify.yml
play/play piece of https://github.com/playframework/play-meta/issues/61
> Auto-merge Mergify's and ScalaSteward's PRs

- .mergify.yml
Due to https://github.com/Mergifyio/mergify-engine/issues/336
> Drop auto-merging Mergify backports

- CONTRIBUTING.md
- scripts/local-pr-validation.sh
Make it easier to fight the first tier of raid bosses.
>  Add new script to do basic validations locally 

- .mergify.yml
- .travis.yml
Reverts playframework/playframework#9376.
Thanks to @JustinPihony help!
> Revert "Remove strict behavior from Mergify"

- documentation/project/plugins.sbt
- project/plugins.sbt
> Bump plugins' versions

- build.sbt
- core/play/src/main/scala/views/helper/Helpers.scala
- project/BuildSettings.scala
This is a rewrite of https://github.com/playframework/playframework/pull/9412 for `master`.
> Prefer immutable seq's

- project/Dependencies.scala
Reverts playframework/playframework#9416
> Revert "Explicitly depend on netty-transport-native-unix-common"

- documentation/manual/gettingStarted/LearningExamples.md
- documentation/manual/tutorial/HelloWorldTutorial.md
I fixed broken tutorial url. 
Fixes #xxxx
> update tutorial url

- core/play/src/main/java/play/mvc/Results.java
- core/play/src/main/scala/play/api/mvc/Results.scala
- core/play/src/main/scala/play/core/j/JavaHelpers.scala
- core/play/src/test/java/play/mvc/ResultsTest.java
> overloaded the redirect method to support the query string parameters

- build.sbt
- project/Dependencies.scala
Currently from staging, as a smoke test for that release
> Update to Akka HTTP 10.1.9

- core/play/src/main/scala/play/api/mvc/Cookie.scala
Same same like #9464, but different.
> Add "None" to Same-site Cookie (Scala)

- core/play/src/main/scala/play/api/mvc/Cookie.scala
- core/play/src/test/scala/play/api/mvc/CookiesSpec.scala
Fix Cookie.SameSite#parse to accept SameSite.None value
https://web.dev/samesite-cookies-explained/
> fix Cookie.SameSite#parse to accept SameSite.None value

- documentation/manual/releases/release28/migration28/Migration28.md
https://github.com/playframework/playframework/pull/9494
https://github.com/akka/akka/blob/56f3a6b12661641c2ecb957114552e0b6407530e/akka-serialization-jackson/src/main/resources/reference.conf#L47-L58
```
akka.serialization.jackson {
serialization-features {
WRITE_DATES_AS_TIMESTAMPS = off
}
}
```
> Fix Copy & Paste typo

- core/play/src/main/scala/play/api/http/Writeable.scala
- core/play/src/main/scala/play/api/mvc/Binders.scala
- core/play/src/test/scala/play/api/http/WriteableSpec.scala
- core/play/src/test/scala/play/api/mvc/BindersSpec.scala
- web/play-openid/src/main/scala/play/api/libs/openid/OpenIdClient.scala
- web/play-openid/src/test/scala/play/api/libs/openid/OpenIDSpec.scala
> fix for UnEncoded key on key-value serialisation #9403.

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
So we can avoid having the instructions instead of valid information on the issues.
> Comment out template instructions

- project/BuildSettings.scala
came across this while troubleshooting community build stuff
> remove dead code in build

- project/BuildSettings.scala
Backport of https://github.com/lagom/lagom/pull/1698.
> Bump MaxMetaspaceSize for scripted tests

- core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
- core/play/src/main/java/play/mvc/StatusHeader.java
> Allow various sendXXX methods to set contentType

- build.sbt
- project/BuildSettings.scala
Empty scriptedDependencies for fast feedback loops & disable scripted
log buffering.
> Tweak scripted setup for speed and debugging

- core/play/src/main/java/play/mvc/StatusHeader.java
- core/play/src/test/java/play/mvc/ResultsTest.java
Same like #9564
- Move duplicate code to private method `attachOnClose`
- Add `onClose` to `sendInputStream` + add tests
> Add onClose callback to Java's sendInputStream

- .gitignore
- dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
- dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/build.sbt
Builds on #9575
Builds on #9576
Builds on #9577
Builds on #9578
> Trailing changes to the scripted test fixes

- core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
- core/play-integration-test/src/it/scala/play/it/http/ScalaResultsHandlingSpec.scala
- core/play/src/main/java/play/mvc/StatusHeader.java
- core/play/src/main/scala/play/api/mvc/Results.scala
- core/play/src/test/scala/play/mvc/StatusHeaderSpec.scala
- project/BuildSettings.scala
We do have these overloads for other methods already.
This is my last pull request related to these file serving methods.
> Overload file serving methods with inline and filename params

- core/play/src/main/scala/play/api/data/format/PlayDate.scala
- core/play/src/test/scala/play/api/data/format/PlayDateSpec.scala
Fixed date constraint on the form input so that seconds and nanoseconds are taken into account. Fixes #9495 .
> Fixed date constraint on the form input 

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/test
See the failure in
https://travis-ci.com/playframework/playframework/jobs/228442014.
> Give evolutions-auto-apply-true 4s to start

- documentation/manual/working/commonGuide/build/sbtSettings.md
> Fix broken link to sbt documentation

- documentation/manual/gettingStarted/PlayConsole.md
* [N/A] Have you added copyright headers to new files?
* [N/A ] Have you checked that both Scala and Java APIs are updated?
* [N/A] Have you updated the documentation for both Scala and Java sections?
* [N/A] Have you added tests for any changed functionality?
Simple grammar fix
Removes a typo
> fixed grammar on port settings description

- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/api/mvc/Cookie.scala
> [2.6.x] Backport of #9475 and #9464

- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/api/mvc/Cookie.scala
> [2.7.x] Backport of #9475 and #9464

- core/play/src/main/scala/play/api/mvc/Results.scala
This commit prevents an error which one encounters
when Redirect is called with a named parameter with only two args,
e.g. Redirect("foo", status = 301). The error in this case will be
'ambiguous reference to overloaded definition' because the named
parameter in both, the overloaded and the original method is equal. Users might find this
confusing and so I simply renamed one of the parameter names.
This commit also checks whether the status code is a valid redirect code
> Validate redirect codes and avoid ambiguous references

- documentation/project/plugins.sbt
One that scala-steward is not doing yet. :-)
> Update twirl version on documentation

- documentation/project/build.properties
- project/build.properties
This is is a proof-of-concept to validate #9416.
> [2.7] Update to sbt 1.3.0

- core/play-integration-test/src/it/scala/play/it/http/RequestHeadersSpec.scala
- documentation/manual/releases/release28/migration28/Migration28.md
- transport/server/play-akka-http-server/src/main/resources/reference.conf
- transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
- transport/server/play-netty-server/src/main/resources/reference.conf
- transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
- transport/server/play-server/src/main/resources/reference.conf
See https://github.com/playframework/playframework/pull/9625#discussion_r323692411
Based on #9625, waiting for its merge before unfreezing this one.
> Move max-header-size config to play.server

- core/play-java/src/main/java/play/libs/Time.java
- core/play/src/main/java/play/i18n/Langs.java
- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/java/play/mvc/StatusHeader.java
- documentation/project/build.properties
- project/Docs.scala
- project/build.properties
> Update to sbt 1.3.0

- documentation/build.sbt
- project/BuildSettings.scala
- project/Release.scala
- project/plugins.sbt
- scripts/it-test-scala-212
- scripts/it-test-scala-213
- scripts/test-docs-212
- scripts/test-docs-213
- scripts/test-scala-212
- scripts/test-scala-213
See https://github.com/lagom/lagom/pull/2261
> Following recommendations on https://github.com/xerial/sbt-sonatype/issues/89#issuecomment-529203859, this PR opts into using `sonatypeBundleRelease`.
> Prefer sonatypeBundleRelease

- .travis.yml
Because of https://github.com/shyiko/jabba/pull/537 `adopt@1.8.202-08` is not available anymore.
Also upgrade to latest jdk11.
> Update/change AdoptOpenJDK

- project/Dependencies.scala
- web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
Fixes #8900
A upstream fix was needed which I provided here: https://github.com/spring-projects/spring-framework/pull/21855
> Upgrade spring which fixes a bug in DynamicForm

- documentation/manual/working/javaGuide/main/tests/JavaFunctionalTest.md
- documentation/manual/working/javaGuide/main/tests/code/javaguide.tests.routes
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/FunctionalTest.java
- documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/controllers/HomeController.java
A small addition to functional testing controllers in Java.
> Document how to use reverse router to test controllers in Java

- .travis.yml
This a manual backport of https://github.com/playframework/playframework/pull/9688 on 2.6.x
> [2.6.x] Fix Jabba settings for AdoptOpenJDK

- .travis.yml
This a manual backport of https://github.com/playframework/playframework/pull/9688 on 2.7.x
> [2.7.x] Fix Jabba settings for AdoptOpenJDK

- core/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
- core/play/src/main/scala/play/core/formatters/Multipart.scala
- core/play/src/main/scala/play/core/parsers/Multipart.scala
- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- project/Dependencies.scala
- scripts/it-test-scala-212
- scripts/scriptLib
- scripts/test-docs-212
- scripts/test-scala-212
Related https://github.com/playframework/interplay/pull/93
> Scala 2.13.1 and 2.12.10

- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- project/AkkaSnapshotRepositories.scala
> Scripted tests use snapshot repositories on cron jobs

- scripts/scriptLib
Refs #9720
Note this introducs the change on travis' scripts but no source file 
needed formatting.
> Check all scalafmt for all scala versions

- documentation/manual/working/javaGuide/main/http/JavaRouting.md
- documentation/manual/working/javaGuide/main/http/code/javaguide.http.routing.routes
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaRouting.scala
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/routing/controllers/Api.java
- documentation/manual/working/scalaGuide/main/http/ScalaRouting.md
- documentation/manual/working/scalaGuide/main/http/code/ScalaRouting.scala
- documentation/manual/working/scalaGuide/main/http/code/scalaguide.http.routing.routes
Fixes #7788
Documents examples for using List[T] based query string parameters in routes.
> #7788 - Document usage of List in routes

- core/play/src/main/java/play/mvc/Http.java
- core/play/src/test/scala/play/mvc/RequestHeaderSpec.scala
- documentation/manual/releases/release28/migration28/Migration28.md
> Make Java's Headers immutable + RequestBuilder copy constructor

- documentation/manual/working/commonGuide/akka/AkkaTyped.md
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/AkkaTypedDocTest.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/AppModule.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/fp/AppComponents.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/fp/AppModule.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/fp/ConfiguredActor.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/fp/HelloActor.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/fp/Main.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/AppComponents.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/AppModule.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/ConfiguredActor.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/HelloActor.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/Main.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/multi/AppModule.java
- documentation/manual/working/commonGuide/akka/code/javaguide/akka/typed/oo/multi/Main.java
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/AkkaTypedDocSpec.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/AppComponents.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/HelloActor.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/multi/AppModule.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/fp/multi/Main.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/AppComponents.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/AppModule.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/ConfiguredActor.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/HelloActor.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/multi/AppModule.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/multi/Main.scala
See the individual commits for details (and PR review).  Highlights:
* Promote better practices in Akka Typed DI examples
* Caution users about using non-singleton Behavior's
* Add Akka Typed DI Java/FP-style examples
> Tweak the Akka Actor Typed docs

- project/Dependencies.scala
https://github.com/playframework/play-ws/pull/410
> [2.6.x]: Update play-ws to version 1.1.14

- documentation/project/build.properties
- documentation/project/plugins.sbt
- project/build.properties
- project/plugins.sbt
ScalaSteward only upgraded the documentation build's usage..
> Really upgrade to Twirl 1.5.0-M5

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http-http2/src/main/resources/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http-http2/src/test/scala/controllers/IntegrationTest.scala
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/test/scala/controllers/IntegrationTest.scala
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/resources/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/scala/controllers/IntegrationTest.scala
Thanks to #8028 netty server can now also set server header.
> Correct server-header tests

- core/play/src/main/scala/play/api/i18n/Messages.scala
- project/BuildSettings.scala
Removes Messages implicits deprecated since 2.6.0.
> Remove deprecated Messages implicits

- core/play-integration-test/src/it/scala/play/it/test/WSEndpointSpec.scala
- core/play-integration-test/src/it/scala/play/it/test/WSEndpointSupport.scala
- core/play/src/main/java/play/libs/typedmap/TypedKey.java
- project/BuildSettings.scala
- testkit/play-test/src/main/scala/play/api/test/TestServer.scala
Removes some deprecated Java methods from 2.6.x.
> Remove more deprecated methods

- core/play/src/main/scala/play/api/templates/Templates.scala
- core/play/src/main/scala/views/defaultpages/badRequest.scala.html
- core/play/src/main/scala/views/defaultpages/devError.scala.html
- core/play/src/main/scala/views/defaultpages/devNotFound.scala.html
- core/play/src/main/scala/views/defaultpages/error.scala.html
- core/play/src/main/scala/views/defaultpages/notFound.scala.html
- core/play/src/main/scala/views/defaultpages/todo.scala.html
- core/play/src/main/scala/views/defaultpages/unauthorized.scala.html
- core/play/src/main/scala/views/helper/Helpers.scala
- core/play/src/main/scala/views/helper/checkbox.scala.html
- core/play/src/main/scala/views/helper/defaultFieldConstructor.scala.html
- core/play/src/main/scala/views/helper/input.scala.html
- core/play/src/main/scala/views/helper/inputCheckboxGroup.scala.html
- core/play/src/main/scala/views/helper/inputRadioGroup.scala.html
- core/play/src/main/scala/views/helper/inputText.scala.html
- core/play/src/main/scala/views/helper/javascriptRouter.scala.html
- core/play/src/main/scala/views/helper/jsloader.scala.html
- core/play/src/main/scala/views/helper/select.scala.html
> Avoids deprecated Symbol literals

- core/play/src/main/scala/play/api/Configuration.scala
- core/play/src/test/scala/play/api/ConfigurationSpec.scala
- documentation/manual/working/commonGuide/configuration/ConfigFile.md
Expose Config's underlying getPeriod as a ConfigLoader[Period].
> Enable config.get[Period]

- web/play-java-forms/src/main/java/play/data/Form.java
- web/play-java-forms/src/test/java/play/data/Subtask.java
- web/play-java-forms/src/test/scala/play/data/FormSpec.scala
> Correctly direct-access default values of form fields

- core/play/src/test/scala/play/mvc/TextBodyParserSpec.scala
This does not change the tests really. The `body` is passed to `parse` explicitly later anyway. It's just cosmetics. (In theory, the `body` in the `request` is used to check for max-content-length, however that does not matter for these test).
`ByteString.toString()` just [gives you a description](https://github.com/akka/akka/blob/e479bb2a999ccfc9bd005febdeb94c4fc032fa60/akka-actor/src/main/scala-2.13%2B/akka/util/ByteString.scala#L742-L748) what the `ByteString` contains, not the actual stringified value (at least if the ByteString size is > 100).
> Don't use ByteString.toString() for request body

- core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala
- documentation/manual/working/commonGuide/build/code/dependencies.sbt
- documentation/manual/working/commonGuide/production/Deploying.md
- documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
- documentation/project/plugins.sbt
- project/Dependencies.scala
- project/Docs.scala
- project/plugins.sbt
- Play-JSON 2.8.0
- Play-WS 2.1.0
- Twirl 1.5.0
And others.
> Update play libraries to GA releases

- documentation/project/build.properties
- project/build.properties
- project/plugins.sbt
Built on top of #9828. 
This brings sbt 1.3.4 already.
> Update interplay to version 2.1.3

- project/plugins.sbt
> Update sbt-native-packager in 2.8.x

- cache/play-caffeine-cache/src/test/scala/play/api/cache/caffeine/CaffeineCacheApiSpec.scala
> CaffeineCacheApiSpec: Give expiration 100ms leeway

- .travis.yml
- documentation/manual/releases/release28/migration28/Migration28.md
- project/Dependencies.scala
- project/plugins.sbt
- scripts/test-scripted-13x
> [2.8.x]: interplay 2.1.4 and run scripted tests for sbt 1.3.x

- project/Dependencies.scala
- Akka 2.5.26
- Jackson Databind 2.8.11.4
- SLF4J 1.7.29
- Netty 4.1.43
- Reactive Streams 1.0.3
> [2.6.x]: Update multiple dependencies

- project/Dependencies.scala
> [2.8.x] Update mockito-core to 3.2.0

- documentation/manual/working/commonGuide/build/code/dependencies.sbt
- project/Dependencies.scala
Use Akka 2.6.1 and some other minor updates.
> [2.8.x]: Akka 2.6.1

- project/Dependencies.scala
> Bumps SSL Config

- project/Dependencies.scala
> [2.8.x]: Update play-ws and play-json

- dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
- documentation/README.md
Fixes #9903 
Related to #9904 
Targets `master` because we're not on a hurry to get it out.
> Remove play omnidoc from main plugin

- documentation/build.sbt
- documentation/manual/working/javaGuide/main/sql/index.toc
> Fix broken links and review the RDBMS section

- documentation/manual/releases/release28/migration28/Migration28.md
> Update latest sbt version (1.3.5)

- core/play/src/main/scala/play/api/mvc/Cookie.scala
> Undeprecate Cookies object - reverting #9215

- documentation/manual/working/javaGuide/main/http/JavaSessionFlash.md
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
- documentation/manual/working/scalaGuide/main/http/ScalaSessionFlash.md
- documentation/manual/working/scalaGuide/main/http/code/ScalaSessionFlash.scala
[doc] Add info on redirects with session
> [2.8] [doc] Add info on redirects with session

- documentation/manual/working/javaGuide/main/akka/JavaAkka.md
> Update JavaAkka.md to add missing word

- documentation/manual/tutorial/ImplementingHelloWorld.md
- documentation/manual/tutorial/code/javaguide/hello/HelloController.java
- documentation/manual/tutorial/code/javaguide/hello/hello.scala.html
- documentation/manual/tutorial/code/javaguide/hello/helloName.scala.html
- documentation/manual/tutorial/code/javaguide/hello/index.scala.html
- documentation/manual/tutorial/code/javaguide/hello/main.scala.html
- documentation/manual/tutorial/code/scalaguide/hello/HelloController.scala
Implements `option 2.` from https://github.com/playframework/playframework/issues/9942#issuecomment-572522407
The Java and the Scala starter samples are out of sync so the tutorial only made sense for the Java implementation.
Fixes #9942 
Related to https://github.com/playframework/play-samples/pull/83
> Update code on tutorial pages

- core/play/src/main/scala/play/api/Configuration.scala
- core/play/src/test/scala/play/api/ConfigurationSpec.scala
Fixes lagom/lagom#2643.
This is a follow up to #9978.
> Read config.file/config.resource from devSettings and sys properties

- documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
- documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
- documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/nested.scala.html
- documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/select.scala.html
I have previously signed the CLA.
(I am not a Java developer so have just created this PR for the Scala guide ONLY.)
Add an extra nested element to the documentation to clearly show how multiple nested values are defined, specifically for how to correctly use apply() / unapply().
Add Clarity for multiple nested form elements.
Issue #9976
> Docs Improvement : Forms, nested values #9976

- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- documentation/project/build.properties
- project/BuildSettings.scala
- project/Dependencies.scala
- project/build.properties
With the upgrade of play-file-watch this...
Fixes #9999
> [2.8] Prep for 2.8.1 release

- documentation/manual/Home.md
- documentation/manual/LatestRelease.md
- documentation/manual/releases/index.toc
- documentation/manual/releases/release29/Highlights29.md
- documentation/manual/releases/release29/index.toc
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/releases/release29/migration29/index.toc
2.9 I guess? I need those pages to document stuff :wink:
> Introducing: Next Play version

- documentation/project/build.properties
- project/build.properties
> Update sbt to 1.3.8

- web/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
Fixes https://github.com/playframework/playframework/issues/10040
Adds `withThreshold` to `GzipFilterConfig` to make it accessible in Java.
N/A
N/A
> Add withThreshold and withCompressionLevel to GzipFilterConfig

- documentation/manual/working/scalaGuide/main/application/ScalaApplication.md
- documentation/manual/working/scalaGuide/main/application/ScalaHttpRequestHandlers.md
`GlobalSettings` does not exist anymore.
> Remove references to GlobalSettings in docs

- project/Dependencies.scala
> Upgrade play-file-watch to 1.1.12

- documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
This pull request fixes a broken link.
> Fix broken link

- documentation/manual/working/commonGuide/production/HTTPServer.md
Minimize the example for nginx and link to official docs for full configuration.
> Review documentation for front end HTTP servers

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/project/plugins.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/test
> Add dianostics for #10047

- scripts/test-scripted
> Show cache before running scripted tests

- core/play/src/main/java/play/BuiltInComponentsFromContext.java
- core/play/src/main/scala/play/api/Application.scala
- core/play/src/main/scala/play/api/http/HttpRequestHandler.scala
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/controllers/UsersController.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/startup/Startup.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/startup/StartupModule.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/views/index.scala.html
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/changes/2.sql
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/changes/3.sql
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/conf/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/conf/evolutions/default/1.sql
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/test
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/controllers/UsersController.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/startup/Startup.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/startup/StartupModule.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/views/index.scala.html
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/changes/2.sql
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/conf/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/conf/evolutions/default/1.sql
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/test
- documentation/manual/working/scalaGuide/main/application/code/ScalaHttpRequestHandlers.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- transport/client/play-ahc-ws/src/test/scala/play/libs/ws/WSSpec.scala
> [2.8.x] Remove autoApply handling from EvolutionsWebCommands (DEV mode)

- core/play/src/main/java/play/http/DefaultHttpErrorHandler.java
Replaces scaladoc syntax with javadoc syntax.
> Fix javadoc

- documentation/manual/working/javaGuide/main/forms/JavaCsrf.md
- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
Fixes https://github.com/playframework/playframework/issues/9187
Update CSRF documentation to clarify
>To allow simple protection for non browser requests, Play only checks requests with cookies in the header.
which should check `Cookie` or `Authorization` by default
> update CSRF documentation

- documentation/manual/working/commonGuide/filters/CspFilter.md
Update documentation in response to https://github.com/playframework/playframework/pull/8242#pullrequestreview-387359926
> [doc] Add report-only section in CspFilter.md

- documentation/manual/tutorial/ImplementingHelloWorld.md
- documentation/manual/tutorial/code/javaguide/hello/HelloController.java
- documentation/manual/tutorial/code/javaguide/hello/hello.scala.html
- documentation/manual/tutorial/code/javaguide/hello/helloName.scala.html
- documentation/manual/tutorial/code/javaguide/hello/index.scala.html
- documentation/manual/tutorial/code/javaguide/hello/main.scala.html
Fixes https://github.com/playframework/playframework/issues/10176
> Remove asset finder from helloWorld

- transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
Fixes https://github.com/playframework/playframework/issues/10072
change uri parse path error from warn to debug
> change uri parse path error from warn to debug

- core/play/src/main/scala/play/api/templates/Templates.scala
- core/play/src/test/scala/play/api/templates/TemplatesSpec.scala
> translate() method should handle arrays

- documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
Upgrading to latest guice beta in #10202, which removes cglib, discloses a problem which @jroper did fix for another class already, [see comment](https://github.com/playframework/playframework/pull/8398#issue-186504370):
> There's a JDK bug that causes `Class.getSimpleName` and other methods like `Class.isAnonymousClass` that depend on it to throw an exception when called on doubly nested Scala classes (https://github.com/scala/bug/issues/2034). This is fixed in JDK9, but in the meantime, any DI framework that checks if a class is anonymous will fail for any such classes. `TemporaryFileReaperConfigurationProvider` is one such class, so I've moved it up a level (keeping the old one for binary compatibility and deprecating it).
The specific JDK bug, which got fixed in JDK9, is …
> Unnested Scala classes to workaround JDK-8 bug

- core/play-streams/src/main/scala/play/api/libs/streams/Execution.scala
- core/play/src/main/scala/play/core/Execution.scala
- project/BuildSettings.scala
`trampoline` is definitely not Play's default execution context.
> Remove outdated code and comments

- core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala
- project/BuildSettings.scala
- project/Dependencies.scala
- testkit/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
See https://webtide.com/jetty-alpn-java-8u252/
> jetty-alpn-agent 2.0.10 and akka-http 10.1.12

- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- project/Dependencies.scala
- scripts/it-test-scala-212
- scripts/test-docs-212
- scripts/test-scala-212
- scripts/test-scripted-13x
Related https://github.com/playframework/interplay/pull/116
> Scala 2.13.2 / 2.12.11 & sbt 1.3.10

- documentation/manual/working/commonGuide/database/Evolutions.md
- persistence/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java
- persistence/play-jdbc-evolutions/src/main/resources/reference.conf
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsHelper.scala
- persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala
- persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsHelperSpec.scala
- persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsSpec.scala
- project/BuildSettings.scala
> Support custom name of play_evolutions(_lock) table

- core/play-integration-test/src/it/scala/play/it/http/ScalaResultsSpec.scala
- core/play-java/src/test/java/play/mvc/ResultAttributesTest.java
- core/play/src/main/java/play/mvc/Result.java
- core/play/src/main/scala/play/api/mvc/Results.scala
- core/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
- core/play/src/test/scala/play/api/mvc/ResultsSpec.scala
- project/BuildSettings.scala
Fixes #10172
Covers both Scala and Java Result.
> Add Result attributes

- core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala
- project/Dependencies.scala
- testkit/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
Same like #10274 but for 2.7.x
akka upgrade to 2.5.31 as well.
> [2.7.x] jetty-alpn-agent 2.0.10, akka-http 10.1.12 and akka 2.5.31

- cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineParser.java
- cache/play-caffeine-cache/src/main/resources/reference.conf
See https://github.com/playframework/playframework/pull/10224#issuecomment-628885245
/cc @wsargent
> Caffeine's internal executor should use Play's default dispatcher

- project/plugins.sbt
> [2.7.x] Bump interplay 2.1.5

- project/plugins.sbt
> [2.8.x] Bumps interplay 2.1.5

- project/Dependencies.scala
> [2.8.x] Minor dependency updates

- project/Dependencies.scala
> [2.8.x] Update caffeine, jcache to 2.8.4

- documentation/manual/gettingStarted/NewApplication.md
Fixes #10303
To avoid getting started error, this PR adds the "navigate to the top level project directory" text.
The same wording is used at https://www.playframework.com/getting-started.
> docs(newapp tutorial): updated instruction

- .travis.yml
> Cache jabba script itself as well

- core/play/src/main/resources/reference.conf
See:
https://github.com/playframework/playframework/blob/649758cb68ead0dcc0aac747dc11081d8ae19feb/core/play/src/main/scala/play/api/libs/Files.scala#L348
> play.akka.blockingIoDispatcher is correct

- transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
> AkkaHttpServer: prevent access to not yet initialized fields

- scripts/publish-local
- scripts/scriptLib
> Cache Akka versions in directory that is part of the travis workspace

- scripts/scriptLib
> [2.8.x] Use only 10.1.x snapshots of akka-http

- core/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationLoaderSpec.scala
- core/play/src/main/scala/play/api/inject/BuiltinModule.scala
- core/play/src/main/scala/play/api/libs/concurrent/Akka.scala
This will help integration with other libraries moving from clasic to typed (e.g. https://github.com/playframework/play-grpc/pull/264/commits/d5a2065e2d31143c2fa22612dde52706c7866789#r453717880 )
> Adds ClassActorSystemProvider in the DI

- project/Dependencies.scala
Did that manually, mergify [had some conflicts](https://github.com/playframework/playframework/pull/10386#issuecomment-659479299).
> [2.8.x] Update akka-actor, ... to 2.6.8

- core/play-streams/src/main/scala/play/api/libs/streams/GzipFlow.scala
- web/play-filters-helpers/src/main/resources/reference.conf
> Fix gzip buffering

- core/play-integration-test/src/it/scala/play/it/libs/json/JavaJsonSpec.scala
- core/play/src/main/scala/play/utils/JsonNodeDeserializer.scala
> Jackson raw value regression (#10505)

- .mergify.yml
Inspired by https://github.com/playframework/playframework/pulls?q=is%3Apr+is%3Aclosed
> Remove `status:merge-when-green` label after merge

- build.sbt
- project/Tasks.scala
refs https://github.com/playframework/play-grpc/issues/303
> Adds akkaHttpVersion on PlayVersion

- documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
Fixes duplicated line in code for testSyncUpload in JavaFileUpload documentation.
https://www.playframework.com/documentation/2.8.x/JavaFileUpload#Testing-the-file-upload
> Fix duplicated code line in docs of JavaFileUpload

- build.sbt
- project/BillOfMaterialsPlugin.scala
see also https://github.com/akka/akka/pull/29839
> PoC BOM for Play

- persistence/play-jdbc-api/src/main/java/play/db/ConnectionCallable.java
- persistence/play-jdbc-api/src/main/java/play/db/ConnectionRunnable.java
- persistence/play-jdbc-api/src/main/java/play/db/DBApi.java
- persistence/play-jdbc-api/src/main/java/play/db/Database.java
Hi!
It's my first PR in your project. I tried to follow your guide lines. Your help will be appreciate.  I signed Lightbend CLA
The PR fixes #10552 
Kind regards
> Remove unnecessary modifiers from interfaces in play-jdbc-api

- core/play/src/test/java/play/mvc/RangeResultsTest.java
- core/play/src/test/java/play/mvc/ResultsTest.java
> Fix parameter order for assertEquals in core/play

- project/Dependencies.scala
Scala Steward won't update these, see #10412
> Upgrade akka and akka-http

- core/play-java/src/test/java/play/mvc/HttpTest.java
- core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
- core/play/src/main/java/play/mvc/Security.java
- core/play/src/test/java/play/mvc/ResultsTest.java
- web/play-java-forms/src/test/scala/play/data/FormSpec.scala
> Replace using deprecated methods of static classes from Http.java

- core/play/src/test/java/play/core/PathsTest.java
- core/play/src/test/java/play/mvc/CallTest.java
> Remove unnecessary exceptions from signature in tests from core/play

- persistence/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
- persistence/play-java-jdbc/src/test/java/play/db/NamedDatabaseTest.java
- persistence/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
- testkit/play-test/src/test/java/play/test/HelpersTest.java
- testkit/play-test/src/test/java/play/test/WithApplicationOverrideTest.java
- testkit/play-test/src/test/java/play/test/WithBrowserTest.java
> Replace deprecated JUnit-matchers on Hamcrest-matchers in play-java-jdbc, play-java-jpa, play-test

- core/play-integration-test/src/it/java/play/it/http/RepeatableBackwardCompatibilityController.java
- core/play/src/main/java/play/Application.java
- core/play/src/main/java/play/ApplicationLoader.java
- core/play/src/main/java/play/core/cookie/encoding/ServerCookieDecoder.java
- core/play/src/main/java/play/core/cookie/encoding/ServerCookieEncoder.java
- core/play/src/main/java/play/i18n/Messages.java
- core/play/src/main/java/play/inject/SourceProvider.java
- core/play/src/main/java/play/libs/XML.java
- core/play/src/main/java/play/mvc/PathBindable.java
- dev-mode/build-link/src/main/java/play/TemplateImports.java
- dev-mode/build-link/src/main/java/play/core/Build.java
- dev-mode/build-link/src/main/java/play/core/BuildDocHandler.java
- dev-mode/run-support/src/main/java/play/runsupport/classloader/DelegatingClassLoader.java
- persistence/play-java-jdbc/src/main/java/play/db/DBModule.java
- persistence/play-java-jdbc/src/main/java/play/db/Databases.java
- persistence/play-java-jdbc/src/main/java/play/db/DefaultDBApi.java
- persistence/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
- persistence/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java
- testkit/play-specs2/src/main/scala/play/api/test/PlaySpecification.scala
- testkit/play-test/src/main/java/play/test/TestBrowser.java
- transport/client/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSComponents.java
- web/play-java-forms/src/main/java/play/data/format/FormattersModule.java
> Remove unused impports, use diamond operator, remove unnecessary modifier public from methods of interfaces

- core/play-guice/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
- core/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java
- core/play-guice/src/test/java/play/inject/guice/GuiceInjectorBuilderTest.java
- core/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
- core/play-integration-test/src/it/java/play/routing/AbstractRoutingDslTest.java
- core/play/src/test/java/play/libs/concurrent/FuturesTest.java
- core/play/src/test/java/play/mvc/CookieBuilderTest.java
- persistence/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
> * Replace deprecated ExceptedException.none() on assertThrows and other fixes for tests

- core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/api/mvc/Request.scala
- core/play/src/test/scala/play/mvc/RawBodyParserSpec.scala
- project/BuildSettings.scala
> Remove using deprecated constructor Http.RequestImpl

- core/play-integration-test/src/it/scala/play/it/http/AkkaResponseHeaderHandlingSpec.scala
- core/play-integration-test/src/it/scala/play/it/http/HttpHeadersCommonSpec.scala
- dev-mode/routes-compiler/src/test/scala/play/routes/compiler/RoutesFileParserSpec.scala
- transport/server/play-netty-server/src/test/scala/play/core/server/netty/NettyHeadersWrapperSpec.scala
- web/play-openid/src/test/scala/play/api/libs/openid/DiscoveryClientSpec.scala
- web/play-openid/src/test/scala/play/api/libs/openid/OpenIDSpec.scala
> Replace "must_== Some()" on "must beSome()" in specs2-tests

- cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheManager.scala
> Refactor CaffeineCacheManager

- transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
> Refactor AhcWSSpec

- core/play/src/main/java/play/core/Paths.java
- core/play/src/test/java/play/core/PathsTest.java
- core/play/src/test/java/play/mvc/CallTest.java
> Rename tests in PathsTest and CallTest from play/core

- cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheManager.scala
- cache/play-caffeine-cache/src/test/scala/play/api/cache/caffeine/CaffeineCacheApiSpec.scala
Fixes #10612 
Return names of available caches
#10612
> Caffeine Cache Manager - Expose cache names

- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/api/controllers/Assets.scala
There are some unclosed files in DefaultAssetsMetadata.
History https://github.com/playframework/playframework/pull/10596#discussion_r551134491
Kind regards
> Close digest-files in DefaultAssetsMetadata

- core/play/src/main/scala/play/api/Configuration.scala
- core/play/src/main/scala/play/api/mvc/BodyParsers.scala
- dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
There are some unused private methods in these classes. It can be removed.
Kind regards
> Remove unused methods from play.api.Configuration and play.runsupport.Reloader

- core/play/src/main/scala/play/api/libs/Files.scala
Fixes one of the memory leak issues reported in #9935
Took the fix from the gist in https://github.com/playframework/playframework/issues/9935#issuecomment-585495107
#9935
> fix DefaultTemporaryFileCreator leak

- persistence/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
- transport/server/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaServerConfigReaderTest.scala
- web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
- web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPReportSpec.scala
Some small changes for tests
Kind regards
> Fix minor warning in tests

- dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
The methods are not used anymore since long time...
> Remove very old methods from routes generator

- web/play-java-forms/src/main/java/play/data/Form.java
- web/play-java-forms/src/test/scala/play/data/FormSpec.scala
> Java forms: Prefix a ValidationError's key with parent form field key

- dev-mode/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayReload.scala
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/app/controllers/HomeController.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt.1
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/common-fail.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/conf/routes
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/controller-fail.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/build.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/src/main/scala/Bar.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/modules/sub-project-inside/src/main/scala/Foo.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/project/plugins.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-inside-fail.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-outside-fail.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/test
- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
Backport of #10648 (only slightly modified to make it work for 2.8.x)
> [2.8.x] Support sbt 1.4 virtual files when displaying error source

- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- project/Dependencies.scala
Also see please merge
https://github.com/playframework/interplay/pull/146
and
https://github.com/playframework/interplay/pull/147
> Scala 2.12.13 and 2.13.5

- core/play/src/main/java/play/package-info.java
- core/play/src/main/scala/play/utils/Resources.scala
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/plugins.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/test
- web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
Things I ran into while compiling / testing with latest OpenJDK 16 release candidate.
> Improve compatibility with JDKs > 11

- core/play/src/main/scala/play/api/mvc/Cookie.scala
Looking at the PR in #10726 again, there is an improvement I missed.
> No need to build a JwtParser each time

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/conf/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/expected-application-log.txt
- documentation/manual/working/commonGuide/build/code/dependencies.sbt
- documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
- documentation/project/plugins.sbt
- project/Dependencies.scala
- project/plugins.sbt
- transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
> [2.8.x] Upgrade dependencies before releasing Play 2.8.8

- .scala-steward.conf
- project/Dependencies.scala
refs https://github.com/playframework/play-json/pull/588
> Bump Jackson to 2.11.x

- project/BuildSettings.scala
- project/Release.scala
- project/plugins.sbt
> Sunset bintray 2.1.x

- core/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
Seems like this was wrongly added in #7961 an nobody noticed:
https://github.com/playframework/playframework/pull/7961/files#diff-7b3611db38a57f67e7c09f74fff300acbbc49eb3a4a5692b711156b732db4b30R44
> Also run netty http 1.1 microbenchmark encrypted

- .scala-steward.conf
> Update scalasteward settings

- build.sbt
- project/BuildSettings.scala
- project/Docs.scala
- project/Tasks.scala
followed https://twitter.com/eed3si9n/status/1378811237929213955
The result introduced a couple of issues and _tried to_ rewrite a couple more that I had to revert.
> Used scalafix for a first cleanup of sbt deprecated syntax

- documentation/manual/working/scalaGuide/main/forms/ScalaCsrf.md
> Updated link to OWASP recommended to familiarize with CSRF

- documentation/manual/releases/release29/Highlights29.md
- documentation/manual/working/commonGuide/database/Evolutions.md
- persistence/play-jdbc-evolutions/src/main/java/play/db/evolutions/Evolutions.java
- persistence/play-jdbc-evolutions/src/main/resources/reference.conf
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsHelper.scala
- persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala
- persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsHelperSpec.scala
- persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsSpec.scala
- project/BuildSettings.scala
(Updated) Screenshot from the release highlights page:
---
> Support for variable substitution in evolutions scripts

- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- documentation/manual/working/commonGuide/build/sbtSubProjects.md
- project/AkkaSnapshotRepositories.scala
- scripts/scriptLib
See https://github.com/akka/akka-http/pull/3792
> Remove bintray leftovers (fixes CRON build)

- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- documentation/manual/working/commonGuide/build/sbtSubProjects.md
- project/AkkaSnapshotRepositories.scala
- scripts/scriptLib
> [2.8.x] Remove bintray leftovers (fixes CRON build)

- core/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationLoader.scala
- core/play-guice/src/test/scala/play/core/test/Fakes.scala
- core/play-guice/src/test/scala/play/utils/ReflectSpec.scala
- core/play/src/main/scala/play/api/controllers/Assets.scala
- core/play/src/main/scala/play/api/libs/Comet.scala
- core/play/src/main/scala/play/core/formatters/Multipart.scala
- core/play/src/main/scala/play/utils/OrderPreserving.scala
- testkit/play-test/src/main/scala/play/api/test/Helpers.scala
- web/play-filters-helpers/src/test/scala/play/filters/csp/CSPFilterSpec.scala
- web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPActionSpec.scala
- web/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala
- web/play-java-forms/src/test/scala/play/data/FormSpec.scala
> fix Auto-application warnings

- core/play/src/main/scala/controllers/Execution.scala
- core/play/src/main/scala/play/api/Logger.scala
- core/play/src/main/scala/play/api/http/MediaRange.scala
- core/play/src/main/scala/play/api/mvc/Binders.scala
- core/play/src/main/scala/play/api/mvc/Results.scala
- core/play/src/main/scala/play/core/Execution.scala
- core/play/src/main/scala/play/core/routing/ReverseRouteContext.scala
- testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
- testkit/play-test/src/main/scala/play/api/test/Helpers.scala
- transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
prepare Scala 3
implicit values type annotations require in Scala 3
> add explicit type annotations for public implicit val and def

- core/play/src/main/scala/play/api/controllers/Assets.scala
- core/play/src/main/scala/play/api/mvc/Binders.scala
- core/play/src/main/scala/play/api/mvc/Cookie.scala
prepare Scala 3
implicit values type annotations require in Scala 3
> add explicit type annotations for implicit val and def

- .travis.yml
Yeah, it doesn't harm, but occupying 3 workers is not great either.
> Stop testing 0.13

- documentation/manual/gettingStarted/LearningExamples.md
> fix: change project starter link

- .travis.yml
These Travis notifications are not actively watched anyway. Let's remove them.
> Travis: remove explicit notifications

- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
Fixes #10864
Use `System.in` in the interaction mode input stream wrapper rather than `FileDescriptor.in`.
As @eed3si9n suggested on the ticket, we essentially want to do what jline already does in [this commit](https://github.com/sbt/jline2/commit/6821546aaeea30df2615fb5d3b4a34b78812da65), for similar reasons.
Also fixes https://github.com/sbt/sbt/issues/6515.
> Fix IOException when using sbt thin client

- project/Dependencies.scala
exactly as per https://github.com/playframework/playframework/pull/10874
however this one targets 2.8 branch
> bump guava dependency to fix vulnerability

- documentation/manual/working/commonGuide/filters/AllowedHostsFilter.md
I used this feature in a project and I through that the doc had a mistake that needed to be fixed since it was extremely confusing to me
> Clarified the allowedhost blacklist usage in documentation

- README.md
Button from here: https://docs.opencollective.com/help/collectives/widgets
> Add Sponsors & Backers and financial contributors badge to README

- .github/release-drafter-2.8.x.yml
- .github/release-drafter-master.yml
- README.md
* Added premium sponsors
* Remove mention of Lightbend's sponsorship
Preview of the part that changed:
> Update release drafts

- dev-mode/run-support/src/main/scala/play/runsupport/Colors.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/Colors.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
Backport of #11070 but without checking for Java 17
> [2.8.x] Add onLoadMessage

- documentation/manual/releases/release26/migration26/Migration26.md
> Documented the change from ValidationError to JsonValidationError in Migration-2.6

- project/Dependencies.scala
> play-ws 2.1.7

- README.md
> Update travis-ci status badge

- README.md
Link goes to the [rules channel](https://discord.com/channels/931647755942776882/932596128988405790)
> Replace gitter with discord

- core/play/src/main/scala/play/api/controllers/Assets.scala
- core/play/src/main/scala/play/utils/Resources.scala
- core/play/src/test/scala/play/utils/ResourcesSpec.scala
> Adding support for checking URL with protocol='bundleresource' existence

- build.sbt
- project/BuildSettings.scala
use `enablePlugins(MimaPlugin)` instead of `mimaDefaultSettings`
https://app.travis-ci.com/github/playframework/playframework/jobs/556754629#L450
```
[warn] /home/travis/build/playframework/playframework/project/BuildSettings.scala:193:5: method mimaDefaultSettings in object MimaPlugin is deprecated (since 0.7.0): Switch to enablePlugins(MimaPlugin)
[warn]     mimaDefaultSettings,
[warn]     ^
```
> fix warning in build file

- .mergify.yml
- .travis.yml
- CONTRIBUTING.md
- core/play/src/main/scala/play/api/mvc/RangeResult.scala
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/hacking/ThirdPartyTools.md
- documentation/manual/hacking/Translations.md
- documentation/manual/hacking/WorkingWithGit.md
- documentation/manual/releases/release24/migration24/Migration24.md
- documentation/manual/releases/release26/migration26/Migration26.md
- documentation/manual/working/commonGuide/configuration/ConfigFile.md
- documentation/manual/working/commonGuide/filters/CspFilter.md
- documentation/manual/working/commonGuide/production/ProductionConfiguration.md
- documentation/manual/working/commonGuide/production/cloud/Deploying-CleverCloud.md
- documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
- documentation/manual/working/scalaGuide/main/forms/ScalaForms.md
- project/Dependencies.scala
> [2.8.x] Rename master branch to main

- documentation/manual/working/commonGuide/database/AccessingAnSQLDatabase.md
JDNI renamed to correct abbreviation JNDI (Java Naming and Directory Interface)
> JDNI renamed to correct abbreviation JNDI (Java Naming and Directory Interface)

- .mergify.yml
> Let's see if we can add author to backport titles

- .mergify.yml
See https://github.com/playframework/play-meta/issues/216
> Mergify: Add [{{ destination_branch }}]

- documentation/manual/working/commonGuide/assets/AssetsSass.md
Out of date docs.
Due to migrating sbt-sassify to Sonatype OSS, I had to change the groupId of the sbt-sassify plugin.
Hence I wanted to update the documentation on the the play website as well. 
https://github.com/irundaia/sbt-sassify/pull/49
https://github.com/irundaia/sbt-sassify/issues/48
> Update AssetsSass.md to reflect a groupId change

- project/Dependencies.scala
* [X ] Have you read [How to write the perfect pull request](https://github.com/blog/1943-how-to-write-the-perfect-pull-request)?
* [X ] Have you added copyright headers to new files?
* [ X] Have you added tests for any changed functionality?
Fixes #10962
Update dependencies jquery to 3.6.0 version
> Update jquery dependency to 3.6.0 version

- documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
Fixes #10937
@Mergifyio backport main
> Doc fix: Body needs to be redirected with `POST`

- documentation/manual/tutorial/HelloWorldTutorial.md
> typing error

- scripts/it-test
- scripts/local-pr-validation.sh
- scripts/publish-local
- scripts/scriptLib
- scripts/test
- scripts/test-docs
- scripts/test-scripted
`scripts/local-pr-validation.sh` was actually broken so I fixed it and also made all the other scripts more user friendly, right now they are just optimized for Travis.
> Make scripts more userfriendly if running outside of CI

- README.md
@ProChirathF @prosasankad :+1:
> Add Pronto Software as premium sponsor

- .github/workflows/build-test.yml
Should have been in #11256 already. Sorry.
> Forgot to append unique id to Java 11 publish job

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- .github/workflows/trigger-cache-invalidation.yml
> Bump version of sharable workflows to `v2`

- .scala-steward.conf
See https://github.com/scala-steward-org/scala-steward/blob/6f2da8b067f38d96e0c00769a83d05705f4ca82f/docs/repo-specific-configuration.md?plain=1#L83-L86
> scala steward should also visit documentation folder

- core/play-integration-test/src/it/scala/play/it/http/websocket/WebSocketClient.scala
- core/play/src/main/scala/play/api/http/AcceptEncoding.scala
- core/play/src/main/scala/play/api/mvc/Filters.scala
- core/play/src/main/scala/play/api/mvc/Handler.scala
- core/play/src/main/scala/play/api/mvc/WebSocket.scala
- core/play/src/main/scala/views/helper/Helpers.scala
use SAM conversion if possible
> use "SAM conversion"

- .github/workflows/build-test.yml
- dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesFileParser.scala
- project/Dependencies.scala
fix some compile error and build settings for Scala 3.
- https://github.com/playframework/playframework/issues/11260
> add routes-compiler Scala 3 build setting

- cache/play-ehcache/src/test/scala/play/api/cache/CachedSpec.scala
- core/play-integration-test/src/it/scala/play/it/http/AkkaHttpCustomServerProviderSpec.scala
- core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
- core/play/src/main/scala/play/api/data/validation/Validation.scala
- core/play/src/main/scala/play/api/libs/crypto/CSRFTokenSigner.scala
- core/play/src/main/scala/play/core/j/JavaHelpers.scala
- core/play/src/main/scala/play/utils/Reflect.scala
- core/play/src/test/scala/play/api/libs/TemporaryFileReaperSpec.scala
- core/play/src/test/scala/play/api/mvc/DefaultBodyParserSpec.scala
- core/play/src/test/scala/play/api/mvc/MaxLengthBodyParserSpec.scala
- core/play/src/test/scala/play/api/mvc/TextBodyParserSpec.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsModule.scala
- persistence/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
- persistence/play-jdbc/src/test/scala/play/api/db/NamedDatabaseSpec.scala
- web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
> fix warnings

- cache/play-caffeine-cache/src/test/java/play/cache/caffeine/NamedCaffeineCacheSpec.java
- core/play-exceptions/src/main/java/play/api/PlayException.java
- core/play-integration-test/src/it/java/play/it/http/websocket/WebSocketSpecJavaActions.java
- core/play/src/main/java/play/libs/F.java
- core/play/src/main/java/play/libs/reflect/ClassUtils.java
- core/play/src/main/java/play/libs/typedmap/TypedKey.java
- core/play/src/test/scala/play/data/AnotherUser.java
- persistence/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAConfig.java
- web/play-java-forms/src/main/java/play/data/Form.java
- web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java
use diamond operator in java files if possible.
> use diamond operator

- web/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
> remove unused code in AddCSRFTokenAction.java

- core/play/src/test/scala/play/api/mvc/MultipartBodyParserSpec.scala
- core/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
- core/play/src/test/scala/play/api/mvc/ResultsSpec.scala
- documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
- documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
- testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
- testkit/play-test/src/test/scala/play/api/test/HelpersSpec.scala
- transport/server/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala
fix compile errors with Scala 3.
- https://github.com/playframework/playframework/issues/11260
> add explicit types for implicits. prepare Scala 3

- web/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
> Update branch in message (RedirectHttpsFilter)

- .github/workflows/build-test.yml
Fixes #xxxx
Adapt build test CI for Scala 3. Change to have one line per module
Make CI script easier to read and update
Prepare for Scala 3 support #11260
> Scala 3 build test

- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/AgeRange.scala
- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/CartItem.scala
- documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala
- documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
- web/play-openid/src/test/scala/play/api/libs/openid/package.scala
add explicit types. prepare Scala 3
> add explicit type for implicits

- core/play/src/main/scala/play/api/mvc/Filters.scala
- core/play/src/main/scala/play/core/j/JavaParsers.scala
- testkit/play-specs2/src/test/scala/play/api/test/FakesSpec.scala
- testkit/play-test/src/main/scala/play/api/test/Helpers.scala
- testkit/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala
- web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
> remove unused type parameters

- .github/workflows/trigger-cache-invalidation.yml
See https://github.com/playframework/.github/pull/31
> Remove workaround to trigger cache invalidation

- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
None (Small Doc edit)
Fixes some minor ambigioutiy on the ScalaWS help page.
None
> link to ScalaCompileTimeDI doc from the DI section of the ScalaWS help

- .github/PULL_REQUEST_TEMPLATE.md
This PR removes the CLA language from the PR template's checklist.
> Removing CLA from the PR template.

- .github/workflows/build-test.yml
- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- project/Dependencies.scala
> [2.8.x] Upgrade to Scala 2.12.17 and 2.13.9

- core/play-integration-test/src/it/scala/play/it/http/HttpPipeliningSpec.scala
- core/play-java/src/main/java/play/libs/XPath.java
- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- project/AkkaSnapshotRepositories.scala
- project/BuildSettings.scala
fix warnings
- https://github.com/sbt/librarymanagement/blob/8b016c7555f98163fdc072b550c1d71136c3db6b/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L158-L161
- https://github.com/scala/scala/blob/8c6b49b95d99b6bfd585271b21b2704a4ac314e9/src/library/scala/util/Either.scala#L171-L172
> fix some warnings

- cache/play-caffeine-cache/src/main/java/play/cache/caffeine/NamedCaffeineCache.java
- project/Dependencies.scala
Added some adjustments to https://github.com/playframework/playframework/pull/10764 for Caffeine
> Update caffeine, jcache to 3.0.1

- project/Dependencies.scala
Because of https://github.com/playframework/play-doc/pull/155
> play-doc 2.2.0-M1

- .github/workflows/build-test.yml
- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- project/Dependencies.scala
- project/plugins.sbt
But not 2.12.17 on this branch because of scala-xml.
> [2.8.x] Latest scala sbt versions

- project/Dependencies.scala
Contains https://github.com/playframework/netty-reactive-streams/pull/161
> [2.8.x] Upgrade netty-reactive-streams

- core/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
- core/play/src/main/scala/play/api/http/HttpErrorHandler.scala
- transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala
When taking another look at #10711 it bothered me that we had to add a special case for the Guice provision errors and use reflection to get the cause.
My goal here is to make it possible for modules to plug in their own error handling logic, so they can specify how to unwrap their own exceptions, rather than doing that in the `play` module. So in this case, `play-guice` should register a handler for provision errors before it wires up the dependencies.
> Move Guice error handling logic to play-guice module

- documentation/manual/ModuleDirectory.md
> Removed unmaintained "Play! Authenticate" module from module directory in documentation

- project/Dependencies.scala
> [2.8.x] Upgrade Akka, Netty, Spring, Joda-Time

- core/play/src/main/scala/play/api/mvc/Results.scala
The example code does not follow the parameter class changes in Results#discardingCookies.
This PR provides example code for the latest class.
> Fix the example code to DiscardingCookie for Results#discardingCookies

- persistence/play-jdbc/src/main/resources/reference.conf
- persistence/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
- persistence/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala
Expose a new hikari option - use case is the AWS JDBC wrapper driver - https://github.com/awslabs/aws-advanced-jdbc-wrapper/blob/main/docs/using-the-jdbc-driver/using-plugins/UsingTheFailoverPlugin.md#connection-pooling
> Add exceptionOverrideClassName Hikari config setting

- core/play-integration-test/src/it/scala/play/it/http/websocket/WebSocketSpec.scala
- documentation/build.sbt
- documentation/project/CrossJava.scala
- project/Dependencies.scala
This is the last PR that makes it into 2.8.19, so I am also running all tests to see if everything is good.
> [2.8.x] Upgrade netty + netty reactive streams + fix backports

- persistence/play-jdbc-api/src/main/java/play/db/TransactionIsolationLevel.java
- persistence/play-jdbc-api/src/main/scala/play/api/db/TransactionIsolationLevel.scala
- project/BuildSettings.scala
> fix typo. Commited => Committed

- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
Fixes #11654
See https://regex101.com/r/TiHvLR/1
> Support MariaDB jdbc con. string for Evolutions tables

- core/play-logback/src/main/scala/play/api/libs/logback/ColoredLevel.scala
- documentation/manual/releases/release29/migration29/Migration29.md
Migration guide:
<kbd><img width="700" src="https://user-images.githubusercontent.com/644927/217304809-7908e870-9370-43ab-9dba-6d1ffd19b199.png" /></kbd>
> Deprecate %coloredLevel Logback pattern

- documentation/manual/gettingStarted/Anatomy.md
Added the `.bsp` directory to the typical `.gitignore` file.
> Added .bsp to the typical .gitignore file

- project/plugins.sbt
https://github.com/lampepfl/dotty/releases/tag/3.3.0-RC3
> Interplay 3.1.0-RC8, comes with Scala 3.3.0-RC3

- documentation/project/plugins.sbt
- project/plugins.sbt
https://github.com/playframework/twirl/releases/tag/1.6.0-RC2
> Twirl 1.6.0-RC2 (needed for Scala 3)

- .github/ISSUE_TEMPLATE.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/PULL_REQUEST_TEMPLATE.md
> Fix some links

- .github/workflows/build-test.yml
- core/play/src/main/scala/play/core/parsers/Multipart.scala
- documentation/build.sbt
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaErrorHandling.scala
- documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala
- documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaNettyEmbeddingPlay.scala
- documentation/manual/working/scalaGuide/main/http/code/ScalaErrorHandling.scala
- project/BuildSettings.scala
- project/plugins.sbt
Hopefully the final piece.
Should make Scala 3 compile and publish on CI, and run all the tests on it.
> Activate Scala 3 on CI

- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
- persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
Fixes #11744 (caused by the fix #11655)
> Fix MysqlJdbcUrl regex matching

- project/BuildSettings.scala
- web/play-filters-helpers/src/main/scala/play/api/test/CSRFTokenHelper.scala
> use implicit value class if possible

- .github/workflows/build-test.yml
- documentation/manual/hacking/Translations.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/project/build.properties
- project/build.properties
- project/plugins.sbt
Running tests to catch problems early.
https://github.com/sbt/sbt/releases/tag/v1.9.0-RC1
> sbt 1.9.0-RC1

- .github/workflows/build-test.yml
- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
While going over #11673 I saw that the workflow files in the 2.8.x branch need a bit of an update, nothing spectacular.
> [2.8.x] Sync GHA workflows with main branch

- documentation/manual/gettingStarted/code/ide.sbt
- documentation/project/plugins.sbt
* https://github.com/sbt/sbt-eclipse/releases/tag/6.0.0
* https://github.com/scala-steward-org/scala-steward/pull/3049
> Upgrade sbt-eclipse in docs + change groupId

- documentation/manual/tutorial/ImplementingHelloWorld.md
- documentation/manual/tutorial/code/javaguide/hello/HelloController.java
- documentation/manual/tutorial/code/javaguide/hello/hello.scala.html
- documentation/manual/tutorial/code/javaguide/hello/helloName.scala.html
- documentation/manual/tutorial/code/javaguide/hello/index.scala.html
- documentation/manual/tutorial/code/javaguide/hello/main.scala.html
> [2.8.x] Remove asset finder from helloWorld

- project/Dependencies.scala
* https://github.com/google/guice/discussions/1742
* https://github.com/google/guice/wiki/Guice600
> Guice 6 final release

- .github/workflows/build-test.yml
- documentation/manual/hacking/Translations.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/project/build.properties
- project/build.properties
Missed that in the previous PR
> sbt 1.9.0-RC3

- documentation/manual/working/commonGuide/configuration/SettingsLogger.md
This PR replaces a dead link in the "Configuring logging" documentation page and makes some minor improvements.
The original URL redirects to another domain which no longer hosts the blog post.
> Fixed dead link

- project/Dependencies.scala
Replaces #11822 - not sure why but GitHub actions not kicking in
> guava 32.0.0-jre (was 31.1-jre)

- documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/classfield/BaseController.java
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/classfield/Counter.java
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/classfield/LiveCounter.java
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/classfield/NoopCounter.java
- documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/guice/classfield/SubclassController.java
- documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md
- documentation/manual/working/scalaGuide/main/dependencyinjection/code/RuntimeDependencyInjection.scala
Adds one more dependency injection case in documentation
> Add class field dependency injection example doc

- documentation/manual/working/commonGuide/build/sbtSubProjects.md
- documentation/manual/working/commonGuide/database/code/database.sbt
update to latest version
note: `groupId` and `artifactId` changed
- https://blogs.oracle.com/mysql/post/mysql-connectorj-has-new-maven-coordinates
- https://repo1.maven.org/maven2/com/mysql/mysql-connector-j/8.0.33/
- https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.33/mysql-connector-java-8.0.33.pom
- https://github.com/mysql/mysql-connector-j/commit/02b704c0bc4080506b80792a6a4eb4b316cd4f05#diff-118e71f89ee4e84ed88d35d5af39e1cebdc0eeb61a29c862f9815761397f1482R42
- https://github.com/mysql/mysql-connector-j/blob/fa4912a849140828e48162a2c396c8df0091bed7/src/build/misc/pom-relocation.xml#L42
> Update mysql client version in doc

- README.md
https://nulab.com/
Replaces Iterable.
> Add Nulab as premium sponsor

- documentation/build.sbt
- project/plugins.sbt
* https://github.com/lampepfl/dotty/releases/tag/3.3.1-RC4
* https://github.com/lampepfl/dotty/releases/tag/3.3.1-RC5
* https://github.com/playframework/interplay/compare/3.1.1...3.1.2
I know I know we should get rid of interplay at some point
> Let's see if Scala 3.3.1-RC5 works well

- core/play/src/main/scala/play/api/mvc/Request.scala
- core/play/src/test/scala/play/api/mvc/RequestSpec.scala
Avoids `play.api.http.HttpErrorHandlerExceptions$$anon$1: Execution exception[[ClassCastException: play.api.mvc.AnyContentAsEmpty$ cannot be cast to play.mvc.Http$RequestBody]]`
Fixes #9789
> Scala `request.asJava` should correctly handle none JRequestBody's

- core/play/src/main/java/play/mvc/BodyParser.java
- core/play/src/main/java/play/mvc/Http.java
- core/play/src/main/scala/play/api/mvc/BodyParsers.scala
- core/play/src/main/scala/play/core/j/JavaParsers.scala
- project/BuildSettings.scala
Yes, that's needed for another bugfix.
> Added `isEmpty` method to MultipartFormData

- project/Dependencies.scala
Ran scala-steward locally, I will cut M7 to test things in play-samples before RC1
> caffeine 3.1.8

- core/play/src/main/scala/play/api/mvc/Request.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
- documentation/manual/General.md
- documentation/manual/Home.md
- documentation/manual/gettingStarted/Installing.md
- documentation/manual/gettingStarted/Requirements.md
- documentation/manual/index.toc
- documentation/manual/releases/release29/Highlights29.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/releases/release29/migration29/Scala3Migration.md
- documentation/manual/releases/release29/migration29/index.toc
- documentation/manual/working/javaGuide/main/akka/JavaAkka.md
- documentation/manual/working/javaGuide/main/async/JavaWebSockets.md
- documentation/manual/working/javaGuide/main/http/JavaActionsComposition.md
- documentation/manual/working/javaGuide/main/http/JavaBodyParsers.md
- documentation/manual/working/javaGuide/main/sql/JavaJPA.md
- documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
- web/play-filters-helpers/src/main/resources/reference.conf
No need to review yet, ~I want to finish this tomorrow...~ (haha good joke back then)
Fixes #11649 (I had a look at _all_ pull requests since 2.8.0 to see what is noteworthy and what needs to be mentioned in the migration guide)
> Play 2.9 highlights and migration guide

- core/play-integration-test/src/test/scala/play/it/http/JavaActionSpec.scala
- core/play/src/main/scala/play/core/j/JavaAction.scala
> Fix `UnsupportedOperationException` because of `.asScala()` call on `MinimalStage`

- documentation/manual/releases/release29/migration29/Migration29.md
> Mention RC3 in migration guide

- .github/mergify.yml
- .github/workflows/build-test.yml
- .github/workflows/delete-caches.yml
The continuation of this discussion https://github.com/playframework/playframework/pull/11997#discussion_r1342810330
> Rollback publishing an artifacts are builded by Java 17 in nightly checks

- .gitattributes
It seems to be a leftover of this change set https://github.com/playframework/playframework/pull/11982
> Fix path in .gitattributes

- build.sbt
- project/BuildSettings.scala
- project/Docs.scala
- project/Omnidoc.scala
- project/PlayBuildBase.scala
- project/PlayLibraryBase.scala
- project/PlayNoPublishBase.scala
- project/PlayRootProjectBase.scala
- project/PlaySbtBuildBase.scala
- project/PlaySbtLibraryBase.scala
- project/PlaySbtPluginBase.scala
- project/PlaySonatypeBase.scala
- project/Playdoc.scala
- project/Versions.scala
- project/plugins.sbt
As part of https://github.com/playframework/interplay/issues/150
> Copy interplay into main repository

- README.md
https://www.sprypoint.com/
Official announcement follows.
> Add SpryPoint as premium sponsor

- .github/workflows/delete-caches.yml
Needs to ignore result code of `grep` command.
> Fix errors if `play-published-local-*` cache entries not found

- core/play-configuration/src/main/scala/play/api/Configuration.scala
- core/play/src/test/scala/play/api/LoggerConfiguratorSpec.scala
- documentation/manual/releases/release26/migration26/JavaConfigMigration26.md
- documentation/manual/releases/release26/migration26/Migration26.md
- documentation/manual/working/commonGuide/configuration/ConfigFile.md
- documentation/manual/working/commonGuide/production/ProductionConfiguration.md
- documentation/manual/working/javaGuide/main/config/JavaConfig.md
- documentation/manual/working/scalaGuide/main/config/ScalaConfig.md
> `typesafehub/config` => `lightbend/config`

- documentation/build.sbt
- documentation/manual/working/commonGuide/build/code/dependencies.sbt
- documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
- project/Dependencies.scala
* https://github.com/playframework/playframework/pull/12038 (most important one)
* https://github.com/playframework/playframework/pull/12040
* https://github.com/playframework/playframework/pull/12037/
* https://github.com/playframework/playframework/pull/12036
* https://github.com/playframework/playframework/pull/12035
> [2.9.x] Dependency updates

- documentation/manual/General.md
- documentation/manual/Home.md
- documentation/manual/LatestRelease.md
- documentation/manual/about/Philosophy.md
- documentation/manual/index.toc
- documentation/manual/releases/Scala3Migration.md
- documentation/manual/releases/index.toc
- documentation/manual/releases/release29/Highlights29.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/releases/release30/Highlights30.md
- documentation/manual/releases/release30/index.toc
- documentation/manual/releases/release30/migration30/Migration30.md
- documentation/manual/releases/release30/migration30/index.toc
I will add a couple of lines tomorrow, not much needed, mostly refering to
* the 2.9 pages and 
* https://pekko.apache.org/docs/pekko/current/project/migration-guides.html
* https://pekko.apache.org/docs/pekko-http/current/migration-guide/index.html
> Play 3 highlights + migration guide + docs adjustments

- .github/scala-steward.conf
I think it will be useful for us.
> Add tag `[2.9.x]` for Steward's pull requests for 2.9.x branch

- documentation/manual/working/commonGuide/production/Deploying.md
> Update sbt-assembly version in doc

- documentation/manual/gettingStarted/LearningExamples.md
- documentation/manual/tutorial/HelloWorldTutorial.md
- documentation/manual/tutorial/Tutorials.md
- documentation/manual/working/commonGuide/server/PekkoHttpServer.md
- documentation/manual/working/javaGuide/main/async/JavaComet.md
- documentation/manual/working/scalaGuide/main/async/ScalaComet.md
use `3.0.x` branch instead of `2.9.x`
> Update play-samples url

- documentation/manual/working/scalaGuide/main/http/ScalaBodyParsers.md
- documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
> [2.9.x] Update play-json scaladoc url

- dev-mode/play-docs-sbt-plugin/src/main/scala/org/playframework/docs/sbtplugin/PlayDocsValidation.scala
- dev-mode/play-docs/src/main/scala/play/docs/DocumentationHandler.scala
- project/Dependencies.scala
Needed for
* #12162
Depends on
* https://github.com/playframework/play-doc/pull/222
> Make docs handle svg files

- documentation/manual/Home.md
- documentation/manual/gettingStarted/NewApplication.md
- documentation/manual/releases/release29/Highlights29.md
- Make Play 3.0 and Play 2.9 more obvious on first sight
- Document `sbt new` and the `--branch` switch when creating a new project
> Docs enhancements

- documentation/manual/releases/release29/Highlights29.md
- documentation/manual/releases/release30/Highlights30.md
- documentation/manual/releases/release30/migration30/Migration30.md
Proposed changes to the 3.0 announcement pages.
> Minor changes to 3.0 notes

- documentation/manual/releases/release29/Highlights29.md
> [2.9.x] Small wording change in 2.9 Highlights

- dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/ConfiguredActor.scala
- documentation/manual/working/commonGuide/akka/code/scalaguide/akka/typed/oo/HelloActor.scala
- documentation/manual/working/commonGuide/configuration/code/CustomAkkaHttpServer.scala
- documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaRouting.scala
- documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaAkkaEmbeddingPlay.scala
- documentation/manual/working/scalaGuide/advanced/embedding/code/ScalaNettyEmbeddingPlay.scala
- documentation/manual/working/scalaGuide/advanced/extending/code/ScalaExtendingPlay.scala
- documentation/manual/working/scalaGuide/main/application/code/EssentialFilter.scala
- documentation/manual/working/scalaGuide/main/application/code/ScalaHttpFilters.scala
- documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
- documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala
- documentation/manual/working/scalaGuide/main/dependencyinjection/code/RuntimeDependencyInjection.scala
- documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
- documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
- documentation/manual/working/scalaGuide/main/tests/code/tests/guice/Component.scala
> [2.8.x] Better Scala 2.13.12 compatibility

- project/Dependencies.scala
Eventually fixes
- #12187
This is not enough:
- #12189
> Upgrade sbt-web to really fix #12187

- project/Dependencies.scala
Eventually fixes
- #12187
This is not enough:
- #12189
> [2.9.x] Upgrade sbt-web to really fix #12187

- documentation/manual/ModuleDirectory.md
Only supports scala 3.
Add the Hepek library for generating boilerplate HTML.  
It is really handy for rapid prototyping, adds HTML validation automatically etc.
> Add hepek components

- documentation/manual/about/Philosophy.md
> Fix link to Zengularity

- documentation/manual/working/commonGuide/build/sbtDependencies.md
- https://github.com/sbt/sbt/issues/7484
> Be more generic about repos (avoid repo.typesafe.com)

- project/Dependencies.scala
> pekko-http 1.0.1

- transport/server/play-pekko-http-server/src/main/resources/reference.conf
Cause more harm than good
- Fixes #12351
> Disable HTTP pipelining

- dev-mode/play-docs-sbt-plugin/src/main/scala/org/playframework/docs/sbtplugin/PlayDocsPlugin.scala
- dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala
- dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala
- dev-mode/play-routes-compiler/src/main/twirl/play/routes/compiler/static/javaWrappers.scala.twirl
- dev-mode/play-routes-compiler/src/test/scala/play/routes/compiler/RoutesCompilerSpec.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
Fixes #12262
Add option to disable JavaScript routers
> Add option to disable JavaScript routers

- documentation/project/plugins.sbt
- project/plugins.sbt
Brings better support for Scala 3.4.0
> [2.9.x] Twirl 1.6.5

- documentation/project/plugins.sbt
- project/plugins.sbt
Brings better support for Scala 3.4.0
> Twirl 2.0.4

- .github/scala-steward.conf
- .github/workflows/build-test.yml
- .github/workflows/dependency-graph.yml
- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
`3.0.x` should not break things and is for patch releases and very minor features only.
> [3.0.x] Introduce 3.0.x branch

- README.md
We did the same other branches.
> [3.0.x] Cleanup README

- documentation/manual/ModuleDirectory.md
Update the Silhouette website location as project has migrated to within playframework github organisation.
N/A documentation fix only.
n/a/ documenation fix
Minor documentation correction only.
> Update ModuleDirectory.md - Update Silhouette location

- documentation/build.sbt
- documentation/manual/releases/Scala3Migration.md
- documentation/manual/releases/release29/migration29/Migration29.md
- project/Versions.scala
- https://github.com/lampepfl/dotty/issues/19820
- #12441
- #12442
> [2.9.x] Scala 3.3.3

- documentation/build.sbt
- documentation/manual/releases/Scala3Migration.md
- documentation/manual/releases/release29/migration29/Migration29.md
- project/Versions.scala
- https://github.com/lampepfl/dotty/issues/19820
- #12441
- #12443
> [3.0.x] Scala 3.3.3

- documentation/build.sbt
- documentation/manual/releases/Scala3Migration.md
- documentation/manual/releases/release29/migration29/Migration29.md
- project/Versions.scala
- https://github.com/lampepfl/dotty/issues/19820
- #12442
- #12443
> Scala 3.3.3

- .github/dependabot.yml
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> Dependabot should upgrade GitHub actions workflows

- documentation/manual/tutorial/Tutorials.md
See https://github.com/playframework/play-samples/pull/571#issuecomment-1977477019 for details
> [2.9.x] [Docs] Link to example should download sources archive

- documentation/manual/tutorial/Tutorials.md
See https://github.com/playframework/play-samples/pull/571#issuecomment-1977477019 for details
> [3.0.x] [Docs] Link to example should download sources archive

- core/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala
- core/play/src/main/scala/play/api/mvc/RangeResult.scala
- documentation/manual/releases/release30/migration30/Migration30.md
- documentation/project/CrossJava.scala
- project/Dependencies.scala
* https://lists.apache.org/thread/grl5h0l79oywnjtmfv0mdg3w108vsh6o
* https://lists.apache.org/thread/4l6zflfpg0q5d2sll2xp7nmd1qyksy2v
* https://github.com/apache/pekko/pull/1214
* https://github.com/apache/pekko-http/pull/520
> Apache Pekko now a Top Level Project

- core/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala
> [2.9.x] Apache Pekko now a Top Level Project

- documentation/manual/ModuleDirectory.md
I added links to the documentation and demo pages for my project Kuzminki.
* [x ] Have you read [How to write the perfect pull request](https://github.blog/2015-01-21-how-to-write-the-perfect-pull-request/)?
* [ x] Have you read through the [contributor guidelines](https://www.playframework.com/contributing)?
* [x ] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [ x] Have you added copyright headers to new files?
* [ x] Have you checked that both Scala and Java APIs are updated?
* [x ] Have you updated the documentation for both Scala and Java sections?
* [x ] Have you added tests for any changed functionality?
Fixes #xxxx
Why did you …
> Kuzminki added to ModuleDirectory.md

- core/play/src/main/scala/play/api/mvc/Action.scala
(https://github.com/playframework/playframework/issues/12362)
> Typo fix in Action.scala

- documentation/manual/releases/Scala3Migration.md
Add a section to the documentation linking to #12272 (InjectedController breaking due to Scala 3 guice issue)
> Add reference to InjectedController bug to Scala3Migration docs

- .github/workflows/dependency-graph.yml
Our [dependency graph](https://github.com/playframework/playframework/network/dependencies) haven't updated from 28 Feb [action#8084271424](https://github.com/playframework/playframework/actions/runs/8084271424/) 😞 
Checked in [action#8847974604](https://github.com/playframework/playframework/actions/runs/8847974604)
> Fix Sbt Dependency Graph submission

- dev-mode/gradle-plugin/build.gradle.kts
- dev-mode/gradle-plugin/gradle/libs.versions.toml
- dev-mode/gradle-plugin/src/test/java/play/gradle/PlayPluginTest.java
- dev-mode/gradle-plugin/src/test/java/play/gradle/PlayRoutesPluginTest.java
- dev-mode/gradle-plugin/src/test/java/play/gradle/PlayRunPluginTest.java
As preparation for https://github.com/playframework/playframework/pull/12531
> Add a few unit tests for Gradle plugin

- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/plugins.sbt
https://github.com/playframework/twirl/releases/tag/1.6.6
> [2.9.x] Twirl 1.6.6

- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/plugins.sbt
https://github.com/playframework/twirl/releases/tag/2.0.5
> [3.0.x] Twirl 2.0.5

- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/plugins.sbt
https://github.com/playframework/twirl/releases/tag/2.0.5
> Twirl 2.0.5

- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/working/commonGuide/production/ConfiguringHttps.md
> Document flag to use self-signed certificates in DEV and when staging

- project/Dependencies.scala
https://github.com/playframework/play-json/releases/tag/2.10.5
> [2.9.x] play-json 2.10.5

- project/Dependencies.scala
https://github.com/playframework/play-json/releases/tag/3.0.3
> [3.0.x] play-json 3.0.3

- project/Dependencies.scala
https://github.com/playframework/play-json/releases/tag/3.0.3
> play-json 3.0.3

- documentation/manual/releases/release26/migration26/Migration26.md
- documentation/manual/releases/release27/migration27/Migration27.md
- documentation/manual/working/javaGuide/main/forms/JavaForms.md
- Bad: https://www.playframework.com/documentation/3.0.x/JavaForms#advanced-validation
- Good: https://www.playframework.com/documentation/3.0.x/JavaForms#Advanced-validation
> Fix a link in the docs

- .github/scala-steward.conf
It's the last month anyway, but still...
Done for
- #12613
- #12614
- #12615
- #12616
> [2.8.x] Pin more deps in scala steward config

- .github/workflows/build-test.yml
- documentation/project/build.properties
- project/PlaySbtBuildBase.scala
- project/Versions.scala
- project/build.properties
https://github.com/sbt/sbt/releases/tag/v1.10.0
> sbt 1.10.0

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/app/controllers/HomeController.java
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/build.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/conf/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/conf/logback.xml
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/conf/routes
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/project/plugins.sbt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/test
Tests both:
- https://github.com/playframework/playframework/pull/12474
- https://github.com/playframework/playframework/pull/12624
> [3.0.x] Add scripted test to check jjwt compatibility

- build.sbt
- core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
Try fix ci builds
The `SLF4JBrigerHandler` will modify the `LoggerContext` concurrently in `shutdown` and `configure` method.
> Try fix log reconfigure error

- .gitignore
> Add `.sdkmanrc` to `.gitignore`

- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/test
- project/Dependencies.scala
- Fixes #5242
Had to introduce a new sbt `AttributeKey` which we can attach to the sbt `state`:
- https://github.com/sbt/sbt-web/pull/248
- https://github.com/sbt/sbt-web/pull/250
> Fix multiple asset pipeline runs in DEV mode

- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/plugins.sbt
> [2.9.x] Twirl 1.6.7

- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/plugins.sbt
- 2.9.x: #12760
- #12761
/cc @colin-lamed
> [3.0.x] Twirl 2.0.6

- documentation/project/plugins.sbt
- project/BuildSettings.scala
- project/plugins.sbt
> Twirl 2.0.6

- README.md
> Update README: Twitter -> X

- project/Dependencies.scala
https://lists.apache.org/thread/g8w0507lotpy6zck0492yn1mc2p1nqyw
> Pekko 1.0.3

- project/Dependencies.scala
https://github.com/jwtk/jjwt/releases/tag/0.12.6
> jjwt 0.12.6

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/build.sbt
> [3.0.x] jjwt 0.12.6 (for testing only)

- core/play/src/main/scala/play/core/parsers/Multipart.scala
- web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
Backport changes from https://github.com/playframework/playframework/pull/12794
> [3.0.x] Backport Pekko 1.1.0-M1 explicit supervision strategy setting

- dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayRunPlugin.java
\+ fix the problem in DEV mode (`playRun`) with configurations are (`reference.conf`) stored in submodules
> [Gradle] Support Kotlin modules

- dev-mode/gradle-plugin/build.gradle.kts
- dev-mode/gradle-plugin/gradle/libs.versions.toml
- dev-mode/gradle-plugin/src/test/java/play/gradle/PlayRunPluginTest.java
Thank a lot @antohaby for inspire a way do this check that I didn't find in original #12821
> [Gradle] Add test for Kotlin submodules case

- documentation/manual/releases/release26/Highlights26.md
- documentation/manual/releases/release27/Highlights27.md
- project/Versions.scala
- https://github.com/scala/scala/releases/tag/v2.12.20
> Scala 2.12.20

- project/Dependencies.scala
https://github.com/google/guava/releases/tag/v33.3.0
> Guava 33.3.0

- project/Dependencies.scala
https://netty.io/news/2024/09/04/4-1-113-Final.html
> Netty 4.1.113

- .github/scala-steward.conf
> [3.0.x] Pin Pekko [HTTP] to 1.0.x

- .github/workflows/build-test.yml
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT-sans-externalized.scala3.jar.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT.scala3.jar.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-sub.asset-changes-sub-1.0-SNAPSHOT.scala3.jar.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/expected-assets-pipeline.assets-pipeline-0.1.0-SNAPSHOT-sans-externalized.scala3.jar.txt
- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/Scala3Migration.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- documentation/project/build.properties
- project/Versions.scala
- project/build.properties
- https://github.com/scala/scala/releases/tag/v2.13.15
- https://www.scala-lang.org/news/3.3.4
- https://github.com/scala/scala3/releases/tag/3.3.4
- https://eed3si9n.com/sbt-1.10.2
- https://github.com/sbt/sbt/releases/tag/v1.10.2
> Upgrade scala (2.13 + 3.3) and sbt

- .github/scala-steward.conf
> [2.9.x] Scala Steward: Pin joda-time

- dev-mode/gradle-plugin/src/main/java/play/gradle/internal/RoutesCompileAction.java
If routes file has an errors
**Expected:**
compilation task should be failed and print information in log
**Actual:**
compilation task is "green" and log is empty. Scala files haven't generated of course 😞
> [Gradle] Failed routes compilation should fail gradle task

- project/Dependencies.scala
https://netty.io/news/2024/11/12/4-1-115-Final.html
> [3.0.x] Netty 4.1.115.Final

- project/Dependencies.scala
https://github.com/playframework/play-ws/releases/tag/3.0.6
> [3.0.x] play-ws 3.0.6

- README.md
https://www.depop.com/ :partying_face: 
- Same story as in https://github.com/playframework/.github/pull/90
> Add Depop as premium sponsor

- .github/workflows/build-test.yml
- documentation/project/build.properties
- project/Versions.scala
- project/build.properties
https://github.com/sbt/sbt/releases/tag/v1.10.6
> sbt 1.10.6

- core/play-microbenchmark/src/test/scala/play/core/server/netty/NettyHelpers.scala
> Fix Microbenchmark tests to make it work with upcoming Scala releases

- documentation/build.sbt
- documentation/manual/hacking/BuildingFromSource.md
- documentation/manual/releases/release27/Highlights27.md
- documentation/manual/releases/release28/migration28/Migration28.md
- documentation/manual/releases/release29/migration29/Migration29.md
- documentation/manual/working/commonGuide/build/sbtDependencies.md
- project/Versions.scala
https://github.com/scala/scala/releases/tag/v2.13.16
> Scala 2.13.16

- .scalafmt.conf
- documentation/.scalafmt.conf
> Prepare scalafmt upgrade

- project/BuildSettings.scala
> [2.9.x] Fix `apiMappings`

- dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
Code is not used anymore since 63c473ffa9e731d215b1bff4a22d4976aa971051
> Remove dead code

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-sub.asset-changes-sub-1.0-SNAPSHOT.scala3.jar.txt
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/expected-assets-pipeline.assets-pipeline-0.1.0-SNAPSHOT-sans-externalized.scala3.jar.txt
- project/Versions.scala
https://github.com/scala/scala3/releases/tag/3.3.5
> Scala 3.3.5

- documentation/manual/working/javaGuide/main/async/JavaWebSockets.md
- documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
I caught this just passing by during other work 🧑‍💻
Still following _"The Boy Scout Rule (©Uncle Bob)"_ 🖖
> Add example and fix doc for asynchronous accepting `WebSocket`

- core/play/src/main/scala/play/api/libs/Files.scala
Fixes #13013 
Do not try to delete the temporary folder during shutdown if it was never created in the 1st place. Because when trying to delete, it actually tries to create the folder if it was not already created. This is useless and can cause errors with read-only filesystems.
I used a simple mutable `var` as I believe this is enough in this context: the `var` is private, in a singleton, only set during a `lazy val` initialization.
However, if you believe we should use an `AtomicBoolean`, just say it :)
Note that I didn't add test, not sure if this is worth it and I'm not sure how to approach writing such a test.
N/A
> Avoid error at shutdown if tmpdir is not writeable but was not used in the first place

- transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala
> Update link on how to fix slow localhost resolution

- documentation/manual/working/scalaGuide/main/forms/ScalaCustomFieldConstructors.md
Fixes https://github.com/playframework/playframework/issues/5172
Updates the Custom Field Constructor documentation to be more clear. Provides suggested filenames and directories so that a beginner can get started with creating custom field constructors.
If anything is still not clear, or we need further edits, let me know. I'm happy to make them.
Outstanding issue with the documentation since October 2015. I created a minimal ("Hello Play") sample project with a minimal custom field constructor  to verify the approach. 
https://github.com/playframework/playframework/issues/5172
> Updates Custom Field Constructor Documentation

- documentation/manual/working/commonGuide/assets/AssetsOverview.md
Resolves https://github.com/playframework/playframework/issues/10572
Closes https://github.com/playframework/playframework/issues/10572
Updates `AssetsOverview.md` with documentation on the behavior of the Last-Modified header. Includes an explanation of the issue, and a workaround.
1. Built a Hello World application using Play Framework.
2. Added this line to build.sbt: `ThisBuild / packageOptions += Package.FixedTimestamp(Package.keepTimestamps)`.
3. Built with `sbt clean universal:packageZipTarball`.
4. Deployed app and sent a GET request to `{host}/assets/images/favicon.png` and inspected the image headers. Verified the `Last-Modified` header is now correctly set.
5. Updated documentation.
* https://github.com/playframework/playframework/issues/10572
* …
> Documentation Update: Asset timestamp handling with sbt

- documentation/manual/gettingStarted/IDE.md
Fixes #12485
- Adds instructions for getting VS Code setup
- Updates to a few broken urls
Noticed this was a raised issue from a while back and hadn't been implemented yet
#12485
> Documentation update: Add VSCode and url fixes to IDE page

- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/conf/application.conf
- dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/expected-application-log.txt
- documentation/manual/working/commonGuide/configuration/SettingsNetty.md
- project/Dependencies.scala
- transport/server/play-netty-server/src/main/resources/reference.conf
- transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
https://netty.io/wiki/native-transports.html#using-the-macosbsd-native-transport
- Got my attention while looking into #12703. 
It's quite easy to add actually.
> Support Netty's MacOS/BSD native transport

- documentation/manual/working/commonGuide/configuration/SettingsNetty.md
- project/Dependencies.scala
- transport/server/play-netty-server/src/main/resources/reference.conf
- transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala
I hope Cupertino has merci with me ;)
> It's called macOS 🍏

- .github/renovate.json
- dev-mode/gradle-plugin/build.gradle.kts
Inspired by the same problem in Twirl https://github.com/playframework/twirl/pull/920
> Fix Renovate to update Gradle Wrapper correctly

- dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayPlugin.java
Also, it doesn't matter an order applying Twirl and Play plugins now.
> [Gradle] Fix inject annotation in Twirl templates

- core/play/src/main/scala/play/api/mvc/Cookie.scala
> fix DiscardingCookie scaladoc

- documentation/build.sbt
- documentation/manual/releases/Scala3Migration.md
- documentation/manual/releases/release29/migration29/Migration29.md
- project/Versions.scala
- https://github.com/scala/scala-lang/pull/1786
> Scala 3.3.6

- documentation/manual/working/commonGuide/configuration/SettingsLogger.md
Relates to https://github.com/playframework/playframework/issues/10438
This documents the issue, until it's fixed (if possible).
> docs: add note about known bug with logger configuration

- .github/workflows/build-test.yml
- documentation/project/build.properties
- project/PlaySbtBuildBase.scala
- project/Versions.scala
- project/build.properties
- project/plugins.sbt
- https://github.com/sbt/sbt-ci-release/releases/tag/v1.11.0
- https://github.com/sbt/sbt/releases/tag/v1.11.0
> sbt + sbt-ci-release 1.11.0

- .github/workflows/build-test.yml
- documentation/project/build.properties
- project/Versions.scala
- project/build.properties
https://github.com/sbt/sbt/releases/tag/v1.11.2
> sbt 1.11.2

- .github/workflows/build-test.yml
- dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- project/PlayLibraryBase.scala
- project/PlaySbtBuildBase.scala
- project/PlaySbtLibraryBase.scala
- project/PlaySbtPluginBase.scala
- project/Versions.scala
> [2.9.x] sbt 1.11.2 everywhere

- .github/workflows/build-test.yml
- dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
- dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
- project/PlayLibraryBase.scala
- project/PlaySbtBuildBase.scala
- project/PlaySbtLibraryBase.scala
- project/PlaySbtPluginBase.scala
- project/Versions.scala
> [3.0.x] sbt 1.11.2 everywhere

- .github/scala-steward.conf
> [2.9.x] Pin okhttp in scala steward

- documentation/build.sbt
- project/Dependencies.scala
Fixes #xxxx
A new bug fix release
> config jar upgrade to 1.4.4

- core/play/src/main/scala/play/api/mvc/RequestHeader.scala
- core/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
> [3.0.x] Make sure Cookies, Session, Flash always exists even if empty

- core/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala
- transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
- transport/server/play-pekko-http-server/src/main/scala/play/core/server/PekkoHttpServer.scala
- transport/server/play-server/src/main/scala/play/core/server/Server.scala
> request passed to `onClientError` now has cookies, flash and session set

- .scalafmt.conf
- dev-mode/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/Colors.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayExceptions.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayFilters.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInternalKeys.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayLayoutPlugin.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayLogback.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
- dev-mode/sbt-plugin/src/main/scala/play/sbt/run/package.scala
- dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
- dev-mode/sbt-plugin/src/main/scala/sbt/internal/io/PlaySource.scala
- dev-mode/sbt-plugin/src/test/scala/play/sbt/ApplicationSecretGeneratorSpec.scala
- dev-mode/sbt-plugin/src/test/scala/play/sbt/PlayRunHookSpec.scala
- project/PlaySbtBuildBase.scala
- project/Versions.scala
Switching `Sbt-Plugin` code to new scala3 syntax. Splitting out some work for Scala3 crossbuilds/compatibility.
> Playsbt plugin scala3 syntax

- dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala
Towards #13319 
Removes `Watched` references in `PlayRun`.
See recommendation from @mkurz in [this comment](https://github.com/playframework/playframework/issues/13319#issuecomment-3296486534).
In short:
* `Watched` is quite different in SBT 2.0.
* `~run` functionality has been broken since sbt 1.4
* We should probably refactor this to use `sbt.nio.Watch` anyway.
> Remove Watched reference in PlayRun

- project/plugins.sbt
https://github.com/sbt/sbt-native-packager/releases/tag/v1.11.4
Minus one CVE
> sbt-native-packager 1.11.4
