framework/src/play-java/src/test/java/play/mvc/HttpTest.java
framework/src/play/src/main/java/play/mvc/Http.java

Just look at the test I added. When copying a context with `withRequest` or the copy constructor the language was never copied.

Also copy lang in ctx copy constructor and ctx.withRequest

---

documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
framework/project/BuildSettings.scala
framework/src/play/src/main/java/play/mvc/Http.java
framework/src/play/src/main/java/play/mvc/Result.java
framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala
framework/src/play/src/test/java/play/mvc/ResultsTest.java

Fixes #8644 
Deprecates method to get cookie that throws an exception if cookie not found and introduces new method that returns cookie wrapped in optional.
As discussed in issue.

Adds method to get cookie as optional.

---

framework/src/play-java/src/test/java/play/mvc/HttpTest.java
framework/src/play/src/main/java/play/mvc/Http.java

Similar to #8675 `WrappedContext` didn't handle the language correctly.
To fix that the language related methods needed to be overriden. Now **all** methods from `Context` are overriden by `WrappedContext`.
(We are not using `WrappedContext` in Play's codebase anymore, this is just for users who still rely on it.)

Correctly handle lang in WrappedContext

---

framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
framework/src/play/src/main/java/play/mvc/Http.java
framework/src/play/src/main/java/play/mvc/Result.java
framework/src/play/src/main/scala/play/api/mvc/Cookie.scala

See motivation and explanation in [this comment](https://github.com/playframework/playframework/pull/8546#discussion_r221903842).
Shouldn't it be OK to just *never* send the `HTTPOnly` flag when discarding a cookie - no matter if the flag was or was not send when creating the cookie?

DiscardingCookie never sends "HTTPOnly"

---

documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
framework/src/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java

I don't know why we put the csrf token in context args. Doesn't make any sense. Also it's Java API only.

Remove dead code

---

documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
documentation/manual/working/commonGuide/configuration/code/detailedtopics/httpec/MyController.java
documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
framework/project/BuildSettings.scala
framework/src/play/src/main/java/play/mvc/Controller.java
framework/src/play/src/main/java/play/mvc/Http.java
framework/src/play/src/main/java/play/mvc/Result.java
framework/src/play/src/main/scala/play/api/mvc/Flash.scala
framework/src/play/src/main/scala/play/api/mvc/RequestHeader.scala
framework/src/play/src/main/scala/play/api/mvc/Results.scala
framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala

This is basically the same as what #8687 was for session.
What was called `addingToSession` is called `flashing` here however (and not `addingToFlash`) to keep naming consistent with the Scala Flash API.
Also that `flashing` does not take a request (like `addingToSession` did), because we don't care about an existing flash in a request - we do not want to send it back to the client. (A flash is only short-lifed between two requests, unlike a session). Therefore `flashing` simply creates a new flash if there isn't one instead of using the `requests` flash.
Ready for review.

Deprecate Http.Context.flash method

---

framework/project/Dependencies.scala

`0.3.5` defaulted to `PKCS12` format for the auto-generated key stores. The `ssl-config` library doesn't support setting the trustStore password which is required in `PKCS12` format to read the trusted certificates. As a consequence generated stores could not be used as truststores.

Bumps ssl-config to 0.3.6

---

framework/src/play-integration-test/src/test/scala/play/it/http/FlashCookieSpec.scala
framework/src/play-integration-test/src/test/scala/play/it/http/UriHandlingSpec.scala
framework/src/play-integration-test/src/test/scala/play/it/test/EndpointIntegrationSpecification.scala
framework/src/play-integration-test/src/test/scala/play/it/test/OkHttpEndpointSupport.scala
framework/src/play-integration-test/src/test/scala/play/it/test/WSEndpointSupport.scala
framework/src/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
framework/src/play-server/src/main/scala/play/core/server/ServerEndpoint.scala
framework/src/play-server/src/main/scala/play/core/server/ServerEndpoints.scala
framework/src/play-test/src/main/scala/play/api/test/RunningServer.scala
framework/src/play-test/src/main/scala/play/api/test/ServerEndpoint.scala
framework/src/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala

Moves `ServerEndpoint{,s}` to `play.core.server`, from `play.api.test`.
Subset of #8689

Move ServerEndpoint to play.core.server

---

framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala

This is a follow-up to #8687 and #8688.
The scala `Result` methods `wResult.withSession(somevalue)` and `wResult.flashing(somevalue)` do **not** preserve any data - these methods will simply replace it's current `session` and `flash` data, replacing it with `somevalue`.
However we do want to preserve the results' session and flash data when creating the *final* result, like we do for headers and cookies just two lines above:
https://github.com/playframework/playframework/blob/f38e65a2e95e61883069a8cee170e72a2a873668/framework/src/play/src/main/scala/play/core/j/JavaHelpers.scala#L143-L144
`withHeaders` and `withCookies` here **do** preserve existing data.

Merge the ctx's flash/session with the result ones

---

documentation/manual/tutorial/PlayApplicationOverview.md

See [https://en.wiktionary.org/wiki/substitute](https://en.wiktionary.org/wiki/substitute).

Fix grammatical error in documentation

---

framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPProcessor.scala
framework/src/play-filters-helpers/src/main/scala/play/filters/csp/CSPResultProcessor.scala

Remove redundant backtick (`) from ScalaDoc

Remove redundant backtick from ScalaDoc

---

framework/src/play/src/main/scala/play/api/data/Forms.scala
framework/src/play/src/test/scala/play/api/data/FormSpec.scala

This introduces default bindings for IndexedSeq and Vector collection types.
In Play 2.6 the default Form bindings for repeated elements are: seq, list and set. However there are many use cases where Vector collection type is preferable due to its overall performance (such as for RandomAccess) if compared to List, it’s also considered one of the most popular and versatile collections in Scala. This change introduces a default binding for Vector and IndexedSeq in play.api.data.Forms as these types are not yet supported.
Pull request provided in response to lightbend discussion:
https://discuss.lightbend.com/t/feature-request-default-binding-for-vector-or-indexedseq-in-play-api-data-forms/2423
Tests added to existing test class: playframework/framework/src/play/src/test/scala/play/api/data/F …

Forms - add support for IndexedSeq and Vector bindings

---

framework/src/play/src/main/java/play/mvc/Http.java

The method `fileMimeTypes()` is part of `JavaContextComponents`. My mistake.

Fixed wrong JavaDoc

---

framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
framework/src/play/src/main/java/play/http/JsonHttpErrorHandler.java
framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala

I noticed that we are not actually running the `HttpErrorHandlerSpec`, because an exception was happening while the class was being constructed. We actually get an error like:
```
[trace] Stack trace suppressed: run last Play-Guice/test:testOnly for the full output.
```
but it doesn't actually fail the test.
I changed the test so that it actually fails, which led to discovering some issues, including that `JsonHttpErrorHandler` is not injectable using runtime DI. I fixed those issues as well in this pull request.
Ideally we also should fail the build if a spec fails on initialization.

Fix HttpErrorHandlerSpec and make JsonHttpErrorHandler injectable

---

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
framework/src/play/src/main/java/play/mvc/ResponseHeader.java
framework/src/play/src/main/java/play/mvc/Result.java
framework/src/play/src/main/scala/play/api/mvc/Results.scala

Fixes #8734.
Add new APIs to discard a cookie from results.

New APIs to discard headers on results

---

documentation/manual/working/scalaGuide/main/http/ScalaBodyParsers.md

From ScalaBodyParsers.md:
"The default body parser that’s used if you do not explicitly select a body parser will look at the incoming Content-Type header, and parses the body accordingly. "
The first half of the sentence is in the future progressive tense while the second is in the present tense. If the body parser *will* take an action in the future all the other actions it takes after that will also be in the future.
It's a small thing I know but it was bothering me as I was reading.

Fixed extremely small typo in ScalaBodyParsers.md

---

framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
framework/src/play-java-forms/src/main/java/play/data/Form.java

Preparations for an upcoming pull requests that deprecates `Http.Context` related stuff inside Java Forms.
Reviewing [per commit](https://github.com/playframework/playframework/pull/8731/commits) should be the easiest.

Java Form and DynamicForm cleanup

---

framework/src/play/src/main/java/play/mvc/Action.java
framework/src/play/src/main/scala/play/core/j/JavaAction.scala

Actually it doesn't really matter how we enter the chain since [Action.java](https://github.com/playframework/playframework/blob/be0e28c1e72be0ba02101e09852c3347835d986f/framework/src/play/src/main/java/play/mvc/Action.java#L62-L83) takes care to call the right method anyway.
This is just to make that a bit cleaner - could have been included in #8694 already actually.

Start action composition chain with call(req) not with call(ctx)

---

documentation/manual/releases/release27/migration27/Migration27.md
framework/project/BuildSettings.scala
framework/src/play-integration-test/src/test/scala/play/it/http/parsing/TextBodyParserSpec.scala
framework/src/play/src/main/java/play/mvc/BodyParser.java
framework/src/play/src/main/java/play/mvc/Http.java
framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
framework/src/play/src/test/scala/play/api/mvc/TextBodyParserSpec.scala
framework/src/play/src/test/scala/play/mvc/TextBodyParserSpec.scala

Fixes https://github.com/playframework/playframework/issues/4997
Changes "text/plain" Text and Tolerant Text parser to use "US-ASCII" as the default charset.
Per tools.ietf.org/html/rfc6657#section-4 the default for "text/plain" should be "US-ASCII", since that's what it's defined as in the media type definition at https://tools.ietf.org/html/rfc6657#section-4

Update Text Body Parser with US-ASCII as default charset

---

documentation/manual/working/javaGuide/main/application/JavaErrorHandling.md
documentation/manual/working/scalaGuide/main/http/ScalaErrorHandling.md
documentation/manual/working/scalaGuide/main/http/code/ScalaErrorHandling.scala
framework/src/play-guice/src/test/scala/play/api/http/HttpErrorHandlerSpec.scala
framework/src/play/src/main/java/play/http/HtmlOrJsonHttpErrorHandler.java
framework/src/play/src/main/java/play/http/PreferredMediaTypeHttpErrorHandler.java
framework/src/play/src/main/scala/play/api/http/HttpErrorHandler.scala
framework/src/play/src/main/scala/play/api/http/MediaRange.scala
framework/src/play/src/test/scala/play/api/http/MediaRangeSpec.scala

This defines a `PreferredMediaTypeHttpErrorHandler` for composing your own error handlers based on error handlers for specific content types, and an `HtmlOrJsonHttpErrorHandler` which does this with the Play-provided HTML and JSON handlers. The handler to use is determined based on the preferences in the `Accept` header. `HtmlOrJsonHttpErrorHandler` is designed to be a suitable default error handler for a web app that has a mixture of HTML and JSON endpoints (most modern web apps).

Add an HttpErrorHandler that selects the client's preferred media type

---

documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaForms.java
documentation/manual/working/javaGuide/main/ws/code/javaguide.ws.routes
documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/OpenIDController.java
framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
framework/src/play-java-forms/src/main/java/play/data/Form.java
framework/src/play-java-forms/src/main/java/play/data/validation/Constraints.java
framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java

There is just one thing you should know when reviewing this:
If you have a very simple template like...
```html
@(myForm: Form[User])
@helper.form(action = routes.Application.submit()) {
@helper.inputText(myForm("email"))
}
```
...the problem here is that `myForm("email")` - which actually calls `myForm.apply(String key)` - uses `Http.Context` internally to retrieve the language - which is then used to format the field value (important for numbers, dates, etc.)
So instead of having to pass a language every time within templates like e.g. `myForm("email", lang)`  (and to stay backwards compatible as well) I solved this by internally - inside the form instance - saving the language that was used during form binding and use it later inside `apply(key)` and `field(key)`.
Just have a look at …

Deprecate Java Form methods that depend on Http.Context

---

framework/src/play-ahc-ws/src/main/java/play/libs/ws/ahc/AhcWSRequest.java
framework/src/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
framework/src/play-ws/src/main/java/play/libs/ws/WSRequest.java
framework/src/play/src/main/java/play/DefaultApplication.java
framework/src/play/src/main/java/play/server/ApplicationProvider.java

Some of them were missing for Play 2.6 already. But market them as Play 2.7 deprecations since it is the version were we are effectively adding the deprecation annotation and docs.

Add some missing deprecated annotations and docs

---

documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/FiltersTest.java
documentation/manual/working/javaGuide/advanced/embedding/code/javaguide/advanced/embedding/JavaEmbeddingPlay.java
documentation/manual/working/javaGuide/advanced/routing/JavaRoutingDsl.md
documentation/manual/working/javaGuide/advanced/routing/code/AppLoader.java
documentation/manual/working/javaGuide/advanced/routing/code/GuiceRouterProvider.java
documentation/manual/working/javaGuide/advanced/routing/code/javaguide/advanced/routing/JavaRoutingDsl.java
documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/components/CompileTimeDependencyInjection.java
documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/GitHubClientTest.java
documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWebServiceClients.java
framework/src/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java
framework/src/play-java/src/main/java/play/routing/RequestFunctions.java
framework/src/play-java/src/main/java/play/routing/RoutingDsl.java
framework/src/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
framework/src/play/src/main/java/play/libs/F.java
framework/src/play/src/main/scala/play/api/mvc/Request.scala

RoutingDsl was able only to access the request using `Http.Context`. This PR fix it.

New APIS to avoid Http.Context when using RoutingDsl

---

framework/src/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
framework/src/play-integration-test/src/test/scala/play/it/http/ScalaResultsHandlingSpec.scala
framework/src/play/src/main/java/play/http/HttpEntity.java
framework/src/play/src/main/scala/play/api/http/HttpEntity.scala

Fixes #8713.
When calling `Result.as` or `HttpEntity.as` with a `null` value, it later fails when doing the model conversion to the server backend. Since the content type can be configured as an `Option`/`Optional`, it makes sense to handle null values as `None` and, instead of failing, just return the response without the header.

Handle null content type as if the header was not set

---

documentation/manual/working/scalaGuide/main/async/code/ScalaAsync.scala

The [Scala Async non-blocking actions demo code](https://www.playframework.com/documentation/2.6.x/ScalaAsync#Creating-non-blocking-actions) does not indicate that the `CustomExecutionContext` created needs to be specifically bound before use. The demo does not mention that it is not a fully-runnable snippet, so this documentation addition should help other Scala users from spending time to figure out what is missing.

Scala Async sample code for non-blocking futures notes CustomExecutionContext binding

---

documentation/manual/working/commonGuide/production/Deploying.md

It is necessary to see the Deploying with JPA page to see missing information about deploying that was not mentioned in the Deploying page.
Issue: https://github.com/playframework/playframework/issues/8773

Add link to Deploying with JPA

---

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java
documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
documentation/manual/working/javaGuide/main/http/code/javaguide/http/views/index.scala.html
documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/controllers/Twitter.java
framework/project/BuildSettings.scala
framework/src/play/src/main/java/play/mvc/Http.java
framework/src/play/src/main/java/play/mvc/Result.java
framework/src/play/src/main/java/play/mvc/Security.java
framework/src/play/src/main/scala/play/api/mvc/Flash.scala
framework/src/play/src/main/scala/play/api/mvc/Session.scala

Java's `Session` and `Flash` are mutable right now... extending `HashMap`...
Let's make it like the Scala ones.
That's what they will look like after Play 2.7 when all the deprecations are removed: https://gist.github.com/mkurz/6878b1f8b0b7a352fcd4683385faff06
(`getOptional` will be renamed back to `get`)

Preparations to make Java Session and Flash immutable

---

documentation/manual/working/commonGuide/configuration/WsSSL.md

Redo of https://github.com/playframework/playframework/pull/8784
This is a documentation only PR, but needs backporting to 2.6.x

Add note for `play.ws.ssl` prefix

---

framework/bin/publish-local
framework/bin/test-scala-212

Some minor travis build improvements:
* new publish-local job is only executed on cron jobs
* `test-scala-212` script should not force a version, but let sbt pick the default one

Minor travis improvements

---

framework/src/play-integration-test/src/test/java/play/it/http/ActionCompositionOrderTest.java
framework/src/play-integration-test/src/test/java/play/it/http/PreserveContextArgsController.java
framework/src/play-integration-test/src/test/scala/play/it/http/JavaActionCompositionSpec.scala
framework/src/play/src/main/java/play/mvc/Action.java

This is the last fix for the `Http.Context` stuff, I promise :sunglasses: 
To reproduce disable the http context thread-local by setting
```
play.allowHttpContext = false
```
**and**
you have a action composition chain that look like this:
1. `call(ctx)`
1. `call(req)`
1. `call(ctx)`
1. the action method
There is one small bug if you set something into the `ctx.args` in the *first* `call` and want to access/retrieve that `ctx.args` value(s) in the *third* `call` again. Right now `ctx.args` will not contain the elements in that *third* `call` which where set in the *first* call. That's because when converting the `ctx` to a `req` between step 1 and 2 the `ctx.args` will be lost (since a request does not have a `args` field).
What I did is I carry over the `ctx.args` via a request attribute …

Pass ctx.args between actions in chain when thread-local is disabled

---

framework/src/play/src/main/java/play/Logger.java

Very tiny fix, just to stay consistent with the other methods (`trace`, `debug`, `info`) which also don't call `logger.underlyingLogger()` directly.

Small fix/cleanup for play.Logger

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala
documentation/manual/working/scalaGuide/main/application/code/EssentialFilter.scala
documentation/manual/working/scalaGuide/main/application/code/FiltersRouting.scala
documentation/manual/working/scalaGuide/main/application/code/ScalaHttpFilters.scala
documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
framework/src/play/src/main/java/play/Logger.java
framework/src/play/src/main/scala/play/api/Logger.scala

In RC3 `play.Logger` [is deprecated](https://www.playframework.com/documentation/2.7.0-RC3/Migration27#play.Logger-deprecated). I get [the idea](https://github.com/playframework/playframework/issues/1669) why using that class introduces some problems. However I think we should not deprecate the class itself, but only it's `static` methods. The same for `play.api.Logger` - we should only deprecate the usage of the singleton. But for both cases it's totally OK to use its instances, there is nothing wrong with them IMHO.
The advantage of using those wrapper classes instead of SLF4J itself is that right now SLF4J [does not provide logging methods which accept lambda expression](https://jira.qos.ch/browse/SLF4J-371) as parameters (for lazy evaluation). That's why I would still keep …

Don't deprecate whole play.Logger, but only the static Logger singleton

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/javaGuide/main/logging/JavaLogging.md
documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaLogging.java
documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/User.scala
documentation/manual/working/scalaGuide/main/application/code/EssentialFilter.scala
documentation/manual/working/scalaGuide/main/application/code/FiltersRouting.scala
documentation/manual/working/scalaGuide/main/application/code/ScalaHttpFilters.scala
documentation/manual/working/scalaGuide/main/http/code/ScalaActionsComposition.scala
documentation/manual/working/scalaGuide/main/logging/ScalaLogging.md
documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
framework/src/play/src/main/scala/play/api/Logger.scala

- Updates Logger documentation to de-emphasize the global logger and mention that it is now deprecated.
- Clarifies different migration paths in the migration guide.
- Updates example code to use a locally-defined logger val where possible.
- Adds a `Logging` trait to make it much easier to use a logger per class in Scala.

Update Logger documentation and add Logging trait

---

framework/src/play-guice/src/main/scala/play/api/inject/guice/GuiceApplicationBuilder.scala
framework/src/play-guice/src/test/scala/play/api/inject/guice/GuiceApplicationBuilderSpec.scala

Fixes #8806 
This needs to be bound as a singleton, since it has mutable state that you might want to access after injecting it into another component.

Bind WebCommands as a Singleton since it has mutable state

---

documentation/manual/releases/release27/migration27/Migration27.md

Fixes links to the CSP filter documentation page in the Play 2.7 migration guide.
Fixes links to the CSP filter documentation page in the Play 2.7 migration guide.

Casing fix for CSPFilter links in the migration guide

---

documentation/manual/working/javaGuide/main/forms/JavaForms.md
documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/JavaFormsDirectFieldAccess.java
documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/u4/User.java
framework/src/play-java-forms/src/main/java/play/data/DynamicForm.java
framework/src/play-java-forms/src/main/java/play/data/Form.java
framework/src/play-java-forms/src/main/resources/reference.conf
framework/src/play-java-forms/src/test/java/play/data/Subtask.java
framework/src/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
framework/src/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala

Fixes https://discuss.lightbend.com/t/databinder-field-access-instead-of-using-accessors/2468
Adds `play.forms.binding.directFieldAccess` config to switch on direct field access for all forms. To control specific forms only this pull request adds `form.withDirectFieldAccess(...)` to switch direct field access on or off - or if `null` falls back to config fallback.

Allow direct field access in Java Forms

---

documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/AgeRange.java
documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/User.java
framework/src/play-java/src/main/java/play/libs/Time.java
framework/src/play/src/main/scala/play/api/mvc/Cookie.scala
framework/src/sbt-plugin/src/sbt-test/routes-compiler-plugin/injected-routes-compilation-with-request-passed/tests/RouterSpec.scala

Same for `Long`.
Bumped into that when trying to run scripted tests with Java 11.
The constructors have been deprecated with Java 9:
https://docs.oracle.com/javase/9/docs/api/java/lang/Integer.html#Integer-int-
https://docs.oracle.com/javase/9/docs/api/java/lang/Long.html#Long-long-
> _It is rarely appropriate to use this constructor. The static factory `valueOf(...)` is generally a better choice, as it is likely to yield significantly better space and time performance._

Integer.valueOf instead of deprecated new Integer(...)

---

documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/playlib/HelloModule.java

When running with Java 11 fixes this problem:
```
[error] documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/playlib/HelloModule.java:16: reference to Module is ambiguous
[error]   both class play.inject.Module in play.inject and class java.lang.Module in java.lang match
```

Fix ambiguous import for Java 11

---

.travis.yml

I think that makes sense, so we don't have to wait for the Java 11 build to finish because it has `allow_failures` set anyway.
See
- https://docs.travis-ci.com/user/customizing-the-build/#fast-finishing
- https://blog.travis-ci.com/2013-11-27-fast-finishing-builds

[Travis CI] fast_finish: true

---

documentation/manual/working/javaGuide/main/forms/JavaFormHelpers.md

Just adds a short sentence which is already available in the [Scala Form docs](https://www.playframework.com/documentation/2.7.0-RC3/ScalaForms#Repeated-values) but is missing in the Java Form docs (this was just copy & paste :smiling_imp:).
Just to confirm:
[Scala implementation](https://github.com/playframework/playframework/blob/2.7.0-RC3/framework/src/play/src/main/scala/play/api/data/Form.scala#L101)
[Java implementation](https://github.com/playframework/playframework/blob/2.7.0-RC3/framework/src/play-java-forms/src/main/java/play/data/Form.java#L239)

Java Form doc update on how to bind List

---

framework/project/BuildSettings.scala

Our release process right now publishes to two services: Sonatype (that will sync to Maven Central) and Bintray (where sbt plugins) lives. That means if one of the services fails for some reason, we may end up in a situation where the release is half done. When that happens, the most secure thing is to do another release increasing the version number.
But this is not ideal and may lead to a confusing situation. For example, right now we have two release candidates for Play 2.7.0 but the second one is RC**8**!
Not promoting the artifacts automatically is not ideal since it adds manual steps to our release process, but for now, it helps us to avoid this situation where we have half-baked releases. We will eventually refactor our release process to make it safer and with minimal manual …

Do not promote artifacts automatically

---

framework/build.sbt
framework/project/BuildSettings.scala

Microbenchmarks weren't being published anymore, but they weren't also
being aggregated. This aggregates the project again but configures it not to release artifacts.
Integration tests on the other side are still being published, but this
is not intentional since this is an internal artifact used only to test
Play itself.
Fixes #7743.

Avoid publishing microbenchmarks and integration tests artifacts

---

documentation/manual/releases/release27/migration27/Migration27.md

The 2.7 migration guide stated that at time of writing, sbt 1.1.6 was the latest version. I've updated that to 1.2.7 (and I have run Play on sbt 1.2.7 and everything seems to work with no problems).

Added sbt 1.2.7 to Play 2.7 migration guide

---

documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md
documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/releases/release27/migration27/index.toc
framework/src/run-support/src/main/scala/play/runsupport/RunHook.scala

The major sections for the migration guide are now:
- How to migrate
- API Changes
- Configuration changes
- Defaults changes
- Updated libraries
- Removed libraries
- Other important changes
This better groups sections that are related but weren't close to each other. It also adds complete code samples for the Http.Context migration guide and do some formatting changes there.
_review using [?w=1](https://github.com/playframework/playframework/pull/8843/files?w=1)_.

Better organize migration guide

---

framework/project/BuildSettings.scala

Avoid to track dependencies for unpublished projects.

Ignoring WhiteSource for unpublished projects

---

framework/project/plugins.sbt

This version brings Scala 2.12.8.
- https://github.com/playframework/interplay/pull/55
- #8863

Update interplay to version 2.0.5

---

framework/src/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
framework/src/play-java/src/test/scala/play/mvc/MixTemplateAndHttpImplicits.scala

Fixes #8866
First of all [I forgot](https://github.com/playframework/playframework/pull/8756/commits/bc48f82fcde3ad6176a4c6c8a92440e2f8f80174) to actually make the three methods `implicit`. Fixed that, however when doing so the new lang method now interferes with the `implicitJavaLang` method (which is also defined in the `PlayMagicForJava` object):
```
[error] framework/src/play-java/src/test/scala/play/mvc/NoImplicitLang.scala:11: ambiguous implicit values:
[error]  both method implicitJavaLang in object PlayMagicForJava of type => play.api.i18n.Lang
[error]  and method messagesProvider2Lang in object PlayMagicForJava of type (implicit msg: play.api.i18n.MessagesProvider)play.api.i18n.Lang
[error]  match expected type play.api.i18n.Lang
[error]     ImplicitLangInclude()
[error] …
```

Fix ambiguous @lang, @flash and @session

---

framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
framework/src/play/src/main/scala/play/core/parsers/Multipart.scala

Fixes #8727 and #6203
This restores the behavior we had in Play 2.4 and before: When submitting a form and leaving a file field empty, the `filename` is empty. Like in Play 2.4, we should handle this as failure.
[This line](https://github.com/playframework/playframework/pull/5037/files#diff-a41a1796efe45be8ecc6d68806de1b81L151) - which was removed - took care for this in Play 2.4 and below. Plus, as you can see in the comments of #8727 and #6203 people work around this problem by checking for an empty file name as well.
(After this pull request I will provide another one which actually also checks for the file itself if it's empty, not just the filename)

Handle multipart form upload with empty filename as BadPart

---

.travis.yml
framework/bin/scriptLib
framework/project/AkkaSnapshotRepositories.scala
framework/project/Dependencies.scala

The purpose is to discover Akka HTTP integration problems sooner. This enables us to configure a nightly build in Travis to test against Akka HTTP snapshots. Basically the same we did for Akka in #8601.

Use Akka HTTP snapshots for our cron builds

---

framework/project/Dependencies.scala

Adds the provided classifier to scala-reflect, so that the Scala version provided by the project is used.
Implements https://github.com/playframework/playframework/issues/1459

Decouple scala-reflect library from Play dependencies

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md
documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
documentation/manual/working/scalaGuide/main/upload/ScalaFileUpload.md
framework/src/play-integration-test/src/test/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
framework/src/play/src/main/scala/play/core/parsers/Multipart.scala

#8880 was for empty filenames, this is for empty files.

Handle multipart form upload with empty file as BadPart

---

framework/project/Dependencies.scala

Update Akka HTTP version to 10.1.6.
https://akka.io/blog/news/2018/12/19/akka-http-10.1.6-released

Update Akka HTTP to version 10.1.6

---

framework/src/play/src/main/scala/play/api/mvc/Action.scala

Contains minor scaladoc improvement. 
Previous example was not showing how to pass the body parser.

minor scaladocs improvement

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/javaGuide/main/upload/code/javaguide/fileupload/controllers/HomeController.java
framework/src/play/src/main/java/play/libs/Files.java
framework/src/play/src/main/scala/play/api/libs/Files.scala
framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala

Fixes #8885.
Add `copyTo` methods to temporary files and better document the differences between copying and moving files.
Depends on #8891.

Add copy methods to temporary files

---

documentation/manual/releases/release27/Highlights27.md
framework/src/play-integration-test/src/it/scala/play/it/action/HeadActionSpec.scala
framework/src/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
framework/src/play-integration-test/src/it/scala/play/it/http/ScalaResultsHandlingSpec.scala
framework/src/play-integration-test/src/it/scala/play/it/tools/HttpBin.scala
framework/src/play/src/main/java/play/mvc/StatusHeader.java
framework/src/play/src/main/scala/play/api/mvc/Results.scala

Fixes #8853.
Add new tests to ensure `HttpEntity.Streamed` sends `Content-Length` when it is defined.

Add tests for HttpEntity.Streamed content length header 

---

framework/bin/test-sbt-plugins-1_0

I missed that one in #8863 
Also is there a reason why we don't use latest sbt when running sbt tests for 1.x?
1.2.8 was just released:
https://developer.lightbend.com/blog/2018-12-30-sbt-1-2-8/

Scala 2.12.8 and latest sbt

---

documentation/manual/releases/release27/migration27/Migration27.md

I thought we tested these code snippets so they compiled?

Fix class literal syntax in the 2.7 migration guide

---

documentation/manual/releases/release25/migration25/Migration25.md

"ScalaTest + Plus" in Migration25 page may be typo of "ScalaTest + Play".

Fix typo "ScalatTest + Play"

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
documentation/manual/working/javaGuide/main/upload/code/javaguide/fileupload/controllers/HomeController.java
documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
framework/build.sbt
framework/src/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
framework/src/play-java-forms/src/test/scala/play/data/FormSpec.scala
framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
framework/src/play/src/main/java/play/mvc/BodyParser.java
framework/src/play/src/main/java/play/mvc/Http.java
framework/src/play/src/main/java/play/mvc/MultipartFormatter.java
framework/src/play/src/main/scala/play/api/mvc/BodyParsers.scala
framework/src/play/src/main/scala/play/core/formatters/Multipart.scala
framework/src/play/src/main/scala/play/core/j/JavaParsers.scala
framework/src/play/src/main/scala/play/core/parsers/Multipart.scala

Manual backport of #8913.
Includes MiMa exclusions that we should remove as soon as we cut 2.7.0.
Resolves #8934

FilePart backporting

---

documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java
framework/src/play-java/src/test/java/play/mvc/RequestBuilderTest.java
framework/src/play/src/main/java/play/mvc/Http.java

Fixes #8895.
Also see #8913 for further details.
I think the name of the method is very confusing because it does not actually save a `MultipartFormData` instance.

Rename bodyMultipart(...) which actually saves a RawBuffer

---

framework/src/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala

Nothing special, during my work on some multipart-form data stuff I thought we should have tests when parsing arrays (specially to make sure they stay in order if the indexes are provided).

Add multipart tests for arrays

---

documentation/manual/working/scalaGuide/main/http/ScalaRouting.md

Fix ScalaRouting.md by making SIRD(String Interpolating Routing DSL) uppercase.

Update ScalaRouting.md sird to be uppercase

---

documentation/manual/working/javaGuide/main/upload/code/JavaFileUploadTest.java

There is absolutely no need to set this header here because it will be set in the `body(...)` method anyway
https://github.com/playframework/playframework/blob/8017eb596b9f732a573f37aaf9343cd8fc975b27/framework/src/play/src/main/java/play/mvc/Http.java#L1215-L1216 which itself gets called by the `bodyMultipart(...)` method: https://github.com/playframework/playframework/blob/8017eb596b9f732a573f37aaf9343cd8fc975b27/framework/src/play/src/main/java/play/mvc/Http.java#L1333
(Also that header was wrong actually because it should include the boundary: `multipart/form-data; boundary=...`)

No need to set header, will be set automatically

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
framework/build.sbt
framework/src/play/src/main/java/play/libs/Files.java
framework/src/play/src/main/scala/play/api/libs/Files.scala
framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala

**This change is backwards compatible for 2.6.x to 2.7.0 migration. Only the newly introduced `copyTo` method breaks for people that make use of it in the `2.7.0-RC`s.**
This applies #8956 onto the `2.7.x` branch (see first commit). This is an important fix and definitely needs  to go into `2.7.x` IMHO.
However it doesn't do just that: [Like suggested](https://github.com/playframework/playframework/issues/8954#issuecomment-454878575) by @wsargent (and by me :wink:) we should get the API right for the move and copy methods.
Therefore what I did is (I tried to keep clean, separate commits for easier reviewing):
* `copyTo` - which will be a *completely new method in 2.7.0* - should immediately return `Path` and not introduce a wrong API from beginning (by returning `TemporaryFile`). That's …

[2.7.x] Fix GC bug and API for TemporaryFile move and copy methods

---

documentation/manual/Home.md
documentation/manual/LatestRelease.md
documentation/manual/releases/index.toc
documentation/manual/releases/release28/Highlights28.md
documentation/manual/releases/release28/index.toc
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/releases/release28/migration28/index.toc

Game on!
I added scaffold highlights and migration pages based on the ones we have in 2.7 (actually just copied and adjusted them).
I already also added the removal of Scala 2.11 support to the migration guide ([like we did in the Play 2.5 guide for Scala 2.10](https://www.playframework.com/documentation/2.6.x/Migration25#Scala-2.10-support-discontinued)) that happend in #8629.

Add docs for 2.8 release ;)

---

documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
framework/src/play/src/main/java/play/libs/Files.java
framework/src/play/src/main/scala/play/api/libs/Files.scala
framework/src/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala

Forward port of #8958 except the MiMa rules in `build.sbt`. (Just did a simple rebase onto master)

[master] Fix GC bug and API for TemporaryFile move and copy methods

---

framework/project/Dependencies.scala

Has been published now for Scala 2.13.0-M5:
https://github.com/etorreborre/specs2/issues/709#issuecomment-452867297

specs2 upgrade

---

framework/src/play-integration-test/src/it/java/play/BuiltInComponentsFromContextTest.java
framework/src/play-integration-test/src/it/scala/play/it/http/JavaHttpErrorHandlingSpec.scala
framework/src/play-server/src/main/scala/play/core/server/Server.scala
framework/src/play/src/main/java/play/BuiltInComponentsFromContext.java

Fixes #8947.
This fixes a problem with requests failing in an unexpected way when there is the need to translate the request to Java (for example if there is a Java error handler) and web commands fail. The problem can be seen in evolutions, but any web command would make the request fails.
See explanation at this comment: https://github.com/playframework/playframework/issues/8947#issuecomment-455196484

[2.7.x]: Avoid error when web command fails and there is a Java error handler

---

framework/project/Dependencies.scala

See http://in.relation.to/2019/01/07/hibernate-validator-6014-final-out/
Needs to be backported to 2.7.x.

Hibernate Validator upgrade (critical bugfix)

---

framework/src/play-java-forms/src/main/java/play/data/Form.java
framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java

Fixes #8318 for the 2.7.x and master branch.
See https://github.com/playframework/playframework/issues/8318#issuecomment-455814157 for explanation.

[2.7.x] Use error.invalid when form binding fails and messages are empty

---

framework/src/play-java-forms/src/main/java/play/data/Form.java
framework/src/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java

Fixes #8318 for the 2.6.x branch.
See https://github.com/playframework/playframework/issues/8318#issuecomment-455814157 for explanation.

[2.6.x] Use error.invalid when form binding fails and messages are empty

---

documentation/manual/releases/release27/Highlights27.md

This is added to 2.7.x Hightlights. Should be backported to 2.7.x.
Resolves #8994

Hightlights new Router.orElse method

---

documentation/manual/working/commonGuide/build/SBTCookbook.md

If you enter UpdateLogging.FULL in sbt it creates errors.
Fixes #xxxx

Replaced UpdateLogging.FULL with UpdateLogging.Full

---

framework/src/sbt-plugin/src/sbt-test/README.md
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/build.sbt
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/project/plugins.sbt
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/main/resources/application.conf
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/main/resources/routes
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/main/scala/controllers/HomeController.scala
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/src/test/scala/controllers/IntegrationTest.scala
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http-http2/test
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/build.sbt
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/project/plugins.sbt
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/main/resources/application.conf
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/main/resources/routes
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/main/scala/controllers/HomeController.scala
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/src/test/scala/controllers/IntegrationTest.scala
framework/src/sbt-plugin/src/sbt-test/http-backend/akka-http/test
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/build.sbt
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/project/plugins.sbt
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/main/resources/application.conf
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/main/resources/routes
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/main/scala/controllers/HomeController.scala
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/src/test/scala/controllers/IntegrationTest.scala
framework/src/sbt-plugin/src/sbt-test/http-backend/netty/test

This is a complement to #8963 
Adds a `scripted` test suite to assert in test code a user always gets a `Server` implemented with the desired backend and protocols.

Assert testkit uses the correct ServerProvider

---

documentation/manual/releases/release27/migration27/JavaHttpContextMigration27.md

This fixes a typo when referencing hypothetical PathBindables named "Request". This typo only exists in the Java documentation.

Fix typo "PahBindable" -> "PathBindable"

---

framework/project/Dependencies.scala

https://github.com/brettwooldridge/HikariCP/blob/HikariCP-3.3.1/CHANGES
+
better Java 11 support because they upgraded Javaassist:
https://github.com/brettwooldridge/HikariCP/pull/1303
https://github.com/jboss-javassist/javassist/releases

HikariCP minor release

---

documentation/manual/working/commonGuide/configuration/SettingsNetty.md
transport/server/play-netty-server/src/main/resources/reference.conf
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala

Fixes #9030
This pull request strips any `"` prefixes and suffixes when setting netty channel options from the key so an config key containing `#` that needs to be quoted (like `"io.netty.channel.epoll.EpollChannelOption#TCP_FASTOPEN" = 1`) can be passed to netty correctly (without the quotes).
I also updated the docs and reference conf with valid examples.
Needs to be backported to `2.7.x`

Correctly read netty channel options

---

core/play/src/main/java/play/mvc/Results.java
core/play/src/main/java/play/mvc/StatusHeader.java

Same like #9038 for 2.7.x but without the Scala API change which would break binary compatibility.

[2.7.x] Allow to set inline content-disposition AND filename together

---

core/play/src/main/scala/play/core/j/JavaAction.scala

Same like #8989 for 2.7.x but just logs a warning instead of aborting the request.

[2.7.x] Log warning for @Singleton java actions

---

core/play-integration-test/src/it/java/play/it/http/ActionCompositionOrderTest.java
core/play-integration-test/src/it/scala/play/it/http/JavaActionCompositionSpec.scala
core/play/src/main/scala/play/core/j/JavaAction.scala

Fixes #8985
See https://github.com/playframework/playframework/issues/8985#issuecomment-457009162 for further explanation how data could be leaked between distinct requests.
We already have [a warning note in the docs](https://www.playframework.com/documentation/2.6.x/JavaActionsComposition#Composing-actions):
> _**Note**: Every request **must** be served by a distinct instance of your play.mvc.Action. If a singleton pattern is used, requests will be routed incorrectly during multiple request scenarios._
However because it's quite easy to check if an action is marked as singleton, I think it's safer to just abort the whole request to completely avoid scenarios where data could be leaked. Like the note in the docs says it already, each action **has to be**  a distinct instance and this …

Disallow @Singleton java actions to avoid data leaks between requests

---

core/play/src/main/java/play/mvc/Results.java
core/play/src/main/java/play/mvc/StatusHeader.java
core/play/src/main/scala/play/api/mvc/Results.scala
project/BuildSettings.scala

This just bit me:
When sending a file (or resource) there are no `ok(...)`,... methods that take **both** the inline **and** the filename param.
(The current workaround is to directly call `return status(OK).sendFile(file, true, "somefilename.txt")` because the `sendXXX` methods do provide those params already...)
Plus:
I also added `sendResource` methods which solely take a filename param (right now you always have to also pass an inline param or a other param as well). Actually the `sendResource` just wasn't on par with all the other `sendXXX` method, which do have such methods already.
Now all those methods should be up-to-date.

Allow to set inline content-disposition AND filename together

---

core/play/src/main/java/play/mvc/Results.java

In the Scala API we do have `sendPath(...)` and in the Java API we also have `statusHeaderObj.sendPath(...)`.
However, we do not have shortcuts for the *static* methods `status(...)`, `ok(...)`, etc.
BTW: The code was generated with https://github.com/jroper/play-source-generator. However that project wasn't up-to-date, therefore I provided an update: https://github.com/jroper/play-source-generator/pull/3.

Add status(...), ok(...), methods with Path param

---

.mergify.yml

* Update to the travis-ci.com move
* Drop the condition on the WIP bot, which was removed
* Update to the new label names
* Drop the label removal, as it interacts poorly with the previous rule

Update the Mergify config

---

documentation/manual/hacking/Repositories.md

This PR updates our documentation to explain that Play is published to Maven central repositories.

Document the use of maven central repository

---

core/play/src/main/scala/play/api/http/HttpConfiguration.scala
core/play/src/test/scala/play/api/http/SecretConfigurationParserSpec.scala

Fixes #8981
Removed `play.crypto.secret` & `application.secret` leaving `play.http.secret.key` as the only way to set secret key

Remove application.secret and play.crypto.secret support

---

core/play/src/main/scala/views/helper/Helpers.scala
core/play/src/test/scala/views/html/helper/HelpersSpec.scala

Fixes https://discuss.lightbend.com/t/form-template-helpers-error-force-an-error/3471
According to [the docs](https://www.playframework.com/documentation/2.7.x/JavaFormHelpers#Field-constructors) you can force an error by passing a *String* param to a form helper:
```
'_error -> "Force an error"
```
However with a string this just doesn't work right now. You have to pass a `FormError` object wrapped in an `Option` instead to make it work:
```
'_error -> Some(FormError("foo", "Force an error"))
```
This pull request finally makes `String` (and `Option(String)`) work so it behaves like the documentation says. You can now write:
```
'_error -> Some("Force an error")
'_error -> "Force an error"
```

Form input helper argument "_error" should handle String

---

dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/app/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/build.sbt
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/conf/application.conf
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/conf/logback.xml
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/conf/routes
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/expected-application-log.txt
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/project/Build.scala
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/http-backend/netty-channel-options/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/build.sbt
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala

Follow-up to #9031
We allow [to pass various options](https://github.com/playframework/playframework/blob/9bf8e49deb60f0203d4140e98eb4437ba5351209/transport/server/play-netty-server/src/main/resources/reference.conf#L50-L68) to Netty:
```
play.server.netty {
option {
// options for bootstrapping go in here (_directly_ inside the "option" path)
child {
// options for channels go in here (inside the "child" path)
}
}
}
```
As you can see we have options for bootstrapping Netty and options for channels. All of these options are defined in [`ChannelOption`](https://netty.io/4.1/api/io/netty/channel/ChannelOption.html) and - when using native socket transport - it's subclasses [`UnixChannelOption`](https://netty.io/4.1/api/io/netty/channel/unix/UnixChannelOption.html) and …

Netty: Make sure to init static Epoll/UnixChannelOption members

---

build.sbt
core/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
scripts/validate-microbenchmarks

Fixes `p.microbenchmark.it.HelloWorldBenchmark` when using akka-http-2 (ak-20-enc) and akka http1.1 encrypted (ak-11-enc)
`ak-20-enc` was failing with a `java.lang.ClassNotFoundException: akka.http.scaladsl.Http2` exception because of missing akka-http2-support jar.
`ak-11-enc` was failing with a `javax.net.ssl.SSLPeerUnverifiedException: Hostname localhost not verified:` which was solved by setting the a dumb `hostnameVerifier` in the OkHttp client

fix jmh Microbenchmarks

---

.scalafmt.conf
scripts/scalafmt

This one is important because as of 2.0.0-RC5 scalafmt-dynamic actually
uses the Scalafmt "version" key in .scalafmt.conf to dispatch to that
Scalafmt version.

Scalafmt 2.0.0-RC5

---

core/play/src/main/scala/play/core/hidden/ObjectMappings.scala

use #! /bin/sh -
the space between #! and /bin/sh is for compatibility
the - is the to prevent arbitrary code execution -[options] can be used
Per Arnold Robbins and Nelson Beebe in Shell Scripting 
http://shop.oreilly.com/product/9780596005955.do
Fixes #xxxx

Changed !#/bin/sh to !# /bin/sh -

---

transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala

The `takeWhile(_.isLastChunk)` causes the downstream sink to immediately receive a completion, while terminating upstream so that from Akka HTTPs perspective, the full request body hasn't been consumed yet. Due to one or the other of these, when the response does get sent, Akka HTTP outputs a warning saying the response is being sent before the request has been consumed.
This replaces it with a `filter(_.isLastChunk)`, so that no termination signals get introduced other than the one coming from Akka HTTP itself, and so consequently avoids the early termination error, meanwhile it has the same effect as `takeWhile` since the last chunk is always the last element in the stream.

Fixed early response warning on chunked requests

---

.github/settings.yml

To indicate on PRs that should backport also to the 2.6.x branch.

Add a "status:needs-backport-2.6" label

---

documentation/project/plugins.sbt
project/plugins.sbt

Fixes #9024
The docs project still used M2.
Plus:
https://github.com/sbt/sbt-native-packager/blob/master/CHANGELOG.md#v1319-2019-03-02

Upgrade twirl (in docs project) and sbt-native-packager

---

documentation/manual/working/commonGuide/production/ProductionConfiguration.md

We do so [here](https://www.playframework.com/documentation/2.7.x/SettingsAkkaHttp) and [here](https://www.playframework.com/documentation/2.7.x/SettingsNetty), so I guess it makes sense to show the configs [here](https://www.playframework.com/documentation/2.7.x/ProductionConfiguration#Server-configuration-options) as well.

Show generic configurations in Production Configuration docs

---

documentation/manual/working/javaGuide/main/akka/JavaAkka.md
documentation/manual/working/javaGuide/main/akka/code/javaguide/akka/akka.conf
documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md

A `fork-join-executor` [does not have](https://github.com/akka/akka/blob/v2.5.21/akka-actor/src/main/resources/reference.conf#L445-L462) a `pool-size-max` config.
Fixes two occurrence in [`JavaAkka`](https://www.playframework.com/documentation/2.7.x/JavaAkka#Configuration) and one occurrence in [`ScalaAkka`](https://www.playframework.com/documentation/2.7.x/ScalaAkka#Configuration).
Interestingly, the first occurrence in `ScalaAkka` was fixed long time ago in #3905 already...

Fix fork-join-executor config in docs

---

documentation/manual/releases/release27/migration27/Migration27.md
project/Dependencies.scala

https://github.com/google/guava/releases/tag/v27.1
We may want to backport.

Upgrade guava

---

web/play-filters-helpers/src/main/resources/reference.conf

Is there something that speaks against adding `127.0.0.1` to allowed hosts? `localhost` is already there, so I think it's safe.
Every time I start up a Play app usually I navigate to '127.0.0.1:9000', hitting the allowed hosts filter which denies my request, so usually I always set this config in my `application.conf`.

Add 127.0.0.1 to allowed hosts filter

---

dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala

Effects dev mode only.
If you have in your `build.sbt`:
```sbt
javaOptions in Runtime += "-Dmyconfkey=one"
```
then run your app in dev mode via
```sbt
run -Dmyconfkey=ten
```
and later in your running app read the key via
```java
config.getString("myconfkey")
```
the result should be`ten`, taken from the command line. Command line args/props should always win, otherwise they are useless. However right now it is `one`.
Fix is easy, we just need to change the order.
Along the way I also fixed a bug I guess: Turns out that we didn't clean all the system properties we set when closing the dev server...
(I also renamed the variables to make clear what they are about)

In DEV mode props from args should override props from javaOptions

---

core/play/src/main/scala/play/api/Play.scala

Fixes an out of date comment for master branch.  This was changed in https://github.com/wsargent/playframework/commit/ccda638#diff-8c92eba25113fadb7c0c63d00ee6a572L42 but the explicit factory comment was not removed.
Backported to 2.7.x branch as https://github.com/playframework/playframework/pull/9103

[master] Remove incorrect comment on SAXParserFactory

---

transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala

This was a TODO in the code
We keep the try/catch as `query()` can fail to parse the query

use request.uri.query().toMultiMap from akka-http

---

dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala

I want to be sure that inside an app whenever I read the server port(s) or the address from the config via 
```java
config.getInt("play.server.http.port")
config.getInt("play.server.https.port")
config.getString("play.server.http.address")
```
I get the actual values the backend server is running with. Usually that is the case of course.
There are exceptions however: E.g. when defining the http port as the first non-property argument in dev mode via
```
run 9003
```
the `play.server.http.port` setting stays the default (9000) while the server is running with 9003.
Or when setting the port/address in `build.sbt` via
```sbt
PlayKeys.playDefaultPort := 9004
PlayKeys.playDefaultAddress := "..."
```
the same behaviour occurs.
This can make problems during development if you have components …

Make sure play.server.http(s).port/address always gets set in DEV mode

---

dev-mode/run-support/src/main/scala/play/runsupport/Reloader.scala
documentation/manual/working/commonGuide/configuration/ConfigFile.md
documentation/manual/working/commonGuide/production/ProductionConfiguration.md
transport/server/play-server/src/main/resources/reference.conf

We want to be able to control the server port(s) and address via environment variables. Unfortunately in Linux it's not possible set set environment variables that contain dots (`http.port`,...).
Therefore I added `PLAY_HTTP_PORT`, `PLAY_HTTPS_PORT` and `PLAY_HTTP_ADDRESS`, the same format that we use for PLAY_EDITOR already
https://github.com/playframework/playframework/blob/02d92bf5b2cd4eb46490b76571a11d8e24422d68/transport/server/play-server/src/main/resources/reference.conf#L105
This is backwards compatible because the env variable is the last fallback (before using the default value).

Allow to set port(s) and address via env variables

---

core/play-microbenchmark/src/test/scala/play/microbenchmark/it/HelloWorldBenchmark.scala
core/play/src/main/scala/play/api/Play.scala
web/play-java-forms/src/main/java/play/data/Form.java

Fixes an out of date comment for 2.7.x branch. This was changed in wsargent/playframework@ccda638#diff-8c92eba25113fadb7c0c63d00ee6a572L42 but the explicit factory comment was not removed.
This was originally https://github.com/playframework/playframework/pull/9085 but was incorrectly created from the playframework branch (and then couldn't be merged because of build breakage, and could not be force pushed).

[2.7.x] Remove incorrect documentation 

---

.travis.yml

Mergify create branches directly on the /playframework/playframework/ repository when doing backports, meaning Travis runs builds for the pull request and the new branch. The same problem happens when someone does a small change using Github UI since it also creates a branch here.
This avoids the double build by limiting which branches are built. Only stable-maintained branches and release tags have builds.

Configure travis to build only stable branches and tags

---

.travis.yml

The main purpose is to get notifications for cron builds since they currently failing without any notification.

Update Slack notification for Travis builds

---

.travis.yml

Backports #9132
Replaces faulty #9136

[2.7] Configure travis to build only stable branches and tags

---

scripts/scriptLib

Strange enough, sbt wasn't reading the second -D option, but it was using the whole string "2.5-20190325-231121 -Dakka.http.version=10.1.7" as the akka version.
I guess this was broken since day one.

Split cron build extra opts

---

core/play-integration-test/src/test/scala/play/it/libs/JavaWSSpec.scala
core/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
project/Dependencies.scala

Update Akka to version 2.5.21. This version changes the signature of `scaladsl.Source.asJava`, so some adjustment was necessary for our tests. This pull request also fixes the cron build for 2.6.x branch since it uses snapshots versions of Akka that contains such change.
https://github.com/akka/akka/pull/26246

[2.6.x]: Update to Akka 2.5.21

---

scripts/it-test-scala-212
scripts/it-test-scala-213
scripts/publish-local
scripts/test-docs
scripts/test-sbt-plugins-0_13
scripts/test-sbt-plugins-1_0
scripts/test-scala-212
scripts/test-scala-213
scripts/validate-code
scripts/validate-docs
scripts/validate-microbenchmarks

Fix was applied to `2.7.x` branch already during backporting (but never made it into `master` branch), see last commit here:
https://github.com/playframework/playframework/pull/9027/commits

Fix source of shellcheck cmd

---

persistence/play-java-jdbc/src/main/java/play/db/DefaultDatabase.java
persistence/play-jdbc-api/src/main/java/play/db/Database.java
project/BuildSettings.scala

This method was deprecated in 2.6.0

Removed deprecated method Database.toScala()

---

core/play-integration-test/src/it/scala/play/it/server/ServerReloadingSpec.scala
documentation/manual/releases/release27/migration27/Migration27.md
project/Dependencies.scala

This version has a new configuration that enables/disables an internal cookie store that is persistent across multiple requests to the same hosts. By default, it is disabled.
- https://github.com/playframework/play-ws/pull/307
- https://github.com/playframework/play-ws/pull/313

Update Play-WS to version 2.0.3

---

core/play/src/main/scala/play/api/mvc/BodyParsers.scala
project/BuildSettings.scala

These methods was deprecated in 2.6.0

Removed deprecated BodyParsers.urlFormEncoded

---

core/play/src/main/scala/play/api/http/StandardValues.scala
core/play/src/main/scala/play/api/mvc/Results.scala
project/BuildSettings.scala

This fileld was deprecated in 2.6.0

Removed deprecated TOO_MANY_REQUEST field

---

scripts/it-test-scala-212
scripts/it-test-scala-213
scripts/scriptLib
scripts/test-docs
scripts/test-sbt-plugins-0_13
scripts/test-sbt-plugins-1_0
scripts/test-scala-211
scripts/test-scala-212
scripts/validate-docs
scripts/validate-microbenchmarks

The main reasons are:
1. Akka does not have snapshot artifacts for Scala 2.11 and 2.13, so tasks
that are cross running will fail.
2. Using the snapshots for some tasks is pointless, for example, mima binary
compatibility check
I'm starting with 2.7.x branch because it also includes Scala 2.11, so it will be easier to forward port.
Better to merge and backport #9124 first.

[2.7.x]: Avoid using Akka and Akka HTTP snapshots for all build tasks

---

core/play/src/main/java/play/mvc/Result.java
core/play/src/test/java/play/mvc/ResultsTest.java

Result.as must also copy flash, session and cookies data

---

.travis.yml

Disable building the master, 2.7.x and 2.6.x branches.  This avoids that
every merge into those branches kicks off a build.  This isn't necessary
because we use Mergify's ["strict merge workflow"][] which means the PR
is up-to-date with the target branch before it gets merged.  As an
additional safe-guard I've changed the branch protection in GitHub to
require PRs to be up-to-date before merging, also.
["strict merge workflow"]: https://doc.mergify.io/strict-workflow.html

Disable branch builds

---

documentation/manual/ModuleDirectory.md

Removes deprecated module `zalando` and promotes `iheartradio` at the top of the list (since it's the most well-maintained).

Updates swagger list

---

project/BuildSettings.scala

The inherited settings for `PlayNonCrossBuiltProject` include multiple values on `crossScalaVersions`. I don't think this makes sense considering these are settings for non-cross built projects.
I've made the override here and not `play/interplay` because the making the change there required creating a new `AutoPlugin` for `NonCrossBuild` and override this setting and ... 
The idea of `NonCrossBuild` seems to only exist in play itself so this hack seems fine.

PlayNonCrossBuiltProject were inheriting multiple scala versions.

---

project/BuildSettings.scala

Before the build was using Scala 2.12.7 for scalaVersion but 2.12.8 in crossScalaVersions. This is a follow up of #9189 to fix problems in our release process.

Use a consistent version of Scala

---

.github/settings.yml
.mergify.yml

We have learned that Mergify backports doesn't work well with squash merges, therefore, in order to benefit of backports and forward porst, we need to modify our strategy and move to merge commits.

Let mergify takes care of backports

---

.travis.yml
core/play-integration-test/src/it/scala/play/it/test/OkHttpEndpointSupport.scala

The job "Run it tests for Scala 2.12 and Java 11" is failing: https://travis-ci.com/playframework/playframework/jobs/192016513
This tasks tracks fixing those issues and enforcing that it doesn't regress by removing the `allow_failures` for Java 11.
Fixes #8829

Fix integration tests on Java 11 & enforce

---

project/Docs.scala

This was not including documentation files since the directory changed when unnesting /framework/.

[2.7.x]: Fix play-docs artifact generation

---

core/play/src/main/java/play/mvc/StatusHeader.java
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/main/scala/play/api/mvc/RangeResult.scala
core/play/src/test/java/play/mvc/RangeResultsTest.java
core/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaStream.java
documentation/manual/working/scalaGuide/main/async/code/scalaguide/async/scalastream/ScalaStream.scala

Have a look at the answers here: https://stackoverflow.com/q/7226588/810109
I think it's better and safer to rely on `Files.size(...)`.

Using Files.size(...) should be safer than file.length()

---

version.sbt

The latest release was finished manually, so there was no
step to update the version to add `-SNAPSHOT`.

[2.6.x]: Fix version after release

---

core/play/src/main/java/play/libs/typedmap/TypedMap.java

[warn] /d/play/core/play/src/main/java/play/libs/typedmap/TypedMap.java:102:1: unchecked cast
[warn]   required: play.libs.typedmap.TypedKey<java.lang.Object>
[warn]   found:    play.libs.typedmap.TypedKey<capture#1 of ?>
[warn]       newUnderlying = newUnderlying.updated(((TypedKey<Object>) e.key()).asScala(), e.value());

Avoid an unchecked cast warning

---

core/play/src/main/resources/play/reference-overrides.conf

Fixes #7242.
General Akka performance tweaks shouldn't be the scope of reference overrides so
let's remove them.
No one remembers the original reason why maximum number of threads was limited, so
let's go of that.
Setting LIFO mode is just a speculation that this might be better and that users actually
care more about throughput than about latency and fairness. It's not Play's job to make
that call.
`parallelism-factor = 1.0` is indeed a very useful default for now but Akka hasn't dared to
change it yet (but will for 2.6). So, let's keep that for now.

Get rid of some extra Akka "performance" tweaks, refs #7242

---

core/play/src/main/scala/play/api/Logger.scala

1. Make use of Option#fold
2. Make logger a def
Making `logger` a val makes it an initialisation hazard, and doesn't
seem necessary (it can still be defined _by_ a val).

Cleanup LoggerLike

---

cache/play-cache/src/main/java/play/cache/AsyncCacheApi.java
cache/play-cache/src/main/java/play/cache/DefaultAsyncCacheApi.java
cache/play-cache/src/main/java/play/cache/DefaultSyncCacheApi.java
cache/play-cache/src/main/java/play/cache/SyncCacheApi.java
cache/play-cache/src/main/java/play/cache/SyncCacheApiAdapter.java
cache/play-caffeine-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
cache/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
core/play/src/main/java/play/libs/Files.java
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/java/play/mvc/Result.java
core/play/src/main/scala/play/api/libs/Files.scala
core/play/src/main/scala/play/core/j/JavaHelpers.scala
core/play/src/test/java/play/mvc/ResultsTest.java
core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java
documentation/manual/working/javaGuide/main/cache/code/javaguide/ehcache/JavaEhCache.java
documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
project/BuildSettings.scala

Fixes #8344
For Play 2.7 we had to rename some methods because their return types changed.

Renamed methods back to their original names

---

core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/java/play/mvc/Result.java
core/play/src/main/scala/play/core/j/JavaHelpers.scala

`Result.withLang(...)` should also take a `String` and a `Locale`, which makes it more comfortable to work with (specially for writing tests).
We have the same already for `Request.withTransientLang`:
https://github.com/playframework/playframework/blob/69844601c616de09292d94d21cf525638f88034f/core/play/src/main/java/play/mvc/Http.java#L1106
https://github.com/playframework/playframework/blob/69844601c616de09292d94d21cf525638f88034f/core/play/src/main/java/play/mvc/Http.java#L1118
https://github.com/playframework/playframework/blob/69844601c616de09292d94d21cf525638f88034f/core/play/src/main/java/play/mvc/Http.java#L1130
And for `RequestBuilder.transientLang`:
https://github.com/playframework/playframework/blob/69844601c616de09292d94d21cf525638f88034f/core/play/src/main/java/play/mvc/Http.ja …

Overload Result#withLang

---

core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
core/play/src/main/java/play/mvc/Http.java
web/play-java-forms/src/test/scala/play/data/FormSpec.scala

I was missing such a method a couple of times already, specially for [`play.mvc.HttpTest`](https://github.com/playframework/playframework/blob/master/core/play-java/src/test/java/play/mvc/HttpTest.java), where you always have to create and set the cookie yourself. 
I will refactor `HttpTest` and get rid of `Http.Context` in one of my next PRs.

Add RequestBuilder.lang(...) helper to set language cookie

---

core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/java/play/mvc/Result.java

Backports #9304 and #9303 (without the deprecations)

[2.7.x] Add RequestBuilder.lang(...) and Result.withLang(locale,...)

---

documentation/manual/ModuleDirectory.md

Updated the URL to the Reactive Mongo plugin page.
Replaces the current link to the Reactive Mongo documentation page with the latest one.
The [existing URL](http://reactivemongo.org/releases/0.11/documentation/tutorial/play2.html) to the Reactive Mongo plugin points to a page with information for Play 2.4 but not the latest versions. The [updated URL](http://reactivemongo.org/releases/0.1x/documentation/tutorial/play.html) includes guides for Play 2.5, 2.6 and 2.7.

Updated the URL to the MongoDB ReactiveMongo Plugin page

---

project/AkkaSnapshotRepositories.scala

(cherry picked from commit e67a050301f84c5841b5a383684aa84b3fb87d95)
Forwardport of #9322

Fix the akka-http snapshots repo

---

core/play/src/main/java/play/mvc/Results.java
core/play/src/main/java/play/mvc/StatusHeader.java

Just small refactoring, no behaviour changes.
In `Results` we reuse the methods from `StatusHeader` everywhere except in the methods I changed in the pull request. Therefore I also added `sendBytes` and `sendByteString`.
This pull request is a prerequisite for my next pull request(s) where I will add/overload more method(s) in these classes.

Refactoring Java's Results and StatusHeader class

---

project/Release.scala
scripts/it-test-scala-212
scripts/it-test-scala-213
scripts/publish-local
scripts/scriptLib
scripts/test-docs
scripts/test-sbt-plugins-0_13
scripts/test-sbt-plugins-1_0
scripts/test-scala-212
scripts/test-scala-213
scripts/validate-docs
scripts/validate-microbenchmarks

Note how the akka and akka-http version overrides move from the removed
runSbtWithSnapshots function to the runSbt function.  This makes it so
all executions of runSbt use the snapshots (when set).
Play-half of https://github.com/playframework/play-meta/issues/79.

[2.7] Enable Akka 2.5 snapshots, including for Scala 2.13, in all CI tasks

---

core/play/src/main/scala/play/api/mvc/BodyParsers.scala

Fixes the need to use the `tolerantJson` `BodyParser`, and then validate the `JsValue`
`BodyParser`s are great to parse request bodies. The `tolerantJson` is currently lacking the option of passing a `json.Reads` similarly to the `json` `BodyParser`. This PR remediates this issue. 
I extracted most of the logic from the `json` `BodyReader`. This removes the need to duplicate logic. 
Not that I am aware.

BodyParser to parse json content given a json.Reads

---

core/play/src/main/java/play/mvc/StatusHeader.java
core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/test/java/play/mvc/ResultsTest.java
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala

In Play Java it's possible to skip the `; filename=...` part in the `Content-Disposition` header:
https://github.com/playframework/playframework/blob/625514b218d5f63c27cab0d8f21e8da5d77ab44d/core/play/src/main/java/play/mvc/StatusHeader.java#L564-L567
However right now the `resourceName` `Optional` is always non-empty because it's created with `of(...)` instead with `ofNullable`. So explictly passing `null` as filename will fail with an exception instead of just skipping that header part.
Along the way I also changed the Scala version to also use `Option` params and made it possible to skip the filename header part as well.
This pull request is a prerequisite for upcoming pull requests which fix stuff related to sending resources.

Don't require filename when sending resource

---

scripts/scriptLib

Latest Akka HTTP (10.1.x) is cross-built for Scala 2.13.0-RC2, for which
there are no Akka 2.5 builds.  So we'll fix how we determine which is
the latest version of Akka HTTP by looking specifically in the 2.13.0-M5
metadata.  And, in a similar vein, do that for Akka too.

[2.7.x] Fix nightlies by looking for latest 2.13.0-M5 releases

---

dev-mode/sbt-plugin/src/main/scala-sbt-1.0/play/sbt/run/PlayRunCompat.scala

Fixes #9368.
Fix sbt parsing version in PlayRun to also handle RC and Milestone versions.

Fix sbt version parsing for RC and M versions

---

core/play/src/main/scala/play/api/libs/concurrent/Akka.scala

The changes are for the issue ActorSystemProvider should accept a List of Setup #9106.
Changes are needed to add health check setups
Fixes #9106

Overloaded ActorSystemProvider.start to accept a List[Setup]

---

scripts/scriptLib

There're a few different issues with scala cross-versioning right now,
with Akka HTTP upgrading to 2.13.0-RC3 and Akka being on slightly
different versions for 2.5.x and 2.6.x.  Right now Play master is using
Scala 2.13.0-RC2 (and Akka 2.6), so we'll use that as the key to lookup
"latest".
NO backport (fixed separately, and differently, on 2.7.x).
Fixes https://github.com/playframework/play-meta/issues/79

Fix master nightlies by looking for latest 2.13.0-RC2 releases

---

.mergify.yml
.travis.yml

To avoid having merge commits made by `mergify[bot]` which conflicts with CLA bot.

Remove strict behavior from Mergify

---

documentation/manual/working/scalaGuide/main/i18n/ScalaI18N.md
project/Docs.scala

In messages.default the default messages for forms validation are defined. 
In order to overwrite the validation messages with language-specific messages, you need to know under which alias the messages are defined.
The reference might save users some time searching for the aliases that play uses.

reference messages.default in ScalaI18N.md

---

core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/templates/Templates.scala
core/play/src/main/scala/views/helper/Helpers.scala
core/play/src/main/scala/views/helper/checkbox.scala.html
core/play/src/main/scala/views/helper/select.scala.html
core/play/src/test/resources/messages
core/play/src/test/scala/play/api/data/FormSpec.scala
core/play/src/test/scala/play/api/templates/TemplatesSpec.scala
core/play/src/test/scala/views/html/helper/HelpersSpec.scala
web/play-java-forms/src/main/java/play/data/Form.java

Manually backporting #9385 because `Form.scala` had conflicts (other files no problem).

[2.7.x] Fix i18n handling for forms

---

core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/templates/Templates.scala
core/play/src/main/scala/views/helper/Helpers.scala
core/play/src/main/scala/views/helper/checkbox.scala.html
core/play/src/main/scala/views/helper/select.scala.html
core/play/src/test/resources/messages
core/play/src/test/scala/play/api/data/FormSpec.scala
core/play/src/test/scala/play/api/templates/TemplatesSpec.scala
core/play/src/test/scala/views/html/helper/HelpersSpec.scala
web/play-java-forms/src/main/java/play/data/Form.java

Fixes #9361 
Remove redundant code (`translateMsgArg`) and instead introduced template helper `translate` which we can re-use everywhere.
Also made sure that the `_text` field for a `checkbox` element and the default value for `select` gets translated. Also `_help` and `_error` field will be translated now.
Added many tests for each use case, plus made sure that everything is escaped correctly.

Fix i18n handling for forms

---

project/Dependencies.scala

Oracle has given JEE to the Eclipse Foundation roughly 1 year ago, and
the project has been renamed Jakarta.
The dependencies were renamed following the guideline of the Eclipse
foundation that can be found here:
https://wiki.eclipse.org/New_Maven_Coordinates.
The new dependencies version are drop-in replacement, but:
- they have a license more business friendly (Eclipse Public License
instead of CDDL + GPL)
- it will be easier to follow the version update with scala steward

Update dependencies javax.* to jakarta

---

core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala

> Have you added tests for any changed functionality?
Yes, there was no test so I added one.
```
[error]   x redirect with a query string (9 ms)
[error]    Some(http://host:port/path?*-._=+%22& "=*-._) != Some(http://host:port/path?*-._=+%22&+%22=*-._) (ResultsSpec.scala:354)
[error] Actual:   ...+%22&[ "]=*-._...
[error] Expected: ...+%22&[+%22]=*-._...
```
```
[info]   + redirect with a query string (3 ms)
```
When constructing a query string using HTML form encoding, this is the algorithm that should be followed: https://url.spec.whatwg.org/#concept-urlencoded-byte-serializer
This requires the same encoding of the key and the value, separated by `=` and then by `&`
At present the caller of `Redirect` has to encode the key before passing it in. We have hit this bug here: …

Correctly encode the key of URL params when redirecting

---

core/play/src/test/scala/views/html/helper/HelpersSpec.scala

Now that #9397 bumps twirl to 1.5.0-M2 - which includes https://github.com/playframework/twirl/pull/226 - I can finally add those test which should have been in #9385 already.

Add more tests to HelpersSpec

---

project/Dependencies.scala

Fixes https://github.com/sbt/sbt/issues/4823
Ref https://github.com/playframework/playframework/pull/9049
The purpose is so play and play applications compile using sbt 1.3.0-RC2, and eventually sbt 1.3.0.
http://repo1.maven.org/maven2/io/netty/netty-transport-native-epoll/4.1.34.Final/netty-transport-native-epoll-4.1.34.Final.pom. Under Linux profile it says:
> The unix-common with classifier dependency is optional because it is not a runtime dependency, but a build time
> dependency to get the static library which is built directly into the shared library generated by this project.
and it makes netty-transport-native-unix-common an optional dependency, but Play directly uses `io.netty.channel.unix.UnixChannelOption`.
When using sbt 1.3.0-RC2 that uses Coursier, …

Explicitly depend on netty-transport-native-unix-common

---

core/play/src/main/scala/play/api/Play.scala

Setting features on it can be fatal.
So let's defer that operation unless it's strictly needed.

Make Play object's xercesSaxParserFactory lazy

---

core/play/src/main/scala/play/api/Mode.scala
core/play/src/main/scala/play/api/Play.scala

Move play.api.Mode to its own file.  While its an important part of the
API, it shouldn't live above the actual Play object.

Leave Play for play.api.Play

---

version.sbt

Otherwise this breaks the script that runs nightly benchmarks.

Set version back to snapshot

---

build.sbt
documentation/manual/releases/release28/Highlights28.md
project/Tasks.scala

Make it simple to keep other Akka modules added by users in sync with modules used out-of-box by Play.
https://github.com/playframework/play-samples/pull/38#discussion_r300434361

Add Akka version to play.core.PlayVersion

---

web/play-filters-helpers/src/test/scala/play/filters/headers/SecurityHeadersFilterSpec.scala

Fixes unicode arrow char warnings
Fixes unicode arrow char warnings
deprecated since Scala 2.13
https://github.com/scala/scala/commit/9e264483d04f48513f3a82e91365667f01a2f5f3

avoid deprecated unicode arrow chars

---

web/play-filters-helpers/src/main/scala/play/filters/HttpFiltersComponents.scala

or was an oversight not to extend `CSPComponents` and include `cspFilter` in `httpFilters` by default ?

Remove unnecessary import

---

core/play/src/main/java/play/mvc/Http.java

Added the item None to Samesite.
Chrome will make samesite default to Lax.
And the old default was defined as None.
https://www.chromestatus.com/feature/5088147346030592

Added "None" to Same-site Cookie

---

core/play/src/main/scala/play/api/templates/Templates.scala
core/play/src/main/scala/views/helper/form.scala.html
core/play/src/main/scala/views/helper/inputDate.scala.html
core/play/src/main/scala/views/helper/inputFile.scala.html
core/play/src/main/scala/views/helper/inputPassword.scala.html
core/play/src/main/scala/views/helper/inputText.scala.html
core/play/src/main/scala/views/helper/script.scala.html
core/play/src/main/scala/views/helper/style.scala.html
core/play/src/main/scala/views/helper/textarea.scala.html
core/play/src/test/scala/views/html/helper/HelpersSpec.scala

Fixes Symbol literal warnings
Fixes Symbol literal warnings
Symbol literal deprecated since Scala 2.13
- https://github.com/scala/scala/releases/tag/v2.13.0
- https://github.com/scala/scala/commit/f46fc7e49058352ff2ac5e843c343e24d0ee6e3c

avoid deprecated Symbol literal

---

core/play/src/main/scala/play/api/Configuration.scala
core/play/src/test/resources/reference.conf
core/play/src/test/scala/play/api/ConfigurationSpec.scala
documentation/manual/releases/release28/migration28/Migration28.md

Noticed this while reviewing https://github.com/playframework/playframework/pull/9390. See details here: https://github.com/playframework/playframework/pull/9390#discussion_r304668348

Always use System Properties when loading Configuration

---

.mergify.yml

Working in conjunction with #9482, which will also get backported.

Disable Mergify's strict merging mode

---

core/play/src/main/resources/play/reference-overrides.conf
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/configuration/ThreadPools.md
documentation/manual/working/commonGuide/configuration/code/ThreadPools.scala

The configuration `parallelism-factor = 1.0` is the new default in Akka
so it, and the rest of the overriding section, can go.
Fixes #9276

Fixups & docs for Akka 2.6's default dispatcher

---

documentation/manual/working/javaGuide/main/cache/code/javaguide/cache/JavaCache.java

Use the same block method other stable tests are using.

Fix JavaCache flaky test

---

core/play/src/main/scala/play/api/Play.scala
core/play/src/test/scala/play/api/PlayGlobalAppSpec.scala

Play.privateMaybeApplication should return Failure instead of sys.error which throws an exception
No related issue, but I can open one if necessary.
This fix is more important for Play 2.7.x since Play.current/maybeApplication/unsafeApplication were already removed in master, but still is more correct to respect the signature and return a Failure than throw an exception.
With this fix `Play.maybeApplication` returns a None instead of throwing an exception
Introduced in https://github.com/playframework/playframework/pull/8462

Play.privateMaybeApplication should return Failure instead of sys.error

---

core/play/src/main/java/play/BuiltInComponentsFromContext.java
core/play/src/main/resources/reference.conf
core/play/src/main/scala/play/api/Application.scala
core/play/src/main/scala/play/api/libs/Files.scala
core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
project/BuildSettings.scala

Resolves #9066
The optional configuration key `play.temporaryFile.dir` can now be used to define the temporary file directory. When absent, the temporary file directory will default to `java.io.tmpdir` as per existing behaviour.
Unit test has been added to ensure correct behaviour, and existing tests have been updated.

Add configuration for temporary file directory

---

cache/play-caffeine-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
cache/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
core/play-integration-test/src/it/scala/play/it/http/JavaCachedActionSpec.scala
core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
core/play-integration-test/src/it/scala/play/it/mvc/FiltersSpec.scala
core/play-streams/src/test/scala/play/api/libs/streams/AccumulatorSpec.scala
core/play-streams/src/test/scala/play/api/libs/streams/ExecutionSpec.scala
core/play-streams/src/test/scala/play/libs/streams/AccumulatorSpec.scala
core/play/src/main/scala/play/api/libs/Files.scala
core/play/src/main/scala/play/api/mvc/Action.scala
core/play/src/main/scala/play/core/utils/HttpHeaderEncoding.scala
dev-mode/play-docs/src/main/scala/play/docs/DocumentationHandler.scala
transport/server/play-server/src/main/scala/play/core/server/Server.scala

It can be done now since we drop Scala 2.11. :-)

Use single abstract methods where it improves code readability

---

core/play-streams/src/main/scala/play/api/libs/streams/GzipFlow.scala

Polling more data than `chunkSize` on each `onPush` fill the `buffer` faster than it gets emptied. This situation gets worse when `chunkSize` is small.
If the buffer contains more than `Int.Max` element a `ByteString` with negative size is produced leading to obvious error downflow. 
The error produces downflow :
```
a.a.RepointableActorRef - Error in stage [akka.stream.impl.io.compression.CompressionUtils$$anon$1@685b613b]: null
java.lang.NegativeArraySizeException: null
at scala.reflect.ManifestFactory$ByteManifest.newArray(Manifest.scala:93)
at scala.reflect.ManifestFactory$ByteManifest.newArray(Manifest.scala:91)
at akka.util.ByteIterator.toArray(ByteIterator.scala:464)
at akka.util.ByteString.toArray(ByteString.scala:729)
at …
```

Avoid gzip buffer overflow when dealing with big file.

---

documentation/build.sbt
documentation/project/CrossJava.scala

With the previous setup I was getting an exception because my
`fullJavaHomes` doesn't have an entry for "8".  This is because the
discovery that sbt does to set `fullJavaHomes` is very flaky, so I added
a fallback of using "system@8" as the key for the Java 8 home (a naming
convention in Jabba that sbt "discovers").
But then I also changed `sourceAndTarget` so it just ignores the
possibly-missing Java home if on JDK 8 already.
I also cleaned up a bit: deleted the unused crossJavaSettings, deleted
the duplicate keys that are in sbt proper, and I changed the package to
`playbuild` as this isn't Akka (and this code isn't part of Play, it's
part of Play's build).

Fix doc compilation using GraalVM

---

core/play/src/main/java/play/mvc/StatusHeader.java
core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/test/java/play/mvc/ResultsTest.java
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/javaGuide/main/async/JavaStream.md
documentation/manual/working/scalaGuide/main/async/ScalaStream.md

According to [RFC 6266 Section 4.2](https://tools.ietf.org/html/rfc6266#section-4.2) there is absolutely no need to send the header `Content-Disposition: inline`:
> On the other hand, if it matches "inline" (case-insensitively), this **implies default processing**. Therefore, **the disposition type "inline" is only useful when it is augmented with additional parameters**, such as the filename...
That should already be enough proof to skip this header, but here is a reference to the MDN web docs as well, [which also clearly state](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Disposition#As_a_response_header_for_the_main_body) that `inline` is the default:
> The first parameter in the HTTP context is either inline (**default value**, indicating it can be displayed …

No need to send "Content-Disposition: inline" header

---

project/BuildSettings.scala

This should speed-up the scripted tests, by ~9s each.  So at 31 scripted
tests that's ~4m39s saved each time.
For context: by default scripted will give each scripted test an
isolated sbt "global directory", which by default is ~/.sbt.  This is
(sometimes) great for sbt's own tests, to avoid existing file state from
hiding the introduction of bugs, when developing sbt.
But when developing a plugin it's entirely wasteful.
Let's reuse the user's ("global") boot directory.
I tried using something more indirect, re-using sbt's own settings
and/or API.  But that turned out to be hard (e.g. can't access
state.value in scriptedLaunchOpts, because its a task in a setting) and
mostly unnecessary (turns out that sbt doesn't use the
scalaProvider.launcher.bootDirectory, like it should... -.-), so …

Reuse the compiler bridges in the user's boot dir

---

core/play/src/main/java/play/mvc/StatusHeader.java
core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/test/java/play/mvc/ResultsTest.java
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala
documentation/manual/working/scalaGuide/main/tests/code/webservice/ScalaTestingWebServiceClients.scala

The Scala API has the same since a very long time already: #203, even though [it was broken](https://github.com/playframework/playframework/issues/6351) for a while, but eventually got fixed again: #6362
Besides of overloading all the `sendFile`, `sendPath` and `sendResouce` methods in the Java API, so every existing method has a variant that takes `..., Runnable onClose, Executor executor`, I also added two more tests to the Scala API ones (also the `sendResource` method in Scala was lacking the feature, so I just added it).

Add onClose callback to Java's sendFile/Path/Resource methods

---

core/play-integration-test/src/it/scala/play/it/http/ScalaResultsHandlingSpec.scala
core/play/src/main/java/play/mvc/Results.java
core/play/src/main/java/play/mvc/StatusHeader.java
core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/test/java/play/mvc/ResultsTest.java
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala
dev-mode/play-docs/src/main/scala/play/docs/DocServerStart.scala
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/scalaGuide/main/async/code/scalaguide/async/scalastream/ScalaStream.scala
project/BuildSettings.scala

From the migration notes I added:
> _Methods for serving files, like `ok(File content, ...)` (and similar) in the [Java API](https://www.playframework.com/documentation/2.7.x/api/java/play/mvc/Results.html#ok-java.io.File-) or `sendFile`, `sendPath` and `sendResource` in both Java's  [`StatusHeader`](https://www.playframework.com/documentation/2.7.x/api/java/play/mvc/StatusHeader.html) and Scala's [`Status`](https://www.playframework.com/documentation/2.7.x/api/scala/play/api/mvc/Results$Status.html) class changed the type of their `filename` parameters: Instead of using a plain `String`, the Scala API now uses an `Option[String]` as return type for its `filename` parameter function. The Java API changed the parameter type to be an `Optional<String>`.            
This API change better …

File serving methods changed the type of their filename parameters

---

dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
documentation/manual/releases/release28/migration28/Migration28.md

Now non-snapshot Play applications won't depend on play-omnidoc by
default, which means, for example, that our seeds and sample apps won't
break in the interim between a playframework/playframework release and a
playframework/omnidoc release (which has additional dependencies - e.g.
scalatestplus-play).
Fixes #9438

Break play+omnidoc's circular dependency

---

documentation/manual/working/javaGuide/main/ws/JavaWS.md
documentation/manual/working/scalaGuide/main/ws/ScalaWS.md

I added "WebService" as an explanation for the abbreviation WS (in "play-**ws**") to both the java and the scala documentation.
Issue: https://github.com/playframework/play-ws/issues/382

Add full name of WS abbreviation to docs

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/app/controllers/HomeController.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/conf/logback.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/conf/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/expected-application-log.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/akka-fork-join-pool/test

Fixes #8167
Fixes #7751
Real fix for #7615
This pull request itself is not the fix. The fix is that Play 2.8 upgrades to akka 2.6. Just read [this comment](https://github.com/playframework/playframework/issues/8167#issuecomment-490645264).
If you run this scripted tests with Play 2.7 you will see that also Java's default common pool will be used (and the test will fail):
```
[DEBUG] controllers.HomeController - ForkJoinPool.commonPool-worker-2
```
Starting with Play 2.8 however that will not be the case anymore. No common pool -> no SecurityExceptions anymore :wink: 
(This scripted test is basically a copy of the [`http-backend-netty-channel-options`](https://github.com/playframework/playframework/tree/c0fb84c769ec215cdf1af475e1e426f51d91ed90/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugi …

Scripted test: Parallel streams use akka FJP threads, not commonPool

---

documentation/manual/working/commonGuide/production/Deploying.md

I went too fast and approved #9607 which supersedes #9587. This PR includes the documentation updates I have done in #9587.

updated links to v1.4.1 release

---

core/play-integration-test/src/it/scala/play/it/i18n/LangSpec.scala
core/play/src/main/scala/play/api/i18n/Langs.scala
documentation/manual/releases/release28/migration28/Migration28.md

Fixes #8953
This fixes i18n locale lookup behavior  for satisfying RFC 4647.
I am developing Japanese language defaulted system which also supports English.
Although i18n setting is below, `Accept-Language: en-GB` does not much `en` and defaults to `ja`.
```
play.i18n.langs = [ "ja", "ja-JP", "en", "en-US" ]
```
I think that following the Language Lookup behavior described in RFC 4647 section 3.4. is preferable for the better i18n support.
* #8953
* [RFC 4647](https://www.ietf.org/rfc/rfc4647.txt)
* https://discuss.lightbend.com/t/play-2-6-i18n-locale-lookup-behavior/3239
Thank you for your taking time 😄

Fix i18n locale lookup behavior

---

core/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
core/play/src/main/scala/play/core/parsers/Multipart.scala

Fixes #6275
When uploading a file with a non ASCII character name, [rfc2184](https://tools.ietf.org/html/rfc2184) should be used. This RFC defines how to encode non ASCII characters in content disposition header. The format is: `key*=charset'language'url-encoded-value`.
The browsers (nor curl) don't use this standard and let the server guess which charset is used to encode filename. The Python (request library) uses extended attribute format if the filename contains non ASCII chars. This make the upload fails.
This PR add the support of the extended attributes in content disposition. Charset is used to decode the value but the language is ignored.
This PR doesn't include the support of value continuation (line wrapping when value is long).
This PR also remove some unnecessary `trim` in …

Fixes #6275 Support rfc2184 extended attribute in multipart disposition

---

core/play/src/main/java/play/mvc/BodyParser.java
documentation/manual/working/javaGuide/main/upload/code/JavaFileUpload.java
project/BuildSettings.scala

Following line in `DelegatingMultipartFormDataBodyParser` is very very nasty:
https://github.com/playframework/playframework/blob/f71d9e1da0a441952c451e27848a35edaebf05d6/core/play/src/main/java/play/mvc/BodyParser.java#L627
Here we pass `maxLength` to create a `multipartParser`... The `maxLength` param, _how we treat it_, is the maximum size of the whole request body that should be allowed for the upload, that's even how we show it [in the example in the docs](https://www.playframework.com/documentation/2.7.x/JavaFileUpload#Writing-a-custom-multipart-file-part-body-parser):
```java
super(materializer, config.parser().maxDiskBuffer(), errorHandler);
```
The docs use `config.parser().maxDiskBuffer()`, which by default is 100M:
https://github.com/playframework/playframework/blob/f71d9e1da0a4 …

Fix "memory leak" in DelegatingMultipartFormDataBodyParser

---

core/play-integration-test/src/it/scala/play/it/http/RequestBodyHandlingSpec.scala
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/server/Server.md
project/BuildSettings.scala
transport/server/play-akka-http-server/src/main/resources/reference.conf
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-netty-server/src/main/resources/reference.conf
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
transport/server/play-server/src/main/resources/reference.conf
transport/server/play-server/src/main/scala/play/core/server/Server.scala

When using Akka HTTP as server backend and making use of `play.server.akka.max-content-length` (by setting it to some byte value instead of [the default](https://github.com/playframework/playframework/blob/2.7.3/transport/server/play-akka-http-server/src/main/resources/reference.conf#L53-L55) `infinite`) and a request comes with a `Content-Length` header whose value exceeds that configured `max-content-length` value, Play will return a HTTP 500 status code right now. Which is wrong, it should be a 413 "request entity too large". Marcos agrees with me: https://github.com/playframework/playframework/issues/8336#issuecomment-440457326 (Also akka-http [did change this recently](https://github.com/akka/akka-http/pull/2395) after [users reported the wrong …

413 instead of 500 when max-content-length exceeds + Netty config

---

core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala

Until now, Scala's file and temporaryFile bodyparser _never_ cared about how much data they parse. Meaning when using these parsers, bad guy can upload as much data as desired, filling up the disk like there is no tomorrow. Because all other parser by default respect the [`maxDiskBuffer`](https://github.com/playframework/playframework/blob/3843d256c8b5635da3eb386152b17218e5fe01b9/core/play/src/main/resources/reference.conf#L108-L109) config, this should apply to these two parser as well. Turns out this behaviour occurs since before even releasing Play 2.0 ([commit](https://github.com/playframework/playframework/commit/2a067fd4d443f707c3f56f0c074b111d742a596d#diff-9138e25f65ebbd50a32f077940baa128R73)) and never was fixed.

Make Scala's file/temporaryFile parser respect max length

---

project/Docs.scala

The last commit in #9521 "fix" the last error in generating Javadoc from the Java sources on Java 11... by not generating any javadoc at all... on any version of Java.
So while I'm still figuring out how to fix that, let's add back "-subpackages play" when generating the api docs on pre-Java 11.

Add back "-subpackages play" on pre-Java 11

---

build.sbt

When adopting Scala 2.13, in order to use latest builds from akka we added this resolver unconditionally.

Removes Akka snaphost resolver

---

project/BuildSettings.scala

Switch to mapping all library jars.

Avoid deprecated ScalaInstance#libraryJar

---

project/Docs.scala

From my testing (running Play-Docs/apiDocs and inspecting the content in
dev-mode/play-docs/target/scala-2.12/apidocs/ and viewing it in the
browser) it appears that before and after nothing changes from no having
this.
I think the intent of "-subpackages x" is that you invoke it like
`javadoc src/liba -subpackages com.acme.liba.foo:com.acme.liba.bar`.
But the way we invoke it is by passing the source files directly, so
javadoc will document all the packages we care about already (which is
the "play" package and every subpackage of it too.)

apiDocs: Drop "-subpackages play"

---

core/play/src/main/scala/play/api/Configuration.scala
core/play/src/test/scala/play/api/ConfigurationSpec.scala
documentation/manual/releases/release28/migration28/Migration28.md

This method is in the new 1.3.5-RC1 version of the config library
(should be released as 1.4.0).
The value added here is that we verify that the reference configuration
is self-containing (i.e. can be resolved) that is: it doesn't make
references to keys that are undefined.

Adopt ConfigFactory.defaultReferenceUnresolved

---

documentation/manual/releases/release28/migration28/Migration28.md
web/play-filters-helpers/src/main/resources/reference.conf
web/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala

Fixes #9208
Along the way I corrected some comments and fixed other bugs as well :wink: 
EDIT: I guess we can backport this to 2.7.

Send HSTS header when X-Forwarded-Proto header is 'https'

---

core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/test/scala/play/api/mvc/MaxLengthBodyParserSpec.scala
core/play/src/test/scala/play/mvc/DummyDelegatingMultipartFormDataBodyParser.java
core/play/src/test/scala/play/mvc/MaxLengthBodyParserSpec.scala

Fixes #8336
This pull request makes sure all the built-in body parsers, no matter if Scala or Java API, check the `Content-Length` header before even trying to parse the body in case its value is exceeded.
This continues the work done in #9625 (which did the same checks, but higher up in the server backends already).
I added exhaustive tests for _all_ built-in body parser, Scala and Java.
(Depends on #9647).

BodyParsers check Content-Length header if it exceeds maxLength

---

documentation/manual/releases/release28/Highlights28.md
project/BuildSettings.scala
web/play-filters-helpers/src/main/resources/reference.conf
web/play-filters-helpers/src/main/scala/play/filters/gzip/GzipFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/gzip/GzipFilterSpec.scala

Fixes #9606
You can now set a treshold via config:
```
play.filters.gzip.threshold = 1k
```
**The question is should we set the threshold to something larger than 0 bytes out-of-the-box?**
E.g. Express.js [uses 1kb by default](https://github.com/expressjs/compression#threshold).
If we do so, we need to add migration notes.
If not, we can backport this pr to 2.7.x straight away without changes.

Add threshold to GzipFilter

---

documentation/manual/working/commonGuide/akka/AkkaClusterSharding.md
documentation/manual/working/commonGuide/akka/AkkaIntegrations.md
documentation/manual/working/commonGuide/akka/index.toc
documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md
documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
documentation/manual/working/commonGuide/server/AkkaHttpServer.md

#9503 introduced more usages of `experimental`.  Instead, prefer using [`incubating`](https://developer.lightbend.com/docs/lightbend-platform/introduction/getting-help/support-terminology.html).
Since the issue affected other existing pages I'm sending a separate PR.
I'm not editing any reference to `experimental` on release notes, highlights or migration guides on purpose.

Prefer incubating over experimental

---

.gitattributes

Original commit:
https://github.com/playframework/playframework/commit/66e80342e4198cd0baff167c19f64098823232a9#diff-fc723d30b02a4cca7a534518111c1a66
Path pointed to this folder back then:
https://github.com/playframework/playframework/tree/2.7.0-M1/framework/src/play-integration-test/src/test/resources/testassets/
This folder does not exist anymore, it was renamed to:
https://github.com/playframework/playframework/tree/master/core/play-integration-test/src/it/resources/testassets/

Fix path in .gitattributes

---

documentation/manual/working/commonGuide/database/AccessingAnSQLDatabase.md
documentation/manual/working/commonGuide/database/code/logback-play-logSql.xml

Having the `logback-play-logSql.xml` where it is now is a bit confusing. It's just used as an example in the documentation, not for Play itself (at least I can not find where it would be used).
@marcospereira You added this file in #4713, that's why I want your thumbs up for this pull request (was it on purpose that you didn't put it in the docs folder?)

Move example logback conf to docs

---

core/play-java/src/main/scala-2.11/play/core/j/JavaImplicitConversions.scala
dev-mode/play-docs-sbt-plugin/src/main/scala-sbt-0.13/com/typesafe/play/docs/sbtplugin/PlayDocsPluginCompat.scala
dev-mode/play-docs-sbt-plugin/src/main/scala-sbt-0.13/com/typesafe/play/docs/sbtplugin/PlayDocsValidationCompat.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/PlayExceptions.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/PlayImportCompat.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/PlayInternalKeysCompat.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/PlaySettingsCompat.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/routes/RoutesCompilerCompat.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/run/PlayReload.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/run/PlayRunCompat.scala
dev-mode/sbt-plugin/src/main/scala-sbt-0.13/play/sbt/test/MediatorWorkaroundPluginCompat.scala
scripts/scriptLib
scripts/validate-code

Fixes #9719 on `2.6.x`.
We may have to manually forward port this to `2.7.x` and `master` but I don't recall seeing this issue on those branches.
I noticed this because of a failure in nightly jobs (vegemite).

Run format and headerCheck on all scala/sbt versions

---

web/play-java-forms/src/main/java/play/data/Form.java
web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala

Now that #9692 fixed the spring bug we can finally make `someFormField.indexes()` behave correctly when used on a `DynamicForm`.

Java's field.indexes() wasn't working for DynamicForm

---

documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/Assets.java
documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/AssetsBuilder.java
documentation/manual/working/commonGuide/build/sbtSubProjects.md

Fixes #9667
The code mentioned in [this file](https://github.com/playframework/playframework/blob/master/documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/AssetsBuilder.java) is displayed in a section named **"Working with subprojects"** of the documentation, which may be found [**here.**](https://www.playframework.com/documentation/2.7.x/sbtSubProjects#Assets-and-controller-classes-should-be-all-defined-in-the-controllers.admin-package) 
The code can't be compiled because there is an inconsistency between the class' name and the constructor. In order to fix this, I changed the name of the class to Assets within the text of the replace annotation.

Eliminated inconsistency between class name and constructor in docs (#9667)

---

core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/test/scala/play/api/mvc/BindersSpec.scala

Adds an instance of QueryStringBindable[Short] which allows to use queryString params with Short type

Added instance for QueryStringBindable[Short]

---

transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala

The `bufferLimit` inside `PlayRequestHandler` is the only config that is fetched via `tryApp.configuration`. This is because of historical reasons (before, as you can see, `play.websocket.buffer.limit` was used, which obvisouly was not availabe via server config (`play.server.*`)).
BTW: The config `"play.websocket.buffer.limit"` [is deprecated since Play 2.6](https://github.com/playframework/playframework/pull/7337/files) already, so I guess it's OK to remove it with 2.8

Pass bufferLimit to PlayRequestHandler instead using tryApp.conf

---

core/play/src/main/scala/play/api/mvc/Security.scala
project/BuildSettings.scala

Remove security traits that were deprecated since 2.6.0
Substitutes available, and this has been deprecated for a while.

Remove deprecated security methods

---

project/BuildSettings.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala

Was used long time ago for [`MaterializeOnDemandPublisher`](https://github.com/playframework/playframework/blob/2.5.0/framework/src/play-streams/src/main/scala/play/api/libs/streams/MaterializeOnDemandPublisher.scala#L47);
https://github.com/playframework/playframework/commit/12732318e4fdca08c9a1f175a9959e2c8a884c3c#diff-591d0c41805033f6b0a185df83b21b9aR137
Not needed anymore since this commit:
https://github.com/playframework/playframework/commit/26e33bc666bc1863ddc9d207428ab87b38e5c724#diff-591d0c41805033f6b0a185df83b21b9aR128

Remove unneeded implicit materializer

---

testkit/play-test/src/test/java/play/test/HelpersTest.java
testkit/play-test/src/test/scala/play/api/test/HelpersSpec.scala

Issue #8632
Fixes #xxxx
The issue that was reported in the issue is actually fixed already. It just seems that there was a test missing, which is now included in this PR.
#8632

Providing a test to show POST request is fired with an empty body

---

core/play/src/main/java/play/BuiltInComponents.java
core/play/src/main/java/play/components/AkkaTypedComponents.java
core/play/src/main/scala/play/api/Application.scala
core/play/src/main/scala/play/api/inject/BuiltinModule.scala
core/play/src/main/scala/play/api/libs/concurrent/Akka.scala
documentation/manual/working/commonGuide/akka/AkkaTyped.md
documentation/manual/working/commonGuide/akka/code/javaguide/akka/components/ComponentsWithTypedScheduler.java
documentation/manual/working/commonGuide/akka/code/scalaguide/akka/components/ComponentsWithTypedScheduler.scala

In Akka 2.6.0, when using Akka Typed and [`ask` pattern](https://github.com/akka/akka/blob/b8636462588ec2f73e264ac6dc3ece5825120e60/akka-actor-typed/src/main/scala/akka/actor/typed/scaladsl/AskPattern.scala#L107-L117), it is necessary to provide a `Scheduler`. To make it easier for users, this adds a new binding for runtime dependency injection and new components for compile-time injection.

Dependency injection support for Akka Typed Scheduler

---

project/BuildSettings.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala

I want this removed, because I _may_ add a param to `runAction` after RC1.

Remove deprecated internal API

---

core/play/src/main/java/play/mvc/RangeResults.java
core/play/src/main/scala/play/api/mvc/RangeResult.scala
core/play/src/main/scala/play/core/j/JavaRangeResult.scala
core/play/src/test/java/play/mvc/RangeResultsTest.java
core/play/src/test/scala/play/api/mvc/RangeResultSpec.scala
documentation/manual/releases/release28/Highlights28.md
documentation/manual/working/javaGuide/main/http/JavaResponse.md
documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaResponse.java
documentation/manual/working/scalaGuide/main/http/ScalaResults.md
documentation/manual/working/scalaGuide/main/http/code/ScalaResults.scala

Apologies that this does not yet include a Java API change or documentation - I will squash that in once someone's had a look to make sure this approach looks sane.
When requesting the very end of a very large file, it can be inefficient to open a file at the start and drop N bytes. This is even more true for data backed by an HTTP API such as S3, where having to download the entire file to serve the last few bytes is extremely inefficient. This allows Source providers to seek directly to the start of the requested range.
Our application stores files in a Swift deployment, and needs to efficiently serve range requests.
By the time ByteStrings are being processed an HTTP response will have already begun, making it too late to implement preseeking at this stage. I've only added a new …

Support RangeResult where the Source provider can pre-seek to the start

---

project/BuildSettings.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala

Please merge this before RC1, I need it for an upcoming pull request. Thank you so much!
`runAction` is not used anywhere outside.
Also the netty equivalent method is just `private`:
https://github.com/playframework/playframework/blob/1851d5d83f388f0510ff642710d609e3e263ab7d/transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala#L288-L293

No need to make method package private

---

documentation/manual/working/javaGuide/main/http/JavaRouting.md

Right now its under `The URI pattern`... That doesn't make sense. IMHO it belongs to `The routes file syntax` - like in the Scala doc: https://www.playframework.com/documentation/2.7.x/ScalaRouting#The-routes-file-syntax

Move docs about route modifier where it belongs

---

core/play-integration-test/src/it/scala/play/it/http/JavaActionSpec.scala
core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/scala/play/api/mvc/Request.scala
core/play/src/test/scala/play/api/mvc/DefaultBodyParserSpec.scala
core/play/src/test/scala/play/mvc/DefaultBodyParserSpec.scala
testkit/play-test/src/test/java/play/test/HelpersTest.java

`hasBody()` must return false for all empty requests, including ones
with a buffer assigned, but not holding any data (buffer size = 0).
This should fix #9757

Make Request.hasBody return false for empty buffers

---

documentation/manual/working/scalaGuide/main/ws/ScalaOpenID.md

This pull request fixes a typo. This typo only exists in the Scala documentation.

Fix typo `openid` -> `openId`

---

core/play/src/main/java/play/server/SSLEngineProvider.java
core/play/src/main/scala/play/server/api/SSLEngineProvider.scala
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/production/ConfiguringHttps.md
documentation/manual/working/commonGuide/production/code/javaguide/CustomSSLEngineProvider.java
documentation/manual/working/commonGuide/production/code/scalaguide/CustomSSLEngineProvider.scala
project/BuildSettings.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-server/src/main/scala/play/core/server/SelfSigned.scala
transport/server/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala
transport/server/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala

This is targeting 2.8.x now, but we can later re-target it to master if we decide too many things are changing.

Refactor SSLEngineProvider to also expose SSLContext

---

project/Dependencies.scala

* update netty to 4.1.43.Final (due to CVE)
* jackson to 2.9.10 (due to CVE)
* jackson-databind to 2.9.10.1 (due to CVE)
* akka-http to 10.1.11
* akka to 2.5.26

[2.7.x] Bump versions before releasing 2.7.4

---

.travis.yml
documentation/manual/releases/release28/migration28/Migration28.md
project/Dependencies.scala
project/plugins.sbt
scripts/test-scripted-13x

Play sbt-plugin should work for sbt 1.2.8 too, so it should not be built for sbt 1.3.4, which 2.8.0-RC2 was.
- https://github.com/lagom/lagom/pull/2479#issuecomment-559851001
- https://github.com/playframework/interplay/pull/99
WIP since it depends on a release of interplay after https://github.com/playframework/interplay/pull/99.

[2.8.x]: interplay 2.1.4 and run scripted tests for sbt 1.3.x

---

core/play-integration-test/src/it/scala/play/it/ServerIntegrationSpecification.scala
core/play-integration-test/src/it/scala/play/it/http/HttpPipeliningSpec.scala
core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala

While the build builds... :-)
This helps to reduce the amount of time our tests take to run for each pull request. The accumulated gain for each pull request (and push) is larger than the upset of delaying the discover that a change broke Netty server backend (something we will only see in nightly builds).
Also, removes some test skippers that aren't used anymore.

Only run Netty integration tests in Travis for cron builds

---

core/play/src/main/scala/play/api/mvc/Session.scala
project/BuildSettings.scala

As reported by @lobax in #9816, when using `Session.decode`, but also any other encode/decode variation, a user will get a runtime error. 
This PR make sure that at least a deprecation warning is emitted whenever a user uses one of the Session methods that rely on deprecated functionally.
Fixes #9816

[2.7.x] Users get a warn when using deprecated functionally in Session

---

core/play-integration-test/src/it/scala/play/it/ServerIntegrationSpecification.scala
core/play-integration-test/src/it/scala/play/it/http/HttpPipeliningSpec.scala

https://travis-ci.com/playframework/playframework/jobs/263296783 failed,
so it would appear those tests should continue to be skipped in CI.

Reinstate skipping HttpPipeliningSpec in CI

---

.scala-steward.conf

We get very often updates for scalafmt that requires a code reformatting. While is nice to have it each time it's adding some unnecessary overhead. 
This PR disable it. We can apply updates from time to time manually when we get to know about any performance improvements or new formatting rule of interest.

Disable scala-steward updates for scalafmt-core

---

documentation/manual/releases/release28/migration28/Migration28.md

Refs #9902 
Targets `2.8.x` so it's removed from the published site asap.

Removes reference to noop settings

---

.travis.yml
scripts/publish-local

https://docs.travis-ci.com/user/using-workspaces/
Caches are meant to be a optimisation only, while workspaces are
intended for sharing files within a build.
The motivation for this change is to address the cache poisoning that
was occuring with cron builds publishing a SNAPSHOT version of Play
while depending on an Akka snapshot version, which was failing the
scripted stage of PR validation because they didn't use Akka's snapshot
resolver.

Switch publishLocal to use Travis CI workspaces

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsReaderSpec.scala

Avoids:
[error]    java.lang.ClassCastException: class org.slf4j.helpers.SubstituteLogger cannot be cast to class ch.qos.logback.classic.Logger (org.slf4j.helpers.SubstituteLogger and ch.qos.logback.classic.Logger are in unnamed module of loader 'app') (LogbackCapturingAppender.scala:19)
[error] play.api.db.evolutions.LogbackCapturingAppender.<init>(LogbackCapturingAppender.scala:19)
[error] play.api.db.evolutions.LogbackCapturingAppender$.attachForLogger(LogbackCapturingAppender.scala:62)
[error] play.api.db.evolutions.LogbackCapturingAppender$.apply(LogbackCapturingAppender.scala:51)
[error] play.api.db.evolutions.EvolutionsReaderSpec.$anonfun$new$3(EvolutionsReaderSpec.scala:16)
[error] play.api.db.evolutions.EvolutionsReaderSpec.withLogbackCapturingAppender(EvolutionsReaderSpec.scala:6 …

Fix slf4j/logback issue in EvolutionsReaderSpec

---

documentation/manual/working/javaGuide/main/http/JavaSessionFlash.md
documentation/manual/working/javaGuide/main/http/code/javaguide/http/JavaSessionFlash.java
documentation/manual/working/scalaGuide/main/http/ScalaSessionFlash.md
documentation/manual/working/scalaGuide/main/http/code/ScalaSessionFlash.scala

This is a documentation change to make the behavior of session/flash clearer and recommend use of redirects to see the updated states.
This is a common problem, and the documentation makes this more confusing by using Ok() and not being explicit about what happens when you modify session data.
* https://discuss.lightbend.com/t/session-issue-on-withsession-method/4596/5

[doc] Add info on redirects with session

---

core/play/src/main/resources/reference.conf

The mime type `application/wasm` is required by [`WebAssembly.instantiateStreaming`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming).
* [Browser support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WebAssembly/instantiateStreaming#Browser_compatibility): Stable versions of Chrome, Firefox and Edge
* Specification: https://github.com/WebAssembly/design/blob/master/Web.md#webassemblyinstantiatestreaming
* Intent to register: https://github.com/WebAssembly/spec/issues/573

Add application/wasm mime type to reference.conf

---

transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala

Introduce a DevServerStart _class_ with most of the logic, so it can be
re-used by Lagom in place of its "LagomReloadableDevServerStart".

Consolidate DevServerStart with Lagom

---

core/play/src/main/scala/play/api/Configuration.scala
core/play/src/test/scala/play/api/ConfigurationSpec.scala

See the in-line comments for details.
This re-introduces some logic that had been removed in
1b69712bb4df23f7dd6b194e06dbc3c96c2617ed.
Fixes #9972.

Avoid -Dconfig.resource from killing dev-mode.

---

documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md

This PR updates ScalaAkka.md
I believe the word `on` is missing from the following sentence
> Let's say you have the following actor, which depends **on** configuration to be injected, plus a key:
Documentation. Adds a missing word to ScalaAkka.md 
Fix a sentence with a missing word.
N/A
N/A

Update ScalaAkka.md to add missing word

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala

Fixes #9839
In MySQL/MariaDB the statement `set innodb_lock_wait_timeout = 1` is used, which obviously is not a (select) query and therefore causes an exception. Using just `query` is safe here because we don't care about what gets returned by the used method.

Use execute instead of executeQuery to lock evolutions

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsSpec.scala

While looking at the evolutions source I found a potential problem: Since #5485 it is possible to configure the db schema in which the generated evolution and lock tables will be saved to via the `play.evolutions.schema` config. As you can see in #5485 this was done by introducing the placeholder `${schema}` for those table's ddl scripts. However the implementation was dirty, because `${schema}` also gets replaced in the user defined sql scripts (1.sql, 2.sql,...) Neither was it the intention of that pull request, nor is that string substition documented. Therefore I fixed that now.
BTW: I will introduce a real string substition mechanism for evolutions files soon, because I needed this already for a client project and it would make evolutions more useful IMHO.

Don't substitute string "${schema}" in evolution files

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
project/BuildSettings.scala

`dbConfig` already has all the information needed.

Remove redundant params in runEvolutions

---

.sbtopts
.travis-jvmopts

Without those, on my machine (both jdk8 and jdk11),
'sbt clean +publishLocal' would run out of memory throwing confusing errors
such as 'java.lang.NoClassDefFoundError: xsbt/DelegatingReporter$PositionImpl$'.
Apparently the JVM heuristics for selecting these values aren't very good yet,
and it would be helpful to supply some reasonable defaults as .sbtopts so new
contributors don't have to deal with this.

Convert .travis-jvmopts to .sbtopts

---

core/play/src/main/java/play/BuiltInComponentsFromContext.java
core/play/src/main/scala/play/api/Application.scala
core/play/src/main/scala/play/api/http/HttpRequestHandler.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/controllers/UsersController.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/startup/Startup.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/startup/StartupModule.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/app/views/index.scala.html
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/changes/2.sql
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/changes/3.sql
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/conf/application.conf
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/conf/evolutions/default/1.sql
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/controllers/UsersController.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/startup/Startup.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/startup/StartupModule.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/app/views/index.scala.html
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/changes/2.sql
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/conf/application.conf
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/conf/evolutions/default/1.sql
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-true/test
documentation/manual/working/scalaGuide/main/application/code/ScalaHttpRequestHandlers.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
transport/client/play-ahc-ws/src/test/scala/play/libs/ws/WSSpec.scala

@gmethvin Check this out.
I implemented your suggestions:
* In DEV mode autoApply now runs evolutions on `ApplicationEvolutions` init. This makes your workaround (where you pretend prod mode) obsolete. However only relevant when autoApply = true.
* Inject the router as `Provider[]`. Relevant for autoApply = false, so controllers won't be initialized before webcommands aren't handled.
I adjusted the existing scripted tests to cover all use cases:
* DB access from controller constructor
* DB access from eager singleton

Remove autoApply handling from EvolutionsWebCommands (DEV mode)

---

project/BuildSettings.scala

This avoids creating artifacts that have the same version number but
depend on a different Akka version.
In particular this is intended to fix the failure at #10047, where
we see a single play version depend on different akka versions. The
theory is that those are play artifacts from different builds.

Create a unique version number when setting akka.version

---

.travis.yml

`--retry` has an exponential backoff, so `5` retries should be good enough.
Fixes #10045.

curl retry when installing jabba on Travis

---

persistence/play-jdbc/src/main/scala/play/api/db/DefaultDBApi.scala

It can cause passwords to be leaked and is recommended against by OWASP.
Fixes #10073. That issue has some more info.

Do not log database URL

---

documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md

Add info on how to keep a websocket connection alive.
Adds a warning to WebSocket docs that Keep-Alive Ping is not yet supported in Play. 
I went down a lot of rabbit holes trying to debug why my WebSocket was always closing, and wanted to ensure others didn't repeat my journey.
https://github.com/playframework/playframework/issues/3861

Update ScalaWebSockets.md: Add Info on Keeping Websockets Alive.

---

core/play-java/src/main/resources/ebean.properties

Remove empty ebean.properties from main project as it causes deprecation warning since ebean v12.2.x
Fixes #10141
Removing empty ebean.properties 
ebean.properties file as it does not belong to this project anymore since version 2.4 and it should be in separated plugin. also, the new version of bean (12.2.x) introduces some changes that causing to have a warning message in the console when the app startup.

Remove empty ebean.properties from main project as it causes deprecat… Fixes #10141

---

core/play/src/main/scala/play/api/inject/Module.scala

Fixes https://github.com/playframework/playframework/issues/8474
add the following message. https://github.com/playframework/playframework/issues/8474#issuecomment-513502897
https://github.com/playframework/playframework/pull/9501

Improve No valid constructors error message to suggest a list of valid constructors

---

.gitignore

In case anyone is using https://scalameta.org/metals/ with this project, this adds the relevant files to `.gitignore` so they won't accidentally be committed.

Add bloop and metals files to .gitignore

---

core/play/src/main/java/play/http/DefaultHttpErrorHandler.java

Allow to override method `fatalErrorMessage(RequestHeader, Throwable)` of the java default error handler to return a meaningful fatal error message.

Allow customization of error message when error handler failed

---

core/play-integration-test/src/it/scala/play/it/libs/json/JavaJsonSpec.scala
documentation/manual/releases/release28/Highlights28.md

Fix Json integration test and 2.8 highlights docs

---

core/play/src/main/java/play/libs/concurrent/HttpExecution.java
documentation/manual/working/javaGuide/main/async/code/javaguide/async/controllers/Application.java

No casting needed anymore (see the docs I updated).
Also the Scala API has to overload (which will be called now), only the Java API is missing it:
https://github.com/playframework/playframework/blob/eede96629f260d5c2a9c361adbaa4a271b456fde/core/play/src/main/scala/play/core/j/HttpExecutionContext.scala#L30

Overload HttpExecution.fromThread with ExecutionContextExecutor param

---

cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineCacheComponents.java

This pull request enables compile-time injection of named caches using Caffeine in Java. Updated name of cache config reflects that in play.api.cache.caffeine.CaffeineCacheComponents.

Set name of default cache config to "play.cache.caffeine"

---

core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/test/scala/play/api/mvc/TextBodyParserSpec.scala
core/play/src/test/scala/play/mvc/TextBodyParserSpec.scala

`tolerantText` needs to make sure it is at the beginning of the byte
buffer every time it retries to decode. This is because previous
decoding attempts may have managed to decode a prefix, in which case,
the byte buffer cursor will no longer be pointing at the front of the
buffer.
This manifests as `tolerantText` potentially "dropping" a prefix off of
the decoded text.
Fixes #10181

Rewind `tolerantText` buffer between failures

---

dev-mode/build-link/src/main/java/play/TemplateImports.java
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

Fixes #9845 
if scala version >= `2.13.0` import `scala.jdk.CollectionConverters._`
else import `scala.collection.JavaConverters._`

import CollectionConverters or JavaConverters based on scala version

---

core/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
project/BuildSettings.scala

This `@varargs` annotation should have been removed in #8832 already, it is a mistake it still exists.
As you cann see here, the `@varargs` of the super class was removed back then:
https://github.com/playframework/playframework/pull/8832/files#diff-d15b4be34e92773af96fd33df2a56f77R75

Remove incorrect @varargs

---

core/play-java/src/test/java/play/mvc/AttributesTest.java
core/play/src/main/java/play/libs/typedmap/TypedEntry.java
core/play/src/main/java/play/libs/typedmap/TypedMap.java
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/scala/play/api/libs/typedmap/TypedEntry.scala
core/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
core/play/src/main/scala/play/api/mvc/Request.scala
core/play/src/main/scala/play/api/mvc/RequestHeader.scala
core/play/src/main/scala/play/core/j/JavaHelpers.scala
core/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
core/play/src/test/scala/play/api/mvc/RequestSpec.scala
core/play/src/test/scala/play/core/test/Fakes.scala
project/BuildSettings.scala

I had a case were this method would be useful. Also there are the `putAll` and `+` methods already on the Java/Scala `TypedMap`s already which take varargs, so we can just pass the varargs param on to them.

Add addAttrs(...) to Request

---

documentation/manual/working/javaGuide/main/json/JavaJsonActions.md
documentation/manual/working/javaGuide/main/json/code/javaguide/json/JavaJsonActions.java

Closes https://github.com/playframework/playframework/issues/10219
I'm not sure if there's a better way to reference `"utf-8"` than creating the string myself. I would have used `Results.UTF8`, but it's `private`. I wonder if it should it be made `protected`?

Document how to return a JSON String

---

core/play/src/main/java/play/libs/concurrent/CustomExecutionContext.java

Adds basically the same method [like we have in `HttpExecutionContext`](https://github.com/playframework/playframework/blob/2.8.1/core/play/src/main/java/play/libs/concurrent/HttpExecutionContext.java#L49-L51) so we can simply call `someCustomEc.current()` to als pass on the classloader easily. IMHO it's just simpler and shorter than wrapping `HttpExecution.fromThread(someCustomEc)` each time.

Add CustomExecutionContext.current()

---

transport/client/play-ws/src/main/scala/play/api/libs/ws/WSResponse.scala

`getBody[BodyReadble] -> body[BodyReadable]`

Method name was outdated in documentation

---

persistence/play-jdbc/src/main/resources/reference.conf
persistence/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
persistence/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala

This makes JMX/thread/logs troubleshooting easier when dealing with many datasources, by overriding the built-in opaque, auto-increment default `HikariPool-xxxx` with a semantic name.
https://github.com/brettwooldridge/HikariCP/blob/HikariCP-3.4.1/src/main/java/com/zaxxer/hikari/HikariConfig.java#L1078-L1102
As far as I can tell, database config names are unique across a Play app instance, and in the case where we have several apps running on the same JVM, it does not seem to be a problem as:
- Threads names don't need to be unique
- I don't see how/why pools of different apps would share the same [metrics registry/trackers](https://github.com/brettwooldridge/HikariCP/blob/a51e6a07e856db5f0bce969d83126a0e4dad676a/src/main/java/com/zaxxer/hikari/HikariConfig.java#L627-L672) (which might …

hikari pool name: default to db config name rather than autoincrement id

---

core/play-integration-test/src/it/scala/play/it/http/IdleTimeoutSpec.scala
project/Dependencies.scala
testkit/play-test/src/main/scala/play/api/test/ServerEndpointRecipe.scala

Backport of #10268
Also upgrades akka to 2.6.5 because that was still missing in the 2.8.x branch.
Also the `withExtraServerConfiguration` method was **not** added to the trait for compatibility reasons (see last commit)

[2.8.x] jetty-alpn-agent 2.0.10, akka-http 10.1.12 and akka 2.6.5

---

documentation/manual/working/javaGuide/main/ws/JavaWS.md
documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/Standalone.java
documentation/manual/working/scalaGuide/main/ws/ScalaWS.md
documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
documentation/manual/working/scalaGuide/main/ws/code/ScalaWSStandalone.scala

This is a documentation workaround for issues like https://github.com/playframework/play-ws/issues/418 where there's an AHC config setting that isn't accessible from the WS config layer.
It adds a note to the documentation, and changes the Scala standalone example to match the Java one.  
It also updates to use `SystemMaterializer` to be compatible with https://github.com/playframework/play-ws/pull/463
I'll add a play-ws PR that covers this in the readme as well.

[doc] Add note to show using AHC client directly

---

documentation/build.sbt
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/releases/release26/Highlights26.md
documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/build/sbtDependencies.md
project/Dependencies.scala
scripts/it-test-scala-212
scripts/test-docs-212
scripts/test-scala-212
scripts/test-scripted-13x

Backports #10217
No change except that in the 2.8.x branch there doesn't exist a `Migration29.md`.

[2.8.x] Scala 2.13.2 / 2.12.11 & sbt 1.3.10

---

core/play/src/main/scala/play/api/libs/Files.scala
core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala

Fixes #10194
The code is the same like in OpenJDK which also uses a `SecureRandom`:
http://hg.openjdk.java.net/jdk/jdk/file/04e3d254c76b/src/java.base/share/classes/java/nio/file/TempFileHelper.java#l55

Make sure Play's temp folder is unique

---

core/play/src/main/java/play/http/JsonHttpErrorHandler.java
core/play/src/main/scala/play/api/http/HttpErrorHandler.scala

Same like #10121, however let's also add this for the JSON error handlers (and for Scala's http error handler, which I forgot in the original pull request).

Allow customization of error message when JSON error handler failed

---

cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineCacheComponents.java
cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineExecutionContext.java
cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineParser.java
cache/play-caffeine-cache/src/main/resources/reference.conf
cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheApi.scala
cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheManager.scala
documentation/manual/working/javaGuide/main/cache/JavaCache.md
documentation/manual/working/scalaGuide/main/cache/ScalaCache.md
project/BuildSettings.scala

`play.cache.dispatcher` will set Caffeine's [internal executor](https://github.com/ben-manes/caffeine/blob/v2.8.1/caffeine/src/main/java/com/github/benmanes/caffeine/cache/Caffeine.java#L281-L303) now.
Fixes #10216

Config to set Caffeine's internal executor

---

web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPReportSpec.scala

The `Unsupported Media Type` error is **not** delegated to the error handler anymore.

Tests for CSP errors, which should be in RFC 7807 format

---

web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPReportSpec.scala

Backport of #10265 but without the method deprecated.

[2.8.x] Tests for CSP errors, which should be in RFC 7807 format

---

core/play-integration-test/src/it/scala/play/it/http/parsing/MultipartFormDataParserSpec.scala
core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/main/scala/play/core/parsers/Multipart.scala
core/play/src/test/scala/play/mvc/DummyDelegatingMultipartFormDataBodyParser.java
core/play/src/test/scala/play/mvc/MaxLengthBodyParserSpec.scala

Slightly modified backport of #10236: Without the config, because that would break binary compatibility and also without the `@deprecation`s of course.
Without the config, users can still write their own custom body parser to allow empty files:
https://github.com/mkurz/play-empty-upload-allowed/blob/master/app/bodyparsers/CustomMultipartFormData.java
and
https://github.com/mkurz/play-empty-upload-allowed/blob/master/app/controllers/HomeController.java#L15

[2.8.x] Allow file uploads with empty body or empty filenames

---

documentation/manual/releases/release27/migration27/Migration27.md

Fixes #9411 (I'm targetting `master` since that's the branch that will get published)

Improve Release27 docs wrt twirl

---

core/play-integration-test/src/it/scala/play/it/http/RequestBodyHandlingSpec.scala
core/play/src/main/java/play/http/HttpErrorHandler.java
core/play/src/main/java/play/http/HttpErrorInfo.java
core/play/src/main/scala/play/api/http/HttpErrorHandler.scala
core/play/src/main/scala/play/api/http/HttpErrorInfo.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
web/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/ScalaCSRFActionSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala

Please read this comment, it should explain the motivation behind this pull request: https://github.com/playframework/playframework/issues/6171#issuecomment-625131455
I tried to keep the `HttpErrorInfo` class as generic as possible, so we can extend it later for other uses cases, maybe one day we want to attach more infos to the request passed to an error handler.
With this pull request I started to add the `HttpErrorInfo` attribute to `onClientErrors` thrown by filters and the server backends for now. We can extend that in later pull requests, if someone comes up with the need for more origin tracking.
For me personally I need to know if the 413 request entity too large came from the server backend or [a body parser](https://github.com/playframework/playframework/blob/2.8.1/core/play/src/ …

Add HttpErrorInfo request attribute to track origins of errors

---

core/play-integration-test/src/it/scala/play/it/http/RequestBodyHandlingSpec.scala
core/play/src/main/java/play/http/HttpErrorHandler.java
core/play/src/main/java/play/http/HttpErrorInfo.java
core/play/src/main/scala/play/api/http/HttpErrorHandler.scala
core/play/src/main/scala/play/api/http/HttpErrorInfo.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
web/play-filters-helpers/src/main/java/play/filters/csrf/RequireCSRFCheckAction.java
web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/ScalaCSRFActionSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala

Manual backport of #10270 because of a small conflict.

[2.8.x] Add HttpErrorInfo request attribute to track origins of errors

---

project/BuildSettings.scala

Fixes #10333 
This PR re-enables cross compilation for `routes-compiler` artfifacts for `2.7.x` branch
Only `2.7.3` currently has `routes-compiler` artifacts built for both `2.12` and `2.13`
See discussion in  #10333 for more insights about the issue and proposed fix
@ignasi35

Re-enabling cross compilation for routes-compiler

---

cache/play-caffeine-cache/src/main/scala/play/api/cache/caffeine/CaffeineCacheApi.scala

Right now you can inject the default cache like:
```java
@Inject
AsyncCacheApi cache;
```
which is equivalent to:
```java
@Inject
@NamedCache("play")
AsyncCacheApi cache;
```
(assuming [the default cache is called `play`](https://github.com/playframework/playframework/blob/2.8.2/cache/play-caffeine-cache/src/main/resources/reference.conf#L24))
I want to have the same for `NamedCaffeineCache`. Right now you always need to use `@NamedCache("play")` to inject the default one. I think this is not necessary and can be made easier. (I need to use `NamedCaffeineCache` to access statistics like: `namedCaffeineCache.synchronous().stats()`)

Support injecting default NamedCaffeineCache

---

build.sbt
project/Tasks.scala

N/A
Makes `akkaHttpVersion` available through `PlayVersion`.
N/A
N/A

Include akkaHttpVersion in PlayVersion

---

core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/test/scala/play/api/mvc/BindersSpec.scala

Fixes #xxxx
This PR fixes incorrect error message produced by implicit `bindableInt` and provides additional specs to confirm that issue is fixed.

Fixes int binder error message and provides specs

---

documentation/manual/working/commonGuide/server/AkkaHttpServer.md
documentation/manual/working/commonGuide/server/code/akka.http.server.sbt
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-akka-http2-support/src/main/resources/reference.conf

In preparation for Akka HTTP 10.2.x. Anyhow, http2AlwaysForInsecure was
not having any real effect at all.
Partial cherry-pick from https://github.com/playframework/playframework/pull/9980
Fixes #10414

Backport: remove usage of deprecated Akka HTTP APIs

---

project/Docs.scala

With sbt 1.4.x, the type is inferred as Optional[Nothing] rather than
Optional[ClassFileManager].
Fixes #xxxx

Add type annotation for Optional.empty

---

core/play-java/src/main/scala/play/core/ObjectMapperModule.scala

Try to ensure the `ObjectMapper` managed by Akka and identified as `"play"` uses the same defaults an `ObjectMapper` provided in Play 2.7.
This is a quick solution we may or may not merge (and just keep as inspiration for users to implement their workaround). The long-term solution is to wait for https://github.com/akka/akka/pull/29797 and set the visibility default for `"play"`'s `ObjectMapper` in `reference-override.conf`; and then, undo the workaround in `ObjectMapperModule` introduced in this PR.
Refs #10523 
see also https://github.com/akka/akka/pull/29797

Restore Jackson visibility defaults

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala

Fixes handling of `AssertionError` from zinc compilation.
I am testing my work project with sbt 1.4.0-RC2 and found that this bug is hiding an exception from zinc and showing this instead:
```
[error] a.a.OneForOneStrategy - java.lang.AssertionError: assertion failed: Created a Compilations with duplicate compilations (of class java.lang.AssertionError)
akka.actor.ActorInitializationException: akka://play-dev-mode/system/Materializers/StreamSupervisor-1/TLS-for-flow-2-1: exception during creation
at akka.actor.ActorInitializationException$.apply(Actor.scala:196)
at akka.actor.ActorCell.create(ActorCell.scala:661)
at akka.actor.ActorCell.invokeAll$1(ActorCell.scala:513)
at akka.actor.ActorCell.systemInvoke(ActorCell.scala:535)
at akka.dispatch.Mailbox.processAllSystemMessages(Mailbox.scala: …
```

sbt-plugin: handle AssertionError from zinc compilation

---

documentation/build.sbt
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/build/sbtDependencies.md

https://github.com/scala/scala/releases/tag/v2.13.4

Scala 2.13.4

---

core/play-integration-test/src/it/scala/play/it/action/FormActionSpec.scala
core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/test/scala/play/api/data/FormSpec.scala
core/play/src/test/scala/play/api/data/FormUtilsSpec.scala
documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleControllerSpec.scala
documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleMessagesSpec.scala
documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
project/BuildSettings.scala
web/play-java-forms/src/main/java/play/data/DynamicForm.java
web/play-java-forms/src/main/java/play/data/Form.java
web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala

Improves #10496 to avoiding using a hardcoded memory limit when binding a request to a form.
Supersedes #10534 and #10539
This PR puts together ideas and code previously pushed to #10534 and #10539 with some extra feedback from offline discussions.

[2.7.x] Let user overwrite limit memory size on form binding

---

core/play-guice/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
core/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java
core/play-guice/src/test/java/play/inject/guice/GuiceInjectorBuilderTest.java

Replace deprecated JUnit-matchers on Hamcrest-matchers in play-guice

---

core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/main/scala/play/api/mvc/Controller.scala
documentation/manual/releases/release27/migration27/Migration27.md
documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
documentation/manual/working/scalaGuide/main/ws/code/ScalaOpenIdSpec.scala
project/BuildSettings.scala

Follow-up to #10543
Relocating the default implicit means user code will, in most cases, be source-compatible. Controllers code should be source compatible and unit tests for forms may require the manual addition of the implicit (as documented in the migration guide in #10543 ).

Provide a formBinding out of the box

---

project/Dependencies.scala

This version brings the Scala 2.10 artifact back so it works with sbt 0.13.
https://github.com/playframework/play-file-watch/releases/tag/1.1.14

Play File Watch 1.1.14 (was 1.1.13) for sbt 0.13

---

core/play/src/main/scala/play/api/mvc/Controller.scala

When adding `defaultFormBinding: FormBinding` as a `val` we introduced a circular dependency on DI for users of  `InjectedController` (which is discouraged).
The problem becomes more apparent because webjars-play provides some tools which use `InjectedController`.
See https://travis-ci.com/github/playframework/play-samples/jobs/457151496
Note this issue affects both Java and Scala users as long as there's an intermediate piece on the DI cake that uses `InjectedController` and even if there's not use of forms.
This fixes a regression introduced in Play `2.8.6` and `2.7.8`.

Makes val lazy to prevent circular dependency on DI

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/src/main/scala/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/test

To be backported to 2.8.x
Fixes #10334
make test less flakey

shutdown-happy-path: make test more reliable

---

web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala

The original implementation split at the first possible colon (:), which works fine until you use IPv6 IPs as hosts, which contain at least 2 additional colons. The new implementation splits only on the last colon, the rest of the logic has been kept unchanged. A test reproducing the problem and confirming the fix has been added.
No issue to reference. I found this problem today and fixed it.
It fixes the AllowedHostsFilter to accept IPv6 addresses in the form of `[::]:9000`.
The original implementation's assumption that the port will be separated by the only colon breaks with IPv6, I correct the assumption to: The port is separated by the last colon. This allows to keep the rest of the logic completely untouched.
No

Correct the HostMatcher logic to get host and port

---

core/play-java/src/main/java/play/libs/Time.java

There are many cases manual boxing/unboxing in the class play.libs.Time.java . It is not necessary. [Documentation](https://docs.oracle.com/javase/8/docs/technotes/guides/language/autoboxing.html)
>  When you take the object out of the collection, you get the Integer that you put in; if you need an int, you must unbox the Integer using the intValue method. All of this boxing and unboxing is a pain, and clutters up your code. The autoboxing and unboxing feature automates the process, eliminating the pain and the clutter.
Kind regards

Remove  manual boxing/unboxing between objects and primitives in play.libs.Time.java

---

dev-mode/play-docs/src/main/scala/play/docs/DocumentationHandler.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala

There are some repeated strings for config property names in ApplicationSecretGenerator. Maybe it will be better to use constants.
Kind regards

Use constants for config properties in ApplicationSecretGenerator

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
project/BuildSettings.scala

Fixes classloader memory leak, due to `ClassTag`
Launches scripted tests with a limited metaspace size. With this change most of the tests fail. After analyzing the heap dump in yourkit profiler, one can see that `ClassTag#cache` is not allowing the classloaders created by play to be GCd. 
The fix is to separate the classloader that loads ClassTag from the classloaders that load the rest of the application classes (libraries and user code), and then the classloaders can be GCd.
I also opened a PR in scala (https://github.com/scala/scala/pull/9276/), but I also managed to fix it in play-plugin. As you can see in that PR discussion this is not a problem in scala 2.13, but the scripted tests only run with scala 2.12
#9935
https://github.com/scala/scala/pull/9276/

Fix classloader memory leak, due to ClassTag

---

core/play/src/main/scala/play/api/http/HttpErrorHandler.scala

Fixes #9020
If `application.conf` is invalid the error handler will be called. So far so good, normal behaviour.
But now the default error handler tries to actually read that invalid config, which will of course fail, because, yeah, the config is invalid ;) So this ends up failing as well and now no result will be produced and [this bizarre and completely useles error message](https://github.com/playframework/playframework/issues/9020#issue-408672151) will be thrown by the akka-http backend.
(Actually it was not me, but @ctoomey [who deserves all the credit](https://github.com/playframework/playframework/issues/9020#issuecomment-564184187))
I can confirm the [reproducer posted in the original issue](https://github.com/SattaiLanfear/play27malformedconf/) now runs fine.

In DEV mode, only set the editor in the error handler if config is valid

---

core/play/src/main/scala/play/api/controllers/Assets.scala
core/play/src/main/scala/play/api/inject/ApplicationLifecycle.scala
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala

Fixes #9043
Actually I experience myself quite often that Play (re-)compiles when I shutdown dev mode (e.g via enter or CTRL+D)
I tracked down the core problem:
https://github.com/playframework/playframework/blob/ce4dadbd8e46bf15b2f61b6e54d447b3e988d8b1/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L251-L257
The line 255 is calling `appProvider.get`, and this `get` call will reload the app which [will cause a compilation (if e.g. the app has not even started yet or a file changed)](https://github.com/playframework/playframework/blob/2.8.7/transport/server/play-server/src/main/scala/play/core/server/DevServerStart.scala#L142). **But we don't want to reload the app and (re-)compile, we want to shut it down!**
Even worse, what happens next is that at some …

Don't reload/(re-)compile or even start an app when shutting down in DEV mode

---

dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/reverseRouter.scala.twirl
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-aggregate-reverse-routes/c/app/controllers/c/C.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/fullform.scala.html
documentation/manual/working/javaGuide/main/forms/code/javaguide/forms/helpers.scala.html
documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala
documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/implicitMessages.scala.html
documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/messages.scala.html
documentation/manual/working/scalaGuide/main/forms/code/scalaguide/forms/scalaforms/views/user.scala.html

Fixes #10363 to avoid the Scala 2.13.3+ warning about `Auto-application to '()'...`
Right now the reverse router always adds parentheses `()` to the generated method. Always.
With this patch it will only add it when also the `conf/routes` files defines it.
The forward router already works correctly.
IMHO there is no need for more tests, because we already have _nine_ `routes-compiler-*` scripted tests:
https://github.com/playframework/playframework/tree/master/dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin
(Besides the normal tests...)
So when the tests work, nothing is broken :wink:

Add empty parentheses () to generated reverse route method depending on routes file

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/app/controllers/HomeController.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/build.sbt.1
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/common-fail.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/conf/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/controller-fail.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/dev-mode-runtime-error-source-sub-project-outside/src/main/scala/Bar.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/modules/sub-project-inside/src/main/scala/Foo.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-inside-fail.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/sub-project-outside-fail.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-runtime-error-source/test
dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala

Fixes #10486
Fixes #10497
Backport for 2.8.x: #10649
Backport for 2.7.x: #10650
sbt 1.4 introduced a virtual file system it is using internally. So instead of Java `File` objects, Play now receives [`BasicVirtualFileRef`](https://github.com/sbt/zinc/blob/v1.4.4/internal/compiler-interface/src/main/java/xsbti/BasicVirtualFileRef.java) and [`MappedVirtualFile`](https://github.com/sbt/zinc/blob/v1.4.4/internal/zinc-core/src/main/scala/sbt/internal/inc/MappedVirtualFile.scala) objects, which both are subclasses of the [`VirtualFileRef`](https://github.com/sbt/zinc/blob/v1.4.4/internal/compiler-interface/src/main/java/xsbti/VirtualFileRef.java) interface.
Fortunately, that `VirtualFileRef` interface has methods that, with some reflection kung fu, we can use to figure out the correct file …

Support sbt 1.4 virtual files when displaying error source

---

web/play-java-forms/src/main/java/play/data/Form.java
web/play-java-forms/src/test/java/play/data/Letter.java
web/play-java-forms/src/test/java/play/data/Thesis.java
web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
web/play-java-forms/src/test/scala/play/data/FormSpec.scala

While working on #10471 I ran into an NPE exception when working with sub-forms when posting a field where the index was missing.
E.g. `foo[].bar` will throw an exception. However `foo[0].bar` (with explicit index) works as expected (because the underlying binder library from Spring can handle that syntax)
Also when posting lists/arrays (where the `[`/`]` brackets are at the end) everything works fine:
Play can handle `foo[0]` and and also `foo[]` (without index) - because Play will add the index automatically so the underyling binder can handle it.
This pull request makes Play to also automatically add an index to `foo[].bar` sub-form fields.

Java forms should handle "foo[].bar" fields when using subforms (index missing)

---

core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/test/scala/play/api/mvc/BindersSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/tests/RouterSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/tests/RouterSpec.scala
documentation/manual/working/javaGuide/advanced/routing/RequestBinders.md
documentation/manual/working/javaGuide/advanced/routing/code/javaguide/binder/models/CartItem.java
documentation/manual/working/scalaGuide/advanced/routing/ScalaRequestBinders.md
documentation/manual/working/scalaGuide/advanced/routing/code/scalaguide/binder/models/CartItem.scala

Fixes #10369 - Let's DO `URLEncode.encode()` for all queryString keys in QSB.unbind().
Unify unbind() behaviour over all query-string binders.
Currently, different binders handle qs-keys differently (look at `res3`):
```
$ sbt console
import play.api.mvc.QueryStringBindable
scala> QueryStringBindable.bindableChar.unbind( "items[1]", '1' )
val res1: String = items[1]=1
scala> QueryStringBindable.bindableInt.unbind( "items[1]", 1 )
val res2: String = items[1]=1
scala> QueryStringBindable.bindableString.unbind( "items[1]", "1" )
val res3: String = items%5B1%5D=1
scala> QueryStringBindable.bindableDouble.unbind( "items[1]", 1 )
val res4: String = items[1]=1.0
```
Special characters like `[`, `]` and others MUST be Form-URL-encoded according to …

QueryStringBindable.unbind(): Do-do-do URLEncode for all queryString keys!

---

transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala

Catch Throwable instead of NonFatal when starting prod server

---

core/play/src/main/scala/play/api/routing/sird/PathBindableExtractor.scala
project/BuildSettings.scala

Seems like it was missing since the beginning, when introducing `PathBindableExtractor`: https://github.com/playframework/playframework/pull/3964/files#diff-c4e9c1637b3d6926b61d0d20f01733ffd7c2915fedfc421f002e908b6e1aa41d

Add UUID PathBindableExtractor

---

project/BuildSettings.scala

master branch uses interplay 3 already which dropped support for 0.13. Not that sbt 0.13 is gone there is no need to target sbt plugins for java 1.6 anymore.
Also see https://github.com/playframework/interplay/pull/101/files#diff-9f23263fad304b1ca48c64c38db7d8f20fbd47120c76899715b9913021ab96eeL26

No need to target jdk 1.6 anymore for plugins

---

cache/play-caffeine-cache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
cache/play-ehcache/src/test/scala/play/api/cache/JavaCacheApiSpec.scala
core/play/src/test/java/play/mvc/ResultsTest.java

There are many rows like that `await(cacheApi.set("foo", "bar", 1 /* second */ ).toScala)` in the tests. These comments can be replaced on variables with readable names. It will look like that `await(cacheApi.set("foo", "bar", oneSecondExpiration).toScala)`

Replace comments on variables with readable names in tests

---

core/play/src/test/scala/play/api/mvc/BindersSpec.scala
core/play/src/test/scala/play/core/routing/RouterSpec.scala

There are many lines like that: `subject.bind("key", uuid.toString) must be_==(Right(uuid))`
It can be replaced on `subject.bind("key", uuid.toString) must beRight(uuid)` .
Kind regards

Replace generic matchers on specific builtin matchers in tests

---

project/Dependencies.scala

https://akka.io/blog/news/2021/02/23/akka-2.6.13-released
https://github.com/akka/akka-http/releases/tag/v10.1.14
**Note that this release may need your project to upgrade to the latest Scala version to compile (Scala 2.13.4+ or 2.12.13+)**
See #10713

Upgrade akka and akka-http

---

dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesGenerator.scala
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/javaWrappers.scala.twirl
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/javascriptReverseRouter.scala.twirl
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/reverseRouter.scala.twirl
dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/static/routesPrefix.scala.twirl

Fixes #10490
Necessary to make a build reproducible and for sbt's 1.4 remote cache feature.
Date was never used.
Source is used only here:
https://github.com/playframework/playframework/blob/202ca0a18dc3e6555eb0ebc73afdc7c2b10480b2/dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala#L58-L59
Comments generated before this patch:
```
// @GENERATOR:play-routes-compiler
// @SOURCE:/home/mkurz/play-test-project/conf/routes
// @DATE:Tue Feb 16 18:47:10 CET 2021
```
With this patch:
```
// @GENERATOR:play-routes-compiler
// @SOURCE:conf/routes
```
Did manual testing, works great (means the error page get's shown highlighting an invalid line in the routes file if there is one)

Routes compiler: Remove generation date, keep the source relative

---

core/play-integration-test/src/it/scala/play/it/http/parsing/AnyContentBodyParserSpec.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala

fix Int overflow. please see test case
use `Long` since https://github.com/playframework/playframework/pull/8627

fix Int overflow in BodyParsers.anyContent(maxLength: Option[Long])

---

.travis.yml

@ignasi35 I removed those in 2.8.x in #10723, IMHO we should do the same for the master branch.

Remove sbt 1.4.x / Scala 2.12.x (Test only 1.4.x / 2.13.x)

---

.github/release-drafter.yml
.github/workflows/release-drafter.yml

Currently the release drafted for master branch is wrongly titled `Play 2.8.8`
Also I want to enable the release drafter for the 2.8.x branch, not sure if that is all it needs.
Lets see.

Release drafter should use correct version + 2.8.x branch

---

.github/workflows/release-drafter.yml
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/tutorial/Tutorials.md

This activates the workflow for release drafter with the config (`.github/release-drafter-2.8.x.yml`) that gets added to the default (=master) branch via #10774
Also same doc updates like in #10774

[2.8.x] Add release-drafter workflow for 2.8.x branch + docs update

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala

Without direct access to the top-level method that returns all Evolutions in the database, any code that wants to do this while preserving the DB representation needs to reimplement or copy-paste several hundred lines of code from DatabaseEvolutions for interacting directly with the play_evolutions table. By making this one method public, such customization can be done with maybe 20 lines of non-boilerplate code.
Customizing the conflict-detection and -resolution behavior is a desirable use-case. For example:
* ignoring changes in very old evolutions, or in a set of known-bad historical evolutions
* comparisons of scripts that are tolerant to differing line ending conventions

Make public DatabaseEvolutions.databaseEvolutions()

---

project/BuildSettings.scala
transport/server/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala

Fixes #10478
Simply applied the same fix like https://github.com/lightbend/ssl-config/pull/269
I can compile Play with Java 16 release candiate now!

Fix compile error on JDK15: Use direct AlgorithmId.get()

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala

Reverts the changes introduced in #10500 to workaround a classtag leak. Since meanwhile the classtag leak was fixed in scala 2.12.13 (https://github.com/scala/scala/pull/9276) the workaround can be reverted.
Since in #10500 we also reduced the MaxMetaspaceSize, hopefully the tests will also caught any regressions

revert changes to playCommonClassloaderTask since we are using scala 2.12.13

---

core/play/src/main/java/play/mvc/Result.java
core/play/src/main/scala/play/api/mvc/Cookie.scala
project/BuildSettings.scala

Fixes #10122
See
* https://github.com/symfony/symfony/issues/36107
* https://github.com/symfony/symfony/pull/36173
* https://web.dev/samesite-cookie-recipes/
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie/SameSite
* https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie
* https://www.thinktecture.com/en/identity/samesite/how-to-delete-samesite-cookies/

Add SameSite to DiscardingCookie

---

transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
transport/server/play-akka-http-server/src/test/scala/play/core/server/akkahttp/AkkaHeadersWrapperTest.scala

Fixes Header.remove() in the specialized AkkaHeadersWrapper to support removing `Content-Type` and `Content-Length`.
This didn't work before because Content-Type and Content-Length are broken out into `knownContentLength` and `request.entity.contentType`
We ran into this issue in our Play proxy server which uses Headers.remove() to strip some incoming headers before proxying to the desired service

Akka-Http-Server: allow Headers.remove() to remove Content-Type and Content-Length

---

documentation/manual/working/scalaGuide/main/ws/ScalaWS.md

This function has been named `bodyAsSource` since at least 2.6.x (the example pulled from the spec file is of course correct).

Fix function name in Scala WS guide

---

core/play-java/src/main/scala/play/core/ObjectMapperModule.scala

The static object mapper, that can be retrieved via the static method [`Json.mapper()`](https://github.com/playframework/playframework/blob/ce4dadbd8e46bf15b2f61b6e54d447b3e988d8b1/core/play/src/main/java/play/libs/Json.java#L54-L66) and set via the static method [`Json.setObjectMapper`](https://github.com/playframework/playframework/blob/2.8.7/core/play/src/main/java/play/libs/Json.java#L204-L214), should only be set once.
Right now it would be overriden each time the provider's `get` method is called (when someone uses DI to inject an objectmapper). That is not so good, because when I use `Json.mapper()` and modify that mapper via a setter e.g. `Json.mapper().setVisibility(...)` I would expect that modified object mapper to persist as long I don't call `Json.setObjectMapper` myself …

Initialize static Json objectMapper only once

---

.travis.yml

Travis offers no guarantees regarding ordering but placing the slowest jobs first on each stage increases the likelihood that those slow jobs will be scheduled earlier.
Scheduling long jobs early decreases the build time.

Long jobs should appear first on a stage

---

documentation/manual/working/javaGuide/main/http/JavaSessionFlash.md
documentation/manual/working/scalaGuide/main/http/ScalaSessionFlash.md

Fixes the docs in:
* https://www.playframework.com/documentation/2.6.x/ScalaSessionFlash
* https://www.playframework.com/documentation/2.6.x/JavaSessionFlash
Since 9d6d39911c37bdaa6890e7916b9177e2376974b7 (Play 2.6) the flash cookie also gets signed.

Fix docs: Flash cookie is signed

---

core/play/src/main/resources/reference.conf

Updates the comment to match [the location used by play](https://github.com/playframework/playframework/blob/92828167e88c419b712bb699ec8a87952b5d643f/core/play/src/main/scala/play/api/routing/Router.scala#L87). Moved in #4106. Placing a file in `_root_.Routes` is currently ignored by play 2.8.

Fix reference.conf "router.Routes" FCQN comment

---

.travis.yml

I can not see the sense of this line (anymore).
@marcospereira Since you removed a similiar line in 9d54e038de02c58819cec77fc419b89f1f957427 / #10014  - that line here can be removed as well or not? Actually both lines were added together in #9928
However, meanwhile things changed: We use sbt-dynver and sbt 1.5.0 (which uses coursier) now and also MiMa [uses coursier now to resolve dependencies](https://github.com/lightbend/mima/releases/tag/0.8.0).
i was interested, so I purged my `.ivy2` folder (which I wanted to do anyway to save some disk space) and published-local the Play master branch. Only after running `scripted` tests that folder was filled with files when the scripted tests are looking for deps (because scripted test still use sbt 1.2.8, which still uses ivy resolution).
```
$ …
```

Remove outdated line in travis.yml

---

scripts/publish-local
scripts/test-scripted

Please see the comment I added in the `test-scripted` file.
Now that [scala-steward runs monthly](https://github.com/playframework/playframework/pull/10823/files), it opens many pull requests at once, in parallel, increasing the chance that these pull requests fail, because of the problem I described in my comment. The problem existed before as well and pull requests failed every now and then, but I never really looked into it what the problem was, until now, when I realized what's going on.
Let's look at one of those failed pull requests: https://travis-ci.com/github/playframework/playframework/builds/225836519:
As you can see, the publish-local jobs [used the version](https://travis-ci.com/github/playframework/playframework/jobs/505156579#L624) `2.8.1+1156-e905d7a5`, so the distance …

Make sure scripted jobs use the same commit like publish-local did

---

.travis.yml
dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
documentation/build.sbt
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/releases/release26/Highlights26.md
documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/build/sbtDependencies.md
documentation/project/build.properties
project/BuildSettings.scala
project/Dependencies.scala
project/build.properties

Run tests against Scala 2.12.14 and 2.13.6 and sbt 1.5.3

---

documentation/manual/working/javaGuide/main/tests/JavaTest.md

Using `-Xrunjdwp:` is outdated, better is to use `-agentlib:jdwp=` starting with Java 5: https://stackoverflow.com/questions/138511
Also [see what sbt uses](https://github.com/sbt/sbt/blob/v1.5.3/launcher-package/src/universal/bin/sbt.bat#L544) when running `sbt -jvm-debug 9999`:
```sh
if defined JVM_DEBUG_PORT (
set _JAVA_OPTS=!_JAVA_OPTS! -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=!JVM_DEBUG_PORT!
)
```

Prefer -agentlib:jdwp= over -Xrunjdwp:

---

transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala

...just like we do in the netty backend:
https://github.com/playframework/playframework/blob/d03d6343697ebaae108b4f10c8709bfc0a6660c8/transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala#L287-L296
IMHO there is no reason why we should use the dev-mode's actor system materializer in the akka backend. Ideally we would use the dev-mode's actor system materializer only for bootstrapping the server, as soon as we have an app available we should use it. The netty backend does exactly that, which IMHO is correct.
That caught my eye while skimming through the code because of [a discussion](https://discuss.lightbend.com/t/exceeded-configured-max-open-requests-value-of-32/8217).

Use app materializer to execute action in akka-http backend

---

project/BuildSettings.scala
testkit/play-test/src/main/java/play/test/Helpers.java

This code does not longer work now that the `StaticRoutesGenerator` got removed in #8049
There is no replacement, but actually there is an overload which takes a `Router` anyway. Actually the `routeAndCall` methods are meant to be used with the routing DSL, where you create a router anyway. For non routing DSL `route(...)` should be used instead.
"Fixes" #8177

Remove routeAndCall(...) methods that depended on StaticRoutesGenerator

---

dev-mode/routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl

avoid `Line is indented too far to the left` warning in Scala 3

align indent in `forwardsRouter.scala.twirl`

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/test
documentation/manual/working/commonGuide/build/sbtDebugging.md
documentation/manual/working/javaGuide/main/tests/JavaTest.md
documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
project/Dependencies.scala
project/Docs.scala
scripts/it-test
scripts/local-pr-validation.sh
scripts/scriptLib
scripts/validate-code
scripts/validate-docs

fix warnings. avoid old style.
https://github.com/sbt/sbt/commit/e6fec6b1db5f212a74bf5e3766b9b70f2d983f24
https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash

fix warnings. use slash syntax instead of old `in`

---

core/play-java/src/main/scala/play/routing/RoutingDslModule.scala
core/play/src/main/scala/play/core/j/JavaHttpErrorHandlerAdapter.scala
core/play/src/main/scala/play/core/parsers/Multipart.scala
documentation/manual/working/scalaGuide/main/http/code/ScalaBodyParsers.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
testkit/play-specs2/src/main/scala/play/api/test/Specs.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
web/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala

fix warnings
procedure syntax is deprecated
https://github.com/scala/scala/commit/1d4d901fcea0a162cd139836b246e85c

fix procedure syntax warnings

---

scripts/scriptLib

This is nice to have for debugging.
Took me a while to figure out where `MaxPermSize` was set in #10819 - which was removed in Java 17 nightlies and causes sbt to fail.

For CI jobs, print files used by sbt + env vars

---

build.sbt

prepare Scala 3 build.
I think we can use [`java-scala-2.13+/play/libs/CrossScala.java`](https://github.com/playframework/playframework/blob/d1f59e95892c69b1bd7e03d63997bb8c54a8de8a/core/play/src/main/java-scala-2.13%2B/play/libs/CrossScala.java) if Scala 3. because Scala 2.13.x and 3.0.x shared same scala-library jar.

update `unmanagedSourceDirectories` setting for Scala 3

---

core/play-integration-test/src/it/scala/play/it/http/parsing/BodyParserSpec.scala
core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/data/format/Format.scala
core/play/src/main/scala/play/api/data/format/package.scala
core/play/src/main/scala/play/api/i18n/Messages.scala
core/play/src/main/scala/play/api/mvc/Action.scala
core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/main/scala/play/api/mvc/WebSocket.scala
core/play/src/main/scala/play/api/mvc/macros/BinderMacros.scala
core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
core/play/src/test/scala/play/api/data/format/FormatSpec.scala
dev-mode/routes-compiler/src/main/scala/play/routes/compiler/RoutesCompiler.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala
documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-joda-forms/src/main/scala/play/api/data/format/JodaFormats.scala

fix warnings
- https://github.com/scala/scala/blob/v2.13.6/src/library/scala/util/Either.scala#L171-L172
- https://github.com/scala/scala/commit/2449721812ce36b0b11ee2653aa809b11f8e3765

avoid deprecated scala.Either#right

---

core/play/src/main/scala/play/utils/JsonNodeDeserializer.scala
core/play/src/test/java/play/utils/Child.java
core/play/src/test/java/play/utils/ChildDeserializer.java
core/play/src/test/java/play/utils/Parent.java
core/play/src/test/scala/play/utils/JsonNodeDeserializerSpec.scala

Fixes `JsonNodeDesrializer`. See https://github.com/lagom/lagom/issues/3241 for context and https://github.com/lagom/lagom/issues/3241#issuecomment-831292303 for a workaround.
When tail recursing, the previous implementation would advance the cursor even when the recursion was about to complete. As a consequence, when invoking Jackson's `readValue` (or `readValueAsTree`, or any equivalent) from within a deserialization the cursor would skip some events leading to skipped properties and data loss.

Fix tail-recursive deserializer (Lagom's #3241)

---

documentation/manual/gettingStarted/IDE.md
documentation/manual/releases/release24/migration24/Migration24.md
documentation/manual/working/commonGuide/build/BuildOverview.md
documentation/manual/working/commonGuide/build/sbtDependencies.md
documentation/manual/working/commonGuide/database/Developing-with-the-H2-Database.md
documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md

This PR updates outdated links to scala-sbt.org in the documentation (except places where the description is specific to sbt 0.13).
sbt 0.13 and its documentation is outdated, so I thought that it should to refer to the 1.x version of the sbt documentation.
Ref) https://www.scala-sbt.org/0.13/docs/

Update outdated links to scala-sbt.org in the documentation

---

project/BuildSettings.scala

In #10500 the value was changed from 512m to 300m.
Since then every now and then we get a `OutOfMemoryError`.
I suggest to just increase the value again.
Also @jtjeferreira could [not reproduce the problem locally](https://github.com/playframework/playframework/issues/10676#issuecomment-774770245)... Maybe it's just that garbage collection on CI is "to slow" or whatever, I don't know, I don't have a PhD in garbage collection...
I think 512m was fine the last years and it's ok to just use that value again.

Set MaxMetaspaceSize to 512m (like it was 4 month ago)

---

build.sbt
project/Dependencies.scala

After merging #10963 another [problem unfolded](https://app.travis-ci.com/github/playframework/playframework/jobs/534232661#L15136-L15139): Now that the cron jobs use the correct and therefore latest akka snapshot again (from the sonatype repo now instead from repo.akka.io) that latest akka snapshot is now 2.6.16-xxx-SNAPSHOT. Before 2.6.14-xxx-SNAPSHOT from repo.akka.io was used (if I remember correctly).
Now the problem is, because we use that latest and greatest akka snapshot, akka upgraded its `scala-java8-compat` library [recently to 1.0.0](https://github.com/akka/akka/pull/30375). That is a problem when running scripted tests with sbt 1.5.x because that latest and greatest sbt version checks for deps compatibily so we end up with broken sbt 1.5 scripted tests:
```
[info] [error] 	* …
```

[2.8x] Fix cron job by upgrading akka + scalaJava8Compat (for Scala 2.13 only)

---

build.sbt
project/Dependencies.scala

This code was added here https://github.com/playframework/playframework/commit/c81dbfaa4a51da8b42b69bc12efe9a63f6868553#diff-a7128390b01737066cea724216ef9341188fa29b0dc84db5024feec2966d68ddR257 ("useful setup for co-developing akka-http and the akka-http play backend") - when developing Play's akka-http backend.
At that time akka-http was just in its [early <= 10.0.6 days](https://github.com/akka/akka-http/tags?after=v10.0.8).
Does actually someone still use this helper? I never did and I think its not necessary anymore, since the play akka-http backend is stable and just requires normal akka-http upgrades (and maybe necessary code adjustments), but not active developing anymore.
If you think its still necessary please just close this PR, its ok for me.

Remove obsolete helper used for developing akka-http play backend

---

documentation/manual/releases/release29/migration29/Migration29.md
web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/JavaCSPReportSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/ScalaCSPReportSpec.scala

Fixes #10876 
Fix CSP report types. Add fallback for Strings as discussed

CSP Reports fix with fallback for Strings

---

core/play/src/main/scala/play/core/utils/AsciiSet.scala
transport/server/play-server/src/main/scala/play/core/server/common/InvalidHeaderCharacterException.scala
transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
transport/server/play-server/src/test/scala/play/core/server/common/ServerResultUtilsSpec.scala

* ~~Have you checked that both Scala and Java APIs are updated?~~
* ~~Have you updated the documentation for both Scala and Java sections?~~
Fixes #10944
Return HTTP 400 instead of 500 when headers contain non-Ascii characters, and avoid writing error logs in such cases.
Another option would be to allow Unicode characters to go through, even though the RFCs do not allow it.
Even then, there would be more malicious cases (e.g. control characters) that should be rejected without causing server errors, so this fix would be required anyways.

HTTP 400 instead of 500 on Unicode headers

---

documentation/manual/gettingStarted/Installing.md
documentation/manual/gettingStarted/Requirements.md

Fixes #10938 
This pull request changes existing links to oracle JDK(which is commercial) to open JDK to prevent readers from accidentally installing commercial software.
[Adoptium](https://adoptium.net/) is selected for the new link because it is the rebrand to popular open JDK [AdoptOpenJDK](https://adoptopenjdk.net/).
- This pull request changes a link to oracle JDK to open JDK on [Requirement page](https://www.playframework.com/documentation/2.8.x/Requirements).
- Currently, Installing.md seems not used(It will redirect to the requirement page if you type https://www.playframework.com/documentation/2.8.x/Installing). But I changed it too in case it will be used again.
- The word “oracle” is mentioned in many files, but as far as I searched, they are mostly links to oracle …

Fix docs: change oracle jdk link to open jdk link

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala

Fixes #10892
Always log error message if an exception occurs when applying evolutions. Even if autocommit is enabled and error would most of the time be duplicated in the `play_evolutions` database.
N/A
N/A

fix: 🐛 Always log error message when applying evolutions (#10892)

---

.travis.yml
project/BuildSettings.scala
scripts/validate-code

Remove Whitesource checks as Lightbend has discontinued the use of the Whitesource service.

Remove Whitesource checks

---

web/play-filters-helpers/src/main/scala/play/filters/cors/AbstractCORSPolicy.scala

As mentioned in #10928, the names for these identifiers should be swapped.

swap names for hostUri and originUri

---

.github/release-drafter-master.yml

A patch was needed in release drafter: https://github.com/release-drafter/release-drafter/pull/823
Finally our release drafts look correct:
Instead of:

Correct versions in release drafter template

---

.github/FUNDING.yml

Let's add a sponsor button, which links to https://opencollective.com/playframework, like [babel](https://github.com/babel/babel) has:
See https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

Displaying a sponsor button to promote Open Collective

---

project/Dependencies.scala

Updates to the current Akka and Akka HTTP versions.
Akka HTTP 10.1.15 includes some important security fixes.
[Akka 2.6.17 release notes](https://akka.io/blog/news/2021/10/15/akka-2.6.17-released)
[Akka HTTP 1.1.15 release notes](https://doc.akka.io/docs/akka-http/10.1/release-notes/10.1.x.html#10-1-15)

bump: Akka 2.6.17 and Akka HTTP 10.1.15 for Play 2.8.9

---

documentation/manual/tutorial/code/javaguide/hello/HelloController.java

Documentation that is incorrect: [before]( https://www.playframework.com/documentation/2.8.x/PlayApplicationOverview) 
```java
public Result index() {
return ok(views.html.index.render("Your new application is
return ok(javaguide.hello.html.index.render("Your new application is ready.", assetsFinder));
}
```
According to https://www.playframework.com/documentation/2.8.x/Documentation
```###replace: foo — Replace the next line with foo. You may optionally terminate this command with ###```
The code sample that was to be run, tested, and injected into the documentation was split into multiple lines (likely by an autoformatter) which made the documentation for the java example incorrect. 
This PR changes the 'replace' to one line, and also reduces the whitespace on the left to prevent the …

Fixed `###replace:` tag that led to incorrect docs

---

project/BuildSettings.scala

We need this to be able to publish to `com.typesafe.play`. This is a new sonatype profile that accepts artifacts for group id `com.typesafe.play`. 
Lightbend's profile `com.typesafe` is not configured anymore for artifacts in group id `com.typesafe.play`.
We need this to move forward with the 2.8.9 release.

use new community sonatype profile

---

documentation/manual/working/commonGuide/configuration/SettingsLogger.md

This is to address CVE-2021-44228.

Upgraded version of log4j used in docs to 2.15.0

---

documentation/manual/working/commonGuide/configuration/SettingsLogger.md

For [CVE-2021-45046](https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45046).

Updating log4j ref in docs to 2.16.0

---

documentation/manual/gettingStarted/Requirements.md

I tried building the [hello world](https://www.playframework.com/documentation/2.8.x/HelloWorldTutorial) and the requirements it linked did not mention that [up to java 11 is supported](https://discuss.lightbend.com/t/play-sample-on-windows-java-lang-illegalstateexception-unable-to-load-cache-item/8663)
Initially I tried with java 17 and got an error basically described in [Play Framework Scala Hello-World fail on Ubuntu 20](https://stackoverflow.com/questions/67291502/play-framework-scala-hello-world-fail-on-ubuntu-20)
After downgrading to java 11 it worked

Show latest version of java supported in 2.8 in Requirements.md

---

documentation/manual/working/commonGuide/configuration/SettingsLogger.md

Docs only - updated log4j version to 2.17.0 for [CVE-2021-45105](https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-45105) - https://logging.apache.org/log4j/2.x/security.html#CVE-2021-45105

Updating log4j to 2.17 in docs

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala

Fixes #11032
In #9420 we made the `run` command interruptible by adding a couple of sleep statements, so that when hitting CTRL+C sbt had the chance to interrupt the thread.
To fix #10864 Greg now switched from `FileDescriptor.in` to `System.in` in #10890, which totally make sense, however it isn't that easy. Starting with sbt 1.4 `System.in` is non-blocking, therefore the patch introduced in #9420 makes the sbt console hang when waiting for an input. The problem is that `read()` recursively calls itself in the same thread that is supposed to read data from System.in, but because of the endless loop it never has the chance to do so.
Anyway, [this comment](https://github.com/sbt/sbt/issues/6515#issuecomment-843565236) confirms exactly what I debugged:
> They shouldn't need to create a non …

ConsoleReader should be blocking in sbt 1.4+ since System.in already is non-blocking

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayRun.scala

While working on #11061 I found out that the current behaviour when pressing CTRL+C while the `run` command is blocking is not good:
```
[myproject] $ run
--- (Running the application, auto-reloading is enabled) ---
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /127.0.0.1:9000
(Server started, use Enter to stop and go back to the console...)
<------------------------------------------ PRESSING CTRL+C HERE ------------------------------------------>
[warn] Canceling execution...
Cancelled: run
[error] Cancelled: run
[error] Use 'last' for the full log.
[myproject] $
<----------------------------- but dev server still running in the background ------------------------------>
[myproject] $ exit
[info] shutting down sbt server
<------------------------- dev server eventually shuts down …
```

Shutdown dev server when pressing CTRL+C during run

---

dev-mode/run-support/src/main/scala/play/runsupport/Colors.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/Colors.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

Until Play version 2.2 we [displayed a welcome message](https://www.playframework.com/documentation/2.2.x/resources/manual/gettingStarted/images/playNew.png) ([code](https://github.com/playframework/playframework/blob/2.2.x/framework/src/console/src/main/scala/Console.scala#L16-L27)). With version 2.3 Play switched to activator and as part of that [the welcome message was removed](https://github.com/playframework/playframework/commit/00573d82a02b1fbe03bfda808ac69416b06da6f8) but never restored (maybe back then James didn't know about the `onLoadMessage` setting).
Also Play 1 always displayed [a welcome screen](https://www.playframework.com/documentation/1.5.x/images/help), so does [sbt for its build since a while](https://github.com/sbt/sbt/commit/4c6e421d591c726594c62ac60da09715daf17e22). …

Add onLoadMessage

---

dev-mode/run-support/src/main/scala/play/runsupport/Colors.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/Colors.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

Backport of #11070, but just checking for Java 8, because Java 11 is only officially supported since Play 2.8: https://www.playframework.com/documentation/2.8.x/Highlights28#Java-11-support

[2.7.x] Add onLoadMessage

---

.github/release-drafter-2.8.x.yml

Just one typo.
The first heading is obsolete since there is a heading already (the one from GitHub itself).

Update draft release announcement used for minor releases

---

.github/release-drafter-2.8.x.yml
.github/release-drafter-master.yml

GitHub improved their release pages: https://github.blog/2021-10-04-beta-github-releases-improving-release-experience/
As written in [the docs as well](https://docs.github.com/en/repositories/releasing-projects-on-github/managing-releases-in-a-repository) when you `@mention` a user in the notes they will be added at the bottom of the release notes, like:
<kbd><img width="400" src="https://user-images.githubusercontent.com/644927/149222490-7f28554d-0db5-4085-9f3b-a0a48b26e95f.png" /></kbd>
However, when releasing 2.8.13 I noticed that there was no one added (I had to modify the draft by hand instead)... That is because right now the authors are included in a link, which actually is a link to the author... So GitHub does not pick up the user because it's a link... 
However e.g. @mkurz …

No need link to author in release drafts, @... is a link already

---

dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
project/Dependencies.scala

See notes in https://github.com/playframework/play-ws/pull/638
Because the Play cron build uses the latest akka snaphot it uses a snapshot version which already upgraded ssl-config to 0.6.0. It looks like ssl-config is not binary compatible between 0.4.3 and 0.6.0, so we have to upgrade it in Play and play-ws as well.

[2.8.x] Use ssl-config to 0.6.0

---

dev-mode/build-link/src/main/java/play/core/Build.java

Small refactoring for better code readability 

---

core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
core/play/src/main/scala/play/api/http/MediaRange.scala
core/play/src/main/scala/play/core/j/JavaAction.scala
core/play/src/main/scala/play/core/system/WebCommands.scala

- Removes compilation warnings about deprecated `Stream` collections in Scala 2.13
- Changes part of getting the project to compile clean on Scala 2.13

Swap deprecated Lazy Stream to LazyList

---

documentation/manual/gettingStarted/IDE.md

`fork := true` doesn't even work for `sbt run`.
System properties set via `javaOptions += "-D...` does work, the reloader picks them up (I just tested this), so `fork := true` is definitely not needed.

fork := true for "sbt run" not needed to set editor (it doesn't even work)

---

core/play/src/main/scala/play/api/mvc/Cookie.scala

Fix warings
- https://github.com/scala/scala/blob/v2.13.8/src/library/scala/package.scala#L50-L53
- https://app.travis-ci.com/github/playframework/playframework/jobs/556754628#L1170
```
[warn] /home/travis/build/playframework/playframework/core/play/src/main/scala/play/api/mvc/Cookie.scala:149:23: type Traversable in package scala is deprecated (since 2.13.0): Use Iterable instead of Traversable
[warn] trait Cookies extends Traversable[Cookie] {
```

use `Iterable` instead of deprecated `Traversable`

---

core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/java/play/mvc/BodyParsers.java
core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/routing/sird/PathBindableExtractor.scala
core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
core/play/src/test/scala/play/api/i18n/MessagesSpec.scala

Fix warnings
- https://github.com/scala/scala/pull/5135
- https://app.travis-ci.com/github/playframework/playframework/jobs/556754629#L1120
```
[warn] /home/travis/build/playframework/playframework/core/play/src/main/scala/play/api/data/Form.scala:803:42: method get in class RightProjection is deprecated (since 2.13.0): Use `Either.toOption.get` instead
[warn]       Right(allErrorsOrItems.map(_.right.get).toList).flatMap(applyConstraints)
[warn]                                          ^
[warn] /home/travis/build/playframework/playframework/core/play/src/main/scala/play/api/data/Form.scala:803:36: method right in class Either is deprecated (since 2.13.0): Either is now right-biased, use methods directly on Either
[warn]       Right(allErrorsOrItems.map(_.right.get).toList).flatMap(applyCon …
```

avoid deprecated Either methods

---

core/play-integration-test/src/it/scala/play/it/http/parsing/FormBodyParserSpec.scala
core/play-integration-test/src/it/scala/play/it/tools/HttpBin.scala
core/play/src/main/scala/play/api/Configuration.scala
core/play/src/main/scala/play/api/data/Form.scala
core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/main/scala/play/api/mvc/Cookie.scala
core/play/src/main/scala/play/api/mvc/Headers.scala
core/play/src/main/scala/play/api/routing/sird/QueryStringExtractors.scala
core/play/src/main/scala/play/core/j/JavaHelpers.scala
core/play/src/main/scala/play/core/j/JavaParsers.scala
core/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala
core/play/src/main/scala/play/core/routing/PathPattern.scala
core/play/src/main/scala/views/helper/checkbox.scala.html
core/play/src/test/scala/play/api/ConfigurationSpec.scala
core/play/src/test/scala/play/api/routing/sird/UrlContextSpec.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
persistence/play-jdbc/src/main/scala/play/api/db/DBModule.scala
testkit/play-test/src/main/scala/play/api/test/Helpers.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
web/play-java-forms/src/test/scala/play/data/FormSpec.scala
web/play-openid/src/main/scala/play/api/libs/openid/OpenIdClient.scala
web/play-openid/src/test/scala/play/api/libs/openid/package.scala

Fix warnings
`.mapValues` => `.view.mapValues`
- https://github.com/scala/scala/blob/v2.13.8/src/library/scala/collection/Map.scala#L261-L262
- https://app.travis-ci.com/github/playframework/playframework/jobs/557562682#L1116
```
[warn] /home/travis/build/playframework/playframework/core/play/src/main/scala/play/api/Configuration.scala:130:41: method mapValues in trait MapOps is deprecated (since 2.13.0): Use .view.mapValues(f). A future version will include a strict version of this method (for now, .view.mapValues(f).toMap).
[warn]       case map: Map[_, _]        => map.mapValues(toJava).toMap.asJava
[warn]                                         ^
[warn] /home/travis/build/playframework/playframework/core/play/src/main/scala/play/api/data/Form.scala:259:8: method mapValues in trait …
```

fix `mapValues` warnings

---

dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsPlugin.scala
dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
documentation/build.sbt
documentation/manual/gettingStarted/code/ide.sbt
documentation/manual/working/commonGuide/build/code/cookbook.sbt
documentation/manual/working/commonGuide/build/sbtCookbook.md
documentation/manual/working/commonGuide/configuration/ConfigFile.md
documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
documentation/manual/working/commonGuide/production/code/assembly.sbt
documentation/manual/working/commonGuide/production/code/debian.sbt
documentation/manual/working/commonGuide/production/code/production.sbt
documentation/manual/working/commonGuide/production/code/rpm.sbt
documentation/manual/working/javaGuide/main/tests/JavaTest.md

Fix warnings
- https://github.com/sbt/sbt/commit/e6fec6b1db5f212a74bf5e3766b9b70f2d983f24
- https://www.scala-sbt.org/1.x/docs/Migrating-from-sbt-013x.html#slash

use slash syntax instead deprecated `in`

---

core/play/src/main/scala/play/api/http/AcceptEncoding.scala
core/play/src/main/scala/play/api/http/MediaRange.scala
core/play/src/main/scala/play/core/j/JavaAction.scala
core/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala
transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala
web/play-filters-helpers/src/main/scala/play/filters/cors/CORSFilter.scala

Fix warnings
use `ArraySeq.unsafeWrapArray`, `toSeq` or something
https://app.travis-ci.com/github/playframework/playframework/jobs/557628971#L1164
```
[warn] /home/travis/build/playframework/playframework/transport/server/play-server/src/main/scala/play/core/server/ProdServerStart.scala:29:69: method copyArrayToImmutableIndexedSeq in class LowPriorityImplicits2 is deprecated (since 2.13.0): Implicit conversions from Array to immutable.IndexedSeq are implemented by copying; Use the more efficient non-copying ArraySeq.unsafeWrapArray or an explicit toIndexedSeq call
[warn]   def main(args: Array[String]): Unit = start(new RealServerProcess(args))
[warn]                                                                     ^
[warn] /home/travis/build/playframework/playframework/transport/serve …
```

fix Seq implicit conversions warnings

---

.github/release-drafter-main.yml
.github/workflows/release-drafter.yml
.travis.yml
CONTRIBUTING.md
README.md
core/play/src/main/scala/play/api/mvc/RangeResult.scala
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/hacking/ThirdPartyTools.md
documentation/manual/hacking/Translations.md
documentation/manual/hacking/WorkingWithGit.md
documentation/manual/releases/release24/migration24/Migration24.md
documentation/manual/releases/release26/migration26/Migration26.md
documentation/manual/working/commonGuide/configuration/ConfigFile.md
documentation/manual/working/commonGuide/filters/CspFilter.md
documentation/manual/working/commonGuide/production/ProductionConfiguration.md
documentation/manual/working/commonGuide/production/cloud/Deploying-CleverCloud.md
documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md
documentation/manual/working/scalaGuide/main/forms/ScalaForms.md

@SethTisue and @ihostage already renamed the `master` branch in some play repos:
* https://github.com/playframework/cachecontrol/pull/163
* https://github.com/playframework/play-file-watch/pull/136
* https://github.com/playframework/play-json/pull/598
* https://github.com/playframework/play-soap/pull/282
* https://github.com/playframework/play-ws/pull/597
* https://github.com/playframework/twirl/pull/416
Now that we are centralising configs in the [`.github`](https://github.com/playframework/.github) repo it's a good idea that all repos have the same default branch name.
To change to `main` locally (if the remote to this repo is called `upstream`):
```sh
git branch -m master main # rename master to main (actually "move")
git fetch upstream
git branch -u upstream/main main # set upstream …
```

Rename master branch to main

---

documentation/manual/ModuleDirectory.md

Remove old or abandoned modules from the modules directory. 
Anything that had no release or any activity  in 4 or more years has been removed from the 2.8 documentation.

Remove old or abandoned 3rd party play modules from module directory

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

The current message sounds a little aggressive/alarmist - people can certainly keep using the framework regardless of whether they contribute or donate. 
That said, we do of course very much want to encourage people to contribute & donate.

Make the "please donate" message more friendly

---

transport/server/play-akka-http-server/src/main/resources/reference.conf
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala

- No new files
- I think `AkkaHttpServer` is implemented only Scala
- No functionality changes
N/A
Add warning for `serverTerminateTimeout` is longer than `service-unbind` phase timeout.
- Default `service-unbind` phase timeout is 5000 milliseconds
- If we set `serverTerminateTimeout = 10 seconds` in the example, it maybe don't work well:
```
--- (Running the application, auto-reloading is enabled) ---
[info] p.c.s.AkkaHttpServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000
(Server started, use Enter to stop and go back to the console...)
[info] p.a.h.EnabledFilters - Enabled Filters (see <https://www.playframework.com/documentation/latest/Filters>):
play.filters.csrf.CSRFFilter
play.filters.headers.SecurityHeadersFilter
play.filters.hosts.AllowedHostsFilter
[info] play.api.Play - …
```

Add warning `serverTerminateTimeout` is longer than `service-unbind` timeout

---

.travis.yml
dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala
documentation/build.sbt
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/hacking/Translations.md
documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/releases/release29/migration29/Migration29.md
documentation/manual/working/commonGuide/build/sbtDependencies.md
project/Dependencies.scala

Finally akka 2.6.19 is compatible with ssl-config 0.6.x, see https://github.com/akka/akka/pull/31046 and https://github.com/akka/akka/pull/31252.

Latest akka/scala/ssl-config

---

documentation/manual/working/javaGuide/main/async/code/javaguide/async/JavaWebSockets.java

See #11029
I don't think this is even needed since you have access to the request later in `...acceptOrResult(request -> ...`
Should have been in #8639, but probably was forgotten.
I think this is just a doc problem.
In case someone really needs the request directly in the controller method we may can make this work, however let's see if there is really need for that.

Fix docs: Passing request to WebSocket action not supported

---

core/play/src/main/java/play/package-info.java
core/play/src/main/scala/play/utils/Resources.scala
project/BuildSettings.scala
project/Dependencies.scala
transport/server/play-server/src/main/scala/play/core/server/ssl/CertificateGenerator.scala

See https://github.com/playframework/playframework/pull/10819#issuecomment-1074831204
This might not enable full Java 17 support for Play 2.8.x out of the box yet, however it unlocks it partially.
People very likely still need to upgrade deps on their own, like:
- Guice to latest version 5.x: https://github.com/google/guice/releases/
- If using Java routing DSL to 0.6.3: `"net.jodah" % "typetools" % "0.6.3"`, see #10055 and #10814
Also avoid using `jnotify` for the `FileWatchService`, see https://github.com/playframework/playframework/pull/10731/files#diff-200727c8deef149abd2e23743e98a3478c2d2662fc0f78529fe46ffd3f675938
There might be other stuff that breaks, which I am not aware of right now.

[2.8.x] Partial support for Java17

---

core/play/src/main/resources/reference.conf
core/play/src/main/scala/play/api/libs/concurrent/Akka.scala
core/play/src/test/scala/play/api/PlayGlobalAppSpec.scala
documentation/manual/releases/release29/migration29/Migration29.md
documentation/manual/working/javaGuide/main/akka/JavaAkka.md
documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md

Please read the migration notes I added, it explains the reasons to delete that config. IMHO that config was never implemented correctly and is prone to cause problems.
Fixes #6183

Remove play.akka.config setting

---

testkit/play-test/src/main/scala/play/api/test/TestServerFactory.scala

This PR defaults the test server to start on an HTTP endpoint that's defined by `play.api.test.Helpers.testServerPort`.
The documentation at https://www.playframework.com/documentation/2.8.x/ScalaFunctionalTestingWithScalaTest#Testing-with-a-server says
> The OneServerPerSuite and OneServerPerTest traits provide the port number on which the server is running as the port field. By default this is 19001, however you can change this either overriding port or by setting the system property testserver.port. This can be useful for integrating with continuous integration servers, so that ports can be dynamically reserved for each build.
But this isn't the case -- the port number is randomly assigned as 0.  So this is inconsistent with the docs and with prior behavior.
Ironically, the current …

DefaultTestServerFactory should use HTTP server port from helpers

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

Running future Play 2.8.x on Java 17:
Running future Play on a not supported Java version:

[2.8.x] Adjust welcome message for experimental Java 17 support

---

project/Dependencies.scala

https://spring.io/blog/2022/03/31/spring-framework-rce-early-announcement
Also see #11213

[2.8.x] Upgrade Spring to fix Spring4Shell vulnerability

---

.github/workflows/trigger-cache-invalidation.yml

Right now there is no possibility to clean the GH actions cache. Neither by UI, nor by REST api:
* https://github.com/actions/cache/issues/2
* https://github.community/t/how-to-clear-cache-in-github-actions/129038
However, there is one workaround (inspired by https://github.com/actions/cache/issues/2#issuecomment-1098723830):
[As stated in the docs](https://docs.github.com/en/actions/using-workflows/caching-dependencies-to-speed-up-workflows#usage-limits-and-eviction-policy), given that...
> ...the total size of all caches in a repository is limited to 10 GB. If you exceed this limit, GitHub will save your cache but will begin evicting caches until the total size is less than 10 GB.
...we can fill up the cache with one big fat 10GB file, which will then cause older entries in the cache to …

Add workflow to trigger cache invalidation

---

.github/workflows/build-test.yml

The problem:
1. Let's assume the cache is empty.
1. A scheduled job starts and will fetch [the current akka snapshot version](https://github.com/playframework/playframework/blob/55238a2b42c2480712b92dd9d7ca486d8ab9a935/.github/workflows/build-test.yml#L29-L30)
1. Afterwards `publishLocal`. Because we are using akka snapshots, the published Play version will be something like `2.8.1+1638-55238a2b-SNAPSHOT-akka-2.6.19+52-00c1da99-SNAPSHOT-akka-http-10.1.15+4-8e825ed4-SNAPSHOT`. Artifacts will be cached with `play-published-local-jdk8-${{ github.sha }}`. (`github.sha` is the commit from the Play repo)
1. scripted test reuse artifacts from cache `play-published-local-jdk8-${{ github.sha }}`
1. Everything works
The scheduled jobs finished, nothing changed (and nothing will be changing) in the …

Fix the GitHub actions cron job

---

.github/workflows/build-test.yml

https://github.com/coursier/cache-action/pull/296 got merged and released as [`v6.3.1`](https://github.com/coursier/cache-action/releases/tag/v6.3.1)

Speed up build with cache-hit-coursier

---

web/play-java-forms/src/main/java/play/data/validation/Constraints.java
web/play-java-forms/src/test/scala/play/data/FormSpec.scala

Fixes https://github.com/playframework/playframework/issues/10622 by changing the java email regex to be the same as the scala one.

10622 - java validation should use the same regex as scala validation

---

.github/workflows/build-test.yml

Make sure to test against all support Java version. When using travis we did not do that for the main branch because in travis only had 5 workers and everything was blocked when a cron build started. This is not a problem anymore with GHA.
Also the `build-test.yml` from the main branch is now almost identical with the `build-test.yml` fromt the 2.8.x branch - only in 2.8.x we still support Scala 2.12.x
(Of course we Java 8 will soon be replaced with Java 17 here)

Test against all Java versions, but only nightly

---

.github/workflows/build-test.yml

This is a initial setup to gradually start to compile with Scala3. 
The next step is to upgrade all the dependencies to their Scala3 releases. That can be challenging. I already run into an issue, for example spec2-mock was not published for Scala3.

Prepare build for Scala3

---

core/play/src/main/scala/play/api/i18n/Messages.scala

postfixOps disabled with Scala 3 by default.

avoid `postfixOps`. prepare Scala 3

---

core/play/src/main/scala/play/api/libs/Collections.scala
core/play/src/main/scala/play/core/j/JavaAction.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala

deprecate `unfoldLeft`. use `scala.Seq.unfold`
- Scala std lib add `Seq.unfold` since 2.13. https://github.com/scala/scala/blob/7952071b88a85e2502e9ecd4e8bd57040d9448f5/src/library/scala/collection/Factory.scala#L114-L124
- playframework dropped Scala 2.12 https://github.com/playframework/playframework/pull/10956

deprecate `Collections.unfoldLeft`

---

core/play-integration-test/src/it/scala/play/it/views/DevErrorPageSpec.scala

Forward port fix from #11305 to make ci happy again.

Use DevHttpErrorHandler to check if play.editor link gets rendered

---

core/play-guice/src/main/scala/play/api/libs/concurrent/TypedAkka.scala

Fixes compile error in Scala 3.
use `Any` instead of `_`
```scala
Welcome to Scala 3.1.2 (11.0.15, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
scala> import scala.reflect.ClassTag
scala> def typeLiteral[C[_], T](cls: Class[_])(implicit C: ClassTag[C[_]]) = null
-- [E043] Type Error: ----------------------------------------------------------
1 |def typeLiteral[C[_], T](cls: Class[_])(implicit C: ClassTag[C[_]]) = null
|                                                             ^^^^
|     unreducible application of higher-kinded type C to wildcard arguments
longer explanation available when compiling with `-explain`
1 error found
scala> def typeLiteral[C[_], T](cls: Class[_])(implicit C: ClassTag[C[?]]) = null
-- [E043] Type Error: …
```

fix TypedAkka.scala. prepare Scala 3

---

core/play/src/main/java/play/libs/Files.java

fix compile error in Scala 3.
use `TemporaryFileCreator` type instead of `SingletonTemporaryFileCreator$`
A.scala
```scala
package example
trait A
object B extends A
```
C.java
```java
package example;
public class C {
example.B$ b = example.B$.MODULE$;
}
```
compile with Scala 3.1.2
```
[error] 4 |  example.B$ b = example.B$.MODULE$;
[error]   |  ^^^^^^^^^^
[error]   |  type B is not a member of example - did you mean example.B.type?
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```
- https://github.com/playframework/playframework/issues/11260

fix `play/libs/Files.java`. prepare Scala 3

---

core/play/src/main/java/play/i18n/MessagesApi.java
core/play/src/main/java/play/inject/Module.java
core/play/src/main/java/play/libs/Scala.java
core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/java/play/mvc/Results.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution-without-documentation/app/controllers/Application.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/app/controllers/Application.scala
documentation/manual/working/commonGuide/filters/code/javaguide/detailed/filters/csp/MyDynamicCSPAction.java

Fix warnings
- https://github.com/playframework/playframework/pull/10956 play dropped Scala 2.12 support

use `CollectionConverters` instead of deprecated `JavaConverters`

---

core/play-java/src/test/java/play/mvc/HttpTest.java
core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
core/play-streams/src/test/java/play/libs/streams/AccumulatorTest.java
core/play/src/main/java/play/http/DefaultHttpFilters.java
core/play/src/main/java/play/mvc/Result.java
core/play/src/main/java/play/mvc/StatusHeader.java
web/play-filters-helpers/src/main/java/play/filters/csrf/AddCSRFTokenAction.java
web/play-java-forms/src/main/java/play/data/DynamicForm.java
web/play-java-forms/src/main/java/play/data/Form.java
web/play-java-forms/src/main/java/play/data/validation/Constraints.java

use method reference in java files if possible.

use method reference

---

core/play/src/main/scala/play/api/mvc/Request.scala
core/play/src/main/scala/play/api/mvc/RequestHeader.scala
core/play/src/main/scala/play/api/mvc/Results.scala

fix compile error with Scala 3.
https://github.com/playframework/playframework/blob/6e614d11cca8070e6c3aa4940f682f8cc1183e73/core/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala#L94
```
[error] 99 |    withAttrs(attrs + (entries: _*))
[error]    |                                ^
[error]    |          `_*` can be used only for last argument of method application.
[error]    |          It is no longer allowed in operands of infix operations.
```
```
Welcome to Scala 3.1.2 (11.0.15, Java OpenJDK 64-Bit Server VM).
Type in expressions for evaluation. Or try :help.
scala> object A { def +(xs: Int*): Unit = () }
// defined object A
scala> def a(xs: Int*) = A + (xs: _*)
-- Error: ----------------------------------------------------------------------
1 |def a(xs: Int*) = A + (xs: _*)
| …
```

avoid infix with `_*`. prepare Scala 3

---

core/play-integration-test/src/it/scala/play/it/http/JavaHttpErrorHandlingSpec.scala
core/play-java/src/main/scala/play/core/TemplateMagicForJava.scala
core/play-streams/src/main/scala/play/api/libs/streams/Accumulator.scala
core/play/src/main/scala/play/api/http/HttpEntity.scala
core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/main/scala/play/api/templates/Templates.scala
core/play/src/main/scala/play/core/j/JavaHelpers.scala
core/play/src/main/scala/play/core/j/JavaRangeResult.scala
core/play/src/main/scala/play/core/j/JavaRouterAdapter.scala
core/play/src/main/scala/play/core/routing/HandlerInvoker.scala
core/play/src/test/scala/play/mvc/DefaultBodyParserSpec.scala
core/play/src/test/scala/play/mvc/MaxLengthBodyParserSpec.scala
core/play/src/test/scala/play/mvc/RequestHeaderSpec.scala
core/play/src/test/scala/play/mvc/ResponseHeaderSpec.scala
core/play/src/test/scala/play/mvc/ResultSpec.scala
web/play-filters-helpers/src/main/scala/play/filters/csp/CSPReportActionBuilder.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
web/play-filters-helpers/src/main/scala/play/filters/headers/SecurityHeadersFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/JavaCSRFActionSpec.scala
web/play-java-forms/src/main/scala/play/core/PlayFormsMagicForJava.scala
web/play-java-forms/src/test/scala/play/data/DynamicFormSpec.scala
web/play-java-forms/src/test/scala/play/data/FormSpec.scala

use std `scala.jdk.OptionConverters` instead of `scala.compat.java8.OptionConverters`
- playframework dropped Scala 2.12 https://github.com/playframework/playframework/pull/10956
- https://github.com/scala/scala/blob/2.13.x/src/library/scala/jdk/OptionConverters.scala scala std lib has OptionConverters since Scala 2.13
- https://github.com/scala/scala-java8-compat/blob/ff64b0109e9445e71f9d7c66fd230be5d12d053b/src/main/scala/scala/compat/java8/OptionConverters.scala

avoid `compat.java8.OptionConverters`

---

project/Docs.scala

fix warnings
> [warn] /home/runner/work/playframework/playframework/project/Docs.scala:190:13: method run in trait JavaDoc is deprecated (since 1.4.0): Use variant that takes VirtualFiles
> [warn]     javadoc.run(sources, classpath, outputDir, options, incToolOpt, log, reporter)
> [warn]             ^
> [warn] one warning found
https://github.com/sbt/zinc/blob/57d03412abe3810be5762a8c8e8c55cbf622ed03/zinc-compile/src/main/scala/sbt/inc/Doc.scala#L108

fix warning in `project/Docs.scala`

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/test

Replaces #11344
I had a look at the test, it seems increasing the timeout a bit should do. The code and test looks ok. Maybe GitHub's virtual machines got slower...

Fix shutdown-downing scripted test by increasing the timeout

---

core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
documentation/manual/working/commonGuide/configuration/code/JavaLog4JLoggerConfigurator.java
documentation/manual/working/commonGuide/configuration/code/Log4j2LoggerConfigurator.scala

Partially addresses #11400 by using a method for finding a logger factory that should be compatible with SLF4J 2.0.0. The upgrade itself can be done separately and not backported to `2.8.x`.
Allows consumers to use SLF4J 2.0.0 in their projects without breaking Play 2.8 compatibility.
Makes `LogbackLoggerConfigurator` compatible with SLF4J 2.0.0, which has removed binding via finding a `StaticLoggerBinder` on the classpath, in favour of `ServiceLoader`. In practice, we don't need to implement any `ServiceLoader` logic because SLF4J provides `LoggerFactory.getILoggerFactory` (which is backwards/forwards compatible.)
Updates documentation references to `StaticLoggerBinder` as well.
`getILoggerFactory` has always provided the functionality we require, so it seems like the natural method to …

SLF4J 2 compatibility: avoid direct usage of StaticLoggerBinder

---

project/Dependencies.scala

Resolves #11419 and resolves #11400
Upgrading SLF4J to v2.0.0 forces us to upgrade Logback too, as explained on the [Logback documentation](https://logback.qos.ch/download.html).
We can't upgrade Logback to 1.4.1 as it needs at least Java 11, and we must keep the Java 8 compatibility for now.
Also removing an exluded dependency for HikariCP as it depends also on SLF4J 2.0.0.
Has been tested on Java 8 and Java 11.
Should fix PR #11417

 Fixing SLF4J 2.0.0 issue for #11419 and #11400

---

.scala-steward.conf

Thanks to #11435 we are building Play with Java 11, so no need to hold back those deps anymore.

scala-steward can now provide Java 11+ only dependencies

---

build.sbt

Publishing a first experimental milestone for the next Play major version [didn't work](https://github.com/playframework/playframework/actions/runs/3173494244/jobs/5169171990#step:5:2479). 
So, the `BillOfMaterialsPlugin` plugin [appends the dependency listings to `pomExtra`](https://github.com/lightbend/sbt-bill-of-materials/blob/86664c142cdc855c2e739a40f1b63d7f6b992db6/src/main/scala/com/lightbend/sbt/billofmaterials/BillOfMaterialsPlugin.scala#L89). Unfortunaly, until now, [we did the same as well.](https://github.com/playframework/playframework/blob/cdffc62844b395aa2ffb4f67e16a1625fe3bd1b0/build.sbt#L60), so the entries were duplicated.
Until now however this didn't cause any problems, because interplay "hard reseted" `pomExtra`, so it kind of overrode one of those settings. Since …

Fix duplicate `<dependencyManagement />` tag in BOM

---

.github/workflows/build-test.yml
documentation/build.sbt
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/releases/release26/Highlights26.md
documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/working/commonGuide/build/sbtDependencies.md
project/Dependencies.scala

I want to cut a new release, however it seems Scala 2.13.9 is a bit buggy (like https://github.com/scala/bug/issues/12650) and 2.13.10 will be released soon.
Reverting to the same versions we used to cut 2.8.16

[2.8.x] Revert "Upgrade to Scala 2.12.17 and 2.13.9"

---

build.sbt
project/Dependencies.scala

I think we don't need update document
I think we don't need add tests
No existed issue
`play-jdbc-api` declared a dependency to `play` but do not really depend on any `play`'s code.
This PR remove that _declaration_ dependency.
I use [anorm](/playframework/anorm) in some projects that use play and in some projects that do NOT use play.
To use anorm, we must [provide a connection](https://playframework.github.io/anorm/#executing-sql-queries), normally by using the `play-jdbc` module.
So I create a `play-jdbc-standalone` project which do NOT depends on Play (just copy code from `play-jdbc` with some minimal change.)
I can also copy code of `play-jdbc-api` but if this PR is merged then I don't need to do that 😄

Remove dependency from play-jdbc-api to play

---

core/play/src/main/scala/play/core/parsers/Multipart.scala

* No new files in this pull request.
* It looks there aren't documentations that we need to update  for this pull request. 
* StackOverflowError depends on an environment so it is difficult to check in unit tests, I think.
Fixes #10590 
Refactoring to avoid StackOverflowError easily when parsing multipart/form-data on `BodyPartParser` of `Multipart`
The current code uses recursive call so StackOverflowError is occurred. We need to estimate `maxMemoryBuffer` size in order to avoid the error.
https://github.com/playframework/playframework/issues/10590
I guess refactoring the code to use @tailrec or loop would avoid the error without estimating the size of `maxMemoryBuffer`.
https://github.com/playframework/playframework/discussions/11347

To refactor `BodyPartParser` of `Multipart` in order to avoid StackOverflowError easily

---

cache/play-caffeine-cache/src/main/resources/reference.conf
documentation/manual/releases/release29/migration29/Migration29.md

Signed-off-by: Felipe Bonezi <felipebonezi@gmail.com>
Fixes #10955 
Add maximum size to Caffeine Cache config using 10000 elements as a default value.
It's already implemented to read from Config file - i.e. `play.cache.caffeine.CaffeineParser` - but it wasn't using any default value.
Ref from #11181

Add maximum-size to Caffeine config.

---

cache/play-caffeine-cache/src/main/resources/reference.conf

First, please have a look at how these configs get parsed [here](https://github.com/playframework/playframework/blob/2.8.2/cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineParser.java#L53-L80).
Now, this is what I fixed:
- `weak-keys` was defined twice. No need.
- ~~`maximum-size` was missing in the config.~~ (fixed in #11317)
- `weak-values` was missing as well. Also **either** `weak-values` **or** `soft-values` should be set to `true` at a certain moment, not both at the same time, because if the "value strength" was set once, it can't be set to another value anymore, therefore setting both results in undertimed behaviour (we don't know which was set first). See the caffeine implementation: https://github.com/ben-manes/caffeine/blob/v3.1.1/caffeine/src/main/java/com/gi …

Fix caffeine config

---

.github/workflows/build-test.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

Use environment file instead `set-output`

---

.github/workflows/build-test.yml
.github/workflows/publish.yml

https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

[2.8.x] Use environment file instead `set-output`

---

core/play-integration-test/src/it/scala/play/it/http/websocket/WebSocketClient.scala
core/play-integration-test/src/it/scala/play/it/http/websocket/WebSocketSpec.scala
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyIdleHandler.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala

So a premium sponsor reached out to me regarding problems with Websockets.
Turns out the Netty server does not care about the `play.server.http.idleTimeout` config when upgrading a connection to a websocket. akka-http however works correctly (did extensive manually testing using https://github.com/vi/websocat and even wireshark to watch those frames).
The problem step-by-step:
1. The netty backend [sets up request handler](https://github.com/playframework/playframework/blob/919b5bda99b03a8ebeca956a6f6c0c6361ce9df5/transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala#L234-L237) which gets added to the netty pipeline via a `HttpStreamsServerHandler`.
2. Our `PlayRequestHandler` [reacts to `IdleStateEvents` to close connections if they are …

[2.8.x] Netty: Websockets should respect play.server.http.idleTimeout

---

core/play-integration-test/src/it/scala/play/it/http/websocket/WebSocketSpec.scala
documentation/manual/working/javaGuide/main/async/JavaWebSockets.md
documentation/manual/working/scalaGuide/main/async/ScalaWebSockets.md
transport/server/play-akka-http-server/src/main/scala/akka/http/play/WebSocketHandler.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/WebSocketHandler.scala
transport/server/play-server/src/main/resources/reference.conf
transport/server/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala

Finally.
Fixes #3861
Fixes https://github.com/akka/akka-http/issues/4147
Needs
With this patch one can set
```
play.server.websocket.periodic-keep-alive-max-idle = 10 seconds
```
in `application.conf` (or `PlayKeys.devSettings` for dev mode) to ping the client after the server didn't hear anything from it after 10 seconds. This is _exactly_ the way how it works in akka-http as well. You might also want to look at the notes in the [RFC about the ping and pong frames](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5.2).
This was inspired by akka-http's [implementation](https://github.com/akka/akka-http/blob/27598478891acc679c82654f1b0b7dbc6dc04647/akka-http-core/src/main/scala/akka/http/impl/engine/ws/WebSocket.scala#L60-L84), however I did not implement a custom payload for the …

[2.8.x] Add WebSocket ping/pong support

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/main/resources/logback.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/main/resources/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/main/scala/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/test/java/ws/WebSocketClient.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/test/scala/controllers/IntegrationTest.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/resources/logback.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/resources/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/scala/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/java/ws/WebSocketClient.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/scala/controllers/IntegrationTest.scala
transport/server/play-server/src/main/scala/play/core/server/ServerEndpoint.scala
transport/server/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala

Manual forward port of #11519 because we don't need Scala 2.12 compatibility anymore.
Scala 2.13+ makes things easier, see https://stackoverflow.com/a/56780934/810109 and https://www.scala-lang.org/files/archive/api/2.13.x/scala/StringContext$s$.html#unapplySeq(s:String):Option[Seq[String]]

Log websocket communication problems + handle special Netty case

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/main/resources/logback.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/main/resources/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/main/scala/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/test/java/ws/WebSocketClient.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-akka-http/src/test/scala/controllers/IntegrationTest.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/resources/logback.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/resources/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/main/scala/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/java/ws/WebSocketClient.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/scala/controllers/IntegrationTest.scala
transport/server/play-server/src/main/scala/play/core/server/ServerEndpoint.scala
transport/server/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala

(I am looking into this because a premium sponsor asked me because they run into problem regarding websockets.)
When a client closes a websocket connection, it's possible it sends an optional status code. Those status codes are defined here: https://www.rfc-editor.org/rfc/rfc6455#section-7.4
Now, if a client sends a status code not defined in that list (or one that is reserved for other purposes) **akka-http** does not care but let's the close status code pass through into the application code, so it does not distinguish between valid and invalid status codes.
**Netty** however is very strict, it does not pass a `play.api.http.websocket.CloseMessage` on into application code. As a consequence an app handling `CloseMessage` will never receive it, even though Netty closes the connection and …

[2.8.x] Log websocket communication problems + handle special Netty case

---

core/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala

[The Java API always worked like this](https://github.com/playframework/playframework/blob/a0aacb6555ab92b71528d2e46863d9f2118b7368/core/play-streams/src/main/java/play/libs/streams/ActorFlow.java#L100) and I think that makes most sense, otherwise one might not be aware that message get dropped, see #6246

Scala's ActorFlow.actorRef() should fail on overflow, like Java does

---

core/play-logback/src/main/resources/logback-play-default.xml
documentation/manual/working/commonGuide/configuration/SettingsLogger.md
documentation/manual/working/commonGuide/database/code/logback-play-logSql.xml

This reverts the changes from #8407 / #8277.
I am sure we don't want logback to shut down the logger context by using`<shutdownHook />` (anymore), because Play already handlest that (at least since v2.7). Actually with `<shutdownHook />` in place, a Play app closes the logger context to early and **logs are lost (!)**...
So what does `<shutdownHook />` actually do?
It [registers](https://github.com/qos-ch/logback/blob/v_1.2.11/logback-core/src/main/java/ch/qos/logback/core/joran/action/ShutdownHookAction.java#L85) a [JVM shutdown hoook](https://docs.oracle.com/en/java/javase/11/docs/api/java.base/java/lang/Runtime.html#addShutdownHook(java.lang.Thread)). So when the JVM shuts down, this hook will automatically close the logger context after a delay... By default that delay is 0, so it …

Do not use/recommend shutdownHook in Logback, Play handles that

---

documentation/manual/ModuleDirectory.md

Signed-off-by: Felipe Bonezi <felipebonezi@gmail.com>
Fixes #10911
Add the `play-secret-rotation` library into public module documentation.

Add play-secret-rotation to public module docs

---

core/play-integration-test/src/it/java/play/routing/AbstractRoutingDslTest.java
core/play/src/main/java/play/mvc/BodyParser.java
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/java/play/mvc/MultipartFormatter.java
core/play/src/main/scala/play/api/http/Writeable.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala
core/play/src/main/scala/play/core/formatters/Multipart.scala
core/play/src/main/scala/play/core/j/JavaParsers.scala
core/play/src/main/scala/play/core/parsers/Multipart.scala
core/play/src/test/scala/play/api/http/WriteableSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/main/java/controller/HomeController.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/main/resources/logback.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/main/resources/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/test/java/controllers/HomeControllerTest.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/test
documentation/manual/working/javaGuide/main/upload/JavaFileUpload.md
documentation/manual/working/scalaGuide/main/upload/code/ScalaFileUpload.scala
project/BuildSettings.scala
testkit/play-test/src/main/scala/play/api/test/Helpers.scala
testkit/play-test/src/test/java/play/test/HelpersTest.java

Fixes #11496 
Handles the case of multipart form data in the java `Helpers` api so that java based routes and tests that accept multipart form data files can be properly tested.
This is my first contribution here, so interested in feedback on implementation:
- I extracted a `FilePart.asScala()` method to keep the codebase DRY. However this method is now in the public API. Is this acceptable? It seemed somewhat appropriate as there are a bunch of similar methods in the same file for similar classes to convert to scala.
- The different types of generic "files" are still not terribly well handled for multipart form data. Only `MultipartFormData[TemporaryFile]` is handled. The types are cooerced somewhat awkwardly, but seems like there's likely diminishing returns with how many cases should …

Handle java multipart form data on requests in test Helpers

---

documentation/manual/working/commonGuide/production/ConfiguringHttps.md

I think documentation wrongly advised downgrading JDK to JDK 8. Given that minimal JDK version seems to be 8, whole paragraph is not applicable. I deleted it.

Updating documentation - ConfiguringHttps.md

---

.github/workflows/build-test.yml

The nightly build [is failing](https://github.com/playframework/playframework/actions/workflows/build-test.yml?query=event%3Aschedule) since #11523 got merged. That's because there akka-http was upgraded from 10.2.7 to 10.2.10, which changed it's behaviour in regards to idle timeouts (for the better), see https://github.com/akka/akka-http/pull/3965
It turns out that at some point in our main branch we upgraded from akka-http 10.1.x to 10.2.x before, however the nightly tests kept using the latest 10.1.x snapshot. Seems like we didn't notice that because all tests passed until now... (Which speaks for akka-http's compatibility :wink:)
Now I tried to change the version used by nightlies so that GitHub actions pulls in the latest akka-http 10.2.x snaphots, but that is failing now with the …

For nightly builds fetch and determine akka-http 10.2.x snapshot, not 10.1.x (but don't use it actually)

---

project/plugins.sbt

For next Play 2.8.x release.
Details here: https://github.com/playframework/interplay/pull/230

[2.8.x] Interplay 2.1.11 to avoid out of memory with gpg

---

web/play-filters-helpers/src/main/scala/play/filters/csp/CSPConfig.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala
web/play-filters-helpers/src/main/scala/play/filters/hosts/AllowedHostsFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/csp/CSPFilterSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFCommonSpecs.scala
web/play-filters-helpers/src/test/scala/play/filters/csrf/CSRFFilterSpec.scala
web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala

For the CSP, CSRF and AllowedHosts filters, route modifier tags can be used to whitelist routes, which then should not be checked by the filter, also blacklists can be used, see e.g. the explanation of the [config here](https://github.com/playframework/playframework/blob/cc3040da2e56e4868525abe4d66534169e9c4668/web/play-filters-helpers/src/main/resources/reference.conf#L100-L109).
Now while reviewing #10536 I realized that when both the white and the blacklist are empty the filters suddenly starte to be permissive and do not check anything anymore...
E.g. if you have a routes file
```
POST /    app.controllers.AppController.foo
+ nocsrf
POST /    app.controllers.AppController.bar
```
and keep the default whitelist that ships with Play, the `bar` route will not be checked ("nocsrf" = do …

Filters should be restrictive when their route modifier black-/whitelist both are empty

---

core/play/src/main/java/play/libs/concurrent/ClassLoaderExecution.java
core/play/src/main/java/play/libs/concurrent/ClassLoaderExecutionContext.java
core/play/src/main/java/play/libs/concurrent/CustomExecutionContext.java
core/play/src/main/java/play/libs/concurrent/HttpExecution.java
core/play/src/main/java/play/libs/concurrent/HttpExecutionContext.java
core/play/src/main/scala/play/api/inject/BuiltinModule.scala
core/play/src/main/scala/play/core/j/ClassLoaderExecutionContext.scala
core/play/src/main/scala/play/core/j/HttpExecutionContext.scala
core/play/src/main/scala/play/core/j/JavaAction.scala
documentation/manual/working/commonGuide/configuration/ThreadPools.md
documentation/manual/working/commonGuide/configuration/code/detailedtopics/clec/MyController.java
documentation/manual/working/javaGuide/main/async/JavaAsync.md
documentation/manual/working/javaGuide/main/async/code/javaguide/async/controllers/Application.java
documentation/manual/working/javaGuide/main/logging/code/javaguide/logging/JavaMarkerController.java

Fixes #10218
FYI: First commit renamed the classes with help of IntelliJ, second commit readds those classes with deprecation notes.

Rename HttpExecution[Context] to ClassLoaderExecution[Context]

---

build.sbt
project/VersionHelper.scala

Fixes #11143 
Add a custom method for sbt-dynver to compute the version by:
- not including the distance
- incrementing minor version (or patch version later)

chore(#11143): set next minor version when being on main branch

---

project/VersionHelper.scala

I think this change is actually important for newcomers that want to run scripted tests and/or want to test changes locally in apps without unnecessary hassles.
Currently when cloning the Play repo and running sbt, the version of the project looks like
* `2.9.0-M3-55c8861d+20230124-0041-SNAPSHOT` if the worktree is "dirty"
* `2.9.0-M3-55c8861d-SNAPSHOT` if the worktree is "clean"
(before #11168 `...-M3-...` would have been `...-M2-...`, but that does not matter here)
This might not look like a big deal and we couldn't care less about that version string, however it could turn into an annoying problem when running scripted tests. It did happen to me not just once, that after I ran `publishLocal` and then did some minor, often not relevant changes and, for whatever reason restarted sbt, and …

Render sha and dirty part in version only when on CI

---

core/play/src/main/scala/play/core/formatters/Multipart.scala

Previously, given a `length` argument outside of the acceptable range (1 to 70, inclusive) `Multipart.randomBoundary` would fail to throw the expected exception.
This change will allow the expected exception to be thrown.

Fix length validation in Multipart.randomBoundary

---

project/plugins.sbt

Pull in just released Scala 3.3.0-RC2:
* https://contributors.scala-lang.org/t/3-3-0-release-thread/6079
* https://github.com/lampepfl/dotty/releases/tag/3.3.0-RC2

Upgrade interplay, provides Scala 3.3.0-RC2

---

project/BuildSettings.scala

Just avoids confusion what to do with 2.13.10 here when adding support for Scala 3.

Keep default for crossScalaVersion PlayNonCrossBuiltProject

---

build.sbt
cache/play-caffeine-cache/src/test/scala/play/api/cache/caffeine/CaffeineCacheApiSpec.scala
core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
documentation/manual/releases/release29/migration29/Migration29.md
documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWSSpec.scala
documentation/manual/working/scalaGuide/main/logging/code/ScalaLoggingSpec.scala
documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithSpecs2.md
documentation/manual/working/scalaGuide/main/tests/code/models/UserSpec.scala
documentation/manual/working/scalaGuide/main/tests/code/specs2/ExampleMockitoSpec.scala
documentation/manual/working/scalaGuide/main/tests/code/specs2/UserServiceSpec.scala
project/Dependencies.scala
testkit/play-test/src/test/scala/play/api/test/InjectingSpec.scala
transport/client/play-ahc-ws/src/test/scala/play/api/libs/ws/ahc/AhcWSSpec.scala
transport/server/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala
web/play-openid/src/test/scala/play/api/libs/openid/DiscoveryClientSpec.scala
web/play-openid/src/test/scala/play/api/libs/openid/OpenIDSpec.scala
web/play-openid/src/test/scala/play/api/libs/openid/WsMock.scala

Replace specs2-mockito with vanilla mockito in preparation for scala 3. 
author of specs2 [recommends switching to ScalaMock](https://github.com/etorreborre/specs2/issues/1079#issuecomment-1092863601), but that doesn't have Scala 3 artifacts yet as well: https://github.com/paulbutcher/ScalaMock/issues/429
https://github.com/playframework/playframework/pull/11266
https://github.com/playframework/playframework/pull/11550

replace specs2-mockito with vanilla mockito

---

core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/scala/play/core/j/JavaHelpers.scala
core/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
project/BuildSettings.scala

Rename methods back to their original names after deprecations in 2.8.0

---

core/play-logback/src/main/resources/logback-play-default.xml
core/play-logback/src/main/resources/logback-play-dev.xml
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/maven-layout-twirl-reload/src/main/resources/logback.xml
documentation/manual/working/commonGuide/database/code/logback-play-logSql.xml

Fixes #11504
See https://logback.qos.ch/manual/layouts.html#coloring
`coloredLevel` dates back to Play 2.0-RC1 in 2011: https://github.com/playframework/playframework/commit/cdd8a71f2559bbbfa4c7d4cb93933a57399d3405#diff-dc85c729087445b29c1ed7724db1616b6613c3d852cfdc0775b9c322fa320fe8R88
This was 6 months before logback introduced the `%highlight` pattern in 2012:
https://github.com/qos-ch/logback/commit/ab97eb0bd5c9459ac1d21a32e57b4a0beea7be14
Intersting thing is we already use that in the play-scala and play-java seed projects anyway, so this is nothing really new.

Switch from coloredLevel to %highlight(%-5level)

---

core/play-integration-test/src/it/scala/play/it/http/BadClientHandlingSpec.scala
core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-akka-http-server/src/main/scala/play/core/server/akkahttp/AkkaModelConversion.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala
transport/server/play-server/src/main/scala/play/core/server/Server.scala
transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala

Partly fixes #11113 by enabling one of the two tests that had do be disabled when ugrading akka-http to 10.2.x.
~akka-http 10.2.0 introduced a parsing mode, which by default is set to strict~ (I was wrong here, the parsing mode existed before already). See
* comments in akka's reference.conf: https://github.com/akka/akka-http/blob/v10.2.10/akka-http-core/src/main/resources/reference.conf#L690-L698
* https://github.com/akka/akka-http/issues/3504

Use uri parsing mode "relaxed" in akka-http 10.2.x

---

core/play-integration-test/src/it/scala/play/it/http/UriHandlingSpec.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala

Fully fixes #11113
Since akka-http 10.2.0, an incorrect percent-encoded uri character will be immediately handled as 400 bad request by akka-http. It gives us (Play) no chance to handle that, so we never see this error in the Play akka-http backend. There is nothing we can do really. So I had to adjust the test, and as part of that I also made netty behave the same (not going through the error handler when it parses incorrect percent-encoded chars). This is because I want to have both http backends to be as much compatible as possible in case one gets replaced by the other.

Handle incorrect percent-encoded query chars

---

core/play/src/main/java/play/libs/typedmap/TypedMap.java
core/play/src/main/java/play/mvc/Http.java
core/play/src/main/scala/play/api/libs/typedmap/TypedMap.scala
core/play/src/main/scala/play/api/mvc/Request.scala
core/play/src/main/scala/play/api/mvc/RequestHeader.scala
core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/main/scala/play/api/mvc/request/RequestFactory.scala
core/play/src/main/scala/play/core/j/JavaHelpers.scala
core/play/src/test/scala/play/core/test/Fakes.scala
project/BuildSettings.scala
testkit/play-test/src/main/scala/play/api/test/Fakes.scala

Fixes #10221 
* Deprecates `-` and `+` Scala symbol methods in `TypedMap`. 
* Adds `updated` and `removed` functions that serve the same purpose.
* Changes outside calls to `+`, `-`, `$plus`, and `$minus` to `updated`/`removed`.
* Adds an ignore rule for MiMa compatibility - new signature doesn't break backwards compatibility.
In the future, postfix symbolic operators are going to be deprecated for methods with multiple parameters. Thus, this change is necessary to meet that need. The original ticket suggests removing _all_ of those operators.
I opted to deprecate the old methods, in case others are using them.

Deprecate TypedMap symbols and replace with named functions

---

.github/workflows/dependency-graph.yml

See https://github.com/playframework/play-meta/issues/242
Submits dependencies to the GitHub dependency graph. This allows dependabot to detect vulnerable dependencies

Set up sbt dependency submission

---

.github/workflows/dependency-graph.yml

However waiting on feedback for https://github.com/scalacenter/sbt-dependency-submission/issues/84 first.

Avoid double submission of the dependency graph

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/build.sbt.1
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/messages-fail-scala2.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/messages-fail-scala3.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/messages-fail.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2-scala2.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2-scala3.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode-compile-and-config-error-source/twirl-fail-2.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/play-position-mapper/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/build.sbt

Nothing special, just Scala 2 vs Scala 3 compiler output / exception messages sometimes differ a little from each other.
Also adjust compiler flags.
Split out from #11551

Prepare scripted tests for Scala 3

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/app/utils/JavaScriptRouterGenerator.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/app/utils/JavaScriptRouterGenerator.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/app/utils/JavaScriptRouterGenerator.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/app/utils/JavaScriptRouterGenerator.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/utils/JavaScriptRouterGenerator.scala

See https://docs.scala-lang.org/scala3/book/methods-main-methods.html#backwards-compatibility-with-scala-2
Split out from #11551

Explicit `main` method needed for Scala 3

---

core/play-integration-test/src/it/scala/play/it/libs/JavaFormSpec.scala
web/play-java-forms/src/test/scala/play/data/FormSpec.scala
web/play-java-forms/src/test/scala/play/data/PartialValidationSpec.scala

Split off from #11551, but slightly different by keeping getters and setters because we want to test the Java Form api (even though it's a bit stupid to do that in Scala code, but I am not going to put that in Java files now. It's "just" tests anyway.)
See 
* https://docs.scala-lang.org/scala3/guides/migration/incompat-other-changes.html#invisible-bean-property
* https://github.com/lampepfl/dotty/issues/11972

Scala 3: Can't use BeanProperty in Scala code to test Java API

---

project/BuildSettings.scala
transport/client/play-ws/src/main/scala/play/api/libs/ws/WSRequest.scala

Avoids following compilation error in Scala 3:
```scala
[error] -- Error: ./transport/client/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSRequest.scala:21:11 
[error] 21 |case class AhcWSRequest(underlying: StandaloneAhcWSRequest) extends WSRequest with WSBodyWritables {
[error]    |           ^
[error]    |class AhcWSRequest needs to be abstract, since:
[error]    |it has 4 unimplemented members.
[error]    |/** As seen from class AhcWSRequest, the missing signatures are as follows.
[error]    | *  For convenience, these are usable as stub implementations.
[error]    | */
[error]    |  override def addHttpHeaders(hdrs: Seq[(String, String)]): AhcWSRequest.this.Self = ???
[error]    |  override def addQueryStringParameters
[error]    |  (parameters: Seq[(String, String)]): …
```

Scala 3: Avoid making `AhcWSRequest` abstract

---

build.sbt
project/BuildSettings.scala

Trying to apply `-Xsource:3` makes this project fail to compile (but interestingly it compiles with Scala 3...)
I was asking myself why this project even exists, it's not used anywhere, turns out:
* https://github.com/playframework/playframework/issues/5290
In theory we could remove it and Play would still work...

Scala3: No `-Xsource:3` for RoutesCompilerProject (with explanations)

---

core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/main/scala/play/api/mvc/macros/BinderMacros.scala
core/play/src/test/scala/play/api/mvc/BindersSpec.scala

While working on the macro stuff for Scala 3 I noticed two bugs:
* When transforming a PathBindable the original javascript unbind method does not get used anymore, which can cause problems for certain types that do not use the default javascript unbind method (e.g. Boolean). All Java types are affected from this "bug", however in real life it should not matter since all use the default method anyway, except boolean, but even for that the default js function should work anyway. It could cause problems for user defind binders however...  This has been fixed for the QuerystringBindable long time ago already: #3854
* The macro code handling `AnyVal` regarding Pathbindable also does not correctly transform an AnyVal. Even when the above is fixed, the macro does create a new instance which …

Fix transforming of PathBindable and also the anyValPathBindable macro

---

core/play-configuration/src/main/scala/play/api/Configuration.scala
core/play-configuration/src/test/scala/play/api/ConfigurationSpec.scala

Implement implicits for `ConfigLoader[java.time.Duration]` and `ConfigLoader[Seq[java.time.Duration]]`. This makes it easier to parse configuration that is used for java API's that expect a `java.time.Duration`.

Add ConfigLoader implicits for java.time.Duration

---

core/play-configuration/src/main/scala/play/api/Configuration.scala
core/play-configuration/src/test/scala/play/api/ConfigurationSpec.scala
core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
core/play/src/test/scala/play/api/routing/sird/UrlContextSpec.scala
dev-mode/play-docs-sbt-plugin/src/main/scala/com/typesafe/play/docs/sbtplugin/PlayDocsValidation.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
web/play-openid/src/test/scala/play/api/libs/openid/DiscoveryClientSpec.scala
web/play-openid/src/test/scala/play/api/libs/openid/package.scala

Fix warnings in JDK 20 or later
replace `new URL(arg)` to `new URI(arg).toURL` 
- https://bugs.openjdk.org/browse/JDK-8295949
- https://github.com/openjdk/jdk/commit/4338f527aa81350e3636dcfbcd2eb17ddaad3914

avoid deprecated `java.net.URL` constructor

---

project/Dependencies.scala

Pulls in correct akka Scala 3 dependencies (before it was using `.cross(CrossVersion.for3Use2_13))`)

play-ws 2.2.0-M3

---

core/play/src/main/scala/play/api/Application.scala

Fix waring in Scala 3
remove `final` modifier
```
[warn] -- [E147] Syntax Warning: /home/runner/work/playframework/playframework/core/play/src/main/scala/play/api/Application.scala:220:14 
[warn] 220 |private[play] final case object ApplicationStoppedReason extends CoordinatedShutdown.Reason
[warn]     |              ^^^^^
[warn]     |              Modifier final is redundant for this definition
```

fix warning

---

build.sbt
dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
project/Dependencies.scala
project/Tasks.scala

Running tests with Scala 3 needs to be done with a `-Dscala3Tests=true` flag.
This causes akka dependencies to use `cross(CrossVersion.for3Use2_13)`.  That's because we use `for3Use2_13` for akka-http as well. If we wouldn't apply `for3Use2_13` for akka now, akka-http would not be able to work with akka Scala 3 artifacts... In short: It sucks.
The flag also excludes some other dependencies were _3 and _2.13 are conflicting now because of the above.
The flag only should be applied when running tests. because for publishing we do want to publish all dependencies with `_3`.
I am working on some sbt plugin magic for the akka-http sbt plugin so it switches to `for3Use2_13` when using it with Scala 3 automatically. Not sure if it will work, but we will see.

Work around missing `akka-http` Scala 3 artifacts for tests

---

core/play-integration-test/src/it/scala/play/it/i18n/LangSpec.scala

`Around` got removed in specs2 5.x because of it's usage of `DelayedInit` which doesn't work anymore in Scala 3.
For this test that didn't matter, but still better to avoid using it.

Avoid usage of specs2 Around

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
project/BuildSettings.scala

Just bumped into that when using `-Werror`/`-Xfatal-warnings` in Scala 3.

Use scala.jdk converter also for Scala 3 in twirl templates

---

testkit/play-test/src/test/java/play/test/HelpersTest.java
transport/server/play-server/src/test/scala/play/core/server/ProdServerStartSpec.scala

Fix warings
```
[warn] /home/runner/work/playframework/playframework/testkit/play-test/src/test/java/play/test/HelpersTest.java:152:1: unchecked conversion
[warn]   required: java.util.Map<java.lang.String,java.lang.String[]>
[warn]   found:    java.util.HashMap
[warn] new java.util.HashMap()
```
https://github.com/google/guava/blob/4d2b6ffb312a4ebf8aa377982fc98a7ece0bc3fd/android/guava/src/com/google/common/io/Files.java#L428-L429
```
[warn] /home/runner/work/playframework/playframework/transport/server/play-server/src/test/scala/play/core/server/ProdServerStartSpec.scala:93:23: method createTempDir in class Files is deprecated
[warn]     val temp = GFiles.createTempDir()
[warn]                       ^
```

fix warnings

---

core/play/src/main/java/play/controllers/AssetsComponents.java
core/play/src/main/scala/play/api/controllers/Assets.scala
core/play/src/main/scala/play/utils/Resources.scala
core/play/src/test/scala/play/api/controllers/AssetsSpec.scala
core/play/src/test/scala/play/utils/ResourcesSpec.scala
documentation/manual/working/commonGuide/build/code/javaguide/common/build/controllers/Assets.java
documentation/manual/working/commonGuide/build/code/scalaguide/common/build/controllers/SubProjectsAssetsBuilder.scala
documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/dependencyinjection/controllers/Assets.java
documentation/manual/working/javaGuide/main/dependencyinjection/code/javaguide/di/components/CompileTimeDependencyInjection.java
documentation/manual/working/scalaGuide/main/dependencyinjection/code/CompileTimeDependencyInjection.scala

This pull request only supports the `resource` scheme. I will not add support for other graalvm features.
graalvm requires resources to be accessed with a scheme called `resource`. So Play needs to handle the `resource` scheme properly.
- The implementation has been copied over from the existing `bundleresource` scheme as it is functionally equivalent.
- Accessing the directory results in an invalid file download. This is because the `resource` scheme cannot tell if the file is a directory.
Discussion for #11253

Add `resource` scheme for #11253

---

core/play/src/main/scala/play/core/routing/GeneratedRouter.scala
core/play/src/main/scala/play/core/routing/package.scala

The purpose of this PR is to refactor deprecated/redundant logic.
*I replaced some packages, but I end up reverting 2 of them for supporting Scala 2.12
- ~~collection.JavaConverters is deprecated from Scala 2.13.0, so I replaced~~
- ~~reference: [JavaConverters](https://www.scala-lang.org/api/current/scala/collection/JavaConverters$.html)~~
- Either is right-biased, so removed `.right` from for comprehensions.
- reference: [scala.util Either](https://www.scala-lang.org/api/current/scala/util/Either.html)
- ~~Symbol mapValues is deprecated, so replaced to `.view.mapValues`~~
- ~~reference: IntelliJ sugguestion~~
- removed curly braces if code can be written in one liners
- I found some deprecated codes, so tried to replace them.
N/A

Refactor: replaced some deprecated / redundant logic

---

testkit/play-test/src/main/scala/play/api/test/Helpers.scala
testkit/play-test/src/test/scala/play/api/test/HelpersSpec.scala

The test helper mixin [play.api.test.RouteInvokers](https://www.playframework.com/documentation/latest/api/scala/play/api/test/RouteInvokers.html) contains helper methods for executing the route and action of an Application instance.
To aid in testing routers built with [String Interpolating Routing DSL](https://www.playframework.com/documentation/latest/ScalaSirdRouter), this PR adds test helper methods to execute a Router instance directly.
These methods are for convenience, so that the test does not need to build a fake application to invoke the router.

Add to RouteInvokers test helper

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-downing/src/main/resources/application.conf
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/shutdown-happy-path/src/main/resources/application.conf

Those scripted tests fail randomly, in the last weeks and months even more often.
So I took time to figure out what's the cause and I think I found it: We need to give the (forced) coordinated shutdown hooks more time to finish. If we don't, the server immediately shuts down all connections after a hard timeout of 5 seconds and the pending request can not be answered anymore, which makes the scripted test fail (which tries to re-send the request like 10 times until it fails)

Fix the shutdown scripted tests

---

dev-mode/routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes

Fix reverse routes generated code. 
escape if Scala keyword
play generate following code and scalac report compile error before this fix
```
[error] target/scala-2.13/routes/main/controllers/ReverseRoutes.scala:382:35: illegal start of simple expression
[error]         case (_pf_escape_type) if type == "x" =>
[error]                                   ^
[error] target/scala-2.13/routes/main/controllers/ReverseRoutes.scala:383:97: '=>' expected but ';' found.
[error]           implicit lazy val _rrc = new play.core.routing.ReverseRouteContext(Map(("type", "x"))); _rrc
[error]                                                                                                 ^
[error] two errors found
```

fix reverse routes escape with fixed param

---

core/play-java/src/main/scala/play/routing/RouterBuilderHelper.scala
core/play/src/main/scala/play/api/routing/sird/PathExtractor.scala
core/play/src/main/scala/play/core/j/JavaAction.scala
transport/server/play-server/src/main/scala/play/core/server/common/ForwardedHeaderHandler.scala

use `lazyZip` 
`lazyZip` is more efficient
https://github.com/scala/scala/blob/aa326fcc429d9a8e7f262eaab71f43a500d37b17/src/library/scala/collection/LazyZipOps.scala#L26-L34

use `lazyZip` instead of `zip` if possible

---

core/play/src/main/scala/play/core/parsers/FormUrlEncodedParser.scala
core/play/src/test/scala/play/api/routing/sird/UrlContextSpec.scala

https://github.com/scala/scala/blob/aa326fcc429d9a8e7f262eaab71f43a500d37b17/src/library/scala/collection/Iterable.scala#L573-L608

use `groupMap` if possible

---

core/play-guice/src/main/java/play/libs/akka/BinderAccessor.java
core/play-guice/src/main/scala/play/api/inject/guice/GuiceInjectorBuilder.scala
core/play-guice/src/main/scala/play/api/libs/concurrent/AkkaGuiceSupport.scala
core/play-integration-test/src/it/scala/play/it/http/JavaRequestsSpec.scala
core/play-integration-test/src/it/scala/play/it/http/JavaResultsHandlingSpec.scala
core/play/src/main/scala/play/core/j/JavaResults.scala
core/play/src/test/scala/play/api/i18n/MessagesSpec.scala
core/play/src/test/scala/play/api/libs/TemporaryFileReaperSpec.scala
persistence/play-jdbc/src/test/scala/play/api/db/DatabasesSpec.scala
transport/server/play-server/src/main/scala/play/core/server/common/PathAndQueryParser.scala
transport/server/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala

* [NA] Have you added copyright headers to new files?
* [NA] Have you checked that both Scala and Java APIs are updated?
* [NA] Have you updated the documentation for both Scala and Java sections?
* [NA] Have you added tests for any changed functionality?
Fixes #xxxx
Compiling the codebase with Scala 2.13.5 generates a ton of warnings. This PR eliminates a lot of them (but not all).
Maintaining a project with that many warnings isn't right.

Clean up eliminate warnings tackle deprecations

---

project/Dependencies.scala

See [this discussion](https://github.com/google/guice/issues/1383), specially https://github.com/google/guice/issues/1383#issuecomment-1523410855: 
The way I see it right now is that we probably should wait for Guice 7 (which should also come soon) before we switch to the jakarta namespace.
Upgrading Guice also unlocks Java 18-21 as a side effect because it upgrades asm.

Guice 6.0.0-rc2

---

documentation/manual/working/commonGuide/schedule/code/scalaguide/scheduling/CodeBlockTask.scala

Documentation of [Scheduled Tasks](https://www.playframework.com/documentation/2.8.x/ScheduledTasks)
To show the correct Scala method to use when wanting a single delayed run of a task.
I noticed a difference between the Scala and Java examples for the section `Or to run a block of code once 10 seconds from now`. The Java code correctly uses `scheduleOnce` while Scala uses `scheduleWithFixedDelay`. Looking at the history of `CodeBlockTask.scala`, I saw that the change was an error.
None

Fix documentation of scheduleOnce

---

persistence/play-jdbc/src/main/resources/reference.conf
persistence/play-jdbc/src/main/scala/play/api/db/HikariCPModule.scala
persistence/play-jdbc/src/test/scala/play/api/db/HikariCPConfigSpec.scala

Support setting of hikari keepaliveTime

---

core/play-integration-test/src/it/scala/play/it/http/parsing/XmlBodyParserSpec.scala
core/play/src/test/scala/play/libs/XMLSpec.scala
core/play/src/test/scala/play/utils/ResourcesSpec.scala
dev-mode/routes-compiler/src/test/scala/play/routes/compiler/RoutesCompilerSpec.scala
documentation/build.sbt
documentation/manual/working/javaGuide/main/ws/code/javaguide/ws/JavaWS.java
documentation/manual/working/scalaGuide/main/ws/code/ScalaWSSpec.scala
project/plugins.sbt
transport/server/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala

Plus, after reading https://github.com/sbt/sbt/releases/tag/v1.8.3, prefer `java.nio.file.Files.createTempFile`, however that does not really matter for Play since only tests use `File.createTempFile` currently. But I changed it anyway because of best practice...

Scala 3.3.0-RC6

---

project/Dependencies.scala

So, I have been busy hacking on
* [sbt-web PRs](https://github.com/sbt/sbt-web/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+updated%3A%3E%3D2023-05-01+)
* [sbt-web-build-base PRs](https://github.com/sbt/sbt-web-build-base/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+updated%3A%3E%3D2023-05-01+)
* [sbt-js-engine PRs](https://github.com/sbt/sbt-js-engine/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed+updated%3A%3E%3D2023-05-01+)
Summary:
* Thanks to jroper, sbt-web removed it's dependency on akka (https://github.com/sbt/sbt-web/pull/169) which simplifies the the project and the other projects ([specially the sbt-js-engine one](https://github.com/sbt/sbt-js-engine/pull/66)) quite a lot. Also it fixes a [memory leak.](https://github.com/sbt/sbt-web/issues/170).
* The …

Upgrade sbt-web and sbt-js-engine

---

core/play-integration-test/src/it/scala/play/it/ServerIntegrationSpecificationSpec.scala
documentation/manual/working/scalaGuide/main/tests/ScalaFunctionalTestingWithSpecs2.md
testkit/play-test/src/main/java/play/test/TestServer.java
testkit/play-test/src/main/scala/play/api/test/Helpers.scala
testkit/play-test/src/main/scala/play/api/test/TestServer.scala
testkit/play-test/src/main/scala/play/api/test/TestServerFactory.scala
testkit/play-test/src/test/scala/play/api/test/HelpersSpec.scala

Fixes #10927. Looks like this had a previous PR that stalled out: https://github.com/playframework/playframework/pull/11179. I cleaned up the remaining work and verified the changes
- rebased and targeted to main
- Fixed compilation issues
- FIxed format issues
Additional changes
-  I modified the values to be `def`s rather than `lazy vals` so that the system property values can more easily be tested and modified programmatically 
- added test coverage
- Updated documentation
Adds ability to specify hostname to bind server to so that test server. This is mainly to serve the use case of having the test server local only.

Fix #10927 - Add ability to configure a test address to bind

---

documentation/manual/working/commonGuide/build/code/dependencies.sbt
documentation/manual/working/javaGuide/main/sql/JavaJPA.md
documentation/manual/working/javaGuide/main/sql/code/JPARepository.java
documentation/manual/working/javaGuide/main/sql/code/jpa.sbt
persistence/play-java-jpa/src/main/java/play/db/jpa/DefaultJPAApi.java
persistence/play-java-jpa/src/main/java/play/db/jpa/JPAApi.java
persistence/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
persistence/play-java-jpa/src/test/java/play/db/jpa/TestEntity.java
persistence/play-java-jpa/src/test/resources/META-INF/persistence.xml
project/BuildSettings.scala
project/Dependencies.scala

**Update:** See [this comment below](https://github.com/playframework/playframework/pull/11079#issuecomment-1533826580).
~Hibernate switched from `hibernate-core` to `hibernate-core-jakarta` that's probably why scala-steward does not kick in for this artifacts anymore.~ Hibernate did not change the groupId, they just offered `*-jakarta` artifacts with the jakarta namespace for their 5.5. and 5.6 release before sunsetting the `*-jakarta` groupId again and moving their main artifact to the jakarta namespace.
See https://hibernate.org/orm/releases/5.5/#whats-new
> Hibernate ORM 5.5 adds new artifacts with the artifact id suffix "-jakarta" like hibernate-core-jakarta.
The hibernate-core-jakarta artifact implements the Jakarta JPA 3.0 specification, while the hibernate-core artifact still …

Switch to Jakarta JPA

---

project/Dependencies.scala

Fixes incompatibility I experienced when working with the play-samples with a project that uses sbt-rjs

New sbt-js-engine milestone

---

core/play/src/main/scala/play/api/libs/EventSource.scala
core/play/src/test/scala/play/api/libs/EventSourceSpec.scala

Fixes #11834 
I passed -1 to split in the formatted of the Event object to keep the trailing newline.

Support trailing newline in SSR

---

build.sbt
project/Dependencies.scala

* https://github.com/scala/scala-xml/releases/tag/v1.3.1
* https://github.com/scala/scala-xml/pull/677
Avoids `StackOverflowError` in Play body parsers.
Made a lengthy comment with explanation.

[2.8.x] scala-xml 1.3.1

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/Play.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayImport.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
documentation/manual/working/javaGuide/main/akka/JavaAkka.md
documentation/manual/working/javaGuide/main/akka/code/javaguide.akkaupdate.sbt
documentation/manual/working/scalaGuide/main/akka/ScalaAkka.md
documentation/manual/working/scalaGuide/main/akka/code/scalaguide.akkaupdate.sbt

We don't ship with those versions, but people a are free to upgrade akka/akka-http themselves.
~This PR makes sure that when using the default `PlayAkkaHttpServer` plugin detect the usage of Scala 3 and akka 2.8+ to avoid applying any workarounds that are needed for akka-http 10.2.x (since this version does not ship Scala 3 artifacts)~
Detection is not reliable possible, so I introduced `PlayKeys.akkaHttpScala3Artifacts`.

Make Play compatible with akka 2.8+ / akka-http 10.5+ when using Scala 3

---

core/play-logback/src/main/scala/play/api/libs/logback/LogbackLoggerConfigurator.scala
project/Dependencies.scala

Fixes #11907
Library users can update their Logback libraries to the latest version by porting ContextInitializer#configureByResource, which was removed in Logback 1.4.9 and 1.3.9.
As noted in the referenced issue, this is due to the fact that Logback has removed the deprecated method.
Nothing

Fix missed ContextInitializer#configureByResource

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/app/controllers/HomeController.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/conf/application.conf
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/conf/evolutions/default/1.sql
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/conf/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/integration-tests/conf/application.conf
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/integration-tests/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/integration-tests/test/controllers/HomeControllerSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolution-path-config/test
documentation/manual/releases/release29/Highlights29.md
documentation/manual/working/commonGuide/database/Evolutions.md
documentation/manual/working/javaGuide/main/tests/JavaTestingWithDatabases.md
documentation/manual/working/javaGuide/main/tests/code/javaguide/tests/JavaTestingWithDatabases.java
documentation/manual/working/scalaGuide/main/tests/ScalaTestingWithDatabases.md
documentation/manual/working/scalaGuide/main/tests/code/database/ScalaTestingWithDatabases.scala
persistence/play-jdbc-evolutions/src/main/resources/reference.conf
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/Evolutions.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsModule.scala
persistence/play-jdbc-evolutions/src/test/resources/evolutions_non_default_path/db_migrations/prod_db/1.sql
persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/DefaultEvolutionsConfigParserSpec.scala
persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsReaderSpec.scala
project/BuildSettings.scala

Fixes #11816
Fixes #3966
Replaces #11819
Replaces #3967
sbt 1.9 [deprecated the `IntegrationTest` configuration](https://eed3si9n.com/sbt-1.9.0#deprecation-of-integrationtest-configuration) and it's recommend to move integration tests in  subprojects instead. This isn't a big deal really, however if you were running evolutions from your integration tests and now move that it-tests into it's own sub-project, the evolution files in the `conf` folder of the main project can not be accessed by the it-sub-project, see #11816.
So this could be a blocker for people trying to get rid of deprecation warnings (and probably upgrading sbt at some point).
Therefore I squeeze that in into Play 2.9 to by allowing to set a location where the evolutions scripts can be found.

Introduce `play.evolutions[.db.default].path`, allows custom evolutions location

---

transport/server/play-akka-http-server/src/main/resources/reference.conf
transport/server/play-akka-http-server/src/main/scala/play/core/server/AkkaHttpServer.scala
transport/server/play-netty-server/src/main/resources/reference.conf

So I did quite some benchmarks today. 
This is what such a benchmark for latest Play 2.8.20 looks like on my machine ([link](https://www.techempower.com/benchmarks/#section=test&shareid=d1258817-06b8-489d-9ca8-e65cd494c394&test=plaintext)):
Now I ran the same benchmark again on latest `main` branch and this is what I got ([link](https://www.techempower.com/benchmarks/#section=test&shareid=1c7f71cf-fffd-4a99-9a29-0fb8db02f2d6&test=plaintext)):
So, I was shocked at first. Like why is there a ~40% performance decrease? Long story short (after trying to figure out what's going on for a while...) it turned out that for the Netty backend the benchmark are quite stable and "only" akka-http was affected.
To make it short: Play 2.8 is still using akka-http 10.1, but main is on 10.2 now. In 10.2 …

Re-enable akka-http HTTP pipelining (like in Play 2.8)

---

documentation/manual/ModuleDirectory.md

* [NA] Have you referenced any issues you're fixing using [commit message keywords](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)?
* [NA] Have you added copyright headers to new files?
* [NA] Have you checked that both Scala and Java APIs are updated?
* [NA] Have you updated the documentation for both Scala and Java sections?
* [NA] Have you added tests for any changed functionality?
Add sbt-svelte to ModuleDirectory.md
It was recommended by mkurz here: https://github.com/orgs/playframework/discussions/11922#discussioncomment-6766739

Add sbt-svelte to ModuleDirectory.md

---

core/play-streams/src/main/scala/play/api/libs/streams/ActorFlow.scala

Fixes #11928
Same story like in https://github.com/apache/incubator-pekko-http/issues/183 / https://github.com/apache/incubator-pekko-http/pull/184

Avoid unapply because we mix Scala 3 and Scala 2.13 artifacts when using akka(-http)

---

core/play/src/main/scala/play/api/mvc/Results.scala
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala

This is a bad bad bug which makes you loose information...
Never made it into a (stable) release yet because Result attributes are a 2.9 feature :sweat_smile:

Bugfix: Make `play.api.mvc.Result.asJava` to include attributes

---

core/play/src/main/resources/reference.conf
core/play/src/main/scala/play/api/http/HttpConfiguration.scala
core/play/src/main/scala/play/api/mvc/Action.scala
core/play/src/main/scala/play/core/routing/HandlerInvoker.scala
core/play/src/test/scala/play/api/http/HttpConfigurationSpec.scala
project/BuildSettings.scala

Woke up early today to implement #11921 before continuing migration guide.
PR works, I am 99,99% sure, however tests and docs come later because I want to cut M7 which, if no problems occur in the play-samples tests, will become RC1.

Introduce `play.http.actionComposition.includeWebSocketActions`

---

.github/workflows/build-test.yml

I do think that was necessary for older ssl-config version, but not now anymore (?). `--add-exports` should be sufficient. We will see if tests pass.

`--add-opens` not needed anymore

---

.github/workflows/build-test.yml
documentation/manual/hacking/Translations.md
documentation/manual/releases/release29/Highlights29.md
documentation/manual/releases/release29/migration29/Migration29.md
documentation/project/build.properties
documentation/project/plugins.sbt
project/Dependencies.scala
project/build.properties
project/plugins.sbt

sbt 1.9.5 introduced a compiler bug.
https://github.com/sbt/sbt/releases/tag/v1.9.5
> Update: ⚠️ sbt 1.9.5 is broken, because it causes Scala compiler to generate wrong class names for anonymous class on lambda. While we investigate please refrain from publishing libraries with it.
scala/bug#12868 (comment)

sbt 1.9.6 + rebuild libs

---

documentation/manual/working/commonGuide/configuration/SettingsAkkaHttp.md

According to the Akka docs, the request-timeout should be smaller than the idle-timeout.
Cf. https://doc.akka.io/docs/akka-http/current/configuration.html
It would probably also be a good idea to either show a warning when, when the request-timeout is larger than the idle-timeout, or even set the actual idle-timeout always as the larger of the two.

Docs: Use example with idle timout larger than request timeout

---

.github/workflows/build-test.yml

Sometimes is very useful to skip some jobs when we sure them are unneeded

Skip CI jobs by label

---

.github/workflows/build-test.yml
.github/workflows/delete-caches.yml

Every 4th hour this workflow will delete unneeded (latest accessed time 2 hour old) cache entries (prefix `play-published-local-*`).

[CI] Improve cache working

---

core/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketClient.scala
project/Dependencies.scala
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/PlayRequestHandler.scala

Not done yet, but I need a published Play 3 milestone with netty-reactive-streams moved to org.playframework to fix https://github.com/playframework/play-ws/pull/806 because it's shading the "wrong" package currently.

Some libs moved to `org.playframework`

---

core/play/src/test/java/play/mvc/CallTest.java
documentation/README.md
documentation/manual/gettingStarted/IDE.md
documentation/style/main.css
web/play-filters-helpers/src/test/scala/play/filters/hosts/AllowedHostsFilterSpec.scala

These (cherry-picked) commits have nothing to do with Pekko or with the `org.playframework` switch, so I backport them 2.9.x so we keep that branches "synced". With that, the main branch only contains pekko and `org.playframework` commits now.

[2.9.x] Backports that are not specific to Play 3

---

documentation/manual/gettingStarted/IDE.md

This replaces the gendered term "his" in the sentence of IDE.md, `each developer must keep his Eclipse configuration files private`, with the neutral "their". 
This change has been made to ensure that Play's documentation is gender neutral as per the guidelines: [https://www.playframework.com/documentation/2.8.x/Documentation#Gender-neutral-language-and-names](https://www.playframework.com/documentation/2.8.x/Documentation#Gender-neutral-language-and-names)
[Play Documentation Guidelines](https://www.playframework.com/documentation/2.8.x/Documentation#Gender-neutral-language-and-names)

Pronoun change in IDE.md for gender neutrality

---

project/plugins.sbt

Doesn't hurt but gives us more commands to inspect dependencies:
* https://www.scala-sbt.org/1.x/docs/sbt-1.4-Release-Notes.html#sbt-dependency-graph+is+in-sourced
* https://github.com/sbt/sbt-dependency-graph#main-tasks

Add `addDependencyTreePlugin`

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

To be released with 2.8.21 after 2.9 and 3.0 are out.

Display soft warning about EOL when starting sbt

---

documentation/manual/hacking/Repositories.md
documentation/manual/working/commonGuide/build/code/dependencies.sbt

fix warnings
- https://github.com/sbt/librarymanagement/commit/e15f0c149ae940575d2314cf044b4347fc67b12a
- https://github.com/sbt/librarymanagement/blob/54011d5e74335bab229bc3f6532b6a1ca6d0d5cd/core/src/main/scala/sbt/librarymanagement/ResolverExtra.scala#L159-L163

replace deprecated `Resolver.sonatypeRepo`

---

documentation/manual/working/scalaGuide/main/http/ScalaBodyParsers.md
documentation/manual/working/scalaGuide/main/ws/ScalaWS.md

fix url
play-json 2.x does not exists with new groupId( `org.playframework` ).
playframework 3.x depends on play-json 3.x.

Update play-json scaladoc url

---

documentation/manual/working/commonGuide/build/sbtDebugging.md
documentation/manual/working/commonGuide/production/Deploying.md

```
[my-first-app] $ compile:packageBin::mappings
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Compile / packageBin / mappings
```
```
[my-first-app] $ universal:packageZipTarball
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Universal / packageZipTarball
```
```
[my-first-app] $ universal:packageBin
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Universal / packageBin
```
```
[my-first-app] $ debian:packageBin
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Debian / packageBin
```
```
[my-first-app] $ rpm:packageBin
[warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Rpm / packageBin
```
- https://github.com/sbt/sbt/blob/3e205d04b830136775dec6fc7daf41b5491b0230/main/src/main/sca …

use new sbt slash syntax in doc

---

documentation/manual/working/javaGuide/main/config/JavaConfig.md

This was part of 3f0e09fd78b in main branch already.

[2.9.x] Fix link to typesafe config

---

documentation/manual/gettingStarted/IDE.md

ensime no longer available
- https://github.com/ensime
- https://ensime.github.io/

remove ensime from IDE.md

---

documentation/manual/working/commonGuide/filters/CspFilter.md

- https://github.com/scala/scala/commit/f46fc7e49058352ff2ac5e843c343e24d0ee6e3c

avoid deprecated `scala.Symbol` literal in `CspFilter.md`

---

project/Dependencies.scala

No other updates for the 2.8.x branch as far as I can see.

[2.8.x] Upgrade typesafe config to 1.4.3

---

build.sbt

Need to ignore `target` folder the same as for another modules

Fix headers check for Play OpenID module

---

.github/workflows/publish.yml

Publish job for protected branches (`main`, `2.9.x`) finishes before check job that why we make a cache entry with not all artifacts that we want.
**Actual** cache size: **780Mb**
**Expected** cache size: **1.2Gb**
For example https://github.com/playframework/playframework/actions/runs/6823204457/job/18556669881

Add suffix to coursier cache key for publish job

---

documentation/manual/releases/release29/migration29/Migration29.md

Fixes 
- #12206 see its comment: https://github.com/playframework/playframework/issues/12206#issuecomment-1812337527

Migration guide: Dispatchers defined directly in the `akka.*` config won’t load automatically anymore

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/ApplicationEvolutions.scala

It seems in
* https://github.com/playframework/play-samples/pull/451
the author had a problem figuring out this actually is a button you can click so I want to make sure this is bullet proof for newcomers and add "_Click here..._" to the button's label:
**Old:**
**New:**

Make clear the evolutions page shows a button

---

core/play/src/main/java/play/mvc/Result.java
core/play/src/test/java/play/mvc/ResultsTest.java
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala

Fixes #12333 
Currently, when modifying a `Result` in Java, the result's `attrs` are lost due to them not being copied. This PR fixes this by also copying the `attrs` to the new `Result` when modifying flash, session, content type, or headers.
The issue only existed in the Java API. Tests have been added to check for the bug in both Java and Scala.

Keep attrs when modifying result

---

project/plugins.sbt

Finally, all our dependencies for Play 2.9 and Play 3.0 are now hosted on Maven Central. Bye bye custom repos like https://repo.scala-sbt.org/ (cough cough https://github.com/sbt/sbt/issues/7202)
* https://github.com/johanandren/sbt-akka-version-check/pull/2
* https://github.com/johanandren/sbt-akka-version-check/releases/tag/v0.2
* https://github.com/johanandren/sbt-akka-version-check/commit/623017edb047435b3a587e2db8b5a9c2682d69d9
* https://repo1.maven.org/maven2/com/markatta/sbt-akka-version-check_2.12_1.0/0.2/sbt-akka-version-check-0.2.pom

[2.9.x] `sbt-akka-version-check` now hosted on maven central

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/dev-mode/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/disabled-assets-jar/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject-assets/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/multiproject/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation-with-request-passed/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-injected-routes-compilation/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-namespace-reverse-router/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-no-package-declaration-in-routes-file/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/project/plugins.sbt
documentation/manual/working/commonGuide/assets/AssetsCoffeeScript.md
documentation/manual/working/commonGuide/assets/AssetsJSHint.md
documentation/manual/working/commonGuide/assets/AssetsLess.md
documentation/manual/working/commonGuide/assets/RequireJS-support.md

- https://github.com/sbt/sbt-less/releases/tag/2.0.0
- https://github.com/sbt/sbt-digest/releases/tag/2.0.0
- https://github.com/sbt/sbt-gzip/releases/tag/2.0.0
- https://github.com/sbt/sbt-coffeescript/releases/tag/2.0.0
- https://github.com/sbt/sbt-jshint/releases/tag/2.0.0
TODO:
They all uses latest sbt-web 1.5 / sbt-js-engine 1.3.x now, but most importantly are now hosted on maven central intead of deprecated https://repo.scala-sbt.org/ (see https://github.com/sbt/sbt/issues/7202).
Only relevant for documentation and scripted tests (meaning if repo.scala-sbt.org goes down we can still successfully run our tests :wink:)

Upgrade sbt-web plugins (to avoid repo.scala-sbt.org)

---

persistence/play-jdbc-evolutions/src/main/scala/play/api/db/evolutions/EvolutionsApi.scala
persistence/play-jdbc-evolutions/src/test/scala/play/api/db/evolutions/EvolutionsSpec.scala

Fixes #8184
Check evolution state before acquiring the connection to actually perform the evolution operation. Previously, the connection to perform the actual operation was acquired before checking, requiring 2 simultaneous connections. This approach requires only a single connection.
Alternatively, `checkEvolutionsState` could be modified to take a current connection, but this would require more code changes to make sure autocommit is handled, and not all callsites have an open connection to use. Practically, Hikari will just reuse the same connection for both, so calling getConnection twice should not be expensive.
I modified the test suite to default to a single connection to make sure this was tested. Unfortunately, this required tweaking many checks, as the test suite itself  opened …

Fix #8184 Evolutions Fail With a Small Pool

---

.github/workflows/build-test.yml
.github/workflows/publish.yml

With v3.5.0 we can't access `repo.scala-sbt.org` and `repo.typesafe.com` anymore, see https://github.com/playframework/.github/commit/372f672ba6267f1f3d6054628456d2eb2f122135 (which IMHO is a good thing to make things future proof).
However Play 2.8 still needs dependencies from those repos, so I just nail the version used to 3.4.
Given Play 2.8 will be EOL this year I think this is ok to do now.

[2.8.x] Allow access to deprecated repos

---

documentation/manual/working/scalaGuide/main/forms/code/ScalaForms.scala

I assume these were inserted using some kind of search and replace mechanism and and the extra set of parenthesis was missed.

Fix unapply examples in ScalaForms docs

---

project/Dependencies.scala

This avoids that we have to cut a new `netty-reactive-streams[-http]` release each time we upgrade netty... which is a bit annoying... Also this approach here is a bit safer IMHO, in case we forget to cut a new `netty-reactive-streams[-http]` release but upgrade netty in the dependencies only and ship mixed dependencies.
* `netty-reactive-streams-http` depends on `netty-reactive-streams`: https://github.com/playframework/netty-reactive-streams/blob/netty-reactive-streams-parent-3.0.2/netty-reactive-streams-http/pom.xml#L17-L21
* `netty-reactive-streams-http` pulls in `netty-codec-http`: https://github.com/playframework/netty-reactive-streams/blob/netty-reactive-streams-parent-3.0.2/netty-reactive-streams-http/pom.xml#L22-L25
* `netty-reactive-streams` pulls in `netty-handler`: …

Explicitly depend on `netty-reactive-streams-http` transitive dependencies

---

project/Dependencies.scala

I run [Linux on a MacBook M1 Pro](https://asahilinux.org/):
```sh
$ uname -m
aarch64
```
Also it seems more cloud services offer Linux arm64 (=aarch64) virtual machines nowadays. The problem is currently when running Play with the netty backend on such CPUs with `play.server.netty.transport = "native"` configured, you end up with this error:
```
2024-02-26 13:41:19 DEBUG i.n.u.internal.NativeLibraryLoader  -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
2024-02-26 13:41:19 DEBUG i.n.u.internal.NativeLibraryLoader  -Dio.netty.native.deleteLibAfterLoading: true
2024-02-26 13:41:19 DEBUG i.n.u.internal.NativeLibraryLoader  -Dio.netty.native.tryPatchShadedId: true
2024-02-26 13:41:19 DEBUG i.n.u.internal.NativeLibraryLoader  -Dio.netty.native.detectNativeLibraryDuplicates: true
Oops, cannot …
```

Make Netty native transport work on Linux `AArch64` and `RISC-V` (besides `x86-64`)

---

core/play/src/main/scala/play/api/controllers/Assets.scala
core/play/src/main/scala/play/api/i18n/I18nModule.scala
core/play/src/main/scala/play/api/inject/Module.scala
dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/RoutesModels.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
documentation/build.sbt
documentation/manual/hacking/BuildingFromSource.md
documentation/manual/releases/Scala3Migration.md
documentation/manual/releases/release26/Highlights26.md
documentation/manual/releases/release27/Highlights27.md
documentation/manual/releases/release28/migration28/Migration28.md
documentation/manual/releases/release29/migration29/Migration29.md
documentation/manual/working/commonGuide/build/sbtDependencies.md
documentation/manual/working/scalaGuide/main/async/code/ScalaWebSockets.scala
project/Versions.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/csrf.scala

- https://contributors.scala-lang.org/t/3-3-2-release-thread/6433/
- https://contributors.scala-lang.org/t/scala-2-13-13-release-planning/6315/
- https://contributors.scala-lang.org/t/scala-2-12-19-release-planning/6216/

Upgrade to latest scala versions

---

testkit/play-test/src/main/scala/play/api/test/TestServer.scala

- Fixes #12331
This is an alternative, less intervening PR to
- #12352

`TestServer.isRunning` should not throw exception but return `false`

---

documentation/manual/gettingStarted/LearningExamples.md

The "learning examples" page at
https://www.playframework.com/documentation/2.8.x/LearningExamples points to the Lightbend Tech Hub -- as this is a repackaging of play-samples and is Lightbend specific, it's probably a good idea to move to directly using the samples.
TODO:
* Link to the tutorials: https://www.playframework.com/documentation/2.8.x/Tutorials
* Find and scrub all references to tech hub in documentation
* Make additional PRs for 2.9.x / 3.0.x to match
This changes documentation only, not source code.

[2.8.x] Move away from using lightbend tech hub (WIP)

---

documentation/manual/gettingStarted/LearningExamples.md

[2.9.x] Fix typo in docs

---

documentation/manual/gettingStarted/LearningExamples.md

`the` twice
- backport: #12412

Fix typo in docs

---

.github/scala-steward.conf

In 2.8 we only allow patch upgrades anymore.
If something important we can do it by hand.

[2.8.x] scala-steward: pin dependencies

---

.github/scala-steward.conf
project/Dependencies.scala

Replaces
- #12130
Can't merge
- #12218
yet because it requires JDK 21 already... pinning in scala steward conf

derby, derbytools 10.16.1.1 (was 10.15.2.0)

---

build.sbt
cache/play-caffeine-cache/src/test/java/play/cache/caffeine/NamedCaffeineCacheSpec.java
core/play-guice/src/test/java/play/inject/guice/GuiceApplicationBuilderTest.java
core/play-guice/src/test/java/play/inject/guice/GuiceApplicationLoaderTest.java
core/play-guice/src/test/java/play/inject/guice/GuiceInjectorBuilderTest.java
core/play-integration-test/src/test/java/play/BuiltInComponentsFromContextTest.java
core/play-integration-test/src/test/java/play/routing/AbstractRoutingDslTest.java
core/play-java/src/test/java/play/mvc/HttpTest.java
core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
core/play/src/test/java/play/i18n/MessagesTest.java
core/play/src/test/java/play/libs/concurrent/FuturesTest.java
persistence/play-java-jdbc/src/test/java/play/db/DatabaseTest.java
persistence/play-java-jdbc/src/test/java/play/db/NamedDatabaseTest.java
persistence/play-java-jpa/src/test/java/play/db/jpa/JPAApiTest.java
project/Dependencies.scala
testkit/play-test/src/test/java/play/test/HelpersTest.java
testkit/play-test/src/test/java/play/test/WithApplicationOverrideTest.java
testkit/play-test/src/test/java/play/test/WithBrowserTest.java
web/play-java-forms/src/test/java/play/mvc/HttpFormsTest.java

It's a first small step for
- #11839
I'm still thinking we should migrate to AssertJ firstly instead of rewrite assertion expressions twice (Hamcrest -> JUnit5 -> AssertJ).
In this part I remove using Hamcrest in sources. The second part will be related to documentation.

Migrate from Hamcrest/FEST-Assert to AssertJ (test sources)

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/ApplicationSecretGenerator.scala

Changed to append the generated play.http.secret.key to the end of file(previously added at the start of the file) so that we do not add the key before comment lines if any.
Fixes #12200

Add generated play.http.secret.key at the end of the application.conf file

---

core/play/src/main/scala/play/api/mvc/Cookie.scala

- Fixes https://github.com/playframework/playframework/pull/12033#issuecomment-1809961474
Users can put in their `build.sbt`, just [like we do](https://github.com/playframework/playframework/blob/3.0.2/project/Dependencies.scala#L75-L81):
```sbt
val jjwtVersion = "0.12.5"
val jjwts = Seq(
"io.jsonwebtoken" % "jjwt-api",
"io.jsonwebtoken" % "jjwt-impl"
).map(_ % jjwtVersion) ++ Seq(
("io.jsonwebtoken" % "jjwt-jackson" % jjwtVersion).excludeAll(ExclusionRule("com.fasterxml.jackson.core"))
)
libraryDependencies ++= jjwts
```
/cc @hertg This one is for you, so you can upgrade jjwt in your Play 3.0.x project.

[3.0.x] Allow users to upgrade to jjwt 0.12.5

---

core/play/src/main/scala/play/api/mvc/Cookie.scala
project/Dependencies.scala

This PR makes #12033 obsolete
This PR upgrades the [jjwt](https://github.com/jwtk/jjwt) dependency from `0.11.5` to `0.12.3`.
The `0.12.0` of `jjwt` adds a lot of new features that were highly anticipated by a lot of `jjwt` users. For example, the support to marshal and parse JWKs and the support for encrypted JWTs (JWE).
The version bump includes breaking changes for a few `jjwt` exposed methods (see [CHANGELOG](https://github.com/jwtk/jjwt/blob/0.12.0/CHANGELOG.md)), while other methods were just deprecated.
Where possible, the deprecated method calls have been replaced with their latest counterpart. A few deprecated classes and methods are still being used in this PR. In particular, anything relating to `io.jsonwebtoken.SignatureAlgorithm`, which has been deprecated as a whole. …

upgrade jjwt to 0.12.5

---

project/BuildSettings.scala
web/play-filters-helpers/src/main/java/play/filters/components/CSRFComponents.java
web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala

- Fixes #8971
Makes sure `play.filters.csrf.errorHandler` will be used by default. More details in the referenced issue.

Inject (CSRF)errorHandler in CSRFCheck

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/distribution/build.sbt
project/plugins.sbt

I was helping out yesterday and today in the sbt-native-packager repo to get a new release out (the first since 14 month)....
- Fixes #8282

sbt-native-packager 1.10.0

---

dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayRunPlugin.java
dev-mode/gradle-plugin/src/test/java/play/gradle/PlayRunPluginTest.java

Copy of #12531 
Original author is @vincent-raman 
* [/] Have you checked that both Scala and Java APIs are updated?
* [/] Have you updated the documentation for both Scala and Java sections?
Fixes playframework/playframework#12530
Avoid relying on the fixed existence of `compileJava`, `compileScala` or even `processResources` in any of the gradle projects when computing the classpath for `playRun`
The computation of the classpath for the `playRun` takes the output folders of the current Play project and any of the subprojects it depends on. It supposes that `compileJava`, `compileScala` and `processResources` tasks exist for any of these projects without any check. If one of them doesn't exist, it fails creating `playRun`.
I chose the approach of mapping directories only if the task …

[Gradle] Fix `playRun` classpath when project depends on a pure java project

---

project/Dependencies.scala

scala-steward is unable to bump this version automatically because of the `match`/`case`:
```
2024-05-02 15:01:01,371 INFO  Process update org.scala-lang.modules:(scala-parser-combinators, scala-parser-combinators_3) : 2.3.0 -> 2.4.0
2024-05-02 15:01:01,658 WARN  Unable to bump version for update org.scala-lang.modules:(scala-parser-combinators, scala-parser-combinators_3) : 2.3.0 -> 2.4.0
2024-05-02 15:01:01,658 WARN  No commits created
```

scala-parser-combinators 2.4.0

---

documentation/manual/working/javaGuide/main/forms/JavaForms.md

The links are outdated for Play 3.0 and 2.9.

[3.0.x] Links now point to correct hibernate validator release

---

core/play/src/main/scala/play/api/mvc/Cookie.scala

- Continuing #12474
The previous pull request did not handle the creation of new cookies :cry: This PR should fix this now.

[3.0.x] Fix jjwt compatibility to allow upgrades

---

.github/workflows/build-test.yml
documentation/project/build.properties
project/PlaySbtBuildBase.scala
project/Versions.scala
project/build.properties

I didn't upgrade sbt in the 3.0.x branch before the 3.0.3 release just to keep things safe, in case 1.10.0 would break stuff like it happend [with sbt 1.9.5 once](https://github.com/scala-steward-org/scala-steward/pull/3169).
For next 3.0.x release it should be ok to now upgrade to sbt 1.10.0, given 3.0.4 is a couple of weeks away and if sbt 1.10.0 has major issues I guess they would surface until then.

[3.0.x] sbt 1.10.0

---

build.sbt
project/BuildSettings.scala
project/plugins.sbt

Fixes #11986
Introduce sbt-pekko-version-check plugin, to make sure versions across Pekko modules are the same in the project.
We had the akka-equivalent of this plugin before.

Introduce sbt-pekko-version-check plugin

---

core/play/src/main/scala/play/api/libs/crypto/CSRFTokenSigner.scala
project/BuildSettings.scala

- Replaces #12519 which I can not force push to, to enable mima checks.

Remove deprecated methods on CSRFTokenSigner

---

core/play/src/main/scala/play/api/routing/Router.scala

Simplify  `PartialFunction` compose
No need to `lift` to `Function`, there are `PartialFunction.andThen(xxx: PartialFunction)`
https://github.com/scala/scala/blob/0d8f4caa713977983c53828f87d50fbadc7dd7ab/src/library/scala/PartialFunction.scala#L164

simplify PartialFunction compose

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/conf/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/project/plugins.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/subproj/app/assets/stylesheets/main.less
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/subproj/app/assets/stylesheets/main.less.new
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/subproj/conf/subproj.routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/test
project/Dependencies.scala

Fixes 
- #12484
- #12636
To confirm the problem, I first push a scripted test that will fail without the fix from
- https://github.com/webjars/webjars-locator-core/pull/159

Update changed assets in subprojects

---

core/play/src/main/resources/play/reference-overrides.conf

~Fixes #xxxx~
Fix Pekko configuration value to match the official documentation.
`jvm-exit-on-fatal-error` was changed to `true` in #6522. However, according to the official documentation, it seems to be set to either `on` or `off`. So I changed it to `on` to match the documentation.
**Pekko**
https://pekko.apache.org/docs/pekko/current/general/configuration-reference.html
```conf
jvm-exit-on-fatal-error = on
```
**Akka**
https://doc.akka.io/docs/akka/current/general/configuration-reference.html
```conf
jvm-exit-on-fatal-error = on
```
- #6522

Fix Pekko configuration value to match the official documentation

---

core/play/src/main/resources/play/reference-overrides.conf

~Fixes #xxxx~
Fix comments for Pekko configurations.
As a result of replacing `Akka` with `Pekko` in #11847, some comments became incorrect, such as "Pekko 2.5". So I fixed them by referring to the official documentation.
- https://pekko.apache.org/docs/pekko/current/general/configuration-reference.html
```conf
jvm-shutdown-hooks = on
```
```conf
coordinated-shutdown {
```
- #11847
- https://github.com/playframework/playframework/commit/5e9cf5c2beb089a2fab80cb0b83f440391bcd7d0#diff-d776d373f69270606271642831c30e051e2d4cf32de3376c9261700dfb9f277b

Fix comments for Pekko configurations

---

documentation/manual/gettingStarted/IDE.md
documentation/manual/gettingStarted/PlayConsole.md

- See #9983 
`~run` does not work anymore. IMHO we should not advertise it in the documentation until fixed. Makes Play look bad.

Temporary remove `~run` from docs because it's broken since long time

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/build.sbt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT-assets.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT-sans-externalized.scala2.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT-sans-externalized.scala3.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT.scala2.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-main.asset-changes-main-1.0-SNAPSHOT.scala3.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-sub.asset-changes-sub-1.0-SNAPSHOT.scala2.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-asset-changes-sub.asset-changes-sub-1.0-SNAPSHOT.scala3.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-jar-manifest-sub.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-jar-manifest.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-jars-in-lib-folder-sans-externalized.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/expected-jars-in-lib-folder.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/asset-changes-in-subprojects/test
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/expected-assets-pipeline.assets-pipeline-0.1.0-SNAPSHOT-assets.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/expected-assets-pipeline.assets-pipeline-0.1.0-SNAPSHOT-sans-externalized.scala2.jar.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/assets-pipeline/expected-assets-pipeline.assets-pipeline-0.1.0-SNAPSHOT-sans-externalized.scala3.jar.txt

- Fixes #7010
Make sure that each generated jar file, no matter if `PlayKeys.externalizeResources` is set to `true` or `false`, contains a meaninful manifest file (including the assets jar).
Also removed the `Main-Class` attribute from the manifest files, because these jar files themselves can not be run via `java -jar`, and even worse, the value of that attribute `play.core.server.ProdServerStart` is a class that does not even exists in one of the generated jar files (it is inside the `org.playframework.play-server_....jar` file).
I split the PR into meaningful commits so you can follow, also I tested the scripted test I added for each commit locally, but I will just now push all commits at once, instead of pushing each commit one-by-one to run the scripted test on CI again and again. I …

Generate a reasonable `META-INF/MANIFEST.MF` file for each generated jar

---

dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayPlugin.java

Fix the first case in https://github.com/playframework/playframework/issues/12720
I agree with @Nezisi, that `java-forms` should be optional dependency. If someone need them, they can configure that explicitly and very easy (`build.gradle.kts`):
```kotlin
import play.TemplateImports
dependencies {
implementation("org.playframework:play-java-forms_$scalaVersion")
}
sourceSets {
main {
twirl {
templateImports.set(TemplateImports.defaultJavaTemplateImports)
}
}
}
```

[Gradle] Template imports for Java project should be minimal

---

core/play-integration-test/src/test/scala/play/it/action/FormActionSpec.scala
core/play/src/main/scala/play/api/mvc/Action.scala
core/play/src/main/scala/play/core/j/JavaAction.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/main/java/controller/HomeController.java
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/main/resources/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/java-test-helpers/src/test/java/controllers/HomeControllerTest.java

Fixes #12770
If the Path of a temporary file is retrieved and processed, the TemporaryFile may be deleted before the response is finished (#12770). This pull request will prevent TemporaryFile from being deleted until the response is finished.
cc/ @mkurz

Prevent TemporaryFile to be deleted before returning a response

---

documentation/manual/working/commonGuide/filters/RedirectHttpsFilter.md
documentation/manual/working/commonGuide/filters/code/CommonRouting.scala
documentation/manual/working/commonGuide/filters/code/commonguide.http.routing.routes
project/BuildSettings.scala
web/play-filters-helpers/src/main/resources/reference.conf
web/play-filters-helpers/src/main/scala/play/filters/https/RedirectHttpsFilter.scala
web/play-filters-helpers/src/test/scala/play/filters/https/RedirectHttpsFilterSpec.scala

As discussed on #12776 , the way to exclude paths for https redirection was very limited. The goal of this PR is to make it much more flexible, taking inspiration from existing whitelist/blacklist route modifiers in the framework (CSRFFilter for example)

Add route modifiers on RedirectHttpsFilter. Resolves #12776

---

core/play/src/main/scala/play/core/parsers/Multipart.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala

This PR applies the recommendations from the Pekko migration guide from 1.0.x to 1.1.x. The Pekko sub stream cancellation strategy was defaulted to `SubstreamCancelStrategy.drain` in the 1.0.x branches. It now defaults to `Supervision.stop` which is an equivalent of `SubstreamCancelStrategy.propagate`. It causes the MultipartFormData parser to fail after the first `form-data` item encountered when using Pekko 1.1.x dependencies in user land.
The change doesn't affect Play 3.0.4 users using the Pekko 1.0.x dependencies included with the framework it self. But it gets the framework ready for when the Pekko 1.1.x release is ready. It has the added benefit of making the usage of the "cancel on purpose as an early sub-stream exit" pattern more obvious. 
[Migration from Apache Pekko 1.0.x to …

Apply recommendations from Pekko 1.1.x Migration guide

---

core/play/src/main/scala/play/core/parsers/Multipart.scala
web/play-filters-helpers/src/main/scala/play/filters/csrf/CSRFActions.scala

relates to #12662 and #12793 
#12793 did not fix the broken tests in #12662 
reordering the code fixes most of the broken tests (in my local testing and most recent 12793 build)

reorder splitWhen code due to pekko 1.1 test failures

---

cache/play-cache/src/main/scala/play/api/cache/SerializableResult.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala

With ByteString.toArray, you need to clone the underlying byte data in the ByteString. ByteString.toArrayUnsafe() avoids the array copy - saving time and memory. The risk is that the code that calls toArrayUnsafe() then modifies the data in the array. If you know that your code just reads the byte array and doesn't change it then it is safe to use ByteString.toArrayUnsafe().

Performance: use ByteString toArrayUnsafe

---

core/play/src/main/scala/play/api/mvc/Cookie.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/jjwt-compatibility/conf/application.conf

Fixes #12817
Fix for `JwtBuilder.setExpiration` method which become `expiration` in 0.12+
#12817, #12624, #12626

[3.0.x] Fix jjwt 0.12 compatibility for `setExpiration` method

---

cache/play-cache/src/main/scala/play/api/cache/SerializableResult.scala
core/play/src/main/scala/play/api/mvc/BodyParsers.scala

`ByteString(Array[Byte])` assumes that later code could change the array data - `fromArrayUnsafe` is faster because it trusts that array is not going to be changed.
- Relates to #12795
Fixes #xxxx

use ByteString.fromArrayUnsafe for perf reasons

---

documentation/manual/tutorial/Tutorials.md

As a Play user
I want the links in the Play documentation to take me to the correct webpage
So that I am not frustrated by a 404 error

Fix broken link

---

core/play-java/src/main/java/play/routing/RoutingDsl.java

The `static private` modifier for these 2 classes was incorrect. In the previous versions of Scala it compiled due to existence of a bug in the compiler. 
The mentioned bug was minimized and discussed in https://github.com/scala/scala3/issues/21599 and was discovered after merging a fix https://github.com/scala/scala3/pull/21362 
Problem was discovered by Scala 3 Open Community Build in: 
- `playframework/playframework` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/12091465203/job/33720349509#step:3:6049) 
- `playframework/omnidoc` - [build logs](https://github.com/VirtusLab/community-build3/actions/runs/12091465203/job/33720345526#step:3:1835)

Change access modifier to package private for  `RoutingDsl.{Route,RouteParam}`

---

core/play-integration-test/src/test/scala/play/it/http/JavaResultsHandlingSpec.scala
core/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala
project/BuildSettings.scala
testkit/play-test/src/main/java/play/test/Helpers.java
testkit/play-test/src/main/scala/play/api/test/Helpers.scala

By default test server ports are random since last Play release, also we removed the globa app now, so we can also run the tests in parallel now.
IMHO we can just keep the methods, in case people want to keep running tests sequentially (for whatever reason).
- Replaces #13095
- Fixes #12214

`shouldRunSequentially` defaults to `false` now

---

core/play-integration-test/src/test/scala/play/it/action/FormActionSpec.scala
core/play/src/test/scala/play/api/libs/TemporaryFileCreatorSpec.scala
core/play/src/test/scala/play/api/mvc/ResultsSpec.scala

This PR just refactors three tests which relied on `tempFileCreator` and `messagesApi` to be available via `SimpleInjector` from this code:
https://github.com/playframework/playframework/blob/3a8154e29130ae3f8c02574f6e835ef8f601d095/core/play/src/main/scala/play/api/Application.scala#L247-L255
The code above is just a workaround to make some components available via `app.injector` for compile time DI while the whole DI support in Play was in development. _In theory_ the above code could now be removed.
This PR makes
- #13093 
work now.

Avoid `app.injector` in tests using compile time DI

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/evolutions-auto-apply-false/test

Seems GitHub actions runner are slower so this does not occure there.

Add timeout to scripted tests to fix failing it locally

---

dev-mode/play-routes-compiler/src/main/scala/play/routes/compiler/templates/package.scala
dev-mode/play-routes-compiler/src/main/twirl/play/routes/compiler/inject/forwardsRouter.scala.twirl
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/app/controllers/Application.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes

I caught this just passing by during other work 🧑‍💻
Still following _"The Boy Scout Rule (©Uncle Bob)"_ 🖖
PS: As a workaround in current version is possible to use next hack:
```
GET         /routes                 controllers.Application.javaRoute(request: Request, `req`)
```

Fix generated router with param `req`

---

core/play/src/main/scala/play/api/mvc/Binders.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala

I caught this just passing by during other work 🧑‍💻
Still following _"The Boy Scout Rule (©Uncle Bob)"_ 🖖

Fix encoding a value of `Char` query param for reverse router

---

core/play/src/main/scala/play/api/mvc/Binders.scala
core/play/src/test/scala/play/api/mvc/BindersSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/conf/routes
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/RouterSpec.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/routes-compiler-routes-compilation/tests/assets/JavaScriptRouterSpec.js

I caught this just passing by during other work 🧑‍💻
Still following _"The Boy Scout Rule (©Uncle Bob)"_ 🖖

Fix encoding a key of `Boolean` query param for JavaScript reverse router

---

transport/server/play-server/src/main/scala/play/core/server/common/WebSocketFlowHandler.scala

https://datatracker.ietf.org/doc/html/rfc6455#section-7.4.1
> 1005 is a reserved value and MUST NOT be set as a status code in a Close control frame by an endpoint.  It is designated for use in applications expecting a status code to indicate that no status code was actually present.
Currently, when the close frame gets send by the client without status code, we set the status code to regular/1000 (the one the app receives):
https://github.com/playframework/playframework/blob/0dcea10a40661926e3b0fb3c107d3ae25b8d9c6b/core/play/src/main/scala/play/api/http/websocket/Message.scala#L38
This is wrong according to the specs the app needs to receive 1005.

If WebSocket close frame does not send status code it defaults to 1005

---

core/play/src/main/java/play/mvc/WebSocket.java

The WebSocket specs [defines various frame types](https://datatracker.ietf.org/doc/html/rfc6455#section-5.5).
In Play we handle them as `Message` ([scala](https://github.com/playframework/playframework/blob/3.0.x/core/play/src/main/scala/play/api/http/websocket/Message.scala), [java](https://github.com/playframework/playframework/blob/3.0.x/core/play/src/main/java/play/http/websocket/Message.java)).
Using Play Scala, it's easy to directly work with `Message` objects, so one can easily receive and send and mix Messages. (Like receive a text message, answer with a binary, etc.). For example:
```scala
def websocket: WebSocket = WebSocket.accept[Message, Message](rh =>
Flow.fromSinkAndSource(
Sink.foreach(_ match {
case TextMessage(data)           => ...
case BinaryMessage(data)         => …
```

Make it easier to work with Play's WebSocket `Message` objects in Java

---

core/play-integration-test/src/test/scala/play/it/http/websocket/WebSocketSpec.scala

one less warning.
`play.api.Configuration.++` was marked as deprecated on 24/09/2019 and since v2.8.0. 
Should it be removed for the 2.9.x series ?

remove usage of deprecated play.api.Configuration ++

---

cache/play-caffeine-cache/src/main/java/play/cache/caffeine/CaffeineDefaultExpiry.java
cache/play-caffeine-cache/src/main/java/play/cache/caffeine/NamedCaffeineCache.java

Next guice version will drop the findbugs jsr305 dependency.
- https://github.com/google/guava/commit/04bf0300b8736ec7297a34da40a6efb21231c5da
- https://github.com/google/guava/issues/2960
I can confirm with latest guice snapshot those annotation are gone and compilation fails.

Remove `javax.annotation`

---

documentation/manual/working/javaGuide/main/dependencyinjection/JavaDependencyInjection.md
documentation/manual/working/scalaGuide/main/dependencyinjection/ScalaDependencyInjection.md

Resolves https://github.com/playframework/playframework/issues/10469
Adds documentation around differences in eager bindings between development and production modes.
Requested in https://github.com/playframework/playframework/issues/10469. 
I verified the behavior by creating a Hello World Play application and creating a custom binding and logging inside the service like this: 
```
if (environment.mode == Mode.Dev) {
logger.info("EagerService created in Development mode")
println("EagerService created in Development mode")
} else {
logger.info("EagerService created in Production mode")
println("EagerService created in Production mode")
}
```
Then I added a module: 
```
class EagerModule extends AbstractModule {
override def configure(): Unit = { …
```

Eager bindings docs clarification

---

.github/workflows/dependency-graph.yml

I think it's confusing that all the alerts look like they come from the documentation project, which is not true. The documentation projects depends on the root project. By checking the root project explicitly, we should also see the alerts for `build.sbt`.
I just want to make sure that no one mistakenly thinks "oh ok it's just the docs, we are fine".

Explicitly submit the root project's dependency

---

project/Dependencies.scala

- Currently we are unable to upgrade FluentLenium and htmlunit: https://github.com/playframework/playframework/issues/13105#issuecomment-2655910010
However at least make sure we ship latest commons-io because the above two outdated libs depend on commons-io 2.11 and 2.10 which come with https://github.com/advisories/GHSA-78wr-2p64-hpwj
At least this makes Dependabot alerts happier.

Avoid outdated commons-io in htmlunit and fluentlenium

---

documentation/manual/working/commonGuide/production/cloud/ProductionHeroku.md

This replaces heroku legacy toolbelt URL replaced by Heroku CLI docs URL on play 3.0 documentation.

Fix Heroku deprecated toolbelt URL on ProductionHeroku.md

---

core/play-java/src/test/java/play/mvc/RequestBuilderTest.java
core/play/src/main/scala/play/core/j/JavaHelpers.scala

I got this issue when working on another pull request 😞 
The problem is related to parsing query params from URI that contains a parameter with empty or no value.
**URI:** 
`/path?param=` or `/path?param`
**Expected result:**
`Map("param" -> List(""))`
**Actual result:**
`Map("param" -> List(null))`
In our codebase we already have a function that implement this parsing (`FormUrlEncodedParser.parse`) and also have a test for this cases https://github.com/playframework/playframework/blob/b295dc85da8deec73a2161707e69ca1a472390f4/core/play/src/test/scala/play/core/parsers/FormUrlEncodedParserSpec.scala#L31-L36

Fix `JavaHelpers.updateRequestWithUri`

---

dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/conf/application.conf
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty-channel-options/expected-application-log.txt
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-netty/src/test/scala/controllers/IntegrationTest.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/http-backend-pekko-http/src/test/scala/controllers/IntegrationTest.scala
documentation/manual/working/commonGuide/configuration/SettingsNetty.md
project/Dependencies.scala
transport/server/play-netty-server/src/main/resources/reference.conf
transport/server/play-netty-server/src/main/scala/play/core/server/NettyServer.scala

> _"Everyone using netty 4.1.x should be able to upgrade to 4.2.0.RC4 without any API breakage. The only new requirement is JDK8 or later."_
<br>
- https://netty.io/news/2024/06/12/4-2-0-Alpha1.html
- https://netty.io/news/2024/07/03/4-2-0-Alpha2.html
- https://netty.io/news/2024/08/26/4-2-0-Alpha3.html
- https://netty.io/news/2024/09/05/4-2-0-Alpha4.html
- https://netty.io/news/2024/11/04/4-2-0-Beta1.html
- https://netty.io/news/2024/12/11/4-2-0-RC1.html
- https://netty.io/news/2025/01/20/4-2-0-RC2.html
- https://netty.io/news/2025/02/11/4-2-0-RC3.html
- https://netty.io/news/2025/03/07/4-2-0-RC4.html
- https://netty.io/news/2025/04/03/4-2-0.html
- https://github.com/netty/netty/wiki/Netty-4.2-Migration-Guide

Netty 4.2.0 and adding io_uring native transport

---

build.sbt
dev-mode/gradle-plugin/build.gradle.kts
dev-mode/gradle-plugin/src/main/java/play/gradle/plugin/PlayRunPlugin.java

I think it's a very low-cost option to provide a Gradle plugin for users who are still using Akka and Play 2.9.x. 
We just need to build for JDK 11 the next modules:
* Play-Exceptions
* Play-Build-Link
* Play-Run-Support
* Play-Routes-Compiler
* Play Gradle Plugin

Gradle Plugin should be compatible with JDK 11

---

README.md

This updates the Informaticon logo in the README to use the proper image depending on light/dark mode, with a fallback to the light-mode image.
Implementation is based on [this post](https://github.blog/developer-skills/github/how-to-make-your-images-in-markdown-on-github-adjust-for-dark-mode-and-light-mode/) from the GitHub blog.
At the time of writing, the newly referenced image files are not yet available. The URLs assume that they'll be correct if the image files submitted in https://github.com/playframework/playframework.com/pull/618 will be made publicly available with a prefix of their MD5 checksum.

update informaticon logo in readme

---

core/play/src/main/scala/play/core/j/JavaAction.scala

See 
- #13281
This does not fix the problem but at least avoids the `ClassCastException`
When using `@With` directly on an action method, there simply is no configuration.
Even the "Simple Action" that is used [in the docs](https://www.playframework.com/documentation/3.0.x/JavaActionsComposition#Composing-actions) when using `@With` make that clear and uses `Void`
https://github.com/playframework/playframework/blob/cf19f573ee76356a6e62ab6bca1b8cac0a3326c2/core/play/src/main/java/play/mvc/Action.java#L50-L51
However, what the author in #13281 tries, even fails with a `ClassCastException` when using `Action.Simple` because also `Void` can not be cast to the desired type.

[3.0.x] Fix `ClassCastException` when using `@With` Java annotation

---

testkit/play-test/src/main/scala/play/api/test/Helpers.scala
testkit/play-test/src/test/scala/play/api/test/HelpersSpec.scala

Fixes #13271
Fix iterator for Cookies created via `play.api.test.Helpers.cookies`.
- Cookies.iterator: https://github.com/playframework/playframework/blob/3.0.x/core/play/src/main/scala/play/api/mvc/Cookie.scala#L206

Fix iterator for Cookies created via play.api.test.Helpers.cookies

---

core/play-integration-test/src/test/scala/play/it/http/PekkoRequestTimeoutSpec.scala

Fix pattern match exhaustivity warning in PekkoRequestTimeoutSpec
I fixed the following warning
```scala
[warn] /Users/toshi/work/github.com/playframework/playframework/core/play-integration-test/src/test/scala/play/it/http/PekkoRequestTimeoutSpec.scala:28:37: match may not be exhaustive.
[warn] It would fail on the following inputs: (_ : scala.concurrent.duration.Duration.Infinite#<local child>), FiniteDuration()
[warn]       def getTimeout(d: Duration) = d match {
[warn]                                     ^
[warn] one warning found
```

Fix pattern match exhaustivity warning in PekkoRequestTimeoutSpec

---

core/play-java/src/test/java/play/mvc/AttributesTest.java
core/play/src/main/java/play/mvc/Http.java

Same as 
- #13407
but for the Java API.
I thought Java's RequestHeader just passes through to the underlying Scala rh methods, but it turns out only for cookies, but not for Flash and Session.
The tests in the first commit I push should fail with:
```
[info] Test run play.mvc.AttributesTest started
[info] Test play.mvc.AttributesTest.testRequestHeader_emptyAttributesSession[0] started
[error] Test play.mvc.AttributesTest.testRequestHeader_emptyAttributesSession[0] failed: java.util.NoSuchElementException: key not found: Session, took 0.002 sec
[error]     at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:243)
[error]     at scala.collection.immutable.Map$EmptyMap$.apply(Map.scala:239)
[error]     at play.api.libs.typedmap.DefaultTypedMap.apply(TypedMap.scala:189)
[error]     at …
```

Make sure Java's Session and Flash always exists even if empty req attrs

---

transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala

The changed code is part of the [`resultConversionWithErrorHandling` method](https://github.com/playframework/playframework/blob/3.0.8/transport/server/play-server/src/main/scala/play/core/server/common/ServerResultUtils.scala#L159-L163). Obviously that code lives in `transport/server/` and is part of the backend servers and only gets called by 
- the [Netty backend's `NettyModelConversion`](https://github.com/playframework/playframework/blob/3.0.8/transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala#L168)
- the [Pekko HTTP's `PekkoModelConversion`](https://github.com/playframework/playframework/blob/3.0.8/transport/server/play-pekko-http-server/src/main/scala/play/core/server/pekkohttp/PekkoModelConversion.scala#L179)
When calling …

A call to `onClientError` from the server backend was missing the `HttpErrorInfo` attr

---

core/play-integration-test/src/test/scala/play/it/http/BadClientHandlingSpec.scala
core/play/src/main/scala/play/api/mvc/request/RequestFactory.scala
core/play/src/test/scala/play/api/mvc/RequestHeaderSpec.scala
transport/server/play-netty-server/src/main/scala/play/core/server/netty/NettyModelConversion.scala
transport/server/play-pekko-http-server/src/main/scala/play/core/server/pekkohttp/PekkoModelConversion.scala

Improvement thanks to
- #13406
Makes sure that calling `attrs(RequestAttrKey.Id)` always returns an id, even if the request was rejected by the server backend (before Play parses any headers to set the cookies, etc.)
https://github.com/playframework/playframework/blob/6a4473c5632c4b736be86a7d7990d2bc31bc2e18/core/play/src/main/scala/play/api/mvc/RequestHeader.scala#L40
Also in the light of 
- #13204
it makes a lot of sense to generate and set the request id as early as possible as #13204 will include a timestamp in the id.

Generate and set the request-id as early as possible

---

documentation/project/plugins.sbt
project/Dependencies.scala
project/PlaySbtBuildBase.scala
project/Versions.scala
project/plugins.sbt

Adds the ability to crossbuild plugins (without actually doing it in CI, explicitly)
Related to #12897.
* Updates to `sbt-twirl` % `2.1.0-M5` (which has crossbuild support)
* Adds sbt2 crossbuilds to default `PlaySbtBuildBase`
* Adds `sbt2` to sbt versions
Needs crossbuilds of the following plugins:
Edit: `+mimaReportBinaryIssues` fails with Scala3 in the crossbuild, so removing. Will follow up with a PR to fix Scala3 compile/format issues.

Add crossbuild support

---

dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala

_All_ tests pass with Java 25 final release candiate:
- #13490
- #13495
IMHO there is no reason why not declare it as supported.
History shows that the final RC of a Java release usually becomes the final release:
- [Java 21 final RC becomes final release](https://mail.openjdk.org/pipermail/jdk-dev/2023-September/008267.html)
- [Java 22 final RC becomes final release](https://mail.openjdk.org/pipermail/jdk-dev/2024-March/008827.html)
- [Java 23 final RC becomes final release](https://mail.openjdk.org/pipermail/jdk-dev/2024-September/009395.html)
- [Java 24 final RC becomes final release](https://mail.openjdk.org/pipermail/jdk-dev/2025-March/009843.html)
There are not P1 bugs reported yet: https://bugs.openjdk.org/issues/?filter=33410
Therefore it's very very likely to say nothing relevant …

[3.0.x] Declare Java 25 LTS officially supported

---

dev-mode/sbt-plugin/src/main/scala-2.12/play/sbt/PluginCompat.scala
dev-mode/sbt-plugin/src/main/scala-3/play/sbt/PluginCompat.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayInteractionMode.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlaySettings.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/routes/RoutesCompiler.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala

Towards #13319 
Lots of type compatibility issues/fixes. Notably:
* Adds uncached to several keys
* Maps `playDefaultRunTask` to Unit, because SBT's `run` is more strict on types. This one concerns me a bit.
* Removes some legacy console reader code for SBT < 1.3, the compilation errors weren't worth the trouble.
* Type conversions via shims
This is stacked on top of #13549, can safely rebase after that is merged.

Sbt2 compatibility cleanup

---

dev-mode/sbt-scripted-tools/src/main/scala/play/sbt/scriptedtools/ScriptedTools.scala

Towards #13319 
Several minor compatibility fixes for `sbt-scripted-tools`.
* `URL` is pruned from SBT 2.0, switch to `URI` and `uri()` calls
* `do {} while()` refactored to plain ol' `while`
* `uncached` and `Inc`/`Value` shims borrowed from Play-Sbt.
Note - this won't work in Scala3 until #13553 goes in - it references types in the scala-3 `PluginCompat` that aren't merged _yet_. The changes are isolated though, so safe to merge for now.

sbt 2 compatibility for sbt-scripted-tools

---

dev-mode/sbt-plugin/src/main/scala-2.12/play/sbt/PluginCompat.scala
dev-mode/sbt-plugin/src/main/scala-3/play/sbt/PluginCompat.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/PlayCommands.scala
dev-mode/sbt-plugin/src/main/scala/play/sbt/run/PlayReload.scala
dev-mode/sbt-plugin/src/main/scala/sbt/PlayRun.scala

Towards #13319 
Adds a shim for the changes to `runTask` in sbt 2.0. Clean up the PluginCompat shim.
`Project.runTask` was removed in SBT 2.0. This necessitated adding a shim to use other available `runTask` methods to achieve similar results.
This patch is not my favorite - it is currently a workaround to re-wrap task results in `Result` and `Option`, because sbt 2.0 does not give us access to the underlying `EvaluateTask` monadic results. This gives us a clean way to replace the shim once a better method is exposed in sbt 2.0. [sbt/sbt#8283](https://github.com/sbt/sbt/pull/8283) should make this a much cleaner shim.
Once this merges, we can start testing cross compatibility in scripted, and work towards publishing crossbuilds.

sbt 2 runTask compatibility

---

.github/workflows/build-test.yml
build.sbt
core/play-integration-test/src/test/java/play/it/JavaServerIntegrationTest.java
core/play-integration-test/src/test/scala/play/it/http/IdleTimeoutSpec.scala
core/play-integration-test/src/test/scala/play/it/test/NettyServerEndpointRecipes.scala
core/play-integration-test/src/test/scala/play/it/test/PekkoHttpServerEndpointRecipes.scala
dev-mode/sbt-plugin/src/sbt-test/play-sbt-plugin/generated-keystore/test
documentation/manual/working/commonGuide/production/ConfiguringHttps.md
project/BuildSettings.scala
project/Dependencies.scala
testkit/play-test/src/test/java/play/test/TestServerTest.java
transport/client/play-ahc-ws/src/main/scala/play/api/libs/ws/ahc/AhcWSClient.scala
transport/server/play-server/src/main/scala/play/core/server/SelfSigned.scala
transport/server/play-server/src/main/scala/play/core/server/ssl/DefaultSSLEngineProvider.scala
transport/server/play-server/src/main/scala/play/core/server/ssl/FakeKeyStore.scala
transport/server/play-server/src/main/scala/play/core/server/ssl/FakeSSLTools.scala
transport/server/play-server/src/test/scala/play/core/server/ssl/ServerSSLEngineSpec.scala

- Fixes https://github.com/playframework/playframework/issues/13234
Until now, we used ssl-config's `FakeKeyStore` class to generate self signed certificates for dev mode and for testing. The classes in `sun.security.x509` which are used to generate a self signed certificate are actually internal Java code (which they use for their `keytool` command line tool as I understood). Because of [JEP 403](https://openjdk.org/jeps/403) Java strongly encapsulates JDK internals as of Java 17, meaning there is no other way to access that code but to add `--add-exports=java.base/sun.security.x509=ALL-UNNAMED"` (or using a specific module name if we would use one) to the `java` command.
With Java 20 (or 19 or 18, not sure) that internal code even changed - which of course [fails …

Avoid internal `sun.security.x509` / `--add-exports`
